// Auto-authored disease data — group g1 (Cardiology, Cardiac & Thoracic Surgery,
// Vascular Surgery, Emergency Medicine). Patient-facing SEO content for MedDroid.
// Educational only — not a diagnosis. No specific drug names/doses.

export default [
  // ===================== CARDIOLOGY (18) =====================
  {
    slug: 'coronary-artery-disease',
    name: 'Coronary Artery Disease (CAD)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A build-up of fatty plaque narrows the arteries that supply blood to the heart muscle. It is the most common heart disease and can lead to angina or a heart attack.',
    causes: [
      'High cholesterol and fatty plaque (atherosclerosis)',
      'High blood pressure',
      'Smoking and tobacco use',
      'Diabetes and high blood sugar',
      'Obesity and lack of physical activity',
      'Family history of early heart disease',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Chest pain or tightness (angina)'],
      ['symptoms/shortness-of-breath', 'Shortness of breath'],
      ['symptoms/fatigue', 'Fatigue on exertion'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      [null, 'Pain spreading to arm, jaw or back'],
      ['symptoms/dizziness', 'Dizziness'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      ['blood-tests/troponin', 'Troponin (if suspected attack)'],
      [null, 'Echocardiogram'],
      [null, 'Treadmill / stress test'],
      [null, 'Coronary angiography'],
    ],
    treatment: [
      'Lifestyle changes: quit smoking, healthy diet, regular exercise, weight control',
      'Medicines to lower cholesterol (statins), control BP and prevent clots (blood thinners)',
      'Controlling diabetes and blood pressure tightly',
      'Angioplasty with a stent to open blocked arteries',
      'Bypass surgery (CABG) for severe multi-vessel disease',
    ],
    whenToSee: [
      'Call your local emergency number now for chest pain lasting more than a few minutes or with sweating and breathlessness',
      'See a doctor for chest tightness that comes on with exertion',
      'Get urgent care if breathlessness or fatigue is worsening',
    ],
    faqs: [
      { q: 'Can coronary artery disease be reversed?', a: 'Plaque cannot usually be fully removed, but healthy lifestyle and treatment can slow or halt progression and greatly lower the risk of a heart attack.' },
      { q: 'Is CAD hereditary?', a: 'A family history of early heart disease raises risk, but lifestyle and conditions like diabetes and high BP play a large role too.' },
    ],
  },
  {
    slug: 'hypertension',
    name: 'Hypertension (High Blood Pressure)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Persistently high pressure inside the arteries. It often has no symptoms but silently damages the heart, brain, kidneys and eyes over time.',
    causes: [
      'Age and family history',
      'High salt intake',
      'Obesity and lack of exercise',
      'Excess alcohol and smoking',
      'Long-term stress',
      'Kidney or hormonal disorders (secondary causes)',
    ],
    symptoms: [
      [null, 'Often no symptoms ("silent killer")'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/dizziness', 'Dizziness'],
      ['symptoms/blurred-vision', 'Blurred vision'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
    ],
    tests: [
      [null, 'Repeated blood pressure readings'],
      ['ecg-explained', 'ECG'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function test'],
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      [null, 'Echocardiogram'],
    ],
    treatment: [
      'Reduce salt, eat more fruit and vegetables, and lose excess weight',
      'Regular exercise and limiting alcohol',
      'Stop smoking',
      'Blood-pressure-lowering medicines when lifestyle alone is not enough',
      'Regular home monitoring and follow-up',
    ],
    whenToSee: [
      'Seek emergency care for a very high reading with chest pain, severe headache, breathlessness or weakness on one side',
      'See a doctor if home readings stay high despite treatment',
      'Get checked at least yearly even if you feel well',
    ],
    faqs: [
      { q: 'What is a normal blood pressure?', a: 'Around 120/80 mmHg is considered normal for most adults; your doctor sets your personal target.' },
      { q: 'Do I need medicine for life?', a: 'Many people do, but some can reduce doses with strong lifestyle changes. Never stop medicine on your own.' },
    ],
  },
  {
    slug: 'heart-failure',
    name: 'Heart Failure',
    dept: ['cardiology', 'Cardiology'],
    lede: 'The heart becomes too weak or stiff to pump blood effectively, so fluid backs up in the lungs and body. It is a long-term condition that can be managed.',
    causes: [
      'Previous heart attack or coronary artery disease',
      'Long-standing high blood pressure',
      'Heart valve disease',
      'Cardiomyopathy (heart muscle disease)',
      'Uncontrolled diabetes',
      'Excess alcohol or certain infections',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness, worse lying flat'],
      ['symptoms/leg-swelling', 'Swollen ankles and legs'],
      ['symptoms/fatigue', 'Tiredness and weakness'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/cough', 'Persistent cough or wheeze'],
      [null, 'Sudden weight gain from fluid'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Echocardiogram'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'BNP / NT-proBNP blood test'],
    ],
    treatment: [
      'Limit salt and fluid as advised; weigh yourself daily',
      'Medicines to remove excess fluid (diuretics) and ease strain on the heart',
      'Treat the underlying cause (blocked arteries, valves, BP)',
      'Devices such as pacemakers or defibrillators in selected patients',
      'Cardiac rehabilitation and gradual exercise',
    ],
    whenToSee: [
      'Call emergency services for severe breathlessness, blue lips or chest pain',
      'See your doctor for rapid weight gain or worsening leg swelling',
      'Get urgent review if you cannot lie flat to sleep',
    ],
    faqs: [
      { q: 'Does heart failure mean my heart is about to stop?', a: 'No. It means the heart is not pumping as well as it should. Many people live for years with the right treatment.' },
      { q: 'Why do I need to weigh myself daily?', a: 'A sudden gain often signals fluid build-up, so treatment can be adjusted early.' },
    ],
  },
  {
    slug: 'atrial-fibrillation',
    name: 'Atrial Fibrillation (AFib)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A common irregular and often fast heart rhythm. It can cause palpitations and, importantly, raises the risk of stroke from clots forming in the heart.',
    causes: [
      'High blood pressure',
      'Coronary artery disease or heart failure',
      'Heart valve disease',
      'Overactive thyroid',
      'Excess alcohol or caffeine',
      'Ageing and diabetes',
    ],
    symptoms: [
      ['symptoms/heart-palpitations', 'Palpitations or fluttering'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/dizziness', 'Dizziness'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/fainting', 'Fainting (less common)'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Holter / 24-hour monitor'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function'],
      [null, 'Echocardiogram'],
      ['blood-tests/electrolytes', 'Electrolytes'],
    ],
    treatment: [
      'Blood thinners to lower stroke risk when needed',
      'Medicines to control heart rate or restore normal rhythm',
      'Cardioversion (a controlled electric shock) in selected cases',
      'Catheter ablation for suitable patients',
      'Treating triggers such as thyroid problems and alcohol',
    ],
    whenToSee: [
      'Call emergency services for palpitations with chest pain, severe breathlessness or fainting',
      'See a doctor promptly if you notice a new irregular or racing pulse',
      'Seek urgent care for sudden weakness, slurred speech or face droop (stroke signs)',
    ],
    faqs: [
      { q: 'Why does AFib cause strokes?', a: 'The irregular beat lets blood pool and clot in the heart; a clot can travel to the brain. Blood thinners lower this risk.' },
      { q: 'Is AFib dangerous?', a: 'It is usually manageable, but untreated it raises stroke and heart-failure risk, so it should be assessed.' },
    ],
  },
  {
    slug: 'cardiac-arrhythmia',
    name: 'Cardiac Arrhythmia (Irregular Heartbeat)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Any problem with the rate or rhythm of the heartbeat — too fast, too slow, or irregular. Many are harmless but some need treatment.',
    causes: [
      'Heart disease or previous heart attack',
      'Electrolyte imbalance',
      'Thyroid disorders',
      'Excess caffeine, alcohol or stimulants',
      'Certain medicines',
      'Genetic rhythm disorders',
    ],
    symptoms: [
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/dizziness', 'Dizziness'],
      ['symptoms/fainting', 'Fainting or near-fainting'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Holter monitor'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function'],
      [null, 'Echocardiogram'],
    ],
    treatment: [
      'Cutting caffeine, alcohol and stimulants that trigger it',
      'Correcting electrolyte or thyroid problems',
      'Rhythm- or rate-controlling medicines',
      'Pacemaker for very slow rhythms',
      'Ablation or an implanted defibrillator in selected cases',
    ],
    whenToSee: [
      'Call emergency services for fainting, chest pain or severe breathlessness with an irregular beat',
      'See a doctor for new, frequent or prolonged palpitations',
      'Seek care if a slow pulse causes tiredness or blackouts',
    ],
    faqs: [
      { q: 'Are palpitations always serious?', a: 'No, occasional skipped beats are common and often harmless, but recurring or symptomatic ones should be checked.' },
      { q: 'Can stress cause arrhythmia?', a: 'Stress, caffeine and lack of sleep can trigger palpitations in many people.' },
    ],
  },
  {
    slug: 'angina',
    name: 'Angina (Heart-Related Chest Pain)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Chest pain or pressure caused by reduced blood flow to the heart muscle, usually from narrowed arteries. It is a warning sign, not a heart attack itself.',
    causes: [
      'Coronary artery disease (narrowed arteries)',
      'Physical exertion or emotional stress',
      'Cold weather',
      'Heavy meals',
      'Smoking, high cholesterol and diabetes',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Chest tightness or pressure'],
      [null, 'Pain spreading to arm, neck or jaw'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue with activity'],
      [null, 'Discomfort eased by rest'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Treadmill / stress test'],
      ['blood-tests/troponin', 'Troponin'],
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      [null, 'Coronary angiography'],
    ],
    treatment: [
      'Rest and avoiding known triggers',
      'Medicines that relax and widen blood vessels',
      'Cholesterol- and BP-lowering medicines and blood thinners',
      'Angioplasty with stenting or bypass surgery when severe',
      'Lifestyle changes: quit smoking, exercise, healthy diet',
    ],
    whenToSee: [
      'Call emergency services if chest pain lasts more than a few minutes or does not ease with rest',
      'See a doctor if angina becomes more frequent or occurs at rest',
      'Seek urgent care for chest pain with sweating, nausea or breathlessness',
    ],
    faqs: [
      { q: 'How is angina different from a heart attack?', a: 'Angina is temporary pain from reduced blood flow that eases with rest; a heart attack is a blocked artery causing lasting damage and needs emergency care.' },
      { q: 'Can angina be treated without surgery?', a: 'Many people are managed with medicines and lifestyle changes; procedures are used when symptoms are severe or arteries are badly blocked.' },
    ],
  },
  {
    slug: 'cardiomyopathy',
    name: 'Cardiomyopathy (Heart Muscle Disease)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A disease of the heart muscle that makes it enlarged, thickened or stiff, so the heart pumps less effectively. Some forms run in families.',
    causes: [
      'Genetic / inherited conditions',
      'Long-standing high blood pressure',
      'Previous heart attack',
      'Excess alcohol',
      'Viral infections of the heart',
      'Sometimes no clear cause',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/leg-swelling', 'Leg and ankle swelling'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/fainting', 'Fainting'],
      ['symptoms/chest-pain', 'Chest discomfort'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['mri-scan-explained', 'Cardiac MRI'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests'],
      [null, 'Genetic testing (selected cases)'],
    ],
    treatment: [
      'Medicines to ease the heart workload and control rhythm',
      'Treating the cause where possible (BP, alcohol, infection)',
      'Implanted devices such as defibrillators in high-risk patients',
      'Limiting strenuous activity if advised',
      'Heart transplant in advanced cases',
    ],
    whenToSee: [
      'Call emergency services for fainting, severe breathlessness or chest pain',
      'See a cardiologist if you have a family history and any heart symptoms',
      'Get checked for unexplained breathlessness or swelling',
    ],
    faqs: [
      { q: 'Is cardiomyopathy inherited?', a: 'Some types are; close relatives may be advised to get screened.' },
      { q: 'Can I exercise with cardiomyopathy?', a: 'Light activity is often fine, but competitive or intense exercise may need to be limited — always follow your cardiologist advice.' },
    ],
  },
  {
    slug: 'heart-valve-disease',
    name: 'Heart Valve Disease',
    dept: ['cardiology', 'Cardiology'],
    lede: 'One or more of the heart valves becomes narrowed (stenosis) or leaky (regurgitation), forcing the heart to work harder. In India it is often linked to past rheumatic fever.',
    causes: [
      'Rheumatic fever in childhood',
      'Age-related wear and calcification',
      'Congenital (present from birth) valve defects',
      'Infection of the heart valves (endocarditis)',
      'Damage after a heart attack',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/leg-swelling', 'Swollen ankles'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/fainting', 'Fainting'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Heart murmur on examination'],
      [null, 'Cardiac catheterisation (selected cases)'],
    ],
    treatment: [
      'Regular monitoring for mild disease',
      'Medicines to relieve symptoms and control rhythm',
      'Valve repair surgery when possible',
      'Valve replacement (mechanical or tissue) for severe disease',
      'Less-invasive valve procedures (such as TAVI) in selected patients',
    ],
    whenToSee: [
      'Call emergency services for severe breathlessness, chest pain or fainting',
      'See a cardiologist if a murmur is found or symptoms appear',
      'Report any history of rheumatic fever to your doctor',
    ],
    faqs: [
      { q: 'Do all valve problems need surgery?', a: 'No. Mild disease is often just monitored; surgery is considered when the valve is severely affected or causing symptoms.' },
      { q: 'What is rheumatic heart disease?', a: 'Valve damage caused by rheumatic fever after a throat infection — still common in India and preventable with early antibiotic treatment of strep throat.' },
    ],
  },
  {
    slug: 'congenital-heart-disease',
    name: 'Congenital Heart Disease',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Structural heart problems present from birth, ranging from small holes that close on their own to complex defects needing surgery.',
    causes: [
      'Problems in heart development before birth',
      'Genetic conditions (such as Down syndrome)',
      'Infections during pregnancy (such as rubella)',
      'Certain medicines, alcohol or diabetes in pregnancy',
      'Often no identifiable cause',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      [null, 'Bluish lips or skin in babies'],
      ['symptoms/fatigue', 'Tiring easily / poor feeding'],
      [null, 'Poor growth in children'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      [null, 'Heart murmur'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Pulse oximetry (oxygen level)'],
      [null, 'Cardiac MRI or catheterisation'],
    ],
    treatment: [
      'Regular monitoring for small defects',
      'Medicines to support the heart and manage symptoms',
      'Catheter-based procedures to close holes or open valves',
      'Corrective or staged surgery for complex defects',
      'Lifelong follow-up with a cardiologist',
    ],
    whenToSee: [
      'Seek emergency care if a baby turns blue, breathes very fast or feeds very poorly',
      'See a paediatric cardiologist if a murmur or poor growth is noted',
      'Continue follow-up into adulthood even after childhood repair',
    ],
    faqs: [
      { q: 'Can congenital heart defects be cured?', a: 'Many can be fully repaired, especially when found early; others are managed lifelong.' },
      { q: 'Can adults have congenital heart disease?', a: 'Yes — some defects are mild and only found in adulthood, and repaired patients need ongoing follow-up.' },
    ],
  },
  {
    slug: 'rheumatic-heart-disease',
    name: 'Rheumatic Heart Disease',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Permanent heart valve damage caused by rheumatic fever, which can follow an untreated strep throat infection. It remains common in India and is preventable.',
    causes: [
      'Rheumatic fever after streptococcal throat infection',
      'Untreated or repeated strep infections in childhood',
      'Poor access to early antibiotics',
      'Crowded living conditions',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/joint-pain', 'Joint pain (during rheumatic fever)'],
      ['symptoms/leg-swelling', 'Ankle swelling'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['blood-tests/esr', 'ESR'],
      ['blood-tests/crp', 'CRP'],
      [null, 'ASO titre / throat swab'],
    ],
    treatment: [
      'Long-term preventive antibiotics to stop recurrence',
      'Medicines for heart failure and rhythm problems',
      'Blood thinners for certain valve or rhythm problems',
      'Valve repair or replacement for severe damage',
      'Prompt treatment of strep throat to prevent it',
    ],
    whenToSee: [
      'Call emergency services for severe breathlessness, chest pain or fainting',
      'See a doctor for known valve disease with worsening symptoms',
      'Treat a sore throat with fever promptly, especially in children',
    ],
    faqs: [
      { q: 'How can rheumatic heart disease be prevented?', a: 'By treating strep throat early with antibiotics and taking preventive antibiotics after rheumatic fever.' },
      { q: 'Is it common in India?', a: 'Yes, it remains an important cause of heart disease in young people in India and other developing regions.' },
    ],
  },
  {
    slug: 'infective-endocarditis',
    name: 'Infective Endocarditis',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A serious infection of the inner lining of the heart or its valves, usually by bacteria in the bloodstream. It needs prompt treatment.',
    causes: [
      'Bacteria entering the blood (dental work, infections, IV drug use)',
      'Damaged or artificial heart valves',
      'Congenital heart defects',
      'Weakened immune system',
      'Indwelling catheters or devices',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever and chills'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/night-sweats', 'Night sweats'],
      ['symptoms/unexplained-weight-loss', 'Weight loss'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/joint-pain', 'Joint or muscle aches'],
    ],
    tests: [
      [null, 'Blood cultures'],
      [null, 'Echocardiogram'],
      ['blood-tests/complete-blood-count-cbc', 'Complete blood count'],
      ['blood-tests/crp', 'CRP'],
      ['blood-tests/esr', 'ESR'],
    ],
    treatment: [
      'A prolonged course of intravenous antibiotics in hospital',
      'Close monitoring of the heart valves',
      'Surgery to repair or replace badly damaged valves',
      'Treating the source of infection',
      'Preventive antibiotics for high-risk patients before some procedures',
    ],
    whenToSee: [
      'Seek urgent care for prolonged unexplained fever, especially with a known valve problem',
      'Call emergency services for sudden breathlessness, weakness or stroke signs',
      'See a doctor for persistent fever after dental or surgical procedures',
    ],
    faqs: [
      { q: 'Who is at risk of endocarditis?', a: 'People with damaged or artificial valves, congenital heart defects or weakened immunity are at higher risk.' },
      { q: 'Is it life-threatening?', a: 'It can be if untreated, but early antibiotics and, when needed, surgery are usually effective.' },
    ],
  },
  {
    slug: 'pericarditis',
    name: 'Pericarditis',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Inflammation of the sac around the heart (the pericardium), often causing sharp chest pain. Most cases are viral and settle with treatment.',
    causes: [
      'Viral infections',
      'Bacterial infections including tuberculosis',
      'Autoimmune diseases',
      'After a heart attack or heart surgery',
      'Kidney failure',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Sharp chest pain, worse lying down'],
      [null, 'Pain eased by sitting forward'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fever', 'Low-grade fever'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/fatigue', 'Fatigue'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Echocardiogram'],
      ['blood-tests/crp', 'CRP'],
      ['blood-tests/esr', 'ESR'],
      ['x-ray-explained', 'Chest X-ray'],
    ],
    treatment: [
      'Rest and anti-inflammatory medicines',
      'Treating the underlying cause (infection, autoimmune disease)',
      'Medicines to reduce the chance of recurrence',
      'Draining fluid if a large collection builds up',
      'Hospital care for severe or complicated cases',
    ],
    whenToSee: [
      'Call emergency services for severe chest pain, fainting or very low blood pressure',
      'See a doctor for chest pain that changes with position or breathing',
      'Seek care for chest pain with fever or breathlessness',
    ],
    faqs: [
      { q: 'How is pericarditis pain different?', a: 'It is often sharp, worse when lying flat or breathing in, and eased by sitting forward — but any chest pain should be assessed.' },
      { q: 'Does it come back?', a: 'It can recur in some people; medicines are used to lower that risk.' },
    ],
  },
  {
    slug: 'high-cholesterol',
    name: 'High Cholesterol (Dyslipidemia)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Raised levels of harmful fats in the blood that build up in artery walls and increase the risk of heart attack and stroke. It usually causes no symptoms.',
    causes: [
      'Diet high in saturated and trans fats',
      'Obesity and lack of exercise',
      'Smoking and excess alcohol',
      'Diabetes and thyroid problems',
      'Family history (inherited high cholesterol)',
    ],
    symptoms: [
      [null, 'Usually no symptoms'],
      [null, 'Fatty deposits around eyes or tendons (in severe cases)'],
      ['symptoms/chest-pain', 'Chest pain if arteries narrow'],
    ],
    tests: [
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function'],
      ['blood-tests/liver-function-test-lft', 'Liver function'],
    ],
    treatment: [
      'Healthy diet low in saturated fat, more fibre and vegetables',
      'Regular exercise and weight loss',
      'Stop smoking and limit alcohol',
      'Cholesterol-lowering medicines (statins) when needed',
      'Treating diabetes and other risk factors',
    ],
    whenToSee: [
      'See a doctor to get your cholesterol checked, especially with a family history',
      'Get urgent care for chest pain or stroke-like symptoms',
      'Discuss medicines if lifestyle changes are not enough',
    ],
    faqs: [
      { q: 'Is all cholesterol bad?', a: 'No — LDL is the harmful type, while HDL is protective. The balance and total level both matter.' },
      { q: 'Can thin people have high cholesterol?', a: 'Yes, especially with an inherited form or unhealthy diet, so screening is useful for everyone.' },
    ],
  },
  {
    slug: 'heart-block',
    name: 'Heart Block (Slow Heart Rhythm)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A delay or block in the electrical signals that control the heartbeat, which can make the heart beat too slowly. Some forms need a pacemaker.',
    causes: [
      'Ageing and wear of the electrical system',
      'Previous heart attack',
      'Heart muscle or valve disease',
      'Certain medicines',
      'Congenital (present from birth)',
    ],
    symptoms: [
      ['symptoms/dizziness', 'Dizziness'],
      ['symptoms/fainting', 'Fainting or blackouts'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/heart-palpitations', 'Slow or irregular pulse'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Holter monitor'],
      [null, 'Echocardiogram'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function'],
    ],
    treatment: [
      'Reviewing and adjusting medicines that slow the heart',
      'Treating reversible causes',
      'A permanent pacemaker for significant block',
      'Monitoring for mild, symptom-free cases',
    ],
    whenToSee: [
      'Call emergency services for fainting, severe dizziness or a very slow pulse',
      'See a doctor for repeated blackouts or unexplained tiredness',
      'Seek care if a very slow heart rate is noticed',
    ],
    faqs: [
      { q: 'Does heart block always need a pacemaker?', a: 'No — mild first-degree block often needs only monitoring, but higher-degree block causing symptoms usually needs a pacemaker.' },
      { q: 'Is a pacemaker safe?', a: 'Pacemaker implantation is a common, well-established and generally safe procedure.' },
    ],
  },
  {
    slug: 'supraventricular-tachycardia',
    name: 'Supraventricular Tachycardia (SVT)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'Episodes of a very fast heart rate starting in the upper chambers of the heart. They can be alarming but are usually not life-threatening.',
    causes: [
      'Extra electrical pathways in the heart',
      'Caffeine, alcohol or stimulants',
      'Stress or lack of sleep',
      'Thyroid problems',
      'Sometimes no clear trigger',
    ],
    symptoms: [
      ['symptoms/heart-palpitations', 'Sudden rapid palpitations'],
      ['symptoms/dizziness', 'Dizziness'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fainting', 'Fainting (occasionally)'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      [null, 'Holter / event monitor'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function'],
      ['blood-tests/electrolytes', 'Electrolytes'],
    ],
    treatment: [
      'Simple vagal manoeuvres to slow the heart during an episode',
      'Avoiding caffeine and other triggers',
      'Medicines to control or prevent episodes',
      'Catheter ablation, which can cure many cases',
    ],
    whenToSee: [
      'Call emergency services for palpitations with fainting, chest pain or severe breathlessness',
      'See a cardiologist for recurrent racing-heart episodes',
      'Learn vagal manoeuvres from your doctor for short episodes',
    ],
    faqs: [
      { q: 'Is SVT dangerous?', a: 'For most people it is not life-threatening, but frequent or severe episodes should be treated.' },
      { q: 'Can SVT be cured?', a: 'Catheter ablation cures the majority of suitable cases.' },
    ],
  },
  {
    slug: 'pulmonary-hypertension',
    name: 'Pulmonary Hypertension',
    dept: ['cardiology', 'Cardiology'],
    lede: 'High blood pressure in the arteries of the lungs, which strains the right side of the heart. It causes breathlessness and needs specialist care.',
    causes: [
      'Long-standing lung disease',
      'Left-sided heart or valve disease',
      'Blood clots in the lungs',
      'Certain congenital heart defects',
      'Connective tissue diseases',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness on exertion'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/leg-swelling', 'Leg swelling'],
      ['symptoms/fainting', 'Fainting'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/dizziness', 'Dizziness'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Right heart catheterisation'],
      [null, 'Lung function tests'],
    ],
    treatment: [
      'Treating the underlying lung or heart cause',
      'Medicines that relax the lung blood vessels (specialist use)',
      'Oxygen therapy when needed',
      'Diuretics for fluid overload',
      'Managing blood clots with blood thinners where relevant',
    ],
    whenToSee: [
      'Call emergency services for fainting or severe sudden breathlessness',
      'See a doctor for unexplained, worsening breathlessness on exertion',
      'Seek review for leg swelling with breathlessness',
    ],
    faqs: [
      { q: 'Is pulmonary hypertension the same as normal high blood pressure?', a: 'No — it affects the lung arteries specifically and needs different, specialist treatment.' },
      { q: 'Can it be treated?', a: 'It cannot always be cured, but treatment can improve symptoms and slow progression.' },
    ],
  },
  {
    slug: 'mitral-valve-prolapse',
    name: 'Mitral Valve Prolapse',
    dept: ['cardiology', 'Cardiology'],
    lede: 'A common, usually harmless condition where the mitral valve bulges slightly as the heart beats. Most people have no symptoms and need no treatment.',
    causes: [
      'Often present from birth',
      'Connective tissue differences',
      'Family tendency',
      'Sometimes linked to other heart conditions',
    ],
    symptoms: [
      [null, 'Often no symptoms'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      ['symptoms/chest-pain', 'Atypical chest discomfort'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/dizziness', 'Dizziness'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      [null, 'Heart murmur / click on examination'],
    ],
    treatment: [
      'Reassurance and monitoring for most people',
      'Reducing caffeine if it triggers palpitations',
      'Medicines only if symptoms are troublesome',
      'Valve repair or replacement in the rare severe leak',
    ],
    whenToSee: [
      'See a cardiologist if you have palpitations or chest discomfort',
      'Call emergency services for fainting or severe breathlessness',
      'Get periodic echocardiograms if a significant leak is found',
    ],
    faqs: [
      { q: 'Is mitral valve prolapse serious?', a: 'For most people it is mild and harmless; only a small number develop a significant leak needing treatment.' },
      { q: 'Can I exercise with it?', a: 'Yes, usually normally — your cardiologist will advise if any limits apply.' },
    ],
  },

  {
    slug: 'aortic-stenosis',
    name: 'Aortic Stenosis (Narrowed Aortic Valve)',
    dept: ['cardiology', 'Cardiology'],
    lede: 'The main outflow valve of the heart becomes narrowed, so the heart must work harder to push blood to the body. It is common in older adults and can cause fainting and breathlessness.',
    causes: [
      'Age-related calcium build-up on the valve',
      'Rheumatic heart disease',
      'A bicuspid (two-flap) valve present from birth',
      'High cholesterol and calcium deposits',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Chest pain on exertion'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fainting', 'Fainting, especially with activity'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/heart-palpitations', 'Palpitations'],
      [null, 'Heart murmur'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Cardiac catheterisation (selected cases)'],
    ],
    treatment: [
      'Regular monitoring for mild disease',
      'Managing blood pressure and other risk factors',
      'Valve replacement surgery for severe disease',
      'Catheter-based valve replacement (TAVI) in selected patients',
      'Avoiding strenuous exertion if advised',
    ],
    whenToSee: [
      'Call emergency services for fainting, severe chest pain or breathlessness',
      'See a cardiologist if a murmur is found or symptoms appear',
      'Report fainting with exertion promptly — it can be a warning sign',
    ],
    faqs: [
      { q: 'Is aortic stenosis serious?', a: 'Severe stenosis with symptoms is serious and usually needs valve replacement, but mild cases are simply monitored.' },
      { q: 'Can medicines cure a narrowed valve?', a: 'No medicine reopens the valve; severe cases need surgical or catheter valve replacement.' },
    ],
  },

  // ============ CARDIAC & THORACIC SURGERY (10) ============
  {
    slug: 'coronary-artery-bypass-graft',
    name: 'Coronary Artery Bypass Graft (CABG)',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Open-heart surgery that reroutes blood around severely blocked heart arteries using a healthy vessel from elsewhere in the body. Often called bypass surgery.',
    causes: [
      'Severe multi-vessel coronary artery disease',
      'Blockages not suitable for angioplasty',
      'Left main artery disease',
      'Ongoing angina despite medicines',
      'Blockage found after a heart attack',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Angina before surgery'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Reduced exercise capacity'],
    ],
    tests: [
      [null, 'Coronary angiography'],
      ['ecg-explained', 'ECG'],
      [null, 'Echocardiogram'],
      ['blood-tests/complete-blood-count-cbc', 'Pre-operative blood tests'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
    ],
    treatment: [
      'Surgery to graft healthy vessels around the blockages',
      'Can be done with or without the heart-lung machine',
      'Hospital recovery followed by cardiac rehabilitation',
      'Continued medicines for cholesterol, BP and clot prevention',
      'Lifestyle changes to protect the new grafts',
    ],
    whenToSee: [
      'Call emergency services for chest pain, fever or wound problems after surgery',
      'See your surgeon for breathlessness or swelling during recovery',
      'Seek urgent care for palpitations or fainting after discharge',
    ],
    faqs: [
      { q: 'How long is recovery after bypass surgery?', a: 'Most people recover over 6 to 12 weeks, with cardiac rehabilitation helping return to activity.' },
      { q: 'Will the blockages come back?', a: 'Grafts can narrow over time, so medicines and a healthy lifestyle are important to keep them open.' },
    ],
  },
  {
    slug: 'heart-valve-replacement',
    name: 'Heart Valve Replacement Surgery',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Surgery to replace a badly damaged heart valve with a mechanical or tissue valve when repair is not possible. It restores normal blood flow through the heart.',
    causes: [
      'Severe valve narrowing (stenosis)',
      'Severe valve leakage (regurgitation)',
      'Rheumatic valve damage',
      'Infected valve (endocarditis)',
      'Congenital valve defects',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Fatigue'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/leg-swelling', 'Leg swelling'],
      ['symptoms/fainting', 'Fainting'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      [null, 'Coronary angiography'],
      ['blood-tests/complete-blood-count-cbc', 'Pre-operative blood tests'],
      ['blood-tests/pt-inr', 'PT/INR (for mechanical valves)'],
    ],
    treatment: [
      'Mechanical valve (durable, needs lifelong blood thinners)',
      'Tissue valve (fewer blood thinners, may wear out sooner)',
      'Minimally invasive or catheter-based replacement (such as TAVI) in selected patients',
      'Cardiac rehabilitation after surgery',
      'Regular follow-up and, for mechanical valves, INR monitoring',
    ],
    whenToSee: [
      'Call emergency services for chest pain, fever or sudden breathlessness after surgery',
      'See your doctor for unusual bleeding if on blood thinners',
      'Report fever or new murmurs promptly (possible valve infection)',
    ],
    faqs: [
      { q: 'Mechanical or tissue valve — which is better?', a: 'Mechanical valves last longer but need lifelong blood thinners; tissue valves need fewer but may wear out. The choice depends on age and lifestyle.' },
      { q: 'Do I need antibiotics before dental work?', a: 'Many valve patients do, to prevent valve infection — check with your cardiologist.' },
    ],
  },
  {
    slug: 'thoracic-aortic-aneurysm',
    name: 'Thoracic Aortic Aneurysm',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'A bulge in the wall of the main artery (aorta) in the chest. It often has no symptoms but can be dangerous if it grows large or tears.',
    causes: [
      'High blood pressure',
      'Atherosclerosis (hardened arteries)',
      'Inherited connective tissue disorders',
      'Bicuspid aortic valve',
      'Ageing and smoking',
    ],
    symptoms: [
      [null, 'Often no symptoms'],
      ['symptoms/chest-pain', 'Chest or upper back pain'],
      ['symptoms/back-pain', 'Back pain'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/cough', 'Cough or hoarseness'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT scan of the aorta'],
      [null, 'Echocardiogram'],
      ['mri-scan-explained', 'MRI'],
    ],
    treatment: [
      'Strict blood pressure control',
      'Stopping smoking',
      'Regular scans to watch the size',
      'Surgery to repair or replace the aorta if large or growing',
      'Stent-graft (endovascular) repair in selected cases',
    ],
    whenToSee: [
      'Call emergency services for sudden severe chest or back pain (possible tear)',
      'See a doctor for a known aneurysm that is enlarging',
      'Report a family history of aortic disease to your doctor',
    ],
    faqs: [
      { q: 'When does an aneurysm need surgery?', a: 'Usually when it reaches a certain size or grows quickly, as the risk of tearing then rises.' },
      { q: 'Can I prevent it getting worse?', a: 'Controlling blood pressure, not smoking and regular monitoring all help.' },
    ],
  },
  {
    slug: 'congenital-heart-surgery',
    name: 'Congenital Heart Defect Surgery',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Surgery to correct structural heart defects present from birth, such as holes between chambers or narrowed vessels. Timing depends on the specific defect.',
    causes: [
      'Holes in the heart (septal defects)',
      'Narrowed or misconnected vessels',
      'Faulty or missing valves',
      'Complex combined defects',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      [null, 'Bluish skin in babies'],
      ['symptoms/fatigue', 'Tiring easily'],
      [null, 'Poor growth or feeding'],
      [null, 'Heart murmur'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      ['ecg-explained', 'ECG'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Cardiac MRI or catheterisation'],
    ],
    treatment: [
      'Catheter-based closure of some holes',
      'Open-heart surgery to repair defects',
      'Staged operations for complex defects',
      'Lifelong follow-up with a cardiologist',
      'Medicines to support the heart before or after surgery',
    ],
    whenToSee: [
      'Seek emergency care if a baby turns blue or breathes very fast',
      'See a paediatric cardiologist for poor growth or a murmur',
      'Keep long-term follow-up even after a successful repair',
    ],
    faqs: [
      { q: 'Is congenital heart surgery safe?', a: 'Outcomes have improved greatly, and many defects are repaired successfully, though risk depends on the specific defect.' },
      { q: 'Will my child live a normal life?', a: 'Many children do very well after repair, though some need ongoing monitoring.' },
    ],
  },
  {
    slug: 'heart-transplant',
    name: 'Heart Transplant',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Surgery to replace a failing heart with a healthy donor heart. It is considered for end-stage heart failure when other treatments no longer work.',
    causes: [
      'End-stage heart failure',
      'Severe cardiomyopathy',
      'Severe coronary artery disease not treatable otherwise',
      'Serious congenital heart disease',
      'Life-threatening rhythm disorders',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Severe breathlessness'],
      ['symptoms/fatigue', 'Extreme fatigue'],
      ['symptoms/leg-swelling', 'Fluid retention'],
      ['symptoms/chest-pain', 'Chest discomfort'],
    ],
    tests: [
      [null, 'Echocardiogram'],
      [null, 'Cardiac catheterisation'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
      [null, 'Tissue typing / cross-match'],
    ],
    treatment: [
      'Assessment and placement on a transplant waiting list',
      'Bridging support such as mechanical heart pumps if needed',
      'The transplant operation itself',
      'Lifelong anti-rejection (immunosuppressant) medicines',
      'Regular monitoring for rejection and infection',
    ],
    whenToSee: [
      'Call emergency services for fever, severe breathlessness or chest pain after transplant',
      'See your transplant team urgently for signs of rejection or infection',
      'Never stop anti-rejection medicines without medical advice',
    ],
    faqs: [
      { q: 'How long can you live after a heart transplant?', a: 'Many recipients live for well over a decade; outcomes depend on age, health and follow-up care.' },
      { q: 'Why are lifelong medicines needed?', a: 'Immunosuppressants stop the body rejecting the new heart, so they must be taken exactly as prescribed.' },
    ],
  },
  {
    slug: 'lung-cancer-surgery',
    name: 'Lung Cancer Surgery',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Surgery to remove cancer from the lung, offered when the tumour is confined and the patient is fit enough. It offers the best chance of cure in early-stage disease.',
    causes: [
      'Smoking and tobacco use',
      'Second-hand smoke',
      'Air pollution',
      'Occupational exposures (asbestos, radon)',
      'Family history',
    ],
    symptoms: [
      ['symptoms/cough', 'Persistent cough'],
      [null, 'Coughing up blood'],
      ['symptoms/chest-pain', 'Chest pain'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/unexplained-weight-loss', 'Weight loss'],
      ['symptoms/fatigue', 'Fatigue'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT scan of chest'],
      [null, 'PET scan'],
      [null, 'Biopsy / bronchoscopy'],
      [null, 'Lung function tests'],
    ],
    treatment: [
      'Removing part or all of the affected lung (lobectomy or pneumonectomy)',
      'Minimally invasive (keyhole / VATS) surgery where suitable',
      'Chemotherapy or radiotherapy before or after surgery',
      'Targeted therapy or immunotherapy in selected cases',
      'Stopping smoking and pulmonary rehabilitation',
    ],
    whenToSee: [
      'See a doctor promptly for a cough lasting more than three weeks or coughing up blood',
      'Call emergency services for sudden severe breathlessness or chest pain',
      'Get checked for unexplained weight loss with chest symptoms',
    ],
    faqs: [
      { q: 'Can you live with one lung?', a: 'Yes — many people manage well after removal of a lung, especially with rehabilitation.' },
      { q: 'Is keyhole lung surgery possible?', a: 'For many early cancers, minimally invasive surgery is possible, with faster recovery.' },
    ],
  },
  {
    slug: 'pneumothorax',
    name: 'Pneumothorax (Collapsed Lung)',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Air leaks into the space around the lung, causing it to collapse partly or fully. It can happen suddenly and causes sharp chest pain and breathlessness.',
    causes: [
      'Spontaneous rupture of a small air sac (often in tall, thin young people)',
      'Chest injury or rib fracture',
      'Underlying lung disease',
      'Medical procedures on the chest',
      'Smoking',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Sudden sharp chest pain'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      [null, 'Rapid breathing'],
      ['symptoms/fatigue', 'Feeling faint'],
      ['symptoms/cough', 'Dry cough'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT scan of chest'],
      [null, 'Oxygen level (pulse oximetry)'],
    ],
    treatment: [
      'Observation and oxygen for small collapses',
      'Removing the air with a needle or chest tube',
      'Surgery to prevent recurrence in repeated cases',
      'Stopping smoking to lower recurrence risk',
    ],
    whenToSee: [
      'Call emergency services for sudden severe breathlessness with chest pain',
      'Seek urgent care if breathing worsens quickly',
      'See a doctor for chest pain after an injury',
    ],
    faqs: [
      { q: 'Can a collapsed lung reinflate on its own?', a: 'A small pneumothorax may reinflate with observation, but larger ones usually need the air removed.' },
      { q: 'Can it happen again?', a: 'Yes, recurrence is possible; surgery can reduce this risk in repeated cases.' },
    ],
  },
  {
    slug: 'esophageal-cancer',
    name: 'Esophageal Cancer',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'Cancer of the food pipe (esophagus) that often causes difficulty swallowing. Surgery is a key treatment for cancer that has not spread.',
    causes: [
      'Smoking and tobacco/betel-nut use',
      'Heavy alcohol use',
      'Long-standing acid reflux (GERD)',
      "Barrett's esophagus",
      'Very hot drinks and certain dietary factors',
    ],
    symptoms: [
      [null, 'Difficulty swallowing'],
      ['symptoms/unexplained-weight-loss', 'Weight loss'],
      ['symptoms/heartburn', 'Persistent heartburn'],
      ['symptoms/chest-pain', 'Chest or throat discomfort'],
      [null, 'Food sticking or regurgitation'],
    ],
    tests: [
      [null, 'Endoscopy with biopsy'],
      [null, 'CT scan'],
      [null, 'PET scan'],
      [null, 'Barium swallow'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests'],
    ],
    treatment: [
      'Surgery to remove the affected part of the esophagus',
      'Chemotherapy and radiotherapy, often before surgery',
      'Stenting or feeding support to help swallowing',
      'Targeted or immunotherapy in selected cases',
      'Nutritional support throughout treatment',
    ],
    whenToSee: [
      'See a doctor promptly for difficulty or pain when swallowing',
      'Get checked for unexplained weight loss with reflux',
      'Seek urgent care for vomiting blood or inability to swallow fluids',
    ],
    faqs: [
      { q: 'Is difficulty swallowing always cancer?', a: 'No, but new or worsening difficulty swallowing should always be assessed to rule out serious causes.' },
      { q: 'Can esophageal cancer be cured?', a: 'Early-stage cancer can often be treated with surgery and other therapies; outlook depends on the stage at diagnosis.' },
    ],
  },
  {
    slug: 'mediastinal-tumor',
    name: 'Mediastinal Tumor',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'A growth in the mediastinum — the central part of the chest between the lungs that holds the heart, windpipe and major vessels. Tumours here can be benign or cancerous.',
    causes: [
      'Thymus gland tumours (thymoma)',
      'Lymphoma',
      'Germ cell tumours',
      'Nerve tissue tumours',
      'Cysts and other growths',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Chest pain or pressure'],
      ['symptoms/cough', 'Cough'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      [null, 'Difficulty swallowing'],
      ['symptoms/unexplained-weight-loss', 'Weight loss'],
      ['symptoms/fatigue', 'Fatigue'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT scan of chest'],
      ['mri-scan-explained', 'MRI'],
      [null, 'Biopsy'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests'],
    ],
    treatment: [
      'Surgery to remove the tumour, often minimally invasive',
      'Chemotherapy or radiotherapy for certain cancers',
      'Combined treatment for lymphomas and germ cell tumours',
      'Regular follow-up scans',
    ],
    whenToSee: [
      'See a doctor for persistent chest pain, cough or breathlessness',
      'Call emergency services for severe breathlessness or swelling of the face and neck',
      'Get checked for unexplained weight loss or night sweats with chest symptoms',
    ],
    faqs: [
      { q: 'Are all mediastinal tumours cancer?', a: 'No — many are benign, but they still often need removal because of their location.' },
      { q: 'How are they found?', a: 'Often on a chest scan done for other reasons, then confirmed with a biopsy.' },
    ],
  },
  {
    slug: 'pectus-excavatum',
    name: 'Pectus Excavatum (Sunken Chest)',
    dept: ['cardiac-surgery', 'Cardiac & Thoracic Surgery'],
    lede: 'A common chest-wall difference where the breastbone is sunken inward, giving a caved-in appearance. It is usually cosmetic but can sometimes affect the heart and lungs.',
    causes: [
      'Abnormal growth of the rib cartilage',
      'Often present from birth and worsens in the teens',
      'Family tendency',
      'Linked to some connective tissue conditions',
    ],
    symptoms: [
      [null, 'Sunken appearance of the chest'],
      ['symptoms/shortness-of-breath', 'Breathlessness on exertion'],
      ['symptoms/fatigue', 'Reduced exercise tolerance'],
      ['symptoms/chest-pain', 'Chest discomfort'],
      ['symptoms/heart-palpitations', 'Palpitations'],
    ],
    tests: [
      [null, 'Physical examination'],
      [null, 'CT scan of chest'],
      [null, 'Echocardiogram'],
      [null, 'Lung function tests'],
    ],
    treatment: [
      'Observation for mild cases',
      'Physiotherapy and exercises to improve posture',
      'Vacuum bell device in selected patients',
      'Surgery (such as the Nuss or Ravitch procedure) for severe cases',
    ],
    whenToSee: [
      'See a doctor if breathlessness or chest pain limits activity',
      'Seek assessment if the appearance affects wellbeing',
      'Discuss timing of any surgery, often best in the teenage years',
    ],
    faqs: [
      { q: 'Is pectus excavatum dangerous?', a: 'Most cases are mild and harmless, but severe forms can press on the heart and lungs and may need surgery.' },
      { q: 'Can it be corrected?', a: 'Yes — devices help mild cases, and surgery can correct severe ones.' },
    ],
  },

  // ===================== VASCULAR SURGERY (12) =====================
  {
    slug: 'peripheral-artery-disease',
    name: 'Peripheral Artery Disease (PAD)',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'Narrowing of the arteries in the legs from plaque build-up, reducing blood flow. It commonly causes leg pain when walking and raises the risk of heart attack and stroke.',
    causes: [
      'Atherosclerosis (fatty plaque in arteries)',
      'Smoking',
      'Diabetes',
      'High blood pressure and cholesterol',
      'Ageing and lack of exercise',
    ],
    symptoms: [
      ['symptoms/leg-swelling', 'Leg pain or cramping when walking'],
      [null, 'Cold, pale or bluish feet'],
      ['symptoms/numbness-and-tingling', 'Numbness in the legs'],
      [null, 'Slow-healing foot sores'],
      ['symptoms/fatigue', 'Leg weakness or fatigue'],
    ],
    tests: [
      [null, 'Ankle-brachial index (ABI)'],
      [null, 'Doppler ultrasound'],
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      [null, 'CT or MR angiography'],
    ],
    treatment: [
      'Stop smoking — the single most important step',
      'Supervised walking exercise programmes',
      'Medicines to control cholesterol, BP and prevent clots',
      'Careful foot care, especially in diabetes',
      'Angioplasty, stenting or bypass surgery for severe cases',
    ],
    whenToSee: [
      'Seek urgent care for a suddenly cold, painful, pale leg (possible blockage)',
      'See a doctor for leg pain on walking that eases with rest',
      'Get non-healing foot sores checked promptly, especially with diabetes',
    ],
    faqs: [
      { q: 'Why does PAD matter beyond the legs?', a: 'The same plaque affects heart and brain arteries, so PAD signals a higher risk of heart attack and stroke.' },
      { q: 'Can walking really help?', a: 'Yes — regular supervised walking often improves how far you can walk before pain starts.' },
    ],
  },
  {
    slug: 'varicose-veins',
    name: 'Varicose Veins',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'Swollen, twisted veins, usually in the legs, caused by weak vein valves that let blood pool. They are common and often cosmetic but can cause aching and complications.',
    causes: [
      'Weak or damaged vein valves',
      'Prolonged standing (common in many jobs)',
      'Pregnancy',
      'Obesity',
      'Family history and ageing',
    ],
    symptoms: [
      [null, 'Bulging, twisted blue or purple veins'],
      ['symptoms/leg-swelling', 'Aching, heavy legs and swelling'],
      ['symptoms/itching', 'Itching around the veins'],
      [null, 'Cramps, worse after standing'],
      ['symptoms/skin-rash', 'Skin changes near the ankle'],
    ],
    tests: [
      [null, 'Physical examination'],
      [null, 'Duplex ultrasound of leg veins'],
    ],
    treatment: [
      'Compression stockings',
      'Leg elevation and regular exercise',
      'Weight loss and avoiding long standing',
      'Injection (sclerotherapy) for smaller veins',
      'Laser, radiofrequency or surgery for larger veins',
    ],
    whenToSee: [
      'See a doctor for painful, hardened or bleeding veins',
      'Seek care for skin ulcers or colour changes near the ankle',
      'Get urgent care for a hot, red, tender vein (possible clot)',
    ],
    faqs: [
      { q: 'Are varicose veins dangerous?', a: 'Usually not, but they can cause discomfort and, occasionally, skin ulcers or clots that need treatment.' },
      { q: 'Do compression stockings cure them?', a: 'They ease symptoms and slow progression but do not remove existing veins.' },
    ],
  },
  {
    slug: 'deep-vein-thrombosis',
    name: 'Deep Vein Thrombosis (DVT)',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'A blood clot forming in a deep vein, usually in the leg. It can be dangerous if part breaks off and travels to the lungs (pulmonary embolism).',
    causes: [
      'Long periods of immobility (long flights, bed rest)',
      'Recent surgery or injury',
      'Pregnancy and hormone medicines',
      'Cancer',
      'Inherited clotting tendencies',
    ],
    symptoms: [
      ['symptoms/leg-swelling', 'Swelling in one leg'],
      [null, 'Pain or tenderness in the calf'],
      ['symptoms/skin-rash', 'Warm, red or discoloured skin'],
      [null, 'Leg feeling heavy'],
    ],
    tests: [
      ['blood-tests/d-dimer', 'D-dimer'],
      [null, 'Doppler ultrasound of leg'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
      ['blood-tests/pt-inr', 'Clotting tests'],
    ],
    treatment: [
      'Blood thinners to stop the clot growing',
      'Compression stockings to reduce swelling',
      'Keeping mobile once treatment starts',
      'Clot-dissolving treatment or a filter in selected severe cases',
      'Treating any underlying cause',
    ],
    whenToSee: [
      'Call emergency services for sudden breathlessness, chest pain or coughing blood (possible clot in the lung)',
      'Seek urgent care for a painful, swollen leg',
      'See a doctor before long travel if you are at high risk',
    ],
    faqs: [
      { q: 'Why is DVT serious?', a: 'A clot can break off and lodge in the lungs, which is life-threatening — so prompt treatment matters.' },
      { q: 'How can I prevent DVT on long journeys?', a: 'Move your legs regularly, stay hydrated and, if advised, wear compression stockings.' },
    ],
  },
  {
    slug: 'abdominal-aortic-aneurysm',
    name: 'Abdominal Aortic Aneurysm (AAA)',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'A bulge in the main artery running through the abdomen. It usually causes no symptoms but can be life-threatening if it bursts.',
    causes: [
      'Atherosclerosis',
      'High blood pressure',
      'Smoking',
      'Ageing (more common in older men)',
      'Family history',
    ],
    symptoms: [
      [null, 'Often no symptoms'],
      ['symptoms/abdominal-pain', 'Deep abdominal pain'],
      ['symptoms/back-pain', 'Back pain'],
      [null, 'Pulsing feeling in the abdomen'],
    ],
    tests: [
      [null, 'Abdominal ultrasound'],
      [null, 'CT scan of abdomen'],
      ['mri-scan-explained', 'MRI'],
    ],
    treatment: [
      'Controlling blood pressure and stopping smoking',
      'Regular scans to monitor small aneurysms',
      'Open surgical repair for large aneurysms',
      'Stent-graft (endovascular / EVAR) repair in suitable patients',
    ],
    whenToSee: [
      'Call emergency services for sudden severe abdominal or back pain with faintness (possible rupture)',
      'See a doctor for a known aneurysm that is enlarging',
      'Discuss screening if you are an older male smoker or have a family history',
    ],
    faqs: [
      { q: 'How do I know if I have an aneurysm?', a: 'Most cause no symptoms and are found on a scan; screening is offered to higher-risk groups in some places.' },
      { q: 'When does it need surgery?', a: 'When it reaches a certain size or grows fast, because the risk of rupture then rises.' },
    ],
  },
  {
    slug: 'carotid-artery-disease',
    name: 'Carotid Artery Disease',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'Narrowing of the carotid arteries in the neck that supply the brain, from plaque build-up. It is an important, treatable cause of stroke.',
    causes: [
      'Atherosclerosis',
      'High blood pressure and cholesterol',
      'Smoking',
      'Diabetes',
      'Ageing',
    ],
    symptoms: [
      [null, 'Often no symptoms until a warning stroke'],
      [null, 'Sudden weakness or numbness on one side'],
      [null, 'Slurred speech'],
      ['symptoms/blurred-vision', 'Sudden vision loss in one eye'],
      ['symptoms/dizziness', 'Dizziness'],
    ],
    tests: [
      [null, 'Carotid Doppler ultrasound'],
      [null, 'CT or MR angiography'],
      ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
    ],
    treatment: [
      'Stopping smoking and controlling BP, cholesterol and diabetes',
      'Blood thinners / antiplatelet medicines',
      'Cholesterol-lowering medicines (statins)',
      'Surgery to clear the artery (carotid endarterectomy) for severe narrowing',
      'Carotid stenting in selected patients',
    ],
    whenToSee: [
      'Call emergency services immediately for face droop, arm weakness or speech problems (stroke signs)',
      'See a doctor if a neck bruit (sound) is found',
      'Seek urgent care for brief episodes of weakness or vision loss (mini-stroke)',
    ],
    faqs: [
      { q: 'What is a mini-stroke?', a: 'A transient ischemic attack (TIA) — brief stroke-like symptoms that recover but warn of a high stroke risk and need urgent assessment.' },
      { q: 'Does narrowing always need surgery?', a: 'No — mild narrowing is managed with medicines and lifestyle; surgery is for severe, especially symptomatic, narrowing.' },
    ],
  },
  {
    slug: 'chronic-venous-insufficiency',
    name: 'Chronic Venous Insufficiency',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'A long-term condition where leg veins struggle to return blood to the heart, causing swelling, skin changes and sometimes ulcers.',
    causes: [
      'Damaged or weak vein valves',
      'Previous deep vein thrombosis',
      'Varicose veins',
      'Prolonged standing and obesity',
      'Ageing',
    ],
    symptoms: [
      ['symptoms/leg-swelling', 'Leg swelling, worse at day-end'],
      [null, 'Aching or heaviness'],
      ['symptoms/skin-rash', 'Brown skin discolouration near ankle'],
      ['symptoms/itching', 'Itching'],
      [null, 'Leg ulcers in advanced cases'],
    ],
    tests: [
      [null, 'Duplex ultrasound of leg veins'],
      [null, 'Physical examination'],
    ],
    treatment: [
      'Compression stockings',
      'Leg elevation and regular exercise',
      'Weight loss and skin care',
      'Wound care for ulcers',
      'Procedures to close faulty veins (laser, radiofrequency or surgery)',
    ],
    whenToSee: [
      'See a doctor for persistent leg swelling or skin changes',
      'Seek care for a leg ulcer that will not heal',
      'Get urgent care for a hot, red, tender leg (possible clot or infection)',
    ],
    faqs: [
      { q: 'Can venous insufficiency be cured?', a: 'It is usually managed rather than cured; compression and vein procedures control symptoms and prevent ulcers.' },
      { q: 'Why do the ankles turn brown?', a: 'Long-standing high vein pressure leaks pigment into the skin, causing the typical discolouration.' },
    ],
  },
  {
    slug: 'diabetic-foot-ulcer',
    name: 'Diabetic Foot Ulcer',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'An open sore on the foot in people with diabetes, caused by nerve damage and poor blood flow. It can become infected and, if neglected, threaten the limb.',
    causes: [
      'Nerve damage reducing foot sensation (neuropathy)',
      'Poor blood flow (peripheral artery disease)',
      'Uncontrolled blood sugar',
      'Foot injuries or ill-fitting footwear',
      'Infection',
    ],
    symptoms: [
      [null, 'A sore or wound on the foot'],
      ['symptoms/numbness-and-tingling', 'Numbness or tingling'],
      ['symptoms/skin-rash', 'Redness or discharge'],
      ['symptoms/fever', 'Fever if infected'],
      [null, 'Foul smell or blackened tissue (serious)'],
    ],
    tests: [
      ['blood-tests/hba1c', 'HbA1c'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
      [null, 'Wound swab / culture'],
      [null, 'Doppler and ankle-brachial index'],
    ],
    treatment: [
      'Good blood sugar control',
      'Wound cleaning, dressing and offloading pressure',
      'Antibiotics for infection',
      'Restoring blood flow (angioplasty or bypass) if arteries are blocked',
      'Regular foot care and proper footwear',
    ],
    whenToSee: [
      'Seek urgent care for a foot wound with spreading redness, fever or black tissue',
      'See a doctor for any new foot sore if you have diabetes',
      'Check feet daily and never ignore a small injury',
    ],
    faqs: [
      { q: 'Why are diabetic foot ulcers so serious?', a: 'Reduced sensation hides injuries and poor blood flow slows healing, so small wounds can worsen and risk the limb.' },
      { q: 'How can I prevent them?', a: 'Keep blood sugar controlled, inspect feet daily, wear well-fitting shoes and treat any sore early.' },
    ],
  },
  {
    slug: 'aortic-dissection',
    name: 'Aortic Dissection',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'A tear in the inner wall of the main artery (aorta) that lets blood split its layers. It is a life-threatening emergency needing immediate treatment.',
    causes: [
      'Long-standing high blood pressure',
      'Aortic aneurysm',
      'Inherited connective tissue disorders',
      'Chest injury',
      'Bicuspid aortic valve',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Sudden severe tearing chest pain'],
      ['symptoms/back-pain', 'Pain spreading to the back'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fainting', 'Fainting'],
      ['symptoms/numbness-and-tingling', 'Weakness or numbness'],
    ],
    tests: [
      [null, 'CT angiography (urgent)'],
      [null, 'Echocardiogram'],
      ['x-ray-explained', 'Chest X-ray'],
      ['blood-tests/d-dimer', 'D-dimer'],
    ],
    treatment: [
      'Call emergency services immediately — this is time-critical',
      'Urgent blood pressure control',
      'Emergency surgery to repair the aorta for certain types',
      'Stent-graft repair in selected cases',
      'Intensive care monitoring',
    ],
    whenToSee: [
      'Call your local emergency number now for sudden severe tearing chest or back pain',
      'Seek immediate care for chest pain with fainting or weakness',
      'Do not wait or drive yourself — this is an emergency',
    ],
    faqs: [
      { q: 'How is dissection different from a heart attack?', a: 'Both cause severe chest pain; dissection often feels tearing and spreads to the back. Either way, call emergency services immediately.' },
      { q: 'Can it be prevented?', a: 'Controlling blood pressure and monitoring known aneurysms lower the risk.' },
    ],
  },
  {
    slug: 'lymphedema',
    name: 'Lymphedema',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'Long-term swelling, usually of an arm or leg, caused by a build-up of lymph fluid when the lymphatic system is damaged or blocked.',
    causes: [
      'Damage or removal of lymph nodes (e.g. after cancer surgery)',
      'Radiotherapy',
      'Infections such as filariasis (important in parts of India)',
      'Injury or repeated infections',
      'Rarely, inherited lymphatic problems',
    ],
    symptoms: [
      ['symptoms/leg-swelling', 'Swelling of a limb'],
      [null, 'Heaviness or tightness'],
      ['symptoms/skin-rash', 'Thickened or hardened skin'],
      [null, 'Reduced movement'],
      ['symptoms/fever', 'Fever during skin infections'],
    ],
    tests: [
      [null, 'Physical examination'],
      [null, 'Lymphoscintigraphy'],
      [null, 'Doppler ultrasound (to exclude clots)'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests'],
    ],
    treatment: [
      'Compression garments and bandaging',
      'Manual lymphatic drainage massage',
      'Skin care to prevent infection',
      'Exercise to help fluid movement',
      'Surgery in selected severe cases',
    ],
    whenToSee: [
      'See a doctor for new or worsening limb swelling',
      'Seek urgent care for fever, redness and pain in the swollen limb (infection)',
      'Get assessed if swelling follows cancer treatment',
    ],
    faqs: [
      { q: 'Can lymphedema be cured?', a: 'It cannot usually be cured but can be well controlled with compression, skin care and drainage therapy.' },
      { q: 'Is it linked to filariasis in India?', a: 'Yes — mosquito-borne filariasis is a notable cause of leg lymphedema in some regions.' },
    ],
  },
  {
    slug: 'arteriovenous-fistula',
    name: 'Arteriovenous Fistula (Dialysis Access)',
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'A surgically created connection between an artery and a vein, usually in the arm, to provide reliable access for kidney dialysis. It is the preferred long-term access.',
    causes: [
      'Need for long-term haemodialysis in kidney failure',
      'Diabetes-related kidney disease',
      'High blood pressure-related kidney disease',
      'Other chronic kidney conditions',
    ],
    symptoms: [
      [null, 'A buzzing/thrill felt over the fistula (normal)'],
      ['symptoms/leg-swelling', 'Arm swelling if it narrows'],
      [null, 'Weak or absent thrill (possible blockage)'],
      ['symptoms/skin-rash', 'Redness at the site (possible infection)'],
    ],
    tests: [
      [null, 'Physical examination (feel for thrill)'],
      [null, 'Duplex ultrasound of the fistula'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
    ],
    treatment: [
      'Surgical creation and a maturing period before use',
      'Care to protect the access arm (no BP cuffs or blood draws on it)',
      'Angioplasty to open a narrowed fistula',
      'Repeat surgery if it fails',
      'Prompt treatment of any infection',
    ],
    whenToSee: [
      'Seek urgent care if the thrill/buzz stops (possible blockage)',
      'See a doctor for redness, pain or swelling at the site',
      'Get urgent care for heavy bleeding from the fistula (apply pressure)',
    ],
    faqs: [
      { q: 'Why is a fistula preferred over a catheter?', a: 'Fistulas last longer and have fewer infections and complications than dialysis catheters.' },
      { q: 'How long before a new fistula can be used?', a: 'It usually needs several weeks to mature before it is strong enough for dialysis.' },
    ],
  },
  {
    slug: 'buerger-disease',
    name: "Buerger's Disease (Thromboangiitis Obliterans)",
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'Inflammation and clotting of small and medium arteries in the hands and feet, strongly linked to tobacco use. It can lead to painful ulcers and tissue loss.',
    causes: [
      'Tobacco use (smoking, chewing) — the key cause',
      'Young to middle-aged adults, more often men',
      'Possible immune involvement',
    ],
    symptoms: [
      [null, 'Pain in hands or feet, worse with activity'],
      [null, 'Cold, pale fingers or toes'],
      ['symptoms/numbness-and-tingling', 'Numbness or tingling'],
      [null, 'Painful sores or ulcers on fingers/toes'],
      [null, 'Colour changes in cold (like Raynaud)'],
    ],
    tests: [
      [null, 'Doppler ultrasound'],
      [null, 'Angiography'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests (to exclude other causes)'],
      ['blood-tests/esr', 'ESR'],
    ],
    treatment: [
      'Complete and permanent stopping of all tobacco — essential',
      'Medicines to improve blood flow and control pain',
      'Careful wound care for ulcers',
      'Avoiding cold and injury to the limbs',
      'Amputation only for severe, non-healing tissue loss',
    ],
    whenToSee: [
      'See a doctor for painful, cold or discoloured fingers or toes',
      'Seek urgent care for non-healing sores or blackened tissue',
      'Get help to quit tobacco as early as possible',
    ],
    faqs: [
      { q: "Can Buerger's disease be cured?", a: 'There is no cure, but completely stopping tobacco can halt progression and often prevents amputation.' },
      { q: 'Is quitting tobacco really that important?', a: 'Yes — it is the single most important treatment; continued use almost always makes it worse.' },
    ],
  },

  {
    slug: 'raynauds-phenomenon',
    name: "Raynaud's Phenomenon",
    dept: ['vascular-surgery', 'Vascular Surgery'],
    lede: 'The small blood vessels in the fingers and toes over-tighten in response to cold or stress, causing them to turn white, then blue, then red. Most cases are mild.',
    causes: [
      'Cold exposure or emotional stress',
      'Often no underlying cause (primary type)',
      'Connective tissue diseases (secondary type)',
      'Smoking',
      'Certain medicines and vibrating tools',
    ],
    symptoms: [
      [null, 'Fingers or toes turning white then blue in cold'],
      ['symptoms/numbness-and-tingling', 'Numbness or tingling'],
      [null, 'Cold, pale fingers and toes'],
      [null, 'Redness and throbbing on warming'],
      [null, 'Sores on fingertips (severe cases)'],
    ],
    tests: [
      [null, 'Physical examination'],
      [null, 'Nailfold capillaroscopy'],
      ['blood-tests/esr', 'ESR'],
      ['blood-tests/complete-blood-count-cbc', 'Blood tests (to check for other conditions)'],
    ],
    treatment: [
      'Keep hands and feet warm and wear gloves',
      'Stop smoking',
      'Manage stress',
      'Medicines to relax blood vessels for frequent attacks',
      'Treating any underlying connective tissue disease',
    ],
    whenToSee: [
      'See a doctor for sores or ulcers on the fingertips',
      'Seek assessment if attacks are severe, one-sided or start later in life',
      'Get checked if you also have joint pains or skin changes',
    ],
    faqs: [
      { q: "Is Raynaud's dangerous?", a: 'The common (primary) type is usually mild and harmless; the secondary type linked to other diseases can be more serious and needs assessment.' },
      { q: 'How can I reduce attacks?', a: 'Keep warm, avoid sudden cold, stop smoking and manage stress; medicines help for frequent attacks.' },
    ],
  },

  // ===================== EMERGENCY MEDICINE (12) =====================
  {
    slug: 'heart-attack',
    name: 'Heart Attack (Myocardial Infarction)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A blocked heart artery cuts off blood to part of the heart muscle, which starts to die. It is a medical emergency — every minute counts.',
    causes: [
      'A blood clot on a ruptured plaque in a heart artery',
      'Severe coronary artery disease',
      'Smoking, diabetes, high BP and cholesterol',
      'Rarely, spasm of a heart artery',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Central chest pain or pressure'],
      [null, 'Pain spreading to arm, jaw or back'],
      [null, 'Cold sweat'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/nausea-and-vomiting', 'Nausea'],
      ['symptoms/dizziness', 'Dizziness or feeling faint'],
    ],
    tests: [
      ['ecg-explained', 'ECG'],
      ['blood-tests/troponin', 'Troponin'],
      [null, 'Coronary angiography'],
      [null, 'Echocardiogram'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Emergency angioplasty and stenting to open the artery',
      'Clot-busting drugs if angioplasty is not quickly available',
      'Blood thinners and other heart-protective medicines',
      'Cardiac monitoring and later cardiac rehabilitation',
    ],
    whenToSee: [
      'Call your local emergency number now for chest pain lasting more than a few minutes',
      'Do not drive yourself — wait for the ambulance',
      'Chew aspirin only if advised by emergency services',
    ],
    faqs: [
      { q: 'What should I do while waiting for the ambulance?', a: 'Sit or lie down, stay calm, and take aspirin only if emergency services advise it. Do not eat or drive.' },
      { q: 'Can a heart attack feel mild?', a: 'Yes — especially in women, older people and those with diabetes, symptoms can be subtle, so do not ignore them.' },
    ],
  },
  {
    slug: 'cardiac-arrest',
    name: 'Cardiac Arrest',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'The heart suddenly stops pumping, so the person collapses, stops breathing normally and loses consciousness. Immediate CPR and defibrillation can save a life.',
    causes: [
      'Dangerous heart rhythms (often after a heart attack)',
      'Severe heart disease or cardiomyopathy',
      'Electrolyte imbalance',
      'Drowning, choking or electrocution',
      'Certain drug overdoses',
    ],
    symptoms: [
      ['symptoms/fainting', 'Sudden collapse'],
      [null, 'No response and no normal breathing'],
      [null, 'No pulse'],
      ['symptoms/chest-pain', 'Sometimes chest pain just before'],
    ],
    tests: [
      ['ecg-explained', 'ECG / cardiac monitor'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      ['blood-tests/troponin', 'Troponin'],
    ],
    treatment: [
      'Call your local emergency number and start CPR immediately',
      'Use an automated external defibrillator (AED) if available',
      'Continue chest compressions until help arrives',
      'Advanced life support and treating the cause in hospital',
      'Intensive care and monitoring after recovery',
    ],
    whenToSee: [
      'Call your local emergency number now if someone collapses and is not breathing normally',
      'Start hands-only CPR straight away — push hard and fast on the centre of the chest',
      'Send someone for the nearest AED',
    ],
    faqs: [
      { q: 'Is cardiac arrest the same as a heart attack?', a: 'No — a heart attack is a blockage; cardiac arrest is the heart stopping. A heart attack can trigger cardiac arrest.' },
      { q: 'Can I harm someone by doing CPR wrongly?', a: 'Doing nothing is far more dangerous. Hands-only CPR greatly improves survival, so act immediately.' },
    ],
  },
  {
    slug: 'anaphylaxis',
    name: 'Anaphylaxis (Severe Allergic Reaction)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A rapid, severe, whole-body allergic reaction that can cause breathing difficulty and a dangerous drop in blood pressure. It is a life-threatening emergency.',
    causes: [
      'Foods (nuts, shellfish, milk, egg)',
      'Insect stings',
      'Medicines',
      'Latex',
      'Sometimes no identified trigger',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Difficulty breathing'],
      ['symptoms/wheezing', 'Wheezing or throat tightness'],
      ['symptoms/skin-rash', 'Widespread hives or rash'],
      [null, 'Swelling of lips, tongue or face'],
      ['symptoms/dizziness', 'Dizziness or collapse'],
      ['symptoms/nausea-and-vomiting', 'Vomiting'],
    ],
    tests: [
      [null, 'Diagnosed clinically — treat first, test later'],
      [null, 'Serum tryptase (after the event)'],
      [null, 'Allergy testing later'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Use an adrenaline auto-injector without delay if available',
      'Lie the person down with legs raised (or sit up if breathing is hard)',
      'A second adrenaline dose may be needed if no improvement',
      'Hospital observation, as symptoms can return',
    ],
    whenToSee: [
      'Call your local emergency number now for breathing difficulty or collapse after exposure',
      'Use an adrenaline pen straight away if prescribed — do not wait',
      'Always go to hospital even if symptoms improve, as they can rebound',
    ],
    faqs: [
      { q: 'When should adrenaline be given?', a: 'Immediately at the first sign of a severe reaction — early adrenaline saves lives, and delay is dangerous.' },
      { q: 'Can symptoms come back after treatment?', a: 'Yes — reactions can return hours later, which is why hospital observation is important.' },
    ],
  },
  {
    slug: 'sepsis',
    name: 'Sepsis',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: "The body's extreme, life-threatening response to an infection that can lead to organ failure. Early recognition and treatment are critical.",
    causes: [
      'Lung infections (pneumonia)',
      'Urine infections',
      'Abdominal infections',
      'Skin and wound infections',
      'Any infection that spreads',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever or very low temperature'],
      [null, 'Fast breathing and heart rate'],
      ['symptoms/dizziness', 'Confusion or drowsiness'],
      [null, 'Very low urine output'],
      ['symptoms/skin-rash', 'Mottled or clammy skin'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Complete blood count'],
      ['blood-tests/crp', 'CRP'],
      [null, 'Blood cultures'],
      ['blood-tests/creatinine', 'Creatinine'],
      [null, 'Lactate level'],
    ],
    treatment: [
      'Call your local emergency number — sepsis is time-critical',
      'Early intravenous antibiotics',
      'Intravenous fluids to support blood pressure',
      'Oxygen and organ support in intensive care if needed',
      'Finding and treating the source of infection',
    ],
    whenToSee: [
      'Call your local emergency number now for confusion, very fast breathing or mottled skin with an infection',
      'Seek urgent care for a high fever with drowsiness or reduced urination',
      'Act fast — early treatment greatly improves survival',
    ],
    faqs: [
      { q: 'Who is most at risk of sepsis?', a: 'The very young, older adults, pregnant women and people with weak immunity or chronic illness are at higher risk.' },
      { q: 'How quickly does sepsis develop?', a: 'It can develop within hours, so any infection with warning signs needs urgent assessment.' },
    ],
  },
  {
    slug: 'shock',
    name: 'Shock (Circulatory Collapse)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A life-threatening state where the body cannot get enough blood and oxygen to its organs. It has several causes and always needs emergency care.',
    causes: [
      'Severe bleeding or fluid loss (hypovolemic)',
      'Serious infection (septic shock)',
      'Heart pump failure (cardiogenic)',
      'Severe allergic reaction (anaphylactic)',
      'Major injury or burns',
    ],
    symptoms: [
      [null, 'Cold, clammy, pale skin'],
      [null, 'Fast, weak pulse'],
      ['symptoms/dizziness', 'Dizziness or confusion'],
      ['symptoms/shortness-of-breath', 'Rapid breathing'],
      ['symptoms/fainting', 'Fainting or collapse'],
      ['symptoms/nausea-and-vomiting', 'Nausea'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      [null, 'Lactate level'],
      ['ecg-explained', 'ECG'],
      ['blood-tests/creatinine', 'Kidney function'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Lay the person down and keep them warm',
      'Intravenous fluids and, when needed, blood',
      'Medicines to support blood pressure',
      'Treating the underlying cause (bleeding, infection, heart problem)',
    ],
    whenToSee: [
      'Call your local emergency number now for collapse with cold clammy skin and a weak pulse',
      'Seek immediate care after major bleeding, injury or severe infection',
      'Do not give food or drink to someone who is collapsing',
    ],
    faqs: [
      { q: 'Is shock the same as feeling shocked emotionally?', a: 'No — medical shock is a dangerous drop in blood flow to organs and is a physical emergency.' },
      { q: 'What can I do while waiting for help?', a: 'Keep the person lying down and warm, control any obvious bleeding, and do not give food or drink.' },
    ],
  },
  {
    slug: 'poisoning',
    name: 'Poisoning & Overdose',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'Harm caused by swallowing, inhaling or absorbing a toxic substance or too much of a medicine. Effects range from mild to life-threatening.',
    causes: [
      'Accidental medicine overdose',
      'Household chemicals or pesticides',
      'Snakebite or venomous stings',
      'Alcohol or recreational drugs',
      'Carbon monoxide or toxic fumes',
    ],
    symptoms: [
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
      ['symptoms/dizziness', 'Confusion or drowsiness'],
      ['symptoms/shortness-of-breath', 'Difficulty breathing'],
      [null, 'Seizures'],
      [null, 'Loss of consciousness'],
      ['symptoms/abdominal-pain', 'Abdominal pain'],
    ],
    tests: [
      [null, 'Identifying the substance taken'],
      ['blood-tests/liver-function-test-lft', 'Liver function'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      [null, 'Drug levels where available'],
    ],
    treatment: [
      'Call your local emergency number or a poison helpline immediately',
      'Take the container or medicine packet to hospital',
      'Do not make the person vomit unless told to by a professional',
      'Specific antidotes where they exist',
      'Supportive care and monitoring in hospital',
    ],
    whenToSee: [
      'Call your local emergency number now for collapse, seizures or breathing difficulty after exposure',
      'Seek immediate care for any suspected overdose, even if the person seems well',
      'For snakebite, keep the limb still and reach hospital urgently',
    ],
    faqs: [
      { q: 'Should I make someone vomit after poisoning?', a: 'No — this can cause harm. Follow the advice of emergency services or a poison control helpline.' },
      { q: 'What information helps the doctors most?', a: 'What was taken, how much, and when — bring the container or packet if you can.' },
    ],
  },
  {
    slug: 'severe-trauma',
    name: 'Severe Trauma (Major Injury)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'Serious injury from events such as road accidents, falls or violence, often affecting several parts of the body. Rapid emergency care saves lives.',
    causes: [
      'Road traffic accidents',
      'Falls from height',
      'Assault or violence',
      'Industrial or machinery accidents',
      'Burns and crush injuries',
    ],
    symptoms: [
      [null, 'Heavy bleeding'],
      ['symptoms/fainting', 'Loss of consciousness'],
      [null, 'Obvious fractures or deformity'],
      ['symptoms/shortness-of-breath', 'Difficulty breathing'],
      ['symptoms/chest-pain', 'Chest or abdominal pain'],
      ['symptoms/dizziness', 'Confusion'],
    ],
    tests: [
      [null, 'Trauma CT scan'],
      ['x-ray-explained', 'X-rays'],
      [null, 'FAST ultrasound'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
      ['blood-tests/pt-inr', 'Clotting tests'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Control heavy bleeding with firm pressure',
      'Do not move someone with a possible spine injury unless in danger',
      'Emergency resuscitation, blood transfusion and surgery as needed',
      'Intensive care and rehabilitation',
    ],
    whenToSee: [
      'Call your local emergency number now for major injury, heavy bleeding or loss of consciousness',
      'Keep the person still if a neck or back injury is possible',
      'Apply firm pressure to bleeding wounds while waiting for help',
    ],
    faqs: [
      { q: 'Should I move an injured person?', a: 'Only if they are in immediate danger — moving someone with a spine injury can cause harm. Otherwise keep them still.' },
      { q: 'How do I control heavy bleeding?', a: 'Press firmly on the wound with a clean cloth and keep pressure on until help arrives.' },
    ],
  },
  {
    slug: 'heat-stroke',
    name: 'Heat Stroke',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A dangerous rise in body temperature, usually from heat exposure or exertion, that overwhelms the body cooling system. It is a life-threatening emergency, especially in hot Indian summers.',
    causes: [
      'Prolonged exposure to high temperatures',
      'Strenuous activity in the heat',
      'Dehydration',
      'High humidity',
      'Being very young, older, or unwell',
    ],
    symptoms: [
      ['symptoms/fever', 'Very high body temperature'],
      [null, 'Hot, dry or flushed skin'],
      ['symptoms/dizziness', 'Confusion or agitation'],
      ['symptoms/nausea-and-vomiting', 'Nausea'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/fainting', 'Fainting or seizures'],
    ],
    tests: [
      [null, 'Core body temperature'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Move to a cool, shaded place',
      'Cool the body quickly with water, wet cloths and fanning',
      'Give sips of water if fully conscious',
      'Intravenous fluids and monitoring in hospital',
    ],
    whenToSee: [
      'Call your local emergency number now for confusion, collapse or very high temperature in the heat',
      'Start cooling the person immediately while waiting for help',
      'Seek care for heat exhaustion that does not improve with rest and fluids',
    ],
    faqs: [
      { q: 'How is heat stroke different from heat exhaustion?', a: 'Heat exhaustion has heavy sweating and tiredness; heat stroke is more severe, with confusion and a dangerously high temperature — a true emergency.' },
      { q: 'How can I prevent it?', a: 'Stay hydrated, avoid peak-heat activity, wear light clothing and rest in the shade during hot weather.' },
    ],
  },
  {
    slug: 'drowning',
    name: 'Drowning',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'Breathing difficulty from being submerged in water, which can rapidly deprive the body of oxygen. Fast rescue and resuscitation are life-saving.',
    causes: [
      'Swimming without supervision',
      'Weak or non-swimmers in deep water',
      'Alcohol near water',
      'Seizures or fainting in water',
      'Floods and open water bodies',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Coughing and breathing difficulty'],
      [null, 'Choking or gasping'],
      ['symptoms/fainting', 'Unconsciousness'],
      [null, 'No breathing (severe)'],
      ['symptoms/chest-pain', 'Chest discomfort'],
    ],
    tests: [
      [null, 'Oxygen level (pulse oximetry)'],
      ['x-ray-explained', 'Chest X-ray'],
      ['blood-tests/electrolytes', 'Electrolytes'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Get the person out of the water safely without endangering yourself',
      'Start CPR if they are not breathing normally',
      'Give oxygen and hospital monitoring, as lung problems can appear later',
      'Keep the person warm',
    ],
    whenToSee: [
      'Call your local emergency number now for any near-drowning, even if the person seems to recover',
      'Start CPR immediately if breathing has stopped',
      'Always go to hospital, as breathing problems can develop hours later',
    ],
    faqs: [
      { q: 'Why go to hospital if the person seems fine?', a: 'Water in the lungs can cause breathing problems hours later, so monitoring is important after any drowning incident.' },
      { q: 'Should I dive in to rescue someone?', a: 'Only if it is safe — reach or throw something to them first, so you do not become a second victim.' },
    ],
  },
  {
    slug: 'acute-stroke',
    name: 'Acute Stroke (Brain Attack)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'Blood flow to part of the brain is suddenly blocked or a vessel bursts, so brain cells begin to die. It is an emergency — fast treatment can limit damage.',
    causes: [
      'A clot blocking a brain artery (ischemic stroke)',
      'Bleeding in the brain (hemorrhagic stroke)',
      'High blood pressure',
      'Atrial fibrillation',
      'Diabetes, smoking and high cholesterol',
    ],
    symptoms: [
      [null, 'Face drooping on one side'],
      ['symptoms/numbness-and-tingling', 'Arm or leg weakness or numbness'],
      [null, 'Slurred or confused speech'],
      ['symptoms/blurred-vision', 'Sudden vision loss'],
      ['symptoms/dizziness', 'Sudden dizziness or loss of balance'],
      ['symptoms/headache', 'Sudden severe headache'],
    ],
    tests: [
      [null, 'Urgent CT scan of the brain'],
      ['mri-scan-explained', 'MRI'],
      ['ecg-explained', 'ECG'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      ['blood-tests/pt-inr', 'Clotting tests'],
    ],
    treatment: [
      'Call your local emergency number immediately — time is brain',
      'Clot-busting drugs for suitable clot strokes given early',
      'Clot removal (thrombectomy) in selected cases',
      'Controlling bleeding and blood pressure for hemorrhagic stroke',
      'Rehabilitation and prevention of future strokes',
    ],
    whenToSee: [
      'Call your local emergency number now if you notice Face drooping, Arm weakness or Speech difficulty (act FAST)',
      'Note the time symptoms started — it guides treatment',
      'Do not wait to see if symptoms pass, even a brief episode needs urgent care',
    ],
    faqs: [
      { q: 'What does FAST mean?', a: 'Face drooping, Arm weakness, Speech difficulty, Time to call emergency services — a quick way to spot a stroke.' },
      { q: 'Why does speed matter so much?', a: 'Brain cells die quickly without blood flow, so earlier treatment means less lasting damage.' },
    ],
  },
  {
    slug: 'status-epilepticus',
    name: 'Status Epilepticus (Prolonged Seizure)',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A seizure lasting more than five minutes, or repeated seizures without recovery in between. It is a medical emergency that can harm the brain if not stopped.',
    causes: [
      'Known epilepsy, especially if medicine is missed',
      'Brain infection (such as meningitis)',
      'Stroke or head injury',
      'Very low blood sugar or sodium',
      'Alcohol withdrawal or poisoning',
    ],
    symptoms: [
      [null, 'Continuous or repeated convulsions'],
      [null, 'Unconsciousness that does not lift'],
      ['symptoms/numbness-and-tingling', 'Jerking of limbs'],
      [null, 'Not returning to normal between seizures'],
    ],
    tests: [
      ['blood-tests/fasting-blood-sugar', 'Blood sugar'],
      ['blood-tests/electrolytes', 'Electrolytes'],
      [null, 'Brain scan (CT / MRI)'],
      [null, 'EEG'],
      ['blood-tests/complete-blood-count-cbc', 'Blood count'],
    ],
    treatment: [
      'Call your local emergency number immediately',
      'Protect the person from injury and do not put anything in the mouth',
      'Turn them on their side once jerking stops',
      'Emergency medicines to stop the seizure',
      'Finding and treating the underlying cause',
    ],
    whenToSee: [
      'Call your local emergency number now for a seizure lasting more than five minutes or repeated seizures',
      'Cushion the head and clear nearby objects during a seizure',
      'Note how long the seizure lasts to tell the medical team',
    ],
    faqs: [
      { q: 'Should I hold the person down or open their mouth?', a: 'No — never restrain them or put anything in the mouth. Protect their head and turn them on their side after.' },
      { q: 'When is a seizure an emergency?', a: 'If it lasts over five minutes, repeats without recovery, or is a first-ever seizure — call emergency services.' },
    ],
  },
  {
    slug: 'acute-asthma',
    name: 'Acute Severe Asthma Attack',
    dept: ['emergency-medicine', 'Emergency Medicine'],
    lede: 'A sudden, severe worsening of asthma where the airways tighten and breathing becomes very difficult. A severe attack is a life-threatening emergency.',
    causes: [
      'Respiratory infections',
      'Allergens (dust, pollen, pets)',
      'Air pollution and smoke',
      'Missing preventer inhalers',
      'Exercise or cold air',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Severe breathlessness'],
      ['symptoms/wheezing', 'Loud wheezing'],
      ['symptoms/chest-pain', 'Chest tightness'],
      ['symptoms/cough', 'Persistent cough'],
      [null, 'Difficulty speaking in full sentences'],
      [null, 'Blue lips (very serious)'],
    ],
    tests: [
      [null, 'Oxygen level (pulse oximetry)'],
      [null, 'Peak flow measurement'],
      ['x-ray-explained', 'Chest X-ray (if needed)'],
      [null, 'Arterial blood gas in severe cases'],
    ],
    treatment: [
      'Use the reliever inhaler straight away, as directed',
      'Call your local emergency number if not improving or the attack is severe',
      'Sit upright and try to stay calm',
      'Oxygen and nebulised medicines in hospital',
      'Steroids to reduce airway inflammation',
    ],
    whenToSee: [
      'Call your local emergency number now if the reliever inhaler is not helping or speaking is hard',
      'Seek urgent care for blue lips, exhaustion or a silent chest',
      'See a doctor to review your inhalers after any severe attack',
    ],
    faqs: [
      { q: 'What should I do during an asthma attack?', a: 'Sit up, use your reliever inhaler as directed, and call emergency services if there is no improvement or you cannot speak in full sentences.' },
      { q: 'How can attacks be prevented?', a: 'Use preventer inhalers regularly as prescribed, avoid known triggers, and follow an asthma action plan.' },
    ],
  },
];
