// MedDroid disease data — group g2
// Departments: Pulmonology, Infectious Diseases, Allergy & Immunology
// Educational content only — not a diagnosis. No specific drug names/doses.
export default [
  // ===================== PULMONOLOGY =====================
  {
    slug: 'asthma',
    name: 'Asthma',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Asthma is a long-term condition where the airways narrow and become inflamed, making it hard to breathe. Symptoms come and go and can usually be well controlled.',
    causes: [
      'Airway inflammation that reacts to triggers',
      'Allergens: dust mites, pollen, pet dander, mould',
      'Air pollution, smoke and strong fumes',
      'Cold air, exercise or chest infections',
      'Family history of asthma, eczema or allergies',
    ],
    symptoms: [
      ['symptoms/wheezing', 'Wheezing'],
      ['symptoms/shortness-of-breath', 'Shortness of breath'],
      ['symptoms/cough', 'Cough, often worse at night'],
      ['symptoms/chest-pain', 'Chest tightness'],
      [null, 'Trouble sleeping due to breathing'],
    ],
    tests: [
      [null, 'Spirometry (lung function test)'],
      [null, 'Peak flow measurement'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Allergy testing'],
    ],
    treatment: [
      'Avoid known triggers where possible',
      'Reliever inhalers for quick symptom relief',
      'Preventer (inhaled steroid) inhalers used daily for control',
      'A written personal asthma action plan with your doctor',
      'Regular reviews and correct inhaler technique',
    ],
    whenToSee: [
      'Reliever inhaler is not helping or is needed very often',
      'Too breathless to talk, eat or sleep — call your local emergency number now',
      'Lips or fingers turning blue, or exhaustion from breathing — emergency',
      'Frequent night-time symptoms or worsening peak flow',
    ],
    faqs: [
      { q: 'Can asthma be cured?', a: 'There is no cure, but with the right inhalers and by avoiding triggers most people control it well and live normally.' },
      { q: 'Is asthma dangerous?', a: 'Most asthma is manageable, but a severe attack can be life-threatening. Learn your warning signs and keep a reliever inhaler handy.' },
    ],
  },
  {
    slug: 'copd',
    name: 'COPD (Chronic Obstructive Pulmonary Disease)',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'COPD is long-term lung damage that makes breathing harder over time, usually from smoking or long-term smoke exposure. It cannot be reversed but can be slowed and managed.',
    causes: [
      'Smoking (the most common cause)',
      'Long-term exposure to biomass/cooking smoke or dust',
      'Air pollution and workplace fumes',
      'Repeated chest infections in childhood',
      'A rare inherited enzyme deficiency (alpha-1 antitrypsin)',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness on activity'],
      ['symptoms/cough', 'Long-term cough with phlegm'],
      ['symptoms/wheezing', 'Wheezing'],
      ['symptoms/fatigue', 'Tiredness'],
      [null, 'Frequent chest infections'],
    ],
    tests: [
      [null, 'Spirometry (lung function test)'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT chest scan'],
      [null, 'Blood oxygen (pulse oximetry)'],
    ],
    treatment: [
      'Stopping smoking is the single most important step',
      'Inhalers (bronchodilators, sometimes inhaled steroids)',
      'Pulmonary rehabilitation exercise programmes',
      'Vaccines (flu, pneumonia) to prevent infections',
      'Oxygen therapy in advanced cases',
    ],
    whenToSee: [
      'Sudden severe breathlessness — call your local emergency number now',
      'Chest pain, blue lips or confusion — emergency',
      'Coughing up more or discoloured phlegm with fever',
      'Symptoms getting steadily worse or interfering with daily life',
    ],
    faqs: [
      { q: 'Is COPD the same as asthma?', a: 'No. COPD is usually caused by smoking and mainly affects older adults with permanent airway damage, while asthma symptoms come and go and are often reversible.' },
      { q: 'Does quitting smoking help if I already have COPD?', a: 'Yes. Stopping smoking at any stage slows further lung damage and is the most effective treatment.' },
    ],
  },
  {
    slug: 'pneumonia',
    name: 'Pneumonia',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Pneumonia is an infection that inflames the air sacs of one or both lungs, which can fill with fluid. It ranges from mild to serious, especially in the very young, elderly or those with other illnesses.',
    causes: [
      'Bacterial infection (most common)',
      'Viral infection (including influenza and COVID-19)',
      'Fungal infection (less common)',
      'Breathing in food, drink or vomit (aspiration)',
      'Weak immunity or existing lung disease',
    ],
    symptoms: [
      ['symptoms/cough', 'Cough, sometimes with phlegm'],
      ['symptoms/fever', 'Fever and chills'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/chest-pain', 'Chest pain when breathing'],
      ['symptoms/fatigue', 'Tiredness and weakness'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      ['blood-tests/crp', 'CRP'],
      [null, 'Sputum test'],
      [null, 'Blood oxygen (pulse oximetry)'],
    ],
    treatment: [
      'Antibiotics for bacterial pneumonia',
      'Rest, fluids and fever/pain relief',
      'Antivirals in some viral cases',
      'Hospital care with oxygen if severe',
      'Vaccination helps prevent some types',
    ],
    whenToSee: [
      'Severe breathlessness or blue lips — call your local emergency number now',
      'Confusion, chest pain or coughing up blood — urgent care',
      'High fever not settling with treatment',
      'Symptoms in a baby, elderly or immunocompromised person',
    ],
    faqs: [
      { q: 'Is pneumonia contagious?', a: 'The germs that cause it can spread through coughs and sneezes, though not everyone exposed will develop pneumonia. Good hygiene and vaccines help.' },
      { q: 'How long does recovery take?', a: 'Many people improve within a week or two, but tiredness and cough can linger for a month or more, especially after severe illness.' },
    ],
  },
  {
    slug: 'acute-bronchitis',
    name: 'Bronchitis',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Bronchitis is inflammation of the airways that carry air to the lungs, usually after a cold or chest infection. Acute bronchitis is common and usually clears on its own.',
    causes: [
      'Viral infection (most acute cases)',
      'Bacterial infection (less common)',
      'Smoking and secondhand smoke',
      'Air pollution, dust or fumes',
      'Following a cold or flu',
    ],
    symptoms: [
      ['symptoms/cough', 'Persistent cough, often with mucus'],
      ['symptoms/sore-throat', 'Sore throat'],
      ['symptoms/wheezing', 'Wheezing'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/chest-pain', 'Chest discomfort when coughing'],
    ],
    tests: [
      [null, 'Usually diagnosed by symptoms and examination'],
      ['x-ray-explained', 'Chest X-ray (to rule out pneumonia)'],
      [null, 'Sputum test if needed'],
      ['blood-tests/crp', 'CRP if infection is suspected'],
    ],
    treatment: [
      'Rest and plenty of fluids',
      'Fever and pain relief as needed',
      'Warm drinks and honey may ease cough',
      'Antibiotics only if a bacterial cause is likely',
      'Avoid smoke and irritants',
    ],
    whenToSee: [
      'Cough lasting more than 3 weeks',
      'Coughing up blood — see a doctor urgently',
      'High fever, severe breathlessness or chest pain — urgent care',
      'Repeated episodes or an existing lung/heart condition',
    ],
    faqs: [
      { q: 'Do I need antibiotics for bronchitis?', a: 'Usually no. Most acute bronchitis is viral and antibiotics do not help. They are only used if a bacterial infection is likely.' },
      { q: 'How is it different from pneumonia?', a: 'Bronchitis inflames the airways, while pneumonia infects the lung tissue itself and is generally more serious. A chest X-ray can tell them apart.' },
    ],
  },
  {
    slug: 'tuberculosis',
    name: 'Tuberculosis (TB)',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Tuberculosis is a bacterial infection that most often affects the lungs but can spread to other parts of the body. It is common in India and fully curable with a proper course of medicines.',
    causes: [
      'Infection with Mycobacterium tuberculosis bacteria',
      'Spread through the air from an infected person coughing',
      'Close, prolonged contact in crowded spaces',
      'Weak immunity (HIV, diabetes, malnutrition)',
      'Latent TB reactivating years later',
    ],
    symptoms: [
      ['symptoms/cough', 'Cough lasting more than 2-3 weeks'],
      ['symptoms/night-sweats', 'Night sweats'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/fever', 'Low-grade fever'],
      ['symptoms/fatigue', 'Tiredness'],
      [null, 'Coughing up blood'],
    ],
    tests: [
      [null, 'Sputum test (for TB bacteria)'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'GeneXpert / molecular TB test'],
      [null, 'Tuberculin skin test / IGRA blood test'],
    ],
    treatment: [
      'A full course of anti-TB antibiotics, usually 6 months',
      'Taking every dose without stopping early is essential',
      'Directly observed treatment (DOTS) programmes in India',
      'Good nutrition and treating conditions that lower immunity',
      'Testing and, if needed, treating close contacts',
    ],
    whenToSee: [
      'Cough lasting more than 2-3 weeks — get tested',
      'Coughing up blood — see a doctor urgently',
      'Severe breathlessness or chest pain — urgent care',
      'Weight loss with fever and night sweats',
    ],
    faqs: [
      { q: 'Is TB curable?', a: 'Yes. TB is fully curable with the correct medicines taken for the full course, usually about 6 months. Stopping early can cause drug-resistant TB.' },
      { q: 'Is TB testing free in India?', a: 'Diagnosis and treatment are provided free through government programmes. Ask at any government health centre.' },
    ],
  },
  {
    slug: 'pulmonary-embolism',
    name: 'Pulmonary Embolism',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'A pulmonary embolism is a blood clot that blocks an artery in the lungs, usually travelling up from a leg vein. It is a medical emergency that needs urgent treatment.',
    causes: [
      'A clot from a deep vein (often the leg) travelling to the lungs',
      'Long periods of immobility (long flights, bed rest, surgery)',
      'Recent surgery, injury or fracture',
      'Cancer or clotting disorders',
      'Pregnancy or some hormone medicines',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Sudden shortness of breath'],
      ['symptoms/chest-pain', 'Chest pain, worse on breathing in'],
      ['symptoms/heart-palpitations', 'Fast heartbeat'],
      ['symptoms/leg-swelling', 'Swelling or pain in one leg'],
      ['symptoms/fainting', 'Feeling faint or collapsing'],
      [null, 'Coughing up blood'],
    ],
    tests: [
      ['blood-tests/d-dimer', 'D-dimer blood test'],
      [null, 'CT pulmonary angiogram (CTPA)'],
      ['ecg-explained', 'ECG'],
      [null, 'Leg vein ultrasound'],
    ],
    treatment: [
      'Blood-thinning (anticoagulant) medicines',
      'Urgent clot-busting treatment in severe cases',
      'Oxygen and monitoring in hospital',
      'Treating the underlying cause and reducing future risk',
      'Compression stockings and movement to prevent leg clots',
    ],
    whenToSee: [
      'Sudden breathlessness, chest pain or collapse — call your local emergency number now',
      'Coughing up blood with breathlessness — emergency',
      'A swollen, painful leg with breathing symptoms — urgent',
      'Symptoms after surgery or a long journey — seek help fast',
    ],
    faqs: [
      { q: 'How serious is a pulmonary embolism?', a: 'It can be life-threatening and needs emergency treatment. With prompt blood thinners, most people recover well.' },
      { q: 'How can I lower my risk on long journeys?', a: 'Move your legs regularly, walk when possible, stay hydrated and, if you are high risk, ask your doctor about prevention.' },
    ],
  },
  {
    slug: 'obstructive-sleep-apnoea',
    name: 'Sleep Apnoea',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Obstructive sleep apnoea is when breathing repeatedly stops and starts during sleep because the throat narrows. It causes poor sleep and daytime tiredness, and is treatable.',
    causes: [
      'Relaxed throat muscles blocking the airway in sleep',
      'Being overweight, especially around the neck',
      'Large tonsils or a set-back jaw',
      'Alcohol and sedatives before bed',
      'Smoking and nasal congestion',
    ],
    symptoms: [
      [null, 'Loud snoring'],
      [null, 'Gasping or pauses in breathing during sleep'],
      ['symptoms/fatigue', 'Daytime sleepiness and tiredness'],
      ['symptoms/headache', 'Morning headaches'],
      [null, 'Poor concentration and irritability'],
    ],
    tests: [
      [null, 'Sleep study (polysomnography)'],
      [null, 'Home sleep apnoea test'],
      [null, 'Epworth sleepiness questionnaire'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid test (to rule out other causes)'],
    ],
    treatment: [
      'Weight loss and avoiding alcohol before bed',
      'Sleeping on your side',
      'CPAP machine that keeps the airway open at night',
      'Mouth (mandibular) devices for milder cases',
      'Surgery in selected cases',
    ],
    whenToSee: [
      'Falling asleep while driving — stop driving and seek help urgently',
      'Witnessed breathing pauses with gasping at night',
      'Severe daytime sleepiness affecting daily life',
      'Morning headaches with high blood pressure',
    ],
    faqs: [
      { q: 'Is snoring the same as sleep apnoea?', a: 'Not always. Snoring is common, but if it comes with breathing pauses, gasping and daytime tiredness, sleep apnoea may be the cause.' },
      { q: 'Can sleep apnoea affect my health long-term?', a: 'Untreated, it can raise blood pressure and strain the heart. Treatment improves sleep, energy and long-term health.' },
    ],
  },
  {
    slug: 'covid-19',
    name: 'COVID-19',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'COVID-19 is a viral infection caused by the SARS-CoV-2 coronavirus. Most people have mild symptoms, but it can be serious in older adults and those with other conditions.',
    causes: [
      'Infection with the SARS-CoV-2 virus',
      'Spread through respiratory droplets and close contact',
      'Touching contaminated surfaces then the face',
      'Crowded, poorly ventilated indoor spaces',
      'Higher risk if unvaccinated or immunocompromised',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever'],
      ['symptoms/cough', 'Cough'],
      ['symptoms/sore-throat', 'Sore throat'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      [null, 'Loss of taste or smell'],
    ],
    tests: [
      [null, 'Rapid antigen test (RAT)'],
      [null, 'RT-PCR swab test'],
      [null, 'Blood oxygen (pulse oximetry)'],
      ['x-ray-explained', 'Chest X-ray if severe'],
    ],
    treatment: [
      'Rest, fluids and fever/pain relief for mild cases',
      'Isolating to avoid spreading the virus',
      'Monitoring oxygen levels at home',
      'Antivirals for those at higher risk',
      'Hospital oxygen or care if breathing worsens',
    ],
    whenToSee: [
      'Severe breathlessness or oxygen level below 94% — call your local emergency number now',
      'Chest pain, confusion or blue lips — emergency',
      'Symptoms rapidly worsening, especially if high-risk',
      'Unable to keep fluids down or very drowsy',
    ],
    faqs: [
      { q: 'Do vaccines still help?', a: 'Yes. Vaccines lower the risk of severe illness and hospitalisation, especially for older and high-risk people. Boosters may be advised.' },
      { q: 'What is long COVID?', a: 'Some people have lasting symptoms like fatigue, breathlessness or brain fog for weeks or months after infection. See a doctor if symptoms persist.' },
    ],
  },
  {
    slug: 'interstitial-lung-disease',
    name: 'Interstitial Lung Disease (ILD)',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Interstitial lung disease is a group of conditions that cause scarring and stiffening of the lung tissue, making it harder to breathe. Early diagnosis helps guide treatment.',
    causes: [
      'Long-term dust exposure (silica, asbestos, farming, birds)',
      'Autoimmune conditions like rheumatoid arthritis',
      'Some medicines and radiation',
      'Idiopathic (no clear cause) pulmonary fibrosis',
      'Ongoing lung inflammation',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness, worse with activity'],
      ['symptoms/cough', 'Persistent dry cough'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/unexplained-weight-loss', 'Weight loss'],
      [null, 'Clubbing of the fingertips'],
    ],
    tests: [
      [null, 'High-resolution CT chest (HRCT)'],
      [null, 'Lung function tests (spirometry, diffusion)'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Blood oxygen (pulse oximetry)'],
    ],
    treatment: [
      'Treating the underlying cause where possible',
      'Avoiding the dust or trigger responsible',
      'Medicines to reduce inflammation or slow scarring',
      'Pulmonary rehabilitation and oxygen therapy',
      'Lung transplant considered in severe cases',
    ],
    whenToSee: [
      'Worsening breathlessness — call your local emergency number now if severe',
      'A dry cough lasting more than a few weeks',
      'Breathlessness with an autoimmune condition or dust exposure',
      'Low oxygen levels or bluish lips',
    ],
    faqs: [
      { q: 'Can ILD be reversed?', a: 'Scarring cannot usually be reversed, but the right treatment can slow progression and improve symptoms, especially when started early.' },
      { q: 'Is ILD the same as COPD?', a: 'No. COPD narrows the airways, while ILD stiffens and scars the lung tissue itself. They need different tests and treatments.' },
    ],
  },
  {
    slug: 'pleural-effusion',
    name: 'Pleural Effusion',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'A pleural effusion is a build-up of fluid between the lung and the chest wall. It is a sign of an underlying condition, so finding the cause is important.',
    causes: [
      'Heart failure (most common cause)',
      'Infections such as pneumonia or TB',
      'Cancer affecting the lung or lining',
      'Liver or kidney disease',
      'Blood clots in the lung',
    ],
    symptoms: [
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/chest-pain', 'Chest pain, worse on breathing'],
      ['symptoms/cough', 'Dry cough'],
      [null, 'Discomfort lying flat'],
      ['symptoms/fever', 'Fever if caused by infection'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Chest ultrasound'],
      [null, 'CT chest scan'],
      [null, 'Fluid sampling (pleural tap)'],
    ],
    treatment: [
      'Treating the underlying cause',
      'Draining the fluid to ease breathing',
      'Antibiotics if caused by infection',
      'Diuretics for heart-related fluid',
      'Procedures to stop fluid returning in some cases',
    ],
    whenToSee: [
      'Severe breathlessness — call your local emergency number now',
      'Chest pain with fever and cough — urgent care',
      'Breathlessness with known heart, liver or kidney disease',
      'Symptoms that keep coming back',
    ],
    faqs: [
      { q: 'Is draining the fluid painful?', a: 'The area is numbed first, so it is usually only mildly uncomfortable, and breathing often improves quickly afterwards.' },
      { q: 'Will the fluid come back?', a: 'It can, if the underlying cause is not treated. Managing the root condition is the key to preventing recurrence.' },
    ],
  },
  {
    slug: 'lung-cancer',
    name: 'Lung Cancer',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Lung cancer is an abnormal growth of cells in the lungs. It is strongly linked to smoking, and outcomes are much better when it is found early.',
    causes: [
      'Smoking (by far the biggest risk)',
      'Secondhand smoke exposure',
      'Air pollution and biomass smoke',
      'Workplace exposure (asbestos, radon, some chemicals)',
      'Family history in some cases',
    ],
    symptoms: [
      ['symptoms/cough', 'A cough that will not go away'],
      [null, 'Coughing up blood'],
      ['symptoms/chest-pain', 'Chest pain'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Tiredness'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT chest scan'],
      [null, 'Biopsy (tissue sample)'],
      [null, 'PET scan for staging'],
    ],
    treatment: [
      'Treatment depends on the type and stage',
      'Surgery to remove the tumour where possible',
      'Radiotherapy and chemotherapy',
      'Targeted therapy or immunotherapy in suitable cases',
      'Supportive care to manage symptoms',
    ],
    whenToSee: [
      'Coughing up blood — see a doctor urgently',
      'A cough lasting more than 3 weeks',
      'Unexplained weight loss with breathlessness or chest pain',
      'New or changing symptoms in a current or former smoker',
    ],
    faqs: [
      { q: 'Can non-smokers get lung cancer?', a: 'Yes. While smoking is the main cause, non-smokers can develop it from pollution, radon, workplace exposures or other factors.' },
      { q: 'Why does early detection matter so much?', a: 'Lung cancer found early is more likely to be treatable, sometimes with surgery, giving much better outcomes than late-stage disease.' },
    ],
  },
  {
    slug: 'bronchiectasis',
    name: 'Bronchiectasis',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Bronchiectasis is a long-term condition where the airways become widened and scarred, so mucus builds up and infections keep coming back. It is managed with airway clearance and treating infections.',
    causes: [
      'Damage from past infections (pneumonia, TB, whooping cough)',
      'Immune system problems',
      'Cystic fibrosis',
      'Blocked airways or inhaled objects',
      'Sometimes no clear cause is found',
    ],
    symptoms: [
      ['symptoms/cough', 'Daily cough with lots of phlegm'],
      [null, 'Repeated chest infections'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/fatigue', 'Tiredness'],
      [null, 'Coughing up blood at times'],
    ],
    tests: [
      [null, 'High-resolution CT chest (HRCT)'],
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Sputum test'],
      [null, 'Lung function tests'],
    ],
    treatment: [
      'Daily airway clearance (physiotherapy, breathing techniques)',
      'Prompt antibiotics for flare-ups',
      'Treating the underlying cause where found',
      'Vaccinations to prevent infections',
      'Exercise and pulmonary rehabilitation',
    ],
    whenToSee: [
      'Coughing up a large amount of blood — call your local emergency number now',
      'High fever with more or discoloured phlegm',
      'Sudden severe breathlessness or chest pain',
      'Flare-ups becoming more frequent',
    ],
    faqs: [
      { q: 'Is bronchiectasis the same as COPD?', a: 'No, though they can occur together. Bronchiectasis is widened, scarred airways that trap mucus, and airway clearance is a key part of care.' },
      { q: 'Why do infections keep coming back?', a: 'Mucus pools in the damaged airways and becomes a breeding ground for germs. Regular clearance helps reduce infections.' },
    ],
  },
  {
    slug: 'pneumothorax',
    name: 'Pneumothorax (Collapsed Lung)',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'A pneumothorax is when air leaks into the space around the lung, causing it to collapse partly or fully. It can happen suddenly and sometimes needs urgent treatment.',
    causes: [
      'A spontaneous air leak, often in tall, slim young people',
      'Chest injury or a broken rib',
      'Underlying lung disease (COPD, asthma)',
      'Medical procedures on the chest',
      'Smoking increases the risk',
    ],
    symptoms: [
      ['symptoms/chest-pain', 'Sudden sharp chest pain on one side'],
      ['symptoms/shortness-of-breath', 'Sudden breathlessness'],
      ['symptoms/heart-palpitations', 'Fast heartbeat'],
      [null, 'Bluish skin if severe'],
      ['symptoms/fatigue', 'Tiredness'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT chest scan'],
      [null, 'Chest ultrasound'],
      [null, 'Blood oxygen (pulse oximetry)'],
    ],
    treatment: [
      'Small ones may heal on their own with monitoring',
      'Removing the air with a needle or chest drain',
      'Oxygen therapy',
      'Treating any underlying lung condition',
      'Procedures to prevent recurrence if it happens repeatedly',
    ],
    whenToSee: [
      'Sudden severe chest pain and breathlessness — call your local emergency number now',
      'Blue lips, collapse or worsening breathing — emergency',
      'Any breathing difficulty after a chest injury',
      'A previous collapsed lung with new symptoms',
    ],
    faqs: [
      { q: 'Can a collapsed lung heal by itself?', a: 'A small pneumothorax may reabsorb on its own with monitoring, but larger ones usually need the air drained.' },
      { q: 'Can I fly or dive afterwards?', a: 'Flying and especially scuba diving can be risky for a time after a pneumothorax. Get specific advice from your doctor first.' },
    ],
  },
  {
    slug: 'chronic-cough',
    name: 'Chronic Cough',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'A chronic cough is one that lasts more than about eight weeks in adults. It is a symptom rather than a disease, and finding the cause is the key to treating it.',
    causes: [
      'Post-nasal drip from allergies or sinus problems',
      'Asthma or airway sensitivity',
      'Acid reflux (GERD)',
      'Smoking or air pollution',
      'Some blood pressure medicines',
      'Lingering effect of an infection',
    ],
    symptoms: [
      ['symptoms/cough', 'Persistent cough'],
      ['symptoms/sore-throat', 'Throat irritation'],
      ['symptoms/heartburn', 'Heartburn or acid taste'],
      ['symptoms/wheezing', 'Wheezing'],
      [null, 'Runny or blocked nose'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'Spirometry (lung function test)'],
      [null, 'Allergy assessment'],
      [null, 'Sputum test if needed'],
    ],
    treatment: [
      'Treating the underlying cause (reflux, allergy, asthma)',
      'Stopping smoking and avoiding irritants',
      'Reviewing medicines that can cause cough',
      'Simple soothing measures like warm drinks and honey',
      'Referral if no cause is found',
    ],
    whenToSee: [
      'Coughing up blood — see a doctor urgently',
      'Cough with weight loss, night sweats or breathlessness',
      'A cough lasting more than 3 weeks that is not improving',
      'Chest pain or a change in a long-standing cough',
    ],
    faqs: [
      { q: 'When is a cough considered chronic?', a: 'In adults, a cough lasting more than about eight weeks is called chronic and is worth investigating for a cause.' },
      { q: 'Can medicines cause a cough?', a: 'Yes. Some blood pressure medicines (ACE inhibitors) are a well-known cause. Tell your doctor about all your medicines.' },
    ],
  },
  {
    slug: 'allergic-rhinitis',
    name: 'Allergic Rhinitis (Hay Fever)',
    dept: ['pulmonology', 'Pulmonology'],
    lede: 'Allergic rhinitis is inflammation of the nose caused by an allergic reaction to things like pollen, dust or pet dander. It is very common and can affect sleep, work and asthma.',
    causes: [
      'Pollen from grass, trees or weeds (seasonal)',
      'Dust mites (year-round)',
      'Pet dander and mould',
      'A tendency to allergies (atopy) that runs in families',
      'Air pollution can worsen symptoms',
    ],
    symptoms: [
      [null, 'Sneezing'],
      [null, 'Runny or blocked nose'],
      ['symptoms/itching', 'Itchy nose, eyes or throat'],
      [null, 'Watery, red eyes'],
      ['symptoms/headache', 'Sinus pressure or headache'],
    ],
    tests: [
      [null, 'Usually diagnosed from symptoms and history'],
      [null, 'Skin prick allergy test'],
      [null, 'Specific IgE blood test'],
      [null, 'Nasal examination'],
    ],
    treatment: [
      'Avoiding known triggers where possible',
      'Saline nasal rinses',
      'Antihistamines to ease sneezing and itching',
      'Steroid nasal sprays for blocked, inflamed noses',
      'Allergen immunotherapy for stubborn cases',
    ],
    whenToSee: [
      'Symptoms not controlled despite treatment',
      'Wheezing or breathlessness (asthma may be involved) — urgent if severe',
      'Facial pain and fever suggesting a sinus infection',
      'Symptoms badly affecting sleep or daily life',
    ],
    faqs: [
      { q: 'Is hay fever the same as a cold?', a: 'No. Hay fever is an allergic reaction with itching and sneezing that lasts as long as you are exposed, while a cold is a virus that clears in a week or so.' },
      { q: 'Can allergic rhinitis trigger asthma?', a: 'Yes. The two are linked, and treating the nose often helps asthma control. Tell your doctor if you also wheeze or get breathless.' },
    ],
  },

  // ===================== INFECTIOUS DISEASES =====================
  {
    slug: 'typhoid',
    name: 'Typhoid Fever',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Typhoid is a bacterial infection spread through contaminated food and water, common in parts of India. It causes prolonged fever and needs antibiotics.',
    causes: [
      'Infection with Salmonella Typhi bacteria',
      'Contaminated food or drinking water',
      'Poor sanitation and hygiene',
      'Eating food handled by an infected person',
      'Close contact with a carrier',
    ],
    symptoms: [
      ['symptoms/fever', 'Prolonged, stepwise fever'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/abdominal-pain', 'Abdominal pain'],
      ['symptoms/fatigue', 'Weakness and tiredness'],
      ['symptoms/constipation', 'Constipation or diarrhoea'],
      [null, 'Poor appetite'],
    ],
    tests: [
      ['blood-tests/widal-test-typhoid', 'Widal test'],
      [null, 'Blood culture (most reliable)'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      [null, 'Stool/urine culture'],
    ],
    treatment: [
      'A full course of antibiotics as prescribed',
      'Rest, fluids and fever control',
      'Light, easily digested food',
      'Completing the whole course to prevent relapse',
      'Vaccination and safe water/food to prevent it',
    ],
    whenToSee: [
      'Severe abdominal pain or bloody stools — urgent care',
      'Confusion, drowsiness or persistent vomiting — emergency',
      'Fever lasting more than a few days without improving',
      'Signs of dehydration or inability to keep fluids down',
    ],
    faqs: [
      { q: 'How can I avoid typhoid?', a: 'Drink safe or boiled water, eat freshly cooked hot food, wash hands well and consider vaccination, especially before travel to high-risk areas.' },
      { q: 'Is the Widal test enough to diagnose typhoid?', a: 'The Widal test can support the diagnosis but is not fully reliable on its own. A blood culture is the more accurate test.' },
    ],
  },
  {
    slug: 'dengue-fever',
    name: 'Dengue Fever',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Dengue is a viral infection spread by day-biting Aedes mosquitoes, common in India during and after the monsoon. Most people recover, but warning signs need urgent care.',
    causes: [
      'Dengue virus spread by Aedes mosquito bites',
      'Mosquitoes breeding in clean, standing water',
      'Peak spread during and after monsoon',
      'Being bitten by an infected mosquito',
      'Living or travelling in areas with outbreaks',
    ],
    symptoms: [
      ['symptoms/fever', 'Sudden high fever'],
      ['symptoms/headache', 'Severe headache and pain behind the eyes'],
      ['symptoms/joint-pain', 'Severe joint and muscle pain'],
      ['symptoms/skin-rash', 'Rash'],
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
      ['symptoms/fatigue', 'Extreme tiredness'],
    ],
    tests: [
      ['blood-tests/dengue-test', 'Dengue test (NS1/antibody)'],
      ['blood-tests/platelet-count', 'Platelet count'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      [null, 'Haematocrit (PCV)'],
    ],
    treatment: [
      'Rest and plenty of fluids to prevent dehydration',
      'Paracetamol for fever (avoid aspirin/ibuprofen)',
      'Monitoring platelet count and warning signs',
      'Hospital care with fluids if warning signs appear',
      'Mosquito control to prevent spread',
    ],
    whenToSee: [
      'Bleeding gums, nose or blood in vomit/stool — call your local emergency number now',
      'Severe abdominal pain, persistent vomiting or restlessness — urgent',
      'Cold, clammy skin or fainting — emergency',
      'Warning signs typically appear as the fever settles',
    ],
    faqs: [
      { q: 'Why avoid aspirin and ibuprofen in dengue?', a: 'They can increase the risk of bleeding, which is already a concern in dengue. Paracetamol is preferred for fever and pain.' },
      { q: 'When are the danger days in dengue?', a: 'Warning signs often appear around days 3-7, as the fever comes down. This is when close monitoring matters most.' },
    ],
  },
  {
    slug: 'malaria',
    name: 'Malaria',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Malaria is a parasite infection spread by night-biting Anopheles mosquitoes. It causes cycles of fever with chills and needs prompt treatment, as some types can be severe.',
    causes: [
      'Plasmodium parasites spread by Anopheles mosquito bites',
      'Mosquitoes active mainly at night',
      'Living or travelling in malaria-prone areas',
      'Rarely, spread through infected blood',
      'Higher risk without mosquito protection',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever with chills and shivering'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/night-sweats', 'Sweating'],
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
      ['symptoms/fatigue', 'Tiredness and body aches'],
    ],
    tests: [
      ['blood-tests/malaria-test', 'Malaria test'],
      [null, 'Blood smear (microscopy)'],
      [null, 'Rapid diagnostic test (RDT)'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
    ],
    treatment: [
      'Antimalarial medicines based on the parasite type',
      'Completing the full course as prescribed',
      'Fluids and fever control',
      'Urgent hospital care for severe malaria',
      'Mosquito nets and repellents to prevent it',
    ],
    whenToSee: [
      'Confusion, drowsiness or fits — call your local emergency number now',
      'Difficulty breathing, very little urine or yellow eyes — urgent',
      'High fever after travel to a malaria area — get tested fast',
      'Persistent vomiting or inability to take medicine',
    ],
    faqs: [
      { q: 'How soon after a mosquito bite can malaria appear?', a: 'Symptoms usually start 1-4 weeks after the bite, but some types can appear months later. Mention any travel to your doctor.' },
      { q: 'Can malaria come back?', a: 'Some types (like P. vivax) can relapse from dormant liver forms. Your doctor may prescribe extra treatment to prevent this.' },
    ],
  },
  {
    slug: 'chikungunya',
    name: 'Chikungunya',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Chikungunya is a viral infection spread by the same mosquitoes as dengue. It causes fever and severe joint pain that can linger for weeks or months.',
    causes: [
      'Chikungunya virus spread by Aedes mosquito bites',
      'Mosquitoes breeding in standing water',
      'Common during and after monsoon',
      'Being bitten by an infected mosquito',
      'Outbreaks in tropical regions',
    ],
    symptoms: [
      ['symptoms/fever', 'Sudden fever'],
      ['symptoms/joint-pain', 'Severe joint pain, often in hands and feet'],
      ['symptoms/skin-rash', 'Rash'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/fatigue', 'Tiredness'],
    ],
    tests: [
      [null, 'Chikungunya antibody/PCR test'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      ['blood-tests/dengue-test', 'Dengue test (to rule out dengue)'],
      ['blood-tests/crp', 'CRP'],
    ],
    treatment: [
      'Rest and plenty of fluids',
      'Paracetamol for fever and joint pain',
      'Avoiding aspirin until dengue is ruled out',
      'Gentle movement and physiotherapy for joint stiffness',
      'Mosquito protection to prevent spread',
    ],
    whenToSee: [
      'High fever with bleeding or severe abdominal pain — urgent (to exclude dengue)',
      'Joint pain that is disabling or lasts many weeks',
      'Persistent vomiting or signs of dehydration',
      'Symptoms in the very young, elderly or pregnant',
    ],
    faqs: [
      { q: 'How long does the joint pain last?', a: 'Most people recover in a week or two, but in some the joint pain and stiffness can last for months. Gentle exercise helps.' },
      { q: 'How is it different from dengue?', a: 'Both cause fever, but chikungunya is known for severe, lasting joint pain, while dengue carries a higher risk of bleeding. Testing tells them apart.' },
    ],
  },
  {
    slug: 'hepatitis-a',
    name: 'Hepatitis A',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Hepatitis A is a viral liver infection spread through contaminated food and water. It usually clears on its own and does not cause long-term liver damage.',
    causes: [
      'Hepatitis A virus in contaminated food or water',
      'Poor sanitation and hygiene',
      'Eating raw or undercooked shellfish',
      'Close contact with an infected person',
      'Common where clean water is limited',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
      ['symptoms/abdominal-pain', 'Pain in the upper right abdomen'],
      [null, 'Yellow skin and eyes (jaundice)'],
      [null, 'Dark urine and pale stools'],
    ],
    tests: [
      ['blood-tests/liver-function-test-lft', 'Liver function test (LFT)'],
      [null, 'Hepatitis A antibody test'],
      ['blood-tests/bilirubin', 'Bilirubin'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
    ],
    treatment: [
      'Rest and plenty of fluids',
      'Eating light, easily digested food',
      'Avoiding alcohol and unnecessary medicines',
      'Most people recover fully in a few weeks',
      'Vaccination and safe food/water to prevent it',
    ],
    whenToSee: [
      'Deep jaundice with confusion or drowsiness — urgent care',
      'Persistent vomiting or inability to keep fluids down',
      'Severe abdominal pain or easy bruising/bleeding',
      'Symptoms worsening rather than improving',
    ],
    faqs: [
      { q: 'Does hepatitis A cause long-term liver damage?', a: 'No. Unlike hepatitis B and C, hepatitis A does not become chronic and usually clears completely with rest.' },
      { q: 'Is there a vaccine?', a: 'Yes, a safe and effective vaccine is available and is worth considering, especially before travel to high-risk areas.' },
    ],
  },
  {
    slug: 'hepatitis-b',
    name: 'Hepatitis B',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Hepatitis B is a viral liver infection spread through blood and body fluids. It can be short-lived or become long-term, so testing and vaccination are important.',
    causes: [
      'Hepatitis B virus in blood and body fluids',
      'From mother to baby at birth',
      'Unprotected sex with an infected person',
      'Sharing needles or unsterile equipment',
      'Unscreened blood or contaminated instruments',
    ],
    symptoms: [
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/nausea-and-vomiting', 'Nausea'],
      ['symptoms/abdominal-pain', 'Upper abdominal pain'],
      [null, 'Yellow skin and eyes (jaundice)'],
      [null, 'Dark urine'],
      ['symptoms/joint-pain', 'Joint pain'],
    ],
    tests: [
      ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B surface antigen (HBsAg)'],
      ['blood-tests/liver-function-test-lft', 'Liver function test (LFT)'],
      [null, 'Hepatitis B viral load'],
      [null, 'Liver ultrasound'],
    ],
    treatment: [
      'Many acute cases clear on their own with rest',
      'Antiviral medicines for chronic infection',
      'Regular monitoring of the liver',
      'Avoiding alcohol to protect the liver',
      'Vaccination and safe practices to prevent it',
    ],
    whenToSee: [
      'Jaundice with confusion or drowsiness — urgent care',
      'Vomiting blood or black stools — emergency',
      'Known exposure to infected blood or fluids — get tested',
      'Long-standing tiredness with abnormal liver tests',
    ],
    faqs: [
      { q: 'Can hepatitis B be cured?', a: 'Chronic hepatitis B usually cannot be fully cured, but antiviral medicines control it well and protect the liver. Many acute cases clear on their own.' },
      { q: 'Should my family be vaccinated?', a: 'Yes. The vaccine is safe and effective. Close contacts and babies of infected mothers should be protected.' },
    ],
  },
  {
    slug: 'hepatitis-c',
    name: 'Hepatitis C',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Hepatitis C is a viral liver infection spread mainly through blood. It often causes no symptoms for years but is now curable with modern antiviral tablets.',
    causes: [
      'Hepatitis C virus spread through blood',
      'Sharing needles or unsterile equipment',
      'Unscreened blood transfusions (mainly in the past)',
      'Unsterile medical, tattoo or piercing equipment',
      'Less commonly, from mother to baby or through sex',
    ],
    symptoms: [
      ['symptoms/fatigue', 'Tiredness (often the only sign)'],
      ['symptoms/joint-pain', 'Joint or muscle aches'],
      ['symptoms/nausea-and-vomiting', 'Nausea'],
      ['symptoms/abdominal-pain', 'Upper abdominal discomfort'],
      [null, 'Jaundice in some cases'],
    ],
    tests: [
      [null, 'Hepatitis C antibody test'],
      [null, 'Hepatitis C RNA (viral load)'],
      ['blood-tests/liver-function-test-lft', 'Liver function test (LFT)'],
      [null, 'Liver ultrasound / fibroscan'],
    ],
    treatment: [
      'Modern antiviral tablets can cure most people',
      'A short course, usually 8-12 weeks',
      'Regular monitoring of the liver',
      'Avoiding alcohol to protect the liver',
      'Safe practices to prevent reinfection',
    ],
    whenToSee: [
      'Known exposure to infected blood — get tested',
      'Jaundice, confusion or vomiting blood — urgent care',
      'Persistent tiredness with abnormal liver tests',
      'A previous risk (old transfusion, needle sharing)',
    ],
    faqs: [
      { q: 'Is hepatitis C really curable now?', a: 'Yes. Modern antiviral tablets cure most people in a few months. Getting tested is the key first step.' },
      { q: 'Can I catch it again after cure?', a: 'Being cured does not make you immune, so avoiding future exposure to infected blood is important to prevent reinfection.' },
    ],
  },
  {
    slug: 'hiv-aids',
    name: 'HIV / AIDS',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'HIV is a virus that weakens the immune system. With modern treatment, people with HIV can live long, healthy lives and cannot pass it on when the virus is undetectable.',
    causes: [
      'HIV spread through blood, sexual fluids and breast milk',
      'Unprotected sex with an infected person',
      'Sharing needles or unsterile equipment',
      'From mother to baby during birth or breastfeeding',
      'Unscreened blood (rare where blood is tested)',
    ],
    symptoms: [
      ['symptoms/fever', 'Flu-like illness soon after infection'],
      ['symptoms/swollen-lymph-nodes', 'Swollen lymph nodes'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/unexplained-weight-loss', 'Weight loss (later stages)'],
      [null, 'Frequent infections (later stages)'],
    ],
    tests: [
      [null, 'HIV antibody/antigen test'],
      [null, 'HIV viral load'],
      [null, 'CD4 cell count'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
    ],
    treatment: [
      'Antiretroviral therapy (ART) taken daily',
      'Treatment keeps the virus under control',
      'Undetectable virus means it cannot be passed on sexually',
      'Regular monitoring of viral load and CD4 count',
      'Prevention: condoms, safe needles, and PrEP for high risk',
    ],
    whenToSee: [
      'Possible exposure to HIV — seek care within 72 hours for PEP',
      'Persistent fever, weight loss or repeated infections',
      'A flu-like illness after a risk event — get tested',
      'Any concern about your HIV status — testing is confidential',
    ],
    faqs: [
      { q: 'Is HIV a death sentence today?', a: 'No. With modern treatment, people with HIV can expect a near-normal life span and good health.' },
      { q: 'What does undetectable = untransmittable mean?', a: 'When treatment keeps the virus so low it cannot be measured, HIV cannot be passed on through sex. This is called U=U.' },
    ],
  },
  {
    slug: 'influenza',
    name: 'Influenza (Flu)',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Influenza is a viral infection of the airways that causes sudden fever, aches and tiredness. Most people recover in about a week, but it can be serious in high-risk groups.',
    causes: [
      'Influenza viruses that change each year',
      'Spread through coughs, sneezes and close contact',
      'Touching contaminated surfaces then the face',
      'Crowded indoor spaces in flu season',
      'Higher risk if unvaccinated',
    ],
    symptoms: [
      ['symptoms/fever', 'Sudden fever and chills'],
      ['symptoms/fatigue', 'Marked tiredness and body aches'],
      ['symptoms/cough', 'Dry cough'],
      ['symptoms/sore-throat', 'Sore throat'],
      ['symptoms/headache', 'Headache'],
    ],
    tests: [
      [null, 'Usually diagnosed from symptoms'],
      [null, 'Rapid flu swab test if needed'],
      ['x-ray-explained', 'Chest X-ray if pneumonia is suspected'],
      [null, 'Blood oxygen (pulse oximetry)'],
    ],
    treatment: [
      'Rest and plenty of fluids',
      'Paracetamol for fever and aches',
      'Antivirals for high-risk people or severe cases',
      'Staying home to avoid spreading it',
      'Yearly vaccination helps prevent it',
    ],
    whenToSee: [
      'Severe breathlessness or chest pain — call your local emergency number now',
      'Confusion, blue lips or unable to stay awake — emergency',
      'High fever not settling, especially in the very young or elderly',
      'Symptoms improving then suddenly worsening (possible pneumonia)',
    ],
    faqs: [
      { q: 'Is flu just a bad cold?', a: 'No. Flu tends to come on suddenly with high fever and severe body aches, and can be more serious, especially for older or high-risk people.' },
      { q: 'Do I need the flu vaccine every year?', a: 'Yes. Flu viruses change each year, so an annual vaccine gives the best protection, especially for high-risk groups.' },
    ],
  },
  {
    slug: 'urinary-tract-infection',
    name: 'Urinary Tract Infection (UTI)',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'A urinary tract infection is a common bacterial infection of the bladder or urinary system. It is easily treated but can become serious if it reaches the kidneys.',
    causes: [
      'Bacteria (often from the gut) entering the urinary tract',
      'More common in women due to anatomy',
      'Holding urine for long periods',
      'Dehydration',
      'Catheters, pregnancy or diabetes increase risk',
    ],
    symptoms: [
      ['symptoms/painful-urination', 'Burning or pain when passing urine'],
      ['symptoms/frequent-urination', 'Needing to pass urine often'],
      ['symptoms/pelvic-pain', 'Lower abdominal or pelvic pain'],
      [null, 'Cloudy or strong-smelling urine'],
      ['symptoms/blood-in-urine', 'Blood in the urine'],
    ],
    tests: [
      [null, 'Urine dipstick test'],
      [null, 'Urine culture'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (if severe)'],
      ['blood-tests/creatinine', 'Kidney function if kidneys involved'],
    ],
    treatment: [
      'Antibiotics as prescribed',
      'Drinking plenty of fluids',
      'Pain relief for discomfort',
      'Completing the full antibiotic course',
      'Good hydration and hygiene to prevent recurrence',
    ],
    whenToSee: [
      'Fever with back/flank pain and vomiting — urgent (possible kidney infection)',
      'Blood in the urine or symptoms not settling',
      'UTI in pregnancy, men, children or with diabetes',
      'Repeated infections needing investigation',
    ],
    faqs: [
      { q: 'Can I treat a UTI without antibiotics?', a: 'Mild ones sometimes settle with fluids, but most need antibiotics to clear fully and prevent the infection spreading to the kidneys.' },
      { q: 'Why do I keep getting UTIs?', a: 'Frequent UTIs can relate to hydration, hygiene, hormones or other conditions. Recurrent infections should be reviewed by a doctor.' },
    ],
  },
  {
    slug: 'cellulitis',
    name: 'Cellulitis',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Cellulitis is a bacterial infection of the skin and the tissue beneath it. It causes a red, warm, painful area that can spread quickly and needs antibiotics.',
    causes: [
      'Bacteria entering through a break in the skin',
      'Cuts, insect bites, ulcers or athlete\'s foot',
      'Swelling in the legs (poor circulation)',
      'Diabetes or a weak immune system',
      'Skin conditions like eczema',
    ],
    symptoms: [
      ['symptoms/skin-rash', 'Red, spreading area of skin'],
      [null, 'Warm, swollen and tender skin'],
      ['symptoms/fever', 'Fever'],
      ['symptoms/swollen-lymph-nodes', 'Swollen nearby lymph nodes'],
      [null, 'Blistering in some cases'],
    ],
    tests: [
      [null, 'Usually diagnosed by examination'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      ['blood-tests/crp', 'CRP'],
      [null, 'Wound swab if there is a break in the skin'],
    ],
    treatment: [
      'Antibiotics as prescribed',
      'Resting and raising the affected limb',
      'Pain relief',
      'Treating the entry point (cut, ulcer, fungal infection)',
      'Hospital antibiotics if severe or spreading fast',
    ],
    whenToSee: [
      'Rapidly spreading redness with high fever — urgent care',
      'Severe pain out of proportion to the skin — emergency (rare serious infection)',
      'Redness near the eye or face',
      'Cellulitis with diabetes or a weak immune system',
    ],
    faqs: [
      { q: 'Is cellulitis contagious?', a: 'Cellulitis itself is not usually spread person to person, but keeping wounds clean and covered helps prevent infection.' },
      { q: 'How quickly should it improve?', a: 'With antibiotics, redness and pain usually start improving within a few days. Tell your doctor if it spreads or worsens.' },
    ],
  },
  {
    slug: 'gastroenteritis',
    name: 'Gastroenteritis (Food Poisoning)',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Gastroenteritis is inflammation of the stomach and intestines, usually from an infection, causing diarrhoea and vomiting. Most cases settle on their own with fluids.',
    causes: [
      'Viruses (a very common cause)',
      'Bacteria from contaminated food or water',
      'Poor food hygiene or unsafe water',
      'Parasites in some cases',
      'Close contact with an infected person',
    ],
    symptoms: [
      ['symptoms/diarrhea', 'Diarrhoea'],
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
      ['symptoms/abdominal-pain', 'Stomach cramps'],
      ['symptoms/fever', 'Mild fever'],
      ['symptoms/fatigue', 'Weakness from fluid loss'],
    ],
    tests: [
      [null, 'Usually diagnosed from symptoms'],
      [null, 'Stool test if severe or prolonged'],
      ['blood-tests/electrolytes', 'Electrolytes if dehydrated'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function if severe'],
    ],
    treatment: [
      'Plenty of fluids and oral rehydration salts (ORS)',
      'Rest and gradual return to light food',
      'Avoiding sugary and fatty foods for a while',
      'Antibiotics only for specific bacterial infections',
      'Careful hand and food hygiene to prevent spread',
    ],
    whenToSee: [
      'Signs of dehydration: little urine, dizziness, dry mouth — urgent',
      'Blood in stools or a very high fever',
      'Vomiting so much you cannot keep fluids down',
      'Symptoms in babies, elderly or the very frail',
    ],
    faqs: [
      { q: 'What is the most important treatment?', a: 'Staying hydrated. Oral rehydration salts replace lost fluids and salts and are the mainstay of care for most cases.' },
      { q: 'Do I need antibiotics for food poisoning?', a: 'Usually not. Most cases are viral or self-limiting. Antibiotics are only used for certain confirmed bacterial infections.' },
    ],
  },
  {
    slug: 'sepsis',
    name: 'Sepsis',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Sepsis is the body\'s extreme, life-threatening response to an infection. It is a medical emergency where every minute counts, so knowing the warning signs saves lives.',
    causes: [
      'Any infection that spreads or overwhelms the body',
      'Chest, urine, abdominal or skin infections',
      'A weak immune system or serious illness',
      'Very young or very old age',
      'Recent surgery, wounds or invasive lines',
    ],
    symptoms: [
      ['symptoms/fever', 'High fever or very low temperature'],
      ['symptoms/heart-palpitations', 'Fast heartbeat'],
      ['symptoms/shortness-of-breath', 'Fast, shallow breathing'],
      ['symptoms/dizziness', 'Confusion or drowsiness'],
      ['symptoms/skin-rash', 'Mottled or pale, clammy skin'],
      [null, 'Passing little or no urine'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      [null, 'Blood cultures'],
      ['blood-tests/crp', 'CRP'],
      [null, 'Blood lactate level'],
    ],
    treatment: [
      'This is an emergency — call your local emergency number now',
      'Urgent hospital antibiotics and fluids',
      'Oxygen and close monitoring',
      'Finding and treating the source of infection',
      'Intensive care support in severe cases',
    ],
    whenToSee: [
      'Confusion, slurred speech or extreme drowsiness — call your local emergency number now',
      'Fast breathing, mottled skin or very little urine — emergency',
      'Feeling more unwell than ever with an infection — seek help immediately',
      'A child who is limp, very hot or cold, or hard to wake — emergency',
    ],
    faqs: [
      { q: 'What makes sepsis so dangerous?', a: 'The body\'s response to infection damages its own organs. It can worsen very fast, which is why urgent treatment is vital.' },
      { q: 'Can sepsis be prevented?', a: 'Treating infections early, keeping wounds clean and staying up to date with vaccines all lower the risk.' },
    ],
  },
  {
    slug: 'chickenpox',
    name: 'Chickenpox',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Chickenpox is a common, very contagious viral infection that causes an itchy, blistering rash and fever. It is usually mild in children but can be more serious in adults.',
    causes: [
      'Varicella-zoster virus',
      'Spread through coughs, sneezes and contact with blisters',
      'Very contagious before the rash and until blisters crust',
      'Being unvaccinated and not previously infected',
      'Close contact in homes and schools',
    ],
    symptoms: [
      ['symptoms/skin-rash', 'Itchy rash turning into fluid-filled blisters'],
      ['symptoms/itching', 'Itching'],
      ['symptoms/fever', 'Fever'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/headache', 'Headache and loss of appetite'],
    ],
    tests: [
      [null, 'Usually diagnosed by the typical rash'],
      [null, 'Swab of a blister if confirmation needed'],
      [null, 'Blood test in special cases'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count if unwell'],
    ],
    treatment: [
      'Rest, fluids and paracetamol for fever',
      'Calamine lotion and cool baths to ease itching',
      'Keeping nails short to avoid scratching',
      'Antivirals for adults or high-risk people',
      'Staying away from others until blisters crust over',
    ],
    whenToSee: [
      'Blisters that become hot, red and painful (skin infection)',
      'Difficulty breathing, chest pain or drowsiness — urgent care',
      'Chickenpox in pregnancy, newborns or weak immunity — seek advice fast',
      'A very high fever or the person becoming very unwell',
    ],
    faqs: [
      { q: 'Can you get chickenpox twice?', a: 'It is uncommon, as most people become immune after one infection. The same virus can later cause shingles, though.' },
      { q: 'When can my child go back to school?', a: 'Once all the blisters have dried and crusted over, usually about 5 days after the rash starts.' },
    ],
  },
  {
    slug: 'measles',
    name: 'Measles',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Measles is a highly contagious viral infection that causes fever and a distinctive rash. It can lead to serious complications, but is preventable with vaccination.',
    causes: [
      'Measles virus, one of the most contagious infections',
      'Spread through coughs, sneezes and the air',
      'Being unvaccinated',
      'Close contact with an infected person',
      'Outbreaks where vaccination rates are low',
    ],
    symptoms: [
      ['symptoms/fever', 'High fever'],
      ['symptoms/cough', 'Cough'],
      [null, 'Runny nose and red, watery eyes'],
      ['symptoms/skin-rash', 'Blotchy rash spreading from the face'],
      [null, 'Tiny white spots inside the mouth'],
    ],
    tests: [
      [null, 'Usually diagnosed by symptoms and rash'],
      [null, 'Measles antibody blood test'],
      [null, 'Swab (throat/nose) for the virus'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count if unwell'],
    ],
    treatment: [
      'Rest, fluids and fever control',
      'There is no specific antiviral — care is supportive',
      'Vitamin A may be given in children',
      'Isolating to prevent spread',
      'Vaccination (MMR) is the best protection',
    ],
    whenToSee: [
      'Difficulty breathing or a fit — call your local emergency number now',
      'Drowsiness, confusion or a stiff neck — urgent care',
      'Ear pain or a worsening fever (possible complication)',
      'Measles in a baby, pregnant woman or someone immunocompromised',
    ],
    faqs: [
      { q: 'Why is measles considered dangerous?', a: 'It can cause pneumonia, ear infections and, rarely, brain inflammation. Complications are more common in young children and adults.' },
      { q: 'How effective is the vaccine?', a: 'The MMR vaccine is very effective. Two doses give strong, long-lasting protection and help stop outbreaks.' },
    ],
  },
  {
    slug: 'mumps',
    name: 'Mumps',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Mumps is a viral infection best known for causing painful swelling of the salivary glands near the jaw. It is preventable with the MMR vaccine.',
    causes: [
      'Mumps virus',
      'Spread through saliva, coughs and sneezes',
      'Sharing utensils or close contact',
      'Being unvaccinated',
      'Crowded settings like schools and hostels',
    ],
    symptoms: [
      [null, 'Painful, swollen glands near the jaw/cheeks'],
      ['symptoms/fever', 'Fever'],
      ['symptoms/headache', 'Headache'],
      ['symptoms/fatigue', 'Tiredness'],
      [null, 'Pain when chewing or swallowing'],
    ],
    tests: [
      [null, 'Usually diagnosed by the typical swelling'],
      [null, 'Mumps antibody/PCR test'],
      [null, 'Saliva or urine sample'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count if unwell'],
    ],
    treatment: [
      'Rest and plenty of fluids',
      'Paracetamol for pain and fever',
      'Warm or cold packs on the swollen glands',
      'Soft foods to make eating easier',
      'Vaccination (MMR) prevents it',
    ],
    whenToSee: [
      'Severe headache, stiff neck or drowsiness — urgent care',
      'Severe abdominal pain or, in men, painful swollen testicles',
      'A very high fever or being very unwell',
      'Symptoms not improving after about a week',
    ],
    faqs: [
      { q: 'Can mumps cause complications?', a: 'Sometimes. It can affect the testicles, ovaries, pancreas or, rarely, the brain. Vaccination greatly reduces this risk.' },
      { q: 'How long is mumps contagious?', a: 'It spreads from a few days before the swelling until about five days after it starts. Stay away from others during this time.' },
    ],
  },
  {
    slug: 'tetanus',
    name: 'Tetanus',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Tetanus is a serious infection caused by bacteria that enter through wounds, releasing a toxin that causes painful muscle stiffness and spasms. It is preventable by vaccination.',
    causes: [
      'Clostridium tetani bacteria found in soil and dust',
      'Bacteria entering through cuts, punctures or burns',
      'Deep or dirty wounds (nails, thorns, animal bites)',
      'Being unvaccinated or overdue for a booster',
      'Wounds contaminated with soil or manure',
    ],
    symptoms: [
      [null, 'Jaw stiffness (lockjaw)'],
      [null, 'Muscle stiffness and painful spasms'],
      [null, 'Difficulty swallowing'],
      ['symptoms/fever', 'Fever and sweating'],
      ['symptoms/heart-palpitations', 'Fast heartbeat'],
    ],
    tests: [
      [null, 'Diagnosed mainly from symptoms and wound history'],
      [null, 'Wound assessment'],
      [null, 'No single blood test confirms it'],
      [null, 'Checking vaccination status'],
    ],
    treatment: [
      'This is a medical emergency needing hospital care',
      'Tetanus immunoglobulin and wound cleaning',
      'Medicines to control spasms',
      'Antibiotics and supportive intensive care',
      'Prevention: keep tetanus vaccination up to date',
    ],
    whenToSee: [
      'Muscle stiffness or spasms after a wound — call your local emergency number now',
      'Difficulty swallowing or breathing — emergency',
      'A deep or dirty wound if you are not up to date on tetanus — seek care same day',
      'Any doubt about your vaccination after an injury',
    ],
    faqs: [
      { q: 'How often do I need a tetanus booster?', a: 'Boosters are generally given every 10 years, and sometimes after a dirty wound if you are overdue. Check with your doctor.' },
      { q: 'Is tetanus contagious?', a: 'No. It is not spread person to person. It comes from bacteria in the environment entering a wound.' },
    ],
  },
  {
    slug: 'rabies',
    name: 'Rabies',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Rabies is a deadly viral infection spread through the bite or scratch of an infected animal, usually a dog. It is almost always fatal once symptoms start, but is entirely preventable with prompt treatment.',
    causes: [
      'Rabies virus in the saliva of infected animals',
      'Bites or scratches from dogs, cats, monkeys or bats',
      'Licks on broken skin or the eyes/mouth',
      'Unvaccinated stray animals (a major risk in India)',
      'Delay in wound care and vaccination after a bite',
    ],
    symptoms: [
      ['symptoms/fever', 'Fever and headache early on'],
      [null, 'Tingling or pain at the bite site'],
      [null, 'Fear of water (later stage)'],
      ['symptoms/dizziness', 'Confusion and agitation'],
      [null, 'Difficulty swallowing and muscle spasms'],
    ],
    tests: [
      [null, 'Diagnosis is mainly clinical after a bite'],
      [null, 'Specialised lab tests in referral centres'],
      [null, 'No routine blood test for early diagnosis'],
      [null, 'Assessment of the biting animal if possible'],
    ],
    treatment: [
      'After a bite: wash the wound with soap and running water for 15 minutes',
      'Go for post-exposure vaccination immediately — do not wait',
      'Rabies immunoglobulin for deep or high-risk wounds',
      'Complete the full vaccination schedule',
      'Once symptoms start, rabies is almost always fatal — prevention is everything',
    ],
    whenToSee: [
      'Any animal bite or scratch — start wound washing and seek vaccination the same day',
      'A lick on broken skin or the eyes/mouth from a suspect animal',
      'Do not wait for symptoms — treatment must begin before they appear',
      'Bites to the face, hands or from a wild animal — urgent priority',
    ],
    faqs: [
      { q: 'What should I do right after a dog bite?', a: 'Wash the wound with soap under running water for about 15 minutes, then go for rabies vaccination immediately. Do not delay.' },
      { q: 'Is it too late if the animal looked healthy?', a: 'Do not take the risk. Always get post-exposure treatment after a bite, as rabies is fatal once symptoms begin but preventable beforehand.' },
    ],
  },
  {
    slug: 'leptospirosis',
    name: 'Leptospirosis',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Leptospirosis is a bacterial infection spread through water or soil contaminated with animal urine, often during floods and monsoon. It ranges from mild flu-like illness to serious organ involvement.',
    causes: [
      'Leptospira bacteria in animal (often rat) urine',
      'Contact with contaminated flood water, mud or soil',
      'Wading through water with cuts on the skin',
      'Farming, sewage and outdoor work',
      'Common after heavy rain and flooding',
    ],
    symptoms: [
      ['symptoms/fever', 'Sudden high fever'],
      ['symptoms/headache', 'Severe headache'],
      ['symptoms/joint-pain', 'Muscle pain, especially in the calves'],
      [null, 'Red eyes'],
      [null, 'Jaundice in severe cases'],
      ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'],
    ],
    tests: [
      [null, 'Leptospira antibody test'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function test'],
      ['blood-tests/liver-function-test-lft', 'Liver function test (LFT)'],
    ],
    treatment: [
      'Antibiotics as prescribed, started early',
      'Rest, fluids and fever control',
      'Hospital care for severe cases',
      'Monitoring kidney and liver function',
      'Avoiding contaminated water to prevent it',
    ],
    whenToSee: [
      'Yellow eyes, reduced urine or breathlessness — urgent care',
      'Bleeding, confusion or severe weakness — emergency',
      'High fever with calf pain after flood exposure — get tested',
      'Symptoms worsening rather than settling',
    ],
    faqs: [
      { q: 'Who is most at risk?', a: 'People exposed to flood water, mud, sewage or animals, including farmers and outdoor workers, especially during the monsoon.' },
      { q: 'How can I protect myself during floods?', a: 'Avoid wading in flood water where possible, cover cuts, wear boots, and wash well after any contact. Seek care early if you get a fever.' },
    ],
  },
  {
    slug: 'scabies',
    name: 'Scabies',
    dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Scabies is a very itchy skin condition caused by tiny mites that burrow under the skin. It spreads through close contact and is easily treated once diagnosed.',
    causes: [
      'Tiny scabies mites burrowing into the skin',
      'Spread through prolonged skin-to-skin contact',
      'Sharing bedding, towels or clothing',
      'Crowded living conditions',
      'Close household or family contact',
    ],
    symptoms: [
      ['symptoms/itching', 'Intense itching, worse at night'],
      ['symptoms/skin-rash', 'Rash with tiny bumps or blisters'],
      [null, 'Thin burrow lines on the skin'],
      [null, 'Itch between fingers, wrists and skin folds'],
      [null, 'Sores from scratching'],
    ],
    tests: [
      [null, 'Usually diagnosed by examination'],
      [null, 'Skin scraping to look for mites'],
      [null, 'Dermoscopy of burrows'],
      [null, 'Checking contacts with symptoms'],
    ],
    treatment: [
      'Medicated cream or lotion applied over the whole body',
      'Treating all close contacts at the same time',
      'Washing bedding and clothes in hot water',
      'Repeating treatment after a week if advised',
      'Itch may last a couple of weeks after successful treatment',
    ],
    whenToSee: [
      'Signs of skin infection: pus, spreading redness, fever',
      'Itching and rash not improving after treatment',
      'Widespread crusted rash (more serious form)',
      'Scabies in babies, elderly or those with weak immunity',
    ],
    faqs: [
      { q: 'Does scabies mean poor hygiene?', a: 'No. Anyone can get scabies through close contact. It is about exposure to the mite, not cleanliness.' },
      { q: 'Why do I still itch after treatment?', a: 'Itching can continue for up to a couple of weeks as the skin recovers, even when the mites are gone. See a doctor if it persists longer.' },
    ],
  },

  // ===================== ALLERGY & IMMUNOLOGY =====================
  {
    slug: 'food-allergy',
    name: 'Food Allergy',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'A food allergy is when the immune system reacts to a particular food, sometimes seriously. Common triggers include peanuts, tree nuts, milk, eggs, wheat, soy, fish and shellfish.',
    causes: [
      'Immune system reacting to a food protein',
      'Common triggers: nuts, milk, egg, wheat, soy, fish, shellfish',
      'A family or personal history of allergies',
      'Eczema or other allergic conditions',
      'Sometimes developing in adulthood',
    ],
    symptoms: [
      ['symptoms/itching', 'Itching or tingling in the mouth'],
      ['symptoms/skin-rash', 'Hives or rash'],
      [null, 'Swelling of lips, face or throat'],
      ['symptoms/nausea-and-vomiting', 'Nausea, vomiting or stomach cramps'],
      ['symptoms/shortness-of-breath', 'Wheezing or difficulty breathing'],
    ],
    tests: [
      [null, 'Skin prick allergy test'],
      [null, 'Specific IgE blood test'],
      [null, 'Supervised food challenge'],
      [null, 'Keeping a food and symptom diary'],
    ],
    treatment: [
      'Strictly avoiding the trigger food',
      'Reading food labels carefully',
      'Antihistamines for mild reactions',
      'An adrenaline auto-injector for those at risk of anaphylaxis',
      'An allergy action plan agreed with your doctor',
    ],
    whenToSee: [
      'Swelling of the throat, difficulty breathing or collapse — call your local emergency number now',
      'Use an adrenaline auto-injector if prescribed, then seek emergency care',
      'A widespread reaction after eating a food',
      'Repeated reactions needing formal allergy testing',
    ],
    faqs: [
      { q: 'Is food intolerance the same as food allergy?', a: 'No. Intolerance (like lactose intolerance) causes discomfort but not an immune reaction, while a true allergy can be serious or life-threatening.' },
      { q: 'Can children outgrow food allergies?', a: 'Some, like milk and egg allergies, are often outgrown, while others such as nut allergies tend to persist. Your doctor can advise on retesting.' },
    ],
  },
  {
    slug: 'drug-allergy',
    name: 'Drug Allergy',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'A drug allergy is an immune reaction to a medicine, ranging from a mild rash to a severe, life-threatening reaction. It is important to know which medicines you react to.',
    causes: [
      'Immune reaction to a medicine',
      'Common with some antibiotics (like penicillin) and painkillers',
      'Previous exposure to the same drug',
      'A history of other allergies',
      'Certain infections increasing reaction risk',
    ],
    symptoms: [
      ['symptoms/skin-rash', 'Rash or hives'],
      ['symptoms/itching', 'Itching'],
      [null, 'Swelling of the face, lips or tongue'],
      ['symptoms/fever', 'Fever'],
      ['symptoms/shortness-of-breath', 'Wheezing or breathing difficulty'],
    ],
    tests: [
      [null, 'Detailed history of the reaction'],
      [null, 'Skin testing for some drugs'],
      [null, 'Specific IgE blood test where available'],
      [null, 'Supervised drug challenge in select cases'],
    ],
    treatment: [
      'Stopping the medicine responsible',
      'Antihistamines for mild rashes',
      'Emergency treatment for severe reactions',
      'Recording the allergy clearly in your records',
      'Using an alternative safe medicine in future',
    ],
    whenToSee: [
      'Swelling of the throat, breathing difficulty or collapse — call your local emergency number now',
      'Blistering rash, peeling skin or mouth sores — urgent (serious reaction)',
      'A widespread rash or fever after starting a medicine',
      'Any reaction so it can be recorded and avoided',
    ],
    faqs: [
      { q: 'Are all drug side effects allergies?', a: 'No. Many side effects (like nausea) are not allergies. A true drug allergy involves the immune system and can cause rash, swelling or breathing problems.' },
      { q: 'Should I tell doctors about a drug reaction?', a: 'Always. Tell every doctor and pharmacist, and consider wearing a medical alert, so the medicine is avoided in future.' },
    ],
  },
  {
    slug: 'anaphylaxis',
    name: 'Anaphylaxis',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Anaphylaxis is a severe, rapid, life-threatening allergic reaction. It is a medical emergency that needs adrenaline and urgent care straight away.',
    causes: [
      'Severe allergy to foods (nuts, shellfish, milk, egg)',
      'Insect stings (bees, wasps)',
      'Certain medicines',
      'Latex',
      'Sometimes no clear trigger is found',
    ],
    symptoms: [
      [null, 'Swelling of the throat, tongue or lips'],
      ['symptoms/shortness-of-breath', 'Difficulty breathing or wheezing'],
      ['symptoms/skin-rash', 'Widespread hives'],
      ['symptoms/dizziness', 'Dizziness or collapse'],
      ['symptoms/heart-palpitations', 'Fast heartbeat'],
      ['symptoms/nausea-and-vomiting', 'Vomiting'],
    ],
    tests: [
      [null, 'Diagnosed clinically during the reaction'],
      [null, 'Blood tryptase test soon after'],
      [null, 'Later allergy testing to find the trigger'],
      [null, 'Specific IgE blood test'],
    ],
    treatment: [
      'This is an emergency — call your local emergency number now',
      'Use an adrenaline auto-injector immediately if available',
      'Lie the person flat and raise their legs (sit up if breathless)',
      'A second adrenaline dose after 5 minutes if no improvement',
      'Hospital observation even after recovery',
    ],
    whenToSee: [
      'Throat swelling, breathing difficulty or collapse — call your local emergency number now',
      'Give adrenaline first, then call for help',
      'Always go to hospital even if symptoms improve (they can return)',
      'Anyone at risk should carry an adrenaline auto-injector',
    ],
    faqs: [
      { q: 'What is the most important treatment?', a: 'Adrenaline, given as early as possible with an auto-injector. Do not delay to try antihistamines first, and always call emergency services.' },
      { q: 'Can symptoms come back after treatment?', a: 'Yes. A second reaction can occur hours later, which is why hospital observation after anaphylaxis is important.' },
    ],
  },
  {
    slug: 'urticaria-hives',
    name: 'Urticaria (Hives)',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Urticaria, or hives, is a raised, itchy rash that can appear anywhere on the skin. It is very common, usually harmless, and often settles on its own.',
    causes: [
      'Allergic reactions to food, medicines or insect bites',
      'Infections (a common trigger)',
      'Heat, cold, pressure or sunlight',
      'Stress',
      'Often no clear cause (chronic hives)',
    ],
    symptoms: [
      ['symptoms/skin-rash', 'Raised, red or skin-coloured welts'],
      ['symptoms/itching', 'Itching'],
      [null, 'Welts that move around and fade within hours'],
      [null, 'Swelling of skin (angioedema) at times'],
      [null, 'Burning or stinging feeling'],
    ],
    tests: [
      [null, 'Usually diagnosed by examination'],
      [null, 'Allergy testing if a trigger is suspected'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/esr', 'ESR (for long-lasting hives)'],
    ],
    treatment: [
      'Avoiding known triggers',
      'Antihistamines to control itching',
      'Cool compresses and loose clothing',
      'Higher-dose or specialist treatment for chronic hives',
      'Most acute hives settle within days',
    ],
    whenToSee: [
      'Swelling of the throat, tongue or trouble breathing — call your local emergency number now',
      'Hives with dizziness or collapse — emergency (possible anaphylaxis)',
      'Hives lasting more than 6 weeks',
      'Widespread hives with fever or feeling unwell',
    ],
    faqs: [
      { q: 'What causes hives that keep coming back?', a: 'Chronic hives often have no clear allergic cause and can relate to the immune system. They are usually controlled well with regular antihistamines.' },
      { q: 'Are hives dangerous?', a: 'Usually not, but if they come with swelling of the throat or breathing difficulty, that is an emergency needing immediate care.' },
    ],
  },
  {
    slug: 'atopic-dermatitis-eczema',
    name: 'Atopic Dermatitis (Eczema)',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Atopic dermatitis, or eczema, is a common condition that makes the skin dry, itchy and inflamed. It often starts in childhood and tends to come and go.',
    causes: [
      'A sensitive skin barrier that loses moisture',
      'A tendency to allergies (atopy) that runs in families',
      'Triggers: soaps, heat, sweat, rough fabrics',
      'Allergens like dust mites or pet dander',
      'Stress and dry weather',
    ],
    symptoms: [
      ['symptoms/itching', 'Itching, often intense'],
      ['symptoms/skin-rash', 'Dry, red, inflamed patches'],
      [null, 'Cracked or scaly skin'],
      [null, 'Skin thickening from scratching'],
      [null, 'Worse in skin creases (elbows, knees)'],
    ],
    tests: [
      [null, 'Usually diagnosed by examination'],
      [null, 'Allergy testing if triggers suspected'],
      [null, 'Skin swab if infection is suspected'],
      [null, 'Patch testing for contact triggers'],
    ],
    treatment: [
      'Regular moisturisers (emollients) as the mainstay',
      'Steroid creams for flare-ups',
      'Avoiding soaps and known triggers',
      'Treating skin infections when they occur',
      'Specialist treatments for severe eczema',
    ],
    whenToSee: [
      'Skin that is weeping, crusted or very painful (possible infection)',
      'Widespread painful blistering with fever — urgent care',
      'Eczema not improving with usual treatment',
      'Sleep or daily life badly affected by itching',
    ],
    faqs: [
      { q: 'Is eczema contagious?', a: 'No. Eczema cannot be caught from someone else. It relates to a sensitive skin barrier and a tendency to allergies.' },
      { q: 'Why do moisturisers matter so much?', a: 'They repair and protect the skin barrier, reducing dryness and flare-ups. Using them regularly, even when the skin looks clear, is key.' },
    ],
  },
  {
    slug: 'allergic-asthma',
    name: 'Allergic Asthma',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Allergic asthma is asthma triggered by allergens such as pollen, dust mites or pet dander. Managing both the allergy and the asthma gives the best control.',
    causes: [
      'Allergens: dust mites, pollen, pet dander, mould',
      'An allergic (atopic) tendency',
      'Often linked with hay fever and eczema',
      'Cold air and exercise can add to triggers',
      'Air pollution and smoke',
    ],
    symptoms: [
      ['symptoms/wheezing', 'Wheezing'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/cough', 'Cough, often at night'],
      ['symptoms/chest-pain', 'Chest tightness'],
      [null, 'Symptoms after contact with an allergen'],
    ],
    tests: [
      [null, 'Spirometry (lung function test)'],
      [null, 'Skin prick allergy test'],
      [null, 'Specific IgE blood test'],
      [null, 'Peak flow monitoring'],
    ],
    treatment: [
      'Reducing exposure to known allergens',
      'Reliever inhalers for symptoms',
      'Preventer (inhaled steroid) inhalers for daily control',
      'Treating hay fever, which can improve asthma',
      'An asthma action plan and regular reviews',
    ],
    whenToSee: [
      'Too breathless to talk, eat or sleep — call your local emergency number now',
      'Reliever inhaler not helping or needed very often',
      'Blue lips or exhaustion from breathing — emergency',
      'Symptoms worsening during allergy season',
    ],
    faqs: [
      { q: 'How is allergic asthma different from ordinary asthma?', a: 'It is asthma set off mainly by allergens. Treating the underlying allergy, alongside the usual inhalers, often improves control.' },
      { q: 'Can treating my hay fever help my asthma?', a: 'Yes. The nose and lungs are linked, so controlling allergic rhinitis often reduces asthma symptoms too.' },
    ],
  },
  {
    slug: 'angioedema',
    name: 'Angioedema',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Angioedema is deeper swelling of the skin, often around the eyes, lips, tongue or throat. It can occur with hives and, if it affects the airway, is an emergency.',
    causes: [
      'Allergic reactions to food, medicines or insect stings',
      'Some blood pressure medicines (ACE inhibitors)',
      'A rare inherited form (hereditary angioedema)',
      'Infections or other triggers',
      'Sometimes no clear cause',
    ],
    symptoms: [
      [null, 'Swelling of the lips, eyes, tongue or face'],
      [null, 'Swelling of the hands, feet or genitals'],
      ['symptoms/shortness-of-breath', 'Difficulty breathing if the throat swells'],
      [null, 'A tight or burning feeling in the swollen area'],
      ['symptoms/skin-rash', 'Hives at the same time in some cases'],
    ],
    tests: [
      [null, 'Diagnosed from the pattern of swelling'],
      [null, 'Allergy testing to find triggers'],
      [null, 'Blood tests for hereditary angioedema (C1 inhibitor)'],
      [null, 'Review of current medicines'],
    ],
    treatment: [
      'Emergency treatment if the airway is affected',
      'Antihistamines for allergic swelling',
      'Stopping any medicine that triggers it',
      'Specific medicines for hereditary angioedema',
      'Avoiding known triggers',
    ],
    whenToSee: [
      'Swelling of the tongue or throat, or trouble breathing — call your local emergency number now',
      'Swelling with dizziness or collapse — emergency (possible anaphylaxis)',
      'Rapidly spreading facial swelling',
      'Recurrent unexplained swelling needing investigation',
    ],
    faqs: [
      { q: 'How is angioedema different from hives?', a: 'Hives are raised, itchy welts on the skin surface, while angioedema is deeper swelling. They often occur together, but throat swelling makes angioedema an emergency.' },
      { q: 'Can medicines cause it?', a: 'Yes. Some blood pressure medicines can trigger angioedema, sometimes after months or years of use. Tell your doctor about all your medicines.' },
    ],
  },
  {
    slug: 'contact-dermatitis',
    name: 'Contact Dermatitis',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Contact dermatitis is a red, itchy rash that appears where the skin touches an irritant or an allergen, such as soaps, metals or chemicals. It settles once the trigger is avoided.',
    causes: [
      'Irritants: soaps, detergents, chemicals, frequent water',
      'Allergens: nickel (jewellery), fragrances, rubber, dyes',
      'Cosmetics and hair products',
      'Certain plants',
      'Work-related exposures',
    ],
    symptoms: [
      ['symptoms/skin-rash', 'Red rash where the skin was in contact'],
      ['symptoms/itching', 'Itching or burning'],
      [null, 'Dry, cracked or scaly skin'],
      [null, 'Blisters that may weep'],
      [null, 'Rash matching the shape of the trigger'],
    ],
    tests: [
      [null, 'Diagnosed from the rash and its location'],
      [null, 'Patch testing for allergic causes'],
      [null, 'Review of products and exposures'],
      [null, 'Skin swab if infection is suspected'],
    ],
    treatment: [
      'Identifying and avoiding the trigger',
      'Washing off the irritant promptly',
      'Moisturisers to repair the skin',
      'Steroid creams for flare-ups',
      'Protective gloves for hand exposures',
    ],
    whenToSee: [
      'Widespread, severe or blistering rash',
      'Signs of infection: pus, spreading redness, fever',
      'Rash near the eyes or on the face',
      'A rash that keeps returning despite avoiding suspected triggers',
    ],
    faqs: [
      { q: 'How do I find out what is causing it?', a: 'Patch testing can identify allergic triggers. Keeping track of products and where the rash appears also helps pinpoint the cause.' },
      { q: 'Will it go away on its own?', a: 'Usually yes, once the trigger is avoided and the skin is cared for. Ongoing exposure keeps the rash going.' },
    ],
  },
  {
    slug: 'primary-immunodeficiency',
    name: 'Immunodeficiency',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Immunodeficiency means the immune system is weakened and cannot fight infections properly. It can be inherited (primary) or acquired, leading to frequent or unusual infections.',
    causes: [
      'Inherited (primary) immune system disorders',
      'Acquired causes: HIV, some cancers, chemotherapy',
      'Long-term steroids or immune-suppressing medicines',
      'Severe malnutrition',
      'Diabetes and other chronic illnesses',
    ],
    symptoms: [
      [null, 'Frequent or unusually severe infections'],
      [null, 'Infections that are slow to clear'],
      ['symptoms/fever', 'Recurrent fevers'],
      ['symptoms/unexplained-weight-loss', 'Weight loss and failure to thrive in children'],
      ['symptoms/fatigue', 'Persistent tiredness'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (CBC)'],
      [null, 'Immunoglobulin levels'],
      [null, 'HIV test'],
      [null, 'Specialised immune function tests'],
    ],
    treatment: [
      'Treating and preventing infections promptly',
      'Vaccinations as advised by a specialist',
      'Immunoglobulin replacement for some conditions',
      'Treating the underlying cause where possible',
      'Long-term specialist follow-up',
    ],
    whenToSee: [
      'A serious infection with high fever or breathlessness — urgent care',
      'Repeated infections needing antibiotics several times a year',
      'Infections that are severe, unusual or slow to clear',
      'Poor growth in a child with frequent infections',
    ],
    faqs: [
      { q: 'When should frequent infections raise concern?', a: 'Very frequent, severe or unusual infections, or those needing repeated antibiotics, may point to an immune problem worth investigating.' },
      { q: 'Can immunodeficiency be treated?', a: 'Many forms can be managed well with infection prevention, vaccines and, for some, immunoglobulin replacement, guided by a specialist.' },
    ],
  },
  {
    slug: 'allergic-conjunctivitis',
    name: 'Allergic Conjunctivitis (Eye Allergy)',
    dept: ['allergy-immunology', 'Allergy & Immunology'],
    lede: 'Allergic conjunctivitis is inflammation of the surface of the eye caused by an allergic reaction, making the eyes red, itchy and watery. It often occurs with hay fever.',
    causes: [
      'Allergens: pollen, dust mites, pet dander, mould',
      'An allergic (atopic) tendency',
      'Often occurs alongside allergic rhinitis',
      'Cosmetics or eye products in some cases',
      'Seasonal (pollen) or year-round (dust mites)',
    ],
    symptoms: [
      ['symptoms/itching', 'Itchy eyes'],
      [null, 'Red, watery eyes'],
      [null, 'Puffy eyelids'],
      [null, 'Burning or gritty feeling'],
      [null, 'Both eyes usually affected'],
    ],
    tests: [
      [null, 'Usually diagnosed from symptoms'],
      [null, 'Allergy testing if trigger unclear'],
      [null, 'Eye examination to rule out other causes'],
      [null, 'Specific IgE blood test'],
    ],
    treatment: [
      'Avoiding known allergens where possible',
      'Cool compresses to soothe the eyes',
      'Antihistamine or anti-allergy eye drops',
      'Artificial tears to wash out allergens',
      'Treating associated hay fever',
    ],
    whenToSee: [
      'Eye pain, changes in vision or sensitivity to light — urgent care',
      'Thick pus or one very red, painful eye (possible infection)',
      'Symptoms not improving with anti-allergy treatment',
      'Contact lens wearers with a red, painful eye',
    ],
    faqs: [
      { q: 'Is an eye allergy contagious?', a: 'No. Unlike infective conjunctivitis, allergic conjunctivitis is not contagious. It is a reaction to allergens like pollen or dust.' },
      { q: 'How can I tell it apart from an eye infection?', a: 'Allergy usually causes itching and affects both eyes with watery discharge, while infection often causes pus and can start in one eye. A doctor can confirm.' },
    ],
  },
];
