// g8.mjs — disease/condition data for ENT, Ophthalmology & Dentistry.
// Patient-facing SEO content for MedDroid (medicalandroid.com).
// Educational only, not a diagnosis. Plain English, India-relevant. NO drug doses.

export default [
  // ============================================================ ENT ===========
  {
    slug: 'ear-infection',
    name: 'Ear Infection (Otitis Media)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'An ear infection is inflammation of the middle ear, usually behind the eardrum. It is very common in young children and often follows a cold.',
    causes: ['Viral or bacterial infection after a cold or flu', 'Blocked eustachian tube trapping fluid behind the eardrum', 'Allergies causing congestion', 'Enlarged adenoids in children', 'Exposure to smoke or polluted air', 'Bottle-feeding while lying flat (in babies)'],
    symptoms: [['symptoms/ear-pain', 'Ear pain'], ['symptoms/fever', 'Fever'], [null, 'Reduced hearing'], [null, 'Discharge from the ear'], ['symptoms/dizziness', 'Dizziness'], [null, 'Tugging at the ear (in children)'], [null, 'Irritability or poor sleep in infants']],
    tests: [[null, 'Otoscopy (ear examination)'], [null, 'Tympanometry'], [null, 'Hearing test (audiometry)'], [null, 'Ear swab if there is discharge']],
    treatment: ['Many cases settle on their own within a few days', 'Pain relief and warm compresses for comfort', 'Antibiotics only when a doctor confirms a bacterial infection', 'Keeping the ear dry if the eardrum has burst', 'Treating the underlying cold or allergy', 'Grommets (ear tubes) for repeated or persistent infections'],
    whenToSee: ['Severe pain, high fever, or symptoms lasting more than 2–3 days', 'Discharge of pus or blood from the ear', 'Swelling, redness or pain behind the ear', 'Sudden hearing loss, stiff neck or confusion'],
    faqs: [
      { q: 'Are ear infections contagious?', a: 'The infection itself is not passed person to person, but the colds and flu that trigger it are. Good hand hygiene helps reduce the risk.' },
      { q: 'Will my child need antibiotics?', a: 'Not always. Many ear infections clear on their own. A doctor decides based on age, severity and how long symptoms have lasted.' },
    ],
  },
  {
    slug: 'swimmers-ear',
    name: "Swimmer's Ear (Otitis Externa)",
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: "Swimmer's ear is inflammation or infection of the outer ear canal, often after water stays trapped inside. It is common in hot, humid weather and after swimming.",
    causes: ['Water trapped in the ear canal after swimming or bathing', 'Scratching or poking the ear with cotton buds or fingers', 'Excess moisture and humidity', 'Skin conditions like eczema in the ear canal', 'Use of earphones or hearing aids that trap moisture'],
    symptoms: [['symptoms/ear-pain', 'Ear pain, worse when tugging the ear'], [null, 'Itching in the ear canal'], [null, 'Discharge from the ear'], [null, 'Blocked or muffled hearing'], [null, 'Redness and swelling of the ear canal']],
    tests: [[null, 'Otoscopy (ear examination)'], [null, 'Ear swab for culture if severe'], [null, 'Hearing test if hearing is affected']],
    treatment: ['Keeping the ear dry while it heals', 'Medicated ear drops prescribed by a doctor', 'Gentle cleaning of the ear canal by a professional', 'Pain relief for comfort', 'Avoiding cotton buds and swimming until healed'],
    whenToSee: ['Severe pain or swelling spreading to the face or neck', 'Fever with the ear symptoms', 'Symptoms not improving after a few days of treatment', 'People with diabetes or weak immunity should seek early care'],
    faqs: [
      { q: 'How is it different from a middle ear infection?', a: "Swimmer's ear affects the outer canal and hurts when you tug the ear, while a middle ear infection sits behind the eardrum and often follows a cold." },
      { q: 'Can I prevent it?', a: 'Dry your ears gently after swimming, avoid cotton buds, and consider well-fitting ear plugs if you swim often.' },
    ],
  },
  {
    slug: 'ear-wax-blockage',
    name: 'Ear Wax Blockage',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Ear wax is natural and protective, but too much can build up and block the ear canal. This can cause a blocked feeling and temporary hearing loss.',
    causes: ['Naturally narrow or hairy ear canals', 'Using cotton buds that push wax deeper', 'Wearing hearing aids or earphones regularly', 'Overproduction of wax', 'Older age, when wax becomes drier'],
    symptoms: [[null, 'Blocked or muffled hearing'], ['symptoms/ear-pain', 'Ear ache or fullness'], [null, 'Ringing in the ear (tinnitus)'], ['symptoms/dizziness', 'Dizziness'], [null, 'Itching in the ear']],
    tests: [[null, 'Otoscopy (ear examination)'], [null, 'Hearing test if hearing is affected']],
    treatment: ['Ear-softening drops (such as olive oil) for a few days', 'Gentle ear irrigation or syringing by a professional', 'Microsuction removal in a clinic', 'Never inserting cotton buds or sharp objects into the ear'],
    whenToSee: ['Sudden or complete hearing loss', 'Severe pain, discharge or bleeding', 'A blockage that does not clear with drops', 'Dizziness or ringing that persists'],
    faqs: [
      { q: 'Are ear candles safe?', a: 'No. Ear candling is not effective and can cause burns or push wax deeper. Use softening drops or see a professional instead.' },
      { q: 'Should I clean my ears daily?', a: 'Ears usually clean themselves. Just wipe the outer ear. Cotton buds tend to push wax deeper and cause blockages.' },
    ],
  },
  {
    slug: 'tinnitus',
    name: 'Tinnitus (Ringing in the Ears)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Tinnitus is hearing a sound such as ringing, buzzing or humming when there is no external source. It is very common and often harmless, though it can be distressing.',
    causes: ['Age-related or noise-induced hearing loss', 'Exposure to loud noise or music', 'Ear wax blockage or ear infection', 'Certain medicines', 'High blood pressure or stress', 'Meniere’s disease or other inner-ear problems'],
    symptoms: [[null, 'Ringing, buzzing or hissing in the ears'], [null, 'Sound in one or both ears'], [null, 'Muffled hearing'], [null, 'Difficulty concentrating or sleeping'], ['symptoms/dizziness', 'Dizziness in some cases']],
    tests: [[null, 'Otoscopy (ear examination)'], [null, 'Hearing test (audiometry)'], [null, 'Blood pressure check'], ['blood-tests/complete-blood-count-cbc', 'Blood tests for anaemia or thyroid'], [null, 'MRI in selected cases']],
    treatment: ['Treating any underlying cause such as wax or infection', 'Sound therapy or background noise to mask the ringing', 'Protecting ears from loud noise', 'Managing stress and improving sleep', 'Hearing aids if there is hearing loss', 'Counselling or cognitive therapy for distressing tinnitus'],
    whenToSee: ['Tinnitus in only one ear', 'Ringing with sudden hearing loss or dizziness', 'Pulsing tinnitus in time with your heartbeat', 'Tinnitus that seriously affects sleep or mood'],
    faqs: [
      { q: 'Will tinnitus go away?', a: 'Many people find it settles or becomes less noticeable over time, especially if a treatable cause is found. Some manage it long term with sound therapy.' },
      { q: 'Can loud music cause tinnitus?', a: 'Yes. Loud music and noise can damage the inner ear and trigger tinnitus. Protecting your ears helps prevent it.' },
    ],
  },
  {
    slug: 'hearing-loss',
    name: 'Hearing Loss',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Hearing loss means reduced ability to hear, in one or both ears. It can come on gradually with age or suddenly, and ranges from mild to profound.',
    causes: ['Age-related hearing loss', 'Long-term exposure to loud noise', 'Ear wax blockage or infections', 'Damage to the eardrum', 'Certain medicines or illnesses', 'Genetic conditions or problems present from birth'],
    symptoms: [[null, 'Difficulty following conversations'], [null, 'Turning up the TV volume'], [null, 'Asking people to repeat themselves'], [null, 'Ringing in the ears (tinnitus)'], [null, 'Muffled sounds'], ['symptoms/dizziness', 'Dizziness in some cases']],
    tests: [[null, 'Hearing test (audiometry)'], [null, 'Otoscopy (ear examination)'], [null, 'Tympanometry'], [null, 'Speech tests'], [null, 'MRI in selected cases']],
    treatment: ['Removing ear wax or treating infection if that is the cause', 'Hearing aids for many types of hearing loss', 'Cochlear implants for severe loss in selected cases', 'Protecting ears from further loud-noise damage', 'Communication and lip-reading support'],
    whenToSee: ['Sudden hearing loss (this is an emergency — seek care the same day)', 'Hearing loss with dizziness, pain or discharge', 'Loss in only one ear', 'Hearing that is affecting work, safety or daily life'],
    faqs: [
      { q: 'Is sudden hearing loss serious?', a: 'Yes. Sudden hearing loss in one ear needs urgent medical review, ideally within a day, as early treatment can improve recovery.' },
      { q: 'Can hearing loss be prevented?', a: 'Much noise-related loss is preventable by avoiding loud noise, using ear protection, and treating ear infections early.' },
    ],
  },
  {
    slug: 'vertigo',
    name: 'Vertigo (Spinning Dizziness)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Vertigo is a false sense that you or your surroundings are spinning or moving. It often comes from a problem in the inner ear, which controls balance.',
    causes: ['Benign paroxysmal positional vertigo (BPPV) from displaced inner-ear crystals', 'Inner-ear infection or inflammation (labyrinthitis, vestibular neuritis)', 'Meniere’s disease', 'Migraine', 'Certain medicines', 'Rarely, problems in the brain'],
    symptoms: [['symptoms/dizziness', 'Spinning or whirling sensation'], ['symptoms/nausea-and-vomiting', 'Nausea and vomiting'], [null, 'Loss of balance'], [null, 'Ringing in the ears'], [null, 'Feeling unsteady on standing'], ['symptoms/blurred-vision', 'Blurred vision or difficulty focusing']],
    tests: [[null, 'Balance and eye-movement tests'], [null, 'Dix-Hallpike positional test'], [null, 'Hearing test (audiometry)'], [null, 'Blood pressure check'], [null, 'MRI in selected cases']],
    treatment: ['Repositioning manoeuvres (such as Epley) for BPPV', 'Medicines to ease nausea and dizziness for short periods', 'Vestibular rehabilitation exercises', 'Treating the underlying cause such as infection or migraine', 'Staying safe to avoid falls during attacks'],
    whenToSee: ['Vertigo with severe headache, weakness or slurred speech', 'Double vision, difficulty walking or numbness', 'Sudden hearing loss with the vertigo', 'Repeated falls or vomiting you cannot control'],
    faqs: [
      { q: 'Is vertigo the same as feeling faint?', a: 'No. Vertigo is a spinning sensation, usually from the inner ear. Feeling faint or light-headed is different and may relate to blood pressure or the heart.' },
      { q: 'How long does an attack last?', a: 'It varies. BPPV attacks last seconds to minutes, while inner-ear inflammation can cause dizziness for days. A doctor can identify the type.' },
    ],
  },
  {
    slug: 'sinusitis',
    name: 'Sinusitis (Sinus Infection)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Sinusitis is inflammation of the sinuses, the air spaces around the nose and eyes. It often follows a cold and causes a blocked nose and facial pain.',
    causes: ['Viral infection after a cold', 'Bacterial infection following a cold', 'Allergies such as allergic rhinitis', 'Nasal polyps or a deviated septum', 'Air pollution, dust or smoke', 'Fungal infection in some cases'],
    symptoms: [[null, 'Blocked or runny nose'], [null, 'Facial pain or pressure'], ['symptoms/headache', 'Headache'], [null, 'Thick yellow or green nasal discharge'], [null, 'Reduced sense of smell'], ['symptoms/fever', 'Fever'], ['symptoms/cough', 'Cough']],
    tests: [[null, 'Nasal examination (nasal endoscopy)'], [null, 'CT scan of the sinuses if long-lasting'], [null, 'Nasal swab in selected cases'], [null, 'Allergy testing if allergy suspected']],
    treatment: ['Steam inhalation and saline nasal rinses', 'Decongestants for short-term relief', 'Pain relief for facial pain', 'Antibiotics only if a doctor confirms a bacterial infection', 'Treating allergies that trigger it', 'Surgery for persistent cases with polyps or blockages'],
    whenToSee: ['Severe headache, swelling around the eyes or vision changes', 'High fever or symptoms lasting more than 10 days', 'Symptoms that worsen after starting to improve', 'Confusion or a stiff neck'],
    faqs: [
      { q: 'Do I need antibiotics for sinusitis?', a: 'Most sinus infections are viral and clear without antibiotics. They are only needed when a doctor confirms a bacterial cause.' },
      { q: 'Why does my sinusitis keep coming back?', a: 'Recurrent sinusitis can be linked to allergies, nasal polyps or a deviated septum. An ENT doctor can find and treat the underlying cause.' },
    ],
  },
  {
    slug: 'allergic-rhinitis',
    name: 'Allergic Rhinitis (Hay Fever)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Allergic rhinitis is inflammation inside the nose triggered by allergens like dust, pollen or pet dander. It causes sneezing, a runny nose and itchy eyes.',
    causes: ['House dust mites', 'Pollen from grass, trees or weeds', 'Pet dander', 'Mould spores', 'Dust and air pollution', 'Strong smells or smoke as triggers'],
    symptoms: [[null, 'Sneezing'], [null, 'Runny or blocked nose'], ['symptoms/itching', 'Itchy nose, eyes or throat'], [null, 'Watery eyes'], ['symptoms/cough', 'Cough'], ['symptoms/fatigue', 'Tiredness from poor sleep']],
    tests: [[null, 'Nasal examination'], [null, 'Allergy skin-prick test'], ['blood-tests/complete-blood-count-cbc', 'Blood count (eosinophils)'], [null, 'Specific IgE blood test']],
    treatment: ['Avoiding known triggers where possible', 'Saline nasal rinses', 'Antihistamines to reduce symptoms', 'Steroid nasal sprays for regular symptoms', 'Keeping the home dust- and mould-free', 'Allergy immunotherapy in selected cases'],
    whenToSee: ['Symptoms that disrupt sleep, work or school', 'Wheezing or breathlessness (possible asthma)', 'Symptoms not controlled despite treatment', 'Recurrent sinus or ear infections'],
    faqs: [
      { q: 'Is allergic rhinitis the same as a cold?', a: 'No. A cold is caused by a virus and clears in a week or so, while allergic rhinitis is triggered by allergens and can last as long as you are exposed.' },
      { q: 'Can it lead to asthma?', a: 'Allergic rhinitis and asthma are linked and often occur together. Good control of the nose symptoms can help the chest too.' },
    ],
  },
  {
    slug: 'nasal-polyps',
    name: 'Nasal Polyps',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Nasal polyps are soft, painless growths on the lining of the nose or sinuses. They are non-cancerous but can block the nose and reduce smell.',
    causes: ['Long-standing inflammation from chronic sinusitis', 'Allergies such as allergic rhinitis', 'Asthma', 'Sensitivity to certain pain-relief medicines', 'Recurrent infections'],
    symptoms: [[null, 'Persistently blocked nose'], [null, 'Reduced or lost sense of smell'], [null, 'Runny nose or post-nasal drip'], ['symptoms/headache', 'Facial pressure or headache'], [null, 'Snoring or mouth breathing']],
    tests: [[null, 'Nasal examination (nasal endoscopy)'], [null, 'CT scan of the sinuses'], [null, 'Allergy testing']],
    treatment: ['Steroid nasal sprays or drops to shrink polyps', 'Saline nasal rinses', 'Treating underlying allergy or infection', 'A short course of steroid tablets in some cases', 'Surgery to remove large or persistent polyps'],
    whenToSee: ['Severe blockage or complete loss of smell', 'Double vision or swelling around the eyes', 'Symptoms not improving with sprays', 'Frequent sinus infections'],
    faqs: [
      { q: 'Are nasal polyps cancerous?', a: 'No, ordinary nasal polyps are non-cancerous. However, any unusual one-sided growth should be checked by an ENT doctor to be sure.' },
      { q: 'Do polyps come back after surgery?', a: 'They can return, especially with ongoing inflammation. Steroid sprays and treating allergies help reduce the chance of recurrence.' },
    ],
  },
  {
    slug: 'deviated-septum',
    name: 'Deviated Nasal Septum',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'The septum is the wall between the two nostrils. When it is bent or off-centre, it can block airflow on one side and cause breathing problems.',
    causes: ['Present from birth in many people', 'Injury to the nose', 'Normal growth of the nose', 'Previous nasal surgery or trauma'],
    symptoms: [[null, 'Blocked nose, often worse on one side'], [null, 'Difficulty breathing through the nose'], [null, 'Recurrent sinus infections'], [null, 'Nosebleeds'], [null, 'Snoring or poor sleep']],
    tests: [[null, 'Nasal examination (nasal endoscopy)'], [null, 'CT scan of the sinuses if needed']],
    treatment: ['Decongestants or steroid sprays to ease congestion', 'Saline nasal rinses', 'Treating any linked allergy', 'Surgery (septoplasty) to straighten the septum in significant cases'],
    whenToSee: ['Constant one-sided blockage affecting sleep or breathing', 'Frequent nosebleeds or sinus infections', 'Breathing problems after a nose injury', 'Symptoms not helped by sprays'],
    faqs: [
      { q: 'Does everyone with a deviated septum need surgery?', a: 'No. Many people have a mild deviation and no problems. Surgery is only considered when it causes significant blockage or repeated infections.' },
      { q: 'Can sprays fix a deviated septum?', a: 'Sprays cannot straighten the septum, but they can reduce congestion and improve airflow. Surgery is the only way to correct the bend itself.' },
    ],
  },
  {
    slug: 'tonsillitis',
    name: 'Tonsillitis',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Tonsillitis is inflammation of the tonsils, the two soft lumps at the back of the throat. It is common in children and causes a sore throat and fever.',
    causes: ['Viral infection (most common)', 'Bacterial infection such as streptococcus', 'Spread from close contact with infected people', 'Weakened immunity'],
    symptoms: [['symptoms/sore-throat', 'Sore throat'], [null, 'Painful swallowing'], ['symptoms/fever', 'Fever'], ['symptoms/swollen-lymph-nodes', 'Swollen glands in the neck'], [null, 'Red or white-spotted tonsils'], [null, 'Bad breath']],
    tests: [[null, 'Throat examination'], [null, 'Throat swab for strep'], ['blood-tests/complete-blood-count-cbc', 'Complete blood count (CBC)'], [null, 'Rapid strep test in selected cases']],
    treatment: ['Rest, fluids and warm salt-water gargles', 'Pain relief for throat pain and fever', 'Antibiotics only for confirmed bacterial infection', 'Soft foods and cool drinks for comfort', 'Surgery (tonsillectomy) for very frequent or severe cases'],
    whenToSee: ['Difficulty breathing or swallowing saliva', 'Severe one-sided throat swelling', 'High fever that does not settle', 'Very frequent recurrent attacks'],
    faqs: [
      { q: 'Do tonsils always need to be removed?', a: 'No. Removal is only considered for very frequent or severe tonsillitis, or if the tonsils cause breathing problems. Most cases are managed without surgery.' },
      { q: 'Is tonsillitis contagious?', a: 'Yes, the infections that cause it can spread through coughs, sneezes and close contact. Hand washing and covering coughs help.' },
    ],
  },
  {
    slug: 'pharyngitis-sore-throat',
    name: 'Pharyngitis (Sore Throat)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Pharyngitis is inflammation of the pharynx, the back of the throat. It causes a scratchy, painful throat and is most often due to a viral infection.',
    causes: ['Viral infections such as the common cold or flu', 'Bacterial infection such as streptococcus', 'Dry air, smoke or air pollution', 'Acid reflux', 'Overuse of the voice', 'Allergies with post-nasal drip'],
    symptoms: [['symptoms/sore-throat', 'Sore, scratchy throat'], [null, 'Painful swallowing'], ['symptoms/fever', 'Fever'], ['symptoms/cough', 'Cough'], [null, 'Hoarse voice'], ['symptoms/swollen-lymph-nodes', 'Swollen neck glands']],
    tests: [[null, 'Throat examination'], [null, 'Throat swab for strep'], ['blood-tests/complete-blood-count-cbc', 'Complete blood count (CBC)']],
    treatment: ['Rest, warm fluids and salt-water gargles', 'Lozenges and pain relief for comfort', 'Staying hydrated', 'Antibiotics only when a bacterial cause is confirmed', 'Avoiding smoke and irritants'],
    whenToSee: ['Difficulty breathing or swallowing', 'Sore throat lasting more than a week', 'High fever, rash or drooling', 'A lump in the neck or persistent hoarseness'],
    faqs: [
      { q: 'How do I know if it is strep throat?', a: 'Strep tends to cause a sudden severe sore throat with fever and no cough. A throat swab is the only way to confirm it and decide if antibiotics are needed.' },
      { q: 'How long does a sore throat last?', a: 'Most viral sore throats improve within a week. See a doctor if it lasts longer or is very severe.' },
    ],
  },
  {
    slug: 'laryngitis',
    name: 'Laryngitis',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Laryngitis is inflammation of the voice box (larynx), usually causing a hoarse or lost voice. It is often short-lived and follows a cold or voice overuse.',
    causes: ['Viral infection such as a cold', 'Overusing or straining the voice', 'Smoking or exposure to smoke', 'Acid reflux', 'Excessive alcohol', 'Long-term irritation from dust or fumes'],
    symptoms: [[null, 'Hoarse or weak voice'], [null, 'Loss of voice'], ['symptoms/sore-throat', 'Sore throat'], ['symptoms/cough', 'Dry cough'], [null, 'A tickling or raw feeling in the throat'], [null, 'Constant need to clear the throat']],
    tests: [[null, 'Throat and voice-box examination'], [null, 'Laryngoscopy if hoarseness persists'], [null, 'Voice assessment']],
    treatment: ['Resting the voice', 'Drinking plenty of fluids', 'Steam inhalation and humidified air', 'Avoiding smoke, alcohol and whispering', 'Treating reflux if that is the cause'],
    whenToSee: ['Hoarseness lasting more than 3 weeks', 'Difficulty breathing or swallowing', 'Coughing up blood', 'A lump in the neck or persistent throat pain'],
    faqs: [
      { q: 'Should I whisper to rest my voice?', a: 'No. Whispering can strain the voice box more than gentle speaking. It is better to rest the voice and speak softly only when needed.' },
      { q: 'When is hoarseness a concern?', a: 'Hoarseness that lasts more than three weeks, especially in smokers, should be checked by an ENT doctor to rule out other causes.' },
    ],
  },
  {
    slug: 'nosebleed',
    name: 'Nosebleed (Epistaxis)',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'A nosebleed is bleeding from the blood vessels inside the nose. Most are minor, come from the front of the nose, and stop with simple first aid.',
    causes: ['Dry air or picking the nose', 'Nose injury or blowing the nose hard', 'Colds, allergies or infections', 'High blood pressure', 'Blood-thinning medicines', 'Bleeding disorders in some cases'],
    symptoms: [[null, 'Bleeding from one or both nostrils'], [null, 'Blood dripping down the back of the throat'], [null, 'Feeling of a blocked nose'], ['symptoms/dizziness', 'Light-headedness with heavy bleeding']],
    tests: [[null, 'Nasal examination'], ['blood-tests/complete-blood-count-cbc', 'Complete blood count (CBC)'], ['blood-tests/pt-inr', 'Clotting tests (PT/INR)'], [null, 'Blood pressure check']],
    treatment: ['Sit up, lean forward and pinch the soft part of the nose for 10–15 minutes', 'Apply a cold pack to the bridge of the nose', 'Avoid picking or blowing the nose after it stops', 'Keeping the nasal lining moist to prevent recurrence', 'Cautery or nasal packing by a doctor for persistent bleeding'],
    whenToSee: ['Bleeding that does not stop after 20 minutes of pressure', 'Very heavy bleeding or bleeding after a serious injury', 'Frequent nosebleeds', 'Feeling faint, pale or breathless with the bleeding'],
    faqs: [
      { q: 'Should I tilt my head back during a nosebleed?', a: 'No. Lean forward instead, so blood does not run down your throat. Tilting back can cause you to swallow blood and feel sick.' },
      { q: 'Why do I get nosebleeds in dry weather?', a: 'Dry air can crack the delicate lining inside the nose. Keeping it moist with saline or a light ointment helps prevent bleeds.' },
    ],
  },
  {
    slug: 'sleep-apnoea',
    name: 'Sleep Apnoea & Snoring',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Obstructive sleep apnoea is repeated pauses in breathing during sleep, caused by the throat narrowing. Loud snoring and daytime tiredness are common signs.',
    causes: ['Being overweight', 'Enlarged tonsils or adenoids', 'A blocked nose or deviated septum', 'Relaxed throat muscles during sleep', 'Alcohol or sedatives before bed', 'A naturally narrow airway'],
    symptoms: [[null, 'Loud snoring'], [null, 'Pauses in breathing noticed by a partner'], ['symptoms/fatigue', 'Daytime sleepiness and tiredness'], ['symptoms/headache', 'Morning headaches'], [null, 'Waking gasping or choking'], [null, 'Poor concentration']],
    tests: [[null, 'Sleep study (polysomnography)'], [null, 'Nasal and throat examination'], [null, 'Blood pressure check'], ['blood-tests/thyroid-function-test-tft', 'Thyroid test (TFT)']],
    treatment: ['Weight loss if overweight', 'Sleeping on the side rather than the back', 'Avoiding alcohol and sedatives before bed', 'A CPAP machine for moderate to severe cases', 'Dental devices for mild cases', 'Surgery to clear a blocked nose or throat in selected cases'],
    whenToSee: ['Breathing pauses or choking during sleep', 'Severe daytime sleepiness affecting driving or work', 'High blood pressure with heavy snoring', 'Waking unrefreshed despite enough sleep'],
    faqs: [
      { q: 'Is snoring always sleep apnoea?', a: 'No. Snoring is common and often harmless, but loud snoring with breathing pauses and daytime tiredness suggests sleep apnoea, which needs assessment.' },
      { q: 'Why does sleep apnoea matter?', a: 'Untreated sleep apnoea can raise the risk of high blood pressure, heart problems and accidents from tiredness, so it is worth treating.' },
    ],
  },
  {
    slug: 'throat-cancer',
    name: 'Throat Cancer',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Throat cancer is a growth of abnormal cells in the throat or voice box. Early detection greatly improves outcomes, so persistent symptoms should be checked.',
    causes: ['Tobacco use, including chewing tobacco and gutkha', 'Heavy alcohol use', 'HPV (human papillomavirus) infection', 'Chewing betel nut / paan', 'Long-term acid reflux', 'Poor diet and long-term irritation'],
    symptoms: [['symptoms/sore-throat', 'Persistent sore throat'], [null, 'Hoarse voice for more than 3 weeks'], [null, 'Difficulty or pain on swallowing'], ['symptoms/swollen-lymph-nodes', 'A lump in the neck'], ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'], [null, 'Persistent cough or coughing blood']],
    tests: [[null, 'Throat examination (laryngoscopy)'], [null, 'Biopsy of the abnormal area'], ['mri-scan-explained', 'MRI scan'], [null, 'CT or PET scan'], [null, 'Endoscopy']],
    treatment: ['Treatment is planned by a cancer specialist team', 'Surgery to remove the tumour in suitable cases', 'Radiotherapy', 'Chemotherapy, often combined with radiotherapy', 'Stopping tobacco and alcohol to aid treatment and recovery'],
    whenToSee: ['Hoarseness or a sore throat lasting more than 3 weeks', 'A neck lump that does not go away', 'Difficulty swallowing or unexplained weight loss', 'Coughing up blood'],
    faqs: [
      { q: 'Can tobacco chewing cause throat cancer?', a: 'Yes. Tobacco in any form, including chewing tobacco, gutkha and paan, is a major risk factor for throat and mouth cancers. Stopping greatly lowers the risk.' },
      { q: 'Is a lump in the neck always cancer?', a: 'No. Most neck lumps are due to infections and settle. But a painless lump that lasts more than a few weeks should always be checked promptly.' },
    ],
  },
  {
    slug: 'vocal-cord-problems',
    name: 'Vocal Cord Problems',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Vocal cord problems include nodules, polyps and cysts on the vocal cords that affect the voice. They often cause hoarseness in people who use their voice a lot.',
    causes: ['Overuse or straining the voice (singers, teachers, callers)', 'Frequent shouting or throat clearing', 'Smoking', 'Acid reflux', 'Recurrent infections', 'Poor voice technique'],
    symptoms: [[null, 'Hoarse or rough voice'], [null, 'Voice tiring quickly'], [null, 'Loss of vocal range'], ['symptoms/sore-throat', 'A feeling of a lump in the throat'], [null, 'Frequent throat clearing'], [null, 'Breathy or weak voice']],
    tests: [[null, 'Voice-box examination (laryngoscopy)'], [null, 'Stroboscopy of the vocal cords'], [null, 'Voice assessment by a speech therapist']],
    treatment: ['Voice rest and good voice hygiene', 'Speech and voice therapy', 'Treating reflux if present', 'Stopping smoking', 'Surgery to remove nodules or polyps in selected cases'],
    whenToSee: ['Hoarseness lasting more than 3 weeks', 'Difficulty breathing or swallowing', 'Complete loss of voice', 'Pain when speaking or coughing up blood'],
    faqs: [
      { q: 'What are vocal cord nodules?', a: 'They are small callus-like growths from repeated voice strain, common in singers and teachers. Many improve with voice therapy and rest.' },
      { q: 'Will my voice fully recover?', a: 'With voice therapy, rest and treating the cause, many people recover well. Persistent problems may need a specialist assessment or minor surgery.' },
    ],
  },
  {
    slug: 'menieres-disease',
    name: "Meniere's Disease",
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: "Meniere's disease is a long-term inner-ear disorder causing episodes of vertigo, ringing in the ears and fluctuating hearing loss, usually in one ear.",
    causes: ['Build-up of fluid in the inner ear', 'Exact cause is often unknown', 'Possible viral, genetic or immune factors', 'Triggers such as stress, salt intake or caffeine'],
    symptoms: [['symptoms/dizziness', 'Sudden attacks of vertigo'], [null, 'Ringing in the ear (tinnitus)'], [null, 'Fluctuating hearing loss'], [null, 'A feeling of fullness in the ear'], ['symptoms/nausea-and-vomiting', 'Nausea and vomiting during attacks'], [null, 'Loss of balance']],
    tests: [[null, 'Hearing test (audiometry)'], [null, 'Balance tests'], [null, 'Otoscopy (ear examination)'], ['mri-scan-explained', 'MRI to exclude other causes']],
    treatment: ['Reducing salt, caffeine and alcohol', 'Medicines to ease dizziness and nausea during attacks', 'Medicines to reduce fluid build-up', 'Vestibular rehabilitation exercises', 'Managing stress', 'Injections or surgery for severe, resistant cases'],
    whenToSee: ['Severe vertigo with repeated vomiting', 'Sudden or worsening hearing loss', 'Vertigo with weakness, slurred speech or double vision', 'Attacks that seriously affect daily life'],
    faqs: [
      { q: "Can Meniere's disease be cured?", a: 'There is no complete cure, but symptoms can often be controlled with diet changes, medicines and rehabilitation. Many people manage attacks well over time.' },
      { q: 'Will I lose my hearing?', a: 'Hearing often fluctuates early on and may gradually reduce in the affected ear over years. Regular monitoring and treatment help manage this.' },
    ],
  },

  // ==================================================== OPHTHALMOLOGY ==========
  {
    slug: 'cataract',
    name: 'Cataract',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'A cataract is clouding of the eye’s natural lens, which causes gradually blurred, dim or cloudy vision. It is very common with age and treatable with surgery.',
    causes: ['Ageing (the most common cause)', 'Diabetes', 'Long-term use of steroid medicines', 'Eye injury or previous eye surgery', 'Excess sunlight (UV) exposure', 'Smoking'],
    symptoms: [['symptoms/blurred-vision', 'Blurred or cloudy vision'], [null, 'Faded or yellowed colours'], [null, 'Glare and halos around lights'], [null, 'Poor night vision'], [null, 'Frequent changes in glasses power'], [null, 'Double vision in one eye']],
    tests: [[null, 'Vision test (visual acuity)'], [null, 'Slit-lamp eye examination'], [null, 'Dilated eye examination'], [null, 'Eye pressure test'], ['blood-tests/fasting-blood-sugar', 'Blood sugar (for diabetes)']],
    treatment: ['Stronger glasses may help in early stages', 'Good lighting for reading and tasks', 'Cataract surgery to replace the cloudy lens (highly effective)', 'Managing diabetes and protecting eyes from UV', 'Regular eye check-ups'],
    whenToSee: ['Vision that affects driving, reading or daily life', 'Sudden vision changes or eye pain', 'Glare that makes night driving difficult', 'Rapid loss of vision'],
    faqs: [
      { q: 'Is cataract surgery safe?', a: 'Cataract surgery is one of the most common and successful operations. Most people recover good vision quickly, though a doctor will explain the small risks.' },
      { q: 'Can cataracts come back after surgery?', a: 'The cataract itself does not return, but the lens capsule can cloud over later. This is easily treated with a quick laser procedure.' },
    ],
  },
  {
    slug: 'glaucoma',
    name: 'Glaucoma',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Glaucoma is damage to the optic nerve, usually from raised pressure inside the eye. It can slowly steal side vision without warning, so regular checks matter.',
    causes: ['Raised pressure inside the eye', 'Increasing age', 'Family history of glaucoma', 'Diabetes and high blood pressure', 'Long-term steroid use', 'Previous eye injury'],
    symptoms: [[null, 'Gradual loss of side (peripheral) vision'], ['symptoms/blurred-vision', 'Blurred vision'], [null, 'Halos around lights'], ['symptoms/headache', 'Eye pain or headache (in acute cases)'], ['symptoms/nausea-and-vomiting', 'Nausea with severe eye pain (acute attack)'], [null, 'Often no symptoms in early stages']],
    tests: [[null, 'Eye pressure test (tonometry)'], [null, 'Visual field test'], [null, 'Optic nerve examination'], [null, 'OCT scan of the optic nerve'], [null, 'Gonioscopy']],
    treatment: ['Pressure-lowering eye drops (long-term)', 'Laser treatment to improve fluid drainage', 'Surgery to lower eye pressure in some cases', 'Regular monitoring of pressure and vision', 'Treating underlying diabetes or blood pressure'],
    whenToSee: ['Sudden severe eye pain with redness and nausea (emergency)', 'Sudden loss of vision or halos around lights', 'A family history — get regular screening', 'Any noticeable loss of side vision'],
    faqs: [
      { q: 'Can lost vision from glaucoma be restored?', a: 'No, vision already lost cannot be recovered, which is why early detection and treatment to prevent further damage are so important.' },
      { q: 'Who should be screened for glaucoma?', a: 'People over 40, those with a family history, diabetics and anyone with high eye pressure should have regular eye checks, as early glaucoma has no symptoms.' },
    ],
  },
  {
    slug: 'diabetic-retinopathy',
    name: 'Diabetic Retinopathy',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Diabetic retinopathy is damage to the blood vessels of the retina caused by diabetes. It is a leading cause of vision loss but can be prevented with good control.',
    causes: ['Long-standing or poorly controlled diabetes', 'High blood sugar levels over time', 'High blood pressure', 'High cholesterol', 'Long duration of diabetes', 'Smoking'],
    symptoms: [['symptoms/blurred-vision', 'Blurred or fluctuating vision'], [null, 'Floaters or dark spots'], [null, 'Difficulty seeing at night'], [null, 'Patchy or missing areas of vision'], [null, 'Often no symptoms in early stages'], [null, 'Sudden vision loss in advanced disease']],
    tests: [[null, 'Dilated retinal examination'], [null, 'Retinal photography'], [null, 'OCT scan of the retina'], ['blood-tests/hba1c', 'HbA1c (blood sugar control)'], [null, 'Fluorescein angiography']],
    treatment: ['Tight control of blood sugar, blood pressure and cholesterol', 'Regular retinal screening for all diabetics', 'Laser treatment to seal leaking vessels', 'Eye injections for swelling of the retina', 'Surgery (vitrectomy) in advanced cases'],
    whenToSee: ['Sudden loss of vision or many new floaters', 'Blurred vision in a person with diabetes', 'A curtain or shadow across vision', 'No eye check in over a year if you are diabetic'],
    faqs: [
      { q: 'Can diabetic retinopathy be prevented?', a: 'Good control of blood sugar, blood pressure and cholesterol, plus regular eye screening, greatly reduces the risk of vision loss from diabetes.' },
      { q: 'How often should diabetics have eye checks?', a: 'Most people with diabetes should have a retinal screening at least once a year, or more often if changes are found.' },
    ],
  },
  {
    slug: 'conjunctivitis',
    name: 'Conjunctivitis (Pink Eye)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Conjunctivitis is inflammation of the thin membrane covering the white of the eye. It causes redness, watering and discharge, and is usually mild and self-limiting.',
    causes: ['Viral infection (most common)', 'Bacterial infection', 'Allergies such as dust or pollen', 'Irritants like smoke, chlorine or chemicals', 'Contact lens problems'],
    symptoms: [[null, 'Red or pink eye'], ['symptoms/itching', 'Itchy or gritty feeling'], [null, 'Watery or sticky discharge'], [null, 'Eyelids stuck together in the morning'], [null, 'Swollen eyelids'], [null, 'Sensitivity to light']],
    tests: [[null, 'Eye examination'], [null, 'Eye swab in severe or persistent cases'], [null, 'Vision test']],
    treatment: ['Most viral cases clear on their own within 1–2 weeks', 'Clean the eyes gently with cooled boiled water', 'Cold compresses for comfort', 'Antibiotic drops only for confirmed bacterial infection', 'Antihistamine drops for allergic cases', 'Avoid sharing towels and touching the eyes'],
    whenToSee: ['Severe eye pain or marked redness', 'Vision changes or sensitivity to light', 'Discharge that does not improve in a week', 'A newborn baby with red, discharging eyes'],
    faqs: [
      { q: 'Is conjunctivitis contagious?', a: 'Viral and bacterial conjunctivitis are very contagious. Wash hands often, avoid touching the eyes and do not share towels until it clears.' },
      { q: 'Do I need antibiotics?', a: 'Most cases are viral and settle without antibiotics. Drops are only needed when a doctor confirms a bacterial infection.' },
    ],
  },
  {
    slug: 'dry-eye',
    name: 'Dry Eye',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Dry eye happens when the eyes do not make enough tears or the tears evaporate too fast. It causes a gritty, irritated feeling and is very common with screen use.',
    causes: ['Long hours on screens with reduced blinking', 'Ageing and hormonal changes', 'Dry, dusty or air-conditioned environments', 'Contact lens wear', 'Certain medicines', 'Some medical conditions'],
    symptoms: [[null, 'Gritty or sandy feeling in the eyes'], ['symptoms/itching', 'Burning or stinging'], [null, 'Watery eyes (reflex tearing)'], ['symptoms/blurred-vision', 'Intermittent blurred vision'], [null, 'Redness'], [null, 'Tired, heavy eyes']],
    tests: [[null, 'Eye examination'], [null, 'Tear film assessment'], [null, 'Schirmer’s tear test'], [null, 'Vision test']],
    treatment: ['Lubricating (artificial tear) drops', 'Taking regular screen breaks and blinking more', 'Warm compresses and gentle lid cleaning', 'Using a humidifier in dry rooms', 'Staying well hydrated', 'Treating any underlying condition'],
    whenToSee: ['Severe pain or marked redness', 'Vision changes that do not settle', 'Symptoms not helped by drops', 'Dry eyes with dry mouth or joint problems'],
    faqs: [
      { q: 'Why do my eyes water if they are dry?', a: 'Dryness can trigger reflex watering, but these tears drain away quickly and do not soothe the eye, so it still feels dry and gritty.' },
      { q: 'Can screens cause dry eyes?', a: 'Yes. We blink far less when looking at screens, so tears evaporate more. Regular breaks and blinking help a lot.' },
    ],
  },
  {
    slug: 'refractive-errors',
    name: 'Refractive Errors (Short & Long Sight)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Refractive errors like myopia (short sight), hyperopia (long sight) and astigmatism cause blurred vision because the eye does not focus light correctly.',
    causes: ['Shape or length of the eyeball', 'Family history', 'Prolonged close work and less outdoor time (myopia in children)', 'Ageing (for near vision — presbyopia)', 'Curvature of the cornea (astigmatism)'],
    symptoms: [['symptoms/blurred-vision', 'Blurred vision (far or near)'], ['symptoms/headache', 'Headaches'], [null, 'Squinting to see clearly'], [null, 'Eye strain'], [null, 'Difficulty reading small print'], ['symptoms/fatigue', 'Tired eyes']],
    tests: [[null, 'Vision test (visual acuity)'], [null, 'Refraction test'], [null, 'Eye examination'], [null, 'Retinal check']],
    treatment: ['Glasses tailored to the error', 'Contact lenses', 'Laser vision correction (LASIK) in suitable adults', 'Regular eye checks, especially for children', 'Encouraging outdoor time in children to slow myopia'],
    whenToSee: ['A child squinting, sitting close to the TV or struggling at school', 'Sudden change in vision', 'Blurring with pain, floaters or flashes', 'Headaches with vision problems'],
    faqs: [
      { q: 'Can spectacle power be reversed?', a: 'Glasses correct the focus but do not change the eye. In suitable adults, laser surgery can reduce dependence on glasses, but a full assessment is needed first.' },
      { q: 'Why is short sight increasing in children?', a: 'More close-up work and less outdoor time are linked to rising myopia. Regular breaks and outdoor play may help slow it.' },
    ],
  },
  {
    slug: 'macular-degeneration',
    name: 'Macular Degeneration',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Age-related macular degeneration affects the macula, the central part of the retina. It blurs the central vision needed for reading and recognising faces.',
    causes: ['Ageing (the main risk factor)', 'Family history', 'Smoking', 'High blood pressure', 'Poor diet low in leafy greens', 'Excess sunlight exposure'],
    symptoms: [['symptoms/blurred-vision', 'Blurred or distorted central vision'], [null, 'Straight lines appearing wavy'], [null, 'A dark or blank patch in the centre of vision'], [null, 'Difficulty reading or recognising faces'], [null, 'Colours appearing less bright'], [null, 'Side vision usually stays normal']],
    tests: [[null, 'Dilated retinal examination'], [null, 'Amsler grid test'], [null, 'OCT scan of the macula'], [null, 'Retinal photography'], [null, 'Fluorescein angiography']],
    treatment: ['Stopping smoking and eating a diet rich in leafy greens', 'Eye injections for the wet type', 'Special vitamin supplements in selected cases', 'Low-vision aids for reading', 'Regular monitoring with an Amsler grid'],
    whenToSee: ['Sudden distortion of straight lines', 'A new blank spot in central vision', 'Rapid drop in central vision', 'Difficulty reading that is getting worse'],
    faqs: [
      { q: 'Will macular degeneration make me fully blind?', a: 'It affects central vision but usually spares side vision, so most people keep enough sight to get around, though reading can become difficult.' },
      { q: 'What is the Amsler grid for?', a: 'It is a simple grid you look at to spot wavy lines or blank patches early, so any change can be reported to your eye doctor quickly.' },
    ],
  },
  {
    slug: 'retinal-detachment',
    name: 'Retinal Detachment',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Retinal detachment is when the retina peels away from the back of the eye. It is a medical emergency that can cause permanent vision loss without prompt treatment.',
    causes: ['Ageing changes in the jelly of the eye', 'Severe short sight (high myopia)', 'Eye injury', 'Previous eye surgery such as cataract surgery', 'Family history', 'Diabetic eye disease'],
    symptoms: [[null, 'Sudden increase in floaters'], [null, 'Flashes of light'], [null, 'A dark curtain or shadow across vision'], ['symptoms/blurred-vision', 'Blurred vision'], [null, 'Sudden loss of part of the vision']],
    tests: [[null, 'Dilated retinal examination'], [null, 'Ultrasound of the eye'], [null, 'OCT scan'], [null, 'Vision test']],
    treatment: ['This is an emergency — urgent surgery is usually needed', 'Laser or freezing treatment to seal retinal tears', 'Surgery to reattach the retina', 'Prompt treatment gives the best chance of saving vision', 'Follow-up monitoring afterwards'],
    whenToSee: ['Sudden many new floaters or flashes of light', 'A curtain or shadow spreading across your vision', 'Sudden loss of part of your sight', 'Any sudden vision change (seek care immediately)'],
    faqs: [
      { q: 'Is retinal detachment an emergency?', a: 'Yes. It needs urgent assessment, often the same day, because the sooner it is repaired, the better the chance of saving vision.' },
      { q: 'What do flashes and floaters mean?', a: 'A few floaters are common, but a sudden shower of floaters with flashes of light can signal a retinal tear and must be checked immediately.' },
    ],
  },
  {
    slug: 'stye',
    name: 'Stye (Hordeolum)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'A stye is a small, painful red lump on the edge of the eyelid caused by a blocked, infected oil gland. Most settle on their own within a week or so.',
    causes: ['Blocked and infected eyelid oil gland', 'Bacteria on the skin', 'Rubbing the eyes with unclean hands', 'Old or shared eye make-up', 'Blepharitis (eyelid inflammation)'],
    symptoms: [[null, 'A painful red lump on the eyelid'], [null, 'Swelling of the eyelid'], [null, 'Watery eye'], ['symptoms/itching', 'Tenderness or itching'], [null, 'A gritty feeling in the eye']],
    tests: [[null, 'Eye and eyelid examination']],
    treatment: ['Warm compresses several times a day', 'Gentle eyelid cleaning', 'Avoid squeezing or popping the stye', 'Avoid eye make-up and contact lenses until it heals', 'Antibiotic ointment only if a doctor advises'],
    whenToSee: ['A stye that does not improve in 1–2 weeks', 'Swelling spreading to the whole eyelid or face', 'Vision changes or severe pain', 'Recurrent styes'],
    faqs: [
      { q: 'Should I pop a stye?', a: 'No. Squeezing a stye can spread the infection. Warm compresses help it drain naturally and settle faster.' },
      { q: 'Why do I keep getting styes?', a: 'Recurrent styes can be linked to blepharitis or poor eyelid hygiene. Regular warm compresses and lid cleaning can help prevent them.' },
    ],
  },
  {
    slug: 'blepharitis',
    name: 'Blepharitis (Eyelid Inflammation)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Blepharitis is inflammation of the eyelid margins, causing red, crusty and irritated eyelids. It is common, long-term and manageable with good eyelid hygiene.',
    causes: ['Blocked oil glands in the eyelids', 'Bacteria on the eyelid skin', 'Skin conditions such as dandruff or rosacea', 'Dry eye', 'Allergies or old make-up'],
    symptoms: [[null, 'Red, swollen eyelids'], [null, 'Crusty or flaky eyelid margins'], ['symptoms/itching', 'Itchy, burning eyes'], [null, 'Gritty feeling'], [null, 'Sticky eyelids in the morning'], [null, 'Watery eyes']],
    tests: [[null, 'Eye and eyelid examination'], [null, 'Tear film assessment']],
    treatment: ['Warm compresses to loosen crusts', 'Gentle eyelid cleaning twice daily', 'Lubricating drops for dryness', 'Treating any linked skin condition', 'Ongoing eyelid hygiene as it tends to recur'],
    whenToSee: ['Vision changes or severe pain', 'Marked eyelid swelling or a lump', 'Symptoms not helped by eyelid hygiene', 'Loss of eyelashes'],
    faqs: [
      { q: 'Can blepharitis be cured?', a: 'It is usually a long-term condition rather than one that is cured, but regular warm compresses and eyelid cleaning keep symptoms well controlled.' },
      { q: 'Is blepharitis contagious?', a: 'No, blepharitis is not contagious. It is caused by blocked glands, bacteria on the skin or related skin conditions, not by spreading from person to person.' },
    ],
  },
  {
    slug: 'uveitis',
    name: 'Uveitis',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Uveitis is inflammation of the middle layer of the eye (the uvea). It causes a red, painful eye and blurred vision, and needs prompt treatment to protect sight.',
    causes: ['Autoimmune or inflammatory conditions', 'Infections such as tuberculosis or herpes', 'Eye injury', 'Sometimes no cause is found', 'Certain systemic diseases'],
    symptoms: [[null, 'Red, painful eye'], ['symptoms/blurred-vision', 'Blurred vision'], [null, 'Sensitivity to light'], [null, 'Floaters'], [null, 'A small or irregular pupil'], ['symptoms/headache', 'Eye ache or headache']],
    tests: [[null, 'Slit-lamp eye examination'], [null, 'Dilated retinal examination'], [null, 'Eye pressure test'], ['blood-tests/esr', 'Inflammation blood tests (ESR/CRP)'], [null, 'Tests for underlying causes']],
    treatment: ['Steroid eye drops to reduce inflammation', 'Drops to relax the pupil and ease pain', 'Treating any underlying infection or disease', 'Stronger medicines for severe or recurrent cases', 'Close follow-up to protect vision'],
    whenToSee: ['A red, painful eye with light sensitivity (seek care promptly)', 'Sudden blurred vision or many floaters', 'Symptoms in a person with an autoimmune disease', 'Any worsening despite treatment'],
    faqs: [
      { q: 'Is uveitis serious?', a: 'It can be, because untreated inflammation may damage vision. With prompt treatment and follow-up, most cases are controlled and sight is protected.' },
      { q: 'Will uveitis come back?', a: 'Some types are one-off, but others recur, especially when linked to an underlying condition. Regular eye checks help catch flare-ups early.' },
    ],
  },
  {
    slug: 'squint',
    name: 'Squint (Strabismus)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'A squint is when the eyes do not point in the same direction. It is common in children and, if untreated early, can lead to a lazy eye and reduced vision.',
    causes: ['Problems with the eye muscles or their nerves', 'Long-sightedness or other refractive errors', 'Family history', 'Present from birth or developing in childhood', 'Sometimes linked to other conditions'],
    symptoms: [[null, 'Eyes pointing in different directions'], [null, 'One eye turning in, out, up or down'], ['symptoms/blurred-vision', 'Blurred or double vision'], [null, 'Tilting or turning the head to see'], [null, 'A lazy eye (reduced vision in one eye)'], [null, 'Eye strain']],
    tests: [[null, 'Vision test'], [null, 'Eye alignment and movement test'], [null, 'Refraction test'], [null, 'Dilated eye examination']],
    treatment: ['Glasses to correct any refractive error', 'Eye patching to treat a lazy eye', 'Eye exercises in selected cases', 'Surgery to align the eye muscles', 'Early treatment in children gives the best results'],
    whenToSee: ['Any squint in a child (get it checked early)', 'A new squint in an adult', 'Double vision', 'A squint after a head injury or with other symptoms'],
    faqs: [
      { q: 'Will a child grow out of a squint?', a: 'Not usually. A constant squint should be checked early, because treating it in childhood protects vision and can prevent a lazy eye.' },
      { q: 'Is a new squint in an adult serious?', a: 'A sudden new squint or double vision in an adult should be assessed promptly, as it can occasionally signal a nerve or brain problem.' },
    ],
  },
  {
    slug: 'colour-blindness',
    name: 'Colour Blindness',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Colour blindness is difficulty telling certain colours apart, most often red and green. It is usually inherited, lifelong, and more common in men.',
    causes: ['Inherited (genetic), most commonly affecting red-green vision', 'Passed on through the X chromosome (more common in men)', 'Certain eye or nerve diseases', 'Some medicines', 'Ageing'],
    symptoms: [[null, 'Difficulty telling red and green apart'], [null, 'Confusing similar shades'], [null, 'Trouble with colour-coded information'], [null, 'Often unaware until tested'], [null, 'Difficulty with blue-yellow in some types']],
    tests: [[null, 'Ishihara colour vision test'], [null, 'Eye examination'], [null, 'Detailed colour vision tests']],
    treatment: ['There is no cure for inherited colour blindness', 'Learning to use labels, order and brightness cues', 'Special tinted lenses may help some people', 'Colour-identifying apps', 'Treating any underlying eye disease if present'],
    whenToSee: ['A sudden change in colour vision (get it checked)', 'Colour problems with vision loss or eye pain', 'A child struggling with colour-based schoolwork', 'Colour vision needed for a job or driving'],
    faqs: [
      { q: 'Can colour blindness be cured?', a: 'Inherited colour blindness cannot be cured, but most people adapt well. Sudden new colour problems, though, should be checked as they can point to an eye disease.' },
      { q: 'Why is it more common in men?', a: 'The most common types are carried on the X chromosome, so men, who have only one X, are affected far more often than women.' },
    ],
  },
  {
    slug: 'eye-floaters',
    name: 'Eye Floaters',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Floaters are small shapes that drift across your vision, like dots, threads or cobwebs. Most are harmless and part of normal ageing of the eye.',
    causes: ['Age-related changes in the jelly (vitreous) of the eye', 'Short-sightedness (myopia)', 'Previous eye surgery or injury', 'Inflammation inside the eye', 'Diabetic eye disease', 'Rarely, a retinal tear'],
    symptoms: [[null, 'Small dots, threads or cobwebs drifting in vision'], [null, 'Shapes that move as you move your eyes'], [null, 'More visible against a bright background'], ['symptoms/blurred-vision', 'Occasional blurring']],
    tests: [[null, 'Dilated retinal examination'], [null, 'Eye examination'], [null, 'OCT scan if needed']],
    treatment: ['Most floaters need no treatment and settle with time', 'The brain often learns to ignore them', 'Treating any underlying eye condition', 'Surgery is only rarely considered for severe cases'],
    whenToSee: ['A sudden shower of new floaters', 'Flashes of light with the floaters', 'A dark curtain or shadow over vision', 'Any floaters with loss of vision (seek urgent care)'],
    faqs: [
      { q: 'Are floaters dangerous?', a: 'Most are harmless age changes. But a sudden increase in floaters, especially with flashes or a shadow, can signal a retinal tear and needs urgent review.' },
      { q: 'Will floaters go away?', a: 'They often become less noticeable over time as they settle and the brain learns to ignore them, though they may not disappear completely.' },
    ],
  },
  {
    slug: 'corneal-ulcer',
    name: 'Corneal Ulcer',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'A corneal ulcer is an open sore on the clear front surface of the eye, usually from infection. It is a serious condition that needs urgent treatment to save sight.',
    causes: ['Bacterial, viral or fungal infection', 'Contact lens misuse or poor hygiene', 'Eye injury or a scratch on the cornea', 'Severe dry eye', 'Reduced blinking or eyelid problems'],
    symptoms: [[null, 'Red, painful eye'], ['symptoms/blurred-vision', 'Blurred vision'], [null, 'Sensitivity to light'], [null, 'Watery or discharging eye'], [null, 'A white spot on the cornea'], [null, 'Feeling of something in the eye']],
    tests: [[null, 'Slit-lamp eye examination'], [null, 'Corneal scraping for culture'], [null, 'Vision test'], [null, 'Fluorescein staining']],
    treatment: ['This needs urgent eye specialist care', 'Intensive antibiotic, antiviral or antifungal drops', 'Stopping contact lens use', 'Pain relief and close monitoring', 'Surgery (corneal transplant) in severe cases'],
    whenToSee: ['A painful red eye with blurred vision (seek care urgently)', 'A white spot on the cornea', 'Severe light sensitivity or discharge', 'Contact lens wearers with a sudden painful eye'],
    faqs: [
      { q: 'Can contact lenses cause corneal ulcers?', a: 'Yes. Poor lens hygiene, sleeping in lenses or overwearing them is a common cause. Good hygiene and correct use greatly reduce the risk.' },
      { q: 'Is a corneal ulcer an emergency?', a: 'Yes. It can damage vision quickly, so a painful red eye with blurring needs same-day assessment by an eye specialist.' },
    ],
  },
  {
    slug: 'watery-eyes',
    name: 'Watery Eyes (Epiphora)',
    dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Watery eyes happen when tears overflow onto the cheeks, either from too many tears or poor tear drainage. It is common and often easily treated.',
    causes: ['Blocked tear ducts', 'Dry eye causing reflex watering', 'Eyelid problems that stop tears draining', 'Allergies or infections', 'Wind, cold or irritants', 'Common in babies with immature tear ducts'],
    symptoms: [[null, 'Tears overflowing onto the cheeks'], [null, 'Blurred vision from excess tears'], [null, 'Sticky or crusty eyelids'], ['symptoms/itching', 'Irritation or redness'], [null, 'A sore or watery inner corner']],
    tests: [[null, 'Eye and eyelid examination'], [null, 'Tear drainage (syringing) test'], [null, 'Tear film assessment']],
    treatment: ['Gentle cleaning of the eyes and lids', 'Treating any infection or allergy', 'Lubricating drops if dry eye is the cause', 'Massage of the tear duct in babies', 'A minor procedure to open a blocked tear duct if needed'],
    whenToSee: ['Watering with pain, redness or vision changes', 'A swollen, tender lump near the inner corner of the eye', 'Persistent watering that does not settle', 'Watering after an eye injury'],
    faqs: [
      { q: 'Why do dry eyes water?', a: 'Dryness can trigger a burst of reflex tears, but these drain away quickly, so the eye keeps watering yet still feels dry and gritty.' },
      { q: 'My baby has a watery eye — is it serious?', a: 'Watery eyes in babies are usually due to immature tear ducts that open by themselves within a year. Gentle massage helps; see a doctor if there is pus or swelling.' },
    ],
  },

  // ======================================================= DENTISTRY ==========
  {
    slug: 'tooth-decay',
    name: 'Tooth Decay (Cavities)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Tooth decay is damage to the tooth caused by acid from plaque bacteria. It creates cavities and, if untreated, leads to pain and infection.',
    causes: ['Frequent sugary or starchy foods and drinks', 'Poor brushing and flossing', 'Plaque build-up on teeth', 'Dry mouth', 'Not enough fluoride', 'Frequent snacking or sipping sweet drinks'],
    symptoms: [[null, 'Toothache'], [null, 'Sensitivity to hot, cold or sweet'], [null, 'Visible holes or pits in teeth'], [null, 'Brown, black or white staining'], [null, 'Pain on biting'], [null, 'Bad breath']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray'], [null, 'Cavity probing']],
    treatment: ['Fillings to repair small cavities', 'Fluoride treatment for early decay', 'Crowns for badly damaged teeth', 'Root canal treatment if decay reaches the nerve', 'Better brushing, flossing and less sugar to prevent more decay'],
    whenToSee: ['Persistent toothache or pain on biting', 'A visible hole or dark spot on a tooth', 'Swelling of the face or gum', 'Sensitivity that does not settle'],
    faqs: [
      { q: 'Can early tooth decay be reversed?', a: 'Very early decay in the enamel can sometimes be halted or reversed with fluoride and good oral care. Once a cavity forms, though, it needs a filling.' },
      { q: 'How can I prevent cavities?', a: 'Brush twice daily with fluoride toothpaste, clean between teeth, cut down on sugary snacks and drinks, and have regular dental check-ups.' },
    ],
  },
  {
    slug: 'toothache',
    name: 'Toothache',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Toothache is pain in or around a tooth, often a sign of decay, infection or a gum problem. It ranges from mild sensitivity to severe throbbing pain.',
    causes: ['Tooth decay or a cavity', 'A tooth abscess or infection', 'Gum disease', 'A cracked or broken tooth', 'A worn or lost filling', 'Teeth grinding or an impacted wisdom tooth'],
    symptoms: [[null, 'Throbbing or sharp tooth pain'], [null, 'Pain on biting or chewing'], [null, 'Sensitivity to hot or cold'], [null, 'Swelling around the tooth or gum'], ['symptoms/fever', 'Fever with severe infection'], [null, 'Bad taste or bad breath']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray'], [null, 'Tooth vitality (pulp) test'], [null, 'Bite assessment']],
    treatment: ['Finding and treating the cause (decay, infection or gum problem)', 'Fillings, crowns or root canal as needed', 'Pain relief for short-term comfort', 'Salt-water rinses for gum irritation', 'Good oral hygiene to prevent recurrence'],
    whenToSee: ['Severe pain lasting more than 1–2 days', 'Facial or gum swelling', 'Fever or a bad taste from the tooth', 'Difficulty opening the mouth or swallowing'],
    faqs: [
      { q: 'Why does my toothache come and go?', a: 'Intermittent pain can come from early decay or sensitivity, but pain that keeps returning usually means a problem that needs a dentist to treat the cause.' },
      { q: 'Can a toothache be an emergency?', a: 'Severe pain with facial swelling, fever or trouble swallowing needs urgent dental or medical care, as it can signal a spreading infection.' },
    ],
  },
  {
    slug: 'gum-disease',
    name: 'Gum Disease (Gingivitis)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Gingivitis is early gum disease, where the gums become red, swollen and bleed easily. It is caused by plaque and is reversible with good oral care.',
    causes: ['Plaque build-up along the gum line', 'Poor brushing and flossing', 'Smoking or tobacco use', 'Diabetes', 'Hormonal changes such as pregnancy', 'Certain medicines'],
    symptoms: [[null, 'Red, swollen gums'], [null, 'Gums that bleed when brushing'], [null, 'Bad breath'], [null, 'Tender gums'], [null, 'Gums that look shiny or puffy']],
    tests: [[null, 'Dental and gum examination'], [null, 'Gum pocket measurement'], [null, 'Dental X-ray if needed']],
    treatment: ['Professional cleaning (scaling) to remove plaque and tartar', 'Brushing twice daily and cleaning between teeth', 'Antiseptic mouthwash if advised', 'Stopping smoking', 'Regular dental check-ups'],
    whenToSee: ['Gums that bleed regularly', 'Persistent bad breath', 'Red, swollen or receding gums', 'Loose teeth or gum pain'],
    faqs: [
      { q: 'Is bleeding gums normal?', a: 'No. Bleeding when you brush is usually an early sign of gum disease. The good news is that gingivitis is reversible with good cleaning and a dental scale.' },
      { q: 'Can gingivitis lead to tooth loss?', a: 'If untreated, gingivitis can progress to periodontitis, which damages the bone and can loosen teeth. Treating it early prevents this.' },
    ],
  },
  {
    slug: 'periodontitis',
    name: 'Periodontitis (Advanced Gum Disease)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Periodontitis is advanced gum disease where infection damages the gums and the bone holding the teeth. Without treatment it can lead to loose teeth and tooth loss.',
    causes: ['Untreated gingivitis', 'Long-term plaque and tartar build-up', 'Smoking or tobacco use', 'Poorly controlled diabetes', 'Family history', 'Poor oral hygiene'],
    symptoms: [[null, 'Receding gums (teeth looking longer)'], [null, 'Loose or shifting teeth'], [null, 'Persistent bad breath'], [null, 'Pus between teeth and gums'], [null, 'Bleeding, swollen gums'], [null, 'Pain on chewing']],
    tests: [[null, 'Gum pocket measurement'], [null, 'Dental X-ray to assess bone loss'], [null, 'Full dental and gum examination']],
    treatment: ['Deep cleaning (scaling and root planing)', 'Meticulous daily brushing and flossing', 'Stopping smoking', 'Managing diabetes', 'Gum surgery in advanced cases', 'Regular maintenance cleanings'],
    whenToSee: ['Loose teeth or teeth that are shifting', 'Pus or persistent swelling around teeth', 'Receding gums or long-looking teeth', 'Ongoing bad breath and bleeding gums'],
    faqs: [
      { q: 'Can periodontitis be cured?', a: 'The damage to bone cannot be fully reversed, but treatment can stop it progressing and keep the teeth stable. Ongoing care is essential.' },
      { q: 'Does gum disease affect general health?', a: 'Severe gum disease is linked with conditions like diabetes and heart disease, so keeping gums healthy is good for overall health too.' },
    ],
  },
  {
    slug: 'tooth-abscess',
    name: 'Tooth Abscess',
    dept: ['dentistry', 'Dentistry'],
    lede: 'A tooth abscess is a pocket of pus caused by a bacterial infection in or around a tooth. It causes severe pain and swelling and needs prompt dental treatment.',
    causes: ['Untreated tooth decay reaching the nerve', 'A cracked or broken tooth', 'Advanced gum disease', 'A failed or old filling', 'Injury to the tooth'],
    symptoms: [[null, 'Severe, throbbing toothache'], [null, 'Swelling of the face, cheek or gum'], ['symptoms/fever', 'Fever'], [null, 'A bad taste or pus in the mouth'], [null, 'Pain spreading to the jaw or ear'], ['symptoms/swollen-lymph-nodes', 'Swollen glands in the neck']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray'], [null, 'Tooth vitality (pulp) test']],
    treatment: ['Draining the abscess', 'Root canal treatment to save the tooth', 'Tooth removal if it cannot be saved', 'Antibiotics if the infection is spreading', 'Pain relief and good oral hygiene'],
    whenToSee: ['Severe toothache with facial swelling', 'Fever with the tooth pain', 'Difficulty breathing or swallowing (seek urgent care)', 'Swelling spreading to the eye or neck'],
    faqs: [
      { q: 'Will antibiotics cure a tooth abscess?', a: 'Antibiotics may control the spread of infection, but they do not cure the abscess. The tooth still needs dental treatment such as drainage, root canal or removal.' },
      { q: 'Is a tooth abscess dangerous?', a: 'It can be if the infection spreads. Swelling reaching the eye or throat, or trouble breathing or swallowing, is an emergency needing immediate care.' },
    ],
  },
  {
    slug: 'wisdom-tooth-problems',
    name: 'Wisdom Tooth Problems',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Wisdom teeth are the last molars to come through, often in the late teens or twenties. They can get stuck (impacted) and cause pain, swelling and infection.',
    causes: ['Not enough space in the jaw', 'Teeth coming in at an angle (impaction)', 'Partially erupted teeth trapping food and bacteria', 'Difficulty cleaning teeth at the back', 'Pressure on neighbouring teeth'],
    symptoms: [[null, 'Pain at the back of the jaw'], [null, 'Swollen, red gum over the tooth'], [null, 'Difficulty opening the mouth'], [null, 'Bad taste or bad breath'], ['symptoms/swollen-lymph-nodes', 'Swollen glands'], [null, 'Pain when chewing']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray or OPG'], [null, 'Assessment of tooth position']],
    treatment: ['Salt-water rinses and good cleaning for mild cases', 'Treating any gum infection', 'Pain relief for comfort', 'Removal (extraction) of problem wisdom teeth', 'Keeping healthy, well-positioned wisdom teeth under review'],
    whenToSee: ['Severe pain or swelling at the back of the jaw', 'Difficulty opening the mouth or swallowing', 'Fever with the gum swelling', 'Repeated infections around the tooth'],
    faqs: [
      { q: 'Do all wisdom teeth need to be removed?', a: 'No. Healthy wisdom teeth that come through properly and can be cleaned may be left alone. Removal is for those causing pain, infection or crowding.' },
      { q: 'What is an impacted wisdom tooth?', a: 'It is a wisdom tooth that cannot fully come through, often because there is not enough space, so it stays partly or fully under the gum and can cause problems.' },
    ],
  },
  {
    slug: 'sensitive-teeth',
    name: 'Sensitive Teeth',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Tooth sensitivity is a short, sharp pain when teeth meet hot, cold, sweet or sour things. It happens when the protective enamel or gum wears away.',
    causes: ['Worn tooth enamel', 'Receding gums exposing the tooth root', 'Tooth decay or a cracked tooth', 'Aggressive brushing', 'Acidic foods and drinks', 'Teeth grinding'],
    symptoms: [[null, 'Short, sharp pain with hot or cold'], [null, 'Pain with sweet or sour foods'], [null, 'Discomfort when brushing'], [null, 'Sensitivity to cold air'], [null, 'Twinges in one or several teeth']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray to rule out decay'], [null, 'Sensitivity testing']],
    treatment: ['Using a desensitising toothpaste', 'Brushing gently with a soft brush', 'Cutting down on acidic foods and drinks', 'Fluoride treatment at the dentist', 'Treating any decay, cracks or gum recession'],
    whenToSee: ['Sensitivity that is severe or getting worse', 'Pain that lingers rather than a brief twinge', 'Sensitivity in just one tooth (possible decay or crack)', 'Sensitivity with swelling or visible damage'],
    faqs: [
      { q: 'Does sensitivity always mean a cavity?', a: 'Not always. It is often due to worn enamel or receding gums, but sensitivity in a single tooth or lingering pain can mean decay or a crack that needs checking.' },
      { q: 'How can I reduce sensitivity?', a: 'Use a desensitising toothpaste, brush gently with a soft brush, and cut down on acidic foods. See a dentist if it persists.' },
    ],
  },
  {
    slug: 'bad-breath',
    name: 'Bad Breath (Halitosis)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Bad breath is an unpleasant smell from the mouth. It is very common and usually caused by bacteria in the mouth, but can sometimes signal another problem.',
    causes: ['Poor oral hygiene and plaque build-up', 'Bacteria coating the tongue', 'Gum disease', 'Dry mouth', 'Strong foods, smoking or alcohol', 'Sinus, throat or stomach problems'],
    symptoms: [[null, 'Persistent unpleasant mouth odour'], [null, 'A bad taste in the mouth'], [null, 'Coated or white tongue'], [null, 'Dry mouth'], [null, 'Others noticing the smell']],
    tests: [[null, 'Dental and gum examination'], [null, 'Assessment of the tongue and mouth'], [null, 'Checking for gum disease or decay']],
    treatment: ['Brushing twice daily and cleaning between teeth', 'Cleaning the tongue', 'Staying well hydrated', 'Treating gum disease or decay', 'Cutting down on smoking, alcohol and strong foods', 'Regular dental check-ups'],
    whenToSee: ['Bad breath that persists despite good oral care', 'Bad breath with sore, bleeding gums', 'A constant bad taste', 'Bad breath with other symptoms like heartburn or a blocked nose'],
    faqs: [
      { q: 'Why do I have bad breath even after brushing?', a: 'Bacteria on the tongue, gum disease or a dry mouth can cause lasting bad breath. Cleaning the tongue and seeing a dentist for gum problems often helps.' },
      { q: 'Can bad breath signal another illness?', a: 'Sometimes. Sinus infections, throat problems, acid reflux or diabetes can cause bad breath, so persistent odour with other symptoms should be checked.' },
    ],
  },
  {
    slug: 'mouth-ulcers',
    name: 'Mouth Ulcers',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Mouth ulcers are small, painful sores inside the mouth. Most are harmless and heal on their own within a week or two, though they can be uncomfortable.',
    causes: ['Minor injury from biting or a hard toothbrush', 'Stress or lack of sleep', 'Certain foods or acidic items', 'Vitamin or iron deficiency', 'Hormonal changes', 'Some medical conditions'],
    symptoms: [[null, 'Painful round sores in the mouth'], [null, 'A white, yellow or grey centre with a red edge'], [null, 'Pain when eating or drinking'], [null, 'Soreness in the mouth'], [null, 'One or several ulcers at a time']],
    tests: [[null, 'Mouth examination'], ['blood-tests/complete-blood-count-cbc', 'Blood count if ulcers recur'], ['blood-tests/vitamin-b12', 'Vitamin B12 and iron studies'], [null, 'Biopsy for a long-lasting ulcer']],
    treatment: ['Most heal by themselves within 1–2 weeks', 'Avoiding spicy, acidic or hard foods', 'Salt-water or antiseptic mouth rinses', 'Protective gels or pastes for comfort', 'Treating any vitamin deficiency'],
    whenToSee: ['An ulcer lasting more than 3 weeks', 'A painless ulcer or lump (get it checked)', 'Frequent or many ulcers at once', 'Ulcers with fever or feeling unwell'],
    faqs: [
      { q: 'When should I worry about a mouth ulcer?', a: 'Any ulcer that lasts more than three weeks, or a painless lump or patch, should be checked by a dentist or doctor to rule out serious causes.' },
      { q: 'Why do I keep getting mouth ulcers?', a: 'Recurrent ulcers can be linked to stress, minor injury, or a lack of iron or vitamins. A blood test may help find a treatable cause.' },
    ],
  },
  {
    slug: 'dry-mouth',
    name: 'Dry Mouth (Xerostomia)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Dry mouth is a lack of enough saliva, leaving the mouth parched. Besides discomfort, it raises the risk of tooth decay and gum problems.',
    causes: ['Certain medicines', 'Dehydration', 'Mouth breathing or snoring', 'Diabetes', 'Ageing', 'Some medical conditions affecting saliva glands'],
    symptoms: [[null, 'A dry, sticky feeling in the mouth'], [null, 'Frequent thirst'], [null, 'Difficulty chewing or swallowing'], [null, 'Cracked lips or a sore tongue'], [null, 'Bad breath'], [null, 'More tooth decay than usual']],
    tests: [[null, 'Mouth examination'], [null, 'Saliva flow assessment'], ['blood-tests/fasting-blood-sugar', 'Blood sugar (for diabetes)'], [null, 'Tests for underlying causes']],
    treatment: ['Sipping water often', 'Sugar-free gum or lozenges to boost saliva', 'Saliva substitutes if needed', 'Avoiding caffeine, alcohol and tobacco', 'Reviewing medicines with a doctor', 'Extra attention to brushing and dental check-ups'],
    whenToSee: ['Persistent dry mouth affecting eating or speaking', 'Dry mouth with dry eyes or joint pains', 'Frequent tooth decay or mouth infections', 'Dry mouth with high thirst and passing lots of urine'],
    faqs: [
      { q: 'Why does dry mouth cause more cavities?', a: 'Saliva washes away food and neutralises acid. With less saliva, acids and bacteria linger longer, so teeth decay more easily.' },
      { q: 'Can medicines cause dry mouth?', a: 'Yes, many common medicines reduce saliva. If you notice dry mouth after starting a new medicine, mention it to your doctor.' },
    ],
  },
  {
    slug: 'teeth-grinding',
    name: 'Teeth Grinding (Bruxism)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Bruxism is grinding or clenching the teeth, often during sleep. Many people are unaware of it until it wears the teeth or causes jaw pain and headaches.',
    causes: ['Stress and anxiety', 'Sleep problems', 'A misaligned bite', 'Excess caffeine or alcohol', 'Smoking', 'Some medicines'],
    symptoms: [[null, 'Worn, flattened or chipped teeth'], ['symptoms/headache', 'Headaches, often in the morning'], [null, 'Jaw pain or tightness'], [null, 'Tooth sensitivity'], [null, 'Clicking of the jaw'], [null, 'A partner noticing grinding sounds at night']],
    tests: [[null, 'Dental examination'], [null, 'Assessment of tooth wear'], [null, 'Bite and jaw assessment']],
    treatment: ['A custom night guard to protect the teeth', 'Managing stress and improving sleep', 'Cutting down on caffeine and alcohol', 'Jaw relaxation exercises', 'Correcting bite problems if present', 'Repairing worn or damaged teeth'],
    whenToSee: ['Jaw pain or persistent morning headaches', 'Worn, chipped or sensitive teeth', 'Clicking or locking of the jaw', 'A partner reporting loud grinding at night'],
    faqs: [
      { q: 'How do I know if I grind my teeth?', a: 'Many people grind in their sleep unknowingly. Morning headaches, jaw ache, worn teeth or a partner hearing grinding are common clues.' },
      { q: 'Does a night guard help?', a: 'Yes. A custom-fitted night guard cushions the teeth and reduces damage from grinding, and treating stress helps tackle the cause.' },
    ],
  },
  {
    slug: 'malocclusion',
    name: 'Malocclusion (Crooked Teeth & Braces)',
    dept: ['dentistry', 'Dentistry'],
    lede: 'Malocclusion means the teeth are crowded, crooked or the bite does not line up properly. It can affect appearance, cleaning and, sometimes, chewing.',
    causes: ['Inherited jaw or tooth size differences', 'Crowding when there is not enough space', 'Thumb-sucking or prolonged dummy use in childhood', 'Early or late loss of baby teeth', 'Jaw injury', 'Extra or missing teeth'],
    symptoms: [[null, 'Crooked or crowded teeth'], [null, 'Teeth that do not meet properly on biting'], [null, 'Difficulty cleaning between teeth'], [null, 'Jaw discomfort'], [null, 'Difficulty biting or chewing'], [null, 'Concerns about appearance']],
    tests: [[null, 'Dental examination'], [null, 'Dental X-ray or OPG'], [null, 'Bite assessment'], [null, 'Dental impressions or scans']],
    treatment: ['Braces to gradually straighten teeth', 'Clear aligners in suitable cases', 'Removing crowded teeth if needed', 'Retainers to hold the result', 'Jaw surgery for severe bite problems', 'Good oral hygiene throughout treatment'],
    whenToSee: ['Difficulty biting, chewing or cleaning teeth', 'A child with very crowded or protruding teeth', 'Jaw pain or clicking with a poor bite', 'Concerns about crooked teeth or appearance'],
    faqs: [
      { q: 'Is there an age limit for braces?', a: 'No. While childhood and teenage years are ideal, adults can also straighten their teeth with braces or clear aligners after a dental assessment.' },
      { q: 'Why do crooked teeth matter beyond looks?', a: 'Crowded or misaligned teeth are harder to clean, which can raise the risk of decay and gum disease, and a poor bite can strain the jaw.' },
    ],
  },
  {
    slug: 'strep-throat',
    name: 'Strep Throat',
    dept: ['ent', 'ENT (Ear, Nose & Throat)'],
    lede: 'Strep throat is a bacterial throat infection caused by group A Streptococcus. Unlike a viral sore throat, it usually comes on suddenly with a severe sore throat and fever but no cough, and it needs antibiotics to prevent complications.',
    causes: [
      'Infection with group A Streptococcus bacteria',
      'Close contact with an infected person (coughs, sneezes)',
      'Sharing food, drinks or utensils',
      'Crowded settings such as schools and hostels',
      'Being aged 5–15 (most common in children)',
      'Weakened immunity',
    ],
    symptoms: [
      ['symptoms/sore-throat', 'Sudden, severe sore throat'],
      [null, 'Pain when swallowing'],
      ['symptoms/fever', 'Fever, often above 38°C'],
      ['symptoms/swollen-lymph-nodes', 'Swollen, tender neck glands'],
      [null, 'Red throat with white or yellow patches on the tonsils'],
      [null, 'Tiny red spots on the roof of the mouth'],
      [null, 'Headache, nausea or a fine rash (scarlet fever)'],
      [null, 'Usually NO cough or runny nose (points away from a common cold)'],
    ],
    tests: [
      [null, 'Throat examination'],
      [null, 'Rapid strep antigen test'],
      [null, 'Throat swab culture (confirmatory)'],
      ['blood-tests/complete-blood-count-cbc', 'Complete blood count (CBC) if needed'],
    ],
    treatment: [
      'A full course of antibiotics prescribed by a doctor (do not stop early)',
      'Rest, plenty of fluids and warm salt-water gargles',
      'Paracetamol or ibuprofen for pain and fever',
      'Soft, soothing foods and cool drinks',
      'Staying home for about 24 hours after starting antibiotics to avoid spreading it',
      'Replacing your toothbrush once recovered',
    ],
    whenToSee: [
      'Difficulty breathing or swallowing, or drooling',
      'A high fever that does not improve within 48 hours of starting antibiotics',
      'A red, sandpaper-like rash (possible scarlet fever)',
      'Joint pain, dark urine or chest symptoms weeks later (rare complications)',
      'A child who is very unwell, not drinking, or dehydrated',
    ],
    faqs: [
      { q: 'How is strep throat different from a normal sore throat?', a: 'Most sore throats are viral and come with a cough or runny nose. Strep throat usually starts suddenly with a severe sore throat, fever and swollen glands but no cough. A throat swab is the only sure way to tell them apart.' },
      { q: 'Do I always need antibiotics for strep throat?', a: 'If a swab confirms strep, antibiotics are recommended — not only to feel better sooner, but to prevent complications such as rheumatic fever and kidney inflammation. Viral sore throats do not need antibiotics.' },
      { q: 'Is strep throat contagious?', a: 'Yes, it spreads easily through coughs, sneezes and shared items. People are usually no longer contagious about 24 hours after starting antibiotics.' },
      { q: 'What happens if strep throat is left untreated?', a: 'Untreated strep can occasionally lead to serious problems such as rheumatic fever (which can affect the heart) or kidney inflammation, so it should be checked by a doctor.' },
    ],
  },
];
