// Disease / topic content — group g9
//   Oncology & Haematology, Sexual Health, Regenerative Medicine, Radiology & Imaging
// Consumed by gen-landing.mjs. Educational only — not a diagnosis, and no drug doses.
// Link arrays: [ 'symptoms/<slug>' | 'blood-tests/<slug>' | '<imaging>' | null, 'Label' ].
// Only slugs that already exist are linked; everything else uses [null, 'Label'].

const ONC = ['oncology', 'Oncology & Haematology'];
const SXH = ['sexual-health', 'Sexual Health'];
const REG = ['regenerative-medicine', 'Regenerative Medicine'];
const RAD = ['radiology', 'Radiology & Imaging'];

export default [
  // =====================================================================
  // ONCOLOGY & HAEMATOLOGY
  // =====================================================================
  {
    slug: 'breast-cancer',
    name: 'Breast Cancer',
    dept: ONC,
    lede: 'Breast cancer is the most common cancer in women, though men can get it too. Found early, it is very often treatable — which is why knowing your normal and getting changes checked matters.',
    causes: [
      'Increasing age (most cases are after 50)',
      'Family history or inherited genes (BRCA1/BRCA2)',
      'Early periods or late menopause (longer oestrogen exposure)',
      'Not having children, or a first pregnancy later in life',
      'Being overweight after menopause, and regular alcohol',
      'Previous breast cancer or certain benign breast conditions',
    ],
    symptoms: [
      [null, 'A new lump or thickening in the breast or armpit'],
      [null, 'A change in breast size, shape or skin (dimpling, puckering)'],
      [null, 'Nipple change — turning inward, discharge or a rash'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands in the armpit'],
      [null, 'Redness or an orange-peel look to the skin'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss (advanced disease)'],
    ],
    tests: [
      [null, 'Clinical breast examination'],
      [null, 'Mammography'],
      [null, 'Breast ultrasound'],
      [null, 'Core-needle biopsy'],
      ['mri-scan-explained', 'Breast MRI in selected cases'],
    ],
    treatment: [
      'Surgery — lumpectomy (breast-conserving) or mastectomy',
      'Radiotherapy, often after breast-conserving surgery',
      'Chemotherapy before or after surgery in many cases',
      'Hormone therapy for hormone-receptor-positive cancers',
      'Targeted therapy (e.g. for HER2-positive cancers)',
      'Treatment is planned by a specialist team and tailored to you',
    ],
    whenToSee: [
      'Any new breast or armpit lump that does not go away',
      'Nipple discharge (especially bloodstained) or a nipple that turns in',
      'Skin dimpling, puckering or a persistent rash on the breast',
    ],
    faqs: [
      { q: 'Does a breast lump always mean cancer?', a: 'No — most breast lumps are benign (such as cysts or fibroadenomas). But only a doctor can tell, so any new or changing lump should be checked promptly.' },
      { q: 'At what age should I start screening?', a: 'It varies by country and personal risk. Many programmes screen women from around 40–50. If you have a strong family history, ask your doctor about starting earlier.' },
    ],
  },
  {
    slug: 'lung-cancer',
    name: 'Lung Cancer',
    dept: ONC,
    lede: 'Lung cancer often causes few symptoms early on, which is why it is frequently found late. Smoking is the biggest risk factor, but non-smokers can develop it too.',
    causes: [
      'Smoking (by far the leading cause) and second-hand smoke',
      'Exposure to radon gas',
      'Asbestos and other workplace chemicals',
      'Air pollution over many years',
      'Previous radiotherapy to the chest',
      'Family history of lung cancer',
    ],
    symptoms: [
      ['symptoms/cough', 'A cough that does not go away or gets worse'],
      [null, 'Coughing up blood'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/chest-pain', 'Chest pain, worse on breathing or coughing'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/fatigue', 'Tiredness and loss of appetite'],
    ],
    tests: [
      ['x-ray-explained', 'Chest X-ray'],
      [null, 'CT scan of the chest'],
      [null, 'Bronchoscopy'],
      [null, 'Biopsy of lung tissue'],
      [null, 'PET scan for staging'],
    ],
    treatment: [
      'Surgery to remove the tumour when caught early enough',
      'Radiotherapy, alone or with chemotherapy',
      'Chemotherapy',
      'Targeted therapy or immunotherapy for certain cancer types',
      'A specialist team decides the plan based on type and stage',
    ],
    whenToSee: [
      'A cough lasting more than three weeks, or a change in a long-term cough',
      'Coughing up blood',
      'Unexplained breathlessness, chest pain or weight loss',
    ],
    faqs: [
      { q: 'Can non-smokers get lung cancer?', a: 'Yes. While smoking is the biggest cause, non-smokers can develop lung cancer from radon, asbestos, pollution or other factors — so persistent symptoms should always be checked.' },
      { q: 'Is a lasting cough always serious?', a: 'Usually not, but a cough lasting more than three weeks, or coughing up blood, needs to be assessed by a doctor to rule out serious causes.' },
    ],
  },
  {
    slug: 'colorectal-cancer',
    name: 'Colorectal (Bowel) Cancer',
    dept: ONC,
    lede: 'Colorectal cancer affects the colon or rectum and often begins as a small growth called a polyp. Screening can catch it early — or even prevent it — before symptoms appear.',
    causes: [
      'Increasing age (most cases after 50)',
      'A diet high in red or processed meat and low in fibre',
      'Being overweight and physically inactive',
      'Smoking and heavy alcohol use',
      'A family history of bowel cancer or polyps',
      'Long-standing inflammatory bowel disease (Crohn\'s, ulcerative colitis)',
    ],
    symptoms: [
      ['symptoms/blood-in-stool', 'Blood in the stool or from the back passage'],
      [null, 'A lasting change in bowel habit (looser, more often)'],
      ['symptoms/abdominal-pain', 'Tummy pain or discomfort'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/fatigue', 'Tiredness from anaemia (low iron)'],
      [null, 'A feeling of not fully emptying the bowel'],
    ],
    tests: [
      [null, 'Faecal immunochemical test (FIT / stool test)'],
      [null, 'Colonoscopy with biopsy'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (checks for anaemia)'],
      [null, 'CT scan for staging'],
    ],
    treatment: [
      'Surgery to remove the affected part of the bowel',
      'Chemotherapy before or after surgery',
      'Radiotherapy, mainly for rectal cancer',
      'Targeted therapy for some advanced cancers',
      'Removing polyps at colonoscopy can prevent cancer developing',
    ],
    whenToSee: [
      'Blood in your stool or bleeding from the back passage',
      'A change in bowel habit lasting more than a few weeks',
      'Unexplained weight loss, tummy pain or persistent tiredness',
    ],
    faqs: [
      { q: 'Is blood in the stool always cancer?', a: 'No — it is often caused by piles (haemorrhoids) or a small tear. But bowel cancer can cause it too, so any bleeding should be checked by a doctor.' },
      { q: 'Should I do bowel screening if I feel fine?', a: 'Yes. Screening is designed to find cancer or pre-cancerous polyps before symptoms start, when treatment works best. Take up screening invitations when offered.' },
    ],
  },
  {
    slug: 'prostate-cancer',
    name: 'Prostate Cancer',
    dept: ONC,
    lede: 'Prostate cancer is one of the most common cancers in men and often grows slowly. Many men live for years with it, and early cancers frequently cause no symptoms at all.',
    causes: [
      'Increasing age (mostly over 50)',
      'Family history of prostate, breast or ovarian cancer',
      'African or Afro-Caribbean ancestry',
      'Inherited genes (such as BRCA2)',
      'Being overweight',
    ],
    symptoms: [
      ['symptoms/frequent-urination', 'Needing to pass urine more often, especially at night'],
      [null, 'Difficulty starting or a weak urine flow'],
      [null, 'A feeling the bladder has not fully emptied'],
      ['symptoms/blood-in-urine', 'Blood in the urine or semen'],
      ['symptoms/back-pain', 'Back or bone pain (advanced disease)'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss (advanced disease)'],
    ],
    tests: [
      ['blood-tests/psa', 'PSA blood test'],
      [null, 'Digital rectal examination'],
      ['mri-scan-explained', 'Prostate MRI'],
      [null, 'Prostate biopsy'],
    ],
    treatment: [
      'Active surveillance (monitoring) for low-risk, slow-growing cancer',
      'Surgery to remove the prostate',
      'Radiotherapy',
      'Hormone therapy to lower testosterone',
      'Chemotherapy for advanced disease',
      'A specialist weighs the benefits and side effects with you',
    ],
    whenToSee: [
      'Persistent urinary changes — weak flow, going more often, urgency',
      'Blood in the urine or semen',
      'New back or bone pain that does not settle',
    ],
    faqs: [
      { q: 'Does a raised PSA mean I have cancer?', a: 'Not necessarily. PSA can rise with age, an enlarged prostate or infection. A raised result needs further assessment, often an MRI or biopsy, to know what is going on.' },
      { q: 'Do all prostate cancers need treatment?', a: 'No. Many are slow-growing and can be safely monitored with active surveillance. Your specialist will advise based on the cancer\'s risk level and your health.' },
    ],
  },
  {
    slug: 'cervical-cancer',
    name: 'Cervical Cancer',
    dept: ONC,
    lede: 'Cervical cancer develops in the neck of the womb and is almost always linked to the HPV virus. It is one of the most preventable cancers thanks to HPV vaccination and screening.',
    causes: [
      'Persistent infection with high-risk HPV (human papillomavirus)',
      'Not attending cervical screening',
      'Smoking',
      'A weakened immune system (e.g. HIV)',
      'Long-term use of the contraceptive pill (small effect)',
    ],
    symptoms: [
      [null, 'Bleeding between periods, after sex or after menopause'],
      [null, 'Unusual or blood-stained vaginal discharge'],
      ['symptoms/pelvic-pain', 'Pelvic pain or pain during sex'],
      ['symptoms/back-pain', 'Lower back pain (later stages)'],
      ['symptoms/fatigue', 'Tiredness (advanced disease)'],
    ],
    tests: [
      [null, 'Cervical screening (smear / Pap test) and HPV test'],
      [null, 'Colposcopy'],
      [null, 'Cervical biopsy'],
      ['mri-scan-explained', 'MRI for staging'],
    ],
    treatment: [
      'Removing pre-cancerous cells found at screening (prevents cancer)',
      'Surgery, from cone biopsy to hysterectomy depending on stage',
      'Radiotherapy',
      'Chemotherapy, often combined with radiotherapy',
      'A specialist plans treatment by stage and your wishes about fertility',
    ],
    whenToSee: [
      'Vaginal bleeding between periods, after sex or after menopause',
      'Persistent unusual vaginal discharge',
      'Ongoing pelvic pain',
    ],
    faqs: [
      { q: 'Can the HPV vaccine prevent cervical cancer?', a: 'It greatly reduces the risk by protecting against the HPV types that cause most cervical cancers. It works best when given before someone becomes sexually active, but screening is still needed too.' },
      { q: 'Why do I still need smears if I feel well?', a: 'Cervical screening finds abnormal cells before they become cancer, when they are easy to treat. Cancer often causes no symptoms early on, so regular screening is key.' },
    ],
  },
  {
    slug: 'oral-cancer',
    name: 'Oral (Mouth) Cancer',
    dept: ONC,
    lede: 'Oral cancer can affect the lips, tongue, gums or lining of the mouth. Found early it is very treatable, so any sore or patch that lasts more than three weeks should be checked.',
    causes: [
      'Tobacco in any form — smoking, chewing or paan',
      'Areca nut / betel quid',
      'Heavy alcohol use (worse combined with tobacco)',
      'HPV infection',
      'Long sun exposure (for lip cancer)',
      'Poor diet and poor oral hygiene',
    ],
    symptoms: [
      [null, 'A mouth ulcer or sore that will not heal'],
      [null, 'A red or white patch inside the mouth'],
      [null, 'A lump in the mouth, lip or neck'],
      ['symptoms/sore-throat', 'Persistent sore throat or hoarse voice'],
      [null, 'Pain or difficulty chewing or swallowing'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands in the neck'],
    ],
    tests: [
      [null, 'Examination of the mouth and neck'],
      [null, 'Biopsy of the abnormal area'],
      [null, 'CT or MRI for staging'],
      [null, 'Endoscopy of the throat'],
    ],
    treatment: [
      'Surgery to remove the tumour',
      'Radiotherapy',
      'Chemotherapy for larger or spread cancers',
      'Targeted therapy in some cases',
      'Stopping tobacco and alcohol improves outcomes',
    ],
    whenToSee: [
      'A mouth ulcer, lump or red/white patch lasting over three weeks',
      'Persistent hoarseness or difficulty swallowing',
      'An unexplained lump in the neck',
    ],
    faqs: [
      { q: 'Are mouth ulcers usually cancer?', a: 'No — most are harmless and heal within two weeks. But an ulcer, lump or patch that lasts longer than three weeks should be checked by a dentist or doctor.' },
      { q: 'Does chewing tobacco really cause cancer?', a: 'Yes. Chewed tobacco, areca nut and betel quid are major causes of mouth cancer. Stopping greatly lowers your risk.' },
    ],
  },
  {
    slug: 'stomach-cancer',
    name: 'Stomach (Gastric) Cancer',
    dept: ONC,
    lede: 'Stomach cancer often causes vague symptoms early on, such as indigestion, so it can be mistaken for something minor. Persistent tummy symptoms in older adults deserve a check.',
    causes: [
      'Long-term Helicobacter pylori infection',
      'A diet high in salted, smoked or pickled foods',
      'Smoking',
      'Family history of stomach cancer',
      'Long-standing stomach inflammation (chronic gastritis)',
      'Being older and male',
    ],
    symptoms: [
      ['symptoms/heartburn', 'Persistent indigestion or heartburn'],
      ['symptoms/abdominal-pain', 'Upper tummy pain or discomfort'],
      [null, 'Feeling full quickly when eating'],
      ['symptoms/nausea-and-vomiting', 'Nausea or vomiting'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/blood-in-stool', 'Black stools or blood in vomit'],
    ],
    tests: [
      [null, 'Upper endoscopy (gastroscopy) with biopsy'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count (checks for anaemia)'],
      [null, 'CT scan for staging'],
      [null, 'Test for Helicobacter pylori'],
    ],
    treatment: [
      'Surgery to remove part or all of the stomach',
      'Chemotherapy before or after surgery',
      'Radiotherapy in some cases',
      'Targeted therapy for certain cancers',
      'Treating H. pylori lowers future risk',
    ],
    whenToSee: [
      'Indigestion that persists or gets worse, especially over 50',
      'Difficulty swallowing, or feeling full very quickly',
      'Black stools, vomiting blood or unexplained weight loss',
    ],
    faqs: [
      { q: 'Is indigestion a sign of stomach cancer?', a: 'Usually not — indigestion is very common and mostly harmless. But if it is persistent, new in an older adult, or comes with weight loss or swallowing trouble, it should be assessed.' },
      { q: 'Can an ulcer bug cause cancer?', a: 'Long-term infection with Helicobacter pylori raises the risk of stomach cancer. It can be tested for and treated, which reduces that risk.' },
    ],
  },
  {
    slug: 'liver-cancer',
    name: 'Liver Cancer',
    dept: ONC,
    lede: 'Liver cancer often develops in a liver already damaged by long-term disease. Because early symptoms are few, people at higher risk are sometimes offered regular monitoring.',
    causes: [
      'Long-term hepatitis B or C infection',
      'Cirrhosis (liver scarring) from any cause',
      'Heavy long-term alcohol use',
      'Fatty liver disease linked to obesity and diabetes',
      'Aflatoxins (a mould toxin on poorly stored grains and nuts)',
    ],
    symptoms: [
      ['symptoms/abdominal-pain', 'Pain or a lump in the upper right tummy'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss and loss of appetite'],
      [null, 'Yellowing of skin and eyes (jaundice)'],
      ['symptoms/itching', 'Itchy skin'],
      ['symptoms/fatigue', 'Tiredness and weakness'],
      [null, 'Swelling of the tummy (fluid build-up)'],
    ],
    tests: [
      [null, 'Liver ultrasound'],
      ['blood-tests/liver-function-test-lft', 'Liver function tests'],
      [null, 'Alpha-fetoprotein (AFP) blood test'],
      [null, 'CT or MRI of the liver'],
      [null, 'Liver biopsy in some cases'],
    ],
    treatment: [
      'Surgery to remove the tumour, when possible',
      'Liver transplant in selected cases',
      'Ablation or targeted treatments delivered through blood vessels',
      'Targeted therapy or immunotherapy for advanced disease',
      'Managing the underlying liver disease is important',
    ],
    whenToSee: [
      'Yellowing of the skin or eyes (jaundice)',
      'Persistent upper-right tummy pain or a lump',
      'Unexplained weight loss with known liver disease',
    ],
    faqs: [
      { q: 'Can hepatitis lead to liver cancer?', a: 'Yes — long-term hepatitis B or C can damage the liver and raise cancer risk over time. Vaccination against hepatitis B and treating infections lowers that risk.' },
      { q: 'How can liver cancer be caught early?', a: 'People with cirrhosis or chronic hepatitis are often offered regular ultrasound and blood tests, as symptoms appear late. Ask your doctor if monitoring applies to you.' },
    ],
  },
  {
    slug: 'leukaemia',
    name: 'Leukaemia',
    dept: ONC,
    lede: 'Leukaemia is a cancer of the blood-forming cells in the bone marrow. It can be fast-growing (acute) or slow (chronic), and symptoms come from a lack of healthy blood cells.',
    causes: [
      'Exact cause is often unknown',
      'Previous chemotherapy or radiotherapy',
      'Certain genetic conditions (e.g. Down syndrome)',
      'Heavy exposure to benzene and some chemicals',
      'Smoking (for some types)',
      'Family history in a minority of cases',
    ],
    symptoms: [
      ['symptoms/fatigue', 'Tiredness and paleness (from anaemia)'],
      ['symptoms/fever', 'Frequent infections or fevers'],
      [null, 'Easy bruising or bleeding'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands'],
      ['symptoms/night-sweats', 'Night sweats'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss and bone pain'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      [null, 'Blood film examination'],
      [null, 'Bone marrow biopsy'],
      [null, 'Genetic and flow-cytometry tests on blood/marrow'],
    ],
    treatment: [
      'Chemotherapy is the mainstay for many types',
      'Targeted therapy for certain genetic subtypes',
      'Stem-cell (bone marrow) transplant in some cases',
      'Some slow chronic types are watched before treating',
      'Supportive care — transfusions and treating infections',
    ],
    whenToSee: [
      'Unexplained bruising, bleeding or repeated infections',
      'Persistent tiredness, fever or night sweats',
      'Swollen glands or bone pain that does not settle',
    ],
    faqs: [
      { q: 'Is leukaemia always fast and life-threatening?', a: 'No. Acute leukaemias develop quickly and need urgent treatment, but chronic types can be slow and are sometimes just monitored for years. A specialist determines the type.' },
      { q: 'How is leukaemia diagnosed?', a: 'It usually starts with a blood count and blood film, followed by a bone marrow biopsy and genetic tests to confirm the type and guide treatment.' },
    ],
  },
  {
    slug: 'lymphoma',
    name: 'Lymphoma',
    dept: ONC,
    lede: 'Lymphoma is a cancer of the lymphatic system, part of the body\'s immune defences. It usually shows first as a painless swollen gland, and many types respond well to treatment.',
    causes: [
      'Cause is often unknown',
      'A weakened immune system (e.g. HIV or after transplant)',
      'Certain infections (Epstein-Barr virus, others)',
      'Some autoimmune conditions',
      'Older age (for many types)',
      'Family history in a minority of cases',
    ],
    symptoms: [
      ['symptoms/swollen-lymph-nodes', 'Painless swollen glands in the neck, armpit or groin'],
      ['symptoms/night-sweats', 'Drenching night sweats'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/fever', 'Fevers that come and go'],
      ['symptoms/fatigue', 'Tiredness'],
      ['symptoms/itching', 'Itchy skin'],
    ],
    tests: [
      [null, 'Biopsy of an affected lymph node'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      [null, 'CT or PET scan for staging'],
      [null, 'Bone marrow biopsy in some cases'],
    ],
    treatment: [
      'Chemotherapy',
      'Radiotherapy, especially for localised disease',
      'Targeted or antibody therapy (e.g. rituximab)',
      'Immunotherapy for some types',
      'Some very slow lymphomas may just be monitored',
    ],
    whenToSee: [
      'A swollen gland that lasts more than a few weeks',
      'Night sweats, unexplained fevers or weight loss',
      'Persistent tiredness or unexplained itching',
    ],
    faqs: [
      { q: 'What is the difference between Hodgkin and non-Hodgkin lymphoma?', a: 'They differ in the specific cells involved, seen under the microscope. Hodgkin lymphoma is one distinct type; non-Hodgkin covers many types. Treatment and outlook depend on the exact kind.' },
      { q: 'Is a swollen gland usually lymphoma?', a: 'No — swollen glands are far more often due to infections. But a gland that stays swollen for weeks without an obvious cause should be checked.' },
    ],
  },
  {
    slug: 'hodgkins-lymphoma',
    name: "Hodgkin's Lymphoma",
    dept: ONC,
    lede: "Hodgkin's lymphoma is a specific type of lymphoma, recognised by particular cells under the microscope. It often affects younger adults and is one of the most treatable cancers.",
    causes: [
      'Cause is usually unknown',
      'Past infection with Epstein-Barr virus (glandular fever)',
      'A weakened immune system',
      'Family history in a small number of cases',
      'Being a young adult or over 55 (two age peaks)',
    ],
    symptoms: [
      ['symptoms/swollen-lymph-nodes', 'Painless swollen glands in the neck, armpit or groin'],
      ['symptoms/night-sweats', 'Heavy night sweats'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      ['symptoms/fever', 'Recurring fevers'],
      ['symptoms/itching', 'Itchy skin'],
      ['symptoms/fatigue', 'Tiredness'],
    ],
    tests: [
      [null, 'Lymph node biopsy'],
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/esr', 'ESR (inflammation marker)'],
      [null, 'PET-CT scan for staging'],
    ],
    treatment: [
      'Chemotherapy is the main treatment',
      'Radiotherapy, often combined with chemotherapy',
      'Targeted or immunotherapy for resistant or relapsed disease',
      'Stem-cell transplant in selected cases',
      'Outlook is generally very good, especially when found early',
    ],
    whenToSee: [
      'A painless swollen gland lasting more than a few weeks',
      'Drenching night sweats or unexplained fevers',
      'Unexplained weight loss with persistent tiredness',
    ],
    faqs: [
      { q: "Is Hodgkin's lymphoma curable?", a: "It is one of the most treatable cancers, and many people are cured, particularly when it is found early. A specialist team guides treatment based on the stage." },
      { q: 'What causes the itching?', a: 'Some people with lymphoma have widespread itchy skin, thought to be caused by chemicals released by the cancer. It often improves once treatment starts.' },
    ],
  },
  {
    slug: 'multiple-myeloma',
    name: 'Multiple Myeloma',
    dept: ONC,
    lede: 'Multiple myeloma is a cancer of plasma cells in the bone marrow. It is not curable for most people, but treatment can control it well and relieve symptoms for years.',
    causes: [
      'Cause is usually unknown',
      'Increasing age (mostly over 60)',
      'Being male, and of African ancestry (higher risk)',
      'A pre-cancerous condition called MGUS',
      'Family history in a minority of cases',
    ],
    symptoms: [
      ['symptoms/back-pain', 'Bone pain, often in the back or ribs'],
      [null, 'Bones that fracture easily'],
      ['symptoms/fatigue', 'Tiredness from anaemia'],
      ['symptoms/fever', 'Frequent infections'],
      [null, 'Excess calcium — thirst, confusion, constipation'],
      [null, 'Kidney problems'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/calcium', 'Calcium level'],
      ['blood-tests/kidney-function-test-rft', 'Kidney function tests'],
      [null, 'Blood and urine tests for abnormal proteins'],
      [null, 'Bone marrow biopsy and imaging of bones'],
    ],
    treatment: [
      'Chemotherapy and targeted drug combinations',
      'Steroids as part of treatment',
      'Stem-cell transplant in suitable patients',
      'Bone-strengthening medicines and radiotherapy for bone pain',
      'Treatment aims to control the disease and protect quality of life',
    ],
    whenToSee: [
      'Persistent or unexplained bone pain, especially in the back',
      'A bone that breaks after a minor injury',
      'Unexplained tiredness, repeated infections or excessive thirst',
    ],
    faqs: [
      { q: 'Is multiple myeloma the same as bone cancer?', a: 'Not quite. It starts in plasma cells in the bone marrow rather than in the bone itself, but it commonly damages bones, which is why bone pain and fractures are common.' },
      { q: 'Can myeloma be cured?', a: 'For most people it is treated as a long-term condition that can be controlled rather than cured. Modern treatments can keep it in check for many years.' },
    ],
  },
  {
    slug: 'ovarian-cancer',
    name: 'Ovarian Cancer',
    dept: ONC,
    lede: 'Ovarian cancer can be hard to spot early because its symptoms are vague and easily mistaken for common tummy complaints. Persistent bloating or pelvic symptoms should be checked.',
    causes: [
      'Increasing age (mostly after menopause)',
      'Inherited genes (BRCA1/BRCA2) and family history',
      'Not having children or having them later',
      'Endometriosis',
      'Being overweight',
      'Hormone replacement therapy (small effect)',
    ],
    symptoms: [
      ['symptoms/bloating', 'Persistent bloating'],
      ['symptoms/abdominal-pain', 'Tummy or pelvic pain'],
      [null, 'Feeling full quickly or loss of appetite'],
      ['symptoms/frequent-urination', 'Needing to pass urine more often'],
      [null, 'Change in bowel habit'],
      ['symptoms/fatigue', 'Tiredness and unexplained weight change'],
    ],
    tests: [
      [null, 'Pelvic and transvaginal ultrasound'],
      [null, 'CA-125 blood test'],
      [null, 'CT scan for staging'],
      [null, 'Biopsy or examination during surgery'],
    ],
    treatment: [
      'Surgery to remove the ovaries and affected tissue',
      'Chemotherapy before or after surgery',
      'Targeted therapy for some cancers',
      'Maintenance treatment to delay return in selected cases',
      'A specialist gynae-oncology team plans care',
    ],
    whenToSee: [
      'Bloating that is persistent and does not come and go',
      'Ongoing pelvic or tummy pain',
      'Feeling full quickly or needing to urinate more often, over weeks',
    ],
    faqs: [
      { q: 'Is bloating a sign of ovarian cancer?', a: 'Occasional bloating is usually harmless. But bloating that is persistent (most days for three weeks or more), especially with pelvic pain or feeling full quickly, should be checked.' },
      { q: 'Should I be tested if it runs in my family?', a: 'If you have a strong family history of ovarian or breast cancer, ask your doctor. You may be offered genetic testing and advice on reducing risk.' },
    ],
  },
  {
    slug: 'pancreatic-cancer',
    name: 'Pancreatic Cancer',
    dept: ONC,
    lede: 'Pancreatic cancer often causes few symptoms until it is advanced, which makes it hard to treat. Painless jaundice or persistent upper-tummy and back pain should prompt a check.',
    causes: [
      'Increasing age',
      'Smoking',
      'Long-standing diabetes',
      'Chronic pancreatitis',
      'Being overweight',
      'Family history and certain inherited genes',
    ],
    symptoms: [
      [null, 'Yellowing of skin and eyes (jaundice), often painless'],
      ['symptoms/abdominal-pain', 'Upper tummy pain spreading to the back'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss'],
      [null, 'Loss of appetite and indigestion'],
      [null, 'New diabetes or worsening blood sugar'],
      [null, 'Pale, greasy stools'],
    ],
    tests: [
      [null, 'CT scan of the abdomen'],
      [null, 'MRI or specialist scan (MRCP)'],
      [null, 'Endoscopic ultrasound with biopsy'],
      ['blood-tests/liver-function-test-lft', 'Liver function tests'],
      [null, 'CA 19-9 blood test'],
    ],
    treatment: [
      'Surgery to remove the tumour when caught early enough',
      'Chemotherapy, before or after surgery or for advanced disease',
      'Radiotherapy in some cases',
      'Treatments to relieve jaundice and pain (supportive care)',
      'A specialist team decides what is possible',
    ],
    whenToSee: [
      'Yellowing of the skin or eyes, especially if painless',
      'Persistent upper tummy or back pain with weight loss',
      'New unexplained diabetes with tummy symptoms',
    ],
    faqs: [
      { q: 'Why is pancreatic cancer often found late?', a: 'The pancreas sits deep in the abdomen and early cancers rarely cause clear symptoms. When symptoms like jaundice or back pain appear, the cancer may already be advanced — so persistent symptoms should be checked promptly.' },
      { q: 'Can new diabetes be a warning sign?', a: 'In some people, sudden new diabetes in later life — especially with weight loss or tummy pain — can be an early clue to pancreatic cancer, and is worth mentioning to your doctor.' },
    ],
  },
  {
    slug: 'thyroid-cancer',
    name: 'Thyroid Cancer',
    dept: ONC,
    lede: 'Thyroid cancer usually shows up as a painless lump in the neck. Most types grow slowly and have an excellent outlook, particularly when found and treated early.',
    causes: [
      'Radiation exposure, especially in childhood',
      'A family history of thyroid cancer',
      'Certain inherited conditions',
      'Being female',
      'Long-standing goitre or thyroid nodules',
      'Iodine deficiency (for some types)',
    ],
    symptoms: [
      [null, 'A painless lump in the front of the neck'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands in the neck'],
      [null, 'A hoarse voice that does not improve'],
      ['symptoms/sore-throat', 'Difficulty swallowing or a persistent sore throat'],
      [null, 'A feeling of pressure in the neck'],
    ],
    tests: [
      [null, 'Neck ultrasound'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid function tests'],
      [null, 'Fine-needle aspiration biopsy'],
      [null, 'Radioactive iodine scan in some cases'],
    ],
    treatment: [
      'Surgery to remove part or all of the thyroid',
      'Radioactive iodine treatment after surgery for some types',
      'Thyroid hormone tablets after removal',
      'External radiotherapy or targeted therapy for rare aggressive types',
      'Most common types have a very good outlook',
    ],
    whenToSee: [
      'A lump in the neck that lasts more than a few weeks',
      'A hoarse voice or swallowing difficulty that does not settle',
      'A swollen neck gland with no infection to explain it',
    ],
    faqs: [
      { q: 'Is a thyroid lump usually cancer?', a: 'No — most thyroid lumps (nodules) are benign. But because a small number are cancerous, a new or growing lump should be checked with an ultrasound and, if needed, a biopsy.' },
      { q: 'Will I need thyroid tablets after surgery?', a: 'If all or most of the thyroid is removed, you will take thyroid hormone tablets daily to replace what the gland made. This is straightforward and monitored with blood tests.' },
    ],
  },
  {
    slug: 'skin-cancer-melanoma',
    name: 'Skin Cancer & Melanoma',
    dept: ONC,
    lede: 'Skin cancer is very common and mostly linked to sun exposure. Melanoma is the most serious type; caught early it is usually curable, which is why watching moles matters.',
    causes: [
      'Ultraviolet (UV) light from sun or sunbeds',
      'Fair skin that burns easily',
      'Many moles or unusual moles',
      'A history of sunburn, especially in childhood',
      'A weakened immune system',
      'Family history of skin cancer',
    ],
    symptoms: [
      [null, 'A new mole, or a mole that changes size, shape or colour'],
      [null, 'A mole with an irregular border or several colours'],
      [null, 'A sore or spot that does not heal'],
      [null, 'A pearly, waxy or scaly patch (non-melanoma types)'],
      ['symptoms/itching', 'A mole that itches, bleeds or crusts'],
    ],
    tests: [
      [null, 'Skin examination, often with a dermatoscope'],
      [null, 'Skin biopsy'],
      ['symptoms/swollen-lymph-nodes', 'Checking nearby lymph glands'],
      [null, 'Imaging for staging if melanoma has spread'],
    ],
    treatment: [
      'Surgery to remove the cancer is the main treatment',
      'Cream, freezing or light therapy for some early non-melanoma cancers',
      'Radiotherapy in some cases',
      'Immunotherapy or targeted therapy for advanced melanoma',
      'Sun protection helps prevent new skin cancers',
    ],
    whenToSee: [
      'A mole that changes in size, shape, colour or is asymmetrical',
      'A mole that itches, bleeds, crusts or becomes inflamed',
      'A new skin spot or sore that does not heal within weeks',
    ],
    faqs: [
      { q: 'How can I tell a normal mole from melanoma?', a: 'The ABCDE guide helps: Asymmetry, an irregular Border, more than one Colour, a Diameter larger than a pencil eraser, and Evolving (changing). Any of these warrants a check.' },
      { q: 'Do sunbeds cause skin cancer?', a: 'Yes. Sunbeds give out UV light that damages skin and raises the risk of melanoma and other skin cancers, especially with use before age 35.' },
    ],
  },
  {
    slug: 'bladder-cancer',
    name: 'Bladder Cancer',
    dept: ONC,
    lede: 'Bladder cancer most often shows up as blood in the urine, usually without pain. It is more common in older adults and in smokers, and early diagnosis improves outcomes.',
    causes: [
      'Smoking (the biggest risk factor)',
      'Exposure to certain workplace chemicals (dyes, rubber, paint)',
      'Increasing age and being male',
      'Long-term bladder infections or irritation',
      'Previous radiotherapy or chemotherapy to the pelvis',
      'Chronic schistosomiasis infection (in some regions)',
    ],
    symptoms: [
      ['symptoms/blood-in-urine', 'Blood in the urine, often painless'],
      ['symptoms/frequent-urination', 'Needing to pass urine more often'],
      ['symptoms/painful-urination', 'Pain or burning when passing urine'],
      [null, 'A sudden urgent need to pass urine'],
      ['symptoms/pelvic-pain', 'Pelvic pain (later stages)'],
    ],
    tests: [
      [null, 'Urine tests, including for cancer cells'],
      [null, 'Cystoscopy (camera into the bladder)'],
      [null, 'CT scan or ultrasound'],
      [null, 'Biopsy during cystoscopy'],
    ],
    treatment: [
      'Removing the tumour through the urethra for early cancers',
      'Medicines placed into the bladder to reduce return',
      'Surgery to remove part or all of the bladder for deeper cancers',
      'Chemotherapy, radiotherapy or immunotherapy',
      'Stopping smoking lowers the risk of return',
    ],
    whenToSee: [
      'Any blood in your urine, even once and even if painless',
      'Persistent urinary urgency, frequency or burning',
      'New pelvic pain with urinary symptoms',
    ],
    faqs: [
      { q: 'I saw blood in my urine once — should I worry?', a: 'Even a single episode of visible blood in the urine should be checked, as it can be the first and only sign of bladder cancer. It is often something less serious, but it needs assessing.' },
      { q: 'Does smoking really affect the bladder?', a: 'Yes. Harmful chemicals from smoking are filtered by the kidneys and collect in the bladder, making smoking the single biggest risk factor for bladder cancer.' },
    ],
  },
  {
    slug: 'anaemia',
    name: 'Anaemia',
    dept: ONC,
    lede: 'Anaemia means having too few healthy red blood cells or too little haemoglobin to carry oxygen around the body. It is very common and often treatable once the cause is found.',
    causes: [
      'Iron deficiency (poor diet, heavy periods, blood loss)',
      'Vitamin B12 or folate deficiency',
      'Long-term illness (kidney disease, inflammation, cancer)',
      'Blood loss from the gut or elsewhere',
      'Inherited conditions (thalassaemia, sickle cell)',
      'Pregnancy',
    ],
    symptoms: [
      ['symptoms/fatigue', 'Tiredness and lack of energy'],
      [null, 'Pale skin'],
      ['symptoms/shortness-of-breath', 'Breathlessness, especially on exertion'],
      ['symptoms/heart-palpitations', 'A fast or pounding heartbeat'],
      ['symptoms/dizziness', 'Dizziness or headaches'],
      [null, 'Brittle nails or hair thinning (iron deficiency)'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/hemoglobin', 'Haemoglobin level'],
      ['blood-tests/ferritin-iron-studies', 'Iron studies / ferritin'],
      ['blood-tests/vitamin-b12', 'Vitamin B12 and folate'],
      [null, 'Tests to find a source of bleeding if needed'],
    ],
    treatment: [
      'Iron supplements and iron-rich foods for iron deficiency',
      'Vitamin B12 or folate replacement when low',
      'Treating the underlying cause (e.g. heavy periods, bleeding)',
      'Blood transfusion for severe anaemia',
      'Specialist care for inherited or bone-marrow causes',
    ],
    whenToSee: [
      'Ongoing tiredness with breathlessness or a racing heart',
      'Anaemia found on a blood test with no obvious cause',
      'Anaemia with black stools, blood loss or weight loss',
    ],
    faqs: [
      { q: 'Is anaemia serious?', a: 'Mild anaemia is common and usually treatable. But because it can be a sign of another problem, such as bleeding in the gut, the cause should always be identified — not just the anaemia treated.' },
      { q: 'Can I fix anaemia with diet alone?', a: 'Diet helps for mild iron deficiency, but many people need supplements, and some types of anaemia need specific treatment. Your doctor will advise based on the cause.' },
    ],
  },
  {
    slug: 'thrombocytopenia',
    name: 'Thrombocytopenia (Low Platelets)',
    dept: ONC,
    lede: 'Thrombocytopenia means a low platelet count. Platelets help blood clot, so when they are low you may bruise or bleed more easily. The cause guides how serious it is.',
    causes: [
      'Immune conditions that destroy platelets (ITP)',
      'Viral infections (including dengue)',
      'Some medicines',
      'Bone marrow problems, including cancers',
      'Liver disease or an enlarged spleen',
      'Heavy alcohol use or certain vitamin deficiencies',
    ],
    symptoms: [
      [null, 'Easy or unexplained bruising'],
      [null, 'Tiny red or purple spots on the skin (petechiae)'],
      [null, 'Bleeding gums or frequent nosebleeds'],
      ['symptoms/blood-in-urine', 'Blood in urine or stool'],
      [null, 'Heavy or prolonged menstrual bleeding'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/platelet-count', 'Platelet count'],
      [null, 'Blood film examination'],
      ['blood-tests/dengue-test', 'Dengue test where relevant'],
      [null, 'Bone marrow biopsy in some cases'],
    ],
    treatment: [
      'Treating the underlying cause (infection, medicine, illness)',
      'Steroids or other medicines for immune causes',
      'Platelet transfusion for severe or dangerous bleeding',
      'Stopping any medicine that may be responsible',
      'A specialist manages persistent or unexplained cases',
    ],
    whenToSee: [
      'Unexplained bruising, or tiny red spots on the skin',
      'Bleeding gums, frequent nosebleeds or blood in urine/stool',
      'Any heavy bleeding that will not stop — seek urgent care',
    ],
    faqs: [
      { q: 'Why do low platelets cause bleeding and bruising?', a: 'Platelets are the cells that help blood clot. When their number falls, small blood vessels leak more easily, causing bruises, pinpoint spots and bleeding from the gums or nose.' },
      { q: 'Can dengue cause low platelets?', a: 'Yes. Dengue and some other viral infections commonly lower the platelet count for a time. Doctors monitor it closely and it usually recovers as you get better.' },
    ],
  },
  {
    slug: 'blood-clotting-disorders',
    name: 'Blood Clotting Disorders',
    dept: ONC,
    lede: 'Clotting disorders affect how well the blood clots — either bleeding too easily (like haemophilia) or clotting too much (thrombophilia). Some are inherited and some develop later.',
    causes: [
      'Inherited conditions (haemophilia, von Willebrand disease)',
      'Inherited tendency to clot (thrombophilia)',
      'Liver disease (affects clotting proteins)',
      'Vitamin K deficiency',
      'Some medicines, including blood thinners',
      'Antiphospholipid syndrome and other immune conditions',
    ],
    symptoms: [
      [null, 'Easy bruising or prolonged bleeding after cuts'],
      [null, 'Heavy periods or bleeding after surgery/dental work'],
      [null, 'Bleeding into joints or muscles (haemophilia)'],
      ['symptoms/leg-swelling', 'Leg swelling and pain from a clot (DVT)'],
      ['symptoms/shortness-of-breath', 'Sudden breathlessness from a lung clot'],
    ],
    tests: [
      ['blood-tests/complete-blood-count-cbc', 'Full blood count'],
      ['blood-tests/pt-inr', 'Clotting tests (PT/INR, APTT)'],
      ['blood-tests/d-dimer', 'D-dimer where a clot is suspected'],
      [null, 'Specialist clotting-factor and genetic tests'],
    ],
    treatment: [
      'Replacing missing clotting factors for bleeding disorders',
      'Blood thinners (anticoagulants) for excess clotting',
      'Medicines to help blood clot before surgery or dental work',
      'Treating underlying causes such as liver disease',
      'Specialist (haematology) care and a clear action plan',
    ],
    whenToSee: [
      'Bleeding that is hard to stop, or bruising with no clear cause',
      'A swollen, painful calf, or sudden breathlessness and chest pain — seek urgent care',
      'A family history of bleeding or clotting problems before surgery',
    ],
    faqs: [
      { q: 'Are clotting disorders always inherited?', a: 'No. Some, like haemophilia, are inherited, but others develop from liver disease, medicines or immune conditions later in life. Tests help identify the type.' },
      { q: 'What is the difference between bleeding and clotting disorders?', a: 'Bleeding disorders make it hard for blood to clot, so you bleed or bruise easily. Clotting disorders make blood clot too readily, raising the risk of dangerous clots in the legs or lungs.' },
    ],
  },

  // =====================================================================
  // SEXUAL HEALTH
  // =====================================================================
  {
    slug: 'chlamydia',
    name: 'Chlamydia',
    dept: SXH,
    lede: 'Chlamydia is one of the most common sexually transmitted infections. Many people have no symptoms at all, which is why regular, confidential testing matters. It is easily treated.',
    causes: [
      'Unprotected vaginal, anal or oral sex',
      'Sex with a new or multiple partners without a condom',
      'A partner who has chlamydia',
      'Sharing sex toys without cleaning or covering them',
      'Passed to a baby during birth',
    ],
    symptoms: [
      [null, 'Often no symptoms at all'],
      ['symptoms/painful-urination', 'Pain or burning when passing urine'],
      [null, 'Unusual discharge from the vagina, penis or anus'],
      ['symptoms/pelvic-pain', 'Pelvic or lower tummy pain'],
      [null, 'Bleeding between periods or after sex'],
      [null, 'Pain or swelling in the testicles'],
    ],
    tests: [
      [null, 'Urine test (for men, usually)'],
      [null, 'Vaginal or genital swab'],
      [null, 'Swab from the throat or rectum if relevant'],
      [null, 'Testing for other STIs at the same time'],
    ],
    treatment: [
      'A short course of antibiotics (a doctor prescribes the type)',
      'Avoiding sex until treatment is finished and cleared',
      'Testing and treating recent sexual partners',
      'A repeat test in some cases to confirm it has gone',
      'Using condoms to prevent reinfection',
    ],
    whenToSee: [
      'Any unusual discharge, pain passing urine or pelvic pain',
      'If a sexual partner tells you they have chlamydia',
      'For a check-up after unprotected sex, even with no symptoms',
    ],
    faqs: [
      { q: 'Can I have chlamydia without symptoms?', a: 'Yes — most people with chlamydia have no symptoms, so you can carry and pass it on without knowing. This is why regular testing is recommended if you are sexually active.' },
      { q: 'Is testing confidential?', a: 'Yes. Sexual health testing is confidential. Many clinics offer free, private testing and some allow home testing kits.' },
    ],
  },
  {
    slug: 'gonorrhoea',
    name: 'Gonorrhoea',
    dept: SXH,
    lede: 'Gonorrhoea is a common sexually transmitted infection caused by bacteria. It can affect the genitals, rectum and throat, and often causes no symptoms — so testing is important.',
    causes: [
      'Unprotected vaginal, anal or oral sex',
      'Sex with a new or multiple partners without a condom',
      'A partner who has gonorrhoea',
      'Sharing sex toys',
      'Passed to a baby during birth',
    ],
    symptoms: [
      [null, 'Often no symptoms, especially in women'],
      [null, 'Thick discharge from the vagina or penis'],
      ['symptoms/painful-urination', 'Pain or burning when passing urine'],
      [null, 'Pain or swelling in the testicles'],
      ['symptoms/pelvic-pain', 'Pelvic pain in women'],
      [null, 'Anal discharge or discomfort'],
    ],
    tests: [
      [null, 'Genital, throat or rectal swab'],
      [null, 'Urine test'],
      [null, 'Testing for other STIs alongside'],
    ],
    treatment: [
      'Antibiotic treatment prescribed by a doctor',
      'Avoiding sex until treatment is complete',
      'Testing and treating recent partners',
      'A follow-up test to confirm the infection has cleared',
      'Using condoms to prevent reinfection',
    ],
    whenToSee: [
      'Unusual genital discharge or pain passing urine',
      'If a partner tells you they have gonorrhoea',
      'For confidential testing after unprotected sex',
    ],
    faqs: [
      { q: 'Why is a follow-up test important for gonorrhoea?', a: 'Some strains of gonorrhoea have become resistant to certain antibiotics. A follow-up test (test of cure) helps make sure the treatment has worked.' },
      { q: 'Can gonorrhoea affect the throat?', a: 'Yes. It can infect the throat through oral sex and often causes no symptoms there, which is why the type of test depends on the kinds of sex you have had.' },
    ],
  },
  {
    slug: 'syphilis',
    name: 'Syphilis',
    dept: SXH,
    lede: 'Syphilis is a sexually transmitted infection that develops in stages. It is treatable, especially early, but if left untreated over years it can cause serious harm to the body.',
    causes: [
      'Unprotected vaginal, anal or oral sex',
      'Direct contact with a syphilis sore',
      'Sharing needles',
      'From a pregnant person to their baby',
      'Multiple sexual partners without protection',
    ],
    symptoms: [
      [null, 'A painless sore (chancre) where infection entered'],
      ['symptoms/skin-rash', 'A rash, often on the palms and soles'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands'],
      ['symptoms/fever', 'Flu-like feelings and tiredness'],
      [null, 'Wart-like growths in moist areas'],
      [null, 'Long symptom-free periods between stages'],
    ],
    tests: [
      [null, 'Blood test for syphilis'],
      [null, 'Swab from a sore'],
      [null, 'Testing for other STIs, including HIV'],
    ],
    treatment: [
      'Antibiotic treatment, usually penicillin injections',
      'Earlier treatment needs fewer doses',
      'Testing and treating sexual partners',
      'Follow-up blood tests to confirm success',
      'Avoiding sex until treatment is complete and cleared',
    ],
    whenToSee: [
      'A painless sore on the genitals, mouth or anus',
      'An unexplained rash, especially on palms and soles',
      'If a partner has syphilis, or after unprotected sex',
    ],
    faqs: [
      { q: 'Why is syphilis called the great imitator?', a: 'Its symptoms can look like many other conditions and often come and go, so it can be missed. A simple blood test is the reliable way to diagnose it.' },
      { q: 'Can syphilis be cured?', a: 'Yes. Antibiotics cure syphilis, and treatment is most effective in the early stages. Any damage already done in late-stage disease may not be reversible, so early testing matters.' },
    ],
  },
  {
    slug: 'genital-herpes',
    name: 'Genital Herpes',
    dept: SXH,
    lede: 'Genital herpes is a common infection caused by the herpes simplex virus. It can cause painful blisters, but many people have mild or no symptoms. It is manageable, though not curable.',
    causes: [
      'The herpes simplex virus (HSV-1 or HSV-2)',
      'Skin-to-skin contact during vaginal, anal or oral sex',
      'Contact with a cold sore during oral sex',
      'Passed on even when there are no visible sores',
      'Sharing sex toys',
    ],
    symptoms: [
      [null, 'Small painful blisters or sores around the genitals or anus'],
      [null, 'Tingling, itching or burning before sores appear'],
      ['symptoms/painful-urination', 'Pain when passing urine'],
      ['symptoms/fever', 'Flu-like feelings during the first outbreak'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands in the groin'],
      [null, 'Recurring milder outbreaks over time'],
    ],
    tests: [
      [null, 'Examination of the sores'],
      [null, 'A swab taken from a blister or sore'],
      [null, 'Testing for other STIs'],
    ],
    treatment: [
      'Antiviral medicines to ease and shorten outbreaks',
      'Pain relief and keeping the area clean and dry',
      'Longer-term antivirals for frequent outbreaks',
      'The virus stays in the body, but outbreaks usually lessen over time',
      'Condoms reduce but do not fully remove the risk of passing it on',
    ],
    whenToSee: [
      'Painful genital blisters or sores, especially a first outbreak',
      'Very frequent or severe outbreaks',
      'Symptoms during pregnancy — tell your maternity team',
    ],
    faqs: [
      { q: 'Can genital herpes be cured?', a: 'No, the virus stays in the body for life, but it is very manageable. Antiviral medicines control outbreaks, which usually become milder and less frequent over time.' },
      { q: 'Can I pass it on without symptoms?', a: 'Yes. The virus can sometimes be passed on even when there are no visible sores. Condoms and avoiding sex during outbreaks reduce the risk.' },
    ],
  },
  {
    slug: 'hpv-genital-warts',
    name: 'HPV & Genital Warts',
    dept: SXH,
    lede: 'HPV (human papillomavirus) is a very common infection. Most cases clear on their own, but some types cause genital warts and others can lead to cancer. Vaccination protects against the main types.',
    causes: [
      'Skin-to-skin contact during vaginal, anal or oral sex',
      'Very common — most sexually active people get some HPV type',
      'Multiple partners without protection increases exposure',
      'A weakened immune system (harder to clear the virus)',
      'Smoking (makes clearance less likely)',
    ],
    symptoms: [
      [null, 'Often no symptoms — many infections clear silently'],
      [null, 'Small fleshy growths (warts) on or around the genitals or anus'],
      ['symptoms/itching', 'Itching or discomfort around warts'],
      [null, 'Occasional bleeding from a wart'],
    ],
    tests: [
      [null, 'Examination of visible warts'],
      [null, 'Cervical screening with HPV testing (in women)'],
      [null, 'Testing for other STIs'],
    ],
    treatment: [
      'Warts may be treated with creams, freezing or removal',
      'Warts can come back and often need more than one treatment',
      'No treatment removes the virus itself — the body usually clears it',
      'HPV vaccination prevents the main wart- and cancer-causing types',
      'Cervical screening detects HPV-related changes early',
    ],
    whenToSee: [
      'New lumps or growths around the genitals or anus',
      'To discuss the HPV vaccine, especially for young people',
      'For routine cervical screening when invited',
    ],
    faqs: [
      { q: 'Does HPV always cause cancer?', a: 'No. Most HPV infections cause no harm and clear on their own. Only some high-risk types, if they persist, can lead to cancers such as cervical cancer — which screening and vaccination help prevent.' },
      { q: 'Is the HPV vaccine worth having?', a: 'Yes. It protects against the HPV types that cause most genital warts and HPV-related cancers, and works best when given before someone becomes sexually active.' },
    ],
  },
  {
    slug: 'hiv',
    name: 'HIV',
    dept: SXH,
    lede: 'HIV is a virus that weakens the immune system. With today\'s treatment, people with HIV can live long, healthy lives and cannot pass it on when the virus is undetectable. Early testing is key.',
    causes: [
      'Unprotected vaginal or anal sex',
      'Sharing needles or injecting equipment',
      'From a mother to baby during pregnancy, birth or breastfeeding',
      'Contact with infected blood',
      'It is not spread by everyday contact, kissing or sharing utensils',
    ],
    symptoms: [
      ['symptoms/fever', 'A flu-like illness a few weeks after infection'],
      ['symptoms/sore-throat', 'Sore throat and body aches'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands'],
      ['symptoms/skin-rash', 'A rash'],
      [null, 'Often no symptoms for years'],
      ['symptoms/unexplained-weight-loss', 'Weight loss and repeated infections (later, untreated)'],
    ],
    tests: [
      [null, 'HIV blood test (or finger-prick / home test)'],
      [null, 'Repeat testing after any recent exposure (window period)'],
      [null, 'Testing for other STIs'],
    ],
    treatment: [
      'Antiretroviral therapy (daily tablets) controls the virus',
      'Treatment keeps the immune system healthy and life expectancy near normal',
      'When the virus is undetectable it cannot be passed on sexually (U=U)',
      'PrEP can prevent HIV in people at higher risk',
      'PEP can reduce risk if started soon after possible exposure',
    ],
    whenToSee: [
      'After any possible exposure — ask urgently about PEP (within 72 hours)',
      'For routine testing if you are sexually active or share needles',
      'A flu-like illness after a recent risk, or to discuss PrEP',
    ],
    faqs: [
      { q: 'Is HIV a death sentence?', a: 'No. With modern treatment, people with HIV can expect a normal life span and good health. The key is early diagnosis and starting treatment.' },
      { q: 'What does undetectable = untransmittable mean?', a: 'When treatment lowers the virus to an undetectable level in the blood, HIV cannot be passed on through sex. This is known as U=U.' },
    ],
  },
  {
    slug: 'trichomoniasis',
    name: 'Trichomoniasis',
    dept: SXH,
    lede: 'Trichomoniasis is a common sexually transmitted infection caused by a tiny parasite. Many people have no symptoms, but it is easily treated with antibiotics once diagnosed.',
    causes: [
      'Unprotected vaginal sex',
      'Sharing sex toys without washing or covering them',
      'A partner who has the infection',
      'Multiple sexual partners without protection',
    ],
    symptoms: [
      [null, 'Often no symptoms'],
      [null, 'Unusual discharge, sometimes frothy or with an odour'],
      ['symptoms/painful-urination', 'Pain or burning when passing urine'],
      ['symptoms/itching', 'Itching or soreness around the genitals'],
      [null, 'Discomfort during sex'],
    ],
    tests: [
      [null, 'Genital swab'],
      [null, 'Urine test in some cases'],
      [null, 'Testing for other STIs'],
    ],
    treatment: [
      'A course of antibiotics prescribed by a doctor',
      'Treating sexual partners at the same time',
      'Avoiding sex until treatment is finished and cleared',
      'Using condoms to prevent reinfection',
    ],
    whenToSee: [
      'Unusual discharge, itching or soreness around the genitals',
      'Pain passing urine or during sex',
      'If a partner has been diagnosed with trichomoniasis',
    ],
    faqs: [
      { q: 'Can men get trichomoniasis?', a: 'Yes, though men often have no symptoms. They can still carry and pass on the infection, which is why partners are treated together.' },
      { q: 'Is trichomoniasis serious?', a: 'It is usually easily treated. But if left untreated it can cause ongoing symptoms and, in pregnancy, may lead to complications — so it is worth getting checked and treated.' },
    ],
  },
  {
    slug: 'bacterial-vaginosis',
    name: 'Bacterial Vaginosis',
    dept: SXH,
    lede: 'Bacterial vaginosis (BV) is a common cause of unusual vaginal discharge. It happens when the natural balance of bacteria changes. It is not an STI, though it is linked to sexual activity.',
    causes: [
      'A change in the natural balance of vaginal bacteria',
      'New or multiple sexual partners',
      'Douching or using scented washes',
      'Not fully understood — it is not passed on like an STI',
      'More common around periods or with an intrauterine device',
    ],
    symptoms: [
      [null, 'Thin, greyish-white discharge'],
      [null, 'A strong fishy smell, often worse after sex'],
      [null, 'Often no itching or soreness'],
      [null, 'Many women have no symptoms at all'],
    ],
    tests: [
      [null, 'Examination and a vaginal swab'],
      [null, 'Checking the vaginal pH'],
      [null, 'Testing for STIs if symptoms overlap'],
    ],
    treatment: [
      'A course of antibiotics (tablets or vaginal gel)',
      'Avoiding douching and scented products',
      'It can come back, and repeat treatment is sometimes needed',
      'Treatment is advised in pregnancy or before some procedures',
    ],
    whenToSee: [
      'A change in discharge, especially with a fishy smell',
      'Symptoms that return after treatment',
      'Any unusual discharge in pregnancy',
    ],
    faqs: [
      { q: 'Is bacterial vaginosis an STI?', a: 'No. BV is caused by an imbalance in the bacteria naturally found in the vagina, not by an infection passed from a partner. It is, however, more common in people who are sexually active.' },
      { q: 'How is BV different from thrush?', a: 'Thrush usually causes itching and a thick white discharge, while BV causes a thin greyish discharge with a fishy smell. A swab can tell them apart, as treatment differs.' },
    ],
  },
  {
    slug: 'erectile-dysfunction',
    name: 'Erectile Dysfunction',
    dept: SXH,
    lede: 'Erectile dysfunction (ED) means difficulty getting or keeping an erection. It is very common, especially with age, and is often a sign of a treatable physical or emotional cause.',
    causes: [
      'Reduced blood flow (heart disease, high blood pressure, diabetes)',
      'High cholesterol and smoking',
      'Stress, anxiety, depression or relationship worries',
      'Low testosterone or hormonal problems',
      'Some medicines',
      'Alcohol and recreational drugs',
    ],
    symptoms: [
      [null, 'Trouble getting an erection'],
      [null, 'Trouble keeping an erection during sex'],
      [null, 'Reduced sexual desire in some cases'],
      [null, 'Occasional difficulty (common) versus persistent (worth checking)'],
    ],
    tests: [
      [null, 'A review of general health, medicines and lifestyle'],
      ['blood-tests/fasting-blood-sugar', 'Blood sugar (for diabetes)'],
      ['blood-tests/lipid-profile-cholesterol', 'Cholesterol'],
      ['blood-tests/testosterone', 'Testosterone level'],
      [null, 'Blood pressure check'],
    ],
    treatment: [
      'Treating underlying conditions (diabetes, blood pressure, cholesterol)',
      'Lifestyle changes — stopping smoking, exercise, less alcohol',
      'Prescription medicines that improve blood flow',
      'Counselling or therapy where stress or anxiety plays a part',
      'Specialist options if first treatments do not work',
    ],
    whenToSee: [
      'Persistent difficulty getting or keeping an erection',
      'ED with chest pain on exertion, or other heart symptoms',
      'When it causes distress or affects your relationship',
    ],
    faqs: [
      { q: 'Is erectile dysfunction a sign of heart problems?', a: 'It can be. Because erections depend on healthy blood flow, ED is sometimes an early warning of narrowed blood vessels, so it is worth checking blood pressure, sugar and cholesterol.' },
      { q: 'Is ED just part of getting older?', a: 'It becomes more common with age, but it is not inevitable and is usually treatable. It should not be dismissed, as it can point to a health issue that benefits from attention.' },
    ],
  },
  {
    slug: 'contraception-overview',
    name: 'Contraception Overview',
    dept: SXH,
    lede: 'Contraception helps prevent unplanned pregnancy, and there are many methods to choose from. The best one depends on your health, lifestyle and preferences — a doctor can help you decide.',
    causes: [
      'Barrier methods — condoms (also protect against STIs)',
      'Combined pill, mini-pill, patch and vaginal ring',
      'Long-acting methods — implant, injection, coil (IUD/IUS)',
      'Emergency contraception after unprotected sex',
      'Permanent methods — sterilisation',
      'Natural family planning (fertility awareness)',
    ],
    symptoms: [
      [null, 'Wanting to prevent pregnancy reliably'],
      [null, 'Needing protection against STIs (condoms)'],
      [null, 'Managing heavy or painful periods (some methods help)'],
      [null, 'Preferring a method you do not have to remember daily'],
    ],
    tests: [
      [null, 'A health and lifestyle discussion with a clinician'],
      [null, 'Blood pressure check before some methods'],
      [null, 'STI testing where appropriate'],
    ],
    treatment: [
      'Choosing a method that fits your health and lifestyle',
      'Long-acting methods are the most reliable, day to day',
      'Only condoms also protect against most STIs',
      'You can switch methods if one does not suit you',
      'Regular review, especially if your health changes',
    ],
    whenToSee: [
      'To choose or change a contraceptive method',
      'If you miss pills or a method fails — ask about emergency options',
      'If you have side effects, or your health or medicines change',
    ],
    faqs: [
      { q: 'Which contraception is the most effective?', a: 'Long-acting reversible methods — the implant, injection and coil — are the most effective because they do not rely on remembering to use them. A clinician can help you choose.' },
      { q: 'Does the pill protect against STIs?', a: 'No. Only condoms protect against most sexually transmitted infections. Many people use condoms alongside another method for both pregnancy and STI protection.' },
    ],
  },
  {
    slug: 'emergency-contraception',
    name: 'Emergency Contraception',
    dept: SXH,
    lede: 'Emergency contraception can prevent pregnancy after unprotected sex or if regular contraception failed. It works best the sooner it is used, so act quickly if you need it.',
    causes: [
      'Unprotected sex',
      'A condom that split or came off',
      'Missed contraceptive pills',
      'A contraceptive method that failed',
      'After a sexual assault',
    ],
    symptoms: [
      [null, 'Needing to prevent pregnancy after unprotected sex'],
      [null, 'Contraception failure (split condom, missed pills)'],
      [null, 'The sooner it is used, the better it works'],
    ],
    tests: [
      [null, 'A brief assessment of timing and health'],
      ['blood-tests/beta-hcg-pregnancy', 'Pregnancy test later if a period is late'],
      [null, 'STI testing after unprotected sex'],
    ],
    treatment: [
      'The emergency contraceptive pill — taken as soon as possible',
      'The copper coil (IUD) — the most effective option, fitted by a clinician',
      'Different pills have different time limits, so seek advice quickly',
      'It does not protect against future sex in the same cycle',
      'Follow up with a pregnancy test if your period is late',
    ],
    whenToSee: [
      'As soon as possible after unprotected sex or contraception failure',
      'If your next period is late, unusually light or missed',
      'To arrange ongoing contraception and STI testing',
    ],
    faqs: [
      { q: 'How soon must I take emergency contraception?', a: 'The sooner the better. The emergency pill works within a few days of unprotected sex depending on the type, and the copper coil can be fitted up to five days after. Ask a pharmacist or clinic quickly.' },
      { q: 'Is the emergency pill the same as an abortion pill?', a: 'No. Emergency contraception works mainly by delaying ovulation to prevent pregnancy starting. It does not end an established pregnancy, and is a different medicine from the abortion pill.' },
    ],
  },
  {
    slug: 'hepatitis-b',
    name: 'Hepatitis B',
    dept: SXH,
    lede: 'Hepatitis B is a virus that infects the liver and can be passed on through sex, blood and from mother to baby. There is a safe, effective vaccine, and treatment for long-term infection.',
    causes: [
      'Unprotected sex with an infected person',
      'Sharing needles or injecting equipment',
      'From mother to baby during birth',
      'Contact with infected blood',
      'Sharing razors or toothbrushes with an infected person',
    ],
    symptoms: [
      [null, 'Often no symptoms, especially in adults'],
      ['symptoms/fatigue', 'Tiredness'],
      [null, 'Yellowing of skin and eyes (jaundice)'],
      ['symptoms/abdominal-pain', 'Tummy pain'],
      ['symptoms/nausea-and-vomiting', 'Nausea and loss of appetite'],
      [null, 'Dark urine and pale stools'],
    ],
    tests: [
      ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B blood test (HBsAg)'],
      ['blood-tests/liver-function-test-lft', 'Liver function tests'],
      [null, 'Further blood tests to check the virus and liver'],
      [null, 'Testing for other STIs and blood-borne viruses'],
    ],
    treatment: [
      'Many adults clear the virus on their own with supportive care',
      'Long-term (chronic) infection is treated with antiviral medicines',
      'Regular monitoring of the liver for chronic infection',
      'Vaccination prevents infection and protects close contacts',
      'Avoiding alcohol and protecting the liver',
    ],
    whenToSee: [
      'Yellowing of the skin or eyes, or dark urine',
      'After possible exposure — ask about vaccination or treatment',
      'For testing if a partner is infected or you are at higher risk',
    ],
    faqs: [
      { q: 'Can hepatitis B be prevented?', a: 'Yes. A safe and effective vaccine prevents hepatitis B, and is offered to babies and people at higher risk. Condoms and not sharing needles also reduce the risk.' },
      { q: 'Is hepatitis B curable?', a: 'Many adults clear the infection naturally. Long-term infection cannot always be cured, but antiviral treatment can control it well and protect the liver from damage.' },
    ],
  },

  // =====================================================================
  // REGENERATIVE MEDICINE  (honest: most are investigational / unproven)
  // =====================================================================
  {
    slug: 'osteoarthritis-prp',
    name: 'Osteoarthritis (PRP & Experimental Options)',
    dept: REG,
    lede: 'Osteoarthritis is joint "wear and tear" causing pain and stiffness. Some clinics offer PRP (platelet-rich plasma) injections, but the evidence is mixed and they are not a proven cure — proven treatments come first.',
    causes: [
      'Age-related wear of joint cartilage',
      'Previous joint injury',
      'Being overweight (extra load on knees and hips)',
      'Repetitive joint stress from work or sport',
      'Family history',
      'Joint alignment problems',
    ],
    symptoms: [
      ['symptoms/joint-pain', 'Joint pain, worse with use'],
      [null, 'Stiffness, especially in the morning or after rest'],
      [null, 'Reduced movement in the joint'],
      [null, 'Grating or clicking with movement'],
      ['symptoms/leg-swelling', 'Swelling around the joint'],
    ],
    tests: [
      [null, 'Clinical examination of the joint'],
      ['x-ray-explained', 'X-ray of the affected joint'],
      ['mri-scan-explained', 'MRI in selected cases'],
      [null, 'Blood tests only to rule out other causes'],
    ],
    treatment: [
      'Proven care first — exercise, weight loss, physiotherapy, pain relief',
      'Joint injections (steroid) for flare-ups',
      'Joint replacement surgery for severe cases',
      'PRP is investigational for osteoarthritis — evidence is mixed and it is not a cure',
      'Be cautious of clinics promising cartilage regrowth or a cure',
    ],
    whenToSee: [
      'Joint pain or stiffness that limits daily activities',
      'A joint that is hot, red and swollen (could be another cause)',
      'Before paying for PRP or stem-cell injections — get independent advice',
    ],
    faqs: [
      { q: 'Do PRP injections cure osteoarthritis?', a: 'No. PRP does not regrow cartilage or cure arthritis. Some studies suggest it may ease pain for a time in certain people, but the evidence is mixed, so it is considered experimental and is not a substitute for proven care.' },
      { q: 'Are private "stem-cell" injections for knees worth it?', a: 'Be cautious. For osteoarthritis these are largely unproven, often expensive and not routinely recommended. Discuss proven options with your doctor before paying for experimental treatments.' },
    ],
  },
  {
    slug: 'tendon-injuries-prp',
    name: 'Tendon Injuries (PRP)',
    dept: REG,
    lede: 'Tendon injuries such as tennis elbow or Achilles problems are common. PRP (platelet-rich plasma) injections are sometimes offered, but the evidence is inconsistent and proven treatments come first.',
    causes: [
      'Overuse or repetitive strain (sport or work)',
      'A sudden increase in activity',
      'Poor technique or unsuitable equipment',
      'Increasing age (tendons weaken over time)',
      'Some medical conditions and medicines',
    ],
    symptoms: [
      ['symptoms/joint-pain', 'Pain around the tendon, worse with use'],
      [null, 'Stiffness, often worse in the morning'],
      [null, 'Tenderness or swelling over the tendon'],
      [null, 'Weakness or difficulty using the affected part'],
      [null, 'A creaking sensation with movement'],
    ],
    tests: [
      [null, 'Clinical examination'],
      [null, 'Ultrasound of the tendon'],
      ['mri-scan-explained', 'MRI in some cases'],
    ],
    treatment: [
      'Proven care first — rest, load management, physiotherapy',
      'Pain relief and activity modification',
      'A structured strengthening (rehab) programme',
      'PRP is investigational for tendon injuries — results are inconsistent',
      'Surgery only for selected, severe or non-healing cases',
    ],
    whenToSee: [
      'Tendon pain that does not improve with rest and rehab',
      'Sudden severe pain or a snapping sensation (possible tear)',
      'Before paying for PRP — ask whether proven options have been tried',
    ],
    faqs: [
      { q: 'Does PRP heal tendon injuries faster?', a: 'The evidence is mixed. Some people report improvement, but good-quality studies have not consistently shown PRP works better than standard rehabilitation, so it is considered experimental.' },
      { q: 'What is the best proven treatment for tendon problems?', a: 'For most tendon injuries, a structured physiotherapy programme focused on gradually loading and strengthening the tendon is the mainstay and has the best evidence.' },
    ],
  },
  {
    slug: 'hair-loss-prp',
    name: 'Hair Loss (PRP)',
    dept: REG,
    lede: 'Hair loss has many causes, the most common being genetic (pattern) baldness. PRP (platelet-rich plasma) injections are marketed for hair loss, but the evidence is limited and results vary.',
    causes: [
      'Genetic (male- or female-pattern) hair loss',
      'Stress, illness or after childbirth (temporary shedding)',
      'Thyroid problems or iron deficiency',
      'Some medicines and treatments',
      'Scalp conditions',
      'Tight hairstyles or hair treatments',
    ],
    symptoms: [
      [null, 'Gradual thinning, often at the crown or hairline'],
      [null, 'A receding hairline (men)'],
      [null, 'Widening parting (women)'],
      [null, 'Sudden shedding after stress or illness'],
      [null, 'Patchy bald spots (may point to another cause)'],
    ],
    tests: [
      [null, 'Examination of the scalp and hair'],
      ['blood-tests/ferritin-iron-studies', 'Iron studies'],
      ['blood-tests/thyroid-function-test-tft', 'Thyroid tests'],
      [null, 'Scalp biopsy in some cases'],
    ],
    treatment: [
      'Treat any underlying cause (iron, thyroid, medicines)',
      'Proven medical treatments for pattern hair loss',
      'Hair transplant surgery for suitable cases',
      'PRP is investigational for hair loss — evidence is limited and effects modest',
      'Be wary of clinics promising dramatic regrowth',
    ],
    whenToSee: [
      'Sudden, patchy or rapid hair loss',
      'Hair loss with scalp pain, redness or scarring',
      'Before paying for PRP — check proven options first',
    ],
    faqs: [
      { q: 'Does PRP regrow hair?', a: 'Evidence is limited. Some small studies suggest modest improvement in thickness for pattern hair loss, but results vary and it is not a guaranteed or standard treatment. Proven medical options should be considered first.' },
      { q: 'Can treating iron or thyroid help my hair?', a: 'Yes, if those are the cause. Low iron and thyroid problems can cause hair thinning, and correcting them can help — which is why a check-up is worthwhile before pursuing costly treatments.' },
    ],
  },
  {
    slug: 'stem-cell-therapy-overview',
    name: 'Stem-Cell Therapy Overview',
    dept: REG,
    lede: 'Stem cells can develop into other cell types, and research into using them to repair tissue is promising. But outside a few proven uses, most stem-cell treatments sold to patients are unproven and experimental.',
    causes: [
      'Proven uses — bone marrow / stem-cell transplants for some blood cancers and disorders',
      'Some skin and eye conditions in specialist settings',
      'Most other uses are experimental and studied in clinical trials',
      'Many private clinics offer unproven treatments for a wide range of conditions',
      'Marketing often runs ahead of the evidence',
    ],
    symptoms: [
      [null, 'Considering stem-cell treatment for a chronic condition'],
      [null, 'Seeing clinics advertise "stem-cell cures"'],
      [null, 'Wanting to know what is proven versus experimental'],
    ],
    tests: [
      [null, 'Specialist assessment of your specific condition'],
      [null, 'Checking whether a treatment is a registered clinical trial'],
      [null, 'Reviewing the evidence with your own doctor'],
    ],
    treatment: [
      'A few stem-cell treatments are proven and used in specialist centres',
      'Most advertised treatments are unproven and not recommended',
      'Genuine research happens through regulated clinical trials',
      'Unproven treatments can be costly and carry real risks',
      'Always discuss with your own doctor before paying for treatment',
    ],
    whenToSee: [
      'Before paying for any stem-cell treatment — get independent medical advice',
      'If a clinic promises a cure or guarantees results — treat this as a red flag',
      'To ask whether a legitimate clinical trial exists for your condition',
    ],
    faqs: [
      { q: 'Are stem-cell treatments a cure for conditions like arthritis or MS?', a: 'For most such conditions, no. Aside from a small number of proven uses (like certain blood disorders), stem-cell treatments are still experimental. Clinics claiming cures should be treated with great caution.' },
      { q: 'How can I tell a genuine treatment from a scam?', a: 'Genuine research runs as regulated clinical trials, is usually free to join, and does not promise guaranteed results. Be wary of clinics that charge large fees, treat many different conditions and make bold claims.' },
    ],
  },
  {
    slug: 'cartilage-repair-experimental',
    name: 'Cartilage Repair (Experimental)',
    dept: REG,
    lede: 'Damaged joint cartilage does not heal well on its own. Several repair techniques exist and some are established, but many cell-based and regenerative approaches are still experimental.',
    causes: [
      'Sports or accident injuries to the joint',
      'Wear and tear (leading to osteoarthritis)',
      'Repeated joint stress',
      'Previous joint injury or surgery',
      'Joint alignment problems',
    ],
    symptoms: [
      ['symptoms/joint-pain', 'Joint pain, especially with movement'],
      [null, 'Swelling after activity'],
      [null, 'Catching, locking or giving way of the joint'],
      [null, 'Reduced range of movement'],
      [null, 'Stiffness'],
    ],
    tests: [
      [null, 'Clinical examination'],
      ['mri-scan-explained', 'MRI to assess cartilage'],
      ['x-ray-explained', 'X-ray to assess the joint'],
      [null, 'Arthroscopy (keyhole look inside the joint)'],
    ],
    treatment: [
      'Physiotherapy and activity changes for many cases',
      'Some surgical repair techniques are established for small defects',
      'Cell-based cartilage repair is used in selected specialist cases',
      'Many regenerative and stem-cell approaches remain experimental',
      'Joint replacement for advanced joint damage',
    ],
    whenToSee: [
      'Persistent joint pain, swelling or locking',
      'A joint that gives way or catches',
      'Before choosing experimental repair — get a specialist opinion',
    ],
    faqs: [
      { q: 'Can cartilage grow back?', a: 'Cartilage has a very limited ability to heal itself. Some surgical techniques can repair small areas, but there is no proven way to fully regrow cartilage across a worn joint — despite what some clinics claim.' },
      { q: 'Are regenerative cartilage treatments proven?', a: 'A few cell-based repairs are used in selected specialist cases, but many advertised regenerative treatments are still experimental. A specialist can advise what is appropriate and evidence-based for you.' },
    ],
  },
  {
    slug: 'wound-healing-growth-factors',
    name: 'Wound Healing & Growth Factors',
    dept: REG,
    lede: 'Most wounds heal on their own, but some — such as diabetic or pressure ulcers — are slow to heal. Growth-factor and regenerative dressings can help selected wounds, alongside proven wound care.',
    causes: [
      'Diabetes (poor circulation and nerve damage)',
      'Poor blood supply to the legs',
      'Pressure sores from limited movement',
      'Infection in the wound',
      'Some medicines and poor nutrition',
      'Smoking (slows healing)',
    ],
    symptoms: [
      [null, 'A wound that does not heal over weeks'],
      [null, 'Increasing redness, swelling or discharge'],
      ['symptoms/skin-rash', 'Surrounding skin changes'],
      ['symptoms/fever', 'Fever (suggests infection)'],
      [null, 'Increasing pain or a bad smell from the wound'],
    ],
    tests: [
      [null, 'Wound examination and measurement'],
      [null, 'Swab if infection is suspected'],
      ['blood-tests/hba1c', 'Blood sugar / HbA1c in diabetes'],
      [null, 'Circulation tests for leg wounds'],
    ],
    treatment: [
      'Proven wound care first — cleaning, dressings, pressure relief',
      'Treating the underlying cause (diabetes, circulation, infection)',
      'Good nutrition and stopping smoking to aid healing',
      'Growth-factor and regenerative dressings can help selected wounds',
      'Specialist wound clinics for complex or non-healing wounds',
    ],
    whenToSee: [
      'A wound that is not healing after a couple of weeks',
      'Spreading redness, swelling, discharge or fever',
      'Any wound in someone with diabetes or poor circulation',
    ],
    faqs: [
      { q: 'Why is my wound not healing?', a: 'Slow healing often has an underlying cause — such as diabetes, poor circulation, pressure or infection. Finding and treating that cause is usually more important than any single dressing.' },
      { q: 'Do growth-factor treatments really help?', a: 'For certain hard-to-heal wounds, some regenerative dressings and growth-factor products can help as part of good wound care. They are not a cure-all, and standard wound care and treating the cause come first.' },
    ],
  },

  // =====================================================================
  // RADIOLOGY & IMAGING  (imaging/procedure explainers, same object shape)
  // =====================================================================
  {
    slug: 'chest-x-ray',
    name: 'Chest X-ray',
    dept: RAD,
    lede: 'A chest X-ray is a quick, painless scan that uses a small dose of radiation to take a picture of the lungs, heart and chest wall. It is one of the most common imaging tests.',
    causes: [
      'To check for chest infections such as pneumonia',
      'To investigate a cough, breathlessness or chest pain',
      'To look at the heart size and outline',
      'To check for fluid or air around the lungs',
      'To look for lung problems or masses',
      'To check the position of tubes or devices',
    ],
    symptoms: [
      ['symptoms/cough', 'A persistent cough'],
      ['symptoms/shortness-of-breath', 'Breathlessness'],
      ['symptoms/chest-pain', 'Chest pain'],
      ['symptoms/fever', 'Fever with chest symptoms'],
    ],
    tests: [
      ['x-ray-explained', 'How X-rays work'],
      [null, 'CT scan of the chest for more detail'],
      [null, 'Chest ultrasound for fluid'],
    ],
    treatment: [
      'It is quick and painless — you stand against a plate and hold your breath',
      'You may be asked to remove clothing and jewellery from the chest',
      'It shows the lungs, heart outline, ribs and major airways',
      'The radiation dose is very low',
      'Tell staff if you are or might be pregnant',
    ],
    whenToSee: [
      'When you have a persistent cough, breathlessness or chest pain',
      'To investigate a suspected chest infection',
      'When your doctor wants to check your heart or lungs',
    ],
    faqs: [
      { q: 'Is a chest X-ray safe?', a: 'Yes. It uses a very small dose of radiation — roughly what you would get from a few days of normal background radiation. The benefit of the information usually far outweighs this tiny risk.' },
      { q: 'Do I need to prepare for a chest X-ray?', a: 'No special preparation is needed. You will be asked to remove clothing and jewellery from the chest area and to hold your breath briefly while the picture is taken.' },
    ],
  },
  {
    slug: 'abdominal-ultrasound',
    name: 'Abdominal Ultrasound',
    dept: RAD,
    lede: 'An abdominal ultrasound uses sound waves — not radiation — to make live images of organs like the liver, gallbladder, kidneys and pancreas. It is safe, painless and widely used.',
    causes: [
      'To investigate tummy pain',
      'To look at the liver, gallbladder and bile ducts (e.g. gallstones)',
      'To check the kidneys and bladder',
      'To assess the pancreas and spleen',
      'To look for fluid or masses in the abdomen',
      'To guide procedures such as biopsies',
    ],
    symptoms: [
      ['symptoms/abdominal-pain', 'Tummy pain'],
      [null, 'Yellowing of the skin (jaundice)'],
      ['symptoms/bloating', 'Bloating'],
      ['symptoms/blood-in-urine', 'Blood in urine (for kidney checks)'],
    ],
    tests: [
      [null, 'CT scan for more detailed views'],
      ['mri-scan-explained', 'MRI in selected cases'],
      ['blood-tests/liver-function-test-lft', 'Liver function tests alongside'],
    ],
    treatment: [
      'You may be asked not to eat for a few hours beforehand',
      'A gel is put on the skin and a probe is moved over the tummy',
      'It is painless and uses no radiation',
      'It shows organs, gallstones, cysts and fluid',
      'You can usually eat and go straight afterwards',
    ],
    whenToSee: [
      'When you have unexplained tummy pain or bloating',
      'To check for gallstones or liver, kidney or pancreas problems',
      'When blood tests suggest a liver or kidney issue',
    ],
    faqs: [
      { q: 'Do I need to fast before an abdominal ultrasound?', a: 'Often yes — you may be asked not to eat for several hours, especially to see the gallbladder clearly. Your appointment letter will tell you what to do.' },
      { q: 'Does an ultrasound use radiation?', a: 'No. Ultrasound uses harmless sound waves rather than radiation, which is why it is safe and can be used in pregnancy.' },
    ],
  },
  {
    slug: 'ct-scan',
    name: 'CT Scan',
    dept: RAD,
    lede: 'A CT (computed tomography) scan uses X-rays and a computer to build detailed cross-section images of the body. It is fast and very useful for many conditions, using more radiation than a plain X-ray.',
    causes: [
      'To look at the brain after injury or stroke symptoms',
      'To investigate the chest, tummy or pelvis in detail',
      'To find or stage cancers',
      'To assess injuries after an accident',
      'To look for blood clots or bleeding',
      'To guide biopsies and other procedures',
    ],
    symptoms: [
      ['symptoms/abdominal-pain', 'Unexplained tummy pain'],
      ['symptoms/headache', 'Severe or sudden headache'],
      ['symptoms/chest-pain', 'Chest pain (in some cases)'],
      [null, 'Injury after an accident'],
    ],
    tests: [
      ['x-ray-explained', 'How X-rays work'],
      ['mri-scan-explained', 'MRI (no radiation, different strengths)'],
      [null, 'Ultrasound as an alternative in some cases'],
    ],
    treatment: [
      'You lie still on a table that moves through a ring-shaped scanner',
      'It is quick, often just a few minutes',
      'A contrast dye may be given by injection to show detail',
      'It uses more radiation than a plain X-ray, but is carefully justified',
      'Tell staff if you are or might be pregnant, or have kidney problems or allergies',
    ],
    whenToSee: [
      'When your doctor needs detailed images of an organ or injury',
      'To investigate or stage a suspected cancer',
      'In an emergency, such as suspected stroke or serious injury',
    ],
    faqs: [
      { q: 'Is a CT scan dangerous because of radiation?', a: 'A CT uses more radiation than a plain X-ray, but the dose is kept as low as possible and is only used when the benefit outweighs the small risk. Your doctor weighs this before requesting one.' },
      { q: 'What is the contrast dye for?', a: 'Contrast dye highlights blood vessels and certain tissues, making problems easier to see. It is generally safe, but tell staff about any allergies or kidney problems beforehand.' },
    ],
  },
  {
    slug: 'mri-scan',
    name: 'MRI Scan',
    dept: RAD,
    lede: 'An MRI (magnetic resonance imaging) scan uses strong magnets and radio waves — not radiation — to make very detailed images, especially of soft tissues like the brain, spine, joints and organs.',
    causes: [
      'To look at the brain and spinal cord in detail',
      'To assess joints, ligaments and soft tissues',
      'To investigate the liver, pelvis and other organs',
      'To find or stage some cancers',
      'To look at blood vessels',
      'When detailed soft-tissue images are needed without radiation',
    ],
    symptoms: [
      ['symptoms/back-pain', 'Persistent back pain with nerve symptoms'],
      ['symptoms/numbness-and-tingling', 'Numbness or tingling'],
      ['symptoms/joint-pain', 'Joint problems'],
      ['symptoms/headache', 'Persistent headaches (in some cases)'],
    ],
    tests: [
      ['mri-scan-explained', 'How MRI works'],
      [null, 'CT scan as an alternative in some cases'],
      [null, 'Ultrasound for some soft-tissue questions'],
    ],
    treatment: [
      'You lie still inside a tunnel-shaped scanner',
      'It is painless but noisy, and can take 20–60 minutes',
      'It uses no radiation',
      'A contrast dye may be given to show more detail',
      'Tell staff about any metal implants, a pacemaker, or if you might be pregnant',
    ],
    whenToSee: [
      'When detailed images of the brain, spine or joints are needed',
      'To investigate nerve symptoms or persistent joint problems',
      'When your specialist requests it for diagnosis or staging',
    ],
    faqs: [
      { q: 'Is an MRI safe?', a: 'Yes. MRI uses magnets and radio waves, not radiation. The main precautions are around metal — tell staff about any implants, a pacemaker or metal fragments, as the magnet is very strong.' },
      { q: 'Will I feel claustrophobic in the scanner?', a: 'Some people do, as the scanner is a narrow tunnel and can be noisy. Tell the team beforehand — they can offer support, and in some cases a more open scanner or medication to help you relax.' },
    ],
  },
  {
    slug: 'mammography',
    name: 'Mammography',
    dept: RAD,
    lede: 'A mammogram is a low-dose X-ray of the breast used to screen for and investigate breast cancer. It can find changes too small to feel, which is why it is central to breast screening.',
    causes: [
      'Routine breast cancer screening',
      'To investigate a breast lump or change',
      'To follow up an abnormal finding',
      'To monitor after breast cancer treatment',
      'To assess nipple discharge or breast pain in some cases',
    ],
    symptoms: [
      [null, 'A breast lump or thickening'],
      [null, 'A change in breast size, shape or skin'],
      [null, 'Nipple discharge or a nipple that turns in'],
      [null, 'Often done in women with no symptoms (screening)'],
    ],
    tests: [
      [null, 'Breast ultrasound (often alongside)'],
      ['mri-scan-explained', 'Breast MRI in selected cases'],
      [null, 'Core-needle biopsy if a change is found'],
    ],
    treatment: [
      'Each breast is briefly pressed between two plates for a clear image',
      'It can feel uncomfortable but lasts only seconds',
      'It uses a low dose of radiation',
      'It can detect very small changes before they can be felt',
      'Results may lead to further tests such as ultrasound or biopsy',
    ],
    whenToSee: [
      'When invited for routine breast screening',
      'If you notice a breast lump or change',
      'To follow up an abnormal breast finding',
    ],
    faqs: [
      { q: 'Does a mammogram hurt?', a: 'The breast is pressed firmly between two plates, which can be uncomfortable or briefly painful, but it only lasts a few seconds. Tell the radiographer if you are in pain.' },
      { q: 'Why have a mammogram if I feel fine?', a: 'Screening mammograms can find breast cancer very early, before it can be felt, when treatment is most effective. This is why women in certain age groups are invited even without symptoms.' },
    ],
  },
  {
    slug: 'ultrasound-in-pregnancy',
    name: 'Ultrasound in Pregnancy',
    dept: RAD,
    lede: 'A pregnancy ultrasound uses sound waves — not radiation — to check the baby\'s growth and wellbeing. It is safe for mother and baby and is a routine part of antenatal care.',
    causes: [
      'To confirm pregnancy and estimate the due date',
      'To check the baby\'s growth and development',
      'To check the position of the baby and placenta',
      'To look at the baby\'s heartbeat and movements',
      'To check for twins or more',
      'To investigate bleeding or pain in pregnancy',
    ],
    symptoms: [
      [null, 'Routine antenatal check (no symptoms needed)'],
      ['symptoms/pelvic-pain', 'Tummy or pelvic pain in pregnancy'],
      [null, 'Bleeding in pregnancy'],
      [null, 'Checking growth if there are concerns'],
    ],
    tests: [
      ['blood-tests/beta-hcg-pregnancy', 'Pregnancy blood test (beta-hCG)'],
      [null, 'Routine antenatal blood tests'],
      [null, 'Further scans if needed'],
    ],
    treatment: [
      'A gel is put on the tummy and a probe is moved over it',
      'An early scan may be done internally (transvaginal) for a clearer view',
      'It is painless and uses no radiation',
      'You may be asked to have a full bladder for some scans',
      'It shows the baby\'s size, position, heartbeat and the placenta',
    ],
    whenToSee: [
      'At routine antenatal scan appointments',
      'If you have bleeding or tummy pain in pregnancy',
      'When your midwife or doctor wants to check the baby\'s growth',
    ],
    faqs: [
      { q: 'Is ultrasound safe for my baby?', a: 'Yes. Ultrasound uses sound waves, not radiation, and has been used safely in pregnancy for decades. Scans are done by trained staff only when there is a reason to.' },
      { q: 'Why might I need an internal (transvaginal) scan?', a: 'In early pregnancy, a scan through the vagina gives a clearer picture of the womb and baby than a scan over the tummy. It is safe and only slightly uncomfortable.' },
    ],
  },
  {
    slug: 'bone-x-ray',
    name: 'Bone X-ray',
    dept: RAD,
    lede: 'A bone X-ray is a quick, painless scan using a small dose of radiation to look at bones and joints. It is the usual first test for suspected fractures and many bone or joint problems.',
    causes: [
      'To check for broken bones (fractures)',
      'To assess joint problems such as arthritis',
      'To investigate bone pain or swelling',
      'To check bone healing after an injury',
      'To look for bone infections or growths',
      'To check joint dislocations',
    ],
    symptoms: [
      ['symptoms/joint-pain', 'Joint pain'],
      ['symptoms/back-pain', 'Back pain'],
      [null, 'Pain, swelling or deformity after an injury'],
      [null, 'Reduced movement in a joint'],
    ],
    tests: [
      ['x-ray-explained', 'How X-rays work'],
      [null, 'CT scan for complex fractures'],
      ['mri-scan-explained', 'MRI for soft tissue and detailed bone views'],
    ],
    treatment: [
      'It is quick and painless — the part is positioned against a plate',
      'You may need a few images from different angles',
      'It uses a small dose of radiation',
      'It shows fractures, joint changes and bone alignment',
      'Tell staff if you are or might be pregnant',
    ],
    whenToSee: [
      'After an injury with pain, swelling or deformity',
      'For ongoing joint or bone pain your doctor wants to investigate',
      'To check how a fracture is healing',
    ],
    faqs: [
      { q: 'Can an X-ray always show a fracture?', a: 'Most fractures show up on X-ray, but some small or hairline breaks can be hard to see at first. If pain continues, a repeat X-ray or a scan like CT or MRI may be needed.' },
      { q: 'Is a bone X-ray safe?', a: 'Yes. It uses a small dose of radiation, and the benefit of diagnosing a bone or joint problem far outweighs the very small risk. Tell staff if you might be pregnant.' },
    ],
  },
  {
    slug: 'pet-scan',
    name: 'PET Scan',
    dept: RAD,
    lede: 'A PET (positron emission tomography) scan uses a small amount of radioactive tracer to show how active tissues are. It is often combined with CT and is especially useful in cancer care.',
    causes: [
      'To find or stage cancers',
      'To check how well cancer treatment is working',
      'To look for cancer spread in the body',
      'To assess some heart and brain conditions',
      'To help tell active disease from scar tissue',
      'To guide biopsy or treatment planning',
    ],
    symptoms: [
      [null, 'Usually done to investigate a known or suspected cancer'],
      ['symptoms/unexplained-weight-loss', 'Unexplained weight loss (as part of cancer work-up)'],
      ['symptoms/swollen-lymph-nodes', 'Swollen glands under investigation'],
    ],
    tests: [
      [null, 'CT scan (often combined as PET-CT)'],
      ['mri-scan-explained', 'MRI for certain areas'],
      [null, 'Biopsy to confirm findings'],
    ],
    treatment: [
      'A small amount of radioactive tracer is injected first',
      'You rest quietly for about an hour while it spreads',
      'The scan itself is painless and takes around 30 minutes',
      'You may be asked not to eat beforehand and to avoid strenuous activity',
      'The radiation leaves the body within hours — you may be asked to avoid close contact with pregnant women and young children briefly',
    ],
    whenToSee: [
      'When your specialist needs to stage a cancer or check treatment',
      'To look for whether a cancer has spread',
      'As part of planning cancer treatment',
    ],
    faqs: [
      { q: 'Is the radioactive tracer in a PET scan harmful?', a: 'The amount used is small and leaves your body within hours. As a precaution you may be asked to keep your distance from pregnant women and young children for a short time afterwards.' },
      { q: 'Why combine PET with CT?', a: 'A PET scan shows how active tissue is, while CT shows detailed anatomy. Combining them (PET-CT) pinpoints exactly where active disease is, which is very useful in cancer care.' },
    ],
  },
];
