-- MediMind — Supabase schema (run once in the NEW project's SQL Editor).
--
-- Security model (same as StemCells): the browser uses the public anon key,
-- restricted to INSERT-only by RLS, so no data can be read from the client. The
-- signed-in admin (authenticated role) can SELECT to power the admin dashboard.
--
-- After running this: Authentication → Providers → enable Google; set the Site URL
-- to https://medicalandroid.com and add the redirect URLs (see DEPLOY.md).

-- ============================================================ tables ==========
create table if not exists public.signups (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text,
  email      text,
  consent    boolean
);

create table if not exists public.chat_logs (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  language       text,
  question       text,
  answer         text,
  had_attachment boolean
);

create table if not exists public.page_views (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  page         text,
  path         text,
  country      text,
  duration_sec integer,
  session_id   text
);

-- ============================================================ RLS =============
alter table public.signups    enable row level security;
alter table public.chat_logs  enable row level security;
alter table public.page_views enable row level security;

-- anon (the public site) may INSERT only
do $$
begin
  perform 1;
  -- signups
  drop policy if exists "anon insert signups" on public.signups;
  create policy "anon insert signups" on public.signups for insert to anon with check (true);
  -- chat_logs
  drop policy if exists "anon insert chat_logs" on public.chat_logs;
  create policy "anon insert chat_logs" on public.chat_logs for insert to anon with check (true);
  -- page_views
  drop policy if exists "anon insert page_views" on public.page_views;
  create policy "anon insert page_views" on public.page_views for insert to anon with check (true);
end $$;

-- ONLY the admin account may SELECT (for the dashboard). The policy checks the
-- signed-in user's email from the JWT, so an ordinary signed-up user gets ZERO
-- rows back even if they call the API directly — not just hidden in the UI.
-- Change the email here if the admin account ever changes.
-- NOTE: the email is inlined as a literal in each policy. A PL/pgSQL variable
-- (do $$ ... $$) cannot be referenced inside a create-policy USING expression —
-- Postgres parses it there as a column name. If the admin account changes,
-- update the literal in all three policies below.
grant select on public.signups, public.chat_logs, public.page_views to authenticated;

drop policy if exists "auth read signups" on public.signups;
create policy "auth read signups" on public.signups for select to authenticated
  using ((auth.jwt() ->> 'email') = 'dr.sanjayanbu@gmail.com');

drop policy if exists "auth read chat_logs" on public.chat_logs;
create policy "auth read chat_logs" on public.chat_logs for select to authenticated
  using ((auth.jwt() ->> 'email') = 'dr.sanjayanbu@gmail.com');

drop policy if exists "auth read page_views" on public.page_views;
create policy "auth read page_views" on public.page_views for select to authenticated
  using ((auth.jwt() ->> 'email') = 'dr.sanjayanbu@gmail.com');

-- make sure anon keeps its INSERT grant
grant insert on public.signups, public.chat_logs, public.page_views to anon;
