// Success-Rate Optimizer — the Simulator's final step.
//
// Cell/gene therapies stall on one number: SUCCESS RATE (illustratively 5-65%,
// driven by therapy type, cell source, and the patient's epigenetic age). This
// module builds an *illustrative* success-rate model and then searches
// combinations of the EXISTING catalogue (product x cell source x delivery route
// x protocol) to formulate a novel therapy that maximises the modelled score.
//
// IMPORTANT (honesty): every number here is a deterministic ILLUSTRATIVE MODEL
// ESTIMATE — NOT a measured or clinical success rate. It reuses only catalogue
// items already presented on the protocol page. Nothing is generated by an LLM
// in this Phase-1 build; the console animation in SimRun is a choreographed
// reveal of these deterministic steps.

import { CARS } from '../api/staticData';
import type { DiseaseEntry } from './catalog';

// ---- option dimensions (illustrative success contributions) ----------------

// Cell source: the biggest lever. Autologous (patient's own) = highest success
// but needs culture time; allogeneic (donor / off-the-shelf) = faster but a bit
// lower; exosome (cell-free) = low immunogenicity; iPSC = potent but slow + more
// screening. successMod is added to the base; weeks is added culture/prep time.
export interface CellSourceDef { key: string; label: string; successMod: number; weeks: number; note: string; }
export const CELL_SOURCES: CellSourceDef[] = [
  { key: 'autologous', label: 'Autologous', successMod: 0.15, weeks: 3, note: "patient's own cells — lowest rejection, needs culture time" },
  { key: 'ipsc',       label: 'iPSC (autologous-derived)', successMod: 0.11, weeks: 6, note: 'potent & patient-matched — longest prep + tumour screening' },
  { key: 'exosome',    label: 'Exosome (cell-free)', successMod: 0.07, weeks: 1, note: 'acellular — low immunogenicity, mild potency' },
  { key: 'allogeneic', label: 'Allogeneic', successMod: -0.03, weeks: 0, note: 'donor / off-the-shelf — fastest, mild rejection risk' },
];

// Protocol enhancers — small, stackable priming steps that raise the modelled
// success (reflecting real preconditioning strategies). One is chosen per run.
export interface ProtocolDef { key: string; label: string; successMod: number; note: string; }
export const PROTOCOLS: ProtocolDef[] = [
  { key: 'standard',   label: 'Standard expansion', successMod: 0.00, note: 'baseline culture & delivery' },
  { key: 'hypoxic',    label: 'Hypoxic preconditioning', successMod: 0.06, note: 'primes cells for the low-oxygen injury site' },
  { key: 'primed',     label: 'Cytokine-primed (IFN-γ/TNF-α)', successMod: 0.08, note: 'licenses MSCs for stronger immunomodulation' },
  { key: '3d',         label: '3D spheroid aggregation', successMod: 0.05, note: 'improves survival & paracrine potency' },
];

// HLA-matching options (only applied to allogeneic grafts).
export interface HlaDef { key: string; label: string; matched: boolean; }
export const HLA_OPTIONS: HlaDef[] = [
  { key: 'matched', label: 'HLA-matched donor', matched: true },
  { key: 'mismatched', label: 'HLA-mismatched', matched: false },
];

// Base success by category (illustrative), keyed off the therapy's body_type.
const CATEGORY_BASE: Record<string, number> = {
  MSC: 0.46, HSC: 0.42, iPSC: 0.40, Exosome: 0.44, NSC: 0.38, 'T-cell': 0.40,
};
const REPROG_BASE = 0.30; // OSK reprogramming is harder / higher-risk

// Preferred delivery route per tissue (matched route scores higher). Mirrors the
// catalog PRESET routes; alternatives are penalised.
const PREFERRED_ROUTE: Record<string, string> = {
  systemic: 'IV infusion', immune: 'Ex-vivo then IV', cns: 'Intrathecal / systemic',
  joint: 'Intra-articular', liver: 'IV infusion', lung: 'Inhaled / IV', heart: 'Intracoronary',
  skin: 'Local injection', pancreas: 'IV / intra-ductal', gut: 'Local / IV', bone: 'Local implant',
  kidney: 'IV infusion', retina: 'Intravitreal injection', muscle: 'IV infusion',
};

// ---- the illustrative success model ----------------------------------------

export interface SuccessInputs {
  category: string;       // body_type (MSC/iPSC/Exosome/…) or 'reprogramming'
  cellSource: string;     // CellSourceDef.key
  route: string;          // chosen delivery route
  protocol: string;       // ProtocolDef.key
  tissueKey: string;      // for route-match
  dnamAge: number;        // epigenetic age drives recovery
  coverage: number;       // 0..1 CpG coverage → confidence factor
  isReprog: boolean;
  hlaMatched?: boolean;   // only meaningful for allogeneic (donor matching)
}

// Age-DEPENDENT cell-source potency (illustrative):
// a patient's own (autologous) cells are potent when young but SENESCENT with
// age, so for older patients a young-donor ALLOGENEIC graft outperforms them by
// ~10-20%. iPSC (reprogrammed to a youthful state) and exosomes are less
// age-sensitive. `old` ramps 0 at age 35 → 1 at age 65.
export function sourceMod(key: string, dnamAge: number): number {
  const old = Math.max(0, Math.min(1, (dnamAge - 35) / 30));
  switch (key) {
    case 'autologous': return 0.15 - 0.22 * old;  // +0.15 young → -0.07 old (own cells age)
    case 'allogeneic': return -0.03 + 0.20 * old; // -0.03 young → +0.17 old (young donor wins)
    case 'ipsc':       return 0.11 - 0.04 * old;  // reprogrammed → stays potent
    case 'exosome':    return 0.07 - 0.02 * old;  // cell-free → mildly age-sensitive
    default:           return 0;
  }
}
// HLA-matching lever — only allogeneic grafts: a matched donor raises success &
// cuts rejection/GvHD; a mismatched one carries a small penalty. N/A otherwise.
export function hlaMod(cellSource: string, hlaMatched?: boolean): number {
  if (cellSource !== 'allogeneic') return 0;
  return hlaMatched ? 0.10 : -0.03;
}

// Gradual age ramp: no penalty below 35; linear to 50; steeper past 50.
// (Young patients recover fast; success falls as biological age rises.)
export function agePenalty(dnamAge: number): number {
  const a = Math.max(0, dnamAge);
  if (a <= 35) return 0;
  const midDrop = Math.min(a, 50) - 35;   // 35→50 : -0.008/yr
  const oldDrop = Math.max(0, a - 50);    // 50+   : -0.014/yr (steeper)
  return midDrop * 0.008 + oldDrop * 0.014;
}

const clamp = (x: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, x));

// A single named contribution to the success model, in PERCENTAGE POINTS (signed).
export interface SuccessTerm { key: string; label: string; points: number; note?: string; }
export interface SuccessBreakdown { terms: SuccessTerm[]; raw: number; covFactor: number; final: number; }

// The success model, decomposed into named terms so the UI can show a transparent
// waterfall (base → cell source → HLA → protocol → route → age → coverage). The
// terms sum (in percentage points) to `final * 100` before clamping, so what the
// user sees adds up. `computeSuccess` below is just `.final`, so the optimiser's
// search behaviour is unchanged.
export function computeSuccessBreakdown(inp: SuccessInputs): SuccessBreakdown {
  const base = inp.isReprog ? REPROG_BASE : (CATEGORY_BASE[inp.category] ?? 0.42);
  const proto = PROTOCOLS.find((p) => p.key === inp.protocol) ?? PROTOCOLS[0];
  const matched = PREFERRED_ROUTE[inp.tissueKey] === inp.route;
  const routeMatch = matched ? 0.08 : -0.05;
  const src = sourceMod(inp.cellSource, inp.dnamAge);   // age-dependent cell-source potency
  const hla = hlaMod(inp.cellSource, inp.hlaMatched);   // HLA-matching (allogeneic only)
  const ageP = agePenalty(inp.dnamAge);
  const raw = base + src + hla + proto.successMod + routeMatch - ageP;
  const covFactor = 0.7 + 0.3 * clamp(inp.coverage, 0, 1); // low coverage → less confidence
  const final = clamp(raw * covFactor, 0.05, 0.90);

  const isAllo = inp.cellSource === 'allogeneic';
  const srcLabel = (CELL_SOURCES.find((s) => s.key === inp.cellSource) ?? CELL_SOURCES[3]).label;
  const terms: SuccessTerm[] = [
    { key: 'base', label: inp.isReprog ? 'Base — OSK reprogramming' : `Base — ${inp.category} therapy`, points: base * 100 },
    { key: 'source', label: `Cell source — ${srcLabel} (age-adjusted)`, points: src * 100 },
  ];
  if (isAllo) {
    terms.push({ key: 'hla', label: inp.hlaMatched ? 'HLA-matched donor' : 'HLA-mismatched', points: hla * 100 });
  }
  terms.push({ key: 'protocol', label: `Protocol — ${proto.label}`, points: proto.successMod * 100 });
  terms.push({ key: 'route', label: `Delivery route ${matched ? '(tissue-matched)' : '(off-target)'}`, points: routeMatch * 100 });
  if (ageP > 0) {
    terms.push({ key: 'age', label: 'Epigenetic-age penalty', points: -ageP * 100 });
  }
  const covPts = raw * (covFactor - 1) * 100; // negative when coverage < 100%
  if (Math.abs(covPts) >= 0.5) {
    terms.push({ key: 'coverage', label: `CpG coverage confidence (${Math.round(inp.coverage * 100)}%)`, points: covPts });
  }
  return { terms, raw, covFactor, final };
}

// Returns a modelled success rate in 0..1 (clamped 0.05–0.90 — never 100%).
export function computeSuccess(inp: SuccessInputs): number {
  return computeSuccessBreakdown(inp).final;
}

export function prepWeeks(cellSource: string): number {
  return (CELL_SOURCES.find((s) => s.key === cellSource) ?? CELL_SOURCES[3]).weeks;
}

// ---- formulation + optimisation --------------------------------------------

export interface Formulation {
  product: string; category: string;
  cellSource: string; cellSourceLabel: string;
  route: string; protocol: string; protocolLabel: string;
  hla: string;            // 'HLA-matched donor' | 'HLA-mismatched' | 'n/a (patient-derived)'
  hlaMatched?: boolean;   // set only for allogeneic
  success: number;        // 0..1
  weeks: number;          // prep/culture time
  notes: string[];
}

// icon = key the UI maps to an inline SVG infographic drawn per step.
export type StepIcon = 'dna' | 'scan' | 'cells' | 'route' | 'flask' | 'search' | 'optimize' | 'assemble';
export interface ConsoleStep { label: string; detail?: string; icon: StepIcon; }

export interface Optimization {
  baseline: Formulation;
  best: Formulation;
  liftPts: number;          // percentage-point gain (best - baseline)
  candidates: number;       // formulations evaluated
  steps: ConsoleStep[];     // choreographed console stream
  options: { cellSources: CellSourceDef[]; routes: string[]; protocols: ProtocolDef[]; hla: HlaDef[] };
  headline: string;
  tradeoff: string;
  disclaimer: string;
  ctx: OptimizeCtx;         // kept so the UI's custom dropdowns can live-recompute
}

export interface OptimizeCtx {
  disease: DiseaseEntry;
  category: string;         // body_type of the selected therapy (fallback 'MSC')
  dnamAge: number;
  coverage: number;
  isReprog: boolean;
  baselineCellSource?: string; // the catalogue's current cell source (fuel_type)
  baselineRoute?: string;
}

// candidate routes = preferred route for the tissue + a couple of real routes
// seen in the catalogue, so the optimiser explores plausible alternatives.
function candidateRoutes(tissueKey: string, currentRoute: string): string[] {
  const pref = PREFERRED_ROUTE[tissueKey];
  const fromCatalogue = Array.from(new Set(CARS.map((c) => c.transmission).filter(Boolean))) as string[];
  const set = new Set<string>([pref, currentRoute, ...fromCatalogue].filter(Boolean));
  return Array.from(set);
}

// Pick a real catalogue product to name the formulation, matching department →
// category → any, so the "novel therapy" reuses an existing catalogue item.
function pickProduct(disease: DiseaseEntry, category: string): string {
  const byDept = CARS.filter((c) => c.make === disease.department);
  const byCat = byDept.filter((c) => c.body_type === category);
  const pool = byCat.length ? byCat : byDept.length ? byDept : CARS;
  return (pool[0]?.model as string) || disease.disease;
}

function mkFormulation(ctx: OptimizeCtx, cellSource: string, route: string, protocol: string, hlaMatched?: boolean): Formulation {
  const src = CELL_SOURCES.find((s) => s.key === cellSource) ?? CELL_SOURCES[3];
  const proto = PROTOCOLS.find((p) => p.key === protocol) ?? PROTOCOLS[0];
  const isAllo = cellSource === 'allogeneic';
  const success = computeSuccess({
    category: ctx.category, cellSource, route, protocol,
    tissueKey: ctx.disease.tissue_key, dnamAge: ctx.dnamAge, coverage: ctx.coverage, isReprog: ctx.isReprog,
    hlaMatched: isAllo ? hlaMatched : undefined,
  });
  const hla = isAllo ? (hlaMatched ? 'HLA-matched donor' : 'HLA-mismatched') : 'n/a (patient-derived)';
  const notes = [src.note, proto.note];
  if (isAllo && hlaMatched) notes.push('HLA-matched donor — lower rejection / GvHD risk');
  return {
    product: pickProduct(ctx.disease, ctx.category),
    category: ctx.isReprog ? 'OSK reprogramming' : ctx.category,
    cellSource, cellSourceLabel: src.label,
    route, protocol, protocolLabel: proto.label,
    hla, hlaMatched: isAllo ? !!hlaMatched : undefined,
    success, weeks: src.weeks,
    notes: notes.filter(Boolean),
  };
}

// Re-score a single formulation (used by the dropdown "custom" mode in SimRun).
export function scoreFormulation(ctx: OptimizeCtx, cellSource: string, route: string, protocol: string, hlaMatched?: boolean): Formulation {
  return mkFormulation(ctx, cellSource, route, protocol, hlaMatched);
}

const pct = (x: number) => Math.round(x * 100);

// Search product x cellSource x route x protocol; return the best formulation,
// the baseline, the lift, and a choreographed console script for the UI.
export function buildOptimization(ctx: OptimizeCtx): Optimization {
  const routes = candidateRoutes(ctx.disease.tissue_key, ctx.baselineRoute || ctx.disease.route);
  const baseSource = ctx.baselineCellSource && CELL_SOURCES.some((s) => s.key === ctx.baselineCellSource)
    ? ctx.baselineCellSource : 'allogeneic';
  // baseline = current selection, allogeneic assumed HLA-mismatched (worst case)
  const baseline = mkFormulation(ctx, baseSource, ctx.baselineRoute || ctx.disease.route, 'standard', baseSource === 'allogeneic' ? false : undefined);

  let best = baseline; let candidates = 0;
  for (const s of CELL_SOURCES) {
    const hlaOpts: (boolean | undefined)[] = s.key === 'allogeneic' ? [true, false] : [undefined];
    for (const r of routes) {
      for (const p of PROTOCOLS) {
        for (const h of hlaOpts) {
          candidates += 1;
          const f = mkFormulation(ctx, s.key, r, p.key, h);
          if (f.success > best.success) best = f;
        }
      }
    }
  }

  const liftPts = pct(best.success) - pct(baseline.success);
  const prefRoute = PREFERRED_ROUTE[ctx.disease.tissue_key] || ctx.disease.route;

  const steps: ConsoleStep[] = [
    { icon: 'dna',      label: 'DECODING EPIGENETIC SIGNATURE', detail: `DNAm age ${ctx.dnamAge.toFixed(1)} yr · coverage ${pct(ctx.coverage)}%` },
    { icon: 'scan',     label: 'INDEXING THERAPY CATALOGUE', detail: `${CARS.length} candidate biologics online` },
    { icon: 'cells',    label: 'PROFILING CELL SOURCES', detail: `age-matched donor potency · ${ctx.dnamAge >= 48 ? 'young-donor allogeneic favoured' : 'autologous favoured'}` },
    { icon: 'route',    label: 'MAPPING DELIVERY VECTOR → TISSUE', detail: `${ctx.disease.tissue} ⟶ ${prefRoute}` },
    { icon: 'flask',    label: 'PRIMING PROTOCOL + HLA MATCHING', detail: 'hypoxic · cytokine-primed · 3D · HLA-matched donor' },
    { icon: 'search',   label: 'RUNNING COMBINATORIAL SYNTHESIS', detail: `${candidates} formulations simulated` },
    { icon: 'optimize', label: 'OPTIMISING SUCCESS MANIFOLD', detail: `baseline ${pct(baseline.success)}% ⟶ peak ${pct(best.success)}%` },
    { icon: 'assemble', label: 'COMPILING NOVEL FORMULATION', detail: `${best.cellSourceLabel} · ${best.protocolLabel}` },
  ];

  const faster = CELL_SOURCES.find((s) => s.key === 'allogeneic')!;
  const tradeoff = best.cellSource === 'allogeneic'
    ? `Off-the-shelf (${faster.label}) — treat in days, at a modelled ${pct(best.success)}% success.`
    : `${best.cellSourceLabel} reaches a modelled ${pct(best.success)}% but adds ~${best.weeks} wk culture/prep; the fastest off-the-shelf option (${faster.label}) trades ~${pct(best.success) - pct(computeSuccess({ category: ctx.category, cellSource: 'allogeneic', route: best.route, protocol: best.protocol, tissueKey: ctx.disease.tissue_key, dnamAge: ctx.dnamAge, coverage: ctx.coverage, isReprog: ctx.isReprog }))} pts of success for speed.`;

  const hlaNote = best.cellSource === 'allogeneic' && best.hlaMatched ? ' with an HLA-matched donor' : '';
  return {
    baseline, best, liftPts, candidates, steps,
    options: { cellSources: CELL_SOURCES, routes, protocols: PROTOCOLS, hla: HLA_OPTIONS },
    headline: `Formulated a novel ${best.cellSourceLabel.toLowerCase()} therapy${hlaNote} at a modelled ${pct(best.success)}% success (+${liftPts} pts vs baseline).`,
    tradeoff,
    disclaimer: 'Illustrative model estimate — not a measured or clinical success rate. Reuses catalogue items only; confirm any real protocol with clinical evidence.',
    ctx,
  };
}

export function summarizeOptimization(o: Optimization): string {
  const hla = o.best.cellSource === 'allogeneic' ? ` · ${o.best.hla}` : '';
  return `Success-rate optimiser — searched ${o.candidates} formulations of existing catalogue items. Best: ${o.best.product} · ${o.best.cellSourceLabel}${hla} · ${o.best.route} · ${o.best.protocolLabel} → modelled ${pct(o.best.success)}% success (+${o.liftPts} pts vs ${pct(o.baseline.success)}% baseline; ~${o.best.weeks} wk prep). ${o.tradeoff} ${o.disclaimer}`;
}
