// AUTO-GENERATED demo dataset (mirrors the server seed) for the static/Pages build.
// Do not edit by hand — run `node scripts/gen-staticdata.mjs` to regenerate.
import type { Car } from '../types';

export const CARS: Car[] = [
  {
    "id": 1,
    "make": "Age Rejuvenation",
    "model": "Persona Reversal Epigenetic Reprogramming",
    "trim": "OSK partial reprogramming (OCT4 · SOX2 · KLF4)",
    "year": 2026,
    "price": 48000,
    "monthly_price": 2000,
    "body_type": "iPSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "AAV-delivered inducible OSK (OCT4, SOX2, KLF4)",
    "power_bhp": 57,
    "zero_to_sixty": 1,
    "top_speed": 7,
    "economy_mpg": 12,
    "rating": 4.3,
    "review_count": 20,
    "accent": "#059669",
    "description": "Built on the Partial Epigenetic Reprogramming platform, Persona Reversal uses controlled, transient expression of three classic Yamanaka transcription factors — OCT4, SOX2 and KLF4 (“OSK”) — to reset the epigenome of aged or damaged cells toward a younger, healthier state, without changing the underlying DNA sequence. Delivered systemically as an intravenous gene therapy, it is being studied for whole-body age reversal — rejuvenating multiple tissues at once rather than a single organ — with the OSK pulse dosed against each person’s DNA-methylation profile to stay inside a safe reprogramming window. First-in-human Phase 1 (investigational).",
    "india_status": "unavailable"
  },
  {
    "id": 2,
    "make": "Age Rejuvenation",
    "model": "Systemic MSC Infusion",
    "trim": "Allogeneic UC-MSC",
    "year": 2022,
    "price": 12000,
    "monthly_price": 500,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 60,
    "zero_to_sixty": 3,
    "top_speed": 2,
    "economy_mpg": 12,
    "rating": 4.2,
    "review_count": 260,
    "accent": "#059669",
    "description": "A wellness-oriented programme of donor MSC infusions promoted for immune modulation and vitality. Investigational — benefits are not established.",
    "india_status": "unavailable"
  },
  {
    "id": 3,
    "make": "Age Rejuvenation",
    "model": "Exosome IV Longevity",
    "trim": "MSC exosome IV",
    "year": 2023,
    "price": 6500,
    "monthly_price": 271,
    "body_type": "Exosome",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "MSC-derived exosomes",
    "power_bhp": 57,
    "zero_to_sixty": 3,
    "top_speed": 1,
    "economy_mpg": 6,
    "rating": 4.1,
    "review_count": 180,
    "accent": "#059669",
    "description": "Intravenous MSC-derived exosomes marketed for anti-ageing and recovery. Investigational; efficacy and safety remain under study.",
    "india_status": "unavailable"
  },
  {
    "id": 4,
    "make": "Age Rejuvenation",
    "model": "NK Cell Immune Boost",
    "trim": "Allogeneic NK cells",
    "year": 2021,
    "price": 9800,
    "monthly_price": 408,
    "body_type": "Immune cell",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "new",
    "seats": 200,
    "doors": 4,
    "engine": "Natural killer (NK) cells",
    "power_bhp": 68,
    "zero_to_sixty": 3,
    "top_speed": 1,
    "economy_mpg": 6,
    "rating": 4.3,
    "review_count": 320,
    "accent": "#059669",
    "description": "Expanded natural-killer cell infusions used to top up immune surveillance, part of a monitored immune-health programme.",
    "india_status": "unavailable"
  },
  {
    "id": 5,
    "make": "Age Rejuvenation",
    "model": "Immune (Thymic) Rejuvenation",
    "trim": "Autologous progenitor",
    "year": 2024,
    "price": 15000,
    "monthly_price": 625,
    "body_type": "Immune cell",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 1,
    "engine": "Thymic epithelial progenitors",
    "power_bhp": 54,
    "zero_to_sixty": 2,
    "top_speed": 7,
    "economy_mpg": 24,
    "rating": 3.9,
    "review_count": 40,
    "accent": "#059669",
    "description": "Experimental approach aiming to restore thymus function and a more youthful immune repertoire. Early research only.",
    "india_status": "unavailable"
  },
  {
    "id": 6,
    "make": "Age Rejuvenation",
    "model": "Senolytic + MSC Program",
    "trim": "MSC + senolytic",
    "year": 2023,
    "price": 11500,
    "monthly_price": 479,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "MSC + senolytic protocol",
    "power_bhp": 59,
    "zero_to_sixty": 4,
    "top_speed": 2,
    "economy_mpg": 12,
    "rating": 4,
    "review_count": 95,
    "accent": "#059669",
    "description": "Combines senescent-cell-clearing agents with MSC infusions to target biological ageing. Investigational research programme.",
    "india_status": "unavailable"
  },
  {
    "id": 7,
    "make": "Diabetes",
    "model": "Type 1 Diabetes",
    "trim": "iPSC islet beta-cells",
    "year": 2024,
    "price": 32000,
    "monthly_price": 1333,
    "body_type": "iPSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "used",
    "seats": 200,
    "doors": 2,
    "engine": "iPSC-derived pancreatic islet (beta) cells",
    "power_bhp": 62,
    "zero_to_sixty": 1,
    "top_speed": 30,
    "economy_mpg": 24,
    "rating": 4.3,
    "review_count": 90,
    "accent": "#0e7490",
    "description": "Replaces the insulin-producing beta cells destroyed in type 1 diabetes with lab-grown pancreatic islet cells, aiming to restore natural glucose control and reduce insulin dependence. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 8,
    "make": "Diabetes",
    "model": "Type 2 Diabetes",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 14000,
    "monthly_price": 583,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 60,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4.2,
    "review_count": 130,
    "accent": "#0e7490",
    "description": "Mesenchymal stem-cell infusions studied to reduce insulin resistance, calm chronic inflammation and support failing beta-cell function in type 2 diabetes. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 9,
    "make": "HIV",
    "model": "CCR5-Δ32 Stem-Cell Transplant",
    "trim": "Allogeneic CCR5-Δ32 HSCT",
    "year": 2019,
    "price": 55000,
    "monthly_price": 2292,
    "body_type": "HSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 240,
    "color": "Inpatient",
    "condition": "new",
    "seats": 300,
    "doors": 4,
    "engine": "CCR5-Δ32 donor haematopoietic stem cells",
    "power_bhp": 78,
    "zero_to_sixty": 1,
    "top_speed": 120,
    "economy_mpg": 36,
    "rating": 4.6,
    "review_count": 60,
    "accent": "#e11d48",
    "description": "An allogeneic stem-cell transplant from a donor with the rare CCR5-Δ32 mutation rebuilds an immune system that HIV cannot infect. This is the approach behind the documented HIV cures — currently reserved for patients who also need a transplant for a blood cancer.",
    "india_status": "unavailable"
  },
  {
    "id": 10,
    "make": "HIV",
    "model": "Cord-Blood CCR5-Δ32 Transplant",
    "trim": "CCR5-Δ32 cord blood",
    "year": 2022,
    "price": 52000,
    "monthly_price": 2167,
    "body_type": "HSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 200,
    "color": "Inpatient",
    "condition": "new",
    "seats": 200,
    "doors": 4,
    "engine": "CCR5-Δ32 cord-blood stem cells",
    "power_bhp": 74,
    "zero_to_sixty": 1,
    "top_speed": 100,
    "economy_mpg": 36,
    "rating": 4.5,
    "review_count": 30,
    "accent": "#e11d48",
    "description": "A cord-blood transplant carrying the CCR5-Δ32 mutation needs a less strict donor match, broadening access to HIV-resistant transplants — the approach that cured the New York patient.",
    "india_status": "unavailable"
  },
  {
    "id": 11,
    "make": "HIV",
    "model": "CCR5 Gene-Edited HSC Therapy",
    "trim": "Autologous CRISPR CCR5-KO",
    "year": 2024,
    "price": 38000,
    "monthly_price": 1583,
    "body_type": "HSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 180,
    "color": "Inpatient",
    "condition": "used",
    "seats": 250,
    "doors": 2,
    "engine": "Patient’s own CRISPR CCR5-edited HSCs",
    "power_bhp": 58,
    "zero_to_sixty": 1,
    "top_speed": 60,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 25,
    "accent": "#e11d48",
    "description": "The patient’s own blood stem cells are gene-edited to remove the CCR5 receptor, so the new T cells they produce resist HIV — an investigational route that aims to avoid the need for a matched donor.",
    "india_status": "unavailable"
  },
  {
    "id": 12,
    "make": "HIV",
    "model": "Anti-HIV Gene Therapy in HSCs",
    "trim": "Lentiviral CCR5/C46",
    "year": 2023,
    "price": 32000,
    "monthly_price": 1333,
    "body_type": "HSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 150,
    "color": "Inpatient",
    "condition": "used",
    "seats": 200,
    "doors": 2,
    "engine": "Lentiviral anti-HIV gene-modified HSCs",
    "power_bhp": 55,
    "zero_to_sixty": 1,
    "top_speed": 45,
    "economy_mpg": 24,
    "rating": 4,
    "review_count": 40,
    "accent": "#e11d48",
    "description": "Blood stem cells are engineered with anti-HIV genes (CCR5 knockdown plus a fusion inhibitor) so they produce immune cells protected from the virus. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 13,
    "make": "HIV",
    "model": "CCR5-Disrupted CD4 T-cell Therapy",
    "trim": "ZFN CCR5-edited CD4 T cells",
    "year": 2022,
    "price": 22000,
    "monthly_price": 917,
    "body_type": "Immune cell",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "CCR5-disrupted autologous CD4 T cells",
    "power_bhp": 52,
    "zero_to_sixty": 2,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4,
    "review_count": 90,
    "accent": "#e11d48",
    "description": "The patient’s CD4 T-helper cells are edited to remove CCR5 and reinfused, expanding a population of HIV-resistant T cells. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 14,
    "make": "Autoimmune",
    "model": "Ankylosing Spondylitis",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 15500,
    "monthly_price": 646,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 66,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4.3,
    "review_count": 160,
    "accent": "#9333ea",
    "description": "Immunomodulatory MSC infusions studied to reduce spinal inflammation, pain and stiffness in ankylosing spondylitis and slow disease progression. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 15,
    "make": "Autoimmune",
    "model": "Rheumatoid Arthritis",
    "trim": "Allogeneic UC-MSC",
    "year": 2022,
    "price": 15000,
    "monthly_price": 625,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 67,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4.4,
    "review_count": 340,
    "accent": "#9333ea",
    "description": "MSC therapy studied to calm the immune attack on the joints in rheumatoid arthritis, reducing pain, swelling and long-term joint damage. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 16,
    "make": "Autoimmune",
    "model": "Systemic Lupus Erythematosus (SLE)",
    "trim": "Allogeneic BM-MSC",
    "year": 2022,
    "price": 18000,
    "monthly_price": 750,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 63,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4.2,
    "review_count": 210,
    "accent": "#9333ea",
    "description": "Immunomodulatory MSC infusions studied to re-balance an overactive immune system in lupus and protect organs such as the kidneys. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 17,
    "make": "Autoimmune",
    "model": "Psoriasis & Psoriatic Arthritis",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 13500,
    "monthly_price": 563,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 65,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.3,
    "review_count": 260,
    "accent": "#9333ea",
    "description": "MSC therapy studied to reduce the skin and joint inflammation of psoriasis and psoriatic arthritis. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 18,
    "make": "Autoimmune",
    "model": "Systemic Sclerosis (Scleroderma)",
    "trim": "Autologous HSCT",
    "year": 2019,
    "price": 42000,
    "monthly_price": 1750,
    "body_type": "HSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 240,
    "color": "Inpatient",
    "condition": "new",
    "seats": 300,
    "doors": 4,
    "engine": "Autologous haematopoietic stem cells",
    "power_bhp": 80,
    "zero_to_sixty": 1,
    "top_speed": 90,
    "economy_mpg": 36,
    "rating": 4.5,
    "review_count": 150,
    "accent": "#9333ea",
    "description": "Autologous stem-cell transplant that resets the immune system in severe, rapidly progressing scleroderma — an established option for carefully selected patients.",
    "india_status": "unavailable"
  },
  {
    "id": 19,
    "make": "Autoimmune",
    "model": "Sjögren’s Syndrome",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 14000,
    "monthly_price": 583,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 61,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4.1,
    "review_count": 90,
    "accent": "#9333ea",
    "description": "MSC infusions studied to ease dryness and systemic inflammation in Sjögren’s syndrome by modulating immune activity. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 20,
    "make": "Autoimmune",
    "model": "Hashimoto’s Thyroiditis",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 12000,
    "monthly_price": 500,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 1,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 58,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4,
    "review_count": 70,
    "accent": "#9333ea",
    "description": "Early-stage MSC therapy studied to reduce autoimmune attack on the thyroid gland in Hashimoto’s thyroiditis. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 21,
    "make": "Autoimmune",
    "model": "Graves’ Disease",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 12500,
    "monthly_price": 521,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 1,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 57,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4,
    "review_count": 60,
    "accent": "#9333ea",
    "description": "Investigational MSC therapy studied to calm the overactive immune response driving Graves’ disease and thyroid eye disease.",
    "india_status": "unavailable"
  },
  {
    "id": 22,
    "make": "Autoimmune",
    "model": "Myasthenia Gravis",
    "trim": "Allogeneic BM-MSC",
    "year": 2022,
    "price": 17000,
    "monthly_price": 708,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 60,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 80,
    "accent": "#9333ea",
    "description": "MSC therapy studied to modulate the antibodies that disrupt nerve-to-muscle signalling in myasthenia gravis, improving muscle strength. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 23,
    "make": "Autoimmune",
    "model": "Autoimmune Hepatitis",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 16000,
    "monthly_price": 667,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 62,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 70,
    "accent": "#9333ea",
    "description": "MSC infusions studied to reduce immune-driven liver inflammation in autoimmune hepatitis and protect liver function. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 24,
    "make": "Autoimmune",
    "model": "Vasculitis",
    "trim": "Allogeneic UC-MSC",
    "year": 2022,
    "price": 16500,
    "monthly_price": 688,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 61,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 90,
    "accent": "#9333ea",
    "description": "Immunomodulatory MSC therapy studied to reduce blood-vessel inflammation in autoimmune vasculitis and lower the risk of organ damage. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 25,
    "make": "Autoimmune",
    "model": "Vitiligo",
    "trim": "MSC-derived exosomes",
    "year": 2023,
    "price": 4500,
    "monthly_price": 188,
    "body_type": "Exosome",
    "fuel_type": "Allogeneic",
    "transmission": "Local injection",
    "mileage": 45,
    "color": "Outpatient",
    "condition": "used",
    "seats": null,
    "doors": 2,
    "engine": "MSC-derived exosomes",
    "power_bhp": 64,
    "zero_to_sixty": 4,
    "top_speed": 7,
    "economy_mpg": 12,
    "rating": 4.2,
    "review_count": 300,
    "accent": "#9333ea",
    "description": "Exosome therapy studied to calm the immune attack on pigment cells and encourage repigmentation of vitiligo patches. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 26,
    "make": "Autoimmune",
    "model": "Alopecia Areata",
    "trim": "Exosome + PRP",
    "year": 2023,
    "price": 4200,
    "monthly_price": 175,
    "body_type": "Exosome",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 45,
    "color": "Outpatient",
    "condition": "used",
    "seats": null,
    "doors": 2,
    "engine": "Exosomes + platelet-rich plasma",
    "power_bhp": 66,
    "zero_to_sixty": 4,
    "top_speed": 3,
    "economy_mpg": 9,
    "rating": 4.3,
    "review_count": 380,
    "accent": "#9333ea",
    "description": "Scalp exosome therapy studied to quieten the immune attack on hair follicles in alopecia areata and support regrowth. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 27,
    "make": "Autoimmune",
    "model": "Polymyositis & Dermatomyositis",
    "trim": "Allogeneic BM-MSC",
    "year": 2022,
    "price": 16000,
    "monthly_price": 667,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 60,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4,
    "review_count": 60,
    "accent": "#9333ea",
    "description": "MSC therapy studied to reduce immune-driven muscle and skin inflammation in polymyositis and dermatomyositis. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 28,
    "make": "Autoimmune",
    "model": "Behçet’s Disease",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 15500,
    "monthly_price": 646,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 61,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 55,
    "accent": "#9333ea",
    "description": "Immunomodulatory MSC therapy studied to reduce recurrent inflammation and ulcers across the body in Behçet’s disease. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 29,
    "make": "Dental",
    "model": "Dental Pulp Regeneration",
    "trim": "Autologous DPSC",
    "year": 2021,
    "price": 6500,
    "monthly_price": 271,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 90,
    "color": "Outpatient day case",
    "condition": "new",
    "seats": 30,
    "doors": 4,
    "engine": "Dental pulp-derived MSC (DPSC)",
    "power_bhp": 84,
    "zero_to_sixty": 1,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.6,
    "review_count": 420,
    "accent": "#0891b2",
    "description": "Regenerative endodontics that uses a patient’s own dental pulp stem cells to revitalise a damaged tooth, restoring living pulp tissue rather than removing it.",
    "india_status": "unavailable"
  },
  {
    "id": 30,
    "make": "Dental",
    "model": "Periodontal Ligament Repair",
    "trim": "Autologous PDLSC",
    "year": 2022,
    "price": 5400,
    "monthly_price": 225,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 60,
    "color": "Outpatient day case",
    "condition": "used",
    "seats": 25,
    "doors": 2,
    "engine": "Periodontal ligament stem cells (PDLSC)",
    "power_bhp": 71,
    "zero_to_sixty": 2,
    "top_speed": 21,
    "economy_mpg": 18,
    "rating": 4.3,
    "review_count": 130,
    "accent": "#0891b2",
    "description": "Investigational cell therapy aiming to rebuild the periodontal ligament and supporting bone lost to gum disease. Currently offered within clinical-trial settings only.",
    "india_status": "unavailable"
  },
  {
    "id": 31,
    "make": "Dental",
    "model": "Alveolar Bone Regeneration",
    "trim": "BM-MSC + scaffold",
    "year": 2020,
    "price": 8900,
    "monthly_price": 371,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Surgical implant",
    "mileage": 120,
    "color": "Day-case surgery",
    "condition": "new",
    "seats": 50,
    "doors": 4,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 80,
    "zero_to_sixty": 1,
    "top_speed": 42,
    "economy_mpg": 12,
    "rating": 4.5,
    "review_count": 310,
    "accent": "#0891b2",
    "description": "Rebuilds jaw-bone volume ahead of implants using bone-marrow MSCs seeded onto a resorbable scaffold, improving graft take versus conventional augmentation.",
    "india_status": "unavailable"
  },
  {
    "id": 32,
    "make": "Dental",
    "model": "Whole-Tooth Bioengineering",
    "trim": "iPSC tooth germ",
    "year": 2024,
    "price": 24000,
    "monthly_price": 1000,
    "body_type": "iPSC",
    "fuel_type": "Allogeneic",
    "transmission": "Surgical implant",
    "mileage": 180,
    "color": "Inpatient",
    "condition": "used",
    "seats": 100,
    "doors": 1,
    "engine": "iPSC-derived odontogenic cells",
    "power_bhp": 58,
    "zero_to_sixty": 3,
    "top_speed": 60,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 22,
    "accent": "#0891b2",
    "description": "Early-stage research growing a biological replacement tooth from induced pluripotent stem cells. Pre-clinical / first-in-human research only.",
    "india_status": "unavailable"
  },
  {
    "id": 33,
    "make": "Orthopedics",
    "model": "Knee Osteoarthritis — StemOne® / CiploStem® (Stempeucel®)",
    "trim": "Allogeneic pooled BM-MSC · CDSCO-approved",
    "year": 2023,
    "price": 2200,
    "monthly_price": 92,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intra-articular",
    "mileage": 30,
    "color": "Outpatient day case",
    "condition": "new",
    "seats": 25,
    "doors": 4,
    "engine": "Adult bone-marrow-derived, culture-expanded, pooled allogeneic MSC (Stempeutics, cGMP Bengaluru)",
    "power_bhp": 70,
    "zero_to_sixty": 1,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.5,
    "review_count": 150,
    "accent": "#2563eb",
    "description": "Stempeucel® (Stempeutics) is an off-the-shelf, DCGI/CDSCO-approved (Permission MF-01/2022) allogeneic mesenchymal stromal cell product — adult bone-marrow-derived, culture-expanded and pooled from screened healthy donors (a bone-marrow MSC, not Wharton’s jelly). Indicated for Kellgren–Lawrence Grade II–III knee osteoarthritis in non-obese patients (BMI < 30 kg/m²). Given as a single intra-articular injection of 25 million cells (1 ml CryoStor CS5 + 1 ml PlasmaLyte A → 2 ml) followed by 2 ml sodium hyaluronate through the same needle, preferably under ultrasound guidance, after IV hydrocortisone + pheniramine pre-medication. A Phase 3 double-blind, placebo-controlled trial showed WOMAC & VAS improvement (p<0.0001) sustained to 2 years with MRI-evidenced cartilage preservation. In India the knee-OA product is marketed as StemOne® (Alkem) and CiploStem® (Cipla); the same platform is CDSCO-approved for critical limb ischaemia (Buerger’s / PAD), marketed as Regenacip® (Cipla). Contraindicated in bleeding disorders and hypersensitivity to hyaluronic acid/animal sera/constituents. See the full protocol for the complete prescribing information; confirm the current Cipla label before treatment.",
    "india_status": "approved"
  },
  {
    "id": 34,
    "make": "Orthopedics",
    "model": "Knee Osteoarthritis MSC Therapy",
    "trim": "Autologous BM-MSC",
    "year": 2019,
    "price": 7800,
    "monthly_price": 325,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Intra-articular",
    "mileage": 45,
    "color": "Outpatient day case",
    "condition": "new",
    "seats": 40,
    "doors": 4,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 82,
    "zero_to_sixty": 1,
    "top_speed": 21,
    "economy_mpg": 12,
    "rating": 4.6,
    "review_count": 1240,
    "accent": "#2563eb",
    "description": "A single intra-articular injection of bone-marrow MSCs to reduce pain and inflammation in mild-to-moderate knee osteoarthritis and support cartilage health.",
    "india_status": "unavailable"
  },
  {
    "id": 35,
    "make": "Orthopedics",
    "model": "Cartilage Repair",
    "trim": "Chondrocyte + MSC",
    "year": 2018,
    "price": 12500,
    "monthly_price": 521,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Intra-articular",
    "mileage": 90,
    "color": "Day-case surgery",
    "condition": "new",
    "seats": 60,
    "doors": 4,
    "engine": "Cultured chondrocytes + MSC",
    "power_bhp": 78,
    "zero_to_sixty": 2,
    "top_speed": 42,
    "economy_mpg": 18,
    "rating": 4.5,
    "review_count": 640,
    "accent": "#2563eb",
    "description": "Matrix-assisted autologous cell implantation that resurfaces focal cartilage defects, delaying or avoiding joint replacement in younger patients.",
    "india_status": "unavailable"
  },
  {
    "id": 36,
    "make": "Orthopedics",
    "model": "Non-union Fracture Repair",
    "trim": "BM-MSC + scaffold",
    "year": 2020,
    "price": 9800,
    "monthly_price": 408,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Surgical implant",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "new",
    "seats": 80,
    "doors": 4,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 85,
    "zero_to_sixty": 1,
    "top_speed": 56,
    "economy_mpg": 12,
    "rating": 4.6,
    "review_count": 380,
    "accent": "#2563eb",
    "description": "Delivers concentrated osteogenic stem cells to fractures that have failed to heal, stimulating new bone formation and union.",
    "india_status": "unavailable"
  },
  {
    "id": 37,
    "make": "Orthopedics",
    "model": "Intervertebral Disc Regeneration",
    "trim": "Autologous MSC intradiscal",
    "year": 2022,
    "price": 11200,
    "monthly_price": 467,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 60,
    "color": "Outpatient day case",
    "condition": "used",
    "seats": 45,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 66,
    "zero_to_sixty": 1,
    "top_speed": 28,
    "economy_mpg": 24,
    "rating": 4.2,
    "review_count": 150,
    "accent": "#2563eb",
    "description": "Investigational injection of MSCs into a degenerated spinal disc to restore disc height and reduce chronic low-back pain. Clinical-trial stage.",
    "india_status": "unavailable"
  },
  {
    "id": 38,
    "make": "Orthopedics",
    "model": "Tendon & Ligament PRP-MSC",
    "trim": "PRP + adipose MSC",
    "year": 2019,
    "price": 3500,
    "monthly_price": 146,
    "body_type": "PRP",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 40,
    "color": "Outpatient",
    "condition": "new",
    "seats": 20,
    "doors": 4,
    "engine": "Platelet-rich plasma + adipose MSC",
    "power_bhp": 74,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 6,
    "rating": 4.4,
    "review_count": 890,
    "accent": "#2563eb",
    "description": "Combines platelet-rich plasma with adipose-derived stem cells to accelerate healing of stubborn tendon and ligament injuries such as tennis elbow or Achilles tendinopathy.",
    "india_status": "unavailable"
  },
  {
    "id": 39,
    "make": "Cardiology",
    "model": "Post-MI Cardiac Repair",
    "trim": "Autologous BM-MNC",
    "year": 2021,
    "price": 18500,
    "monthly_price": 771,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Intracoronary",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "used",
    "seats": 100,
    "doors": 3,
    "engine": "Bone marrow mononuclear cells",
    "power_bhp": 64,
    "zero_to_sixty": 1,
    "top_speed": 30,
    "economy_mpg": 12,
    "rating": 4.2,
    "review_count": 210,
    "accent": "#dc2626",
    "description": "Intracoronary delivery of bone-marrow cells after a heart attack, aiming to limit scar formation and preserve pumping function. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 40,
    "make": "Cardiology",
    "model": "Heart Failure MSC Therapy",
    "trim": "Allogeneic MSC",
    "year": 2022,
    "price": 22000,
    "monthly_price": 917,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intramyocardial",
    "mileage": 90,
    "color": "Inpatient",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 61,
    "zero_to_sixty": 2,
    "top_speed": 45,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 140,
    "accent": "#dc2626",
    "description": "Catheter-based injection of donor MSCs into the heart muscle to reduce inflammation and improve function in chronic heart failure. Clinical-trial stage.",
    "india_status": "unavailable"
  },
  {
    "id": 41,
    "make": "Cardiology",
    "model": "Cardiosphere-derived Cell Therapy",
    "trim": "Allogeneic CDC",
    "year": 2023,
    "price": 24500,
    "monthly_price": 1021,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intracoronary",
    "mileage": 100,
    "color": "Inpatient",
    "condition": "used",
    "seats": 75,
    "doors": 2,
    "engine": "Cardiosphere-derived cells",
    "power_bhp": 60,
    "zero_to_sixty": 1,
    "top_speed": 30,
    "economy_mpg": 18,
    "rating": 4,
    "review_count": 60,
    "accent": "#dc2626",
    "description": "Heart-derived progenitor cells studied for their anti-fibrotic, regenerative signalling in cardiomyopathy. Investigational research therapy.",
    "india_status": "unavailable"
  },
  {
    "id": 42,
    "make": "Cardiology",
    "model": "Critical Limb Ischaemia",
    "trim": "Autologous BM-MNC",
    "year": 2020,
    "price": 14500,
    "monthly_price": 604,
    "body_type": "HSC",
    "fuel_type": "Autologous",
    "transmission": "Intramuscular",
    "mileage": 80,
    "color": "Day-case",
    "condition": "new",
    "seats": 90,
    "doors": 4,
    "engine": "Bone marrow mononuclear cells",
    "power_bhp": 70,
    "zero_to_sixty": 1,
    "top_speed": 28,
    "economy_mpg": 12,
    "rating": 4.3,
    "review_count": 260,
    "accent": "#dc2626",
    "description": "Stem-cell injections that promote new blood-vessel growth in poorly perfused limbs, helping avoid amputation in no-option critical limb ischaemia.",
    "india_status": "unavailable"
  },
  {
    "id": 43,
    "make": "Gastroenterology",
    "model": "Crohn’s Perianal Fistula",
    "trim": "Allogeneic adipose MSC",
    "year": 2019,
    "price": 16500,
    "monthly_price": 688,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Local injection",
    "mileage": 60,
    "color": "Day-case surgery",
    "condition": "new",
    "seats": 120,
    "doors": 4,
    "engine": "Adipose-derived MSC",
    "power_bhp": 76,
    "zero_to_sixty": 1,
    "top_speed": 42,
    "economy_mpg": 12,
    "rating": 4.5,
    "review_count": 430,
    "accent": "#d97706",
    "description": "Local injection of donor adipose stem cells to heal complex perianal fistulas in Crohn’s disease — one of the first approved MSC therapies of its kind.",
    "india_status": "unavailable"
  },
  {
    "id": 44,
    "make": "Gastroenterology",
    "model": "Gut GvHD MSC Therapy",
    "trim": "Allogeneic BM-MSC",
    "year": 2018,
    "price": 19500,
    "monthly_price": 813,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Inpatient",
    "condition": "new",
    "seats": 200,
    "doors": 4,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 72,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 12,
    "rating": 4.4,
    "review_count": 320,
    "accent": "#d97706",
    "description": "Intravenous MSCs that calm the immune attack of steroid-refractory graft-versus-host disease affecting the gut, used after bone-marrow transplant.",
    "india_status": "unavailable"
  },
  {
    "id": 45,
    "make": "Gastroenterology",
    "model": "Liver Cirrhosis MSC Therapy",
    "trim": "Allogeneic UC-MSC",
    "year": 2022,
    "price": 17800,
    "monthly_price": 742,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 63,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 110,
    "accent": "#d97706",
    "description": "Investigational MSC infusions aiming to reduce fibrosis and improve liver function in decompensated cirrhosis. Clinical-trial stage.",
    "india_status": "unavailable"
  },
  {
    "id": 46,
    "make": "Gastroenterology",
    "model": "Ulcerative Colitis MSC",
    "trim": "Allogeneic MSC",
    "year": 2023,
    "price": 15500,
    "monthly_price": 646,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 60,
    "zero_to_sixty": 4,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4,
    "review_count": 80,
    "accent": "#d97706",
    "description": "Immunomodulatory MSC therapy under study for inducing remission in moderate-to-severe ulcerative colitis. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 47,
    "make": "Neurology",
    "model": "Multiple Sclerosis aHSCT",
    "trim": "Autologous HSCT",
    "year": 2017,
    "price": 45000,
    "monthly_price": 1875,
    "body_type": "HSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 240,
    "color": "Inpatient",
    "condition": "new",
    "seats": 300,
    "doors": 4,
    "engine": "Autologous haematopoietic stem cells",
    "power_bhp": 83,
    "zero_to_sixty": 1,
    "top_speed": 90,
    "economy_mpg": 36,
    "rating": 4.7,
    "review_count": 540,
    "accent": "#7c3aed",
    "description": "Autologous haematopoietic stem-cell transplant that “reboots” the immune system, halting disease activity in aggressive relapsing multiple sclerosis.",
    "india_status": "unavailable"
  },
  {
    "id": 48,
    "make": "Neurology",
    "model": "Spinal Cord Injury NSC",
    "trim": "Allogeneic NSC",
    "year": 2023,
    "price": 28000,
    "monthly_price": 1167,
    "body_type": "iPSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intrathecal",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "used",
    "seats": 40,
    "doors": 2,
    "engine": "Neural stem cells",
    "power_bhp": 57,
    "zero_to_sixty": 2,
    "top_speed": 60,
    "economy_mpg": 24,
    "rating": 4.1,
    "review_count": 70,
    "accent": "#7c3aed",
    "description": "Neural stem cells delivered into the spinal fluid to support remyelination and recovery after spinal cord injury. Early clinical research.",
    "india_status": "unavailable"
  },
  {
    "id": 49,
    "make": "Neurology",
    "model": "Stroke Recovery MSC",
    "trim": "Allogeneic MSC",
    "year": 2022,
    "price": 21000,
    "monthly_price": 875,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 62,
    "zero_to_sixty": 1,
    "top_speed": 30,
    "economy_mpg": 12,
    "rating": 4.2,
    "review_count": 160,
    "accent": "#7c3aed",
    "description": "Investigational MSC infusion in the sub-acute phase after ischaemic stroke, studied to enhance neurological recovery and reduce disability.",
    "india_status": "unavailable"
  },
  {
    "id": 50,
    "make": "Neurology",
    "model": "Parkinson’s iPSC Dopaminergic",
    "trim": "Allogeneic iPSC-DA",
    "year": 2024,
    "price": 38000,
    "monthly_price": 1583,
    "body_type": "iPSC",
    "fuel_type": "Allogeneic",
    "transmission": "Surgical implant",
    "mileage": 180,
    "color": "Inpatient",
    "condition": "used",
    "seats": 5,
    "doors": 1,
    "engine": "iPSC-derived dopaminergic neurons",
    "power_bhp": 55,
    "zero_to_sixty": 1,
    "top_speed": 90,
    "economy_mpg": 36,
    "rating": 4,
    "review_count": 30,
    "accent": "#7c3aed",
    "description": "Lab-grown dopamine neurons transplanted into the brain to replace those lost in Parkinson’s disease. First-in-human research stage.",
    "india_status": "unavailable"
  },
  {
    "id": 51,
    "make": "Neurology",
    "model": "ALS / MND MSC Therapy",
    "trim": "Autologous MSC-NTF",
    "year": 2023,
    "price": 26000,
    "monthly_price": 1083,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Intrathecal",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 2,
    "engine": "MSC-neurotrophic factor cells",
    "power_bhp": 54,
    "zero_to_sixty": 3,
    "top_speed": 21,
    "economy_mpg": 18,
    "rating": 3.9,
    "review_count": 90,
    "accent": "#7c3aed",
    "description": "MSCs engineered to secrete neurotrophic factors, delivered intrathecally to slow motor-neuron loss in ALS. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 52,
    "make": "Neurology",
    "model": "Muscular Dystrophy",
    "trim": "Myogenic progenitor / gene-corrected cells",
    "year": 2024,
    "price": 28000,
    "monthly_price": 1167,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 120,
    "color": "Day-case",
    "condition": "used",
    "seats": 200,
    "doors": 1,
    "engine": "MSC / satellite-cell-derived myogenic progenitors",
    "power_bhp": 44,
    "zero_to_sixty": 6,
    "top_speed": 3,
    "economy_mpg": 24,
    "rating": 3.8,
    "review_count": 26,
    "accent": "#7c3aed",
    "description": "A regenerative programme for Duchenne and limb-girdle muscular dystrophies — the inherited loss of muscle-protecting proteins that drives progressive weakness. Systemically infused myogenic progenitor cells (and, in research, gene-corrected autologous cells restoring dystrophin) aim to replenish the muscle stem-cell pool, deliver functional protein, and slow fibre loss, alongside AAV micro-dystrophin gene therapy. Delivered as a monitored infusion with muscle strength and function tracked as read-outs. Investigational — trials are ongoing and benefit is not established.",
    "india_status": "unavailable"
  },
  {
    "id": 53,
    "make": "Neurology",
    "model": "FSHD (Facioscapulohumeral Dystrophy)",
    "trim": "DUX4 epigenetic silencing",
    "year": 2026,
    "price": 44000,
    "monthly_price": 1833,
    "body_type": "iPSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "Epigenetic editor (D4Z4 re-methylation / DUX4 silencing)",
    "power_bhp": 52,
    "zero_to_sixty": 2,
    "top_speed": 7,
    "economy_mpg": 12,
    "rating": 4,
    "review_count": 14,
    "accent": "#7c3aed",
    "description": "Unlike Duchenne, facioscapulohumeral dystrophy is fundamentally an EPIGENETIC disease: loss of methylation at the D4Z4 macrosatellite repeat de-represses the normally-silent DUX4 gene, whose toxic protein kills muscle. That makes it uniquely suited to the epigenetic-reprogramming platform — rather than correcting a gene, the therapy restores the missing methylation / re-silences DUX4 (epigenetic editing, CRISPRi, or Persona Reversal-style epigenetic reprogramming) to switch the toxic gene back off, without altering the DNA sequence. Delivered systemically to muscle. First-in-class research concept — investigational, benefit not established.",
    "india_status": "unavailable"
  },
  {
    "id": 54,
    "make": "Pulmonology",
    "model": "COPD MSC Therapy",
    "trim": "Allogeneic MSC",
    "year": 2022,
    "price": 16800,
    "monthly_price": 700,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "used",
    "seats": 100,
    "doors": 2,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 61,
    "zero_to_sixty": 3,
    "top_speed": 14,
    "economy_mpg": 18,
    "rating": 4.1,
    "review_count": 130,
    "accent": "#0ea5e9",
    "description": "Anti-inflammatory MSC infusions studied to slow lung decline and improve quality of life in chronic obstructive pulmonary disease. Clinical-trial stage.",
    "india_status": "unavailable"
  },
  {
    "id": 55,
    "make": "Pulmonology",
    "model": "Pulmonary Fibrosis (IPF) MSC",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 18500,
    "monthly_price": 771,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 120,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 58,
    "zero_to_sixty": 2,
    "top_speed": 14,
    "economy_mpg": 24,
    "rating": 4,
    "review_count": 85,
    "accent": "#0ea5e9",
    "description": "Investigational cord-tissue MSC therapy aiming to dampen the scarring process of idiopathic pulmonary fibrosis. Research use only.",
    "india_status": "unavailable"
  },
  {
    "id": 56,
    "make": "Pulmonology",
    "model": "ARDS MSC Therapy",
    "trim": "Allogeneic MSC",
    "year": 2021,
    "price": 14500,
    "monthly_price": 604,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 30,
    "color": "Inpatient",
    "condition": "used",
    "seats": 150,
    "doors": 3,
    "engine": "Bone marrow-derived MSC",
    "power_bhp": 63,
    "zero_to_sixty": 1,
    "top_speed": 21,
    "economy_mpg": 6,
    "rating": 4.1,
    "review_count": 200,
    "accent": "#0ea5e9",
    "description": "Intravenous MSCs studied for acute respiratory distress syndrome, including viral pneumonia, to reduce lung inflammation and injury. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 57,
    "make": "Pulmonology",
    "model": "Airway Epithelial Regeneration",
    "trim": "Autologous basal cell",
    "year": 2024,
    "price": 20000,
    "monthly_price": 833,
    "body_type": "iPSC",
    "fuel_type": "Autologous",
    "transmission": "Surgical implant",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "used",
    "seats": 40,
    "doors": 1,
    "engine": "Airway basal stem cells",
    "power_bhp": 56,
    "zero_to_sixty": 2,
    "top_speed": 30,
    "economy_mpg": 24,
    "rating": 3.9,
    "review_count": 25,
    "accent": "#0ea5e9",
    "description": "Early research using a patient’s own airway stem cells to regenerate damaged bronchial lining. Pre-clinical / first-in-human.",
    "india_status": "unavailable"
  },
  {
    "id": 58,
    "make": "Cosmetic",
    "model": "Facial Fat Grafting + SVF",
    "trim": "Autologous SVF",
    "year": 2018,
    "price": 6800,
    "monthly_price": 283,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 120,
    "color": "Day-case surgery",
    "condition": "new",
    "seats": 80,
    "doors": 4,
    "engine": "Adipose-derived SVF / MSC",
    "power_bhp": 86,
    "zero_to_sixty": 1,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.6,
    "review_count": 980,
    "accent": "#db2777",
    "description": "Enriches transferred facial fat with the stromal vascular fraction, improving graft survival for natural, long-lasting volume restoration.",
    "india_status": "unavailable"
  },
  {
    "id": 59,
    "make": "Cosmetic",
    "model": "Hair Restoration Exosome",
    "trim": "Exosome + PRP",
    "year": 2021,
    "price": 2900,
    "monthly_price": 121,
    "body_type": "Exosome",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 60,
    "color": "Outpatient",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Exosomes + platelet-rich plasma",
    "power_bhp": 73,
    "zero_to_sixty": 4,
    "top_speed": 3,
    "economy_mpg": 9,
    "rating": 4.4,
    "review_count": 1200,
    "accent": "#db2777",
    "description": "Scalp injections of regenerative exosomes and PRP that stimulate dormant follicles to thicken hair and slow early-stage hair loss.",
    "india_status": "unavailable"
  },
  {
    "id": 60,
    "make": "Cosmetic",
    "model": "Skin Rejuvenation Exosomes",
    "trim": "Exosome microneedling",
    "year": 2022,
    "price": 1800,
    "monthly_price": 75,
    "body_type": "Exosome",
    "fuel_type": "Allogeneic",
    "transmission": "Topical",
    "mileage": 45,
    "color": "Outpatient",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "MSC-derived exosomes",
    "power_bhp": 78,
    "zero_to_sixty": 3,
    "top_speed": 2,
    "economy_mpg": 6,
    "rating": 4.5,
    "review_count": 1500,
    "accent": "#db2777",
    "description": "Exosome serums driven into the skin with microneedling to boost collagen, calm redness and brighten tone with minimal downtime.",
    "india_status": "unavailable"
  },
  {
    "id": 61,
    "make": "Cosmetic",
    "model": "Scar & Wound MSC Therapy",
    "trim": "Autologous MSC",
    "year": 2020,
    "price": 5200,
    "monthly_price": 217,
    "body_type": "MSC",
    "fuel_type": "Autologous",
    "transmission": "Local injection",
    "mileage": 60,
    "color": "Outpatient",
    "condition": "new",
    "seats": 40,
    "doors": 4,
    "engine": "Adipose-derived MSC",
    "power_bhp": 80,
    "zero_to_sixty": 2,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.4,
    "review_count": 540,
    "accent": "#db2777",
    "description": "Targeted stem-cell injections that soften scars and accelerate healing of difficult wounds by remodelling collagen and improving blood supply.",
    "india_status": "unavailable"
  },
  {
    "id": 62,
    "make": "Nephrology",
    "model": "Chronic Kidney Disease (CKD) MSC Therapy",
    "trim": "Allogeneic UC-MSC",
    "year": 2023,
    "price": 14000,
    "monthly_price": 583,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 150,
    "doors": 2,
    "engine": "Umbilical cord-derived MSC",
    "power_bhp": 58,
    "zero_to_sixty": 3,
    "top_speed": 3,
    "economy_mpg": 12,
    "rating": 4.1,
    "review_count": 140,
    "accent": "#0d9488",
    "description": "Intravenous mesenchymal stem-cell infusions studied to slow the decline of kidney function in chronic kidney disease. MSCs release anti-inflammatory and anti-fibrotic signals that aim to protect surviving nephrons, calm interstitial inflammation and reduce scarring (fibrosis) — the process that drives CKD toward dialysis. Delivered as a monitored day-case infusion, usually repeated over several cycles with eGFR and proteinuria tracked as read-outs. Investigational — trials are ongoing and benefit is not established.",
    "india_status": "unavailable"
  },
  {
    "id": 63,
    "make": "Nephrology",
    "model": "Acute Kidney Injury (AKI) MSC Therapy",
    "trim": "Autologous/allogeneic BM-MSC",
    "year": 2024,
    "price": 16000,
    "monthly_price": 667,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Inpatient",
    "condition": "used",
    "seats": 200,
    "doors": 2,
    "engine": "Bone-marrow-derived MSC",
    "power_bhp": 62,
    "zero_to_sixty": 2,
    "top_speed": 2,
    "economy_mpg": 6,
    "rating": 4,
    "review_count": 70,
    "accent": "#0d9488",
    "description": "A regenerative programme for acute kidney injury — the sudden loss of kidney function after sepsis, major surgery, or nephrotoxic drugs. Infused MSCs home to the injured tubules, dampening the inflammatory storm and secreting growth factors that support tubular epithelial repair, with the goal of speeding recovery and preventing progression to chronic kidney disease. Given in the inpatient setting alongside standard supportive care. Investigational.",
    "india_status": "unavailable"
  },
  {
    "id": 64,
    "make": "Nephrology",
    "model": "Diabetic Kidney Disease Exosome Therapy",
    "trim": "MSC-derived exosomes",
    "year": 2024,
    "price": 9000,
    "monthly_price": 375,
    "body_type": "Exosome",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "MSC-derived exosomes",
    "power_bhp": 55,
    "zero_to_sixty": 4,
    "top_speed": 2,
    "economy_mpg": 12,
    "rating": 3.9,
    "review_count": 45,
    "accent": "#0d9488",
    "description": "Cell-free therapy using MSC-derived exosomes — nanoscale vesicles carrying reparative RNA and proteins — for diabetic kidney disease, the leading cause of kidney failure. The exosomes are studied to deliver anti-fibrotic and podocyte-protective cargo to the glomerulus without the risks of whole-cell infusion, aiming to preserve filtration and reduce protein leak. Early-stage research.",
    "india_status": "unavailable"
  },
  {
    "id": 65,
    "make": "Nephrology",
    "model": "Persona Reversal Renal Epigenetic Reprogramming",
    "trim": "OSK partial reprogramming (OCT4 · SOX2 · KLF4)",
    "year": 2026,
    "price": 52000,
    "monthly_price": 2167,
    "body_type": "iPSC",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "Exosome/AAV-delivered inducible OSK (OCT4, SOX2, KLF4)",
    "power_bhp": 54,
    "zero_to_sixty": 1,
    "top_speed": 7,
    "economy_mpg": 12,
    "rating": 4.2,
    "review_count": 12,
    "accent": "#0d9488",
    "description": "A first-in-class research application of the Persona Reversal partial epigenetic reprogramming platform to the kidney. Controlled, transient expression of OCT4, SOX2 and KLF4 (“OSK”) is used to reset the epigenetic age of injured tubular and glomerular cells toward a younger, more regenerative state — reversing fibrosis-associated methylation changes without altering the DNA sequence. Aimed at the aged/fibrotic kidney in chronic kidney disease, and delivered systemically by a kidney-homing carrier (IV exosome or AAV). First-in-human concept (investigational).",
    "india_status": "unavailable"
  },
  {
    "id": 66,
    "make": "Age Rejuvenation",
    "model": "Muse Cell IV Therapy",
    "trim": "Allogeneic Muse cells",
    "year": 2024,
    "price": 18000,
    "monthly_price": 750,
    "body_type": "Muse",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 50,
    "doors": 2,
    "engine": "Bone-marrow / adipose-derived Muse cells",
    "power_bhp": 50,
    "zero_to_sixty": 2,
    "top_speed": 3,
    "economy_mpg": 12,
    "rating": 4,
    "review_count": 45,
    "accent": "#059669",
    "description": "Muse (multilineage-differentiating stress-enduring) cells are a naturally pluripotent, non-tumorigenic subpopulation given intravenously and reported to home to injured tissue. Investigational — studied in trials for stroke, myocardial infarction, ALS and spinal-cord injury; benefits are not established.",
    "india_status": "unavailable"
  },
  {
    "id": 67,
    "make": "Age Rejuvenation",
    "model": "VSEL Regenerative Therapy",
    "trim": "Autologous VSELs",
    "year": 2024,
    "price": 14000,
    "monthly_price": 583,
    "body_type": "VSEL",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 120,
    "color": "Day-case",
    "condition": "used",
    "seats": null,
    "doors": 1,
    "engine": "Very small embryonic-like stem cells (blood-mobilised)",
    "power_bhp": 40,
    "zero_to_sixty": 1,
    "top_speed": 2,
    "economy_mpg": 6,
    "rating": 3.9,
    "review_count": 30,
    "accent": "#059669",
    "description": "Very small embryonic-like stem cells (VSELs) are isolated from the patient’s own mobilised blood and re-administered for cellular rejuvenation. Highly investigational — the existence and clinical value of VSELs remain scientifically debated.",
    "india_status": "unavailable"
  },
  {
    "id": 68,
    "make": "Age Rejuvenation",
    "model": "Peptide Restoration Program",
    "trim": "Signalling peptides",
    "year": 2023,
    "price": 3200,
    "monthly_price": 267,
    "body_type": "Adjunct",
    "fuel_type": "Synthetic",
    "transmission": "Subcutaneous",
    "mileage": 15,
    "color": "Home / clinic",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Compounded signalling peptides (e.g. BPC-157, thymosin-β4)",
    "power_bhp": 55,
    "zero_to_sixty": 12,
    "top_speed": 0,
    "economy_mpg": 3,
    "rating": 4,
    "review_count": 140,
    "accent": "#059669",
    "description": "A supportive programme of signalling peptides for recovery, sleep and tissue repair. Wellness support, not a disease treatment — several peptides are compounded or off-label and not individually approved.",
    "india_status": "unavailable"
  },
  {
    "id": 69,
    "make": "Age Rejuvenation",
    "model": "NAD+ Infusion Therapy",
    "trim": "IV NAD+",
    "year": 2022,
    "price": 2400,
    "monthly_price": 200,
    "body_type": "Adjunct",
    "fuel_type": "Synthetic",
    "transmission": "IV infusion",
    "mileage": 180,
    "color": "Day-case",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Nicotinamide adenine dinucleotide (NAD+)",
    "power_bhp": 50,
    "zero_to_sixty": 6,
    "top_speed": 0,
    "economy_mpg": 3,
    "rating": 4.1,
    "review_count": 210,
    "accent": "#059669",
    "description": "Intravenous NAD+ used to support cellular energy metabolism and recovery. Supportive wellness therapy; long-term anti-ageing benefits are not established.",
    "india_status": "unavailable"
  },
  {
    "id": 70,
    "make": "Age Rejuvenation",
    "model": "Hormone Optimization (BHRT)",
    "trim": "Bioidentical hormone therapy",
    "year": 2021,
    "price": 2800,
    "monthly_price": 120,
    "body_type": "Adjunct",
    "fuel_type": "Bioidentical",
    "transmission": "Pellet / injection",
    "mileage": 20,
    "color": "Clinic",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Bioidentical hormones (testosterone, oestrogen, thyroid)",
    "power_bhp": 65,
    "zero_to_sixty": 4,
    "top_speed": 0,
    "economy_mpg": 6,
    "rating": 4.2,
    "review_count": 300,
    "accent": "#059669",
    "description": "Physician-supervised optimisation of age-related hormone decline via bioidentical hormone replacement. Established endocrine practice when clinically indicated; requires monitoring.",
    "india_status": "unavailable"
  },
  {
    "id": 71,
    "make": "Age Rejuvenation",
    "model": "IV Nutrition (Myers’ Cocktail)",
    "trim": "Micronutrient IV",
    "year": 2020,
    "price": 350,
    "monthly_price": 29,
    "body_type": "Adjunct",
    "fuel_type": "Micronutrient",
    "transmission": "IV infusion",
    "mileage": 45,
    "color": "Day-case",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Vitamin / mineral micronutrient blend",
    "power_bhp": 45,
    "zero_to_sixty": 6,
    "top_speed": 0,
    "economy_mpg": 1,
    "rating": 4,
    "review_count": 420,
    "accent": "#059669",
    "description": "A vitamin-and-mineral IV blend used for hydration, recovery and general wellness. Supportive only — not a treatment for any specific disease.",
    "india_status": "unavailable"
  },
  {
    "id": 72,
    "make": "Cosmetic",
    "model": "PRP Facial Rejuvenation",
    "trim": "Autologous PRP",
    "year": 2019,
    "price": 900,
    "monthly_price": 75,
    "body_type": "PRP",
    "fuel_type": "Autologous",
    "transmission": "Microneedling / injection",
    "mileage": 45,
    "color": "Clinic",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Platelet-rich plasma (own blood)",
    "power_bhp": 62,
    "zero_to_sixty": 3,
    "top_speed": 1,
    "economy_mpg": 3,
    "rating": 4.3,
    "review_count": 260,
    "accent": "#db2777",
    "description": "Platelet-rich plasma from the patient’s own blood, applied with microneedling or injection to improve skin tone and texture. A widely offered aesthetic treatment.",
    "india_status": "unavailable"
  },
  {
    "id": 73,
    "make": "Cosmetic",
    "model": "PRP Hair Restoration",
    "trim": "Autologous PRP",
    "year": 2019,
    "price": 1200,
    "monthly_price": 100,
    "body_type": "PRP",
    "fuel_type": "Autologous",
    "transmission": "Scalp injection",
    "mileage": 40,
    "color": "Clinic",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Platelet-rich plasma (own blood)",
    "power_bhp": 60,
    "zero_to_sixty": 4,
    "top_speed": 1,
    "economy_mpg": 6,
    "rating": 4.2,
    "review_count": 300,
    "accent": "#db2777",
    "description": "Scalp injections of platelet-rich plasma to slow hair loss and support regrowth in androgenetic alopecia. Commonly offered; results vary and maintenance sessions are needed.",
    "india_status": "unavailable"
  },
  {
    "id": 74,
    "make": "Oncology",
    "model": "CAR-T Cell Therapy",
    "trim": "Autologous CD19 CAR-T",
    "year": 2018,
    "price": 380000,
    "monthly_price": 15833,
    "body_type": "Immune cell",
    "fuel_type": "Autologous",
    "transmission": "IV infusion",
    "mileage": 60,
    "color": "Inpatient",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Genetically engineered chimeric antigen receptor T cells",
    "power_bhp": 80,
    "zero_to_sixty": 1,
    "top_speed": 21,
    "economy_mpg": 24,
    "rating": 4.6,
    "review_count": 500,
    "accent": "#9f1239",
    "description": "A patient’s own T cells are genetically engineered to target a cancer antigen (e.g. CD19), expanded and re-infused. FDA/EMA-approved for certain blood cancers (some leukaemias, lymphomas and multiple myeloma) — an established, high-complexity cell therapy delivered in specialist inpatient centres.",
    "india_status": "approved"
  },
  {
    "id": 75,
    "make": "Orthopedics",
    "model": "BioKnee Biologic Reconstruction",
    "trim": "Cartilage paste graft + meniscus + biologics",
    "year": 2020,
    "price": 22000,
    "monthly_price": 917,
    "body_type": "Surgical",
    "fuel_type": "Autologous + allograft",
    "transmission": "Surgical implantation",
    "mileage": 120,
    "color": "Day-surgery",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Articular cartilage paste graft, meniscus allograft, growth factors",
    "power_bhp": 78,
    "zero_to_sixty": 1,
    "top_speed": 90,
    "economy_mpg": 24,
    "rating": 4.5,
    "review_count": 160,
    "accent": "#2563eb",
    "description": "A biologic alternative to knee replacement that rebuilds the arthritic knee — articular cartilage paste grafting, meniscus replacement where needed, and biologic augmentation — to preserve the natural joint. An established surgical programme for select arthritic knees.",
    "india_status": "unavailable"
  },
  {
    "id": 76,
    "make": "Orthopedics",
    "model": "BioACL Biologic Reconstruction",
    "trim": "Scaffold + allograft ACL + biologics",
    "year": 2021,
    "price": 16000,
    "monthly_price": 667,
    "body_type": "Surgical",
    "fuel_type": "Autologous + allograft",
    "transmission": "Surgical implantation",
    "mileage": 100,
    "color": "Day-surgery",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Biologically augmented ACL reconstruction (scaffold + growth factors)",
    "power_bhp": 75,
    "zero_to_sixty": 1,
    "top_speed": 120,
    "economy_mpg": 24,
    "rating": 4.4,
    "review_count": 120,
    "accent": "#2563eb",
    "description": "Anterior cruciate ligament reconstruction augmented with a scaffold and biologics to improve healing and preserve native tissue. An established surgical option for ACL injury.",
    "india_status": "unavailable"
  },
  {
    "id": 77,
    "make": "Orthopedics",
    "model": "Muse Cell Cartilage Repair",
    "trim": "Allogeneic Muse cells",
    "year": 2024,
    "price": 15000,
    "monthly_price": 625,
    "body_type": "Muse",
    "fuel_type": "Allogeneic",
    "transmission": "Intra-articular injection",
    "mileage": 60,
    "color": "Day-case",
    "condition": "used",
    "seats": 30,
    "doors": 2,
    "engine": "Bone-marrow / adipose-derived Muse cells",
    "power_bhp": 55,
    "zero_to_sixty": 1,
    "top_speed": 14,
    "economy_mpg": 12,
    "rating": 4.1,
    "review_count": 40,
    "accent": "#2563eb",
    "description": "Intra-articular Muse (multilineage-differentiating stress-enduring) cells for cartilage and joint-tissue repair. These naturally pluripotent, non-tumorigenic cells are injected into the joint, where they home to damaged cartilage and can differentiate toward chondrocytes. Investigational — studied for chondral injury and knee osteoarthritis; benefits are not yet established.",
    "india_status": "unavailable"
  },
  {
    "id": 78,
    "make": "Oncology",
    "model": "HSCT for Leukaemia & Lymphoma",
    "trim": "Allogeneic / autologous HSC graft",
    "year": 2016,
    "price": 250000,
    "monthly_price": 10417,
    "body_type": "HSC",
    "fuel_type": "Allogeneic",
    "transmission": "IV infusion",
    "mileage": 120,
    "color": "Inpatient",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "CD34+ haematopoietic stem cells (bone marrow / mobilised peripheral blood / cord blood)",
    "power_bhp": 65,
    "zero_to_sixty": 1,
    "top_speed": 90,
    "economy_mpg": 36,
    "rating": 4.7,
    "review_count": 900,
    "accent": "#9f1239",
    "description": "The standard-of-care stem-cell transplant for blood cancers — leukaemia, lymphoma and myeloma. After high-dose chemotherapy/conditioning, healthy blood-forming (haematopoietic) stem cells — from a matched donor (allogeneic) or the patient’s own cells (autologous) — are infused to rebuild the bone marrow and immune system. A well-established, high-complexity therapy delivered in specialist transplant units.",
    "india_status": "approved"
  },
  {
    "id": 79,
    "make": "Neurology",
    "model": "Neural Stem Cells for Alzheimer’s Disease",
    "trim": "Allogeneic neural stem cells",
    "year": 2024,
    "price": 42000,
    "monthly_price": 1750,
    "body_type": "NSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intrathecal",
    "mileage": 90,
    "color": "Day-case",
    "condition": "used",
    "seats": 20,
    "doors": 1,
    "engine": "Allogeneic neural / neural-progenitor stem cells",
    "power_bhp": 40,
    "zero_to_sixty": 3,
    "top_speed": 30,
    "economy_mpg": 18,
    "rating": 3.9,
    "review_count": 25,
    "accent": "#7c3aed",
    "description": "Investigational neural stem-cell therapy for Alzheimer’s disease. Neural stem/progenitor cells are delivered (e.g. intrathecally) to support surviving neurons, modulate neuroinflammation and secrete neurotrophic factors, with the aim of slowing cognitive decline. Early-stage research only — efficacy in Alzheimer’s is not established, and it is offered strictly within clinical-trial settings.",
    "india_status": "unavailable"
  },
  {
    "id": 80,
    "make": "Vascular",
    "model": "Critical Limb Ischaemia — Regenacip® (Stempeucel®)",
    "trim": "Allogeneic pooled BM-MSC · CDSCO-approved",
    "year": 2017,
    "price": 3200,
    "monthly_price": 133,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Intramuscular",
    "mileage": 45,
    "color": "Day case",
    "condition": "new",
    "seats": null,
    "doors": 4,
    "engine": "Adult bone-marrow-derived, culture-expanded, pooled allogeneic MSC (Stempeutics, cGMP Bengaluru)",
    "power_bhp": 65,
    "zero_to_sixty": 2,
    "top_speed": 30,
    "economy_mpg": 12,
    "rating": 4.4,
    "review_count": 200,
    "accent": "#be123c",
    "description": "Stempeucel® — India’s FIRST DCGI/CDSCO commercially-approved cell-therapy product — for critical limb ischaemia (CLI) due to Buerger’s disease and atherosclerotic peripheral arterial disease. Allogeneic pooled bone-marrow MSCs (dose ~2 million cells/kg) given as intramuscular injections into the affected limb to promote new blood-vessel growth, reduce rest pain and improve limb salvage. Marketed in India as Regenacip® (Cipla); Phase IV post-marketing surveillance supports continued safety and efficacy. Use per approved label.",
    "india_status": "approved"
  },
  {
    "id": 81,
    "make": "Diabetes",
    "model": "Diabetic Foot Ulcer — Stempeucel® (Phase III)",
    "trim": "Allogeneic pooled BM-MSC · investigational",
    "year": 2024,
    "price": 3000,
    "monthly_price": 125,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Local injection",
    "mileage": 45,
    "color": "Day case",
    "condition": "used",
    "seats": null,
    "doors": 3,
    "engine": "Adult bone-marrow-derived, pooled allogeneic MSC (Stempeutics)",
    "power_bhp": 55,
    "zero_to_sixty": 2,
    "top_speed": 42,
    "economy_mpg": 12,
    "rating": 4,
    "review_count": 40,
    "accent": "#0e7490",
    "description": "Stempeutics’ allogeneic bone-marrow MSC product being developed for non-healing diabetic foot ulcers. Currently a Phase III (in-progress) investigational product — NOT yet commercially approved; available only within approved clinical-trial settings. Aims to accelerate wound healing through the MSC secretome.",
    "india_status": "unavailable"
  },
  {
    "id": 82,
    "make": "Gastroenterology",
    "model": "Peri-anal Fistula (Crohn’s) — Stempeucel® (Phase I/II)",
    "trim": "Allogeneic pooled BM-MSC · investigational",
    "year": 2024,
    "price": 3500,
    "monthly_price": 146,
    "body_type": "MSC",
    "fuel_type": "Allogeneic",
    "transmission": "Local injection",
    "mileage": 45,
    "color": "Day case",
    "condition": "used",
    "seats": null,
    "doors": 2,
    "engine": "Adult bone-marrow-derived, pooled allogeneic MSC (Stempeutics)",
    "power_bhp": 52,
    "zero_to_sixty": 1,
    "top_speed": 42,
    "economy_mpg": 12,
    "rating": 3.9,
    "review_count": 25,
    "accent": "#d97706",
    "description": "Stempeutics’ allogeneic bone-marrow MSC product being developed for peri-anal fistula due to Crohn’s disease. Currently a Phase I/II (in-progress) investigational product — NOT yet commercially approved; available only within approved clinical-trial settings.",
    "india_status": "unavailable"
  }
];
