// Child-health Q&A cluster for MedDroid. Parent-facing, high-search questions.
// Each page is a full page object (same shape gen-landing's page() consumes),
// with strong red-flag warnings. Educational only, not a diagnosis. Any dosing
// mentioned is a general weight-based reference — confirm with a doctor.

const REL = (arr) => arr;

export const CHILD_QA = [
  {
    slug: 'child-health/child-fever-when-to-worry',
    name: 'Child Fever: When to Worry',
    title: 'Child Fever: When to Worry & What to Do | MedDroid',
    desc: 'Fever in children — what counts as a fever, safe home care, and the red-flag signs that mean you should see a doctor urgently. Educational, not a diagnosis.',
    h1: 'Child fever: when to worry',
    lede: 'Most childhood fevers are caused by viral infections and settle on their own. What matters most is not the exact number on the thermometer but how your child looks and behaves — and knowing the warning signs that need a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s fever',
    featTitle: 'Safe home care for a child’s fever',
    features: [
      'Offer plenty of fluids to prevent dehydration',
      'Dress lightly; keep the room comfortably cool',
      'Paracetamol or ibuprofen for comfort, dosed by weight (not by age alone)',
      'Let them rest; do not force food',
      'Check on them through the night if unwell',
    ],
    warnings: [
      'Any fever in a baby under 3 months — see a doctor urgently',
      'A stiff neck, a rash that does not fade when pressed, or a bulging soft spot',
      'Fast, difficult or grunting breathing, or blue lips',
      'A fit (seizure), unusual drowsiness, or being hard to wake',
      'Fever above 40°C, lasting more than 3 days, or a child who looks very unwell',
    ],
    noteTitle: 'Treat the child, not the number.',
    note: 'How unwell a child is matters more than the exact temperature. MedDroid gives general information, not a diagnosis — seek care for any red-flag sign above.',
    faqs: [
      { q: 'What temperature is a fever in a child?', a: 'Generally 38°C (100.4°F) or above. A mild fever helps fight infection; focus on comfort and hydration, and watch for warning signs.' },
      { q: 'Should I alternate paracetamol and ibuprofen?', a: 'Sometimes doctors advise alternating for a distressed child, but never double-dose and always use weight-based amounts. Ask your doctor before combining.' },
      { q: 'When is a child’s fever an emergency?', a: 'Any fever under 3 months of age, or fever with a stiff neck, non-fading rash, breathing difficulty, a fit, or extreme drowsiness — get emergency care.' },
    ],
    related: REL([['diseases/childhood-fever', 'Childhood fever'], ['diseases/febrile-seizures', 'Febrile seizures'], ['how-to-reduce-fever-at-home', 'How to reduce fever'], ['medicines/paracetamol', 'Paracetamol']]),
  },
  {
    slug: 'child-health/paracetamol-dose-for-children',
    name: 'Paracetamol Dose for Children',
    title: 'Paracetamol Dose for Children (by Weight) | MedDroid',
    desc: 'How paracetamol is dosed for children — by weight, not age — how often, the daily limit, and safety tips. General reference only; confirm with your doctor.',
    h1: 'Paracetamol dose for children',
    lede: 'Children’s paracetamol should be dosed by weight, not age, and measured with the syringe or cup provided. Getting the amount and the concentration right keeps it both effective and safe.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about children’s paracetamol',
    featTitle: 'Key points on children’s paracetamol',
    features: [
      'Usual dose is about 15 mg per kg of body weight per dose',
      'Given every 4–6 hours, up to 4 doses (max ~60 mg/kg) in 24 hours',
      'Dose by weight, not age — and use the measuring device provided',
      'Check the strength (e.g. 120 mg/5 ml vs 250 mg/5 ml syrup) — they differ',
      'Do not combine with other products that also contain paracetamol',
    ],
    warnings: [
      'Never exceed the daily limit — paracetamol overdose can harm the liver',
      'Do not use in babies under 2–3 months without a doctor’s advice',
      'If your child seems very unwell, see a doctor rather than only medicating',
      'Seek help immediately after any accidental overdose, even if the child seems fine',
    ],
    noteTitle: 'General reference — confirm the exact dose.',
    note: 'This is a general guide. The exact dose depends on your child’s weight and the product strength, so always follow the pack instructions or your doctor/pharmacist. MedDroid cannot prescribe.',
    faqs: [
      { q: 'How much paracetamol can I give my child?', a: 'About 15 mg per kg per dose, every 4–6 hours, up to four times a day — measured with the device provided and matched to the syrup strength. Confirm the exact amount with your pharmacist.' },
      { q: 'Can I give paracetamol and ibuprofen together?', a: 'They can sometimes be alternated for a distressed child, but never at the same dose time without advice, and never exceed either drug’s limit. Ask your doctor.' },
      { q: 'What if I gave too much?', a: 'Contact a doctor or poison helpline immediately, even if your child looks well — paracetamol overdose can damage the liver and needs prompt treatment.' },
    ],
    related: REL([['medicines/paracetamol', 'Paracetamol'], ['medicines/ibuprofen', 'Ibuprofen'], ['child-health/child-fever-when-to-worry', 'Child fever: when to worry'], ['how-to-reduce-fever-at-home', 'How to reduce fever']]),
  },
  {
    slug: 'child-health/ibuprofen-for-children',
    name: 'Ibuprofen for Children',
    title: 'Ibuprofen for Children: Dose, Safety & When to Avoid | MedDroid',
    desc: 'Ibuprofen for children — how it is dosed by weight, when to give it with food, and when to avoid it. General reference only; confirm with your doctor.',
    h1: 'Ibuprofen for children',
    lede: 'Ibuprofen relieves pain and fever and reduces inflammation, but it is harder on the stomach and kidneys than paracetamol and is not suitable for every child. Here is how it is used safely.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about children’s ibuprofen',
    featTitle: 'Key points on children’s ibuprofen',
    features: [
      'Usual dose is about 5–10 mg per kg per dose, every 6–8 hours',
      'Always give with or after food to protect the stomach',
      'Dose by weight and match the syrup strength',
      'Not for babies under 3 months',
      'Keep the child well hydrated while using it',
    ],
    warnings: [
      'Avoid in dehydration, chickenpox, or a child who is not drinking (kidney risk)',
      'Avoid with a history of stomach ulcers, asthma flares from NSAIDs, or kidney problems',
      'Tummy pain, black stools or vomiting blood — stop and seek care',
      'A very unwell child needs a doctor, not just medicine',
    ],
    noteTitle: 'General reference — confirm the exact dose.',
    note: 'The exact dose depends on your child’s weight and the product strength — follow the pack or your doctor/pharmacist. Paracetamol is often preferred when a child is dehydrated. MedDroid cannot prescribe.',
    faqs: [
      { q: 'How much ibuprofen for a child?', a: 'Around 5–10 mg per kg per dose every 6–8 hours, with food, measured to the syrup strength. Confirm the exact amount with your pharmacist.' },
      { q: 'When should I avoid ibuprofen in my child?', a: 'Avoid it if they are dehydrated, not drinking, have chickenpox, or have kidney/stomach problems — paracetamol is safer in those cases.' },
      { q: 'Paracetamol or ibuprofen for a child?', a: 'Either can help fever and pain; ibuprofen also reduces inflammation but needs food and caution in dehydration. Ask a pharmacist which suits your child.' },
    ],
    related: REL([['medicines/ibuprofen', 'Ibuprofen'], ['medicines/paracetamol', 'Paracetamol'], ['child-health/paracetamol-dose-for-children', 'Paracetamol dose for children'], ['child-health/child-fever-when-to-worry', 'Child fever']]),
  },
  {
    slug: 'child-health/baby-vomiting-when-to-worry',
    name: 'Baby Vomiting: When to Worry',
    title: 'Baby Vomiting: Causes & When to Worry | MedDroid',
    desc: 'Vomiting in babies and children — common causes, how to keep fluids down, and the warning signs that need a doctor urgently. Educational, not a diagnosis.',
    h1: 'Baby vomiting: when to worry',
    lede: 'Occasional vomiting is common in babies and children, often from a tummy bug or feeding. The main risk is dehydration — and a few warning signs mean you should seek help quickly.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s vomiting',
    featTitle: 'What helps',
    features: [
      'Offer small, frequent sips of fluid or ORS',
      'Keep breastfeeding or feeding in small amounts',
      'Reintroduce normal food gradually once vomiting settles',
      'Watch wet nappies/urine as a sign of hydration',
      'Rest and avoid fatty or sugary foods for a while',
    ],
    warnings: [
      'Green (bile) or blood-stained vomit',
      'Forceful, projectile vomiting in a young baby',
      'Signs of dehydration: few wet nappies, sunken eyes, drowsiness',
      'A swollen, hard or very painful tummy',
      'Vomiting with a high fever, stiff neck, or a bad headache',
    ],
    noteTitle: 'Rehydration comes first.',
    note: 'ORS in small frequent sips is the key treatment. Do not give anti-vomiting medicine to a child without a doctor’s advice. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I stop my baby vomiting?', a: 'Give small, frequent sips of ORS or milk rather than large feeds, and let the stomach rest. Most tummy bugs settle in a day or two — watch for dehydration.' },
      { q: 'When is vomiting an emergency in a child?', a: 'Green or bloody vomit, projectile vomiting in a young baby, a swollen painful tummy, or signs of dehydration or a stiff neck all need urgent care.' },
      { q: 'What is projectile vomiting?', a: 'Forceful vomiting that shoots out, especially in a young baby after feeds, can signal a blockage (like pyloric stenosis) and should be checked promptly.' },
    ],
    related: REL([['diseases/gastroenteritis', 'Gastroenteritis'], ['medicines/ors', 'ORS'], ['diseases/pyloric-stenosis', 'Pyloric stenosis'], ['symptoms/nausea-and-vomiting', 'Nausea & vomiting']]),
  },
  {
    slug: 'child-health/diarrhea-in-children',
    name: 'Diarrhea in Children',
    title: 'Diarrhea in Children: Treatment & When to Worry | MedDroid',
    desc: 'Diarrhoea in children — how to prevent dehydration with ORS and zinc, what to feed, and the warning signs that need a doctor. Educational, not a diagnosis.',
    h1: 'Diarrhea in children',
    lede: 'Most childhood diarrhoea is caused by a viral tummy bug and gets better in a few days. The most important thing is preventing dehydration — with ORS and, in young children, zinc.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s diarrhoea',
    featTitle: 'What helps',
    features: [
      'Give ORS after each loose stool to replace fluids and salts',
      'Zinc supplements for 10–14 days help young children recover (as advised)',
      'Keep breastfeeding and offer normal, bland food',
      'Avoid sugary drinks and fruit juices (they worsen it)',
      'Wash hands well to stop it spreading',
    ],
    warnings: [
      'Signs of dehydration: few wet nappies, sunken eyes, no tears, drowsiness',
      'Blood or mucus in the stool',
      'High fever, or diarrhoea lasting more than a few days',
      'A child too weak to drink or keep fluids down',
      'Severe tummy pain or a swollen belly',
    ],
    noteTitle: 'ORS and zinc are the mainstay.',
    note: 'Do not give anti-diarrhoeal medicines (like loperamide) to young children. ORS, zinc and continued feeding are the safe, proven approach. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the best treatment for diarrhoea in children?', a: 'ORS to prevent dehydration, zinc for young children, continued feeding and good hygiene. Most viral cases settle without antibiotics.' },
      { q: 'Can I give my child anti-diarrhoea medicine?', a: 'No — medicines like loperamide are not recommended for young children. Focus on fluids, ORS and zinc, and see a doctor for warning signs.' },
      { q: 'What should my child eat with diarrhoea?', a: 'Continue normal, bland foods (rice, khichdi, banana, toast, curd) and keep breastfeeding. Avoid sugary and fatty foods for a while.' },
    ],
    related: REL([['diseases/gastroenteritis', 'Gastroenteritis'], ['medicines/ors', 'ORS'], ['medicines/zinc', 'Zinc'], ['how-to-stop-diarrhea', 'How to stop diarrhoea']]),
  },
  {
    slug: 'child-health/is-my-child-dehydrated',
    name: 'Is My Child Dehydrated?',
    title: 'Signs of Dehydration in Children & Babies | MedDroid',
    desc: 'How to tell if a child or baby is dehydrated — early and serious signs, what to do, and when it is an emergency. Educational, not a diagnosis.',
    h1: 'Is my child dehydrated?',
    lede: 'Children lose fluid quickly with vomiting, diarrhoea, fever or heat, and can become dehydrated faster than adults. Knowing the signs — and acting early with ORS — prevents it becoming serious.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dehydration',
    featTitle: 'Signs to check',
    features: [
      'Fewer wet nappies or passing little urine',
      'Dry mouth and lips, crying with few or no tears',
      'Sunken eyes, or a sunken soft spot in a baby',
      'Tiredness, irritability or unusual drowsiness',
      'Thirst and cool, mottled hands and feet (more serious)',
    ],
    warnings: [
      'Very little or no urine for many hours',
      'Drowsiness, floppiness or being hard to wake',
      'Fast breathing or a rapid heartbeat',
      'Cold, blotchy hands and feet',
      'Unable to keep any fluids down',
    ],
    noteTitle: 'Act early with ORS.',
    note: 'Start ORS in small frequent sips at the first signs. Serious dehydration needs urgent medical care, sometimes fluids by drip. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the first signs of dehydration in a child?', a: 'Fewer wet nappies, a dry mouth, fewer tears and increased thirst or tiredness. Start ORS early before it worsens.' },
      { q: 'How do I rehydrate my child at home?', a: 'Give ORS in small, frequent sips, keep breastfeeding, and continue offering fluids. Avoid sugary drinks. Seek care if signs worsen.' },
      { q: 'When is dehydration an emergency?', a: 'Very little urine, drowsiness or floppiness, fast breathing, cold blotchy skin, or inability to drink all need urgent medical care.' },
    ],
    related: REL([['diseases/dehydration', 'Dehydration'], ['medicines/ors', 'ORS'], ['child-health/diarrhea-in-children', 'Diarrhea in children'], ['child-health/baby-vomiting-when-to-worry', 'Baby vomiting']]),
  },
  {
    slug: 'child-health/cough-and-cold-in-children',
    name: 'Cough & Cold in Children',
    title: 'Cough & Cold in Children: Care & When to Worry | MedDroid',
    desc: 'Cough and cold in children — safe home care, why cough syrups are not advised for young kids, and the breathing warning signs that need a doctor. Not a diagnosis.',
    h1: 'Cough and cold in children',
    lede: 'Coughs and colds are very common in childhood — young children can catch several a year. Most are viral and settle with simple care; the key is watching the breathing and avoiding unnecessary medicines.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s cough or cold',
    featTitle: 'Safe home care',
    features: [
      'Plenty of fluids and rest',
      'Saline nose drops and gentle suction for a blocked nose in babies',
      'Warm fluids and honey for cough (only over 1 year of age)',
      'Paracetamol or ibuprofen for discomfort or fever (by weight)',
      'Keep the air smoke-free',
    ],
    warnings: [
      'Fast, difficult or noisy breathing, or the ribs pulling in',
      'Blue lips, grunting, or pauses in breathing',
      'A high fever that will not settle, or a very unwell child',
      'A cough lasting more than 3 weeks, or coughing up blood',
      'A baby under 3 months with a fever',
    ],
    noteTitle: 'Skip cough syrups in young children.',
    note: 'Over-the-counter cough and cold medicines are not recommended for children under about 6 years and can be harmful. Focus on fluids, saline and comfort. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Can I give cough syrup to my child?', a: 'Over-the-counter cough and cold medicines are not advised under about 6 years and offer little benefit. Honey (over age 1), fluids and saline drops are safer.' },
      { q: 'How many colds are normal for a child?', a: 'Young children can have 6–8 or more colds a year, especially at daycare or school — usually nothing to worry about if they recover between them.' },
      { q: 'When should a child’s cough be checked?', a: 'For fast or laboured breathing, blue lips, a high persistent fever, a cough over 3 weeks, or a very unwell child — see a doctor.' },
    ],
    related: REL([['diseases/common-cold-in-children', 'Common cold in children'], ['diseases/bronchiolitis', 'Bronchiolitis'], ['diseases/croup', 'Croup'], ['diseases/childhood-asthma', 'Childhood asthma']]),
  },
  {
    slug: 'child-health/teething-signs-and-remedies',
    name: 'Teething Signs & Remedies',
    title: 'Teething: Signs, Age & How to Soothe a Baby | MedDroid',
    desc: 'Baby teething — when teeth appear, the real signs, how to soothe the discomfort safely, and what teething does NOT cause. Educational, not a diagnosis.',
    h1: 'Teething: signs and how to soothe your baby',
    lede: 'Most babies start teething around 6 months. It can cause dribbling, gum discomfort and irritability — but it does not cause high fever or diarrhoea, so do not blame those on teeth.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about teething',
    featTitle: 'How to soothe teething',
    features: [
      'Let your baby chew on a clean, chilled (not frozen) teething ring',
      'Gently rub the gums with a clean finger',
      'Wipe away drool to prevent a rash around the mouth',
      'Extra cuddles and distraction help',
      'Paracetamol by weight if they are in real discomfort (over the right age)',
    ],
    warnings: [
      'A high fever, diarrhoea or vomiting is NOT from teething — look for another cause',
      'A very unwell, floppy or drowsy baby',
      'Refusing all feeds or signs of dehydration',
      'Avoid amber teething necklaces (choking/strangulation risk)',
    ],
    noteTitle: 'Teething does not cause serious illness.',
    note: 'Blaming a high fever or diarrhoea on teething can delay treating a real infection. If your baby is unwell, look for another cause. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the signs of teething?', a: 'Dribbling, chewing on things, sore red gums, irritability and mild discomfort. Teething does not cause high fever or diarrhoea.' },
      { q: 'When do babies start teething?', a: 'Usually around 6 months, though it ranges from about 3 to 12 months. The bottom front teeth often come first.' },
      { q: 'Are teething gels and necklaces safe?', a: 'Avoid amber teething necklaces (choking/strangulation risk). Some teething gels are not advised for babies — a chilled teething ring is safer. Ask your doctor.' },
    ],
    related: REL([['child-health/child-fever-when-to-worry', 'Child fever: when to worry'], ['medicines/paracetamol', 'Paracetamol'], ['diseases/tooth-decay', 'Tooth decay'], ['child-health/how-to-help-baby-sleep', 'How to help baby sleep']]),
  },
  {
    slug: 'child-health/how-to-help-baby-sleep',
    name: 'How to Help Baby Sleep',
    title: 'How to Help Your Baby Sleep (Safely) | MedDroid',
    desc: 'How to help a baby sleep and settle — safe sleep basics, a simple bedtime routine, and when night waking needs a doctor. Educational, not a diagnosis.',
    h1: 'How to help your baby sleep',
    lede: 'Newborn sleep is broken and unpredictable, and that is normal. A calm routine and safe-sleep habits help everyone rest — and reduce the risk of sudden infant death (SIDS).',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about baby sleep',
    featTitle: 'Safe sleep & settling',
    features: [
      'Always place baby on their BACK to sleep, on a firm flat surface',
      'Keep the cot clear — no pillows, bumpers or loose bedding',
      'A calm, consistent bedtime routine (feed, bath, dim lights)',
      'Daytime feeds and light; keep night feeds quiet and dark',
      'Room-share (not bed-share) for the early months where advised',
    ],
    warnings: [
      'Never let a baby sleep on a sofa, or bed-share if you smoke, drink or are very tired',
      'A baby who is very hard to wake, floppy, or breathing abnormally',
      'Persistent inconsolable crying or poor feeding',
      'Sudden change in a normally settled baby (could signal illness)',
    ],
    noteTitle: 'Safe sleep saves lives.',
    note: 'Back to sleep, a clear firm cot, and no overheating greatly lower the risk of SIDS. MedDroid gives general information, not a diagnosis — see your doctor with any concern.',
    faqs: [
      { q: 'How can I get my baby to sleep through the night?', a: 'Newborns cannot sleep through at first — it develops over months. A consistent routine, distinguishing day from night, and safe-sleep habits help it come sooner.' },
      { q: 'Is it safe to sleep with my baby in my bed?', a: 'Room-sharing is encouraged, but bed-sharing raises SIDS risk, especially if you smoke, drink, take sedating medicine, or the baby was premature. Never sleep with a baby on a sofa.' },
      { q: 'Why does my baby wake so often at night?', a: 'Frequent waking is normal in babies, often for feeds. If waking suddenly increases or your baby seems unwell, check for another cause.' },
    ],
    related: REL([['child-health/colic-in-babies', 'Colic in babies'], ['child-health/teething-signs-and-remedies', 'Teething'], ['child-health/child-development-milestones', 'Development milestones'], ['diseases/insomnia', 'Insomnia']]),
  },
  {
    slug: 'child-health/colic-in-babies',
    name: 'Colic in Babies',
    title: 'Colic in Babies: Signs & How to Soothe | MedDroid',
    desc: 'Baby colic — what it is, the “rule of threes”, how to soothe a colicky baby, and the warning signs that mean it is something else. Educational, not a diagnosis.',
    h1: 'Colic in babies: how to cope',
    lede: 'Colic is intense, hard-to-soothe crying in an otherwise healthy, well-fed baby, often in the late afternoon or evening. It is exhausting but harmless and usually improves by 3–4 months.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about colic',
    featTitle: 'Ways to soothe a colicky baby',
    features: [
      'Hold, rock or carry your baby; try gentle motion',
      'White noise or a calm, dim environment',
      'A warm bath or gentle tummy massage',
      'Check feeding technique and wind (burp) after feeds',
      'Take breaks and share care — it is okay to put baby down safely and step away for a moment',
    ],
    warnings: [
      'Fever, vomiting (especially green), or blood in the stool',
      'Poor feeding, few wet nappies or weight loss',
      'A high-pitched or weak cry, floppiness or drowsiness',
      'Crying that suddenly changes or a swollen, tender tummy',
    ],
    noteTitle: 'Colic is harmless — but rule out other causes.',
    note: 'Colic does not harm your baby, but if there is fever, vomiting, poor feeding or your baby seems unwell, it is not just colic — see a doctor. Never shake a baby. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is colic?', a: 'Intense crying, often defined as more than 3 hours a day, 3 days a week, for 3 weeks, in a healthy baby. It usually eases by 3–4 months.' },
      { q: 'How do I soothe a colicky baby?', a: 'Hold and rock them, try white noise, a warm bath or tummy massage, check feeding and winding, and take breaks with support — caregiver wellbeing matters too.' },
      { q: 'Do colic drops work?', a: 'Evidence is limited. Some parents try simethicone or probiotic drops; ask your doctor. Soothing techniques and time are the mainstay.' },
    ],
    related: REL([['child-health/how-to-help-baby-sleep', 'How to help baby sleep'], ['medicines/simethicone', 'Simethicone'], ['medicines/probiotics', 'Probiotics'], ['child-health/starting-solids-for-babies', 'Starting solids']]),
  },
  {
    slug: 'child-health/constipation-in-children',
    name: 'Constipation in Children',
    title: 'Constipation in Children: Causes & What Helps | MedDroid',
    desc: 'Constipation in children — common causes, diet and toilet habits that help, when laxatives are used, and warning signs. Educational, not a diagnosis.',
    h1: 'Constipation in children',
    lede: 'Constipation is very common in children, often from diet, not drinking enough, or holding on. It is usually easily managed, but it helps to act early before it becomes a stubborn cycle.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s constipation',
    featTitle: 'What helps',
    features: [
      'More fluids (water) through the day',
      'More fibre: fruits, vegetables and wholegrains',
      'A relaxed toilet routine after meals, with feet supported',
      'Physical activity and play',
      'Laxatives (like lactulose or PEG) if advised by a doctor',
    ],
    warnings: [
      'Constipation in a newborn, or no first stool in the first days of life',
      'Blood in the stool, or severe tummy pain',
      'Vomiting (especially green) with a swollen belly',
      'Weight loss, poor growth, or leaking soiling',
    ],
    noteTitle: 'Treat early to break the cycle.',
    note: 'Painful, hard stools make children hold on, which worsens constipation. Diet, routine and, when needed, doctor-advised laxatives help. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What helps constipation in children?', a: 'More water and fibre, a regular relaxed toilet routine, activity, and — if needed — a gentle laxative on medical advice. Act early to avoid a stubborn cycle.' },
      { q: 'Are laxatives safe for children?', a: 'Yes, gentle ones like lactulose or PEG are commonly used under a doctor’s guidance, often for several weeks, and are not habit-forming in the way people fear.' },
      { q: 'When should I worry about my child’s constipation?', a: 'See a doctor for a newborn who is constipated, blood in the stool, severe pain, vomiting with a swollen belly, or poor growth.' },
    ],
    related: REL([['diseases/constipation', 'Constipation'], ['medicines/lactulose', 'Lactulose'], ['medicines/polyethylene-glycol', 'PEG (laxative)'], ['child-health/starting-solids-for-babies', 'Starting solids']]),
  },
  {
    slug: 'child-health/newborn-jaundice-when-to-worry',
    name: 'Newborn Jaundice: When to Worry',
    title: 'Newborn Jaundice: When to Worry & Treatment | MedDroid',
    desc: 'Newborn jaundice — why it happens, when it is normal, when it needs treatment (phototherapy), and the danger signs. Educational, not a diagnosis.',
    h1: 'Newborn jaundice: when to worry',
    lede: 'Yellowing of a newborn’s skin and eyes (jaundice) is very common in the first days of life and usually harmless. But some babies need treatment, and a few warning signs must not be missed.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about newborn jaundice',
    featTitle: 'What to know',
    features: [
      'Common jaundice appears after day 2–3 and fades within 1–2 weeks',
      'Frequent feeding helps clear it',
      'A blood test (bilirubin level) guides whether treatment is needed',
      'Phototherapy (special blue light) is the usual treatment',
      'Most babies recover fully with no lasting effects',
    ],
    warnings: [
      'Jaundice in the first 24 hours of life — urgent',
      'Deep yellow or jaundice reaching the arms, legs or palms',
      'A baby who is very sleepy, feeding poorly, or hard to wake',
      'High-pitched crying, arching, or stiffness',
      'Pale stools and dark urine (possible liver problem)',
    ],
    noteTitle: 'Very high levels need prompt treatment.',
    note: 'Untreated very high bilirubin can rarely harm the brain, so danger signs need urgent care. Most jaundice is mild and resolves. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is newborn jaundice normal?', a: 'Mild jaundice appearing after day 2–3 is very common and usually harmless, fading within a week or two with good feeding.' },
      { q: 'When does newborn jaundice need treatment?', a: 'When a blood bilirubin level is high for the baby’s age, phototherapy is used. Jaundice in the first 24 hours, or a very sleepy or poorly feeding baby, needs urgent review.' },
      { q: 'Does sunlight cure baby jaundice?', a: 'Direct sun is not a safe or reliable treatment and risks sunburn/overheating. Medical phototherapy is the proven treatment when needed.' },
    ],
    related: REL([['diseases/neonatal-jaundice', 'Neonatal jaundice'], ['diseases/jaundice', 'Jaundice'], ['blood-tests/bilirubin', 'Bilirubin test'], ['child-health/child-fever-when-to-worry', 'Child fever']]),
  },
  {
    slug: 'child-health/baby-vaccination-schedule-india',
    name: 'Baby Vaccination Schedule (India)',
    title: 'Baby Vaccination Schedule in India: Age-by-Age | MedDroid',
    desc: 'India baby vaccination schedule — the main vaccines by age, why they matter, what to expect after, and catch-up. Educational; follow your doctor and official schedule.',
    h1: 'Baby vaccination schedule (India)',
    lede: 'Vaccines protect your child from serious, preventable diseases. India’s Universal Immunization Programme and the IAP schedule cover the key ones from birth through childhood — here is the general picture.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about vaccines',
    featTitle: 'General schedule (confirm with your doctor)',
    features: [
      'At birth: BCG, OPV (0 dose), Hepatitis B',
      '6, 10, 14 weeks: DPT/Pentavalent, OPV/IPV, Rotavirus, PCV',
      '9–12 months: Measles-Rubella (MR), Vitamin A, JE (in some areas)',
      '16–24 months: MR 2nd dose, DPT booster, OPV booster',
      '5–6 & 10–16 years: DPT/Td boosters; HPV for girls (recommended)',
    ],
    warnings: [
      'A high fever, a fit, or a severe reaction after a previous vaccine — tell your doctor before the next',
      'Postpone routine vaccines if your child is seriously unwell (a mild cold is usually fine)',
      'Difficulty breathing, swelling or collapse after a vaccine (very rare) — emergency',
    ],
    noteTitle: 'Follow the official/IAP schedule.',
    note: 'Exact vaccines and timing can change and vary by state and private (IAP) schedules. Always follow your doctor and your child’s vaccination card. MedDroid gives general information, not a schedule prescription.',
    faqs: [
      { q: 'What vaccines does a newborn get in India?', a: 'Usually BCG, the birth dose of oral polio (OPV 0), and Hepatitis B at or soon after birth.' },
      { q: 'Is mild fever after vaccination normal?', a: 'Yes — mild fever, fussiness or soreness at the injection site for a day or two is common and expected. Paracetamol by weight can help comfort.' },
      { q: 'What if we missed a vaccine?', a: 'Catch-up is almost always possible — see your doctor, who will restart or continue the schedule rather than begin all over again.' },
    ],
    related: REL([['diseases/childhood-vaccination', 'Childhood vaccination'], ['diseases/measles', 'Measles'], ['diseases/whooping-cough', 'Whooping cough'], ['diseases/rubella', 'Rubella']]),
  },
  {
    slug: 'child-health/normal-baby-weight-by-age',
    name: 'Normal Baby Weight by Age',
    title: 'Normal Baby Weight by Age: A Simple Guide | MedDroid',
    desc: 'Normal baby weight and growth by age — rough guides, why growth charts matter more than a single number, and when to check with a doctor. Not a diagnosis.',
    h1: 'Normal baby weight by age',
    lede: 'Babies grow at different rates, so a healthy weight is a range, not one number. What matters most is a steady curve on the growth chart — not comparing your baby to others.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your baby’s growth',
    featTitle: 'Rough weight guide (varies widely)',
    features: [
      'Birth: around 2.5–4 kg on average',
      'Babies often lose a little weight in the first week, then regain it',
      'Roughly doubles birth weight by ~4–6 months',
      'Roughly triples birth weight by ~1 year',
      'Steady growth along the chart matters more than a single reading',
    ],
    warnings: [
      'Not regaining birth weight by 2–3 weeks',
      'Crossing downward across growth-chart lines (faltering growth)',
      'Very few wet nappies or signs of poor feeding',
      'Sudden weight loss or a persistently very unwell baby',
    ],
    noteTitle: 'The curve matters more than the number.',
    note: 'Doctors track growth on WHO/IAP charts over time. One low or high reading is rarely a problem — a change in the trend is what counts. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How much should my baby weigh?', a: 'It varies a lot. As a rough guide, babies double their birth weight by about 4–6 months and triple it by a year — but a steady growth curve matters more than the exact number.' },
      { q: 'My baby lost weight after birth — is that normal?', a: 'Yes, a small loss in the first week is normal; most babies regain their birth weight by around 2 weeks. Tell your doctor if they do not.' },
      { q: 'When should I worry about my baby’s weight?', a: 'If they are not regaining birth weight, dropping across chart lines, feeding poorly or seem unwell — have them checked.' },
    ],
    related: REL([['child-health/child-development-milestones', 'Development milestones'], ['child-health/starting-solids-for-babies', 'Starting solids'], ['diseases/childhood-obesity', 'Childhood obesity'], ['diseases/malnutrition', 'Malnutrition']]),
  },
  {
    slug: 'child-health/child-development-milestones',
    name: 'Child Development Milestones',
    title: 'Child Development Milestones by Age | MedDroid',
    desc: 'Child development milestones — rough age guides for smiling, sitting, walking and talking, and the “red flags” that mean it is worth checking. Educational, not a diagnosis.',
    h1: 'Child development milestones',
    lede: 'Children reach milestones at their own pace, within broad ranges. Milestones are a guide, not a test — but a few “red flags” are worth discussing with your doctor early, because early help works best.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about milestones',
    featTitle: 'Rough milestone guide',
    features: [
      '~2 months: social smile, follows objects with eyes',
      '~6 months: rolls over, reaches for things, babbles',
      '~9–12 months: sits well, crawls, pulls to stand, says “mama/dada”',
      '~12–18 months: first steps, first words, points at things',
      '~2 years: runs, two-word phrases, follows simple instructions',
    ],
    warnings: [
      'Not smiling by 3 months, or not making eye contact',
      'Not sitting by ~9 months, or not walking by ~18 months',
      'No words by ~16–18 months, or losing skills they once had',
      'Floppy or very stiff limbs, or always using only one hand very early',
    ],
    noteTitle: 'Ranges are wide — but check red flags early.',
    note: 'Milestones vary, and being a little behind is often normal. But losing skills, or clear red flags, deserve an early check — early support makes a big difference. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'When do babies start walking and talking?', a: 'Many walk between about 12–18 months and say first words around 12 months, but the normal range is wide. Focus on steady progress rather than exact dates.' },
      { q: 'What are developmental red flags?', a: 'No social smile by 3 months, not sitting by ~9 months, not walking by ~18 months, no words by ~18 months, or losing previously gained skills — discuss these with your doctor.' },
      { q: 'Should I worry if my child is a little behind?', a: 'Often not — children develop at different speeds. But an early check is wise if there are red flags or you have a nagging worry; early help is very effective.' },
    ],
    related: REL([['child-health/normal-baby-weight-by-age', 'Baby weight by age'], ['diseases/autism-spectrum', 'Autism spectrum'], ['diseases/adhd', 'ADHD'], ['child-health/how-to-help-baby-sleep', 'Baby sleep']]),
  },
  {
    slug: 'child-health/rash-in-babies-and-children',
    name: 'Rash in Babies & Children',
    title: 'Rash in Babies & Children: Common Causes & Warning Signs | MedDroid',
    desc: 'Baby and child rashes — common causes (heat, eczema, viral, nappy rash), simple care, and the one rash that is an emergency. Educational, not a diagnosis.',
    h1: 'Rash in babies and children',
    lede: 'Most childhood rashes are harmless — heat rash, nappy rash, eczema or a passing viral rash. The one you must never miss is a rash that does not fade when pressed, which can signal meningitis.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s rash',
    featTitle: 'Common causes',
    features: [
      'Nappy rash (red skin in the nappy area)',
      'Heat rash (tiny bumps in hot weather)',
      'Eczema (dry, itchy patches)',
      'Viral rashes (with a cold or fever, e.g. hand-foot-mouth, chickenpox)',
      'Hives (raised, itchy welts from an allergy)',
    ],
    warnings: [
      'A rash that does NOT fade when pressed with a glass (do the glass test) — with fever, this is a meningitis emergency',
      'A rash with a high fever, stiff neck, or a very unwell child',
      'Rapid facial/lip swelling or breathing difficulty (severe allergy)',
      'Blistering, raw skin, or a spreading, hot, painful rash',
    ],
    noteTitle: 'Do the glass test.',
    note: 'Press a clear glass firmly over the rash: if the spots do NOT fade, especially with fever, seek emergency care — it can be meningitis/septicaemia. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I know if my child’s rash is serious?', a: 'Do the glass test — a rash that does not fade under pressure, especially with fever, is an emergency. Also worrying: breathing difficulty, swelling, a stiff neck, or a very unwell child.' },
      { q: 'What helps nappy rash?', a: 'Frequent nappy changes, gentle cleaning, letting the skin air, and a barrier cream. See a doctor if it is severe, raw, or not improving (it may be a fungal infection).' },
      { q: 'Is a rash with a viral illness normal?', a: 'Many viral infections cause a mild rash that clears as the child recovers. Watch for the warning signs above and check if you are unsure.' },
    ],
    related: REL([['symptoms/skin-rash', 'Skin rash'], ['diseases/meningitis', 'Meningitis'], ['diseases/hand-foot-mouth-disease', 'Hand, foot & mouth'], ['diseases/chickenpox', 'Chickenpox']]),
  },
  {
    slug: 'child-health/starting-solids-for-babies',
    name: 'Starting Solids for Babies',
    title: 'Starting Solids: When & How to Begin Baby Food | MedDroid',
    desc: 'Starting solids (weaning) — when to begin (~6 months), first foods, foods to avoid, choking safety and allergy introduction. Educational, not a diagnosis.',
    h1: 'Starting solids for babies',
    lede: 'Most babies are ready for solids around 6 months, alongside continued milk. Introducing a variety of foods — including common allergens — early and safely helps set up healthy eating.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about starting solids',
    featTitle: 'How to start',
    features: [
      'Begin around 6 months, when baby can sit and hold their head steady',
      'Start with soft, mashed foods (dal, rice, khichdi, mashed fruit/veg)',
      'Continue breast milk or formula alongside',
      'Introduce one new food at a time; include common allergens early (egg, peanut as smooth paste)',
      'Offer a variety of tastes and textures over time',
    ],
    warnings: [
      'Choking hazards: whole nuts, grapes, hard raw pieces — always cut small and supervise',
      'No added salt or sugar, and no honey before 1 year (botulism risk)',
      'Signs of a food allergy: rash, swelling, vomiting, or breathing trouble — stop and seek care',
      'Never leave a baby alone while eating',
    ],
    noteTitle: 'No honey before age 1; always supervise.',
    note: 'Introduce foods safely, avoid choking hazards and added salt/sugar, and never give honey before 1 year. MedDroid gives general information, not a diagnosis — ask your doctor about allergy introduction if there is a family history.',
    faqs: [
      { q: 'When should I start solids?', a: 'Around 6 months, when your baby can sit with support and hold their head steady, while continuing milk feeds. Starting much earlier is not recommended.' },
      { q: 'What foods should I avoid?', a: 'No honey before 1 year, no added salt or sugar, and avoid choking hazards like whole nuts and grapes. Cut food small and always supervise.' },
      { q: 'Should I delay allergenic foods like egg and peanut?', a: 'No — current advice is to introduce common allergens early (as smooth pastes), which may reduce allergy risk. Ask your doctor if there is a strong family history.' },
    ],
    related: REL([['child-health/normal-baby-weight-by-age', 'Baby weight by age'], ['child-health/constipation-in-children', 'Constipation in children'], ['diseases/food-allergy', 'Food allergy'], ['diseases/iron-deficiency-anaemia', 'Iron-deficiency anaemia']]),
  },
  {
    slug: 'child-health/ear-infection-in-children',
    name: 'Ear Infection in Children',
    title: 'Ear Infection in Children: Signs & Treatment | MedDroid',
    desc: 'Ear infection in children — signs (ear pain, tugging, fever), home care, when antibiotics are needed, and warning signs. Educational, not a diagnosis.',
    h1: 'Ear infection in children',
    lede: 'Middle-ear infections are very common in young children, often after a cold. Many settle on their own with pain relief, and antibiotics are not always needed — but some situations do need a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your child’s ear',
    featTitle: 'Signs & home care',
    features: [
      'Signs: ear pain, tugging at the ear, fever, irritability, poor sleep',
      'A baby may just be unsettled, feed poorly or have a fever after a cold',
      'Pain relief with paracetamol or ibuprofen (by weight) is the mainstay',
      'Most improve within a few days without antibiotics',
      'Keep the ear dry; do not put anything (or oil) into the ear canal',
    ],
    warnings: [
      'Fluid or pus draining from the ear',
      'Swelling, redness or tenderness behind the ear',
      'A stiff neck, severe headache, or a very unwell child',
      'Symptoms in a baby under 6 months, or lasting more than 2–3 days',
      'Hearing concerns after repeated infections',
    ],
    noteTitle: 'Antibiotics are not always needed.',
    note: 'Many ear infections are viral or self-limiting, so pain relief is first-line and antibiotics are used selectively. MedDroid gives general information, not a diagnosis — see a doctor for the warning signs.',
    faqs: [
      { q: 'How do I know if my child has an ear infection?', a: 'Ear pain or tugging, fever, irritability and poor sleep after a cold are common signs. A doctor confirms by looking in the ear.' },
      { q: 'Does my child need antibiotics for an ear infection?', a: 'Often not — many settle with pain relief in a few days. Antibiotics are used for young babies, severe cases, or if it is not improving. A doctor decides.' },
      { q: 'How can I ease my child’s ear pain?', a: 'Weight-based paracetamol or ibuprofen is the main relief. Do not put oil or objects in the ear. See a doctor if there is discharge or it worsens.' },
    ],
    related: REL([['diseases/ear-infection', 'Ear infection'], ['medicines/amoxicillin', 'Amoxicillin'], ['medicines/paracetamol', 'Paracetamol'], ['child-health/cough-and-cold-in-children', 'Cough & cold in children']]),
  },
  {
    slug: 'child-health/bedwetting-in-children',
    name: 'Bedwetting in Children',
    title: 'Bedwetting in Children: Causes & How to Help | MedDroid',
    desc: 'Bedwetting (nocturnal enuresis) in children — why it happens, when it is normal, practical help, and when to see a doctor. Educational, not a diagnosis.',
    h1: 'Bedwetting in children',
    lede: 'Bedwetting is common and rarely a child’s fault — the bladder and night-time signals simply take time to mature. Most children grow out of it, and gentle, blame-free support helps.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about bedwetting',
    featTitle: 'What helps',
    features: [
      'Stay calm and reassuring — never punish or shame',
      'Encourage daytime fluids but reduce drinks close to bedtime',
      'A toilet visit right before bed',
      'Protect the mattress and involve the child in a low-key routine',
      'A bedwetting alarm or medicine (desmopressin) if advised, usually after age 5–7',
    ],
    warnings: [
      'Suddenly starting to wet the bed after being dry for a long time',
      'Daytime wetting, pain or burning when passing urine (possible infection)',
      'Excessive thirst, weight loss or drinking a lot (check for diabetes)',
      'Snoring with poor sleep (possible sleep apnoea)',
    ],
    noteTitle: 'It is common and treatable — not naughtiness.',
    note: 'Bedwetting is usually a developmental delay, not behaviour. Treatment is generally considered from around age 5–7 if it bothers the child. New-onset bedwetting or daytime symptoms deserve a check. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'At what age should bedwetting stop?', a: 'Many children are dry at night by 5, but it is still common later and often runs in families. It is usually only treated if it continues past about 5–7 and bothers the child.' },
      { q: 'How can I help my child stop bedwetting?', a: 'Reassurance, fewer drinks before bed, a pre-bed toilet visit, and — if needed — a bedwetting alarm or medicine on a doctor’s advice. Never punish.' },
      { q: 'When should bedwetting be checked?', a: 'If a previously dry child suddenly starts, or there is daytime wetting, pain passing urine, excessive thirst or weight loss — see a doctor.' },
    ],
    related: REL([['diseases/urinary-tract-infection', 'Urinary tract infection'], ['diseases/type-1-diabetes', 'Type 1 diabetes'], ['diseases/obstructive-sleep-apnoea', 'Sleep apnoea'], ['child-health/how-to-help-baby-sleep', 'Baby sleep']]),
  },
  {
    slug: 'child-health/worms-in-children',
    name: 'Worms in Children',
    title: 'Worms in Children: Signs, Treatment & Deworming | MedDroid',
    desc: 'Intestinal worms in children — signs (itchy bottom, tummy ache), how deworming works, prevention and hygiene, and when to see a doctor. Not a diagnosis.',
    h1: 'Worms in children',
    lede: 'Intestinal worms are very common in children, especially threadworms. They are easily treated with deworming medicine, and good hygiene stops them coming back and spreading.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about worms',
    featTitle: 'Signs & what helps',
    features: [
      'Signs: an itchy bottom (worse at night), tummy ache, poor appetite, disturbed sleep',
      'Sometimes tiny white threadworms are seen around the bottom or in stool',
      'Deworming medicine (albendazole or mebendazole) usually clears them',
      'Treat the whole household together for threadworms',
      'Routine deworming is often advised every 6 months in childhood',
    ],
    warnings: [
      'Weight loss, blood in the stool, or a swollen tummy',
      'Persistent tummy pain or vomiting',
      'Passing a large worm, or worms not clearing after treatment',
      'Pallor and tiredness (possible anaemia from heavy infestation)',
    ],
    noteTitle: 'Hygiene prevents reinfection.',
    note: 'Handwashing, short clean nails, washing bedding and treating the household together stop worms returning. Follow your doctor’s or the local deworming programme’s advice. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I know if my child has worms?', a: 'An itchy bottom (especially at night), tummy ache, poor appetite and disturbed sleep are common signs. You may see tiny white threadworms around the bottom.' },
      { q: 'How are worms treated in children?', a: 'A deworming tablet or syrup (usually albendazole or mebendazole), often with a repeat dose after 2 weeks for threadworms, plus treating the whole family and good hygiene.' },
      { q: 'How often should children be dewormed?', a: 'Many programmes advise deworming every 6 months in childhood. Follow your doctor or local health guidance.' },
    ],
    related: REL([['diseases/worm-infestation', 'Worm infestation'], ['medicines/albendazole', 'Albendazole'], ['medicines/mebendazole', 'Mebendazole'], ['diseases/childhood-anaemia', 'Childhood anaemia']]),
  },
];
