// Content data for the two large SEO clusters:
//   /symptoms/<slug>/      — a symptom, its likely causes (diseases), red flags
//   /blood-tests/<slug>/   — a blood test, its normal reference range, high/low
// Consumed by gen-landing.mjs. Ranges are TYPICAL ADULT values and vary by lab,
// age, sex and method — every blood-test page repeats that caveat.

const EMG = 'call your local emergency number now';

// ------------------------------------------------------------- symptoms ------
export const SYMPTOMS = [
  { slug: 'chest-pain', name: 'Chest pain', dept: ['cardiology', 'Cardiology'],
    lede: 'Chest pain has many causes — from a pulled muscle or acid reflux to the heart. Some of it is an emergency. Here is how to tell what is usually harmless from what needs help now.',
    causes: [
      'Heart — angina or heart attack (pressure/tightness, often with breathlessness or sweating)',
      'Acid reflux / GERD — burning behind the breastbone, worse lying down',
      'Muscle or rib strain — sharp, worse on movement or pressing the spot',
      'Anxiety or panic attack — tightness with fast breathing and fear',
      'Lung causes — pneumonia, pleurisy or a clot (pulmonary embolism)',
      'Costochondritis — inflammation of rib-cartilage joints',
    ],
    warnings: [
      `Crushing or pressure-like pain spreading to the arm, jaw or back — ${EMG}`,
      'Chest pain with breathlessness, sweating, nausea or fainting',
      'Sudden severe pain with a racing heart or collapse',
      'Any chest pain that is new, severe or not settling — get seen urgently',
    ],
    faqs: [
      { q: 'Is chest pain always a heart attack?', a: 'No — most chest pain is not a heart attack. But heart pain can be subtle, so pressure spreading to the arm or jaw, or pain with breathlessness or sweating, should be treated as an emergency.' },
      { q: 'How do I know if it is acid reflux or my heart?', a: 'Reflux tends to burn, follows meals and eases with antacids; heart pain tends to be pressure brought on by exertion. They can overlap, so when unsure, get checked — an ECG settles it quickly.' },
    ] },
  { slug: 'headache', name: 'Headache', dept: ['neurology', 'Neurology'],
    lede: 'Almost everyone gets headaches, and the vast majority are harmless. A few patterns, though, point to something serious. Here are the common causes and the warning signs.',
    causes: [
      'Tension headache — a tight band around the head, stress-related',
      'Migraine — throbbing, often one-sided, with nausea or light sensitivity',
      'Sinus headache — pressure over the cheeks/forehead with a blocked nose',
      'Dehydration, skipped meals, caffeine withdrawal or poor sleep',
      'Eye strain or uncorrected vision',
      'Medication-overuse headache — from taking painkillers too often',
    ],
    warnings: [
      `A sudden "worst headache of my life" (thunderclap) — ${EMG}`,
      'Headache with fever and a stiff neck, or a non-fading rash',
      'Headache with weakness, confusion, slurred speech or vision loss',
      'A new headache after a head injury, or one that steadily worsens over days',
    ],
    faqs: [
      { q: 'When should I worry about a headache?', a: 'A sudden severe headache, or one with fever and stiff neck, weakness, confusion or vision changes, needs urgent care. A steadily worsening new headache also warrants review.' },
      { q: 'What is the difference between a migraine and a tension headache?', a: 'Tension headaches feel like a tight band and are usually mild-moderate; migraines throb, are often one-sided, and come with nausea or sensitivity to light and sound.' },
    ] },
  { slug: 'abdominal-pain', name: 'Abdominal (stomach) pain', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'Stomach pain is extremely common and usually settles on its own. The location, type and company it keeps (fever, vomiting, bleeding) help tell mild causes from ones that need urgent care.',
    causes: [
      'Indigestion, gas or constipation',
      'Gastritis or peptic ulcer — burning upper-tummy pain',
      'Food poisoning or a stomach bug (with diarrhoea/vomiting)',
      'Appendicitis — pain moving to the lower right, with fever',
      'Gallstones — right upper pain after fatty meals',
      'Urinary infection or kidney stones (with urinary symptoms)',
    ],
    warnings: [
      `Sudden severe pain with a rigid, board-like abdomen — ${EMG}`,
      'Pain with vomiting blood, or black/tarry stools',
      'Pain low on the right with fever (possible appendicitis)',
      'Pain in pregnancy, or severe pain that is not settling',
    ],
    faqs: [
      { q: 'When is stomach pain an emergency?', a: 'Severe, sudden pain with a rigid abdomen, pain with vomiting blood or black stools, or lower-right pain with fever all need urgent assessment.' },
      { q: 'What causes recurring upper-abdominal pain?', a: 'Common culprits are gastritis, acid reflux and peptic ulcers. Persistent pain, weight loss or difficulty swallowing should be investigated by a doctor.' },
    ] },
  { slug: 'back-pain', name: 'Back pain', dept: ['orthopedics', 'Orthopedics'],
    lede: 'Most back pain is muscular and improves within a few weeks. A small number of "red-flag" features suggest a nerve or serious cause that needs prompt attention.',
    causes: [
      'Muscle or ligament strain — the most common cause',
      'Poor posture or prolonged sitting',
      'Slipped (herniated) disc — with pain shooting down a leg (sciatica)',
      'Age-related wear (spondylosis, arthritis)',
      'Osteoporosis — a compression fracture in older adults',
      'Kidney causes — infection or stones (loin pain)',
    ],
    warnings: [
      `Loss of bladder or bowel control, or numbness around the groin — ${EMG}`,
      'Leg weakness or numbness that is worsening',
      'Back pain with fever, or after a significant fall/injury',
      'Unexplained weight loss or night pain with a history of cancer',
    ],
    faqs: [
      { q: 'How long does back pain take to heal?', a: 'Simple muscular back pain usually eases within 2–6 weeks with gentle movement and pain relief. Pain that persists beyond that, or comes with red flags, should be reviewed.' },
      { q: 'Should I rest or stay active with back pain?', a: 'Gentle activity is better than bed rest for most back pain. Avoid heavy lifting, keep moving within comfort, and see a doctor if it is severe or not improving.' },
    ] },
  { slug: 'joint-pain', name: 'Joint pain', dept: ['rheumatology', 'Rheumatology'],
    lede: 'Aching or swollen joints can come from wear, injury, gout or an autoimmune condition. The pattern — which joints, morning stiffness, swelling — points to the cause.',
    causes: [
      'Osteoarthritis — wear-and-tear, worse with use, in older adults',
      'Rheumatoid arthritis — symmetrical, with prolonged morning stiffness',
      'Gout — sudden severe pain, often the big toe, red and hot',
      'Injury or overuse (sprain, tendinitis)',
      'Viral infections causing temporary joint aches',
      'Lupus or other autoimmune disease',
    ],
    warnings: [
      'A hot, red, very painful swollen joint with fever (possible infection) — seek urgent care',
      'A joint that cannot bear weight after an injury',
      'Joint pain with a widespread rash or feeling very unwell',
      'Prolonged morning stiffness (over an hour) in several joints',
    ],
    faqs: [
      { q: 'Is my joint pain arthritis?', a: 'Possibly — osteoarthritis worsens with use and age, while rheumatoid arthritis is symmetrical with long morning stiffness. Blood tests and an exam help tell them apart.' },
      { q: 'What makes gout flare up?', a: 'High uric acid crystallising in a joint — often triggered by alcohol, red meat, seafood or dehydration. A sudden, very painful big-toe joint is classic.' },
    ] },
  { slug: 'neck-pain', name: 'Neck pain', dept: ['orthopedics', 'Orthopedics'],
    lede: 'Neck pain is usually from muscle strain or posture and settles with time. Rarely it signals a nerve or serious problem — the red flags below tell you when to act.',
    causes: [
      'Muscle strain — "text neck", poor posture, sleeping awkwardly',
      'Cervical spondylosis — age-related wear',
      'Pinched nerve — pain or tingling down the arm',
      'Whiplash after a jolt or accident',
      'Stress and tension',
      'Rarely, meningitis (with fever and stiffness)',
    ],
    warnings: [
      `A stiff neck with high fever, headache and a rash — ${EMG} (possible meningitis)`,
      'Neck pain after a significant injury or fall',
      'Arm weakness, numbness, or clumsiness in the hands',
      'Loss of bladder or bowel control',
    ],
    faqs: [
      { q: 'Why does my neck hurt after using my phone?', a: 'Looking down for long periods strains the neck muscles ("text neck"). Raising the screen, taking breaks and gentle stretches usually help.' },
      { q: 'When is neck stiffness serious?', a: 'A stiff neck with fever, severe headache and sensitivity to light can indicate meningitis and needs emergency care.' },
    ] },
  { slug: 'ear-pain', name: 'Ear pain', dept: ['ent', 'ENT'],
    lede: 'Ear pain is common — especially in children — and often comes from infection or wax. Most settles, but persistent pain or hearing loss should be checked.',
    causes: [
      'Middle-ear infection (otitis media) — common in children',
      "Swimmer's ear (outer-ear infection)",
      'Ear wax build-up',
      'Referred pain from the throat, teeth or jaw (TMJ)',
      'Pressure changes (flying, diving)',
      'A foreign body (especially in children)',
    ],
    warnings: [
      'Severe pain with swelling/redness behind the ear, or facial weakness — seek urgent care',
      'High fever, a very unwell child, or a stiff neck',
      'Sudden hearing loss, or discharge of blood/fluid after injury',
      'Pain not settling after a few days',
    ],
    faqs: [
      { q: 'Do ear infections need antibiotics?', a: 'Many ear infections are viral and settle on their own with pain relief. Antibiotics are used in certain cases — a doctor decides based on age and severity.' },
      { q: 'How do I safely remove ear wax?', a: 'Never use cotton buds, which push wax deeper. Softening drops help; if the ear is blocked or painful, a clinician can clear it safely.' },
    ] },
  { slug: 'sore-throat', name: 'Sore throat', dept: ['ent', 'ENT'],
    lede: 'Most sore throats are viral and clear within a week. A few are bacterial (strep) or point to something needing care — here is how to tell.',
    causes: [
      'Viral infection (common cold, flu) — the usual cause',
      'Strep throat — bacterial, with fever and swollen tonsils, no cough',
      'Tonsillitis',
      'Acid reflux irritating the throat',
      'Dry air, smoking or shouting',
      'Glandular fever (mononucleosis) in teens/young adults',
    ],
    warnings: [
      `Difficulty breathing or swallowing, or drooling — ${EMG}`,
      'A muffled "hot potato" voice with severe one-sided pain',
      'High fever with a widespread rash',
      'A sore throat lasting more than a week, or with a neck lump',
    ],
    faqs: [
      { q: 'Is my sore throat viral or strep?', a: 'Strep is more likely with fever, swollen tonsils with white spots, tender neck glands and NO cough. Viral throats usually come with a runny nose and cough. A swab confirms strep.' },
      { q: 'When do I need antibiotics for a sore throat?', a: 'Only if it is bacterial (strep). Most sore throats are viral and improve with fluids, rest and pain relief.' },
    ] },
  { slug: 'painful-urination', name: 'Painful urination', dept: ['urology', 'Urology'],
    lede: 'Burning or stinging when you pee (dysuria) usually means a urinary infection, but there are other causes. It is easily tested and treated.',
    causes: [
      'Urinary tract infection (UTI) — the most common cause',
      'Sexually transmitted infection (STI)',
      'Kidney or bladder stones',
      'Prostate problems in men',
      'Vaginal irritation or thrush in women',
      'Dehydration or irritants (soaps, chemicals)',
    ],
    warnings: [
      'Fever with back/flank pain and vomiting (possible kidney infection) — seek urgent care',
      'Blood in the urine',
      'Inability to pass urine, or severe lower-tummy pain',
      'Symptoms in pregnancy, or a very unwell feeling',
    ],
    faqs: [
      { q: 'Can a UTI go away on its own?', a: 'Mild UTIs sometimes settle with fluids, but many need antibiotics — and an untreated UTI can spread to the kidneys. Testing your urine is the safe step.' },
      { q: 'Why does it burn when I urinate but the test is clear?', a: 'Causes include STIs, irritation, or inflammation without infection. If symptoms persist with a "clear" test, a doctor may look further.' },
    ] },
  { slug: 'pelvic-pain', name: 'Pelvic pain', dept: ['gynaecology', 'Gynaecology'],
    lede: 'Pain low in the abdomen or pelvis has many causes across the gut, bladder and reproductive organs. Some need urgent care, especially in pregnancy.',
    causes: [
      'Period pain (dysmenorrhoea) or ovulation pain',
      'Urinary tract infection',
      'Ovarian cyst',
      'Pelvic inflammatory disease (infection)',
      'Endometriosis',
      'Constipation or irritable bowel',
    ],
    warnings: [
      `Severe one-sided pain with a missed period or positive pregnancy test — ${EMG} (possible ectopic)`,
      'Pain with fever and abnormal discharge',
      'Sudden severe pain with fainting',
      'Heavy bleeding with dizziness',
    ],
    faqs: [
      { q: 'Is severe period pain normal?', a: 'Some cramping is normal, but pain that stops you functioning, or is worsening over months, can point to conditions like endometriosis and deserves review.' },
      { q: 'What is an ectopic pregnancy?', a: 'A pregnancy growing outside the womb — it causes one-sided pain and bleeding and is a medical emergency. Any severe pelvic pain with a positive pregnancy test needs immediate care.' },
    ] },
  { slug: 'fever', name: 'Fever', dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'A fever (38°C / 100.4°F or above) is the body fighting infection. Most fevers are viral and settle in a few days — but certain features need prompt care.',
    causes: [
      'Viral infections (flu, COVID, common cold)',
      'Bacterial infections (throat, chest, urine)',
      'In many regions: typhoid, dengue, malaria',
      'COVID-19',
      'Post-vaccination (short-lived)',
      'Less commonly, inflammatory conditions',
    ],
    warnings: [
      `A stiff neck, non-fading rash, confusion or difficulty breathing — ${EMG}`,
      'Fever in a baby under 3 months',
      'A very high fever that will not come down, or fever over 5 days',
      'Fever with severe pain, dehydration or a rapidly worsening condition',
    ],
    faqs: [
      { q: 'What temperature counts as a fever?', a: 'Generally 38°C (100.4°F) or above. How you feel matters as much as the number — a lower reading with severe symptoms still deserves attention.' },
      { q: 'How do I bring a fever down at home?', a: 'Fluids, rest and appropriate paracetamol or ibuprofen for comfort. Watch for the red-flag signs above, and seek care for very young children or a fever that lingers.' },
    ] },
  { slug: 'fatigue', name: 'Fatigue and tiredness', dept: ['endocrinology', 'Endocrinology'],
    lede: 'Feeling constantly tired is one of the most common health complaints. Often it is lifestyle, but persistent fatigue can signal anaemia, thyroid problems, diabetes or low mood.',
    causes: [
      'Poor sleep, stress or overwork',
      'Anaemia (low haemoglobin/iron)',
      'Thyroid problems (usually underactive)',
      'Diabetes or blood-sugar swings',
      'Depression or anxiety',
      'Vitamin D or B12 deficiency; viral illness',
    ],
    warnings: [
      'Fatigue with chest pain, severe breathlessness or fainting — seek urgent care',
      'Rapid unexplained weight loss with fatigue',
      'Fatigue with very pale skin, blood loss or a racing heart',
      'Fatigue lasting weeks despite rest',
    ],
    faqs: [
      { q: 'What blood tests check for the cause of fatigue?', a: 'Common ones are a full blood count (anaemia), thyroid (TSH), blood sugar/HbA1c, and vitamin D and B12. MedDroid can explain your results in plain language.' },
      { q: 'When should tiredness be investigated?', a: 'If it lasts more than a couple of weeks despite good sleep, or comes with weight loss, breathlessness or low mood, see a doctor for simple tests.' },
    ] },
  { slug: 'unexplained-weight-loss', name: 'Unexplained weight loss', dept: ['endocrinology', 'Endocrinology'],
    lede: 'Losing weight without trying — especially more than 5% of your body weight over 6–12 months — should always be checked, as it can point to a treatable condition.',
    causes: [
      'Overactive thyroid (hyperthyroidism)',
      'Diabetes (new or poorly controlled)',
      'Depression or anxiety reducing appetite',
      'Digestive disease (coeliac, IBD, ulcers)',
      'Chronic infection (e.g. TB in some regions)',
      'Cancer (a less common but important cause)',
    ],
    warnings: [
      'Weight loss with coughing blood, or blood in stool/urine — seek prompt care',
      'Weight loss with night sweats and persistent fever',
      'Difficulty swallowing or a persistent change in bowel habit',
      'Any significant unintentional weight loss — get reviewed',
    ],
    faqs: [
      { q: 'How much unexplained weight loss is concerning?', a: 'Losing more than about 5% of your body weight over 6–12 months without trying is worth investigating with your doctor.' },
      { q: 'What tests are done for unexplained weight loss?', a: 'Usually blood tests (thyroid, sugar, blood count, inflammation), sometimes imaging or endoscopy, guided by your other symptoms.' },
    ] },
  { slug: 'night-sweats', name: 'Night sweats', dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Occasional sweating at night from a warm room is normal. Drenching night sweats that soak the sheets, especially with other symptoms, deserve a look.',
    causes: [
      'Menopause / perimenopause',
      'Infections (including TB in some regions)',
      'Overactive thyroid',
      'Anxiety or low blood sugar',
      'Certain medicines',
      'Rarely, lymphoma or other cancers',
    ],
    warnings: [
      'Night sweats with unexplained weight loss and persistent fever — seek prompt care',
      'Night sweats with a new lump or swollen glands',
      'Coughing blood or a persistent cough',
      'Drenching sweats lasting weeks',
    ],
    faqs: [
      { q: 'Are night sweats always serious?', a: 'No — a hot room, menopause or anxiety are common, harmless causes. But drenching sweats with weight loss, fever or lumps should be checked.' },
      { q: 'What is the link between night sweats and TB?', a: 'In regions where TB is common, drenching night sweats with a lasting cough, fever and weight loss can be a sign and should be tested.' },
    ] },
  { slug: 'dizziness', name: 'Dizziness', dept: ['neurology', 'Neurology'],
    lede: '"Dizzy" can mean light-headedness or a spinning sensation (vertigo). Most causes are benign — inner ear, dehydration, blood pressure — but some need urgent care.',
    causes: [
      'Inner-ear problems (BPPV, labyrinthitis) — spinning vertigo',
      'Low blood pressure on standing / dehydration',
      'Low blood sugar',
      'Anaemia',
      'Anxiety or hyperventilation',
      'Medication side effects',
    ],
    warnings: [
      `Dizziness with slurred speech, face droop, weakness or double vision — ${EMG} (stroke)`,
      'Dizziness with chest pain, fainting or a very fast/slow pulse',
      'Sudden severe headache with the dizziness',
      'A recent head injury',
    ],
    faqs: [
      { q: 'What is the difference between dizziness and vertigo?', a: 'Dizziness is a general light-headed feeling; vertigo is a false sense of spinning, usually from the inner ear. The cause and treatment differ.' },
      { q: 'Why do I feel dizzy when I stand up?', a: 'A brief drop in blood pressure on standing (postural hypotension) — often from dehydration or medicines. Rising slowly and drinking fluids helps; persistent cases need review.' },
    ] },
  { slug: 'fainting', name: 'Fainting (syncope)', dept: ['cardiology', 'Cardiology'],
    lede: 'Fainting is a brief loss of consciousness from a temporary drop in blood flow to the brain. Most is harmless (a simple faint), but some points to the heart.',
    causes: [
      'Simple faint (vasovagal) — from standing, heat, pain or fright',
      'Dehydration or low blood pressure',
      'Low blood sugar',
      'Heart rhythm problems (arrhythmia)',
      'Heart valve or structural disease',
      'Certain medicines',
    ],
    warnings: [
      'Fainting during exercise or while lying down — needs urgent cardiac review',
      'Fainting with chest pain or palpitations',
      'A family history of sudden death, or fainting with injury',
      'Fainting with no warning at all',
    ],
    faqs: [
      { q: 'Is fainting dangerous?', a: 'Most faints are harmless, but fainting during exertion, with chest pain or palpitations, or with a family history of sudden death, needs prompt heart checks.' },
      { q: 'How can I prevent simple fainting?', a: 'Stay hydrated, rise slowly, avoid long standing in heat, and lie down or sit with your head low if you feel the warning signs (light-headedness, sweating, tunnel vision).' },
    ] },
  { slug: 'swollen-lymph-nodes', name: 'Swollen lymph nodes', dept: ['infectious-diseases', 'Infectious Diseases'],
    lede: 'Swollen glands in the neck, armpit or groin usually mean your body is fighting an infection nearby. Most settle within a couple of weeks.',
    causes: [
      'Viral or bacterial infection (throat, cold, skin)',
      'Dental or ear infection (neck glands)',
      'Glandular fever (mononucleosis)',
      'Skin infection near the node',
      'Tuberculosis in some regions',
      'Rarely, lymphoma or other cancer',
    ],
    warnings: [
      'A hard, fixed, painless node that keeps growing — get reviewed',
      'Swollen glands with unexplained weight loss, night sweats and fever',
      'A node larger than ~2 cm lasting over 2–4 weeks',
      'Swelling with difficulty breathing or swallowing',
    ],
    faqs: [
      { q: 'How long should swollen glands last?', a: 'Glands that swell with an infection usually shrink within 2–3 weeks. A node that persists beyond a month, keeps growing or feels hard and fixed should be checked.' },
      { q: 'Are swollen lymph nodes a sign of cancer?', a: 'Usually not — infection is far more common. But painless, hard, growing nodes, especially with weight loss or night sweats, need medical assessment.' },
    ] },
  { slug: 'shortness-of-breath', name: 'Shortness of breath', dept: ['pulmonology', 'Pulmonology'],
    lede: 'Breathlessness ranges from normal (hard exercise) to a medical emergency. Sudden or severe shortness of breath should always be taken seriously.',
    causes: [
      'Asthma or COPD',
      'Chest infection / pneumonia',
      'Anxiety or panic',
      'Anaemia',
      'Heart failure',
      'A blood clot in the lung (pulmonary embolism)',
    ],
    warnings: [
      `Sudden severe breathlessness, or blue lips — ${EMG}`,
      'Breathlessness with chest pain, or coughing blood',
      'Breathlessness at rest or that wakes you from sleep',
      'A swollen, painful calf with breathlessness (possible clot)',
    ],
    faqs: [
      { q: 'When is breathlessness an emergency?', a: 'Sudden or severe shortness of breath, blue lips, chest pain, or breathlessness at rest all need emergency care.' },
      { q: 'Why am I short of breath climbing stairs?', a: 'It can be deconditioning, asthma, anaemia or a heart/lung cause. New or worsening breathlessness on mild exertion should be assessed.' },
    ] },
  { slug: 'cough', name: 'Cough', dept: ['pulmonology', 'Pulmonology'],
    lede: 'A cough clears the airways and usually follows a cold, settling in 2–3 weeks. A lasting cough or one with alarm features needs a closer look.',
    causes: [
      'Viral infection (cold, flu, COVID)',
      'Post-nasal drip / sinusitis',
      'Asthma (often a dry night cough)',
      'Acid reflux',
      'Chest infection / pneumonia (with fever, phlegm)',
      'Smoking; in some regions, TB',
    ],
    warnings: [
      'Coughing up blood — get seen promptly',
      'Cough with breathlessness, chest pain or high fever',
      'A cough lasting more than 3 weeks',
      'Cough with unexplained weight loss or drenching night sweats',
    ],
    faqs: [
      { q: 'How long should a cough last?', a: 'A cough after a cold can linger 2–3 weeks. A cough beyond 3 weeks, or with blood, weight loss or breathlessness, should be investigated.' },
      { q: 'Why do I cough more at night?', a: 'Night coughs can point to asthma, post-nasal drip or acid reflux. If it disturbs sleep regularly, a doctor can help find the cause.' },
    ] },
  { slug: 'heart-palpitations', name: 'Heart palpitations', dept: ['cardiology', 'Cardiology'],
    lede: 'Palpitations are an awareness of your heartbeat — racing, pounding or skipping. Most are harmless, but some rhythms need treatment.',
    causes: [
      'Anxiety, stress or panic',
      'Caffeine, alcohol or nicotine',
      'Fever, dehydration or exercise',
      'Overactive thyroid',
      'Anaemia',
      'Arrhythmias such as atrial fibrillation',
    ],
    warnings: [
      'Palpitations with chest pain, fainting or severe breathlessness — seek urgent care',
      'A very fast pulse that will not settle',
      'Palpitations with a family history of sudden death',
      'Frequent or prolonged episodes',
    ],
    faqs: [
      { q: 'Are palpitations dangerous?', a: 'Usually not — they are often caused by caffeine, stress or exercise. But palpitations with fainting, chest pain or breathlessness, or that are frequent and prolonged, need heart checks.' },
      { q: 'How are palpitations investigated?', a: 'An ECG, sometimes a 24-hour heart monitor, plus blood tests for thyroid and anaemia. MedDroid can explain an ECG in plain words while your doctor confirms.' },
    ] },
  { slug: 'wheezing', name: 'Wheezing', dept: ['pulmonology', 'Pulmonology'],
    lede: 'Wheezing is a whistling sound when you breathe, from narrowed airways. It is common in asthma and chest infections, and occasionally an emergency.',
    causes: [
      'Asthma',
      'COPD',
      'Chest infection / bronchitis',
      'Allergic reaction',
      'Acid reflux',
      'A foreign body (especially in children)',
    ],
    warnings: [
      `Wheeze with severe breathlessness, blue lips or unable to speak in full sentences — ${EMG}`,
      'Wheeze with lip/throat swelling or a rash (anaphylaxis)',
      'Sudden wheeze after a bee sting, food or new medicine',
      'A reliever inhaler not working',
    ],
    faqs: [
      { q: 'Does wheezing always mean asthma?', a: 'No — infections, COPD, allergy and reflux can all cause wheeze. New or recurrent wheeze should be assessed to find the cause.' },
      { q: 'When is wheezing an emergency?', a: 'If it comes with severe breathlessness, blue lips, an inability to speak in full sentences, or signs of an allergic reaction, call emergency services.' },
    ] },
  { slug: 'nausea-and-vomiting', name: 'Nausea and vomiting', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'Feeling sick and vomiting are usually short-lived — a bug or something you ate. The concern is dehydration and a few warning patterns.',
    causes: [
      'Stomach bug (gastroenteritis) or food poisoning',
      'Pregnancy (morning sickness)',
      'Migraine',
      'Motion sickness',
      'Medicines or alcohol',
      'Appendicitis, gallstones or other abdominal problems',
    ],
    warnings: [
      'Vomiting blood, or vomit that looks like coffee grounds — seek urgent care',
      'Signs of dehydration: little urine, dizziness, dry mouth',
      'Vomiting with severe abdominal pain or a rigid tummy',
      'A severe headache, stiff neck or confusion with vomiting',
    ],
    faqs: [
      { q: 'How do I stay hydrated when vomiting?', a: 'Sip small amounts of water or oral rehydration solution frequently rather than large drinks. Seek help if you cannot keep fluids down or show signs of dehydration.' },
      { q: 'When should vomiting be checked?', a: 'If it lasts more than 1–2 days, contains blood, comes with severe pain or dehydration, or with a severe headache and stiff neck, get medical care.' },
    ] },
  { slug: 'diarrhea', name: 'Diarrhea', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'Loose, frequent stools are usually a short-lived infection and settle within a few days. Staying hydrated is the priority; a few features need care.',
    causes: [
      'Viral or bacterial gastroenteritis',
      'Food poisoning',
      "Travellers' diarrhoea",
      'Medicines (e.g. antibiotics)',
      'Irritable bowel syndrome (IBS)',
      'Inflammatory bowel disease (IBD)',
    ],
    warnings: [
      'Blood or black tarry stools — get seen promptly',
      'Signs of dehydration: little urine, dizziness, sunken eyes',
      'High fever with severe abdominal pain',
      'Diarrhoea lasting more than a week, or in a baby/older adult',
    ],
    faqs: [
      { q: 'What should I eat and drink with diarrhoea?', a: 'Keep drinking — water and oral rehydration solution — and eat light foods as tolerated. Avoid anti-diarrhoeal medicines if there is blood or high fever until reviewed.' },
      { q: 'When is diarrhoea serious?', a: 'Blood in stool, signs of dehydration, high fever with severe pain, or diarrhoea lasting over a week all warrant medical assessment.' },
    ] },
  { slug: 'constipation', name: 'Constipation', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'Infrequent or hard-to-pass stools are very common and usually respond to fibre, fluids and activity. A change in habit, or bleeding, needs attention.',
    causes: [
      'Low fibre or fluid intake',
      'Inactivity',
      'Ignoring the urge to go; travel/routine change',
      'Medicines (painkillers, iron, some others)',
      'Underactive thyroid',
      'IBS; rarely, a bowel obstruction or growth',
    ],
    warnings: [
      'Constipation with severe abdominal pain, vomiting and a bloated tummy — seek urgent care',
      'Blood in the stool or from the back passage',
      'A persistent change in bowel habit over weeks (especially over 40)',
      'Unexplained weight loss with constipation',
    ],
    faqs: [
      { q: 'How can I relieve constipation naturally?', a: 'More fibre (fruit, vegetables, whole grains), plenty of fluids, regular activity, and not delaying when you feel the urge. Laxatives help short-term if needed.' },
      { q: 'When should constipation be investigated?', a: 'A new, persistent change in bowel habit, bleeding, or weight loss — especially after 40 — should be reviewed to rule out serious causes.' },
    ] },
  { slug: 'bloating', name: 'Bloating', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'A tight, full or swollen tummy is usually down to gas, diet or IBS. Persistent bloating, particularly in women, occasionally needs investigation.',
    causes: [
      'Gas from certain foods (beans, fizzy drinks, dairy)',
      'Constipation',
      'Irritable bowel syndrome (IBS)',
      'Food intolerance (e.g. lactose)',
      'Swallowing air; eating quickly',
      'Rarely, ovarian or bowel disease',
    ],
    warnings: [
      'Persistent bloating with weight loss or loss of appetite — get reviewed',
      'Bloating with blood in stool or a change in bowel habit',
      'New, persistent bloating in a woman (possible ovarian cause)',
      'Severe pain with a hard, distended abdomen',
    ],
    faqs: [
      { q: 'What foods cause bloating?', a: 'Common triggers are beans, onions, cabbage, fizzy drinks, and dairy if you are lactose intolerant. Eating slowly and keeping a food diary helps identify yours.' },
      { q: 'When is bloating a warning sign?', a: 'Persistent bloating with weight loss, appetite loss, or a change in bowel habit — especially new in women — should be checked by a doctor.' },
    ] },
  { slug: 'heartburn', name: 'Heartburn and acid reflux', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'A burning feeling behind the breastbone after meals is classic acid reflux (GERD). It is common and manageable, but persistent symptoms or alarm features need review.',
    causes: [
      'Acid reflux / GERD',
      'Large, fatty or spicy meals; eating late',
      'Being overweight; pregnancy',
      'Smoking, alcohol, caffeine',
      'Hiatus hernia',
      'Certain medicines',
    ],
    warnings: [
      'Difficulty or pain on swallowing, or food sticking — get reviewed',
      'Vomiting blood or black stools',
      'Unexplained weight loss with heartburn',
      'Heartburn-like pain with breathlessness or sweating (rule out the heart)',
    ],
    faqs: [
      { q: 'How can I reduce heartburn?', a: 'Smaller meals, not lying down for 3 hours after eating, raising the head of the bed, losing excess weight, and cutting triggers (spicy/fatty food, alcohol, caffeine). Antacids help short-term.' },
      { q: 'When is heartburn a concern?', a: 'Trouble swallowing, weight loss, vomiting blood, or symptoms not settling with treatment need investigation, sometimes with an endoscopy.' },
    ] },
  { slug: 'blood-in-stool', name: 'Blood in stool', dept: ['gastroenterology', 'Gastroenterology'],
    lede: 'Blood in the stool is common and often from piles or a small tear, but it should never be ignored — it can be the first sign of something serious.',
    causes: [
      'Haemorrhoids (piles) — bright red on wiping',
      'Anal fissure (a small tear) — pain with bright red blood',
      'Gastroenteritis or infection',
      'Inflammatory bowel disease',
      'Peptic ulcer (black, tarry stools)',
      'Polyps or bowel cancer',
    ],
    warnings: [
      'Black, tarry stools or vomiting blood — seek urgent care',
      'Heavy bleeding or feeling faint/dizzy',
      'Blood with weight loss or a persistent change in bowel habit',
      'Any rectal bleeding over 40, or with a family history of bowel cancer',
    ],
    faqs: [
      { q: 'Is blood in stool always cancer?', a: 'No — piles and fissures are far more common. But because bleeding can signal something serious, it should always be assessed, especially over 40 or with other symptoms.' },
      { q: 'What does black stool mean?', a: 'Black, tarry stool (melaena) suggests bleeding higher up in the gut, such as a stomach ulcer, and needs urgent medical attention.' },
    ] },
  { slug: 'numbness-and-tingling', name: 'Numbness and tingling', dept: ['neurology', 'Neurology'],
    lede: '"Pins and needles" or numbness usually means a nerve is compressed or irritated. Most is temporary, but sudden or spreading numbness can be serious.',
    causes: [
      'A trapped nerve (e.g. carpal tunnel, sciatica)',
      'Sitting/lying in one position too long',
      'Vitamin B12 deficiency',
      'Diabetes (nerve damage)',
      'Thyroid problems',
      'Nerve or spinal conditions; rarely, stroke or MS',
    ],
    warnings: [
      `Sudden numbness/weakness on one side, face droop or slurred speech — ${EMG} (stroke)`,
      'Numbness around the groin with bladder/bowel changes',
      'Rapidly spreading numbness or weakness',
      'Numbness after a significant neck/back injury',
    ],
    faqs: [
      { q: 'Why do my hands go numb at night?', a: 'A common cause is carpal tunnel syndrome — pressure on a wrist nerve. It often improves with a splint; persistent symptoms should be assessed.' },
      { q: 'When is numbness an emergency?', a: 'Sudden numbness or weakness on one side, with face droop or speech trouble, can be a stroke — call emergency services immediately.' },
    ] },
  { slug: 'skin-rash', name: 'Skin rash', dept: ['dermatology', 'Dermatology'],
    lede: 'Rashes are extremely common and usually harmless — from allergy or eczema to viral infections. A few patterns signal an emergency.',
    causes: [
      'Allergic reaction or contact dermatitis',
      'Eczema or psoriasis',
      'Hives (urticaria)',
      'Viral infections (e.g. chickenpox, measles)',
      'Fungal or bacterial skin infection',
      'Heat rash; drug reactions',
    ],
    warnings: [
      `A rash that does not fade when pressed, with fever — ${EMG} (meningitis/sepsis)`,
      'Rash with lip/face swelling or difficulty breathing (anaphylaxis)',
      'Widespread blistering or peeling skin',
      'A rapidly spreading, hot, painful red area with fever',
    ],
    faqs: [
      { q: 'What is the "glass test" for a rash?', a: 'Press a clear glass firmly over the rash. If the spots do NOT fade under pressure and there is fever, it can indicate meningitis or sepsis — seek emergency care immediately.' },
      { q: 'Can MedDroid look at a photo of my rash?', a: 'Yes — attach a clear photo and MedDroid will describe what it appears to show and common possibilities. It cannot diagnose; anything spreading, blistering or with fever needs a doctor.' },
    ] },
  { slug: 'itching', name: 'Itching', dept: ['dermatology', 'Dermatology'],
    lede: 'Itchy skin (pruritus) is usually from dryness, allergy or a skin condition. Persistent, whole-body itching without a rash can occasionally point to an internal cause.',
    causes: [
      'Dry skin',
      'Eczema, psoriasis or hives',
      'Allergic reactions',
      'Insect bites or scabies',
      'Liver or kidney problems (itch without a rash)',
      'Thyroid problems; iron deficiency',
    ],
    warnings: [
      'Itching with lip/throat swelling or breathlessness (allergy) — seek urgent care',
      'Whole-body itching without a rash, with weight loss or night sweats',
      'Yellowing of the skin or eyes with itching',
      'Severe itching that stops sleep for weeks',
    ],
    faqs: [
      { q: 'Why do I itch all over with no rash?', a: 'Generalised itch without a rash can be dry skin, but persistent cases are sometimes linked to thyroid, liver, kidney or blood conditions and deserve blood tests.' },
      { q: 'How do I relieve itchy skin?', a: 'Moisturise regularly, avoid hot showers and harsh soaps, and use antihistamines for allergic itch. See a doctor if it is severe, spreading or not settling.' },
    ] },
  { slug: 'blurred-vision', name: 'Blurred vision', dept: ['ophthalmology', 'Ophthalmology'],
    lede: 'Blurred vision is often just a need for glasses or dry eyes, but sudden blurring or loss of vision is an emergency for the eye.',
    causes: [
      'Refractive error (needing glasses)',
      'Dry eyes',
      'Cataract (gradual clouding)',
      'Diabetes affecting the retina',
      'Migraine (temporary aura)',
      'Glaucoma; retinal problems',
    ],
    warnings: [
      `Sudden loss of vision, or a "curtain" over your sight — ${EMG}`,
      'Blurred vision with severe eye pain, redness and nausea',
      'Blur with weakness, slurred speech or a severe headache (stroke)',
      'Flashes and a shower of new floaters (possible retinal detachment)',
    ],
    faqs: [
      { q: 'When is blurred vision an emergency?', a: 'Sudden vision loss, a curtain across your sight, severe eye pain with redness, or blur with stroke symptoms all need immediate care.' },
      { q: 'Can diabetes cause blurred vision?', a: 'Yes — high blood sugar can blur vision temporarily and, over time, damage the retina. Diabetics should have regular eye checks.' },
    ] },
  { slug: 'leg-swelling', name: 'Leg swelling', dept: ['cardiology', 'Cardiology'],
    lede: 'Swollen legs or ankles are common — often from standing, heat or minor causes. Swelling in one leg, or with breathlessness, can be serious.',
    causes: [
      'Standing/sitting for long periods; heat',
      'Venous insufficiency (weak leg veins)',
      'Heart, kidney or liver problems (both legs)',
      'A blood clot (DVT) — usually one leg',
      'Injury or infection (one leg, red/hot)',
      'Certain medicines; pregnancy',
    ],
    warnings: [
      'One swollen, painful, warm or red calf — seek urgent care (possible clot)',
      'Leg swelling with chest pain or breathlessness — call emergency services',
      'Sudden swelling with skin breakdown or severe pain',
      'Swelling with reduced urine or yellowing of the skin',
    ],
    faqs: [
      { q: 'Is swelling in both legs or one leg more concerning?', a: 'One-sided swelling that is painful, warm or red can be a blood clot (DVT) and needs urgent assessment. Both-legs swelling more often points to heart, kidney or vein causes.' },
      { q: 'How can I reduce mild leg swelling?', a: 'Elevate the legs, move regularly, avoid long standing, and use compression stockings if advised. Persistent or one-sided swelling should be checked.' },
    ] },
  { slug: 'blood-in-urine', name: 'Blood in urine', dept: ['urology', 'Urology'],
    lede: 'Blood in the urine (haematuria), whether visible or found on a test, always needs to be explained — even if it is painless and happens once.',
    causes: [
      'Urinary tract infection',
      'Kidney or bladder stones',
      'An enlarged prostate in men',
      'Kidney disease',
      'Vigorous exercise (temporary)',
      'Bladder or kidney tumours',
    ],
    warnings: [
      'Inability to pass urine, or passing clots with severe pain — seek urgent care',
      'Blood in urine with fever and flank pain (kidney infection)',
      'Heavy bleeding with dizziness',
      'Any visible blood in urine — always get it checked, even once',
    ],
    faqs: [
      { q: 'Is painless blood in urine serious?', a: 'Painless visible blood in the urine must always be investigated, as it can be an early sign of a bladder or kidney tumour — even when it happens only once.' },
      { q: 'Can a UTI cause blood in urine?', a: 'Yes — infections commonly cause blood and burning. But because other causes exist, a test and sometimes further checks are done to be sure.' },
    ] },
  { slug: 'frequent-urination', name: 'Frequent urination', dept: ['urology', 'Urology'],
    lede: 'Needing to pee more often can be as simple as drinking more fluids, or a sign of infection, diabetes or a prostate problem. The pattern points to the cause.',
    causes: [
      'Drinking more fluid, caffeine or alcohol',
      'Urinary tract infection',
      'Diabetes (with thirst and weight change)',
      'Overactive bladder',
      'Enlarged prostate in men',
      'Pregnancy; certain medicines (diuretics)',
    ],
    warnings: [
      'Frequency with fever, back pain and vomiting (kidney infection) — seek urgent care',
      'Inability to pass urine despite the urge',
      'Blood in the urine',
      'Frequency with excessive thirst and weight loss (possible new diabetes)',
    ],
    faqs: [
      { q: 'Why do I urinate so often at night?', a: 'Night-time urination (nocturia) can be from fluids before bed, an enlarged prostate, overactive bladder, or conditions like diabetes and heart problems. Persistent cases deserve review.' },
      { q: 'Can frequent urination mean diabetes?', a: 'Yes — passing lots of urine with thirst, tiredness and weight loss can be a sign of diabetes. A simple blood sugar or HbA1c test checks for it.' },
    ] },
];

// ---------------------------------------------------------- blood tests ------
const LAB_NOTE = 'Reference ranges are TYPICAL ADULT values and vary by laboratory, age, sex, pregnancy and the method used. Always read your result against the range printed on YOUR report, and let your doctor interpret it alongside your history.';

export const BLOODTESTS = [
  { slug: 'complete-blood-count-cbc', name: 'Complete Blood Count (CBC)',
    lede: 'The CBC is the most common blood test. It measures your red cells, white cells and platelets — screening for anaemia, infection and clotting problems in one panel.',
    rows: [
      ['Haemoglobin (men)', '13.5–17.5 g/dL'],
      ['Haemoglobin (women)', '12.0–15.5 g/dL'],
      ['WBC count', '4,000–11,000 /µL'],
      ['Platelets', '150,000–450,000 /µL'],
      ['Haematocrit (men/women)', '≈ 41–50% / 36–44%'],
    ],
    high: ['High WBC often means infection or inflammation; very high can need investigation', 'High haemoglobin/haematocrit can reflect dehydration or other conditions'],
    low: ['Low haemoglobin = anaemia (iron/B12 deficiency, blood loss)', 'Low platelets raise bleeding risk; low WBC can lower infection defence'],
    faqs: [
      { q: 'What does a CBC test detect?', a: 'It screens for anaemia (low haemoglobin), infection or immune problems (white cells), and bleeding/clotting issues (platelets) — a broad first-line health check.' },
      { q: 'Do I need to fast for a CBC?', a: 'No — a CBC does not usually require fasting, though your lab may combine it with tests (like glucose or lipids) that do.' },
    ] },
  { slug: 'lipid-profile-cholesterol', name: 'Lipid Profile (Cholesterol)',
    lede: 'A lipid profile measures the fats in your blood — total, LDL ("bad"), HDL ("good") cholesterol and triglycerides — to estimate heart-disease risk.',
    rows: [
      ['Total cholesterol', '< 200 mg/dL (desirable)'],
      ['LDL cholesterol', '< 100 mg/dL (optimal)'],
      ['HDL cholesterol', '> 40 (men) / > 50 (women) mg/dL'],
      ['Triglycerides', '< 150 mg/dL'],
    ],
    high: ['High LDL and triglycerides raise the risk of heart attack and stroke', 'Targets are lower if you have diabetes or existing heart disease'],
    low: ['Low HDL ("good" cholesterol) is unfavourable', 'Very low total cholesterol is uncommon and usually not a concern on its own'],
    faqs: [
      { q: 'Do I need to fast for a lipid profile?', a: 'Many labs ask for a 9–12 hour fast, mainly for accurate triglycerides. Some newer guidelines allow non-fasting testing — follow your lab’s instruction.' },
      { q: 'What is a healthy cholesterol level?', a: 'Generally total < 200, LDL < 100 and HDL above 40 (men)/50 (women) mg/dL — but your personal target depends on your overall heart-disease risk.' },
    ] },
  { slug: 'liver-function-test-lft', name: 'Liver Function Test (LFT)',
    lede: 'The LFT checks how well your liver is working, using enzymes (SGPT/ALT, SGOT/AST, ALP) and products it processes (bilirubin, protein, albumin).',
    rows: [
      ['ALT / SGPT', '7–56 U/L'],
      ['AST / SGOT', '5–40 U/L'],
      ['ALP', '44–147 U/L'],
      ['Total bilirubin', '0.1–1.2 mg/dL'],
      ['Albumin', '3.5–5.0 g/dL'],
    ],
    high: ['High ALT/AST suggests liver cell irritation (fatty liver, hepatitis, alcohol, medicines)', 'High bilirubin can cause jaundice (yellow skin/eyes)'],
    low: ['Low albumin can reflect long-standing liver disease, malnutrition or kidney loss'],
    faqs: [
      { q: 'What do raised SGPT and SGOT mean?', a: 'Raised ALT (SGPT) and AST (SGOT) indicate the liver is irritated — common causes are fatty liver, alcohol, viral hepatitis and certain medicines. The pattern and your history guide the cause.' },
      { q: 'Can fatty liver show on an LFT?', a: 'Yes — fatty liver often mildly raises ALT/AST. An ultrasound and lifestyle review usually follow; it is common and often reversible.' },
    ] },
  { slug: 'kidney-function-test-rft', name: 'Kidney Function Test (RFT/KFT)',
    lede: 'Also called RFT or renal panel, this measures creatinine, urea and electrolytes, and calculates eGFR — how well your kidneys are filtering.',
    rows: [
      ['Creatinine (men)', '0.7–1.3 mg/dL'],
      ['Creatinine (women)', '0.6–1.1 mg/dL'],
      ['Blood urea', '15–40 mg/dL'],
      ['eGFR', '> 90 mL/min/1.73m² (normal)'],
    ],
    high: ['High creatinine/urea with low eGFR points to reduced kidney function', 'Can rise with dehydration, medicines or kidney disease'],
    low: ['Low creatinine is usually not a concern (low muscle mass, pregnancy)'],
    faqs: [
      { q: 'What does a high creatinine mean?', a: 'It suggests the kidneys are filtering less well — from dehydration, medicines or kidney disease. eGFR puts it in context; your doctor interprets the trend.' },
      { q: 'What is a normal eGFR?', a: 'An eGFR above 90 is normal; 60–89 is mildly reduced (often with age). Below 60 for 3 months or more suggests chronic kidney disease and needs review.' },
    ] },
  { slug: 'thyroid-function-test-tft', name: 'Thyroid Function Test (TFT)',
    lede: 'The TFT checks your thyroid — the gland that sets your metabolism — mainly through TSH, with free T4 and T3 as needed.',
    rows: [
      ['TSH', '0.4–4.0 mIU/L'],
      ['Free T4', '0.8–1.8 ng/dL'],
      ['Free T3', '2.3–4.2 pg/mL'],
    ],
    high: ['High TSH usually means an UNDER-active thyroid (hypothyroidism): tiredness, weight gain, cold intolerance', 'Low TSH with high T4/T3 means an OVER-active thyroid'],
    low: ['Low TSH usually means an OVER-active thyroid (hyperthyroidism): weight loss, palpitations, heat intolerance'],
    faqs: [
      { q: 'What does a high TSH mean?', a: 'A high TSH usually signals an underactive thyroid — your gland needs more stimulation. Symptoms include tiredness, weight gain and feeling cold. Your doctor may start thyroid hormone.' },
      { q: 'Do I need to fast for a thyroid test?', a: 'Usually no. For consistency, many people test in the morning; if you take thyroid medicine, ask whether to take it before or after the blood draw.' },
    ] },
  { slug: 'electrolytes', name: 'Electrolyte Panel',
    lede: 'Electrolytes are the minerals that keep your nerves, muscles and fluid balance working. This panel checks sodium, potassium, chloride and bicarbonate.',
    rows: [
      ['Sodium (Na)', '135–145 mmol/L'],
      ['Potassium (K)', '3.5–5.0 mmol/L'],
      ['Chloride (Cl)', '98–107 mmol/L'],
      ['Bicarbonate (HCO₃)', '22–29 mmol/L'],
    ],
    high: ['High potassium can affect the heart rhythm and needs prompt attention', 'High sodium usually reflects dehydration'],
    low: ['Low sodium can cause confusion and needs a cause found', 'Low potassium can cause weakness and cramps'],
    faqs: [
      { q: 'Why are potassium levels important?', a: 'Potassium keeps the heart and muscles working. Both high and low levels can disturb the heart rhythm, so abnormal results are taken seriously.' },
      { q: 'What causes low sodium?', a: 'Common causes include certain medicines (diuretics), excess water intake, and hormonal or kidney conditions. Symptoms range from none to confusion; the cause guides treatment.' },
    ] },
  { slug: 'fasting-blood-sugar', name: 'Fasting Blood Sugar',
    lede: 'Fasting blood glucose is measured after 8 hours without food. It is a first-line test for diabetes and prediabetes.',
    rows: [
      ['Normal', '70–99 mg/dL'],
      ['Prediabetes', '100–125 mg/dL'],
      ['Diabetes', '≥ 126 mg/dL (confirmed)'],
    ],
    high: ['100–125 mg/dL = prediabetes; ≥126 (on two tests) = diabetes', 'Very high readings with symptoms need prompt care'],
    low: ['Below ~70 mg/dL is low (hypoglycaemia): shakiness, sweating, confusion — treat with fast sugar'],
    faqs: [
      { q: 'How long should I fast before this test?', a: 'Usually 8–12 hours of no food or drink except water. Take it in the morning, and check with your doctor about any medicines beforehand.' },
      { q: 'What level means diabetes?', a: 'A fasting glucose of 126 mg/dL or above, confirmed on a second test, indicates diabetes; 100–125 is prediabetes. HbA1c is often checked alongside.' },
    ] },
  { slug: 'hba1c', name: 'HbA1c (Glycated Haemoglobin)',
    lede: 'HbA1c reflects your average blood sugar over the past 2–3 months, so it does not need fasting. It is used to diagnose and monitor diabetes.',
    rows: [
      ['Normal', '< 5.7%'],
      ['Prediabetes', '5.7–6.4%'],
      ['Diabetes', '≥ 6.5%'],
      ['Common target (treated diabetes)', '≈ < 7% (individualised)'],
    ],
    high: ['5.7–6.4% = prediabetes; 6.5% or above = diabetes', 'A rising HbA1c means average sugars are climbing'],
    low: ['A low HbA1c is generally good, but can be affected by anaemia or recent blood loss'],
    faqs: [
      { q: 'Do I need to fast for HbA1c?', a: 'No — because it reflects a 2–3 month average, HbA1c can be taken at any time of day without fasting.' },
      { q: 'What HbA1c should a diabetic aim for?', a: 'Many people aim for under 7%, but the target is individual — your doctor sets it based on your age, health and risk of lows.' },
    ] },
  { slug: 'hemoglobin', name: 'Haemoglobin (Hb)',
    lede: 'Haemoglobin is the protein in red cells that carries oxygen. A low level means anaemia; it is one of the most-checked single markers.',
    rows: [
      ['Men', '13.5–17.5 g/dL'],
      ['Women', '12.0–15.5 g/dL'],
      ['Children', '≈ 11–16 g/dL (age-dependent)'],
    ],
    high: ['High haemoglobin can reflect dehydration, smoking, lung conditions or living at altitude'],
    low: ['Low haemoglobin = anaemia — from iron, B12 or folate deficiency, or blood loss; causes tiredness, pallor and breathlessness'],
    faqs: [
      { q: 'What is a dangerously low haemoglobin?', a: 'Symptoms increase as it falls; levels below about 7–8 g/dL often cause marked tiredness and breathlessness and may need urgent treatment. Any low result should be investigated for the cause.' },
      { q: 'How can I raise low haemoglobin?', a: 'It depends on the cause — iron-rich foods or supplements for iron deficiency, B12/folate if deficient, and treating any bleeding. Your doctor first finds out why it is low.' },
    ] },
  { slug: 'platelet-count', name: 'Platelet Count',
    lede: 'Platelets are the tiny cells that help blood clot. Too few raises bleeding risk; too many can raise clotting risk.',
    rows: [
      ['Normal', '150,000–450,000 /µL'],
      ['Low (thrombocytopenia)', '< 150,000 /µL'],
      ['High (thrombocytosis)', '> 450,000 /µL'],
    ],
    high: ['High platelets can follow infection, inflammation or iron deficiency; rarely a bone-marrow condition'],
    low: ['Low platelets (e.g. in dengue, some infections, or immune conditions) increase bleeding/bruising risk'],
    faqs: [
      { q: 'Why do platelets drop in dengue?', a: 'Dengue can suppress platelet production and increase their breakdown, so counts fall — sometimes sharply. They are monitored closely, as very low counts raise bleeding risk.' },
      { q: 'What platelet level is dangerous?', a: 'Bleeding risk rises as platelets fall, particularly below about 20,000–50,000 /µL. Any significantly low count needs medical assessment and monitoring.' },
    ] },
  { slug: 'wbc-count', name: 'White Blood Cell (WBC) Count',
    lede: 'White cells are your immune defence. The total count, and which type is raised, help point to infection, inflammation or other conditions.',
    rows: [
      ['Normal', '4,000–11,000 /µL'],
      ['High (leukocytosis)', '> 11,000 /µL'],
      ['Low (leukopenia)', '< 4,000 /µL'],
    ],
    high: ['High WBC usually means infection or inflammation; stress and steroids also raise it; very high needs investigation'],
    low: ['Low WBC can follow viral infections or certain medicines and can reduce infection defence'],
    faqs: [
      { q: 'What does a high white cell count mean?', a: 'Most often an infection or inflammation. The differential (which cells are up — neutrophils suggest bacteria, lymphocytes viruses) refines the picture.' },
      { q: 'Should I worry about a slightly low WBC?', a: 'A mildly low count is common after viral illness and often harmless. A persistently or markedly low count should be reviewed.' },
    ] },
  { slug: 'creatinine', name: 'Serum Creatinine',
    lede: 'Creatinine is a waste product cleared by the kidneys, so its blood level is a key marker of kidney function, used to calculate eGFR.',
    rows: [
      ['Men', '0.7–1.3 mg/dL'],
      ['Women', '0.6–1.1 mg/dL'],
    ],
    high: ['High creatinine suggests reduced kidney filtering — from dehydration, medicines or kidney disease'],
    low: ['Low creatinine is usually harmless (low muscle mass, pregnancy)'],
    faqs: [
      { q: 'What raises creatinine besides kidney disease?', a: 'Dehydration, a high-protein meal or intense exercise before the test, and certain medicines can raise it. Your doctor looks at the trend and eGFR together.' },
      { q: 'Can high creatinine be reversed?', a: 'If it is from a reversible cause like dehydration or a medicine, yes. Chronic kidney disease is managed to slow progression. Finding the cause is the first step.' },
    ] },
  { slug: 'blood-urea-bun', name: 'Blood Urea / BUN',
    lede: 'Urea (or BUN, blood urea nitrogen) is a waste product from protein breakdown, filtered by the kidneys. It is read alongside creatinine.',
    rows: [
      ['Blood urea', '15–40 mg/dL'],
      ['BUN', '7–20 mg/dL'],
    ],
    high: ['High urea/BUN can reflect dehydration, a high-protein diet, bleeding in the gut, or reduced kidney function'],
    low: ['Low urea can occur with a low-protein diet, pregnancy or liver disease'],
    faqs: [
      { q: 'What is the difference between urea and BUN?', a: 'They measure the same thing reported differently — BUN counts only the nitrogen part. BUN ≈ urea ÷ 2.14. Use whichever your lab reports, against its range.' },
      { q: 'Does a high urea always mean kidney trouble?', a: 'No — dehydration and a high-protein meal commonly raise it. It is most useful read together with creatinine and eGFR.' },
    ] },
  { slug: 'uric-acid', name: 'Uric Acid',
    lede: 'Uric acid is a waste product; when it builds up it can crystallise in joints (gout) or form kidney stones.',
    rows: [
      ['Men', '3.4–7.0 mg/dL'],
      ['Women', '2.4–6.0 mg/dL'],
    ],
    high: ['High uric acid can cause gout (sudden severe joint pain, often the big toe) and kidney stones'],
    low: ['Low uric acid is uncommon and rarely a problem'],
    faqs: [
      { q: 'What foods raise uric acid?', a: 'Red meat, organ meats, seafood, alcohol (especially beer) and sugary drinks. Staying hydrated and moderating these helps lower levels.' },
      { q: 'Does high uric acid always cause gout?', a: 'No — many people with high uric acid never get gout. But higher levels increase the risk of attacks and stones, so it is often managed if symptomatic.' },
    ] },
  { slug: 'crp', name: 'C-Reactive Protein (CRP)',
    lede: 'CRP is a protein that rises with inflammation anywhere in the body, so it is a quick, general marker of infection or inflammatory disease.',
    rows: [
      ['Normal', '< 10 mg/L'],
      ['hs-CRP (low cardiac risk)', '< 1 mg/L'],
      ['hs-CRP (higher cardiac risk)', '> 3 mg/L'],
    ],
    high: ['A high CRP indicates active inflammation or infection; very high suggests significant bacterial infection', 'Raised hs-CRP is linked to higher heart-disease risk'],
    low: ['A low/normal CRP suggests little active inflammation'],
    faqs: [
      { q: 'What does a high CRP mean?', a: 'It signals inflammation somewhere — commonly infection, injury or an inflammatory condition. CRP shows that inflammation is present, not where, so it is read with your symptoms.' },
      { q: 'What is the difference between CRP and hs-CRP?', a: 'They measure the same protein; hs-CRP (high-sensitivity) detects small amounts used to assess cardiovascular risk, while standard CRP tracks infection/inflammation.' },
    ] },
  { slug: 'esr', name: 'ESR (Erythrocyte Sedimentation Rate)',
    lede: 'The ESR is an older, simple marker of inflammation — how fast red cells settle in a tube. It rises slowly and stays up longer than CRP.',
    rows: [
      ['Men', '< 15–20 mm/hr (age-dependent)'],
      ['Women', '< 20–30 mm/hr (age-dependent)'],
    ],
    high: ['A high ESR reflects inflammation, infection, anaemia or, when very high, conditions like some cancers or autoimmune disease'],
    low: ['A low ESR is normal and not a concern'],
    faqs: [
      { q: 'What is the difference between ESR and CRP?', a: 'Both track inflammation. CRP rises and falls quickly (good for acute change); ESR rises and falls slowly. They are often done together.' },
      { q: 'What does a very high ESR mean?', a: 'A markedly high ESR needs a cause found — infections, autoimmune disease and some cancers can raise it. It is a clue, not a diagnosis.' },
    ] },
  { slug: 'calcium', name: 'Serum Calcium',
    lede: 'Calcium is vital for bones, nerves and muscles. Blood calcium is tightly controlled, so abnormal levels always deserve a cause.',
    rows: [
      ['Total calcium', '8.5–10.2 mg/dL'],
      ['Ionised calcium', '4.6–5.3 mg/dL'],
    ],
    high: ['High calcium can cause thirst, constipation, kidney stones and confusion; often from parathyroid problems'],
    low: ['Low calcium can cause tingling, muscle cramps and spasms'],
    faqs: [
      { q: 'What causes high blood calcium?', a: 'The most common causes are an overactive parathyroid gland and certain cancers. It is investigated because it affects the kidneys, bones and brain.' },
      { q: 'Is calcium in the blood the same as bone density?', a: 'No — blood calcium reflects the level circulating now, not the calcium stored in bones. Bone density is measured separately (a DEXA scan).' },
    ] },
  { slug: 'sodium', name: 'Sodium (Na)',
    lede: 'Sodium is the main electrolyte controlling your body’s water balance. Both high and low levels can affect the brain.',
    rows: [
      ['Normal', '135–145 mmol/L'],
      ['Low (hyponatraemia)', '< 135 mmol/L'],
      ['High (hypernatraemia)', '> 145 mmol/L'],
    ],
    high: ['High sodium usually means dehydration (not enough water)'],
    low: ['Low sodium can cause nausea, headache and confusion; causes include diuretics, excess water and hormonal problems'],
    faqs: [
      { q: 'What are the symptoms of low sodium?', a: 'Mild cases may cause none; lower levels bring nausea, headache, confusion and, if severe, seizures. The cause must be found before correcting it, which is done carefully.' },
      { q: 'Can drinking too much water lower sodium?', a: 'Yes — drinking excessive water quickly can dilute blood sodium. It is uncommon but can be serious in endurance athletes or certain conditions.' },
    ] },
  { slug: 'potassium', name: 'Potassium (K)',
    lede: 'Potassium keeps your heart and muscles working. Because both high and low levels disturb the heart rhythm, abnormal results are taken seriously.',
    rows: [
      ['Normal', '3.5–5.0 mmol/L'],
      ['Low (hypokalaemia)', '< 3.5 mmol/L'],
      ['High (hyperkalaemia)', '> 5.0 mmol/L'],
    ],
    high: ['High potassium can cause dangerous heart-rhythm changes and needs prompt attention; often from kidney problems or medicines'],
    low: ['Low potassium can cause weakness, cramps and palpitations; often from vomiting, diarrhoea or diuretics'],
    faqs: [
      { q: 'Why is high potassium dangerous?', a: 'Potassium controls the heart’s electrical activity — a high level can trigger a life-threatening rhythm. That is why it is corrected urgently when very high.' },
      { q: 'Can a blood sample give a falsely high potassium?', a: 'Yes — if red cells break during collection (haemolysis), potassium leaks out and reads high. If a result is unexpectedly high, the test is often repeated.' },
    ] },
  { slug: 'albumin', name: 'Serum Albumin',
    lede: 'Albumin is the main protein in blood, made by the liver. It reflects nutrition, and liver and kidney health.',
    rows: [
      ['Normal', '3.5–5.0 g/dL'],
    ],
    high: ['High albumin usually just reflects dehydration'],
    low: ['Low albumin can indicate liver disease, poor nutrition, inflammation, or protein loss through the kidneys or gut'],
    faqs: [
      { q: 'What does low albumin mean?', a: 'It can reflect long-standing liver disease, malnutrition, ongoing inflammation, or protein leaking from the kidneys (nephrotic syndrome) or gut. The cause guides treatment.' },
      { q: 'Is albumin part of the liver function test?', a: 'Yes — albumin is included in the LFT, because the liver makes it. A falling albumin can indicate reduced liver synthesis over time.' },
    ] },
  { slug: 'bilirubin', name: 'Bilirubin',
    lede: 'Bilirubin is a yellow product from the breakdown of red cells, processed by the liver. High levels cause jaundice — yellow skin and eyes.',
    rows: [
      ['Total bilirubin', '0.1–1.2 mg/dL'],
      ['Direct (conjugated)', '0.0–0.3 mg/dL'],
    ],
    high: ['High bilirubin causes jaundice; causes include liver disease, bile-duct blockage, and increased red-cell breakdown', 'A common harmless cause is Gilbert’s syndrome'],
    low: ['Low bilirubin is not clinically significant'],
    faqs: [
      { q: 'What does high bilirubin mean?', a: 'It can come from liver problems, a blocked bile duct, or faster red-cell breakdown. The split between direct and indirect bilirubin helps point to the cause.' },
      { q: 'Is mild high bilirubin always serious?', a: 'Not always — Gilbert’s syndrome is a common, harmless cause of mildly raised bilirubin, especially when fasting or unwell. Persistent or high levels still need review.' },
    ] },
  { slug: 'vitamin-d', name: 'Vitamin D (25-OH)',
    lede: 'Vitamin D supports bones, muscles and immunity. Deficiency is very common, especially with limited sun exposure.',
    rows: [
      ['Deficient', '< 20 ng/mL'],
      ['Insufficient', '20–29 ng/mL'],
      ['Sufficient', '30–100 ng/mL'],
    ],
    high: ['Very high vitamin D (usually from over-supplementing) can raise blood calcium and harm the kidneys'],
    low: ['Low vitamin D can cause bone/muscle aches, tiredness and, over time, weak bones'],
    faqs: [
      { q: 'How do I raise low vitamin D?', a: 'Sensible sun exposure, vitamin-D-rich foods, and supplements at the dose your doctor advises. Levels are usually rechecked after a course of treatment.' },
      { q: 'What problems does vitamin D deficiency cause?', a: 'Tiredness, bone and muscle aches, and — if long-standing — softening of the bones and higher fracture risk. It is easily corrected once identified.' },
    ] },
  { slug: 'vitamin-b12', name: 'Vitamin B12',
    lede: 'Vitamin B12 is needed for healthy blood and nerves. Deficiency is common in vegetarians and older adults and can cause anaemia and nerve symptoms.',
    rows: [
      ['Normal', '200–900 pg/mL'],
      ['Borderline/low', '< 200 pg/mL'],
    ],
    high: ['High B12 is usually harmless (often from supplements); rarely it needs a cause found'],
    low: ['Low B12 can cause tiredness, a sore tongue, tingling/numbness and memory problems, and anaemia'],
    faqs: [
      { q: 'What are the symptoms of B12 deficiency?', a: 'Tiredness, pale skin, a sore red tongue, pins-and-needles or numbness, and poor concentration. Nerve symptoms make prompt treatment important.' },
      { q: 'Who is at risk of low B12?', a: 'Vegetarians and vegans, older adults, people on certain medicines (like metformin or long-term acid reducers), and those with absorption problems (pernicious anaemia).' },
    ] },
  { slug: 'ferritin-iron-studies', name: 'Ferritin & Iron Studies',
    lede: 'Ferritin reflects your body’s iron stores and is the best single test for iron deficiency — the commonest cause of anaemia worldwide.',
    rows: [
      ['Ferritin (men)', '30–400 ng/mL'],
      ['Ferritin (women)', '15–150 ng/mL'],
      ['Serum iron', '60–170 µg/dL'],
      ['Transferrin saturation', '20–50%'],
    ],
    high: ['High ferritin can reflect inflammation or infection, iron overload, or liver disease'],
    low: ['Low ferritin = low iron stores (iron-deficiency), causing tiredness, pallor and hair thinning'],
    faqs: [
      { q: 'What does low ferritin mean?', a: 'It means your iron stores are low — the earliest sign of iron deficiency, often before anaemia appears. Causes include poor intake, heavy periods and gut blood loss.' },
      { q: 'Can ferritin be high without high iron?', a: 'Yes — ferritin also rises with inflammation or infection (it is an "acute-phase" marker), so a high value is interpreted alongside CRP and iron studies.' },
    ] },
  { slug: 'tsh', name: 'TSH (Thyroid Stimulating Hormone)',
    lede: 'TSH is the pituitary’s signal to the thyroid and the single best screening test for thyroid problems. It moves opposite to thyroid activity.',
    rows: [
      ['Normal', '0.4–4.0 mIU/L'],
      ['High', '> 4.0 mIU/L (underactive thyroid)'],
      ['Low', '< 0.4 mIU/L (overactive thyroid)'],
    ],
    high: ['High TSH means an UNDER-active thyroid (hypothyroidism): tiredness, weight gain, feeling cold, dry skin'],
    low: ['Low TSH means an OVER-active thyroid (hyperthyroidism): weight loss, palpitations, anxiety, heat intolerance'],
    faqs: [
      { q: 'Why does high TSH mean an underactive thyroid?', a: 'When the thyroid makes too little hormone, the pituitary raises TSH to push it harder — so a high TSH signals an underactive gland, not an overactive one.' },
      { q: 'What is subclinical hypothyroidism?', a: 'A mildly raised TSH with normal T4 and few or no symptoms. It is monitored and sometimes treated, depending on the level and your situation.' },
    ] },
  { slug: 'testosterone', name: 'Testosterone',
    lede: 'Testosterone is the main male sex hormone (also present in smaller amounts in women). It is tested for low libido, fatigue, fertility and hormonal symptoms.',
    rows: [
      ['Total testosterone (men)', '≈ 300–1,000 ng/dL'],
      ['Total testosterone (women)', '≈ 15–70 ng/dL'],
    ],
    high: ['High testosterone in women can cause acne, excess hair and irregular periods (e.g. PCOS)'],
    low: ['Low testosterone in men can cause low libido, fatigue, low mood and reduced muscle'],
    faqs: [
      { q: 'When should testosterone be tested?', a: 'Usually a morning sample, as levels are highest then and vary through the day. Two low morning readings are typically needed before diagnosing low testosterone.' },
      { q: 'What causes low testosterone?', a: 'Ageing, obesity, chronic illness, certain medicines, and problems of the testes or pituitary. The cause guides whether and how it is treated.' },
    ] },
  { slug: 'cortisol', name: 'Cortisol',
    lede: 'Cortisol is the body’s main stress hormone, following a daily rhythm — high in the morning, low at night. It is tested for adrenal problems.',
    rows: [
      ['Morning (8 am)', '≈ 6–23 µg/dL'],
      ['Evening', 'Lower than morning'],
    ],
    high: ['High cortisol (Cushing’s) can cause weight gain, high blood pressure, easy bruising and high sugar'],
    low: ['Low cortisol (Addison’s/adrenal insufficiency) can cause fatigue, low blood pressure and weight loss — and can be an emergency in a crisis'],
    faqs: [
      { q: 'Why is cortisol measured in the morning?', a: 'Cortisol peaks in the early morning and falls through the day, so timing matters. Abnormal rhythms or levels prompt further specialised testing.' },
      { q: 'What is an adrenal crisis?', a: 'A dangerous shortage of cortisol causing very low blood pressure, vomiting and collapse — a medical emergency needing immediate treatment, seen in adrenal insufficiency.' },
    ] },
  { slug: 'beta-hcg-pregnancy', name: 'Beta hCG (Pregnancy Test)',
    lede: 'Beta hCG is the hormone of pregnancy. A blood test detects it early and, when repeated, shows whether a pregnancy is progressing normally.',
    rows: [
      ['Not pregnant', '< 5 mIU/mL'],
      ['Possible pregnancy', '5–25 mIU/mL (repeat)'],
      ['Pregnant', '> 25 mIU/mL (rises early on)'],
    ],
    high: ['Very high or rapidly rising hCG can occur in multiple pregnancy or certain conditions'],
    low: ['A slow-rising or falling hCG can indicate an early miscarriage or ectopic pregnancy'],
    faqs: [
      { q: 'How soon can a blood hCG detect pregnancy?', a: 'A blood test can detect pregnancy about 8–11 days after conception — earlier than most urine tests. Levels roughly double every 48–72 hours in early pregnancy.' },
      { q: 'What does a low or slow-rising hCG mean?', a: 'It can indicate a very early pregnancy, an early miscarriage, or an ectopic pregnancy. Repeat tests and an ultrasound clarify — sudden pain with a positive test needs urgent care.' },
    ] },
  { slug: 'troponin', name: 'Troponin',
    lede: 'Troponin is a protein released when heart muscle is damaged. It is the key blood test used in hospitals to diagnose a heart attack.',
    rows: [
      ['Normal', 'Below the assay’s 99th percentile (often < 0.04 ng/mL)'],
      ['Raised', 'Above the cut-off — suggests heart-muscle injury'],
    ],
    high: ['A rising troponin strongly suggests a heart attack or other heart-muscle injury and is a medical emergency', 'It can also rise in other serious illness'],
    low: ['A normal troponin (on serial tests) makes a heart attack much less likely'],
    faqs: [
      { q: 'Does a raised troponin always mean a heart attack?', a: 'Not always — it shows heart-muscle injury, which is usually a heart attack but can occur in other serious conditions. It is interpreted with the ECG and symptoms.' },
      { q: 'Why is troponin tested more than once?', a: 'Levels rise over hours after heart injury, so serial samples (e.g. on arrival and a few hours later) show the trend and improve accuracy.' },
    ] },
  { slug: 'd-dimer', name: 'D-Dimer',
    lede: 'D-dimer is a fragment released when a blood clot breaks down. It is mainly used to help rule OUT a clot (DVT or lung clot) when suspicion is low.',
    rows: [
      ['Normal', '< 0.5 µg/mL FEU (< 500 ng/mL)'],
      ['Raised', '> 0.5 µg/mL FEU'],
    ],
    high: ['A raised D-dimer can indicate a clot, but also rises with infection, inflammation, surgery, pregnancy and age — so it is not specific'],
    low: ['A normal D-dimer, with low clinical suspicion, helps safely rule out a clot'],
    faqs: [
      { q: 'What does a high D-dimer mean?', a: 'It suggests clot breakdown is happening somewhere, but many non-clot causes (infection, surgery, pregnancy) also raise it. A high result usually leads to imaging to look for a clot.' },
      { q: 'Can a normal D-dimer rule out a clot?', a: 'When the clinical suspicion is low, a normal D-dimer makes a DVT or pulmonary embolism very unlikely and can avoid further scans.' },
    ] },
  { slug: 'pt-inr', name: 'PT / INR',
    lede: 'PT (prothrombin time) and its standardised form, INR, measure how quickly your blood clots. INR is used to monitor blood thinners like warfarin.',
    rows: [
      ['PT', '≈ 11–13.5 seconds'],
      ['INR (not on warfarin)', '0.8–1.1'],
      ['INR (typical warfarin target)', '2.0–3.0'],
    ],
    high: ['A high INR means blood is clotting too slowly — higher bleeding risk (over-anticoagulation, liver disease, vitamin K lack)'],
    low: ['A low INR on warfarin means under-treatment — higher clotting risk'],
    faqs: [
      { q: 'What INR should I aim for on warfarin?', a: 'Most people target an INR of 2.0–3.0, though some conditions need a higher range. Your clinic sets and monitors your target and adjusts the dose.' },
      { q: 'What raises my INR unexpectedly?', a: 'Some antibiotics, alcohol, illness, and changes in diet (vitamin K in leafy greens) can shift INR. Regular monitoring catches these changes.' },
    ] },
  { slug: 'psa', name: 'PSA (Prostate-Specific Antigen)',
    lede: 'PSA is a protein made by the prostate. A blood test is used to screen for and monitor prostate conditions, including cancer.',
    rows: [
      ['Commonly used cut-off', '< 4 ng/mL'],
      ['Note', 'Normal rises with age; interpretation is individual'],
    ],
    high: ['A raised PSA can indicate prostate enlargement, infection (prostatitis) or cancer — it is not specific and needs interpretation'],
    low: ['A low PSA is reassuring but does not fully exclude prostate disease'],
    faqs: [
      { q: 'Does a high PSA mean prostate cancer?', a: 'Not necessarily — an enlarged prostate and prostatitis commonly raise PSA. The level, your age, the trend and an exam guide whether further tests are needed.' },
      { q: 'What can falsely raise PSA?', a: 'Recent ejaculation, vigorous cycling, a urine infection, or a recent prostate exam or catheter. Testing is often repeated or timed to avoid these.' },
    ] },
  { slug: 'widal-test-typhoid', name: 'Widal Test (Typhoid)',
    lede: 'The Widal test looks for antibodies against the typhoid bacteria in your blood. It is a supportive test — helpful but with real limitations.',
    rows: [
      ['O antigen titre', 'Significant if ≥ 1:160 (lab-dependent)'],
      ['H antigen titre', 'Significant if ≥ 1:160 (lab-dependent)'],
      ['Best confirmation', 'Blood culture (gold standard)'],
    ],
    high: ['A high or rising titre supports typhoid, especially with fever and matching symptoms'],
    low: ['A low or negative titre early in illness does not fully exclude typhoid — antibodies take time to rise'],
    faqs: [
      { q: 'Is the Widal test reliable for typhoid?', a: 'It is only supportive. It can be falsely positive (past infection, vaccination, other illnesses) or falsely negative early on. A single high titre is weaker than a rising one; blood culture is the gold standard.' },
      { q: 'How is typhoid best diagnosed?', a: 'A blood culture in the first week is the most reliable test. Widal is used where culture is not available, interpreted with symptoms and, ideally, paired samples a week apart.' },
    ] },
  { slug: 'dengue-test', name: 'Dengue Test (NS1, IgM, IgG)',
    lede: 'Dengue is diagnosed with different tests depending on the day of illness: NS1 antigen early, then IgM/IgG antibodies. Platelet counts are watched closely.',
    rows: [
      ['NS1 antigen', 'Best in days 1–5 of fever'],
      ['IgM antibody', 'Positive from ~day 4–5 onward'],
      ['IgG antibody', 'Past or secondary infection'],
      ['Monitor', 'Platelet count & haematocrit'],
    ],
    high: ['A positive NS1 or IgM supports current dengue; a positive IgG with IgM can indicate a secondary (often more severe) infection'],
    low: ['A negative NS1 late in the illness does not exclude dengue — antibody tests are then more useful'],
    faqs: [
      { q: 'Which dengue test should I get and when?', a: 'In the first 5 days of fever, the NS1 antigen is best; from around day 4–5, IgM antibodies become positive. Your day of illness decides the right test.' },
      { q: 'Why are platelets monitored in dengue?', a: 'Dengue can lower platelets and leak fluid from vessels, so serial platelet counts and haematocrit help spot warning signs of severe dengue that need hospital care.' },
    ] },
  { slug: 'malaria-test', name: 'Malaria Test',
    lede: 'Malaria is diagnosed by finding the parasite in the blood — by microscopy (the gold standard) or a rapid antigen test (RDT).',
    rows: [
      ['Blood smear (microscopy)', 'Gold standard; identifies species & load'],
      ['Rapid antigen test (RDT)', 'Fast; positive/negative'],
      ['If negative but suspicious', 'Repeat smears over 48–72 hrs'],
    ],
    high: ['A positive test confirms malaria; microscopy also shows the species and parasite load, which guide treatment'],
    low: ['A single negative test does not exclude malaria — repeat testing is advised if fever continues'],
    faqs: [
      { q: 'How accurate is a rapid malaria test?', a: 'RDTs are quick and useful, but microscopy remains the gold standard as it identifies the species and how many parasites are present. A negative RDT with ongoing fever should prompt repeat smears.' },
      { q: 'When should I get tested for malaria?', a: 'Any fever after being in a malaria region should be tested promptly — malaria can become severe quickly, so early diagnosis matters.' },
    ] },
  { slug: 'hepatitis-b-hbsag', name: 'Hepatitis B (HBsAg)',
    lede: 'HBsAg (hepatitis B surface antigen) is the main screening test for a current hepatitis B infection. A fuller panel shows whether you are infected, immune or a carrier.',
    rows: [
      ['HBsAg', 'Positive = current infection'],
      ['Anti-HBs', 'Positive = immunity (vaccine or past infection)'],
      ['Anti-HBc', 'Marks past or present exposure'],
    ],
    high: ['A positive HBsAg means active hepatitis B — further tests assess the virus level and liver, and it can be transmitted to others'],
    low: ['A negative HBsAg with positive anti-HBs means you are immune and not currently infected'],
    faqs: [
      { q: 'What does a positive HBsAg mean?', a: 'It means you currently have hepatitis B. Follow-up tests (viral load, e-antigen, liver function) show how active it is and whether treatment is needed, and precautions prevent spreading it.' },
      { q: 'Does a positive anti-HBs mean I have hepatitis B?', a: 'No — anti-HBs indicates immunity, usually from vaccination or a cleared past infection. It is the protective antibody, not a sign of current infection.' },
    ] },
  { slug: 'hiv-test', name: 'HIV Test',
    lede: 'An HIV test checks whether you have been infected with the human immunodeficiency virus. Modern tests are highly accurate, and early diagnosis means HIV can be treated so effectively that people live long, healthy lives.',
    rows: [
      ['Non-reactive (negative)', 'No HIV antibodies/antigen detected'],
      ['Reactive (positive)', 'Needs a confirmatory test before diagnosis'],
      ['Window period', 'Up to ~4–12 weeks depending on the test'],
      ['4th-generation test', 'Detects antigen + antibody (earlier detection)'],
    ],
    high: ['A reactive (positive) screening test is always confirmed with a second test before a diagnosis is made', 'If confirmed, early treatment keeps the virus controlled and undetectable'],
    low: ['A non-reactive result usually means no infection', 'If you tested during the early window period, a repeat test may be advised to be sure'],
    faqs: [
      { q: 'How soon after exposure can HIV be detected?', a: 'It depends on the test. Modern 4th-generation tests can detect HIV from about 2–4 weeks, but a test at 6–12 weeks (or as your provider advises) gives the most reliable result.' },
      { q: 'Is a positive HIV screening test a diagnosis?', a: 'No. A reactive screening test must be confirmed with a second, different test. Diagnosis is only made after confirmation.' },
      { q: 'Is HIV testing confidential?', a: 'Yes. Testing is confidential, and in India free testing and counselling are available at ICTC centres. Early diagnosis allows very effective treatment.' },
    ] },
  { slug: 'blood-group-test', name: 'Blood Group Test',
    lede: 'A blood group (blood typing) test tells you which ABO group (A, B, AB or O) and Rh type (positive or negative) you have. It is essential before transfusions, surgery and during pregnancy.',
    rows: [
      ['ABO groups', 'A, B, AB or O'],
      ['Rh factor', 'Positive or negative'],
      ['Universal donor (red cells)', 'O negative'],
      ['Universal recipient', 'AB positive'],
    ],
    high: ['There is no "high" or "low" — your blood group is fixed for life', 'Rh-negative mothers with an Rh-positive baby may need a protective injection in pregnancy'],
    low: ['Knowing your group is vital for safe transfusion — the wrong group can cause a dangerous reaction', 'Carry your blood group details for emergencies'],
    faqs: [
      { q: 'Can my blood group change?', a: 'No. Your ABO and Rh type are determined by your genes and stay the same throughout life (rare exceptions occur after certain bone-marrow transplants).' },
      { q: 'Why does blood group matter in pregnancy?', a: 'If the mother is Rh-negative and the baby is Rh-positive, the mother’s body can react against the baby’s blood. A protective injection (anti-D) prevents problems, so testing early matters.' },
      { q: 'What is the universal donor blood group?', a: 'O-negative red cells can be given to almost anyone in an emergency, which is why O-negative donors are always in demand.' },
    ] },
  { slug: 'ra-factor', name: 'RA Factor (Rheumatoid Factor)',
    lede: 'The rheumatoid factor (RA factor) test looks for an antibody often present in rheumatoid arthritis and some other conditions. It helps assess joint pain, but a positive result alone does not confirm arthritis.',
    rows: [
      ['Normal (negative)', 'typically < 14 IU/mL'],
      ['Weakly positive', 'mildly raised'],
      ['Strongly positive', 'markedly raised'],
    ],
    high: ['A high RA factor supports (but does not prove) rheumatoid arthritis, especially with joint symptoms', 'It can also be raised in other autoimmune and chronic infections', 'Higher levels can suggest more active disease'],
    low: ['A negative result does not fully rule out rheumatoid arthritis — some people have "seronegative" disease', 'The result is always read alongside symptoms and other tests such as anti-CCP and CRP'],
    faqs: [
      { q: 'Does a positive RA factor mean I have rheumatoid arthritis?', a: 'Not on its own. RA factor can be positive in healthy people and in other conditions. Doctors combine it with your symptoms, examination and tests like anti-CCP and CRP.' },
      { q: 'Can RA factor be negative in arthritis?', a: 'Yes. Some people with genuine rheumatoid arthritis are RA-factor negative (seronegative). This is why the test is only one piece of the picture.' },
      { q: 'What other tests go with RA factor?', a: 'Anti-CCP antibodies, ESR and CRP (for inflammation) and joint X-rays are commonly used together to assess rheumatoid arthritis.' },
    ] },
  { slug: 'amylase-lipase', name: 'Amylase & Lipase',
    lede: 'Amylase and lipase are enzymes made mainly by the pancreas. Raised levels — especially lipase — are used to help diagnose pancreatitis (inflammation of the pancreas) in someone with abdominal pain.',
    rows: [
      ['Amylase', '≈ 30–110 U/L'],
      ['Lipase', '≈ 0–160 U/L'],
      ['Pancreatitis', 'often raised 3× or more above normal'],
    ],
    high: ['Markedly high lipase/amylase with abdominal pain suggests acute pancreatitis', 'Milder rises can occur with gallstones, some medicines or other abdominal problems', 'Lipase is more specific to the pancreas than amylase'],
    low: ['Low levels are usually not a concern', 'Very low levels can occasionally reflect long-standing pancreas damage'],
    faqs: [
      { q: 'What do high amylase and lipase mean?', a: 'They point towards pancreatitis when there is matching abdominal pain, but can also rise for other reasons. A doctor interprets them with your symptoms and scans.' },
      { q: 'Which is better, amylase or lipase?', a: 'Lipase is more specific to the pancreas and stays raised longer, so it is often the preferred test for suspected pancreatitis.' },
      { q: 'Do I need to fast for this test?', a: 'Usually no special preparation is needed, but avoid alcohol beforehand and follow any instructions your lab gives.' },
    ] },
  { slug: 'prolactin', name: 'Prolactin',
    lede: 'Prolactin is a hormone from the pituitary gland. It is tested for irregular periods, infertility, milk discharge from the breast, or low libido. Levels naturally rise in pregnancy and breastfeeding.',
    rows: [
      ['Women (non-pregnant)', '≈ 4–23 ng/mL'],
      ['Men', '≈ 3–15 ng/mL'],
      ['Pregnancy / breastfeeding', 'naturally much higher'],
    ],
    high: ['High prolactin can stop periods, cause milk discharge and reduce fertility', 'Causes include stress, certain medicines, an underactive thyroid, or a small pituitary growth (prolactinoma)', 'Very high levels usually need imaging of the pituitary'],
    low: ['Low prolactin is uncommon and rarely causes problems on its own', 'It may occasionally reflect reduced pituitary function'],
    faqs: [
      { q: 'What causes high prolactin?', a: 'Common causes are stress, certain medicines, an underactive thyroid, pregnancy/breastfeeding and a benign pituitary tumour (prolactinoma). The test is repeated and investigated as needed.' },
      { q: 'How should I prepare for a prolactin test?', a: 'Levels rise with stress, exercise, sleep and breast stimulation, so labs often draw the sample later in the morning after resting. Follow your lab’s advice.' },
      { q: 'Can high prolactin affect fertility?', a: 'Yes. High prolactin can disturb ovulation and periods in women and lower testosterone in men, both of which can affect fertility — and it is often treatable.' },
    ] },
  { slug: 'vdrl-syphilis', name: 'VDRL (Syphilis Test)',
    lede: 'The VDRL test screens for syphilis, a sexually transmitted infection. It is often done in pregnancy and sexual-health checks. A reactive result is always confirmed with a more specific test.',
    rows: [
      ['Non-reactive', 'No sign of syphilis infection'],
      ['Reactive', 'Needs a confirmatory test (e.g. TPHA/FTA-ABS)'],
      ['Titre (e.g. 1:8, 1:32)', 'Higher titres suggest active infection'],
    ],
    high: ['A reactive VDRL with a high titre suggests active syphilis needing treatment', 'Titres are used to monitor response to treatment (they should fall)'],
    low: ['A non-reactive result usually means no syphilis, but very early or very late infection can occasionally be missed', 'False-reactive results can occur, which is why confirmation is essential'],
    faqs: [
      { q: 'Is a reactive VDRL a definite diagnosis of syphilis?', a: 'No. VDRL is a screening test and can occasionally be falsely reactive. A specific confirmatory test (such as TPHA or FTA-ABS) is always done before diagnosis.' },
      { q: 'Why is VDRL done in pregnancy?', a: 'Untreated syphilis can seriously harm the baby, and it is easily treatable, so screening in pregnancy is routine and important.' },
      { q: 'Can syphilis be cured?', a: 'Yes. Syphilis is curable with the right antibiotics, especially when caught early. Partners usually need testing and treatment too.' },
    ] },
  { slug: 'metabolic-panel', name: 'Metabolic Panel (CMP/BMP)',
    lede: 'A metabolic panel is a group of blood tests that check your blood sugar, kidney function, and salts (electrolytes) — and, in the comprehensive version, your liver and proteins too. It gives a broad snapshot of body chemistry.',
    rows: [
      ['Glucose', '70–99 mg/dL (fasting)'],
      ['Sodium', '135–145 mmol/L'],
      ['Potassium', '3.5–5.1 mmol/L'],
      ['Creatinine', '0.6–1.3 mg/dL'],
      ['Blood urea (BUN)', '7–20 mg/dL'],
    ],
    high: ['High glucose can indicate diabetes; high creatinine/urea can reflect reduced kidney function', 'Abnormal salts (sodium/potassium) can affect the heart and nerves and may need prompt attention'],
    low: ['Low glucose (hypoglycaemia) can cause shakiness and confusion', 'Low sodium or potassium can cause weakness, cramps or heart-rhythm problems'],
    faqs: [
      { q: 'What is the difference between a BMP and a CMP?', a: 'A basic metabolic panel (BMP) checks sugar, kidney function and electrolytes. A comprehensive one (CMP) adds liver tests and proteins. Your doctor chooses based on what they need to know.' },
      { q: 'Do I need to fast for a metabolic panel?', a: 'Often yes, mainly for an accurate glucose reading. Your lab will tell you whether an 8–12 hour fast is needed.' },
      { q: 'What does a metabolic panel screen for?', a: 'It screens for diabetes, kidney problems, salt imbalances and (in the comprehensive version) liver problems — a broad first-line health check.' },
    ] },
];

export { LAB_NOTE };
