// Department / speciality pages for /ask/<slug>/.
// Each department is rebuilt as a rich page: conditions treated, common symptoms
// (linked to /symptoms/ pages), tests & procedures (linked to /blood-tests/ and
// imaging pages), when to see the specialist, and FAQs.
//
// symptoms / tests items are [href|null, label]:
//   href null  -> plain text bullet (no page for it yet)
//   href set   -> internal link to /<href>/  (must be an existing slug)
// Consumed by gen-landing.mjs.

export const DEPARTMENTS = [
  // ---------------------------------------------------------------- medicine
  { slug: 'general-medicine', label: 'General Medicine (Physician)',
    lede: 'A general physician (internal medicine doctor) is the first port of call for adult health — diagnosing everyday illnesses, managing long-term conditions, and referring you to the right specialist when needed.',
    conditions: ['Fever and common infections', 'High blood pressure (hypertension)', 'Type 2 diabetes', 'Thyroid disorders', 'High cholesterol', 'Anaemia', 'Routine health check-ups and preventive care'],
    symptoms: [['symptoms/fever', 'Fever'], ['symptoms/fatigue', 'Fatigue & tiredness'], ['symptoms/headache', 'Headache'], ['symptoms/dizziness', 'Dizziness'], ['symptoms/unexplained-weight-loss', 'Unexplained weight loss']],
    tests: [['blood-tests/complete-blood-count-cbc', 'CBC'], ['blood-tests/fasting-blood-sugar', 'Blood sugar'], ['blood-tests/hba1c', 'HbA1c'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], ['blood-tests/thyroid-function-test-tft', 'Thyroid (TFT)']],
    whenToSee: ['A fever or illness that is not settling', 'A new long-term problem like high BP or diabetes needing management', 'Several vague symptoms that need a first assessment and the right referral'],
    faqs: [
      { q: 'What does a general physician treat?', a: 'Adults’ everyday illnesses and chronic diseases — infections, blood pressure, diabetes, thyroid, cholesterol and more — and they coordinate referrals to specialists when needed.' },
      { q: 'When should I see a physician vs a specialist?', a: 'Start with a general physician for undiagnosed or general problems; they will refer you to the right specialist if your condition needs focused care.' },
    ] },
  { slug: 'cardiology', label: 'Cardiology',
    lede: 'Cardiologists diagnose and treat conditions of the heart and blood vessels — from chest pain and blood pressure to rhythm problems and heart failure.',
    conditions: ['Coronary artery disease & heart attack', 'Angina', 'High blood pressure (hypertension)', 'Heart failure', 'Arrhythmias (e.g. atrial fibrillation)', 'High cholesterol', 'Heart valve disease'],
    symptoms: [['symptoms/chest-pain', 'Chest pain'], ['symptoms/heart-palpitations', 'Palpitations'], ['symptoms/shortness-of-breath', 'Breathlessness'], ['symptoms/leg-swelling', 'Leg swelling'], ['symptoms/fainting', 'Fainting']],
    tests: [['ecg-explained', 'ECG'], ['blood-tests/troponin', 'Troponin'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], [null, 'Echocardiogram'], [null, 'Angiography / TMT']],
    whenToSee: ['Chest pain on exertion, or pressure spreading to the arm/jaw (emergency if severe)', 'Palpitations with fainting or breathlessness', 'Breathlessness or leg swelling that is worsening', 'Uncontrolled blood pressure'],
    faqs: [
      { q: 'What is the difference between a heart attack and angina?', a: 'Angina is chest pain from reduced blood flow that eases with rest; a heart attack is a blockage causing lasting damage and is an emergency. Sudden severe chest pain needs urgent care.' },
      { q: 'Can MedDroid read my ECG?', a: 'Yes — attach it and MedDroid explains the rate, rhythm and features in plain words. It is educational; a cardiologist confirms on the actual tracing.' },
    ] },
  { slug: 'neurology', label: 'Neurology',
    lede: 'Neurologists treat conditions of the brain, spinal cord and nerves — headaches, seizures, stroke, and disorders affecting movement, memory and sensation.',
    conditions: ['Migraine & chronic headache', 'Stroke & TIA', 'Epilepsy (seizures)', 'Parkinson’s disease', 'Multiple sclerosis', 'Peripheral neuropathy', 'Dementia & memory disorders'],
    symptoms: [['symptoms/headache', 'Headache'], ['symptoms/dizziness', 'Dizziness'], ['symptoms/numbness-and-tingling', 'Numbness & tingling'], ['symptoms/fainting', 'Fainting'], ['symptoms/blurred-vision', 'Blurred vision']],
    tests: [['mri-scan-explained', 'MRI brain'], [null, 'CT scan'], [null, 'EEG'], [null, 'Nerve conduction study'], ['blood-tests/vitamin-b12', 'Vitamin B12']],
    whenToSee: ['Sudden weakness, face droop or slurred speech — an emergency (stroke)', 'A sudden “worst-ever” headache', 'A first seizure, or seizures that change', 'Progressive numbness, weakness or memory loss'],
    faqs: [
      { q: 'How do I recognise a stroke?', a: 'Use FAST — Face droop, Arm weakness, Speech difficulty, Time to call emergency services. Stroke is a medical emergency; act immediately.' },
      { q: 'When should a headache see a neurologist?', a: 'Frequent, severe or changing headaches, or headaches with neurological signs (weakness, vision changes, seizures), warrant a neurology review.' },
    ] },
  { slug: 'gastroenterology', label: 'Gastroenterology',
    lede: 'Gastroenterologists treat the digestive system — stomach, intestines, liver, pancreas and gallbladder — from acidity and IBS to ulcers and liver disease.',
    conditions: ['Acid reflux (GERD) & gastritis', 'Peptic ulcers', 'Irritable bowel syndrome (IBS)', 'Inflammatory bowel disease (Crohn’s, colitis)', 'Fatty liver & hepatitis', 'Gallstones', 'Piles (haemorrhoids)'],
    symptoms: [['symptoms/abdominal-pain', 'Abdominal pain'], ['symptoms/heartburn', 'Heartburn'], ['symptoms/bloating', 'Bloating'], ['symptoms/diarrhea', 'Diarrhea'], ['symptoms/constipation', 'Constipation'], ['symptoms/blood-in-stool', 'Blood in stool']],
    tests: [['blood-tests/liver-function-test-lft', 'Liver function (LFT)'], [null, 'Endoscopy'], [null, 'Colonoscopy'], [null, 'Ultrasound abdomen'], ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B']],
    whenToSee: ['Vomiting blood, or black/tarry stools — urgent', 'Blood in the stool or a persistent change in bowel habit', 'Difficulty swallowing or unexplained weight loss', 'Persistent abdominal pain or reflux not settling'],
    faqs: [
      { q: 'What does a gastroenterologist do?', a: 'They diagnose and treat digestive and liver conditions, and perform procedures like endoscopy and colonoscopy to look inside the gut.' },
      { q: 'When is acidity a reason to see a specialist?', a: 'If reflux is frequent, not settling with treatment, or comes with trouble swallowing, weight loss or bleeding, a gastroenterologist should assess it.' },
    ] },
  { slug: 'endocrinology', label: 'Endocrinology (Diabetes & Thyroid)',
    lede: 'Endocrinologists treat hormone and gland disorders — diabetes, thyroid disease, and problems of the adrenal, pituitary and reproductive hormones.',
    conditions: ['Type 1 & type 2 diabetes', 'Thyroid disorders (under/overactive)', 'PCOS', 'Osteoporosis', 'Adrenal disorders', 'Pituitary disorders', 'Obesity & metabolic syndrome'],
    symptoms: [['symptoms/fatigue', 'Fatigue'], ['symptoms/unexplained-weight-loss', 'Weight loss'], ['symptoms/frequent-urination', 'Frequent urination'], ['symptoms/heart-palpitations', 'Palpitations']],
    tests: [['blood-tests/fasting-blood-sugar', 'Fasting sugar'], ['blood-tests/hba1c', 'HbA1c'], ['blood-tests/thyroid-function-test-tft', 'Thyroid (TFT)'], ['blood-tests/tsh', 'TSH'], ['blood-tests/cortisol', 'Cortisol'], ['blood-tests/vitamin-d', 'Vitamin D']],
    whenToSee: ['High blood sugar or a new diabetes diagnosis needing management', 'Thyroid symptoms (weight, energy, heart-rate changes)', 'Irregular periods with acne/excess hair (possible PCOS)', 'Very high or very low readings on hormone tests'],
    faqs: [
      { q: 'What is the difference between an endocrinologist and a diabetologist?', a: 'A diabetologist focuses on diabetes; an endocrinologist covers all hormone glands, including diabetes, thyroid, adrenal and pituitary conditions.' },
      { q: 'What tests check thyroid and diabetes?', a: 'TSH (and T4/T3) for thyroid; fasting glucose and HbA1c for diabetes. MedDroid can explain your results in plain language.' },
    ] },
  { slug: 'pulmonology', label: 'Pulmonology',
    lede: 'Pulmonologists (chest physicians) treat the lungs and airways — asthma, COPD, infections, and breathing problems.',
    conditions: ['Asthma', 'COPD', 'Pneumonia & chest infections', 'Tuberculosis (in some regions)', 'Sleep apnoea', 'Interstitial lung disease', 'Chronic cough'],
    symptoms: [['symptoms/cough', 'Cough'], ['symptoms/shortness-of-breath', 'Breathlessness'], ['symptoms/wheezing', 'Wheezing'], ['symptoms/chest-pain', 'Chest pain']],
    tests: [['x-ray-explained', 'Chest X-ray'], [null, 'Spirometry (lung function)'], [null, 'CT chest'], ['blood-tests/complete-blood-count-cbc', 'CBC'], ['blood-tests/crp', 'CRP']],
    whenToSee: ['Severe or sudden breathlessness, or blue lips — emergency', 'Coughing blood', 'A cough lasting over 3 weeks', 'Wheeze or breathlessness not controlled by inhalers'],
    faqs: [
      { q: 'What does a pulmonologist treat?', a: 'Lung and airway conditions — asthma, COPD, chest infections, sleep apnoea and chronic cough — using tests like spirometry and chest imaging.' },
      { q: 'When should a cough be checked by a specialist?', a: 'A cough lasting more than 3 weeks, or with blood, weight loss or breathlessness, should be investigated by a chest physician.' },
    ] },
  { slug: 'nephrology', label: 'Nephrology',
    lede: 'Nephrologists treat the kidneys — chronic kidney disease, high blood pressure, electrolyte problems and dialysis care.',
    conditions: ['Chronic kidney disease (CKD)', 'Acute kidney injury', 'Kidney stones (medical care)', 'High blood pressure related to kidneys', 'Glomerulonephritis', 'Electrolyte imbalances', 'Dialysis & transplant care'],
    symptoms: [['symptoms/leg-swelling', 'Leg/ankle swelling'], ['symptoms/blood-in-urine', 'Blood in urine'], ['symptoms/frequent-urination', 'Frequent urination'], ['symptoms/fatigue', 'Fatigue']],
    tests: [['blood-tests/creatinine', 'Creatinine'], ['blood-tests/kidney-function-test-rft', 'Kidney function (RFT)'], ['blood-tests/blood-urea-bun', 'Blood urea'], ['blood-tests/electrolytes', 'Electrolytes'], ['blood-tests/potassium', 'Potassium']],
    whenToSee: ['A rising creatinine or falling eGFR', 'Swelling with reduced urine output', 'Blood or heavy protein in the urine', 'Very high potassium or other electrolyte problems'],
    faqs: [
      { q: 'What does a high creatinine mean?', a: 'It suggests the kidneys are filtering less well. A nephrologist interprets it with eGFR and urine tests to find the cause and slow any kidney disease.' },
      { q: 'How can I protect my kidneys?', a: 'Control blood pressure and sugar, stay hydrated, avoid overusing certain painkillers, and have kidney function checked if you are at risk.' },
    ] },
  { slug: 'rheumatology', label: 'Rheumatology',
    lede: 'Rheumatologists treat joints, muscles and autoimmune conditions — arthritis, gout, lupus and inflammatory disease.',
    conditions: ['Rheumatoid arthritis', 'Osteoarthritis', 'Gout', 'Lupus (SLE)', 'Ankylosing spondylitis', 'Psoriatic arthritis', 'Fibromyalgia'],
    symptoms: [['symptoms/joint-pain', 'Joint pain'], ['symptoms/back-pain', 'Back pain'], ['symptoms/neck-pain', 'Neck pain'], ['symptoms/fatigue', 'Fatigue']],
    tests: [['blood-tests/crp', 'CRP'], ['blood-tests/esr', 'ESR'], ['blood-tests/uric-acid', 'Uric acid'], [null, 'RA factor / anti-CCP'], [null, 'ANA (autoimmune)']],
    whenToSee: ['A hot, red, swollen joint with fever — urgent (possible infection)', 'Joint pain with prolonged morning stiffness', 'Joint pain with a rash or feeling very unwell', 'Persistent joint pain not improving'],
    faqs: [
      { q: 'What is the difference between osteoarthritis and rheumatoid arthritis?', a: 'Osteoarthritis is wear-and-tear, worse with use; rheumatoid arthritis is autoimmune, symmetrical, with long morning stiffness. Blood tests help tell them apart.' },
      { q: 'What blood tests are used in rheumatology?', a: 'Inflammation markers (CRP, ESR), uric acid for gout, and autoimmune tests like RA factor, anti-CCP and ANA — read alongside your symptoms.' },
    ] },
  { slug: 'infectious-diseases', label: 'Infectious Diseases',
    lede: 'Infectious-disease specialists diagnose and treat complex or persistent infections, guide antibiotic use, and advise on travel and prevention.',
    conditions: ['Typhoid, dengue & malaria', 'Tuberculosis', 'Hepatitis B & C', 'HIV', 'Sepsis', 'Persistent or unusual fevers', 'Travel-related infections'],
    symptoms: [['symptoms/fever', 'Fever'], ['symptoms/night-sweats', 'Night sweats'], ['symptoms/swollen-lymph-nodes', 'Swollen glands'], ['symptoms/cough', 'Cough'], ['symptoms/diarrhea', 'Diarrhea']],
    tests: [['blood-tests/complete-blood-count-cbc', 'CBC'], ['blood-tests/widal-test-typhoid', 'Widal (typhoid)'], ['blood-tests/dengue-test', 'Dengue test'], ['blood-tests/malaria-test', 'Malaria test'], ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B'], ['blood-tests/crp', 'CRP']],
    whenToSee: ['High fever with confusion, a stiff neck or a non-fading rash — emergency', 'Fever lasting more than 5–7 days', 'Fever after travel to a malaria/dengue region', 'Persistent night sweats and weight loss'],
    faqs: [
      { q: 'Do I always need antibiotics for an infection?', a: 'No — many infections are viral and do not respond to antibiotics. A specialist helps decide when they are truly needed to avoid resistance.' },
      { q: 'What tests diagnose typhoid, dengue and malaria?', a: 'Blood culture (best) or Widal for typhoid; NS1/IgM for dengue; blood smear or rapid test for malaria — chosen by the day of illness and symptoms.' },
    ] },
  { slug: 'allergy-immunology', label: 'Allergy & Immunology',
    lede: 'Allergy and immunology specialists diagnose and manage allergies, asthma and disorders of the immune system.',
    conditions: ['Allergic rhinitis (hay fever)', 'Food allergies', 'Drug allergies', 'Eczema & hives', 'Asthma (allergic)', 'Anaphylaxis', 'Immune deficiency disorders'],
    symptoms: [['symptoms/skin-rash', 'Skin rash'], ['symptoms/itching', 'Itching'], ['symptoms/wheezing', 'Wheezing'], ['symptoms/shortness-of-breath', 'Breathlessness']],
    tests: [[null, 'Skin-prick allergy test'], [null, 'Specific IgE blood test'], ['blood-tests/complete-blood-count-cbc', 'CBC (eosinophils)'], [null, 'Patch testing']],
    whenToSee: ['Lip/throat swelling or difficulty breathing (anaphylaxis) — emergency', 'A severe reaction to a food, sting or medicine', 'Recurrent hives or eczema not controlled', 'Frequent or unusual infections (immune concern)'],
    faqs: [
      { q: 'How are allergies diagnosed?', a: 'Through your history plus skin-prick or specific-IgE blood tests to identify triggers. A specialist interprets these together with your symptoms.' },
      { q: 'What should I do in a severe allergic reaction?', a: 'Anaphylaxis (swelling, breathing trouble, collapse) is an emergency — use an adrenaline auto-injector if prescribed and call emergency services immediately.' },
    ] },
  // ------------------------------------------------------------- surgical
  { slug: 'general-surgery', label: 'General Surgery',
    lede: 'General surgeons operate on a wide range of conditions — appendicitis, hernias, gallstones, and abdominal and skin problems needing surgery.',
    conditions: ['Appendicitis', 'Hernias', 'Gallstones (cholecystectomy)', 'Piles, fissures & fistula', 'Abscesses & skin lumps', 'Thyroid & breast lumps', 'Bowel conditions'],
    symptoms: [['symptoms/abdominal-pain', 'Abdominal pain'], ['symptoms/bloating', 'Bloating'], ['symptoms/blood-in-stool', 'Blood in stool'], ['symptoms/swollen-lymph-nodes', 'Lumps / swellings']],
    tests: [['x-ray-explained', 'X-ray'], [null, 'Ultrasound'], [null, 'CT scan'], ['blood-tests/complete-blood-count-cbc', 'CBC'], [null, 'Biopsy']],
    whenToSee: ['Severe sudden abdominal pain with a rigid tummy — emergency', 'A painful, irreducible or tender lump/hernia', 'A lump that is growing or hard', 'Right-lower abdominal pain with fever (appendicitis)'],
    faqs: [
      { q: 'What conditions need general surgery?', a: 'Common ones include appendicitis, hernias, gallstones and piles, plus removal of lumps. Many are now done by keyhole (laparoscopic) surgery.' },
      { q: 'What is keyhole surgery?', a: 'Laparoscopic (keyhole) surgery uses small cuts and a camera, usually meaning less pain and faster recovery than open surgery for suitable operations.' },
    ] },
  { slug: 'orthopedics', label: 'Orthopedics',
    lede: 'Orthopaedic surgeons treat bones, joints, muscles and ligaments — fractures, arthritis, sports injuries and spine problems.',
    conditions: ['Fractures & dislocations', 'Osteoarthritis (joint replacement)', 'Sports injuries (ACL, meniscus)', 'Back & neck problems', 'Frozen shoulder', 'Carpal tunnel syndrome', 'Osteoporosis-related fractures'],
    symptoms: [['symptoms/joint-pain', 'Joint pain'], ['symptoms/back-pain', 'Back pain'], ['symptoms/neck-pain', 'Neck pain'], ['symptoms/numbness-and-tingling', 'Numbness & tingling']],
    tests: [['x-ray-explained', 'X-ray'], ['mri-scan-explained', 'MRI'], [null, 'CT scan'], ['blood-tests/uric-acid', 'Uric acid'], ['blood-tests/vitamin-d', 'Vitamin D']],
    whenToSee: ['A bone that looks deformed or cannot bear weight after injury', 'Back pain with leg weakness or bladder/bowel changes — urgent', 'A joint that is hot, red and swollen with fever', 'Persistent joint pain limiting daily life'],
    faqs: [
      { q: 'When do I need a joint replacement?', a: 'When arthritis pain and stiffness limit daily life despite medication, physiotherapy and lifestyle measures, an orthopaedic surgeon may discuss joint replacement.' },
      { q: 'Can MedDroid explain my X-ray or MRI?', a: 'Yes — attach it and MedDroid describes what it appears to show in plain words. It is educational; a radiologist and your surgeon confirm.' },
    ] },
  { slug: 'urology', label: 'Urology',
    lede: 'Urologists treat the urinary tract in men and women and the male reproductive system — stones, infections, prostate and bladder problems.',
    conditions: ['Kidney & bladder stones', 'Urinary tract infections', 'Enlarged prostate (BPH)', 'Prostate cancer', 'Bladder problems & incontinence', 'Blood in urine', 'Male infertility & erectile issues'],
    symptoms: [['symptoms/painful-urination', 'Painful urination'], ['symptoms/blood-in-urine', 'Blood in urine'], ['symptoms/frequent-urination', 'Frequent urination']],
    tests: [['blood-tests/psa', 'PSA (prostate)'], ['blood-tests/creatinine', 'Creatinine'], [null, 'Urine test / culture'], [null, 'Ultrasound KUB'], [null, 'Cystoscopy']],
    whenToSee: ['Inability to pass urine, or passing clots with severe pain — urgent', 'Any visible blood in the urine — always get checked', 'A UTI with fever and flank pain (kidney infection)', 'A rising PSA or prostate symptoms'],
    faqs: [
      { q: 'Is painless blood in urine serious?', a: 'It must always be investigated, as it can be an early sign of a bladder or kidney tumour — even if it happens only once and without pain.' },
      { q: 'When should men check their prostate?', a: 'Discuss PSA testing with a urologist if you have urinary symptoms (weak stream, night-time frequency) or from around age 50 (earlier with family history).' },
    ] },
  { slug: 'ent', label: 'ENT (Ear, Nose & Throat)',
    lede: 'ENT surgeons treat ear, nose, throat, sinus and neck conditions — from infections and hearing loss to sinus and voice problems.',
    conditions: ['Ear infections & hearing loss', 'Sinusitis & nasal blockage', 'Tonsillitis', 'Vertigo (inner ear)', 'Tinnitus', 'Voice & swallowing problems', 'Neck lumps'],
    symptoms: [['symptoms/ear-pain', 'Ear pain'], ['symptoms/sore-throat', 'Sore throat'], ['symptoms/dizziness', 'Dizziness / vertigo'], ['symptoms/swollen-lymph-nodes', 'Neck swelling']],
    tests: [[null, 'Hearing test (audiometry)'], [null, 'Nasal endoscopy'], [null, 'CT sinuses'], ['blood-tests/complete-blood-count-cbc', 'CBC']],
    whenToSee: ['Difficulty breathing or swallowing — emergency', 'Sudden hearing loss', 'A neck lump lasting more than 2–3 weeks', 'A hoarse voice lasting over 3 weeks'],
    faqs: [
      { q: 'What causes ringing in the ears (tinnitus)?', a: 'Common causes include wax, hearing loss, noise exposure and ear infections. An ENT can find the cause and advise on management.' },
      { q: 'When do tonsils need removal?', a: 'Recurrent severe tonsillitis, breathing problems in sleep, or complications may lead an ENT surgeon to recommend tonsillectomy.' },
    ] },
  { slug: 'ophthalmology', label: 'Ophthalmology',
    lede: 'Ophthalmologists (eye surgeons) treat eye and vision conditions — cataracts, glaucoma, diabetic eye disease and eye injuries.',
    conditions: ['Cataract', 'Glaucoma', 'Diabetic retinopathy', 'Refractive errors (glasses/LASIK)', 'Conjunctivitis & eye infections', 'Dry eyes', 'Retinal problems'],
    symptoms: [['symptoms/blurred-vision', 'Blurred vision'], ['symptoms/headache', 'Headache (eye strain)']],
    tests: [[null, 'Vision & refraction test'], [null, 'Eye-pressure (tonometry)'], [null, 'Retinal / fundus exam'], ['blood-tests/fasting-blood-sugar', 'Blood sugar (diabetes)']],
    whenToSee: ['Sudden vision loss or a “curtain” over vision — emergency', 'Severe eye pain with redness and nausea', 'Flashes with a shower of new floaters', 'An eye injury or chemical splash'],
    faqs: [
      { q: 'How often should diabetics have eye checks?', a: 'At least once a year — diabetes can silently damage the retina, and early treatment protects sight. Sudden vision change needs prompt review.' },
      { q: 'Is cataract surgery safe?', a: 'Cataract surgery is one of the most common and successful operations, usually restoring clear vision. Your ophthalmologist advises on timing.' },
    ] },
  // ------------------------------------------------------- women / children
  { slug: 'gynaecology', label: 'Gynaecology & Obstetrics',
    lede: 'Gynaecologists and obstetricians care for women’s reproductive health and pregnancy — periods, fertility, pregnancy and menopause.',
    conditions: ['Menstrual problems', 'PCOS', 'Pregnancy & antenatal care', 'Fibroids', 'Endometriosis', 'Menopause', 'Vaginal infections'],
    symptoms: [['symptoms/pelvic-pain', 'Pelvic pain'], ['symptoms/abdominal-pain', 'Abdominal pain'], ['symptoms/painful-urination', 'Painful urination']],
    tests: [['blood-tests/beta-hcg-pregnancy', 'Beta hCG (pregnancy)'], [null, 'Pelvic ultrasound'], ['blood-tests/thyroid-function-test-tft', 'Thyroid'], ['blood-tests/hemoglobin', 'Haemoglobin'], [null, 'Pap smear']],
    whenToSee: ['Severe pelvic pain with a positive pregnancy test — emergency (possible ectopic)', 'Heavy bleeding with dizziness', 'Bleeding after menopause', 'Pain with fever and abnormal discharge'],
    faqs: [
      { q: 'When should I see a gynaecologist about my periods?', a: 'If periods are very heavy, very painful, irregular, or stop unexpectedly — or for bleeding after menopause — a gynaecologist should assess you.' },
      { q: 'What is antenatal (pregnancy) care?', a: 'Regular check-ups, scans and tests through pregnancy to keep mother and baby healthy and catch problems early. Some symptoms in pregnancy need urgent review.' },
    ] },
  { slug: 'paediatrics', label: 'Paediatrics',
    lede: 'Paediatricians care for the health of babies, children and teenagers — infections, growth, vaccinations and childhood conditions.',
    conditions: ['Childhood fever & infections', 'Cough, cold & asthma', 'Diarrhoea & dehydration', 'Growth & nutrition problems', 'Vaccination', 'Newborn care', 'Childhood allergies'],
    symptoms: [['symptoms/fever', 'Fever'], ['symptoms/cough', 'Cough'], ['symptoms/diarrhea', 'Diarrhea'], ['symptoms/skin-rash', 'Rash'], ['symptoms/ear-pain', 'Ear pain']],
    tests: [['blood-tests/complete-blood-count-cbc', 'CBC'], ['blood-tests/dengue-test', 'Dengue test'], ['blood-tests/malaria-test', 'Malaria test'], ['blood-tests/hemoglobin', 'Haemoglobin']],
    whenToSee: ['Difficulty breathing, a non-fading rash, drowsiness or dehydration — emergency', 'Fever in a baby under 3 months', 'A child who is not drinking or is very lethargic', 'Poor growth or feeding concerns'],
    faqs: [
      { q: 'My child has a fever — when should I worry?', a: 'Seek urgent care for breathing difficulty, a non-fading rash, drowsiness, dehydration, or any fever in a baby under 3 months. When in doubt with a child, get seen.' },
      { q: 'Are childhood vaccinations safe?', a: 'Vaccines are among the safest, most effective ways to protect children from serious diseases. Your paediatrician can explain the schedule and any concerns.' },
    ] },
  // -------------------------------------------------------------- cancer
  { slug: 'oncology', label: 'Oncology & Haematology',
    lede: 'Oncologists and haematologists diagnose and treat cancers and blood disorders — with chemotherapy, targeted therapy and blood-disease care.',
    conditions: ['Common cancers (breast, lung, colon, etc.)', 'Blood cancers (leukaemia, lymphoma)', 'Anaemia & blood disorders', 'Clotting & bleeding disorders', 'Chemotherapy & targeted therapy', 'Cancer screening', 'Palliative & supportive care'],
    symptoms: [['symptoms/unexplained-weight-loss', 'Weight loss'], ['symptoms/night-sweats', 'Night sweats'], ['symptoms/swollen-lymph-nodes', 'Swollen glands'], ['symptoms/fatigue', 'Fatigue'], ['symptoms/blood-in-stool', 'Blood in stool']],
    tests: [['blood-tests/complete-blood-count-cbc', 'CBC'], [null, 'Biopsy'], [null, 'CT / PET scan'], [null, 'Tumour markers'], ['blood-tests/ferritin-iron-studies', 'Iron studies']],
    whenToSee: ['A new, hard, painless lump that is growing', 'Unexplained weight loss with night sweats', 'Unusual bleeding or bruising', 'A change in bowel or bladder habit that persists'],
    faqs: [
      { q: 'Can MedDroid explain my biopsy or pathology report?', a: 'Yes — it translates the terms into plain language and what they generally mean. It is educational, not a diagnosis; your oncologist interprets it fully.' },
      { q: 'What is the difference between oncology and haematology?', a: 'Oncology treats cancers of organs; haematology treats blood disorders and blood cancers (like leukaemia). They often work together.' },
    ] },
  // -------------------------------------------------------- skin / dental
  { slug: 'dermatology', label: 'Dermatology',
    lede: 'Dermatologists treat the skin, hair and nails — acne, rashes, infections, hair loss and skin cancer.',
    conditions: ['Acne', 'Eczema & psoriasis', 'Fungal & bacterial skin infections', 'Hair loss', 'Pigmentation problems', 'Moles & skin cancer', 'Hives & allergic rashes'],
    symptoms: [['symptoms/skin-rash', 'Skin rash'], ['symptoms/itching', 'Itching']],
    tests: [[null, 'Skin examination / dermoscopy'], [null, 'Skin biopsy'], [null, 'Fungal scraping'], [null, 'Patch/allergy testing']],
    whenToSee: ['A mole that is changing, bleeding or growing', 'A rapidly spreading, hot, painful red area with fever', 'Widespread blistering or peeling skin — urgent', 'Persistent acne, rash or hair loss affecting you'],
    faqs: [
      { q: 'How do I know if a mole is dangerous?', a: 'Watch for the ABCDE signs — Asymmetry, irregular Border, multiple Colours, large Diameter, and Evolving change. Any of these should be seen by a dermatologist.' },
      { q: 'Can MedDroid look at a photo of my skin?', a: 'Yes — attach a clear photo and MedDroid describes what it appears to show and common possibilities. It cannot diagnose; changing or worrying lesions need a dermatologist.' },
    ] },
  { slug: 'dentistry', label: 'Dentistry',
    lede: 'Dentists care for teeth, gums and the mouth — cavities, toothache, gum disease, and dental procedures.',
    conditions: ['Tooth decay (cavities)', 'Toothache & abscess', 'Gum disease (gingivitis)', 'Wisdom-tooth problems', 'Root canal & fillings', 'Braces / orthodontics', 'Oral ulcers'],
    symptoms: [['symptoms/ear-pain', 'Jaw / referred pain']],
    tests: [[null, 'Dental X-ray'], [null, 'Oral examination']],
    whenToSee: ['Facial swelling with a toothache and fever — prompt care', 'A knocked-out or broken tooth (dental emergency)', 'Severe or throbbing toothache', 'Bleeding gums or a mouth ulcer lasting over 2 weeks'],
    faqs: [
      { q: 'How do I relieve a toothache before I can see a dentist?', a: 'Rinse with warm salt water, use appropriate pain relief, and avoid very hot/cold foods. A persistent or severe toothache, or facial swelling, needs prompt dental care.' },
      { q: 'How often should I see a dentist?', a: 'A check-up every 6–12 months helps catch decay and gum disease early. See one sooner for pain, swelling or bleeding gums.' },
    ] },
  // --------------------------------------------------------------- mind
  { slug: 'psychiatry', label: 'Psychiatry & Mental Health',
    lede: 'Psychiatrists are doctors who diagnose and treat mental-health conditions — depression, anxiety, sleep and mood disorders — including with medication.',
    conditions: ['Depression', 'Anxiety & panic disorders', 'Bipolar disorder', 'Sleep disorders (insomnia)', 'OCD', 'Addiction', 'Stress-related conditions'],
    symptoms: [['symptoms/fatigue', 'Fatigue'], ['symptoms/headache', 'Headache'], ['symptoms/heart-palpitations', 'Palpitations (anxiety)']],
    tests: [['blood-tests/thyroid-function-test-tft', 'Thyroid (rule-out)'], ['blood-tests/vitamin-b12', 'Vitamin B12'], ['blood-tests/vitamin-d', 'Vitamin D']],
    whenToSee: ['Thoughts of self-harm or suicide — seek help immediately', 'Low mood or anxiety affecting daily life for weeks', 'Sleep, appetite or concentration badly disrupted', 'Mood swings or thoughts that worry you or others'],
    faqs: [
      { q: 'What if I have thoughts of self-harm?', a: 'Please seek help immediately — contact your local emergency number or a crisis line now. Urgent support is available and you are not alone.' },
      { q: 'Are antidepressants addictive?', a: 'They are not addictive in the way some drugs are, but they should be started and stopped with a doctor’s guidance. A psychiatrist explains how they work and the options.' },
    ] },
  { slug: 'psychology', label: 'Psychology & Counselling',
    lede: 'Psychologists and counsellors provide talking therapy and support for stress, relationships, emotions and coping — without medication.',
    conditions: ['Stress & burnout', 'Anxiety & low mood', 'Relationship & family issues', 'Grief & loss', 'Trauma & PTSD', 'Self-esteem & confidence', 'Behavioural & coping difficulties'],
    symptoms: [['symptoms/fatigue', 'Fatigue'], ['symptoms/headache', 'Tension headaches']],
    tests: [[null, 'Psychological assessment / questionnaires']],
    whenToSee: ['Thoughts of self-harm — seek urgent help now', 'Stress or worry affecting daily life, work or relationships', 'Difficulty coping after a loss or trauma', 'Ongoing low mood that talking through could help'],
    faqs: [
      { q: 'What is the difference between a psychologist and a psychiatrist?', a: 'Psychologists and counsellors focus on talking therapy; psychiatrists are doctors who can also prescribe medicine. Many people benefit from both together.' },
      { q: 'When should I see a counsellor?', a: 'If stress, worry or low mood is affecting your daily life, sleep or relationships, talking to a professional can help — you do not have to wait for a crisis.' },
    ] },
  // ------------------------------------------------------- allied / other
  { slug: 'physiotherapy', label: 'Physiotherapy & Rehab',
    lede: 'Physiotherapists restore movement and function after injury, surgery or illness — through exercises, manual therapy and rehabilitation.',
    conditions: ['Back & neck pain', 'Sports injuries', 'Post-surgery rehabilitation', 'Stroke rehabilitation', 'Frozen shoulder & joint stiffness', 'Posture problems', 'Arthritis management'],
    symptoms: [['symptoms/back-pain', 'Back pain'], ['symptoms/neck-pain', 'Neck pain'], ['symptoms/joint-pain', 'Joint pain'], ['symptoms/numbness-and-tingling', 'Numbness & tingling']],
    tests: [['x-ray-explained', 'X-ray'], ['mri-scan-explained', 'MRI'], [null, 'Movement / functional assessment']],
    whenToSee: ['Persistent pain limiting movement or daily activity', 'Recovery guidance after surgery or injury', 'Weakness or stiffness that is not improving', 'Back pain with red flags — see a doctor first'],
    faqs: [
      { q: 'What does a physiotherapist do?', a: 'They assess movement and design exercises and hands-on treatment to reduce pain and restore function after injury, surgery or illness.' },
      { q: 'Can physiotherapy help back pain?', a: 'Yes — for most mechanical back pain, guided exercise and posture work are among the most effective treatments. Red-flag back pain should be assessed by a doctor first.' },
    ] },
  { slug: 'nutrition', label: 'Nutrition & Dietetics',
    lede: 'Dietitians and nutritionists give evidence-based diet advice — for weight, diabetes, deficiencies and healthy eating tailored to you.',
    conditions: ['Weight management', 'Diabetes diet', 'High cholesterol diet', 'Nutrient deficiencies', 'Food intolerances', 'Diet in kidney/liver disease', 'Sports & clinical nutrition'],
    symptoms: [['symptoms/fatigue', 'Fatigue'], ['symptoms/unexplained-weight-loss', 'Weight change'], ['symptoms/bloating', 'Bloating']],
    tests: [['blood-tests/hba1c', 'HbA1c'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], ['blood-tests/vitamin-d', 'Vitamin D'], ['blood-tests/vitamin-b12', 'Vitamin B12'], ['blood-tests/ferritin-iron-studies', 'Iron studies']],
    whenToSee: ['A new diagnosis (diabetes, high cholesterol) needing a diet plan', 'Unintended weight loss or gain', 'Confirmed deficiencies (vitamin D, B12, iron)', 'Digestive symptoms that may be diet-related'],
    faqs: [
      { q: 'What is the difference between a dietitian and a nutritionist?', a: 'Dietitians are qualified to give medical nutrition therapy for conditions like diabetes and kidney disease; nutritionists advise on general healthy eating. Both help tailor a plan.' },
      { q: 'What should I eat for diabetes or weight loss?', a: 'Balanced meals, controlled portions and fewer refined carbs and sugary drinks — but the right plan is individual. A dietitian tailors it to you.' },
    ] },
  { slug: 'sexual-health', label: 'Sexual Health',
    lede: 'Sexual-health services provide confidential testing, treatment and advice for sexually transmitted infections, contraception and sexual well-being.',
    conditions: ['Sexually transmitted infections (STIs)', 'Contraception advice', 'HIV testing & care', 'Erectile & sexual difficulties', 'Vaginal & genital infections', 'Emergency contraception', 'Sexual well-being'],
    symptoms: [['symptoms/painful-urination', 'Painful urination'], ['symptoms/pelvic-pain', 'Pelvic pain'], ['symptoms/skin-rash', 'Genital rash / sores']],
    tests: [[null, 'STI screening panel'], ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B'], [null, 'HIV test'], [null, 'Urine test']],
    whenToSee: ['Genital sores, discharge or pain', 'A possible exposure to an STI', 'Needing contraception or emergency contraception', 'Any concern about sexual health — testing is confidential'],
    faqs: [
      { q: 'Are sexual-health services confidential?', a: 'Yes — testing and treatment are confidential. Many STIs have no symptoms, so testing is worthwhile after any risk. MedDroid answers these questions without judgement.' },
      { q: 'What are common signs of an STI?', a: 'Discharge, burning on urination, sores or itching — but many STIs cause no symptoms at all, which is why testing matters.' },
    ] },
  { slug: 'regenerative-medicine', label: 'Regenerative Medicine',
    lede: 'Regenerative medicine explores using cells, PRP and growth factors to support healing. MedDroid is honest that many such treatments are still investigational.',
    conditions: ['Osteoarthritis (PRP/experimental)', 'Sports & tendon injuries', 'Wound healing', 'Hair restoration (PRP)', 'Joint & cartilage repair (research)', 'Stem-cell therapy (mostly investigational)'],
    symptoms: [['symptoms/joint-pain', 'Joint pain'], ['symptoms/back-pain', 'Back pain']],
    tests: [['x-ray-explained', 'X-ray'], ['mri-scan-explained', 'MRI']],
    whenToSee: ['Persistent joint or tendon pain not responding to standard care', 'Wanting to understand if a regenerative option is evidence-based', 'Before paying for any experimental therapy — seek expert advice'],
    faqs: [
      { q: 'Is stem-cell or PRP therapy proven?', a: 'For a few conditions there is evidence; for many it is experimental or unproven. MedDroid is honest about this and urges caution and expert advice before paying for treatment.' },
      { q: 'How do I judge if a regenerative clinic is legitimate?', a: 'Ask about the evidence, regulatory approval and realistic outcomes. Be wary of clinics that over-promise cures — get an independent specialist opinion.' },
    ] },

  // =============================== NEW DEPARTMENTS (13) ===================
  { slug: 'emergency-medicine', label: 'Emergency Medicine',
    lede: 'Emergency medicine handles urgent, life-threatening problems — heart attacks, strokes, severe injuries, breathing difficulty and poisoning. For a real emergency, do not use an app — call your local emergency number.',
    conditions: ['Heart attack & chest pain', 'Stroke', 'Severe injuries & trauma', 'Difficulty breathing', 'Severe allergic reactions', 'Poisoning & overdose', 'Severe bleeding'],
    symptoms: [['symptoms/chest-pain', 'Chest pain'], ['symptoms/shortness-of-breath', 'Breathlessness'], ['symptoms/fainting', 'Fainting'], ['symptoms/numbness-and-tingling', 'Sudden numbness/weakness']],
    tests: [['ecg-explained', 'ECG'], ['blood-tests/troponin', 'Troponin'], ['blood-tests/d-dimer', 'D-dimer'], ['x-ray-explained', 'X-ray'], ['blood-tests/complete-blood-count-cbc', 'CBC']],
    whenToSee: ['Crushing chest pain, or pain spreading to arm/jaw — call emergency services now', 'Stroke signs: face droop, arm weakness, slurred speech (FAST)', 'Severe breathlessness, heavy bleeding or a severe allergic reaction', 'Any sudden, severe or life-threatening symptom'],
    faqs: [
      { q: 'When should I go to the emergency department?', a: 'For chest pain, stroke signs, severe breathing difficulty, major injury, severe bleeding, a severe allergic reaction, or any sudden life-threatening symptom — call your local emergency number immediately.' },
      { q: 'Can MedDroid handle an emergency?', a: 'No. MedDroid is for general information only. In an emergency, do not wait for an app — contact emergency services or go to the nearest emergency department.' },
    ] },
  { slug: 'geriatrics', label: 'Geriatrics (Elderly Care)',
    lede: 'Geriatricians specialise in the health of older adults — managing multiple conditions, memory, mobility, falls and medications together, for quality of life.',
    conditions: ['Multiple long-term conditions', 'Dementia & memory loss', 'Falls & balance problems', 'Osteoporosis', 'Frailty & mobility loss', 'Medication review (polypharmacy)', 'Incontinence'],
    symptoms: [['symptoms/dizziness', 'Dizziness'], ['symptoms/fainting', 'Fainting / falls'], ['symptoms/fatigue', 'Fatigue'], ['symptoms/numbness-and-tingling', 'Numbness & tingling'], ['symptoms/frequent-urination', 'Frequent urination']],
    tests: [['blood-tests/complete-blood-count-cbc', 'CBC'], ['blood-tests/vitamin-b12', 'Vitamin B12'], ['blood-tests/vitamin-d', 'Vitamin D'], ['blood-tests/thyroid-function-test-tft', 'Thyroid'], ['blood-tests/kidney-function-test-rft', 'Kidney function']],
    whenToSee: ['Recurrent falls or new unsteadiness', 'Worsening memory or confusion', 'Several medicines causing side effects', 'A sudden decline in an older adult — get seen'],
    faqs: [
      { q: 'What does a geriatrician do?', a: 'They look after older adults with several conditions at once — balancing treatments, reviewing medicines, and focusing on memory, mobility and independence.' },
      { q: 'Why is medication review important in older adults?', a: 'Older people often take many medicines that can interact or cause falls and confusion. A geriatrician reviews them to keep only what truly helps.' },
    ] },
  { slug: 'hepatology', label: 'Hepatology (Liver)',
    lede: 'Hepatologists specialise in the liver, gallbladder and bile ducts — fatty liver, hepatitis, cirrhosis and jaundice.',
    conditions: ['Fatty liver disease', 'Hepatitis B & C', 'Cirrhosis', 'Jaundice', 'Alcohol-related liver disease', 'Liver cysts & lesions', 'Liver failure & transplant care'],
    symptoms: [['symptoms/abdominal-pain', 'Upper-abdominal pain'], ['symptoms/itching', 'Itching'], ['symptoms/fatigue', 'Fatigue'], ['symptoms/leg-swelling', 'Swelling (legs/abdomen)']],
    tests: [['blood-tests/liver-function-test-lft', 'Liver function (LFT)'], ['blood-tests/bilirubin', 'Bilirubin'], ['blood-tests/albumin', 'Albumin'], ['blood-tests/hepatitis-b-hbsag', 'Hepatitis B'], [null, 'Ultrasound / FibroScan']],
    whenToSee: ['Yellowing of the skin or eyes (jaundice)', 'Persistently abnormal liver tests', 'Swelling of the abdomen or legs with liver disease', 'Vomiting blood or confusion with known liver disease — emergency'],
    faqs: [
      { q: 'What does a raised SGPT/SGOT mean?', a: 'Raised liver enzymes indicate the liver is irritated — commonly fatty liver, alcohol, hepatitis or medicines. A hepatologist finds the cause and advises treatment.' },
      { q: 'Is fatty liver reversible?', a: 'Often yes — early fatty liver improves with weight loss, exercise, controlling sugar and cutting alcohol. Left unchecked it can progress, so it is worth acting on.' },
    ] },
  { slug: 'andrology', label: "Andrology & Men's Health",
    lede: 'Andrology focuses on male reproductive and sexual health — fertility, testosterone, erectile difficulties and related concerns.',
    conditions: ['Male infertility', 'Low testosterone', 'Erectile dysfunction', 'Premature ejaculation', 'Varicocele', 'Prostate-related symptoms', 'Sexual health concerns'],
    symptoms: [['symptoms/frequent-urination', 'Frequent urination'], ['symptoms/painful-urination', 'Painful urination'], ['symptoms/fatigue', 'Fatigue / low energy']],
    tests: [['blood-tests/testosterone', 'Testosterone'], ['blood-tests/psa', 'PSA'], [null, 'Semen analysis'], ['blood-tests/fasting-blood-sugar', 'Blood sugar'], ['blood-tests/thyroid-function-test-tft', 'Thyroid']],
    whenToSee: ['Difficulty conceiving after a year of trying', 'Persistent low libido, fatigue or erectile difficulty', 'Testicular pain, lump or swelling — get checked', 'Concerns about male fertility or hormones'],
    faqs: [
      { q: 'What causes low testosterone?', a: 'Ageing, obesity, chronic illness, certain medicines and testicular or pituitary problems. A morning blood test (repeated) confirms it before any treatment.' },
      { q: 'How is male fertility assessed?', a: 'Mainly with a semen analysis, plus hormone blood tests (testosterone, and others). An andrologist interprets these and advises on options.' },
    ] },
  { slug: 'pain-management', label: 'Pain Management',
    lede: 'Pain-management specialists treat chronic and complex pain — back, nerve, joint and cancer pain — with medicines, injections and rehabilitation.',
    conditions: ['Chronic back & neck pain', 'Nerve pain (sciatica, neuropathy)', 'Arthritis pain', 'Cancer pain', 'Post-surgical chronic pain', 'Migraine & headache', 'Fibromyalgia'],
    symptoms: [['symptoms/back-pain', 'Back pain'], ['symptoms/neck-pain', 'Neck pain'], ['symptoms/joint-pain', 'Joint pain'], ['symptoms/numbness-and-tingling', 'Numbness & tingling'], ['symptoms/headache', 'Headache']],
    tests: [['mri-scan-explained', 'MRI'], ['x-ray-explained', 'X-ray'], [null, 'Nerve studies']],
    whenToSee: ['Pain lasting more than 3 months despite treatment', 'Nerve pain, numbness or weakness', 'Pain limiting sleep, work or daily life', 'Back pain with red flags — see a doctor urgently'],
    faqs: [
      { q: 'What does a pain-management specialist do?', a: 'They treat long-standing or complex pain using a mix of medicines, targeted injections, physiotherapy and other techniques to improve function and quality of life.' },
      { q: 'Are pain injections safe?', a: 'Procedures like nerve blocks and epidural injections are commonly used and generally safe when done by a specialist. They explain the benefits and risks for your case.' },
    ] },
  { slug: 'radiology', label: 'Radiology & Imaging',
    lede: 'Radiologists use imaging — X-ray, ultrasound, CT and MRI — to diagnose disease and guide treatment. MedDroid can explain what your scan or report appears to show.',
    conditions: ['X-ray interpretation', 'Ultrasound scans', 'CT scans', 'MRI scans', 'Mammography', 'Image-guided biopsies', 'Interventional procedures'],
    symptoms: [['symptoms/chest-pain', 'Chest pain'], ['symptoms/abdominal-pain', 'Abdominal pain'], ['symptoms/back-pain', 'Back pain'], ['symptoms/headache', 'Headache']],
    tests: [['x-ray-explained', 'X-ray explained'], ['mri-scan-explained', 'MRI explained'], ['ecg-explained', 'ECG explained'], [null, 'CT scan'], [null, 'Ultrasound']],
    whenToSee: ['You have a scan or report you do not understand', 'Your doctor recommends imaging for symptoms', 'You want a plain-language explanation before your appointment'],
    faqs: [
      { q: 'Can MedDroid read my X-ray, MRI or scan report?', a: 'MedDroid explains what an image or report appears to show in plain words — educational only. A qualified radiologist and your treating doctor must confirm the diagnosis.' },
      { q: 'What is the difference between a CT and an MRI?', a: 'CT uses X-rays and is fast, good for bone, lungs and emergencies; MRI uses magnets, giving detailed soft-tissue images (brain, joints, spine) without radiation.' },
    ] },
  { slug: 'neurosurgery', label: 'Neurosurgery',
    lede: 'Neurosurgeons operate on the brain, spine and nerves — for tumours, bleeds, slipped discs, and trapped nerves.',
    conditions: ['Brain tumours', 'Brain haemorrhage & aneurysm', 'Slipped (herniated) disc', 'Spinal stenosis', 'Head & spinal injuries', 'Hydrocephalus', 'Trapped/compressed nerves'],
    symptoms: [['symptoms/headache', 'Severe/persistent headache'], ['symptoms/numbness-and-tingling', 'Numbness & tingling'], ['symptoms/back-pain', 'Back pain'], ['symptoms/neck-pain', 'Neck pain'], ['symptoms/blurred-vision', 'Vision changes']],
    tests: [['mri-scan-explained', 'MRI'], [null, 'CT scan'], [null, 'Angiography'], [null, 'Nerve studies']],
    whenToSee: ['Sudden “worst-ever” headache, or weakness/speech trouble — emergency', 'Leg weakness or bladder/bowel changes with back pain — urgent', 'Progressive numbness or weakness in limbs', 'A brain or spine lesion needing surgical opinion'],
    faqs: [
      { q: 'Does a slipped disc always need surgery?', a: 'No — most improve with time, physiotherapy and pain management. Surgery is considered for severe or worsening nerve compression, weakness, or loss of bladder/bowel control.' },
      { q: 'What symptoms need a neurosurgeon urgently?', a: 'A sudden severe headache, new weakness or speech difficulty, or back pain with leg weakness or bladder/bowel changes — these need emergency assessment.' },
    ] },
  { slug: 'cardiac-surgery', label: 'Cardiac & Thoracic Surgery',
    lede: 'Cardiac and thoracic surgeons operate on the heart, major vessels and chest — bypass surgery, valve repair and lung operations.',
    conditions: ['Coronary bypass (CABG)', 'Heart valve repair/replacement', 'Congenital heart defects', 'Aortic aneurysm surgery', 'Lung surgery', 'Chest wall & thoracic tumours', 'Pacemaker/device surgery'],
    symptoms: [['symptoms/chest-pain', 'Chest pain'], ['symptoms/shortness-of-breath', 'Breathlessness'], ['symptoms/heart-palpitations', 'Palpitations'], ['symptoms/leg-swelling', 'Leg swelling']],
    tests: [['ecg-explained', 'ECG'], ['blood-tests/troponin', 'Troponin'], [null, 'Echocardiogram'], [null, 'Coronary angiography'], [null, 'CT chest']],
    whenToSee: ['Severe chest pain — emergency (call for help now)', 'Known severe blockages or valve disease needing surgery', 'Worsening breathlessness with heart disease', 'A referral from your cardiologist for surgery'],
    faqs: [
      { q: 'What is a coronary bypass (CABG)?', a: 'Bypass surgery reroutes blood around blocked heart arteries using a graft, restoring blood flow. It is considered when blockages are severe or unsuitable for stents.' },
      { q: 'When is heart valve surgery needed?', a: 'When a valve is severely narrowed or leaking and causing symptoms or strain on the heart. Your cardiologist and surgeon decide on repair vs replacement.' },
    ] },
  { slug: 'plastic-surgery', label: 'Plastic & Cosmetic Surgery',
    lede: 'Plastic surgeons perform reconstructive and cosmetic surgery — repairing after injury or disease, and enhancing appearance.',
    conditions: ['Burn & wound reconstruction', 'Scar revision', 'Cleft lip & palate', 'Hand surgery', 'Skin cancer removal & repair', 'Cosmetic procedures', 'Post-cancer reconstruction'],
    symptoms: [['symptoms/skin-rash', 'Skin lesions'], ['symptoms/swollen-lymph-nodes', 'Lumps / swellings']],
    tests: [[null, 'Clinical assessment'], [null, 'Biopsy'], [null, 'Imaging (as needed)']],
    whenToSee: ['A wound or burn needing reconstruction', 'A skin lesion needing removal and repair', 'Reconstruction after cancer or injury', 'Considering a cosmetic procedure — seek a qualified surgeon'],
    faqs: [
      { q: 'What is the difference between plastic and cosmetic surgery?', a: 'Plastic surgery includes reconstruction after injury, burns or disease; cosmetic surgery focuses on enhancing appearance. Plastic surgeons are trained in both.' },
      { q: 'How do I choose a safe cosmetic surgeon?', a: 'Check qualifications and registration, ask about experience with the specific procedure, and be wary of unrealistic promises. A proper consultation covers risks and recovery.' },
    ] },
  { slug: 'vascular-surgery', label: 'Vascular Surgery',
    lede: 'Vascular surgeons treat blood-vessel conditions (other than the heart) — blocked arteries, varicose veins, aneurysms and clots.',
    conditions: ['Peripheral artery disease', 'Varicose veins', 'Deep vein thrombosis (DVT)', 'Aortic aneurysm', 'Diabetic foot & ulcers', 'Carotid artery disease', 'Poor circulation'],
    symptoms: [['symptoms/leg-swelling', 'Leg swelling'], ['symptoms/leg-swelling', 'Leg pain on walking']],
    tests: [['blood-tests/d-dimer', 'D-dimer'], [null, 'Doppler ultrasound'], [null, 'CT/MR angiography'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile']],
    whenToSee: ['A painful, swollen, warm calf — urgent (possible DVT)', 'Leg pain on walking that eases with rest (claudication)', 'A non-healing foot ulcer, especially with diabetes', 'Sudden cold, pale, painful limb — emergency'],
    faqs: [
      { q: 'What is peripheral artery disease?', a: 'Narrowed leg arteries from fatty build-up, causing pain on walking and, if severe, non-healing wounds. It also signals higher heart and stroke risk, so it is managed seriously.' },
      { q: 'Are varicose veins dangerous?', a: 'Usually they are a cosmetic and comfort issue, but they can cause skin changes or ulcers over time. A vascular surgeon advises when treatment helps.' },
    ] },
  { slug: 'paediatric-surgery', label: 'Paediatric Surgery',
    lede: 'Paediatric surgeons perform operations on babies and children — for congenital conditions, hernias, appendicitis and childhood surgical problems.',
    conditions: ['Childhood hernias & hydrocele', 'Appendicitis in children', 'Undescended testes', 'Congenital abnormalities', 'Intussusception & bowel problems', 'Circumcision (medical)', 'Childhood lumps'],
    symptoms: [['symptoms/abdominal-pain', 'Tummy pain (child)'], ['symptoms/nausea-and-vomiting', 'Vomiting'], ['symptoms/swollen-lymph-nodes', 'Swelling / lump']],
    tests: [[null, 'Ultrasound'], ['x-ray-explained', 'X-ray'], ['blood-tests/complete-blood-count-cbc', 'CBC']],
    whenToSee: ['A child with severe, persistent tummy pain and vomiting — urgent', 'A groin or scrotal swelling in a child', 'A tense, painful lump that cannot be pushed back (hernia)', 'A newborn with a suspected congenital problem'],
    faqs: [
      { q: 'Are childhood hernias common?', a: 'Yes — groin (inguinal) hernias are common in children, especially infants, and are usually repaired with a small operation to prevent complications.' },
      { q: 'How is appendicitis different in children?', a: 'Children may not describe pain clearly; look for tummy pain moving to the lower right, fever, vomiting and refusing food. It needs prompt assessment as it can worsen quickly.' },
    ] },
  { slug: 'bariatric-surgery', label: 'Bariatric (Weight-loss) Surgery',
    lede: 'Bariatric surgeons help people with severe obesity lose weight and improve health through procedures like gastric sleeve and bypass, alongside lifestyle support.',
    conditions: ['Severe obesity', 'Obesity with type 2 diabetes', 'Obesity with high blood pressure', 'Sleep apnoea with obesity', 'Gastric sleeve & bypass', 'Weight regain after surgery', 'Metabolic syndrome'],
    symptoms: [['symptoms/shortness-of-breath', 'Breathlessness'], ['symptoms/joint-pain', 'Joint pain'], ['symptoms/fatigue', 'Fatigue']],
    tests: [['blood-tests/hba1c', 'HbA1c'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], ['blood-tests/thyroid-function-test-tft', 'Thyroid'], ['blood-tests/vitamin-d', 'Vitamin D'], ['blood-tests/vitamin-b12', 'Vitamin B12']],
    whenToSee: ['Severe obesity not responding to diet and exercise', 'Obesity with diabetes, sleep apnoea or joint problems', 'Wanting to understand if surgery is an option', 'Follow-up nutrition and support after weight-loss surgery'],
    faqs: [
      { q: 'Who is eligible for bariatric surgery?', a: 'Generally people with a high BMI (often ≥ 37.5, or ≥ 32.5 with conditions like diabetes — thresholds vary), after other measures have failed. A team assesses suitability.' },
      { q: 'Is weight-loss surgery just about appearance?', a: 'No — it is a medical treatment that can put type 2 diabetes into remission and improve blood pressure, sleep apnoea and joint health, alongside lasting lifestyle change.' },
    ] },
];

// Labels for the 12 NEW app-selectable departments (General Medicine already
// exists in the app as "General Physician"). Keys are for the Assistant page.
export const NEW_APP_SPECIALTIES = [
  { key: 'emergency', label: 'Emergency Medicine' },
  { key: 'geriatrics', label: 'Geriatrics (Elderly Care)' },
  { key: 'hepatology', label: 'Hepatology (Liver)' },
  { key: 'andrology', label: "Andrology & Men's Health" },
  { key: 'pain', label: 'Pain Management' },
  { key: 'radiology', label: 'Radiology & Imaging' },
  { key: 'neurosurgery', label: 'Neurosurgery' },
  { key: 'cardiacsurgery', label: 'Cardiac & Thoracic Surgery' },
  { key: 'plastic', label: 'Plastic & Cosmetic Surgery' },
  { key: 'vascular', label: 'Vascular Surgery' },
  { key: 'paedsurgery', label: 'Paediatric Surgery' },
  { key: 'bariatric', label: 'Bariatric (Weight-loss) Surgery' },
];
