// Bulk drug library — batch 2. Same class-based model as drugs-bulk.mjs.
// Class-level clinical info + real brand names; NO specific dose shown (deferred
// to a doctor). Brand lists are common examples and vary by country.

export const DRUG_CLASSES_2 = [
  {
    class: 'Eye (ophthalmic) medicine',
    desc: 'Eye drops and ointments treat glaucoma, infections, allergy, inflammation or dryness of the eyes.',
    uses: ['Glaucoma (lowering eye pressure)', 'Eye infections and inflammation', 'Eye allergy and itching', 'Dry, gritty eyes'],
    sideEffects: ['Brief stinging or blurring after use', 'Redness or irritation', 'Changes in eye colour/lashes (some glaucoma drops)'],
    precautions: ['Wash hands and do not touch the dropper to the eye', 'Remove contact lenses before use unless told otherwise', 'Space different eye drops by a few minutes'],
    warnings: ['Eye pain, marked redness or sudden vision change', 'Signs of allergy around the eye', 'Worsening despite treatment'],
    faqs: [
      { q: 'How do I use eye drops correctly?', a: 'Wash hands, tilt your head back, pull down the lower lid, drop in one drop, close the eye gently and press the inner corner for a minute. Do not touch the tip to your eye.' },
      { q: 'Can I use old eye drops?', a: 'Most drops should be discarded about 4 weeks after opening, and never shared, to avoid infection. Check the label.' },
    ],
    members: [
      { slug: 'latanoprost', name: 'Latanoprost (eye)', brandsIndia: ['Latoprost', '9 PM', 'Xalatan'], brandsWorld: ['Xalatan'], blurb: 'Latanoprost eye drops lower eye pressure in glaucoma, used once at night.' },
      { slug: 'timolol-eye', name: 'Timolol (eye)', brandsIndia: ['Iotim', 'Glucomol', 'Timolet'], brandsWorld: ['Timoptic'], blurb: 'Timolol eye drops lower eye pressure in glaucoma.' },
      { slug: 'brimonidine-eye', name: 'Brimonidine (eye)', brandsIndia: ['Alphagan', 'Iobrim'], brandsWorld: ['Alphagan'], blurb: 'Brimonidine eye drops reduce eye pressure in glaucoma.' },
      { slug: 'dorzolamide-eye', name: 'Dorzolamide (eye)', brandsIndia: ['Dorzox', 'Misopt'], brandsWorld: ['Trusopt'], blurb: 'Dorzolamide eye drops lower eye pressure, often combined with timolol.' },
      { slug: 'moxifloxacin-eye', name: 'Moxifloxacin (eye)', brandsIndia: ['Vigamox', '5-Moxi', 'Milflox'], brandsWorld: ['Vigamox', 'Moxeza'], blurb: 'Moxifloxacin eye drops treat bacterial eye infections (conjunctivitis).' },
      { slug: 'tobramycin-eye', name: 'Tobramycin (eye)', brandsIndia: ['Tobastar', 'Toba', 'Tobramycin'], brandsWorld: ['Tobrex'], blurb: 'Tobramycin eye drops treat bacterial eye infections.' },
      { slug: 'olopatadine-eye', name: 'Olopatadine (eye)', brandsIndia: ['Winolap', 'Olopat', 'Pataday'], brandsWorld: ['Pataday', 'Patanol'], blurb: 'Olopatadine eye drops relieve itchy, allergic eyes.' },
      { slug: 'carboxymethylcellulose-eye', name: 'Carboxymethylcellulose (tear drops)', brandsIndia: ['Refresh Tears', 'Teardrops', 'Optive'], brandsWorld: ['Refresh', 'Optive'], blurb: 'Carboxymethylcellulose is a lubricating tear drop for dry, gritty eyes.' },
    ],
  },
  {
    class: 'Vertigo & anti-nausea (vestibular) medicine',
    desc: 'These relieve dizziness (vertigo), motion sickness and nausea by acting on the balance and vomiting centres.',
    uses: ['Vertigo and dizziness', 'Motion sickness', 'Nausea and vomiting', 'Ménière’s disease (some)'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Blurred vision (some)'],
    precautions: ['Do not drive if drowsy', 'Avoid alcohol', 'Caution in the elderly, glaucoma and prostate problems'],
    warnings: ['Sudden severe vertigo with slurred speech or weakness (possible stroke — emergency)', 'Fainting', 'Marked drowsiness or confusion'],
    faqs: [
      { q: 'What is the best medicine for vertigo?', a: 'It depends on the cause — betahistine is common for Ménière’s, while cinnarizine or prochlorperazine help acute spells. A doctor should find and treat the cause.' },
      { q: 'Are vertigo medicines meant for long-term use?', a: 'Usually short-term for spells. Persistent vertigo needs a proper diagnosis, and exercises (vestibular rehab) often help more than long-term drugs.' },
    ],
    members: [
      { slug: 'betahistine', name: 'Betahistine', brandsIndia: ['Vertin', 'Betavert', 'Zevert'], brandsWorld: ['Serc', 'Betaserc'], blurb: 'Betahistine reduces vertigo attacks, especially in Ménière’s disease.' },
      { slug: 'cinnarizine', name: 'Cinnarizine', brandsIndia: ['Stugeron', 'Vertizine', 'Cinaron'], brandsWorld: ['Stugeron'], blurb: 'Cinnarizine relieves vertigo and motion sickness.' },
      { slug: 'prochlorperazine', name: 'Prochlorperazine', brandsIndia: ['Stemetil', 'Vometil'], brandsWorld: ['Compazine', 'Stemetil'], blurb: 'Prochlorperazine treats severe nausea, vomiting and vertigo.' },
      { slug: 'meclizine', name: 'Meclizine (Meclozine)', brandsIndia: ['Diligan', 'Pregnidoxin'], brandsWorld: ['Antivert', 'Bonine'], blurb: 'Meclizine relieves vertigo and motion sickness.' },
      { slug: 'dimenhydrinate', name: 'Dimenhydrinate', brandsIndia: ['Gravol', 'Dramamine'], brandsWorld: ['Dramamine', 'Gravol'], blurb: 'Dimenhydrinate prevents and treats motion sickness and nausea.' },
      { slug: 'promethazine', name: 'Promethazine (Phenergan)', brandsIndia: ['Phenergan', 'Avomine'], brandsWorld: ['Phenergan'], blurb: 'Promethazine is a sedating antihistamine for nausea, allergy and travel sickness.' },
    ],
  },
  {
    class: 'Migraine medicine',
    desc: 'These stop migraine attacks (triptans) or help prevent them.',
    uses: ['Stopping a migraine attack (triptans)', 'Preventing frequent migraines', 'Cluster headache (some)'],
    sideEffects: ['Tingling, flushing or tightness (triptans)', 'Drowsiness (preventers)', 'Dizziness'],
    precautions: ['Triptans are avoided in uncontrolled heart disease', 'Do not overuse painkillers/triptans (rebound headache)', 'Preventers are taken daily, not for acute attacks'],
    warnings: ['Chest tightness or pain with a triptan — seek advice', 'Sudden “worst-ever” headache (emergency)', 'Weakness, slurred speech or vision loss'],
    faqs: [
      { q: 'What is the difference between triptans and preventers?', a: 'Triptans (like sumatriptan) stop an attack once it starts; preventers (like flunarizine or propranolol) are taken daily to reduce how often migraines happen.' },
      { q: 'Can migraine medicines cause more headaches?', a: 'Yes — using acute painkillers or triptans too often can cause “medication-overuse headache”. Limit acute treatment days and consider prevention.' },
    ],
    members: [
      { slug: 'sumatriptan', name: 'Sumatriptan', brandsIndia: ['Suminat', 'Migratan', 'Sumitrex'], brandsWorld: ['Imitrex', 'Imigran'], blurb: 'Sumatriptan stops a migraine attack once it has started.' },
      { slug: 'rizatriptan', name: 'Rizatriptan', brandsIndia: ['Rizact', 'Rizora'], brandsWorld: ['Maxalt'], blurb: 'Rizatriptan is a fast-acting triptan for migraine attacks.' },
      { slug: 'naratriptan', name: 'Naratriptan', brandsIndia: ['Naramig'], brandsWorld: ['Amerge', 'Naramig'], blurb: 'Naratriptan is a longer-acting triptan for migraine.' },
      { slug: 'zolmitriptan', name: 'Zolmitriptan', brandsIndia: ['Zomig', 'Zolmist'], brandsWorld: ['Zomig'], blurb: 'Zolmitriptan treats migraine attacks and comes as a nasal spray too.' },
      { slug: 'flunarizine', name: 'Flunarizine', brandsIndia: ['Sibelium', 'Flunaz', 'Nomigrain'], brandsWorld: ['Sibelium'], blurb: 'Flunarizine is a daily migraine-prevention medicine.' },
    ],
  },
  {
    class: 'Gout medicine',
    desc: 'These lower uric acid to prevent gout, or calm an acute gout attack.',
    uses: ['Preventing gout attacks (urate-lowering)', 'Treating an acute gout flare (colchicine)', 'High uric acid with complications'],
    sideEffects: ['Rash (allopurinol)', 'Diarrhoea (colchicine)', 'Tummy upset'],
    precautions: ['Urate-lowering drugs can trigger a flare when started (cover advised)', 'Do not start/stop during an acute attack without advice', 'Colchicine dose is limited to avoid toxicity'],
    warnings: ['A serious skin rash with allopurinol (stop and seek care urgently)', 'Severe diarrhoea, vomiting or muscle weakness (colchicine toxicity)', 'Signs of allergy'],
    faqs: [
      { q: 'Should I take allopurinol during a gout attack?', a: 'Do not start it during an attack, and if you already take it, do not stop. Starting can briefly worsen a flare, so it is begun after an attack settles, often with cover.' },
      { q: 'Do I need gout medicine for life?', a: 'Urate-lowering treatment is often long-term to keep uric acid low and prevent attacks and joint damage. Diet helps but usually is not enough alone.' },
    ],
    members: [
      { slug: 'allopurinol', name: 'Allopurinol', brandsIndia: ['Zyloric', 'Ciploric', 'Zyrik'], brandsWorld: ['Zyloprim', 'Aloprim'], blurb: 'Allopurinol lowers uric acid to prevent gout attacks long-term.' },
      { slug: 'febuxostat', name: 'Febuxostat', brandsIndia: ['Febustat', 'Zurig', 'Feburic'], brandsWorld: ['Uloric', 'Adenuric'], blurb: 'Febuxostat lowers uric acid, an option when allopurinol is unsuitable.' },
      { slug: 'colchicine', name: 'Colchicine', brandsIndia: ['Zycolchin', 'Goutnil'], brandsWorld: ['Colcrys', 'Mitigare'], blurb: 'Colchicine relieves and prevents acute gout flares at carefully limited doses.' },
    ],
  },
  {
    class: 'Bone / osteoporosis medicine',
    desc: 'These strengthen bone and reduce fracture risk in osteoporosis.',
    uses: ['Osteoporosis (preventing fractures)', 'Bone loss from steroids or menopause', 'Some bone conditions and high calcium'],
    sideEffects: ['Heartburn or tummy upset (oral bisphosphonates)', 'Flu-like symptoms after infusions', 'Low calcium (correct deficiency first)'],
    precautions: ['Take oral bisphosphonates upright with water, then stay upright 30–60 min', 'Ensure enough calcium and vitamin D', 'Tell your dentist before major dental work'],
    warnings: ['Difficulty or pain swallowing (oesophagus irritation)', 'New thigh or jaw pain (rare bone effects)', 'Numbness/spasms (low calcium)'],
    faqs: [
      { q: 'Why take osteoporosis tablets on an empty stomach?', a: 'Oral bisphosphonates are poorly absorbed with food and can irritate the food pipe, so they are taken first thing with plain water, staying upright afterwards.' },
      { q: 'How long are these medicines taken?', a: 'Often several years, sometimes with a planned break (“drug holiday”). Your doctor reviews the balance of benefit and rare risks.' },
    ],
    members: [
      { slug: 'alendronate', name: 'Alendronate', brandsIndia: ['Osteofos', 'Gemfos', 'Restofos'], brandsWorld: ['Fosamax'], blurb: 'Alendronate is a weekly bisphosphonate tablet for osteoporosis.' },
      { slug: 'risedronate', name: 'Risedronate', brandsIndia: ['Risofos', 'Actonel'], brandsWorld: ['Actonel'], blurb: 'Risedronate is a bisphosphonate for osteoporosis, taken weekly or monthly.' },
      { slug: 'zoledronic-acid', name: 'Zoledronic Acid', brandsIndia: ['Zoldria', 'Zybon', 'Aclasta'], brandsWorld: ['Reclast', 'Aclasta'], blurb: 'Zoledronic acid is a once-yearly bone-strengthening infusion.' },
      { slug: 'teriparatide', name: 'Teriparatide', brandsIndia: ['Forteo', 'Bonmax', 'Teribone'], brandsWorld: ['Forteo'], blurb: 'Teriparatide is a daily injection that builds new bone in severe osteoporosis.' },
      { slug: 'denosumab', name: 'Denosumab', brandsIndia: ['Prolia', 'Densmab'], brandsWorld: ['Prolia', 'Xgeva'], blurb: 'Denosumab is a 6-monthly injection that reduces bone loss and fractures.' },
    ],
  },
  {
    class: 'Injectable diabetes medicine (insulin analogue & GLP-1)',
    desc: 'These injectable medicines control blood sugar; GLP-1 types also aid weight loss.',
    uses: ['Type 2 diabetes not controlled on tablets', 'Type 1 diabetes (insulins)', 'Weight management (some GLP-1s)', 'Heart/kidney protection (some GLP-1s)'],
    sideEffects: ['Low blood sugar (insulins)', 'Nausea, especially early (GLP-1s)', 'Injection-site reactions'],
    precautions: ['Rotate injection sites; store as directed', 'GLP-1s are started low to limit nausea', 'Match insulin to meals; never skip meals after a dose'],
    warnings: ['Severe low sugar: confusion, fainting (emergency)', 'Severe abdominal pain (rare pancreatitis with GLP-1s)', 'Very high sugar with vomiting/drowsiness'],
    faqs: [
      { q: 'Do GLP-1 medicines cause weight loss?', a: 'Yes — several (like semaglutide and liraglutide) reduce appetite and support weight loss, alongside lowering blood sugar.' },
      { q: 'What is the difference between long- and rapid-acting insulin?', a: 'Long-acting (like glargine, degludec) gives steady background cover; rapid-acting (like aspart, lispro) covers meals. Many people use both.' },
    ],
    members: [
      { slug: 'insulin-glargine', name: 'Insulin Glargine', brandsIndia: ['Lantus', 'Basalog', 'Glaritus'], brandsWorld: ['Lantus', 'Basaglar', 'Toujeo'], blurb: 'Glargine is a long-acting background insulin given once daily.' },
      { slug: 'insulin-aspart', name: 'Insulin Aspart', brandsIndia: ['NovoRapid', 'Novomix (mix)'], brandsWorld: ['NovoLog', 'Fiasp'], blurb: 'Aspart is a rapid-acting mealtime insulin.' },
      { slug: 'insulin-lispro', name: 'Insulin Lispro', brandsIndia: ['Humalog', 'Lispro'], brandsWorld: ['Humalog', 'Admelog'], blurb: 'Lispro is a rapid-acting mealtime insulin.' },
      { slug: 'insulin-degludec', name: 'Insulin Degludec', brandsIndia: ['Tresiba'], brandsWorld: ['Tresiba'], blurb: 'Degludec is an ultra-long-acting background insulin.' },
      { slug: 'liraglutide', name: 'Liraglutide', brandsIndia: ['Victoza', 'Saxenda'], brandsWorld: ['Victoza', 'Saxenda'], blurb: 'Liraglutide is a daily GLP-1 injection for diabetes and weight loss.' },
      { slug: 'semaglutide', name: 'Semaglutide (Ozempic/Wegovy)', brandsIndia: ['Rybelsus (oral)', 'Ozempic'], brandsWorld: ['Ozempic', 'Wegovy', 'Rybelsus'], blurb: 'Semaglutide is a weekly GLP-1 for diabetes and weight loss (also an oral tablet).' },
      { slug: 'dulaglutide', name: 'Dulaglutide', brandsIndia: ['Trulicity'], brandsWorld: ['Trulicity'], blurb: 'Dulaglutide is a once-weekly GLP-1 injection for type 2 diabetes.' },
    ],
  },
  {
    class: 'Nasal & decongestant medicine',
    desc: 'These relieve a blocked or runny nose from colds and allergies.',
    uses: ['Blocked nose from colds', 'Allergic rhinitis (steroid sprays)', 'Sinus congestion'],
    sideEffects: ['Nasal dryness or stinging', 'Rebound congestion (decongestant sprays if overused)', 'Raised heart rate/BP (oral decongestants)'],
    precautions: ['Do not use decongestant sprays more than 5–7 days (rebound)', 'Oral decongestants: caution with high BP, heart disease', 'Steroid sprays work best used regularly'],
    warnings: ['Palpitations or a big BP rise (oral decongestants)', 'Severe nosebleeds', 'Worsening symptoms or facial pain/fever (sinus infection)'],
    faqs: [
      { q: 'Why does my nose get more blocked after using a spray?', a: 'Decongestant sprays like xylometazoline cause “rebound” congestion if used beyond about a week — the nose becomes dependent. Use them only short-term.' },
      { q: 'Are steroid nasal sprays safe long-term?', a: 'Yes, for allergic rhinitis they are safe for regular use and work best taken daily rather than only when blocked.' },
    ],
    members: [
      { slug: 'xylometazoline', name: 'Xylometazoline (nasal)', brandsIndia: ['Otrivin', 'Nasivion (oxymet)', 'Xylo'], brandsWorld: ['Otrivin'], blurb: 'Xylometazoline is a fast nasal decongestant spray for short-term use.' },
      { slug: 'oxymetazoline', name: 'Oxymetazoline (nasal)', brandsIndia: ['Nasivion', 'Nasoclear-O'], brandsWorld: ['Afrin'], blurb: 'Oxymetazoline is a nasal decongestant spray for short-term relief.' },
      { slug: 'mometasone-nasal', name: 'Mometasone (nasal)', brandsIndia: ['Nasonex', 'Metaspray', 'Momeflo'], brandsWorld: ['Nasonex'], blurb: 'Mometasone nasal spray is a steroid for allergic rhinitis and nasal polyps.' },
      { slug: 'pseudoephedrine', name: 'Pseudoephedrine', brandsIndia: ['Sudafed (combos)', 'Nasoclear'], brandsWorld: ['Sudafed'], blurb: 'Pseudoephedrine is an oral decongestant for a blocked nose and sinuses.' },
      { slug: 'phenylephrine', name: 'Phenylephrine', brandsIndia: ['Sinarest (combo)', 'Coldarin'], brandsWorld: ['Sudafed PE'], blurb: 'Phenylephrine is an oral decongestant found in many cold combinations.' },
    ],
  },
  {
    class: 'Laxative & bowel (IBD) medicine',
    desc: 'These relieve constipation or treat inflammatory bowel disease.',
    uses: ['Constipation', 'Bowel preparation before procedures', 'Ulcerative colitis and Crohn’s (aminosalicylates)'],
    sideEffects: ['Bloating, cramps or wind', 'Diarrhoea if overused', 'Nausea'],
    precautions: ['Use stimulant laxatives short-term', 'Drink plenty of water with fibre laxatives', 'IBD medicines need regular monitoring'],
    warnings: ['Severe abdominal pain or no bowel movement with vomiting (possible obstruction)', 'Blood in stools', 'Signs of dehydration from overuse'],
    faqs: [
      { q: 'Which laxative is safest for regular use?', a: 'Bulk-forming (fibre) and osmotic laxatives (like PEG or lactulose) are gentler for longer use; stimulant laxatives are best kept short-term.' },
      { q: 'What is mesalamine used for?', a: 'Mesalamine (an aminosalicylate) reduces gut inflammation in ulcerative colitis and mild Crohn’s disease, and helps keep them in remission.' },
    ],
    members: [
      { slug: 'polyethylene-glycol', name: 'Polyethylene Glycol (PEG)', brandsIndia: ['Peglec', 'Movicol', 'Cremalax'], brandsWorld: ['MiraLAX', 'Movicol'], blurb: 'PEG is a gentle osmotic laxative for constipation and bowel prep.' },
      { slug: 'senna', name: 'Senna', brandsIndia: ['Softovac (combo)', 'Sofsena'], brandsWorld: ['Senokot', 'Ex-Lax'], blurb: 'Senna is a plant-based stimulant laxative for short-term constipation.' },
      { slug: 'liquid-paraffin', name: 'Liquid Paraffin', brandsIndia: ['Cremaffin (combo)', 'Milk of Magnesia (combo)'], brandsWorld: ['(mineral oil laxatives)'], blurb: 'Liquid paraffin softens stool to ease constipation, used short-term.' },
      { slug: 'mesalamine', name: 'Mesalamine (5-ASA)', brandsIndia: ['Mesacol', 'Octasa', 'Tidocol'], brandsWorld: ['Asacol', 'Pentasa', 'Lialda'], blurb: 'Mesalamine reduces gut inflammation in ulcerative colitis and Crohn’s disease.' },
      { slug: 'sulfasalazine', name: 'Sulfasalazine', brandsIndia: ['Saaz', 'Sazo', 'Sulfaz'], brandsWorld: ['Azulfidine', 'Salazopyrin'], blurb: 'Sulfasalazine treats inflammatory bowel disease and some forms of arthritis.' },
      { slug: 'rifaximin', name: 'Rifaximin', brandsIndia: ['Rifagut', 'Ciboz', 'Xifaxan'], brandsWorld: ['Xifaxan'], blurb: 'Rifaximin is a gut-acting antibiotic for travellers’ diarrhoea, IBS-D and liver-related brain fog.' },
    ],
  },
  {
    class: 'Anti-tuberculosis (TB) medicine',
    desc: 'These treat tuberculosis. TB always needs a combination of drugs for several months to cure it and prevent resistance.',
    uses: ['Active tuberculosis (in combination)', 'Latent TB (prevention)', 'Drug-resistant TB (specialist regimens)'],
    sideEffects: ['Nausea and loss of appetite', 'Orange-red urine/tears (rifampicin — harmless)', 'Tingling in hands/feet (isoniazid — B6 helps)'],
    precautions: ['Take every dose — missing doses causes resistance', 'Liver function is monitored', 'Rifampicin interacts with many drugs, including contraceptives'],
    warnings: ['Yellow eyes, dark urine or severe nausea (liver — urgent)', 'Vision changes (ethambutol)', 'Numbness/weakness or severe rash'],
    faqs: [
      { q: 'Why is TB treated with so many medicines for so long?', a: 'TB bacteria are slow-growing and hardy, so several drugs together for at least 6 months are needed to cure it and stop resistance developing.' },
      { q: 'Why has my urine turned orange?', a: 'Rifampicin harmlessly colours urine, tears and sweat orange-red. It can permanently stain soft contact lenses.' },
    ],
    members: [
      { slug: 'rifampicin', name: 'Rifampicin', brandsIndia: ['R-Cin', 'Rifald', 'Rimactane'], brandsWorld: ['Rifadin', 'Rimactane'], blurb: 'Rifampicin is a core TB drug (also used for some other infections).' },
      { slug: 'isoniazid', name: 'Isoniazid', brandsIndia: ['Isokin', 'Solonex'], brandsWorld: ['(isoniazid/INH brands)'], blurb: 'Isoniazid is a core TB drug; vitamin B6 is given to prevent nerve effects.' },
      { slug: 'ethambutol', name: 'Ethambutol', brandsIndia: ['Combutol', 'Mycobutol'], brandsWorld: ['Myambutol'], blurb: 'Ethambutol is a core TB drug; vision is monitored during treatment.' },
      { slug: 'pyrazinamide', name: 'Pyrazinamide', brandsIndia: ['Pyzina', 'P-Zide'], brandsWorld: ['(pyrazinamide brands)'], blurb: 'Pyrazinamide is used in the intensive early phase of TB treatment.' },
    ],
  },
  {
    class: 'Hospital / strong antibiotic (injectable)',
    desc: 'These powerful antibiotics are used in hospital for serious or resistant infections.',
    uses: ['Severe or hospital-acquired infections', 'Resistant bacterial infections', 'Sepsis and serious pneumonia (in hospital)'],
    sideEffects: ['Diarrhoea or nausea', 'Injection-site reactions', 'Kidney or hearing effects (aminoglycosides)'],
    precautions: ['Given and monitored in hospital', 'Kidney function and drug levels are checked (some)', 'Reserved to preserve their effectiveness'],
    warnings: ['Severe allergy (swelling, breathing difficulty)', 'Reduced hearing or urine (aminoglycosides)', 'Severe or bloody diarrhoea'],
    faqs: [
      { q: 'Why are these antibiotics only used in hospital?', a: 'They are potent, given by injection, and need monitoring of kidneys and drug levels. They are reserved for serious infections to slow resistance.' },
      { q: 'What is a “last-resort” antibiotic?', a: 'Drugs like colistin or vancomycin are kept for infections resistant to other antibiotics, so overusing them would be dangerous for everyone.' },
    ],
    members: [
      { slug: 'piperacillin-tazobactam', name: 'Piperacillin-Tazobactam', brandsIndia: ['Piptaz', 'Zosyn', 'Tazact'], brandsWorld: ['Zosyn', 'Tazocin'], blurb: 'A broad-spectrum injectable antibiotic for serious infections.' },
      { slug: 'meropenem', name: 'Meropenem', brandsIndia: ['Meronem', 'Merocrit', 'Meropen'], brandsWorld: ['Merrem'], blurb: 'Meropenem is a carbapenem antibiotic for severe, resistant infections.' },
      { slug: 'amikacin', name: 'Amikacin', brandsIndia: ['Mikacin', 'Amikacin'], brandsWorld: ['Amikin'], blurb: 'Amikacin is an aminoglycoside for serious gram-negative infections; kidneys/hearing are monitored.' },
      { slug: 'gentamicin', name: 'Gentamicin', brandsIndia: ['Genticyn', 'Garamycin'], brandsWorld: ['Garamycin'], blurb: 'Gentamicin is an aminoglycoside for serious infections and some eye/skin uses.' },
      { slug: 'vancomycin', name: 'Vancomycin', brandsIndia: ['Vancocin', 'Vancomax'], brandsWorld: ['Vancocin'], blurb: 'Vancomycin treats resistant gram-positive infections such as MRSA.' },
      { slug: 'colistin', name: 'Colistin', brandsIndia: ['Walcolis', 'Xylistin'], brandsWorld: ['Coly-Mycin'], blurb: 'Colistin is a last-resort antibiotic for multidrug-resistant infections.' },
    ],
  },
  {
    class: 'Antiprotozoal & other antimicrobial',
    desc: 'These treat protozoal gut infections (like amoebiasis and giardia) and some other infections.',
    uses: ['Amoebiasis and giardiasis', 'Some vaginal and dental infections', 'Traveller’s and parasitic diarrhoea'],
    sideEffects: ['Metallic taste', 'Nausea', 'Dark urine (some)'],
    precautions: ['Avoid alcohol with nitroimidazoles (reaction)', 'Complete the course', 'Tell your doctor about liver disease'],
    warnings: ['Strong reaction with alcohol (flushing, vomiting)', 'Numbness/tingling on long courses', 'Severe allergy'],
    faqs: [
      { q: 'Can I drink alcohol with tinidazole or ornidazole?', a: 'Avoid alcohol during and for a couple of days after — like metronidazole, they can cause an unpleasant flushing-and-vomiting reaction.' },
      { q: 'How are these different from antibiotics?', a: 'They mainly target single-celled parasites (protozoa) rather than bacteria, though some (nitroimidazoles) work against certain bacteria too.' },
    ],
    members: [
      { slug: 'tinidazole', name: 'Tinidazole', brandsIndia: ['Tiniba', 'Fasigyn', 'Tinvista'], brandsWorld: ['Tindamax', 'Fasigyn'], blurb: 'Tinidazole treats amoebiasis, giardiasis and some vaginal infections.' },
      { slug: 'secnidazole', name: 'Secnidazole', brandsIndia: ['Secnil', 'Synidaz'], brandsWorld: ['Solosec'], blurb: 'Secnidazole is a single-dose option for some protozoal and vaginal infections.' },
      { slug: 'ornidazole', name: 'Ornidazole', brandsIndia: ['Ornof', 'Dazolic', 'Giro'], brandsWorld: ['(ornidazole brands)'], blurb: 'Ornidazole treats amoebic and other protozoal infections, often with an antibiotic.' },
      { slug: 'nitazoxanide', name: 'Nitazoxanide', brandsIndia: ['Nizonide', 'Netazox', 'Kidazox'], brandsWorld: ['Alinia'], blurb: 'Nitazoxanide treats parasitic and some viral diarrhoea, including giardia and cryptosporidium.' },
      { slug: 'fosfomycin', name: 'Fosfomycin', brandsIndia: ['Fosfocin', 'Uबiotic'], brandsWorld: ['Monurol'], blurb: 'Fosfomycin is a single-dose antibiotic for uncomplicated urinary infections.' },
    ],
  },
  {
    class: 'Antimalarial (treatment)',
    desc: 'These treat malaria; the choice depends on the malaria type and region.',
    uses: ['Treating malaria', 'Preventing malaria in travellers (some)', 'Severe malaria (injectable artesunate)'],
    sideEffects: ['Nausea and tummy upset', 'Dizziness', 'Vivid dreams (mefloquine)'],
    precautions: ['Complete the full course', 'Check G6PD status before primaquine', 'Take with food where advised'],
    warnings: ['Confusion, fits or very high fever (severe malaria — emergency)', 'Dark urine (possible blood breakdown, esp. G6PD)', 'Severe rash or allergy'],
    faqs: [
      { q: 'Why is primaquine given after other malaria drugs?', a: 'In some malaria types (vivax/ovale), the parasite hides in the liver. Primaquine clears these to prevent relapse — but G6PD status must be checked first.' },
      { q: 'Is malaria treatment different for severe cases?', a: 'Yes — severe malaria is treated urgently in hospital, usually with injectable artesunate, then a full oral course.' },
    ],
    members: [
      { slug: 'artemether-lumefantrine', name: 'Artemether-Lumefantrine (ACT)', brandsIndia: ['Lumether', 'Combither', 'Coartem'], brandsWorld: ['Coartem', 'Riamet'], blurb: 'This artemisinin combination (ACT) is first-line for falciparum malaria.' },
      { slug: 'artesunate', name: 'Artesunate', brandsIndia: ['Falcigo', 'Larinate'], brandsWorld: ['(artesunate injection brands)'], blurb: 'Injectable artesunate is the treatment of choice for severe malaria.' },
      { slug: 'primaquine', name: 'Primaquine', brandsIndia: ['Malirid', 'Primaquine'], brandsWorld: ['(primaquine brands)'], blurb: 'Primaquine clears the liver stage of vivax malaria to prevent relapse (check G6PD first).' },
      { slug: 'mefloquine', name: 'Mefloquine', brandsIndia: ['Mefax', 'Larimef'], brandsWorld: ['Lariam'], blurb: 'Mefloquine treats and prevents malaria; it can cause vivid dreams or mood effects.' },
      { slug: 'quinine', name: 'Quinine', brandsIndia: ['Qinine', 'Relicin'], brandsWorld: ['Qualaquin'], blurb: 'Quinine is an older antimalarial still used for certain cases.' },
    ],
  },
  {
    class: 'Skin (dermatology) medicine — advanced',
    desc: 'These treat eczema, psoriasis, acne, pigmentation and fungal skin problems, mostly applied to the skin.',
    uses: ['Eczema and psoriasis', 'Acne and pigmentation', 'Fungal skin infections', 'Hair loss (topical)'],
    sideEffects: ['Local irritation, burning or dryness', 'Sun sensitivity (retinoids)', 'Skin lightening/darkening (some)'],
    precautions: ['Use sun protection with retinoids and hydroquinone', 'Avoid strong products on broken skin', 'Follow the course; some take weeks to work'],
    warnings: ['Severe burning, blistering or allergic rash', 'Spreading infection', 'Worsening despite treatment'],
    faqs: [
      { q: 'How long do skin creams take to work?', a: 'Acne and pigmentation creams often take 6–12 weeks; fungal and eczema treatments vary. Consistency matters — do not stop too early.' },
      { q: 'Can I use hydroquinone long-term?', a: 'No — it is used in short supervised courses for pigmentation, as long unsupervised use can cause side effects. A dermatologist should guide it.' },
    ],
    members: [
      { slug: 'tacrolimus-topical', name: 'Tacrolimus (topical)', brandsIndia: ['Tacroz', 'Takfa', 'Protopic'], brandsWorld: ['Protopic'], blurb: 'Tacrolimus ointment treats eczema without the thinning caused by steroids, useful on the face.' },
      { slug: 'calcipotriol', name: 'Calcipotriol', brandsIndia: ['Daivonex', 'Psorid-C', 'Calcigen'], brandsWorld: ['Dovonex', 'Daivonex'], blurb: 'Calcipotriol is a vitamin-D cream for plaque psoriasis.' },
      { slug: 'salicylic-acid', name: 'Salicylic Acid (skin)', brandsIndia: ['Salicylix', 'Saslic'], brandsWorld: ['(salicylic acid brands)'], blurb: 'Salicylic acid exfoliates and unclogs pores in acne and helps warts and dandruff.' },
      { slug: 'tretinoin', name: 'Tretinoin (topical)', brandsIndia: ['Retino-A', 'A-Ret', 'Tretin'], brandsWorld: ['Retin-A'], blurb: 'Tretinoin is a retinoid cream for acne and skin renewal; needs sun protection.' },
      { slug: 'minoxidil-topical', name: 'Minoxidil (topical)', brandsIndia: ['Mintop', 'Tugain', 'Hairgro'], brandsWorld: ['Rogaine'], blurb: 'Minoxidil solution/foam is applied to the scalp to slow hair loss and regrow hair.' },
      { slug: 'hydroquinone', name: 'Hydroquinone', brandsIndia: ['Melalite', 'Eukroma', 'Skinlite'], brandsWorld: ['(hydroquinone brands)'], blurb: 'Hydroquinone lightens dark patches (melasma) in short, supervised courses.' },
      { slug: 'luliconazole', name: 'Luliconazole', brandsIndia: ['Lulican', 'Lulibet (combo)', 'Lulikem'], brandsWorld: ['Luzu'], blurb: 'Luliconazole is an antifungal cream for ringworm and skin fungal infections.' },
      { slug: 'azelaic-acid', name: 'Azelaic Acid', brandsIndia: ['Aziderm', 'Azelac'], brandsWorld: ['Finacea', 'Azelex'], blurb: 'Azelaic acid treats acne and rosacea and helps pigmentation.' },
    ],
  },
  {
    class: 'Immunosuppressant / DMARD',
    desc: 'These calm an overactive immune system in autoimmune diseases and after transplants.',
    uses: ['Rheumatoid and other inflammatory arthritis', 'Autoimmune diseases (lupus, IBD, psoriasis)', 'Preventing transplant rejection'],
    sideEffects: ['Increased infection risk', 'Nausea or mouth ulcers', 'Blood-count or liver changes'],
    precautions: ['Regular blood tests to monitor blood counts, liver and kidneys', 'Avoid live vaccines; report infections early', 'Methotrexate is taken WEEKLY, not daily, with folic acid'],
    warnings: ['Fever, sore throat or infection (weakened immunity)', 'Breathlessness or persistent cough', 'Yellow eyes, easy bruising or unusual bleeding'],
    faqs: [
      { q: 'Why is methotrexate taken once a week?', a: 'For arthritis and psoriasis it is a weekly dose — taking it daily by mistake can be dangerous. Folic acid is added on other days to reduce side effects.' },
      { q: 'Are these medicines dangerous?', a: 'They need monitoring because they lower immunity and can affect blood, liver and kidneys — but for serious autoimmune disease the benefits usually outweigh the risks.' },
    ],
    members: [
      { slug: 'methotrexate', name: 'Methotrexate', brandsIndia: ['Folitrax', 'Imutrex', 'Methocip'], brandsWorld: ['Trexall', 'Otrexup'], blurb: 'Methotrexate is a weekly DMARD for rheumatoid arthritis, psoriasis and some cancers.' },
      { slug: 'azathioprine', name: 'Azathioprine', brandsIndia: ['Imuran', 'Azoran', 'Azophar'], brandsWorld: ['Imuran', 'Azasan'], blurb: 'Azathioprine suppresses the immune system in autoimmune disease and after transplants.' },
      { slug: 'mycophenolate', name: 'Mycophenolate Mofetil', brandsIndia: ['Cellcept', 'Mycept', 'Mmf'], brandsWorld: ['CellCept', 'Myfortic'], blurb: 'Mycophenolate prevents transplant rejection and treats some autoimmune diseases.' },
      { slug: 'cyclosporine', name: 'Cyclosporine', brandsIndia: ['Panimun Bioral', 'Sandimmun'], brandsWorld: ['Neoral', 'Sandimmune'], blurb: 'Cyclosporine suppresses immunity in transplants and severe psoriasis/eczema.' },
      { slug: 'leflunomide', name: 'Leflunomide', brandsIndia: ['Lefno', 'Cleft', 'Lefra'], brandsWorld: ['Arava'], blurb: 'Leflunomide is a DMARD for rheumatoid and psoriatic arthritis.' },
    ],
  },
  {
    class: 'Parkinson’s & dementia medicine',
    desc: 'These help movement in Parkinson’s disease or memory/function in dementia.',
    uses: ['Parkinson’s disease (movement symptoms)', 'Restless legs (some)', 'Alzheimer’s and other dementias'],
    sideEffects: ['Nausea', 'Dizziness or low blood pressure on standing', 'Sleepiness or vivid dreams (Parkinson’s drugs)'],
    precautions: ['Do not stop Parkinson’s medicines suddenly', 'Rise slowly to avoid dizziness', 'Report sudden sleep attacks or impulse-control changes'],
    warnings: ['Sudden severe stiffness or high fever if doses are missed', 'Fainting', 'Hallucinations or marked confusion'],
    faqs: [
      { q: 'Do dementia medicines cure Alzheimer’s?', a: 'No — medicines like donepezil and memantine do not cure dementia, but they can ease symptoms and slow decline for a time in some people.' },
      { q: 'Why must Parkinson’s medicines be taken on time?', a: 'Levels need to stay steady; late or missed doses can cause sudden stiffness and difficulty moving.' },
    ],
    members: [
      { slug: 'levodopa-carbidopa', name: 'Levodopa-Carbidopa', brandsIndia: ['Syndopa', 'Tidomet', 'Sinemet'], brandsWorld: ['Sinemet', 'Rytary'], blurb: 'Levodopa-carbidopa is the main treatment for Parkinson’s movement symptoms.' },
      { slug: 'pramipexole', name: 'Pramipexole', brandsIndia: ['Pramipex', 'Parpex'], brandsWorld: ['Mirapex'], blurb: 'Pramipexole is a dopamine agonist for Parkinson’s and restless legs.' },
      { slug: 'ropinirole', name: 'Ropinirole', brandsIndia: ['Ropark', 'Repreve'], brandsWorld: ['Requip'], blurb: 'Ropinirole is a dopamine agonist for Parkinson’s and restless legs.' },
      { slug: 'donepezil', name: 'Donepezil', brandsIndia: ['Donep', 'Aricep', 'Dopezil'], brandsWorld: ['Aricept'], blurb: 'Donepezil eases symptoms of Alzheimer’s dementia.' },
      { slug: 'memantine', name: 'Memantine', brandsIndia: ['Admenta', 'Nemdaa', 'Memantine'], brandsWorld: ['Namenda'], blurb: 'Memantine is used for moderate-to-severe Alzheimer’s dementia.' },
    ],
  },
  {
    class: 'Hormonal & contraceptive medicine',
    desc: 'These provide contraception or hormone treatment for menopause and related conditions.',
    uses: ['Contraception (regular and emergency)', 'Menopause symptoms (HRT)', 'Menstrual and hormone conditions'],
    sideEffects: ['Nausea, breast tenderness', 'Spotting or cycle changes', 'Mood changes'],
    precautions: ['Combined (oestrogen) types raise clot risk — not for smokers over 35 or clot history', 'Emergency pills work best taken as soon as possible', 'Regular review with your doctor'],
    warnings: ['Leg pain/swelling or breathlessness (clot)', 'Severe headache/migraine with aura, or vision changes', 'Chest pain'],
    faqs: [
      { q: 'How soon should I take the emergency pill?', a: 'As soon as possible after unprotected sex — levonorgestrel works best within 72 hours, and sooner is more effective.' },
      { q: 'Is hormone replacement therapy (HRT) safe?', a: 'For many women around menopause the benefits outweigh the risks, but it depends on your age and health. Your doctor helps weigh it up.' },
    ],
    members: [
      { slug: 'combined-oral-contraceptive', name: 'Combined Oral Contraceptive Pill', brandsIndia: ['Mala-N', 'Yasmin', 'Krimson'], brandsWorld: ['Yaz', 'Microgynon'], blurb: 'The combined pill (oestrogen + progestogen) prevents pregnancy and can regulate periods.' },
      { slug: 'levonorgestrel-ecp', name: 'Levonorgestrel (Emergency Pill)', brandsIndia: ['i-Pill', 'Unwanted-72', 'Preventol'], brandsWorld: ['Plan B', 'Levonelle'], blurb: 'Levonorgestrel emergency contraception is taken after unprotected sex, ideally within 72 hours.' },
      { slug: 'desogestrel', name: 'Desogestrel (Mini-Pill)', brandsIndia: ['Cerazette', 'Novelon (combo)'], brandsWorld: ['Cerazette', 'Slynd'], blurb: 'Desogestrel is a progestogen-only “mini-pill”, suitable when oestrogen must be avoided.' },
      { slug: 'estradiol-hrt', name: 'Estradiol (HRT)', brandsIndia: ['Progynova', 'Estrabet'], brandsWorld: ['Estrace', 'Estraderm'], blurb: 'Estradiol is used in hormone replacement therapy for menopause symptoms.' },
      { slug: 'dydrogesterone', name: 'Dydrogesterone', brandsIndia: ['Duphaston', 'Dydroboon'], brandsWorld: ['Duphaston'], blurb: 'Dydrogesterone is a progestogen for menstrual disorders and to support early pregnancy in some cases.' },
    ],
  },
  {
    class: 'Emergency & critical-care medicine',
    desc: 'These are used in medical emergencies, usually by trained staff.',
    uses: ['Severe allergic reaction (anaphylaxis)', 'Cardiac arrest and very slow heart rate', 'Opioid overdose reversal', 'Poisoning'],
    sideEffects: ['Fast heartbeat and anxiety (adrenaline)', 'Dry mouth (atropine)', 'Withdrawal symptoms (naloxone in opioid users)'],
    precautions: ['Adrenaline auto-injectors: know how and when to use them', 'These are given by or under medical guidance', 'Always call emergency services in a crisis'],
    warnings: ['Anaphylaxis is a life-threatening emergency — use adrenaline and call for help', 'Any overdose or poisoning needs urgent medical care'],
    faqs: [
      { q: 'When do I use an adrenaline auto-injector?', a: 'At the first signs of a severe allergic reaction (throat swelling, breathing difficulty, collapse) — inject into the outer thigh and call emergency services immediately.' },
      { q: 'What does naloxone do?', a: 'Naloxone rapidly reverses an opioid overdose, restoring breathing. It is a temporary fix — the person still needs emergency care.' },
    ],
    members: [
      { slug: 'adrenaline-epinephrine', name: 'Adrenaline (Epinephrine)', brandsIndia: ['Adrenaline', 'EpiPen'], brandsWorld: ['EpiPen', 'Auvi-Q'], blurb: 'Adrenaline is the life-saving treatment for anaphylaxis and is used in cardiac arrest.' },
      { slug: 'atropine', name: 'Atropine', brandsIndia: ['Atropine', 'Tropine'], brandsWorld: ['(atropine injection brands)'], blurb: 'Atropine speeds a dangerously slow heart and is used in certain poisonings.' },
      { slug: 'naloxone', name: 'Naloxone', brandsIndia: ['Nalox', 'Narcotan'], brandsWorld: ['Narcan'], blurb: 'Naloxone rapidly reverses an opioid overdose.' },
      { slug: 'activated-charcoal', name: 'Activated Charcoal', brandsIndia: ['Charcoal', 'Actidose'], brandsWorld: ['Actidose', 'EZ-Char'], blurb: 'Activated charcoal can bind some poisons if given soon after ingestion, under medical guidance.' },
    ],
  },
  {
    class: 'Endocrine (cancer hormone) therapy',
    desc: 'These block hormones that drive certain cancers, especially breast cancer.',
    uses: ['Hormone-sensitive breast cancer (treatment and prevention)', 'Some other hormone-related conditions'],
    sideEffects: ['Hot flushes', 'Joint aches (aromatase inhibitors)', 'Mood changes'],
    precautions: ['Taken long-term under an oncologist', 'Bone health is monitored (aromatase inhibitors)', 'Report unusual bleeding (tamoxifen)'],
    warnings: ['Leg swelling/pain or breathlessness (clot with tamoxifen)', 'Unusual vaginal bleeding', 'New bone pain or fractures'],
    faqs: [
      { q: 'How long is breast-cancer hormone therapy taken?', a: 'Often 5–10 years, because it greatly lowers the chance of the cancer returning. Your oncologist tailors the duration.' },
      { q: 'What is the difference between tamoxifen and letrozole?', a: 'Tamoxifen blocks oestrogen’s effect and suits many women including before menopause; aromatase inhibitors like letrozole lower oestrogen and are used after menopause.' },
    ],
    members: [
      { slug: 'tamoxifen', name: 'Tamoxifen', brandsIndia: ['Tamodex', 'Mamofen', 'Nolvadex'], brandsWorld: ['Nolvadex', 'Soltamox'], blurb: 'Tamoxifen treats and helps prevent hormone-sensitive breast cancer.' },
      { slug: 'letrozole', name: 'Letrozole', brandsIndia: ['Letroz', 'Femara', 'Oreta'], brandsWorld: ['Femara'], blurb: 'Letrozole lowers oestrogen in breast cancer and is also used to induce ovulation.' },
      { slug: 'anastrozole', name: 'Anastrozole', brandsIndia: ['Anabrez', 'Armotraz', 'Arimidex'], brandsWorld: ['Arimidex'], blurb: 'Anastrozole is an aromatase inhibitor for breast cancer after menopause.' },
    ],
  },
  {
    class: 'COPD & long-acting inhaler',
    desc: 'These daily inhalers keep the airways open in COPD and long-term asthma.',
    uses: ['COPD maintenance', 'Long-term asthma control (with a steroid)', 'Reducing flare-ups and breathlessness'],
    sideEffects: ['Dry mouth', 'Throat irritation or hoarseness', 'Fast heartbeat or tremor (with some)'],
    precautions: ['These are preventers, not for sudden attacks — keep a reliever', 'Rinse the mouth after steroid-containing inhalers', 'Use correct inhaler technique (ask for a demo)'],
    warnings: ['Severe breathlessness or a reliever not working (emergency)', 'Palpitations', 'Worsening symptoms despite regular use'],
    faqs: [
      { q: 'Can I use these inhalers for a sudden attack?', a: 'No — long-acting inhalers are for daily control. For sudden symptoms you need a fast reliever like salbutamol.' },
      { q: 'Why rinse my mouth after inhaling?', a: 'With steroid-containing inhalers, rinsing reduces the risk of oral thrush and hoarseness.' },
    ],
    members: [
      { slug: 'tiotropium', name: 'Tiotropium', brandsIndia: ['Tiova', 'Tiomate'], brandsWorld: ['Spiriva'], blurb: 'Tiotropium is a once-daily long-acting inhaler that keeps COPD airways open.' },
      { slug: 'glycopyrronium-inhaler', name: 'Glycopyrronium (inhaler)', brandsIndia: ['Seebri', 'Glyco'], brandsWorld: ['Seebri'], blurb: 'Glycopyrronium is a long-acting inhaled bronchodilator for COPD.' },
      { slug: 'salmeterol', name: 'Salmeterol', brandsIndia: ['Seroflo (combo)', 'Serobid'], brandsWorld: ['Serevent'], blurb: 'Salmeterol is a long-acting airway opener used with an inhaled steroid.' },
      { slug: 'umeclidinium', name: 'Umeclidinium', brandsIndia: ['(in combos)'], brandsWorld: ['Incruse', 'Anoro (combo)'], blurb: 'Umeclidinium is a once-daily long-acting inhaler for COPD.' },
    ],
  },
  {
    class: 'Systemic corticosteroid (extra)',
    desc: 'These steroids strongly reduce inflammation and calm the immune system in many conditions.',
    uses: ['Severe inflammation and autoimmune flares', 'Severe allergy and asthma flares', 'Some cancers and after transplants'],
    sideEffects: ['Increased appetite, weight gain', 'Raised blood sugar and blood pressure', 'Mood and sleep changes'],
    precautions: ['Do not stop suddenly after longer courses (taper)', 'Monitor sugar, blood pressure and bones with long use', 'Watch for infections'],
    warnings: ['Signs of infection (steroids can mask them)', 'Severe mood disturbance', 'Weakness/dizziness if stopped abruptly (adrenal effect)'],
    faqs: [
      { q: 'Why do steroids need to be tapered?', a: 'After more than a short course, the body reduces its own steroid output. Stopping suddenly can cause a dangerous drop, so the dose is reduced gradually.' },
      { q: 'Are steroid injections different from tablets?', a: 'Injections can be into a joint (local) or into muscle/vein (whole-body). A joint injection acts locally with fewer whole-body effects.' },
    ],
    members: [
      { slug: 'methylprednisolone', name: 'Methylprednisolone', brandsIndia: ['Medrol', 'Solu-Medrol'], brandsWorld: ['Medrol', 'Depo-Medrol'], blurb: 'Methylprednisolone is a steroid for inflammation, given as tablets or injection.' },
      { slug: 'hydrocortisone', name: 'Hydrocortisone', brandsIndia: ['Efcorlin', 'Lycortin'], brandsWorld: ['Cortef', 'Solu-Cortef'], blurb: 'Hydrocortisone is a steroid used for adrenal insufficiency, allergy and inflammation.' },
      { slug: 'betamethasone-systemic', name: 'Betamethasone (systemic)', brandsIndia: ['Betnesol', 'Celestone'], brandsWorld: ['Celestone'], blurb: 'Betamethasone is a potent steroid, also given before preterm birth to help baby’s lungs.' },
      { slug: 'deflazacort', name: 'Deflazacort', brandsIndia: ['Defcort', 'Zenflax', 'Moaz'], brandsWorld: ['Emflaza'], blurb: 'Deflazacort is a steroid used in some inflammatory conditions and muscular dystrophy.' },
    ],
  },
  {
    class: 'Antifungal (systemic, advanced)',
    desc: 'These treat serious internal fungal infections and some resistant skin/nail cases.',
    uses: ['Serious internal (systemic) fungal infections', 'Resistant nail and skin infections', 'Oral and throat thrush (nystatin)'],
    sideEffects: ['Nausea and tummy upset', 'Liver enzyme changes', 'Vision changes (voriconazole)'],
    precautions: ['Liver function is monitored', 'Many drug interactions', 'Given under specialist care (serious infections)'],
    warnings: ['Yellow eyes or dark urine (liver)', 'Visual disturbances (voriconazole)', 'Severe allergy or infusion reactions'],
    faqs: [
      { q: 'Why do serious fungal infections need strong antifungals?', a: 'Deep or bloodstream fungal infections can be life-threatening and need potent, closely monitored antifungals, often given in hospital.' },
      { q: 'Is nystatin absorbed into the body?', a: 'Barely — it acts locally in the mouth or gut, which makes it useful for oral/gut thrush with few whole-body effects.' },
    ],
    members: [
      { slug: 'voriconazole', name: 'Voriconazole', brandsIndia: ['Vfend', 'Vorizol'], brandsWorld: ['Vfend'], blurb: 'Voriconazole treats serious mould and other invasive fungal infections.' },
      { slug: 'nystatin', name: 'Nystatin', brandsIndia: ['Mycostatin', 'Candid Mouth Paint (clotrimazole alt)'], brandsWorld: ['Nystop', 'Mycostatin'], blurb: 'Nystatin treats oral and gut thrush, acting locally.' },
      { slug: 'amphotericin-b', name: 'Amphotericin B', brandsIndia: ['Fungizone', 'Amphotret', 'Ambisome'], brandsWorld: ['AmBisome', 'Fungizone'], blurb: 'Amphotericin B is a powerful antifungal for severe infections, given in hospital.' },
    ],
  },
  {
    class: 'Antiarrhythmic (heart rhythm)',
    desc: 'These control abnormal heart rhythms.',
    uses: ['Atrial fibrillation and flutter', 'Some fast or dangerous rhythms', 'Maintaining a normal rhythm'],
    sideEffects: ['Slow heartbeat or dizziness', 'Tiredness', 'Organ effects with long use (amiodarone)'],
    precautions: ['Regular ECG and blood tests (some)', 'Amiodarone needs thyroid, liver, lung and eye monitoring', 'Many drug interactions'],
    warnings: ['Fainting, very slow or very fast pulse', 'Breathlessness or new cough (amiodarone lung effect)', 'Vision changes or yellow skin'],
    faqs: [
      { q: 'Why does amiodarone need so much monitoring?', a: 'It is very effective but can affect the thyroid, liver, lungs, eyes and skin over time, so regular checks are needed.' },
      { q: 'Can heart-rhythm drugs be stopped when I feel fine?', a: 'No — feeling well often means they are working. Stopping can let a dangerous rhythm return; only change them with your cardiologist.' },
    ],
    members: [
      { slug: 'amiodarone', name: 'Amiodarone', brandsIndia: ['Cordarone', 'Tachyra', 'Amipace'], brandsWorld: ['Pacerone', 'Cordarone'], blurb: 'Amiodarone controls serious heart rhythm problems and needs careful monitoring.' },
      { slug: 'sotalol', name: 'Sotalol', brandsIndia: ['Sotagard', 'Sotalol'], brandsWorld: ['Betapace'], blurb: 'Sotalol is a beta-blocker that also controls certain heart rhythms.' },
      { slug: 'flecainide', name: 'Flecainide', brandsIndia: ['Flecarite', 'Flexid'], brandsWorld: ['Tambocor'], blurb: 'Flecainide restores and maintains normal rhythm in atrial fibrillation in suitable patients.' },
      { slug: 'dronedarone', name: 'Dronedarone', brandsIndia: ['Multaq'], brandsWorld: ['Multaq'], blurb: 'Dronedarone helps maintain normal rhythm in atrial fibrillation.' },
    ],
  },
  {
    class: 'Injectable blood thinner (heparin)',
    desc: 'These fast-acting injectable anticoagulants prevent and treat clots.',
    uses: ['Preventing clots after surgery or during hospital stays', 'Treating deep-vein and lung clots', 'During pregnancy (when a blood thinner is needed)'],
    sideEffects: ['Bruising at injection sites', 'Bleeding tendency', 'Rarely, low platelets'],
    precautions: ['Rotate injection sites', 'Report unusual bleeding', 'Dose adjusted in kidney disease'],
    warnings: ['Black stools, blood in urine/vomit, or coughing blood', 'Severe headache or a bad fall', 'A sharp drop in platelets (rare)'],
    faqs: [
      { q: 'Why is a heparin injection used instead of tablets?', a: 'It works fast and is easy to control, so it is used in hospital, after surgery, and in pregnancy where tablet blood thinners may be unsuitable.' },
      { q: 'Can I inject enoxaparin at home?', a: 'Yes — many people are taught to give the pre-filled injection under the skin at home, rotating sites and watching for bleeding.' },
    ],
    members: [
      { slug: 'enoxaparin', name: 'Enoxaparin', brandsIndia: ['Clexane', 'Lomoh', 'Enoxion'], brandsWorld: ['Lovenox', 'Clexane'], blurb: 'Enoxaparin is a low-molecular-weight heparin injection to prevent and treat clots.' },
      { slug: 'dalteparin', name: 'Dalteparin', brandsIndia: ['Fragmin'], brandsWorld: ['Fragmin'], blurb: 'Dalteparin is a low-molecular-weight heparin for clot prevention and treatment.' },
      { slug: 'fondaparinux', name: 'Fondaparinux', brandsIndia: ['Arixtra', 'Fondaparin'], brandsWorld: ['Arixtra'], blurb: 'Fondaparinux is an injectable anticoagulant for clot prevention and treatment.' },
    ],
  },
  {
    class: 'Overactive bladder & prostate (extra)',
    desc: 'These treat urinary urgency, frequency and prostate-related urinary symptoms.',
    uses: ['Overactive bladder (urgency, frequency, leaks)', 'Enlarged prostate urinary symptoms', 'Bed-wetting in some cases'],
    sideEffects: ['Dry mouth and constipation (anticholinergics)', 'Blurred vision', 'Dizziness'],
    precautions: ['Caution in glaucoma and severe constipation', 'Rise slowly (alpha-blockers)', 'Review effect after a few weeks'],
    warnings: ['Inability to pass urine (retention)', 'Fainting or severe dizziness', 'Severe constipation'],
    faqs: [
      { q: 'How do overactive-bladder medicines work?', a: 'Most relax the bladder muscle to reduce urgency and frequency. Newer ones (mirabegron) work differently with less dry mouth.' },
      { q: 'How long before they help?', a: 'It can take a few weeks. Bladder training and fluid habits alongside the medicine improve results.' },
    ],
    members: [
      { slug: 'oxybutynin', name: 'Oxybutynin', brandsIndia: ['Oxybutin', 'Cystran'], brandsWorld: ['Ditropan', 'Oxytrol'], blurb: 'Oxybutynin calms an overactive bladder to reduce urgency and leaks.' },
      { slug: 'mirabegron', name: 'Mirabegron', brandsIndia: ['Mirabt', 'Bettmir', 'Mirasone'], brandsWorld: ['Myrbetriq', 'Betmiga'], blurb: 'Mirabegron relaxes the bladder with less dry mouth than older medicines.' },
      { slug: 'alfuzosin', name: 'Alfuzosin', brandsIndia: ['Alfusin', 'Aflo'], brandsWorld: ['Uroxatral'], blurb: 'Alfuzosin relaxes the prostate to ease urinary flow in BPH.' },
    ],
  },
  {
    class: 'Antispasmodic & gut comfort',
    desc: 'These ease cramping abdominal pain, spasm and trapped wind.',
    uses: ['Stomach and bowel cramps', 'Irritable bowel syndrome (IBS)', 'Period cramps', 'Trapped wind and bloating'],
    sideEffects: ['Dry mouth', 'Blurred vision (some)', 'Constipation'],
    precautions: ['Caution in glaucoma and some heart/prostate conditions', 'Short-term use for cramps', 'Do not ignore persistent pain'],
    warnings: ['Severe or persistent abdominal pain', 'Inability to pass urine', 'Vomiting with a swollen belly'],
    faqs: [
      { q: 'What helps IBS cramps?', a: 'Antispasmodics like mebeverine or hyoscine ease cramps; alongside diet changes (and sometimes peppermint oil) they help many people with IBS.' },
      { q: 'What is simethicone for?', a: 'It breaks up trapped gas to relieve bloating and wind, and is safe even for infant colic.' },
    ],
    members: [
      { slug: 'hyoscine-butylbromide', name: 'Hyoscine Butylbromide (Buscopan)', brandsIndia: ['Buscopan', 'Cyclopam (combo)'], brandsWorld: ['Buscopan'], blurb: 'Hyoscine butylbromide relieves stomach and bowel cramps.' },
      { slug: 'mebeverine', name: 'Mebeverine', brandsIndia: ['Meva', 'Colospa', 'Morease'], brandsWorld: ['Colofac'], blurb: 'Mebeverine is an antispasmodic used mainly for IBS cramps.' },
      { slug: 'simethicone', name: 'Simethicone', brandsIndia: ['Gas-O-Fast', 'Colicaid', 'Neopeptine'], brandsWorld: ['Gas-X', 'Mylicon'], blurb: 'Simethicone relieves bloating, trapped wind and infant colic.' },
    ],
  },
  {
    class: 'Sleep & sedative (non-benzodiazepine)',
    desc: 'These help short-term sleep problems; most are for brief use to avoid dependence.',
    uses: ['Short-term insomnia', 'Jet lag or shift-work sleep problems (melatonin)', 'Occasional sleeplessness'],
    sideEffects: ['Morning drowsiness', 'Dizziness', 'Headache'],
    precautions: ['Use for the shortest time; address sleep habits first', 'Do not drive if drowsy; avoid alcohol', 'Caution in the elderly (falls)'],
    warnings: ['Doing activities while not fully awake (rare, with some sleep drugs)', 'Marked next-day drowsiness', 'Dependence with prolonged use'],
    faqs: [
      { q: 'Is melatonin safe?', a: 'Melatonin is generally well tolerated for short-term sleep problems and jet lag, and is non-habit-forming, though good sleep habits matter most.' },
      { q: 'Are sleeping pills addictive?', a: 'Some (like zolpidem) can cause dependence with regular use, so they are meant for short courses while sleep habits are improved.' },
    ],
    members: [
      { slug: 'zolpidem', name: 'Zolpidem', brandsIndia: ['Zolfresh', 'Nitrest', 'Zolined'], brandsWorld: ['Ambien', 'Stilnox'], blurb: 'Zolpidem is a short-term sleeping tablet for insomnia.' },
      { slug: 'melatonin', name: 'Melatonin', brandsIndia: ['Meloset', 'Zytonin', 'Restwel'], brandsWorld: ['Circadin', '(melatonin brands)'], blurb: 'Melatonin is a sleep-timing hormone used for insomnia and jet lag.' },
      { slug: 'doxylamine', name: 'Doxylamine', brandsIndia: ['Doxinate (with B6)', 'Restwel'], brandsWorld: ['Unisom'], blurb: 'Doxylamine is a sedating antihistamine used for occasional sleeplessness and pregnancy nausea (with B6).' },
    ],
  },
  {
    class: 'Liver & miscellaneous',
    desc: 'These support the liver, gallstones or metabolism in specific conditions.',
    uses: ['Certain liver conditions and gallstones', 'Fatty liver support (some)', 'Weight management (orlistat)'],
    sideEffects: ['Diarrhoea or oily stools (orlistat)', 'Tummy upset', 'Nausea'],
    precautions: ['Follow dietary advice with these medicines', 'Report worsening liver symptoms', 'Some need long-term use'],
    warnings: ['Yellow eyes, dark urine or severe tummy pain', 'Severe or persistent diarrhoea', 'Signs of allergy'],
    faqs: [
      { q: 'Does ursodeoxycholic acid dissolve gallstones?', a: 'It can slowly dissolve certain small cholesterol gallstones and is used in some liver conditions, but it works gradually and is not suitable for all stones.' },
      { q: 'How does orlistat help weight loss?', a: 'It blocks absorption of some dietary fat. It works best with a lower-fat diet — otherwise it causes oily, loose stools.' },
    ],
    members: [
      { slug: 'ursodeoxycholic-acid', name: 'Ursodeoxycholic Acid (UDCA)', brandsIndia: ['Udiliv', 'Ursocol', 'Udihep'], brandsWorld: ['Ursodiol', 'Actigall'], blurb: 'UDCA is used for certain gallstones and liver conditions.' },
      { slug: 'orlistat', name: 'Orlistat', brandsIndia: ['Obelit', 'Vyfat', 'Xenical'], brandsWorld: ['Xenical', 'Alli'], blurb: 'Orlistat aids weight loss by reducing fat absorption from food.' },
      { slug: 'silymarin', name: 'Silymarin (Milk Thistle)', brandsIndia: ['Livomyn', 'Silybon', 'Hepamerz (combo)'], brandsWorld: ['(milk thistle brands)'], blurb: 'Silymarin is a milk-thistle extract used as liver support (evidence is limited).' },
    ],
  },
];
