// Bulk drug library for MedDroid, organised by DRUG CLASS. Each page inherits
// accurate class-level clinical info (uses, side effects, precautions, warnings)
// plus the individual drug's real brand names and a one-line description.
// IMPORTANT: bulk pages show NO specific dose — dosing is deferred to a doctor —
// because fabricating adult/paediatric doses for hundreds of drugs would be
// unsafe. Detailed doses live only on the hand-verified curated set (drugs.mjs).
// Brand lists are common examples, not exhaustive, and vary by country.

export const DRUG_CLASSES = [
  {
    class: 'ACE inhibitor (blood pressure)',
    desc: 'ACE inhibitors relax blood vessels to lower blood pressure and protect the heart and kidneys.',
    uses: ['High blood pressure', 'Heart failure', 'Kidney protection in diabetes', 'After a heart attack'],
    sideEffects: ['A persistent dry cough', 'Dizziness, especially at first', 'Rarely, raised blood potassium'],
    precautions: ['Not to be used in pregnancy', 'Kidney function and potassium are monitored', 'Rise slowly to avoid dizziness'],
    warnings: ['Swelling of the face, lips or throat (rare — urgent)', 'Fainting or very low blood pressure', 'Muscle weakness or palpitations (high potassium)'],
    faqs: [
      { q: 'Why do ACE inhibitors cause a dry cough?', a: 'They can raise a natural substance (bradykinin) that irritates the airways, causing a tickly dry cough in some people. If troublesome, your doctor may switch you to an ARB.' },
      { q: 'Are ACE inhibitors safe in pregnancy?', a: 'No — they should be avoided in pregnancy. Tell your doctor if you are pregnant or planning to be.' },
    ],
    members: [
      { slug: 'ramipril', name: 'Ramipril', brandsIndia: ['Cardace', 'Ramistar', 'Hopace'], brandsWorld: ['Altace', 'Tritace'], blurb: 'Ramipril is a widely used ACE inhibitor for blood pressure and heart protection.' },
      { slug: 'enalapril', name: 'Enalapril', brandsIndia: ['Envas', 'Enam', 'Nuril'], brandsWorld: ['Vasotec'], blurb: 'Enalapril is an ACE inhibitor used for high blood pressure and heart failure.' },
      { slug: 'lisinopril', name: 'Lisinopril', brandsIndia: ['Lisoril', 'Listril', 'Hipril'], brandsWorld: ['Prinivil', 'Zestril'], blurb: 'Lisinopril is a once-daily ACE inhibitor for blood pressure and heart failure.' },
      { slug: 'perindopril', name: 'Perindopril', brandsIndia: ['Coversyl', 'Prindace'], brandsWorld: ['Coversyl', 'Aceon'], blurb: 'Perindopril is a long-acting ACE inhibitor for blood pressure and heart disease.' },
    ],
  },
  {
    class: 'ARB (blood pressure)',
    desc: 'ARBs relax blood vessels to lower blood pressure and protect the kidneys, without the cough that ACE inhibitors can cause.',
    uses: ['High blood pressure', 'Kidney protection in diabetes', 'Heart failure', 'Reducing cardiovascular risk'],
    sideEffects: ['Dizziness at first', 'Tiredness', 'Rarely, raised blood potassium'],
    precautions: ['Not to be used in pregnancy', 'Kidney function and potassium are monitored', 'Rise slowly to avoid dizziness'],
    warnings: ['Facial or throat swelling (rare — urgent)', 'Fainting or very low blood pressure', 'Muscle weakness or palpitations (high potassium)'],
    faqs: [
      { q: 'How are ARBs different from ACE inhibitors?', a: 'They work at a later step in the same system and usually do not cause the dry cough, so they are often used when an ACE inhibitor is not tolerated.' },
      { q: 'Can I take an ARB in pregnancy?', a: 'No — ARBs must be avoided in pregnancy. Speak to your doctor if pregnant or planning to be.' },
    ],
    members: [
      { slug: 'olmesartan', name: 'Olmesartan', brandsIndia: ['Olmy', 'Olmat', 'Benitec'], brandsWorld: ['Benicar', 'Olmetec'], blurb: 'Olmesartan is an ARB for high blood pressure, taken once daily.' },
      { slug: 'valsartan', name: 'Valsartan', brandsIndia: ['Valzaar', 'Diovan', 'Starval'], brandsWorld: ['Diovan'], blurb: 'Valsartan is an ARB used for blood pressure and heart failure.' },
      { slug: 'candesartan', name: 'Candesartan', brandsIndia: ['Candesar', 'Atacand'], brandsWorld: ['Atacand'], blurb: 'Candesartan is a long-acting ARB for blood pressure and heart failure.' },
      { slug: 'irbesartan', name: 'Irbesartan', brandsIndia: ['Irovel', 'Xarb'], brandsWorld: ['Avapro', 'Aprovel'], blurb: 'Irbesartan is an ARB especially used to protect the kidneys in diabetes.' },
    ],
  },
  {
    class: 'Beta-blocker (heart)',
    desc: 'Beta-blockers slow the heart and lower blood pressure, easing the heart’s workload.',
    uses: ['High blood pressure', 'Angina and after a heart attack', 'Certain fast or irregular heart rhythms', 'Heart failure (specific ones)'],
    sideEffects: ['Tiredness', 'Cold hands and feet', 'Slow heartbeat or dizziness'],
    precautions: ['Do not stop suddenly (rebound effects)', 'Caution in asthma and some heart conditions', 'May mask low-sugar warning signs in diabetes'],
    warnings: ['Very slow pulse, fainting or breathlessness', 'Worsening wheeze in asthma', 'Swelling or rapid weight gain'],
    faqs: [
      { q: 'Can I stop a beta-blocker suddenly?', a: 'No — stopping abruptly can cause a rebound rise in heart rate and blood pressure. Any change should be gradual and doctor-guided.' },
      { q: 'Why do beta-blockers cause tiredness?', a: 'By slowing the heart they can reduce energy at first; this often settles. Tell your doctor if it persists.' },
    ],
    members: [
      { slug: 'atenolol', name: 'Atenolol', brandsIndia: ['Aten', 'Tenormin', 'Betacard'], brandsWorld: ['Tenormin'], blurb: 'Atenolol is a common beta-blocker for blood pressure and angina.' },
      { slug: 'bisoprolol', name: 'Bisoprolol', brandsIndia: ['Concor', 'Corbis', 'Bisoheart'], brandsWorld: ['Zebeta', 'Cardicor'], blurb: 'Bisoprolol is a heart-selective beta-blocker used in heart failure and blood pressure.' },
      { slug: 'nebivolol', name: 'Nebivolol', brandsIndia: ['Nebicard', 'Nebilong', 'Nodon'], brandsWorld: ['Bystolic', 'Nebilet'], blurb: 'Nebivolol is a newer beta-blocker that also relaxes blood vessels.' },
      { slug: 'carvedilol', name: 'Carvedilol', brandsIndia: ['Carca', 'Cardivas', 'Carloc'], brandsWorld: ['Coreg'], blurb: 'Carvedilol is a beta-blocker widely used in heart failure.' },
      { slug: 'propranolol', name: 'Propranolol', brandsIndia: ['Ciplar', 'Inderal', 'Provanol'], brandsWorld: ['Inderal'], blurb: 'Propranolol is a beta-blocker also used for tremor, migraine prevention and anxiety symptoms.' },
    ],
  },
  {
    class: 'Calcium-channel blocker (blood pressure)',
    desc: 'These relax and widen blood vessels to lower blood pressure and ease angina.',
    uses: ['High blood pressure', 'Angina', 'Some fast heart rhythms (certain ones)'],
    sideEffects: ['Ankle swelling', 'Flushing and headache', 'Constipation (with some)'],
    precautions: ['Grapefruit can raise levels of some', 'Rise slowly to avoid dizziness', 'Do not stop suddenly for heart rhythm use'],
    warnings: ['Marked ankle swelling or sudden weight gain', 'Fainting or very low blood pressure', 'Very slow pulse (with diltiazem/verapamil)'],
    faqs: [
      { q: 'Why do these cause ankle swelling?', a: 'They widen small blood vessels, which can let fluid pool in the ankles. Tell your doctor if it is troublesome.' },
      { q: 'Can I eat grapefruit with these?', a: 'Grapefruit can raise blood levels of some calcium-channel blockers — check with your pharmacist about your specific medicine.' },
    ],
    members: [
      { slug: 'nifedipine', name: 'Nifedipine', brandsIndia: ['Depin', 'Nicardia', 'Calcigard'], brandsWorld: ['Adalat', 'Procardia'], blurb: 'Nifedipine is a calcium-channel blocker for blood pressure and angina.' },
      { slug: 'cilnidipine', name: 'Cilnidipine', brandsIndia: ['Cilacar', 'Nexovas', 'Dilnip'], brandsWorld: ['Atelec'], blurb: 'Cilnidipine is a calcium-channel blocker that causes less ankle swelling than some others.' },
      { slug: 'felodipine', name: 'Felodipine', brandsIndia: ['Felogard', 'Plendil'], brandsWorld: ['Plendil'], blurb: 'Felodipine is a once-daily calcium-channel blocker for blood pressure.' },
      { slug: 'diltiazem', name: 'Diltiazem', brandsIndia: ['Dilzem', 'Angizem'], brandsWorld: ['Cardizem', 'Tiazac'], blurb: 'Diltiazem is a calcium-channel blocker for angina and some heart rhythms.' },
      { slug: 'verapamil', name: 'Verapamil', brandsIndia: ['Calaptin', 'Veroz'], brandsWorld: ['Calan', 'Isoptin'], blurb: 'Verapamil is a calcium-channel blocker used for rhythm control and angina.' },
    ],
  },
  {
    class: 'Diuretic (water tablet)',
    desc: 'Diuretics help the body remove excess salt and water, lowering blood pressure and reducing swelling.',
    uses: ['High blood pressure', 'Fluid overload and swelling (oedema)', 'Heart failure', 'Some kidney and liver conditions'],
    sideEffects: ['Passing more urine', 'Dizziness or dehydration', 'Salt imbalances (sodium, potassium)'],
    precautions: ['Blood salts and kidney function are monitored', 'Take earlier in the day to avoid night-time urination', 'Stay hydrated in hot weather'],
    warnings: ['Severe dizziness, cramps or palpitations (salt imbalance)', 'Very little urine or signs of dehydration', 'Gout flares with some diuretics'],
    faqs: [
      { q: 'When should I take a water tablet?', a: 'Usually in the morning, so the extra urination does not disturb your sleep.' },
      { q: 'Do diuretics affect potassium?', a: 'Some lower potassium and others raise it, so your doctor checks your blood salts, especially when starting or changing the dose.' },
    ],
    members: [
      { slug: 'hydrochlorothiazide', name: 'Hydrochlorothiazide (HCTZ)', brandsIndia: ['Aquazide', 'Hydrazide'], brandsWorld: ['Microzide', 'Esidrix'], blurb: 'HCTZ is a thiazide water tablet used for blood pressure, often in combination pills.' },
      { slug: 'chlorthalidone', name: 'Chlorthalidone', brandsIndia: ['Ctd', 'Chlortha'], brandsWorld: ['Thalitone', 'Hygroton'], blurb: 'Chlorthalidone is a long-acting thiazide-like diuretic for blood pressure.' },
      { slug: 'indapamide', name: 'Indapamide', brandsIndia: ['Natrilix', 'Lorvas'], brandsWorld: ['Natrilix', 'Lozol'], blurb: 'Indapamide is a thiazide-like diuretic commonly used for blood pressure.' },
      { slug: 'furosemide', name: 'Furosemide (Lasix)', brandsIndia: ['Lasix', 'Frusenex'], brandsWorld: ['Lasix'], blurb: 'Furosemide is a strong loop diuretic used for fluid overload in heart, kidney and liver disease.' },
      { slug: 'torsemide', name: 'Torsemide', brandsIndia: ['Dytor', 'Tide'], brandsWorld: ['Demadex', 'Soaanz'], blurb: 'Torsemide is a loop diuretic for fluid overload and heart failure.' },
      { slug: 'spironolactone', name: 'Spironolactone', brandsIndia: ['Aldactone', 'Spiromide'], brandsWorld: ['Aldactone', 'CaroSpir'], blurb: 'Spironolactone is a potassium-sparing diuretic used in heart failure, fluid and hormone conditions.' },
    ],
  },
  {
    class: 'Statin / lipid-lowering',
    desc: 'These lower cholesterol to reduce the risk of heart attack and stroke.',
    uses: ['Lowering high cholesterol', 'Preventing heart attack and stroke', 'After a heart attack or stroke'],
    sideEffects: ['Muscle aches', 'Digestive upset', 'Rarely, raised liver enzymes'],
    precautions: ['Statins are avoided in pregnancy', 'Limit alcohol; grapefruit can raise some statin levels', 'Occasional liver blood tests'],
    warnings: ['Unexplained muscle pain or weakness with dark urine (rare — seek advice)', 'Yellow eyes or severe tummy pain'],
    faqs: [
      { q: 'Do lipid medicines need to be lifelong?', a: 'Often yes, because cholesterol rises again if they stop. Lifestyle helps, but do not stop without discussing it with your doctor.' },
      { q: 'Are muscle aches from statins serious?', a: 'Mild aches are common and usually harmless, but severe muscle pain with weakness or dark urine is rare and needs prompt review.' },
    ],
    members: [
      { slug: 'rosuvastatin', name: 'Rosuvastatin', brandsIndia: ['Rosuvas', 'Rozavel', 'Crevast'], brandsWorld: ['Crestor'], blurb: 'Rosuvastatin is a potent statin for lowering cholesterol.' },
      { slug: 'simvastatin', name: 'Simvastatin', brandsIndia: ['Simvas', 'Simlup'], brandsWorld: ['Zocor'], blurb: 'Simvastatin is a widely used statin, taken in the evening.' },
      { slug: 'fenofibrate', name: 'Fenofibrate', brandsIndia: ['Lipicard', 'Fenolip'], brandsWorld: ['Tricor', 'Lipofen'], blurb: 'Fenofibrate is a fibrate that mainly lowers triglycerides.' },
      { slug: 'ezetimibe', name: 'Ezetimibe', brandsIndia: ['Ezedoc', 'Ezetib'], brandsWorld: ['Zetia', 'Ezetrol'], blurb: 'Ezetimibe lowers cholesterol by reducing its absorption from the gut, often added to a statin.' },
    ],
  },
  {
    class: 'Oral diabetes medicine',
    desc: 'These help control blood sugar in type 2 diabetes through different mechanisms.',
    uses: ['Type 2 diabetes', 'Often combined with metformin', 'Improving long-term sugar control (HbA1c)'],
    sideEffects: ['Vary by type: some cause low sugar, some urinary infections, some weight change', 'Digestive upset', 'Dizziness'],
    precautions: ['Do not skip meals with sugar-lowering types', 'Kidney function may be checked', 'Report frequent low-sugar episodes'],
    warnings: ['Low blood sugar: shakiness, sweating, confusion (with some types)', 'Signs of urinary or genital infection (with SGLT2 types)', 'Severe tummy pain (rare)'],
    faqs: [
      { q: 'Why are there so many diabetes tablets?', a: 'They work in different ways — some make more insulin, some reduce sugar absorption, some remove sugar in urine. Doctors combine them to reach target sugar with fewest side effects.' },
      { q: 'Can these replace metformin?', a: 'They are usually added to metformin rather than replacing it, unless metformin is not suitable. Your doctor tailors the combination.' },
    ],
    members: [
      { slug: 'gliclazide', name: 'Gliclazide', brandsIndia: ['Diamicron', 'Glizid', 'Reclide'], brandsWorld: ['Diamicron'], blurb: 'Gliclazide is a sulfonylurea that helps the pancreas release insulin.' },
      { slug: 'glipizide', name: 'Glipizide', brandsIndia: ['Glynase', 'Glez'], brandsWorld: ['Glucotrol'], blurb: 'Glipizide is a sulfonylurea for type 2 diabetes.' },
      { slug: 'sitagliptin', name: 'Sitagliptin', brandsIndia: ['Januvia', 'Istavel', 'Sitagly'], brandsWorld: ['Januvia'], blurb: 'Sitagliptin is a DPP-4 inhibitor that improves the body’s own insulin response with a low risk of low sugar.' },
      { slug: 'vildagliptin', name: 'Vildagliptin', brandsIndia: ['Galvus', 'Jalra', 'Zomelis'], brandsWorld: ['Galvus'], blurb: 'Vildagliptin is a DPP-4 inhibitor for type 2 diabetes.' },
      { slug: 'teneligliptin', name: 'Teneligliptin', brandsIndia: ['Tenepride', 'Zita', 'Teneza'], brandsWorld: ['Tenelia'], blurb: 'Teneligliptin is an affordable DPP-4 inhibitor widely used in India.' },
      { slug: 'dapagliflozin', name: 'Dapagliflozin', brandsIndia: ['Forxiga', 'Dapa', 'Sugafit'], brandsWorld: ['Farxiga', 'Forxiga'], blurb: 'Dapagliflozin is an SGLT2 inhibitor that lowers sugar via the urine and also helps the heart and kidneys.' },
      { slug: 'empagliflozin', name: 'Empagliflozin', brandsIndia: ['Jardiance', 'Gibtulio'], brandsWorld: ['Jardiance'], blurb: 'Empagliflozin is an SGLT2 inhibitor with proven heart and kidney benefits.' },
      { slug: 'pioglitazone', name: 'Pioglitazone', brandsIndia: ['Pioz', 'Piozone'], brandsWorld: ['Actos'], blurb: 'Pioglitazone improves insulin sensitivity in type 2 diabetes.' },
      { slug: 'voglibose', name: 'Voglibose', brandsIndia: ['Volix', 'Vogs', 'Recansi'], brandsWorld: ['Basen'], blurb: 'Voglibose slows carbohydrate absorption to blunt after-meal sugar spikes.' },
      { slug: 'acarbose', name: 'Acarbose', brandsIndia: ['Glucobay', 'Asucrose'], brandsWorld: ['Precose', 'Glucobay'], blurb: 'Acarbose reduces the rise in blood sugar after meals.' },
    ],
  },
  {
    class: 'NSAID / pain reliever',
    desc: 'Non-steroidal anti-inflammatory drugs relieve pain, swelling and fever, but can affect the stomach, kidneys and heart.',
    uses: ['Pain with inflammation (joints, muscles)', 'Period pain', 'Dental and post-injury pain', 'Fever'],
    sideEffects: ['Stomach upset and heartburn', 'Nausea', 'Fluid retention or raised blood pressure'],
    precautions: ['Take with food, lowest dose for shortest time', 'Avoid with ulcers, kidney or significant heart disease', 'Caution in the elderly and asthma'],
    warnings: ['Black stools or vomiting blood (GI bleeding)', 'Chest pain or breathlessness', 'Swelling, rash or wheezing (allergy)'],
    faqs: [
      { q: 'Are NSAIDs safe for daily use?', a: 'For short-term relief they are fine for most people, but regular long-term use raises the risk of stomach, kidney and heart problems — use the lowest dose for the shortest time and review with a doctor.' },
      { q: 'Can I take an NSAID with paracetamol?', a: 'Usually yes, as they work differently and can be combined for stronger relief. Check with a pharmacist if you have other conditions.' },
    ],
    members: [
      { slug: 'naproxen', name: 'Naproxen', brandsIndia: ['Naprosyn', 'Xenobid'], brandsWorld: ['Aleve', 'Naprosyn'], blurb: 'Naproxen is a longer-acting NSAID useful for arthritis and period pain.' },
      { slug: 'mefenamic-acid', name: 'Mefenamic Acid', brandsIndia: ['Meftal', 'Ponstan'], brandsWorld: ['Ponstan', 'Ponstel'], blurb: 'Mefenamic acid is an NSAID popular for period pain and fever in children (as Meftal-P).' },
      { slug: 'etoricoxib', name: 'Etoricoxib', brandsIndia: ['Etozox', 'Nucoxia', 'Etoshine'], brandsWorld: ['Arcoxia'], blurb: 'Etoricoxib is a COX-2 NSAID that is a little gentler on the stomach, used for arthritis and gout.' },
      { slug: 'nimesulide', name: 'Nimesulide', brandsIndia: ['Nise', 'Nimulid', 'Nimek'], brandsWorld: ['(restricted/withdrawn in many countries)'], blurb: 'Nimesulide is an NSAID used in adults in India; it is restricted elsewhere due to liver concerns.' },
      { slug: 'ketorolac', name: 'Ketorolac', brandsIndia: ['Ketanov', 'Zofer-K', 'Torolac'], brandsWorld: ['Toradol'], blurb: 'Ketorolac is a strong short-term NSAID for acute pain, used only for a few days.' },
      { slug: 'tramadol', name: 'Tramadol', brandsIndia: ['Ultracet (with paracetamol)', 'Tramazac', 'Domadol'], brandsWorld: ['Ultram', 'Tramal'], blurb: 'Tramadol is a prescription opioid-type painkiller for moderate-to-severe pain; it can cause dependence.' },
      { slug: 'serratiopeptidase', name: 'Serratiopeptidase', brandsIndia: ['Serrapin', 'Danzen', 'M-Cap'], brandsWorld: ['Danzen'], blurb: 'Serratiopeptidase is an enzyme often added to painkillers to reduce swelling.' },
    ],
  },
  {
    class: 'Cephalosporin antibiotic',
    desc: 'Cephalosporins are a large family of antibiotics for many bacterial infections.',
    uses: ['Throat, ear and sinus infections', 'Urinary and skin infections', 'Chest infections', 'Some serious infections (injectable ones)'],
    sideEffects: ['Diarrhoea or loose stools', 'Nausea', 'Rash'],
    precautions: ['Tell your doctor about penicillin/cephalosporin allergy', 'Complete the full course', 'Antibiotics do not help viral infections'],
    warnings: ['Severe allergy (swelling, breathing difficulty)', 'Severe or bloody diarrhoea', 'Widespread rash'],
    faqs: [
      { q: 'Can I take a cephalosporin if I am allergic to penicillin?', a: 'There is a small chance of cross-reaction, so always tell your doctor about any penicillin allergy before taking one.' },
      { q: 'Should I finish the course?', a: 'Yes — stopping early can leave bacteria that regrow and become resistant.' },
    ],
    members: [
      { slug: 'cephalexin', name: 'Cephalexin', brandsIndia: ['Sporidex', 'Phexin', 'Ceff'], brandsWorld: ['Keflex'], blurb: 'Cephalexin is a first-generation cephalosporin for skin, throat and urinary infections.' },
      { slug: 'cefadroxil', name: 'Cefadroxil', brandsIndia: ['Cefadrox', 'Droxyl', 'Kefloxin'], brandsWorld: ['Duricef'], blurb: 'Cefadroxil is a first-generation cephalosporin taken once or twice daily.' },
      { slug: 'cefuroxime', name: 'Cefuroxime', brandsIndia: ['Ceftum', 'Supacef', 'CefASo'], brandsWorld: ['Ceftin', 'Zinacef'], blurb: 'Cefuroxime is a second-generation cephalosporin for respiratory and urinary infections.' },
      { slug: 'cefpodoxime', name: 'Cefpodoxime', brandsIndia: ['Cepodem', 'Doxcef', 'Cefpo'], brandsWorld: ['Vantin'], blurb: 'Cefpodoxime is a third-generation oral cephalosporin for chest, ear and urinary infections.' },
      { slug: 'ceftriaxone', name: 'Ceftriaxone', brandsIndia: ['Monocef', 'Oframax', 'Cefaxone'], brandsWorld: ['Rocephin'], blurb: 'Ceftriaxone is a powerful injectable cephalosporin for serious infections in hospital.' },
    ],
  },
  {
    class: 'Antibiotic (other)',
    desc: 'These antibiotics from various families treat specific bacterial infections; they do not work against viruses.',
    uses: ['Chest, throat, skin or urinary infections (depending on the drug)', 'Dental and gut infections', 'Some resistant infections'],
    sideEffects: ['Diarrhoea or nausea', 'Tummy upset', 'Rash'],
    precautions: ['Complete the full course', 'Tell your doctor about allergies and other medicines', 'Antibiotics do not help colds and flu'],
    warnings: ['Severe allergy (swelling, breathing difficulty)', 'Severe or bloody diarrhoea', 'Any serious reaction — stop and seek advice'],
    faqs: [
      { q: 'Why should antibiotics not be overused?', a: 'Overuse drives antibiotic resistance, making infections harder to treat. Only take them when a doctor advises, and finish the course.' },
      { q: 'Can I drink alcohol with antibiotics?', a: 'It depends on the antibiotic — some (like metronidazole) react badly with alcohol. Check with your pharmacist about yours.' },
    ],
    members: [
      { slug: 'clarithromycin', name: 'Clarithromycin', brandsIndia: ['Claribid', 'Crixan', 'Synclar'], brandsWorld: ['Biaxin'], blurb: 'Clarithromycin is a macrolide antibiotic for chest infections and part of ulcer (H. pylori) treatment.' },
      { slug: 'roxithromycin', name: 'Roxithromycin', brandsIndia: ['Roxid', 'Rulide', 'Roxee'], brandsWorld: ['Rulide'], blurb: 'Roxithromycin is a macrolide antibiotic for respiratory, skin and dental infections.' },
      { slug: 'erythromycin', name: 'Erythromycin', brandsIndia: ['Erythrocin', 'Althrocin'], brandsWorld: ['Ery-Tab', 'Erythrocin'], blurb: 'Erythromycin is an older macrolide antibiotic, also used for acne.' },
      { slug: 'clindamycin', name: 'Clindamycin', brandsIndia: ['Dalacin C', 'Clincin', 'Clinac'], brandsWorld: ['Cleocin'], blurb: 'Clindamycin treats skin, dental and some serious infections, and is used topically for acne.' },
      { slug: 'linezolid', name: 'Linezolid', brandsIndia: ['Linospan', 'Linox', 'Lizolid'], brandsWorld: ['Zyvox'], blurb: 'Linezolid is a reserve antibiotic for resistant infections such as MRSA.' },
      { slug: 'nitrofurantoin', name: 'Nitrofurantoin', brandsIndia: ['Niftran', 'Nitrofit', 'Martifur'], brandsWorld: ['Macrobid', 'Macrodantin'], blurb: 'Nitrofurantoin is a first-choice antibiotic for uncomplicated urinary infections.' },
      { slug: 'cotrimoxazole', name: 'Cotrimoxazole (Septran)', brandsIndia: ['Septran', 'Bactrim', 'Ciplin'], brandsWorld: ['Bactrim', 'Septra'], blurb: 'Cotrimoxazole combines two antibiotics for urinary, chest and some other infections.' },
      { slug: 'ofloxacin', name: 'Ofloxacin', brandsIndia: ['Oflox', 'Zanocin', 'Zenflox'], brandsWorld: ['Floxin'], blurb: 'Ofloxacin is a fluoroquinolone antibiotic for urinary, gut and other infections.' },
      { slug: 'norfloxacin', name: 'Norfloxacin', brandsIndia: ['Norflox', 'Uritas'], brandsWorld: ['Noroxin'], blurb: 'Norfloxacin is a fluoroquinolone often used for urinary and gut infections.' },
      { slug: 'moxifloxacin', name: 'Moxifloxacin', brandsIndia: ['Moxif', 'MoxiCip', 'Moximax'], brandsWorld: ['Avelox'], blurb: 'Moxifloxacin is a fluoroquinolone for respiratory and some eye infections.' },
    ],
  },
  {
    class: 'Antifungal',
    desc: 'Antifungals treat fungal infections of the skin, nails, mouth or internal organs.',
    uses: ['Ringworm and skin fungal infections', 'Nail and scalp fungal infections', 'Thrush (candida)', 'Some serious internal fungal infections'],
    sideEffects: ['Tummy upset or nausea', 'Headache', 'Skin reactions (topical)'],
    precautions: ['Long courses may need liver checks (oral ones)', 'Many interact with other medicines', 'Complete the full course for full cure'],
    warnings: ['Yellow eyes or dark urine (liver — oral antifungals)', 'Severe rash or allergy', 'Palpitations with some antifungals'],
    faqs: [
      { q: 'Why do fungal infections take so long to treat?', a: 'Fungi grow slowly and live in skin, nails and hair, so treatment often continues for weeks — and nails can take months.' },
      { q: 'Do I need tablets or is cream enough?', a: 'Small skin patches often clear with cream; widespread, scalp or nail infections usually need tablets. A doctor decides.' },
    ],
    members: [
      { slug: 'fluconazole', name: 'Fluconazole', brandsIndia: ['Forcan', 'Zocon', 'Flucos'], brandsWorld: ['Diflucan'], blurb: 'Fluconazole is a widely used antifungal for thrush and skin fungal infections.' },
      { slug: 'itraconazole', name: 'Itraconazole', brandsIndia: ['Itaspor', 'Canditral', 'Sporanox'], brandsWorld: ['Sporanox'], blurb: 'Itraconazole is an oral antifungal for stubborn skin, nail and internal fungal infections.' },
      { slug: 'terbinafine', name: 'Terbinafine', brandsIndia: ['Terbicip', 'Sebifin', 'Lamisil'], brandsWorld: ['Lamisil'], blurb: 'Terbinafine is a first-choice antifungal for ringworm and nail infections.' },
      { slug: 'clotrimazole', name: 'Clotrimazole', brandsIndia: ['Candid', 'Clotrimazole', 'Surfaz'], brandsWorld: ['Canesten', 'Lotrimin'], blurb: 'Clotrimazole is a topical antifungal cream/powder for skin and vaginal thrush.' },
      { slug: 'ketoconazole', name: 'Ketoconazole', brandsIndia: ['Ketostar', 'Nizral', 'Danruf'], brandsWorld: ['Nizoral'], blurb: 'Ketoconazole is used mainly as a shampoo/cream for dandruff and skin fungal infections.' },
      { slug: 'griseofulvin', name: 'Griseofulvin', brandsIndia: ['Grisovin FP', 'Walavin'], brandsWorld: ['Gris-PEG'], blurb: 'Griseofulvin is an older oral antifungal used for scalp ringworm, especially in children.' },
    ],
  },
  {
    class: 'Antiviral',
    desc: 'Antivirals treat specific viral infections such as herpes, shingles or influenza.',
    uses: ['Cold sores, genital herpes and shingles', 'Chickenpox in some cases', 'Influenza (certain ones)'],
    sideEffects: ['Nausea', 'Headache', 'Tiredness'],
    precautions: ['Start early for best effect', 'Drink plenty of fluids', 'Dose is adjusted in kidney disease'],
    warnings: ['Confusion or reduced urine (kidney effect)', 'Severe rash or allergy'],
    faqs: [
      { q: 'Do antivirals cure herpes?', a: 'They do not remove the virus for good, but they shorten outbreaks, ease symptoms and can reduce how often attacks happen.' },
      { q: 'Why start antivirals early?', a: 'They work best in the first day or two of symptoms, before the virus multiplies, so starting promptly matters.' },
    ],
    members: [
      { slug: 'acyclovir', name: 'Acyclovir (Aciclovir)', brandsIndia: ['Acivir', 'Zovirax', 'Ocuvir'], brandsWorld: ['Zovirax'], blurb: 'Acyclovir treats cold sores, genital herpes, shingles and chickenpox.' },
      { slug: 'valacyclovir', name: 'Valacyclovir', brandsIndia: ['Valcivir', 'Valtoval', 'Vdevelox'], brandsWorld: ['Valtrex'], blurb: 'Valacyclovir is a convenient form of acyclovir for herpes and shingles.' },
      { slug: 'oseltamivir', name: 'Oseltamivir (Tamiflu)', brandsIndia: ['Fluvir', 'Antiflu', 'Tamiflu'], brandsWorld: ['Tamiflu'], blurb: 'Oseltamivir treats and prevents influenza, including H1N1 (swine flu), when started early.' },
    ],
  },
  {
    class: 'Antihistamine (allergy)',
    desc: 'Antihistamines relieve allergy symptoms such as sneezing, itching, runny nose and hives.',
    uses: ['Allergic rhinitis (hay fever)', 'Hives and itching', 'Allergic skin and eye symptoms', 'Some are used for sleep or nausea'],
    sideEffects: ['Drowsiness (more with older ones)', 'Dry mouth', 'Headache'],
    precautions: ['Be careful driving if drowsy', 'Alcohol increases drowsiness', 'Older antihistamines need caution in the elderly'],
    warnings: ['Severe allergic reaction (rare)', 'Excess drowsiness or confusion'],
    faqs: [
      { q: 'Which antihistamines are non-drowsy?', a: 'Newer ones like fexofenadine, loratadine and bilastine cause little drowsiness, while older ones like chlorpheniramine and hydroxyzine are more sedating.' },
      { q: 'Can I take antihistamines every day?', a: 'Newer ones are generally safe for daily use in allergy seasons; discuss long-term use with a doctor.' },
    ],
    members: [
      { slug: 'fexofenadine', name: 'Fexofenadine', brandsIndia: ['Allegra', 'Fexo', 'Histafree'], brandsWorld: ['Allegra'], blurb: 'Fexofenadine is a non-drowsy antihistamine for hay fever and hives.' },
      { slug: 'loratadine', name: 'Loratadine', brandsIndia: ['Lorfast', 'Alaspan', 'Loridin'], brandsWorld: ['Claritin', 'Clarityn'], blurb: 'Loratadine is a once-daily, low-drowsiness antihistamine.' },
      { slug: 'desloratadine', name: 'Desloratadine', brandsIndia: ['Deslor', 'Deslor', 'Dazit'], brandsWorld: ['Clarinex', 'Aerius'], blurb: 'Desloratadine is a non-drowsy antihistamine, the active form of loratadine.' },
      { slug: 'hydroxyzine', name: 'Hydroxyzine', brandsIndia: ['Atarax', 'Hyzine'], brandsWorld: ['Atarax', 'Vistaril'], blurb: 'Hydroxyzine is a sedating antihistamine used for itching, hives and anxiety.' },
      { slug: 'chlorpheniramine', name: 'Chlorpheniramine (CPM)', brandsIndia: ['Piriton', 'CPM', 'Cadistin'], brandsWorld: ['Chlor-Trimeton', 'Piriton'], blurb: 'Chlorpheniramine is an older sedating antihistamine, common in cold and cough combinations.' },
      { slug: 'bilastine', name: 'Bilastine', brandsIndia: ['Bilagram', 'Blorm', 'Bilafast'], brandsWorld: ['Bilaxten', 'Ilaxten'], blurb: 'Bilastine is a newer non-drowsy antihistamine for allergies and hives.' },
    ],
  },
  {
    class: 'Acidity, antacid & gut medicine',
    desc: 'These treat acidity, indigestion, ulcers, spasm and bowel problems.',
    uses: ['Acidity, heartburn and reflux', 'Stomach cramps and spasm', 'Constipation or diarrhoea (specific ones)', 'Nausea and bloating'],
    sideEffects: ['Constipation or diarrhoea', 'Bloating or wind', 'Drowsiness (with some antispasmodics)'],
    precautions: ['Do not ignore ongoing symptoms without a diagnosis', 'Some interact with other medicines', 'Use laxatives short-term'],
    warnings: ['Weight loss, difficulty swallowing or black stools (see a doctor)', 'Severe or persistent tummy pain', 'Blood in vomit or stools'],
    faqs: [
      { q: 'When should acidity be checked by a doctor?', a: 'See a doctor for alarm symptoms — weight loss, difficulty swallowing, black stools, vomiting blood, or symptoms that do not settle with usual treatment.' },
      { q: 'Are antacids and acid-reducers the same?', a: 'No — antacids neutralise acid for quick, short relief, while acid-reducers (PPIs/H2 blockers) lower acid production for longer control.' },
    ],
    members: [
      { slug: 'esomeprazole', name: 'Esomeprazole', brandsIndia: ['Nexpro', 'Esoz', 'Sompraz'], brandsWorld: ['Nexium'], blurb: 'Esomeprazole is a proton-pump inhibitor for reflux and ulcers.' },
      { slug: 'lansoprazole', name: 'Lansoprazole', brandsIndia: ['Lan', 'Lanzol', 'Junior Lanzol'], brandsWorld: ['Prevacid'], blurb: 'Lansoprazole is a proton-pump inhibitor for acidity and ulcers.' },
      { slug: 'famotidine', name: 'Famotidine', brandsIndia: ['Famocid', 'Topcid'], brandsWorld: ['Pepcid'], blurb: 'Famotidine is an H2 blocker that reduces stomach acid, gentler than PPIs for mild acidity.' },
      { slug: 'sucralfate', name: 'Sucralfate', brandsIndia: ['Sucrafil', 'Pepticaine'], brandsWorld: ['Carafate'], blurb: 'Sucralfate coats and protects ulcers and inflamed stomach lining.' },
      { slug: 'metoclopramide', name: 'Metoclopramide', brandsIndia: ['Perinorm', 'Reglan'], brandsWorld: ['Reglan', 'Maxolon'], blurb: 'Metoclopramide relieves nausea and helps the stomach empty; used short-term.' },
      { slug: 'dicyclomine', name: 'Dicyclomine (Cyclopam)', brandsIndia: ['Cyclopam', 'Colimex', 'Spasmonil'], brandsWorld: ['Bentyl'], blurb: 'Dicyclomine is an antispasmodic for stomach and period cramps.' },
      { slug: 'drotaverine', name: 'Drotaverine', brandsIndia: ['Drotin', 'Doverine', 'Drotakind'], brandsWorld: ['No-Spa'], blurb: 'Drotaverine relaxes smooth muscle to relieve cramping abdominal and period pain.' },
      { slug: 'loperamide', name: 'Loperamide', brandsIndia: ['Eldoper', 'Roko', 'Imodium'], brandsWorld: ['Imodium'], blurb: 'Loperamide slows the bowel to control non-infective diarrhoea (avoid with blood or high fever).' },
      { slug: 'lactulose', name: 'Lactulose', brandsIndia: ['Duphalac', 'Looz', 'Livoluk'], brandsWorld: ['Duphalac', 'Kristalose'], blurb: 'Lactulose is a gentle laxative for constipation and to lower ammonia in liver disease.' },
      { slug: 'bisacodyl', name: 'Bisacodyl (Dulcolax)', brandsIndia: ['Dulcoflex', 'Bisacodyl'], brandsWorld: ['Dulcolax'], blurb: 'Bisacodyl is a stimulant laxative for short-term constipation relief.' },
      { slug: 'ispaghula-husk', name: 'Ispaghula Husk (Isabgol)', brandsIndia: ['Isabgol', 'Naturolax', 'Fybogel'], brandsWorld: ['Metamucil', 'Fybogel'], blurb: 'Ispaghula (psyllium) is a fibre supplement for constipation and gut health.' },
    ],
  },
  {
    class: 'Respiratory / cough & cold medicine',
    desc: 'These ease breathing, loosen mucus or calm a cough in chest and airway conditions.',
    uses: ['Asthma and COPD (inhalers)', 'Loosening or calming a cough', 'Wheeze and breathlessness', 'Blocked airways'],
    sideEffects: ['Shakiness or fast heartbeat (relievers)', 'Hoarseness or oral thrush (steroid inhalers)', 'Drowsiness (some cough medicines)'],
    precautions: ['Rinse the mouth after steroid inhalers', 'Use a spacer with inhalers for better delivery', 'Do not rely on cough syrup for a lasting cough — get it checked'],
    warnings: ['Severe breathlessness, blue lips or unable to speak (emergency)', 'Reliever inhaler not working', 'A cough lasting more than 3 weeks or with blood'],
    faqs: [
      { q: 'What is the difference between a reliever and a preventer inhaler?', a: 'A reliever opens the airways quickly during symptoms; a preventer (often a steroid) is taken daily to reduce inflammation and prevent attacks.' },
      { q: 'Do cough syrups actually work?', a: 'Evidence is limited. Fluids, steam and treating the cause help most. A lasting or severe cough should be checked rather than just suppressed.' },
    ],
    members: [
      { slug: 'budesonide', name: 'Budesonide (inhaler)', brandsIndia: ['Budecort', 'Budez'], brandsWorld: ['Pulmicort', 'Rhinocort'], blurb: 'Budesonide is an inhaled steroid preventer that reduces airway inflammation in asthma.' },
      { slug: 'fluticasone', name: 'Fluticasone (inhaler/nasal)', brandsIndia: ['Flohale', 'Flomist', 'Seroflo (with salmeterol)'], brandsWorld: ['Flovent', 'Flonase'], blurb: 'Fluticasone is an inhaled/nasal steroid for asthma and allergic rhinitis.' },
      { slug: 'ipratropium', name: 'Ipratropium', brandsIndia: ['Ipravent', 'Duolin (with salbutamol)'], brandsWorld: ['Atrovent'], blurb: 'Ipratropium is an inhaled bronchodilator, often combined with salbutamol for COPD.' },
      { slug: 'formoterol', name: 'Formoterol', brandsIndia: ['Foracort (combo)', 'Formonide'], brandsWorld: ['Foradil', 'Symbicort (combo)'], blurb: 'Formoterol is a long-acting airway opener used with an inhaled steroid in asthma/COPD.' },
      { slug: 'theophylline', name: 'Theophylline', brandsIndia: ['Deriphyllin', 'Theobid'], brandsWorld: ['Theo-24', 'Uniphyl'], blurb: 'Theophylline is an older oral airway opener for asthma and COPD, needing careful monitoring.' },
      { slug: 'ambroxol', name: 'Ambroxol', brandsIndia: ['Ambrolite', 'Mucolite', 'Ambrodil'], brandsWorld: ['Mucosolvan'], blurb: 'Ambroxol is a mucolytic that thins and loosens chest mucus.' },
      { slug: 'dextromethorphan', name: 'Dextromethorphan (cough)', brandsIndia: ['Corex DX', 'Benadryl DR'], brandsWorld: ['Robitussin DM', 'Delsym'], blurb: 'Dextromethorphan is a cough suppressant for a dry, tickly cough.' },
      { slug: 'guaifenesin', name: 'Guaifenesin (expectorant)', brandsIndia: ['Grilinctus', 'Ascoril (combo)'], brandsWorld: ['Mucinex', 'Robitussin'], blurb: 'Guaifenesin is an expectorant that helps clear a chesty, productive cough.' },
    ],
  },
  {
    class: 'Antidepressant / anti-anxiety',
    desc: 'These treat depression, anxiety and related conditions, and some also help nerve pain or sleep.',
    uses: ['Depression', 'Anxiety and panic', 'OCD, PTSD and related conditions', 'Nerve pain or sleep (some)'],
    sideEffects: ['Nausea or sleep changes early on', 'Sexual side effects (SSRIs)', 'Drowsiness or dizziness (some)'],
    precautions: ['Full effect takes 4–6 weeks — do not stop early', 'Do not stop suddenly (taper to avoid withdrawal)', 'Tell your doctor about all other medicines'],
    warnings: ['Worsening mood or thoughts of self-harm, especially early — seek help urgently', 'Agitation, high fever or confusion (rare serotonin syndrome)', 'Unusual bleeding (SSRIs)'],
    faqs: [
      { q: 'How long do antidepressants take to work?', a: 'Some effects appear in 1–2 weeks, but full benefit usually takes 4–6 weeks. Keep taking them and stay in touch with your doctor.' },
      { q: 'Can I stop antidepressants once I feel better?', a: 'Not suddenly — stopping should be gradual and doctor-guided, and treatment often continues a while after recovery to prevent relapse.' },
    ],
    members: [
      { slug: 'escitalopram', name: 'Escitalopram', brandsIndia: ['Nexito', 'Cipralex', 'Escitalent'], brandsWorld: ['Lexapro', 'Cipralex'], blurb: 'Escitalopram is a widely used SSRI for depression and anxiety.' },
      { slug: 'fluoxetine', name: 'Fluoxetine (Prozac)', brandsIndia: ['Fludac', 'Flunil', 'Prodep'], brandsWorld: ['Prozac'], blurb: 'Fluoxetine is a long-acting SSRI for depression, OCD and related conditions.' },
      { slug: 'paroxetine', name: 'Paroxetine', brandsIndia: ['Paxidep', 'Xet', 'Pari'], brandsWorld: ['Paxil', 'Seroxat'], blurb: 'Paroxetine is an SSRI for depression and anxiety disorders.' },
      { slug: 'amitriptyline', name: 'Amitriptyline', brandsIndia: ['Tryptomer', 'Amitone'], brandsWorld: ['Elavil'], blurb: 'Amitriptyline is a tricyclic used in low doses for nerve pain, migraine prevention and sleep.' },
      { slug: 'duloxetine', name: 'Duloxetine', brandsIndia: ['Duzela', 'Dulane', 'Delok'], brandsWorld: ['Cymbalta'], blurb: 'Duloxetine treats depression and anxiety and also helps nerve pain.' },
      { slug: 'venlafaxine', name: 'Venlafaxine', brandsIndia: ['Venlor', 'Veniz', 'Ventab'], brandsWorld: ['Effexor'], blurb: 'Venlafaxine is an SNRI for depression and anxiety.' },
      { slug: 'mirtazapine', name: 'Mirtazapine', brandsIndia: ['Mirtaz', 'Mirt', 'Mirnite'], brandsWorld: ['Remeron'], blurb: 'Mirtazapine is an antidepressant that also improves sleep and appetite.' },
    ],
  },
  {
    class: 'Sedative / anti-anxiety (benzodiazepine group)',
    desc: 'These calm the nervous system for short-term anxiety, sleep or seizures. They can cause dependence, so they are used carefully and short-term.',
    uses: ['Short-term severe anxiety', 'Short-term sleep problems', 'Some seizures and muscle spasm', 'Alcohol-withdrawal (medically supervised)'],
    sideEffects: ['Drowsiness and dizziness', 'Poor concentration or memory', 'Unsteadiness'],
    precautions: ['Use for the shortest time possible (dependence risk)', 'Do not drive if drowsy; avoid alcohol', 'Do not stop suddenly after regular use (taper)'],
    warnings: ['Severe drowsiness or breathing problems (especially with opioids/alcohol)', 'Confusion or falls, especially in the elderly', 'Withdrawal symptoms if stopped abruptly'],
    faqs: [
      { q: 'Are these medicines addictive?', a: 'They can cause dependence with regular use, so they are prescribed short-term and tapered off rather than stopped suddenly.' },
      { q: 'Why should I avoid alcohol with them?', a: 'Both slow the nervous system, and together they can dangerously reduce alertness and breathing.' },
    ],
    members: [
      { slug: 'clonazepam', name: 'Clonazepam', brandsIndia: ['Clonotril', 'Rivotril', 'Lonazep'], brandsWorld: ['Klonopin', 'Rivotril'], blurb: 'Clonazepam is used for certain seizures and severe anxiety; it can cause dependence.' },
      { slug: 'alprazolam', name: 'Alprazolam', brandsIndia: ['Alprax', 'Restyl', 'Trika'], brandsWorld: ['Xanax'], blurb: 'Alprazolam is a short-acting anti-anxiety medicine for short-term use only, with dependence risk.' },
      { slug: 'diazepam', name: 'Diazepam (Valium)', brandsIndia: ['Valium', 'Calmpose', 'Dizy'], brandsWorld: ['Valium'], blurb: 'Diazepam is used for anxiety, muscle spasm, seizures and alcohol withdrawal, short-term.' },
      { slug: 'lorazepam', name: 'Lorazepam', brandsIndia: ['Ativan', 'Lorazep', 'Larpose'], brandsWorld: ['Ativan'], blurb: 'Lorazepam is used for short-term anxiety and, by injection, for seizures.' },
      { slug: 'etizolam', name: 'Etizolam', brandsIndia: ['Etizola', 'Etilaam', 'Depitin'], brandsWorld: ['Etizest'], blurb: 'Etizolam is a benzodiazepine-like anti-anxiety medicine used short-term in some countries.' },
    ],
  },
  {
    class: 'Antipsychotic / mood stabiliser',
    desc: 'These treat serious mental-health conditions such as psychosis, bipolar disorder and severe agitation.',
    uses: ['Schizophrenia and psychosis', 'Bipolar disorder', 'Severe agitation', 'Add-on for hard-to-treat depression (some)'],
    sideEffects: ['Drowsiness', 'Weight gain and raised blood sugar (some)', 'Movement stiffness or restlessness'],
    precautions: ['Regular monitoring of weight, sugar and lipids', 'Do not stop suddenly', 'Caution in the elderly with dementia'],
    warnings: ['High fever with muscle stiffness and confusion (rare, serious — urgent)', 'Uncontrolled movements', 'Very high blood sugar'],
    faqs: [
      { q: 'Do antipsychotics cause weight gain?', a: 'Several can increase appetite, weight and blood sugar, so these are monitored. The benefit for serious conditions usually outweighs this, and your doctor manages it.' },
      { q: 'Can I stop an antipsychotic when I feel well?', a: 'Not on your own — stopping can trigger relapse. Any change should be planned with your psychiatrist.' },
    ],
    members: [
      { slug: 'olanzapine', name: 'Olanzapine', brandsIndia: ['Oleanz', 'Olimelt', 'Olanex'], brandsWorld: ['Zyprexa'], blurb: 'Olanzapine treats schizophrenia and bipolar disorder; it can increase weight and sugar.' },
      { slug: 'risperidone', name: 'Risperidone', brandsIndia: ['Risdone', 'Sizodon', 'Respidon'], brandsWorld: ['Risperdal'], blurb: 'Risperidone is used for schizophrenia, bipolar disorder and severe irritability.' },
      { slug: 'quetiapine', name: 'Quetiapine', brandsIndia: ['Qutan', 'Seroquin', 'Q-Pin'], brandsWorld: ['Seroquel'], blurb: 'Quetiapine treats schizophrenia and bipolar disorder and is sometimes used for sleep at low doses.' },
      { slug: 'aripiprazole', name: 'Aripiprazole', brandsIndia: ['Arip MT', 'Asprito', 'Arpizol'], brandsWorld: ['Abilify'], blurb: 'Aripiprazole is an antipsychotic with generally less weight gain than some others.' },
    ],
  },
  {
    class: 'Anti-epileptic (seizure medicine)',
    desc: 'These control seizures in epilepsy and are sometimes used for nerve pain or mood.',
    uses: ['Epilepsy and seizure control', 'Some nerve pain', 'Mood stabilising (some)'],
    sideEffects: ['Drowsiness or dizziness', 'Unsteadiness', 'Mood or behaviour changes'],
    precautions: ['Do not stop suddenly (seizure risk)', 'Some interact with many medicines and contraception', 'Certain ones need blood-level or organ monitoring'],
    warnings: ['A serious skin rash (stop and seek care urgently)', 'Thoughts of self-harm or marked mood change', 'Yellow eyes or easy bruising (liver/blood effects)'],
    faqs: [
      { q: 'Can epilepsy medicines be stopped once seizures stop?', a: 'Only under specialist guidance after a long seizure-free period — stopping suddenly or too soon can bring seizures back.' },
      { q: 'Do these affect the contraceptive pill?', a: 'Some do, reducing its effect, so discuss reliable contraception with your doctor if you take them.' },
    ],
    members: [
      { slug: 'levetiracetam', name: 'Levetiracetam', brandsIndia: ['Levipil', 'Levroxa', 'Torleva'], brandsWorld: ['Keppra'], blurb: 'Levetiracetam is a widely used, well-tolerated epilepsy medicine.' },
      { slug: 'valproate', name: 'Sodium Valproate', brandsIndia: ['Valparin', 'Encorate', 'Divaa'], brandsWorld: ['Depakote', 'Epilim'], blurb: 'Valproate controls several seizure types and stabilises mood; avoided in pregnancy.' },
      { slug: 'carbamazepine', name: 'Carbamazepine', brandsIndia: ['Tegrital', 'Zeptol', 'Mazetol'], brandsWorld: ['Tegretol'], blurb: 'Carbamazepine treats epilepsy and nerve pain such as trigeminal neuralgia.' },
      { slug: 'phenytoin', name: 'Phenytoin', brandsIndia: ['Eptoin', 'Dilantin'], brandsWorld: ['Dilantin'], blurb: 'Phenytoin is an older epilepsy medicine needing blood-level monitoring.' },
      { slug: 'lamotrigine', name: 'Lamotrigine', brandsIndia: ['Lamitor', 'Lametec', 'Lamodep'], brandsWorld: ['Lamictal'], blurb: 'Lamotrigine treats epilepsy and stabilises mood in bipolar disorder; the dose is increased slowly to avoid rash.' },
      { slug: 'clobazam', name: 'Clobazam', brandsIndia: ['Frisium', 'Clobam'], brandsWorld: ['Onfi', 'Frisium'], blurb: 'Clobazam is an add-on for certain seizures.' },
    ],
  },
  {
    class: 'Muscle relaxant',
    desc: 'These ease muscle spasm and stiffness in back pain, neck pain and muscle injuries.',
    uses: ['Muscle spasm and stiffness', 'Back and neck pain', 'Spasticity (some)'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Weakness or dry mouth'],
    precautions: ['Do not drive if drowsy', 'Avoid alcohol', 'Use short-term for acute pain'],
    warnings: ['Severe drowsiness', 'Marked weakness or fainting', 'Allergic reaction'],
    faqs: [
      { q: 'Why do muscle relaxants make me sleepy?', a: 'Many act on the nervous system, which commonly causes drowsiness. Avoid driving and alcohol while taking them.' },
      { q: 'How long should I take a muscle relaxant?', a: 'Usually a short course for acute spasm alongside pain relief and gentle movement — long-term use is generally avoided.' },
    ],
    members: [
      { slug: 'thiocolchicoside', name: 'Thiocolchicoside', brandsIndia: ['Myoril', 'Thiobax', 'Miothin'], brandsWorld: ['Muscoril'], blurb: 'Thiocolchicoside is a muscle relaxant for painful spasm, often combined with an NSAID.' },
      { slug: 'chlorzoxazone', name: 'Chlorzoxazone', brandsIndia: ['Parafon', 'Myogesic'], brandsWorld: ['Parafon Forte'], blurb: 'Chlorzoxazone relieves muscle spasm from strains and sprains.' },
      { slug: 'tizanidine', name: 'Tizanidine', brandsIndia: ['Sirdalud', 'Tizan', 'Brentzo'], brandsWorld: ['Zanaflex'], blurb: 'Tizanidine eases muscle spasm and spasticity.' },
      { slug: 'baclofen', name: 'Baclofen', brandsIndia: ['Liofen', 'Baclof', 'Skelemax'], brandsWorld: ['Lioresal', 'Gablofen'], blurb: 'Baclofen reduces spasticity in conditions affecting the nerves and spinal cord.' },
    ],
  },
  {
    class: 'Urology & men’s health',
    desc: 'These treat prostate enlargement, urinary symptoms and erectile dysfunction.',
    uses: ['Enlarged prostate (BPH) and urinary symptoms', 'Erectile dysfunction', 'Overactive bladder (some)'],
    sideEffects: ['Dizziness or low blood pressure', 'Headache and flushing (ED medicines)', 'Reduced semen or sexual changes (some)'],
    precautions: ['Do not combine ED medicines with nitrate heart drugs (dangerous)', 'Rise slowly to avoid dizziness', 'Tell your doctor about heart conditions'],
    warnings: ['Chest pain during activity — do not use ED drugs with nitrates', 'An erection lasting over 4 hours (emergency)', 'Fainting or sudden vision/hearing change'],
    faqs: [
      { q: 'Can I take Viagra-type medicines with heart tablets?', a: 'Never combine them with nitrate heart medicines — the combination can cause a dangerous drop in blood pressure. Always tell your doctor your heart history.' },
      { q: 'Do prostate medicines shrink the prostate?', a: 'Alpha-blockers relax the muscle to ease flow quickly; 5-alpha-reductase inhibitors (finasteride/dutasteride) slowly shrink the prostate over months.' },
    ],
    members: [
      { slug: 'tamsulosin', name: 'Tamsulosin', brandsIndia: ['Urimax', 'Veltam', 'Contiflo'], brandsWorld: ['Flomax'], blurb: 'Tamsulosin relaxes the prostate and bladder neck to ease urinary flow in BPH.' },
      { slug: 'finasteride', name: 'Finasteride', brandsIndia: ['Finast', 'Fincar', 'Finpecia'], brandsWorld: ['Proscar', 'Propecia'], blurb: 'Finasteride shrinks an enlarged prostate and, at low dose, treats male hair loss.' },
      { slug: 'dutasteride', name: 'Dutasteride', brandsIndia: ['Dutas', 'Duprost', 'Veltride'], brandsWorld: ['Avodart'], blurb: 'Dutasteride shrinks the prostate and is also used for hair loss.' },
      { slug: 'sildenafil', name: 'Sildenafil (Viagra)', brandsIndia: ['Manforce', 'Suhagra', 'Penegra'], brandsWorld: ['Viagra', 'Revatio'], blurb: 'Sildenafil treats erectile dysfunction; also used for pulmonary hypertension.' },
      { slug: 'tadalafil', name: 'Tadalafil (Cialis)', brandsIndia: ['Tadact', 'Megalis', 'Tadarise'], brandsWorld: ['Cialis', 'Adcirca'], blurb: 'Tadalafil is a long-acting erectile-dysfunction medicine, also used for BPH.' },
      { slug: 'solifenacin', name: 'Solifenacin', brandsIndia: ['Vesicare', 'Soliten', 'Cystofix'], brandsWorld: ['Vesicare'], blurb: 'Solifenacin calms an overactive bladder to reduce urgency and frequency.' },
    ],
  },
  {
    class: 'Blood thinner (anticoagulant)',
    desc: 'These reduce the blood’s tendency to clot, preventing strokes and dangerous clots.',
    uses: ['Preventing stroke in atrial fibrillation', 'Treating and preventing deep-vein clots and lung clots', 'After certain heart valve or clot conditions'],
    sideEffects: ['Easier bruising or bleeding', 'Nosebleeds or gum bleeding', 'Heavier periods'],
    precautions: ['Tell every doctor/dentist you take a blood thinner', 'Warfarin needs regular blood (INR) tests and diet consistency', 'Avoid unnecessary NSAIDs (bleeding risk)'],
    warnings: ['Black stools, blood in urine/vomit, or coughing blood', 'A severe headache or a bad fall (internal bleeding)', 'Bleeding that will not stop'],
    faqs: [
      { q: 'What is the difference between warfarin and newer blood thinners?', a: 'Warfarin needs regular INR blood tests and diet care; newer ones (like apixaban, rivaroxaban) have fixed doses and no routine testing, but are not suitable for every condition.' },
      { q: 'Can I take painkillers with a blood thinner?', a: 'Paracetamol is usually preferred; avoid NSAIDs like ibuprofen unless your doctor agrees, as they add to bleeding risk.' },
    ],
    members: [
      { slug: 'warfarin', name: 'Warfarin', brandsIndia: ['Warf', 'Uniwarfin'], brandsWorld: ['Coumadin', 'Jantoven'], blurb: 'Warfarin is a long-established blood thinner needing regular INR monitoring.' },
      { slug: 'dabigatran', name: 'Dabigatran', brandsIndia: ['Pradaxa', 'Dabimet'], brandsWorld: ['Pradaxa'], blurb: 'Dabigatran is a newer fixed-dose blood thinner for atrial fibrillation and clots.' },
      { slug: 'rivaroxaban', name: 'Rivaroxaban', brandsIndia: ['Xarelto', 'Rivaroxa'], brandsWorld: ['Xarelto'], blurb: 'Rivaroxaban is a once-daily blood thinner for AF and clot prevention.' },
      { slug: 'apixaban', name: 'Apixaban', brandsIndia: ['Eliquis', 'Apixabid'], brandsWorld: ['Eliquis'], blurb: 'Apixaban is a twice-daily blood thinner with a good safety profile for AF and clots.' },
    ],
  },
  {
    class: 'Heart medicine (angina, rhythm & failure)',
    desc: 'These support the heart in angina, heart failure and rhythm problems.',
    uses: ['Angina (chest pain)', 'Heart failure', 'Certain heart rhythm problems', 'After a heart attack'],
    sideEffects: ['Headache or flushing (nitrates)', 'Slow pulse (some)', 'Dizziness'],
    precautions: ['Nitrates must never be combined with ED medicines', 'Do not stop heart medicines suddenly', 'Report a very slow or irregular pulse'],
    warnings: ['Fainting or severe dizziness', 'Very slow or very fast pulse', 'Worsening breathlessness or swelling'],
    faqs: [
      { q: 'How do nitrates help chest pain?', a: 'They widen blood vessels so the heart gets more oxygen with less effort, relieving angina. A spray/tablet under the tongue works within minutes.' },
      { q: 'What should I do if angina is not relieved?', a: 'If chest pain does not settle with rest and your usual nitrate, treat it as a possible heart attack and seek emergency care.' },
    ],
    members: [
      { slug: 'isosorbide-mononitrate', name: 'Isosorbide Mononitrate', brandsIndia: ['Monotrate', 'Ismo', 'Isordil (dinitrate)'], brandsWorld: ['Imdur', 'Monoket'], blurb: 'Isosorbide mononitrate is a nitrate that prevents angina by widening blood vessels.' },
      { slug: 'nitroglycerin', name: 'Nitroglycerin (GTN)', brandsIndia: ['Angispray', 'Nitrocontin', 'GTN'], brandsWorld: ['Nitrostat', 'Nitro-Dur'], blurb: 'Nitroglycerin is a fast-acting nitrate spray/tablet for sudden angina.' },
      { slug: 'digoxin', name: 'Digoxin', brandsIndia: ['Lanoxin', 'Digoxin'], brandsWorld: ['Lanoxin'], blurb: 'Digoxin steadies certain fast heart rhythms and supports a failing heart; it needs careful dosing.' },
      { slug: 'ivabradine', name: 'Ivabradine', brandsIndia: ['Ivabrad', 'Inapure', 'Bradia'], brandsWorld: ['Corlanor', 'Procoralan'], blurb: 'Ivabradine slows a fast heart rate in angina and heart failure.' },
      { slug: 'ticagrelor', name: 'Ticagrelor', brandsIndia: ['Brilinta', 'Ticaflo', 'Axcer'], brandsWorld: ['Brilinta', 'Brilique'], blurb: 'Ticagrelor is an antiplatelet used with aspirin after a heart attack or stent.' },
    ],
  },
  {
    class: 'Antiparasitic / anthelmintic',
    desc: 'These treat worm infestations and parasitic infections.',
    uses: ['Intestinal worms (roundworm, threadworm, hookworm)', 'Some parasitic skin and tissue infections', 'Mass deworming programmes', 'Filariasis (specific ones)'],
    sideEffects: ['Mild tummy upset', 'Nausea', 'Headache or dizziness'],
    precautions: ['Treat close contacts and maintain hygiene (worms)', 'Some are avoided in pregnancy', 'Follow-up doses may be needed'],
    warnings: ['Severe allergic reaction', 'Yellow eyes (rare liver effect with long courses)', 'Neurological symptoms with certain heavy infections (specialist care)'],
    faqs: [
      { q: 'How often should children be dewormed?', a: 'In many areas routine deworming is advised every 6 months in childhood; follow your local programme or doctor’s advice.' },
      { q: 'Do I need to treat my whole family for worms?', a: 'For threadworms especially, treating the household together and good hand/hygiene measures help prevent reinfection.' },
    ],
    members: [
      { slug: 'albendazole', name: 'Albendazole', brandsIndia: ['Zentel', 'Bandy', 'Albezol'], brandsWorld: ['Albenza'], blurb: 'Albendazole is a broad deworming medicine for common intestinal worms.' },
      { slug: 'mebendazole', name: 'Mebendazole', brandsIndia: ['Mebex', 'Wormin'], brandsWorld: ['Vermox', 'Emverm'], blurb: 'Mebendazole treats threadworm, roundworm and other intestinal worms.' },
      { slug: 'ivermectin', name: 'Ivermectin', brandsIndia: ['Ivermectol', 'Iverjohn'], brandsWorld: ['Stromectol', 'Soolantra'], blurb: 'Ivermectin treats scabies and certain parasitic infections.' },
      { slug: 'praziquantel', name: 'Praziquantel', brandsIndia: ['Distocide', 'Cisticid'], brandsWorld: ['Biltricide'], blurb: 'Praziquantel treats tapeworm and fluke infections.' },
      { slug: 'diethylcarbamazine', name: 'Diethylcarbamazine (DEC)', brandsIndia: ['Banocide Forte', 'Hetrazan'], brandsWorld: ['Hetrazan'], blurb: 'DEC is the main medicine for lymphatic filariasis in India’s elimination programme.' },
      { slug: 'hydroxychloroquine', name: 'Hydroxychloroquine (HCQS)', brandsIndia: ['HCQS', 'Oxcq', 'Zyq'], brandsWorld: ['Plaquenil'], blurb: 'Hydroxychloroquine is used for malaria and for autoimmune diseases like lupus and rheumatoid arthritis.' },
      { slug: 'chloroquine', name: 'Chloroquine', brandsIndia: ['Lariago', 'Emquin'], brandsWorld: ['Aralen'], blurb: 'Chloroquine is an older antimalarial still used for certain malaria and amoebic infections.' },
    ],
  },
  {
    class: 'Skin (dermatology) medicine',
    desc: 'These treat skin infections, inflammation, acne and parasites, mostly applied to the skin.',
    uses: ['Skin and wound infections', 'Eczema and inflammatory rashes (steroid creams)', 'Acne', 'Scabies and lice'],
    sideEffects: ['Local irritation, burning or dryness', 'Skin thinning with strong steroids (long use)', 'Sun sensitivity (some acne creams)'],
    precautions: ['Use steroid creams thinly, for limited periods, as directed', 'Avoid strong steroids on the face unless told to', 'Use sun protection with retinoid/acne creams'],
    warnings: ['Spreading redness, pus or fever (worsening infection)', 'Severe burning or allergic rash', 'Skin thinning or stretch marks from steroid overuse'],
    faqs: [
      { q: 'Are steroid creams safe for the face?', a: 'Only mild ones, briefly, and usually on medical advice — strong steroids on the face can cause thinning, redness and other problems.' },
      { q: 'How long can I use a steroid cream?', a: 'Use it for the short course your doctor advises. Long-term unsupervised use, especially of strong ones, can damage the skin.' },
    ],
    members: [
      { slug: 'mupirocin', name: 'Mupirocin', brandsIndia: ['Bactroban', 'T-Bact', 'Mupinase'], brandsWorld: ['Bactroban', 'Centany'], blurb: 'Mupirocin is an antibiotic ointment for impetigo and minor skin infections.' },
      { slug: 'fusidic-acid', name: 'Fusidic Acid', brandsIndia: ['Fucidin', 'Fusiwal', 'Fudic'], brandsWorld: ['Fucidin'], blurb: 'Fusidic acid is an antibiotic cream for skin infections like impetigo.' },
      { slug: 'clobetasol', name: 'Clobetasol', brandsIndia: ['Tenovate', 'Clobetamos'], brandsWorld: ['Temovate', 'Dermovate'], blurb: 'Clobetasol is a very strong steroid cream for severe skin conditions, used briefly.' },
      { slug: 'betamethasone-cream', name: 'Betamethasone (skin)', brandsIndia: ['Betnovate', 'Betnesol'], brandsWorld: ['Betnovate', 'Diprosone'], blurb: 'Betamethasone is a potent steroid cream for eczema and inflammatory skin conditions.' },
      { slug: 'permethrin', name: 'Permethrin', brandsIndia: ['Permite', 'Scabper'], brandsWorld: ['Elimite', 'Nix'], blurb: 'Permethrin cream/lotion treats scabies and head lice.' },
      { slug: 'benzoyl-peroxide', name: 'Benzoyl Peroxide', brandsIndia: ['Persol', 'Benzac', 'Brevoxyl'], brandsWorld: ['Benzac', 'PanOxyl'], blurb: 'Benzoyl peroxide is a first-line acne treatment that clears pores and bacteria.' },
      { slug: 'adapalene', name: 'Adapalene', brandsIndia: ['Adaferin', 'Deriva', 'Adapen'], brandsWorld: ['Differin'], blurb: 'Adapalene is a retinoid gel for acne that unclogs pores.' },
      { slug: 'ketoconazole-cream', name: 'Ketoconazole (cream/shampoo)', brandsIndia: ['Nizral', 'Ketostar', 'Danruf'], brandsWorld: ['Nizoral'], blurb: 'Ketoconazole cream/shampoo treats dandruff and skin fungal infections.' },
      { slug: 'calamine', name: 'Calamine Lotion', brandsIndia: ['Caladryl', 'Lacto Calamine'], brandsWorld: ['Caladryl'], blurb: 'Calamine soothes itching from rashes, insect bites and chickenpox.' },
    ],
  },
  {
    class: 'Vitamin & supplement',
    desc: 'Supplements correct deficiencies and support health when diet or absorption falls short.',
    uses: ['Correcting vitamin or mineral deficiency', 'Pregnancy and growth needs', 'Recovery after illness', 'General nutritional support'],
    sideEffects: ['Usually few at recommended doses', 'Tummy upset (some, e.g. iron, zinc)', 'Problems only with excessive doses'],
    precautions: ['More is not better — avoid megadoses without advice', 'Some interact with medicines (timing matters)', 'Deficiency is best confirmed by a test where possible'],
    warnings: ['Symptoms of overdose with fat-soluble vitamins (A, D, E, K) at high doses', 'Accidental iron overdose in children is an emergency'],
    faqs: [
      { q: 'Do I need supplements if I eat well?', a: 'A balanced diet covers most needs, but common gaps (vitamin D, B12, iron in some groups) may need supplements — ideally guided by a test.' },
      { q: 'Can I take too many vitamins?', a: 'Yes — especially fat-soluble vitamins (A, D, E, K) and iron, which can build up and cause harm. Stick to recommended amounts.' },
    ],
    members: [
      { slug: 'methylcobalamin-b12', name: 'Vitamin B12 (Methylcobalamin)', brandsIndia: ['Nurokind', 'Methylcobal', 'Neurobion Forte'], brandsWorld: ['(cyanocobalamin/methylcobalamin brands)'], blurb: 'Vitamin B12 corrects B12 deficiency, which causes tiredness, anaemia and nerve symptoms.' },
      { slug: 'vitamin-c', name: 'Vitamin C (Ascorbic Acid)', brandsIndia: ['Limcee', 'Celin', 'Redoxon'], brandsWorld: ['Redoxon', 'Emergen-C'], blurb: 'Vitamin C supports immunity, wound healing and iron absorption.' },
      { slug: 'folic-acid', name: 'Folic Acid', brandsIndia: ['Folvite', 'Folinext'], brandsWorld: ['(folic acid brands)'], blurb: 'Folic acid prevents certain anaemias and neural-tube defects — important before and in early pregnancy.' },
      { slug: 'zinc', name: 'Zinc', brandsIndia: ['Zincovit', 'Z&D', 'Zinconia'], brandsWorld: ['(zinc sulfate/gluconate brands)'], blurb: 'Zinc supports immunity and shortens childhood diarrhoea when given with ORS.' },
      { slug: 'multivitamin', name: 'Multivitamin', brandsIndia: ['Zincovit', 'Supradyn', 'A to Z', 'Becosules'], brandsWorld: ['Centrum', 'One A Day'], blurb: 'Multivitamins provide a mix of vitamins and minerals for general nutritional support.' },
      { slug: 'magnesium', name: 'Magnesium', brandsIndia: ['Mgluconate', 'Magnamit'], brandsWorld: ['(magnesium oxide/citrate brands)'], blurb: 'Magnesium supports muscle and nerve function and may help cramps and constipation.' },
      { slug: 'omega-3', name: 'Omega-3 (Fish Oil)', brandsIndia: ['Maxepa', 'Seven Seas', 'Omega'], brandsWorld: ['(fish-oil/omega-3 brands)'], blurb: 'Omega-3 fatty acids support heart health and can lower high triglycerides.' },
      { slug: 'vitamin-b-complex', name: 'Vitamin B-Complex', brandsIndia: ['Becosules', 'Neurobion', 'B-Long'], brandsWorld: ['(B-complex brands)'], blurb: 'B-complex provides the B vitamins together for energy and nerve health.' },
    ],
  },
  {
    class: 'Thyroid & hormone medicine',
    desc: 'These treat an overactive thyroid and some hormone-related conditions.',
    uses: ['Overactive thyroid (hyperthyroidism)', 'Preparing for thyroid surgery/radioiodine', 'Some hormone-related conditions'],
    sideEffects: ['Rash or itching', 'Joint or muscle aches', 'Rarely, low white blood cells'],
    precautions: ['Report a sore throat or fever promptly (blood-count effect)', 'Thyroid levels are monitored regularly', 'Dose changes with pregnancy'],
    warnings: ['Sore throat, mouth ulcers or fever (possible low white cells — urgent blood test)', 'Yellow eyes or dark urine (liver)', 'Severe rash'],
    faqs: [
      { q: 'How long are antithyroid medicines taken?', a: 'Often 12–18 months or longer, with regular thyroid tests. Some people need surgery or radioiodine for a lasting solution.' },
      { q: 'Why report a sore throat on these medicines?', a: 'Rarely they lower infection-fighting white cells, so a sore throat or fever needs a prompt blood check.' },
    ],
    members: [
      { slug: 'carbimazole', name: 'Carbimazole', brandsIndia: ['Neomercazole', 'Antithyrox'], brandsWorld: ['(carbimazole brands)'], blurb: 'Carbimazole is the main medicine for an overactive thyroid.' },
      { slug: 'methimazole', name: 'Methimazole', brandsIndia: ['Thyrozole', 'Methmr'], brandsWorld: ['Tapazole'], blurb: 'Methimazole treats hyperthyroidism (carbimazole converts to it in the body).' },
      { slug: 'propylthiouracil', name: 'Propylthiouracil (PTU)', brandsIndia: ['PTU', 'Thyrocil'], brandsWorld: ['(propylthiouracil brands)'], blurb: 'PTU treats overactive thyroid and is preferred in early pregnancy.' },
    ],
  },
  {
    class: 'Women’s health & hormones',
    desc: 'These treat heavy periods, hormonal and reproductive conditions.',
    uses: ['Heavy or irregular periods', 'Hormone support and contraception (some)', 'Fertility treatment (some)'],
    sideEffects: ['Nausea or breast tenderness', 'Mood changes', 'Spotting or cycle changes'],
    precautions: ['Some raise clot risk — tell your doctor about clot history', 'Not for use in pregnancy unless specified', 'Regular review with your doctor'],
    warnings: ['Leg swelling/pain or breathlessness (possible clot)', 'Severe headache or vision changes', 'Heavy unexpected bleeding'],
    faqs: [
      { q: 'Can tranexamic acid stop heavy periods?', a: 'Yes — it reduces heavy menstrual bleeding when taken during the period, and is a common non-hormonal option.' },
      { q: 'Are hormone medicines safe?', a: 'For most people, when prescribed appropriately, yes — but they carry specific risks (like clots) that your doctor weighs against the benefits.' },
    ],
    members: [
      { slug: 'tranexamic-acid', name: 'Tranexamic Acid', brandsIndia: ['Pause', 'Trapic', 'Texakind'], brandsWorld: ['Lysteda', 'Cyklokapron'], blurb: 'Tranexamic acid reduces heavy menstrual bleeding and other bleeding.' },
      { slug: 'norethisterone', name: 'Norethisterone', brandsIndia: ['Primolut N', 'Regestrone'], brandsWorld: ['Aygestin', 'Norlutate'], blurb: 'Norethisterone is a progestogen used to delay periods and treat heavy or irregular bleeding.' },
      { slug: 'medroxyprogesterone', name: 'Medroxyprogesterone', brandsIndia: ['Meprate', 'Deviry'], brandsWorld: ['Provera', 'Depo-Provera'], blurb: 'Medroxyprogesterone is a progestogen for menstrual disorders and contraception (injection).' },
      { slug: 'clomiphene', name: 'Clomiphene (Clomid)', brandsIndia: ['Fertyl', 'Ovofar', 'Siphene'], brandsWorld: ['Clomid', 'Serophene'], blurb: 'Clomiphene stimulates ovulation to help with fertility, including in PCOS.' },
    ],
  },
];
