// Patient-facing medicine/drug pages for MedDroid. Educational only — general
// information about what a medicine is for, common side effects and precautions.
// NO personalised dosing or prescriptions: every page defers the exact dose to a
// doctor/pharmacist and the leaflet in the pack. Brand names common in India are
// noted only to help people recognise the medicine.

export const DRUGS = [
  {
    slug: 'paracetamol',
    name: 'Paracetamol (Acetaminophen)',
    lede: 'Paracetamol is one of the most widely used medicines in the world for fever and mild-to-moderate pain. It is generally very safe at the right dose, but an overdose can seriously harm the liver — so it must be used carefully.',
    uses: ['Bringing down fever', 'Headache and body aches', 'Toothache and period pain', 'Pain from colds and flu', 'A first-choice painkiller in pregnancy (confirm with your doctor)'],
    sideEffects: ['Usually very well tolerated at the correct dose', 'Rare skin rash or allergic reaction', 'Liver damage only with overdose or in liver disease'],
    precautions: ['Do not take more than the daily limit on the pack', 'Many cold/flu combination products already contain paracetamol — do not double up', 'Use with caution in liver disease and with regular alcohol'],
    warnings: ['Taking too much is dangerous even if you feel fine at first — get medical help immediately after any overdose', 'Swelling of the face or lips, or trouble breathing (allergy)', 'Yellowing of the eyes or severe tummy pain (possible liver harm)'],
    faqs: [
      { q: 'Is paracetamol safe in pregnancy?', a: 'Paracetamol is generally considered the preferred painkiller in pregnancy when needed, at the lowest effective dose for the shortest time — but always confirm with your doctor.' },
      { q: 'Paracetamol or ibuprofen — which is better?', a: 'Paracetamol is gentler on the stomach and good for fever and general pain; ibuprofen also reduces inflammation. The best choice depends on the problem and your health — ask a pharmacist.' },
      { q: 'Can I take paracetamol with other medicines?', a: 'Usually yes, but check that cold, flu or pain products do not also contain paracetamol, or you could exceed the safe daily amount without realising.' },
    ],
    related: [['medicines/dolo-650', 'Dolo 650'], ['medicines/ibuprofen', 'Ibuprofen'], ['how-to-reduce-fever-at-home', 'How to reduce fever'], ['is-my-fever-serious', 'Is my fever serious?']],
  },
  {
    slug: 'dolo-650',
    name: 'Dolo 650 (Paracetamol 650 mg)',
    lede: 'Dolo 650 is India’s most prescribed paracetamol brand. Each tablet contains 650 mg of paracetamol and is used for fever and pain. It works exactly like any other paracetamol of the same strength.',
    uses: ['Fever, including viral fever and post-vaccination fever', 'Headache and body aches', 'Mild-to-moderate pain', 'Cold and flu symptoms'],
    sideEffects: ['Usually very well tolerated', 'Rare rash or allergic reaction', 'Liver harm only with overdose or existing liver disease'],
    precautions: ['Do not combine with other paracetamol-containing products', 'Stay within the daily limit advised by your doctor', 'Caution with liver disease and regular alcohol'],
    warnings: ['Overdose is dangerous even before you feel unwell — seek medical help at once', 'Yellow eyes, dark urine or severe tummy pain', 'Signs of allergy such as facial swelling or breathing difficulty'],
    faqs: [
      { q: 'Is Dolo 650 safe to take daily?', a: 'For short courses at the correct dose it is generally safe, but taking it every day over long periods should be under a doctor’s guidance, as excess paracetamol can harm the liver.' },
      { q: 'What is the difference between Dolo 650 and Dolo 500?', a: 'Only the strength — Dolo 650 has 650 mg of paracetamol per tablet and Dolo 500 has 500 mg. The medicine itself is the same.' },
      { q: 'Can I take Dolo 650 on an empty stomach?', a: 'Paracetamol can usually be taken with or without food. Follow the advice on the pack or from your doctor.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/ibuprofen', 'Ibuprofen'], ['diseases/viral-fever', 'Viral fever'], ['how-to-reduce-fever-at-home', 'How to reduce fever']],
  },
  {
    slug: 'ibuprofen',
    name: 'Ibuprofen (Brufen)',
    lede: 'Ibuprofen is an anti-inflammatory painkiller (NSAID) used for pain, swelling and fever. It works well but is harder on the stomach and kidneys than paracetamol, so it is used more carefully.',
    uses: ['Pain with inflammation (sprains, back pain, arthritis)', 'Period pain', 'Headache and dental pain', 'Fever'],
    sideEffects: ['Stomach upset, heartburn or indigestion', 'Nausea', 'Raised blood pressure with long-term use'],
    precautions: ['Take with or after food', 'Avoid with stomach ulcers, kidney disease or certain heart conditions', 'Use with caution in asthma, late pregnancy and the elderly'],
    warnings: ['Black or tarry stools, or vomiting blood (stomach bleeding)', 'Severe stomach pain', 'Swelling, breathlessness or a skin reaction (allergy)'],
    faqs: [
      { q: 'Can I take ibuprofen and paracetamol together?', a: 'They can often be used together or alternated for stronger pain relief, as they work differently. Check with a pharmacist, especially if you have other health conditions.' },
      { q: 'Should ibuprofen be taken with food?', a: 'Yes — taking it with or after food reduces the chance of stomach irritation.' },
      { q: 'Who should avoid ibuprofen?', a: 'People with stomach ulcers, kidney disease, certain heart problems, or in the later stages of pregnancy should generally avoid it or use it only on medical advice.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/aspirin', 'Aspirin'], ['diseases/gastritis', 'Gastritis'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)']],
  },
  {
    slug: 'aspirin',
    name: 'Aspirin',
    lede: 'Aspirin has two very different roles: at higher doses it relieves pain and fever, and at low doses it thins the blood to help prevent heart attacks and strokes in people at risk. It is not suitable for children.',
    uses: ['Low-dose: preventing clots in heart disease and after a stroke (on medical advice)', 'Higher-dose: pain and fever (less common now)', 'Given early during a suspected heart attack in adults'],
    sideEffects: ['Stomach irritation and heartburn', 'Increased tendency to bruise or bleed', 'Ringing in the ears at high doses'],
    precautions: ['Never give to children or teenagers (risk of Reye’s syndrome)', 'Avoid with bleeding disorders or active ulcers', 'Tell your dentist/surgeon before procedures'],
    warnings: ['Black stools, vomiting blood, or unusual bleeding', 'Severe allergic reaction or wheezing', 'Sudden severe stomach pain'],
    faqs: [
      { q: 'Should I take low-dose aspirin daily?', a: 'Only if your doctor advises it — usually for people with existing heart disease or high risk. Taken without need, it can cause bleeding, so it is not for everyone.' },
      { q: 'Aspirin or ibuprofen for pain?', a: 'Ibuprofen or paracetamol are now more commonly used for everyday pain. Aspirin’s main modern role is as a low-dose blood thinner.' },
      { q: 'Do I stop aspirin before surgery?', a: 'Sometimes — because it thins the blood. Always follow your doctor’s or surgeon’s specific instructions; do not stop a heart medicine on your own.' },
    ],
    related: [['medicines/ibuprofen', 'Ibuprofen'], ['diseases/heart-attack', 'Heart attack'], ['diseases/stroke', 'Stroke'], ['diseases/coronary-artery-disease', 'Coronary artery disease']],
  },
  {
    slug: 'metformin',
    name: 'Metformin',
    lede: 'Metformin is the most common first-choice medicine for type 2 diabetes. It lowers blood sugar mainly by reducing sugar released by the liver and helping the body respond to insulin. It does not usually cause low sugar on its own.',
    uses: ['Type 2 diabetes (first-line treatment)', 'Prediabetes in some cases', 'Polycystic ovary syndrome (PCOS) in some cases'],
    sideEffects: ['Nausea, diarrhoea or a metallic taste (often settle over time)', 'Reduced appetite', 'Low vitamin B12 with long-term use'],
    precautions: ['Take with food to reduce tummy upset', 'Needs kidney function checks', 'May be paused before scans with contrast dye and around surgery'],
    warnings: ['Lactic acidosis is rare but serious: muscle pain, deep or fast breathing, unusual tiredness and cold feeling — seek urgent care', 'Persistent vomiting or dehydration'],
    faqs: [
      { q: 'Does metformin cause weight loss?', a: 'It is weight-neutral or may cause modest weight loss for some people, unlike some other diabetes medicines that can cause weight gain.' },
      { q: 'Should I take metformin with food?', a: 'Yes — taking it with or just after meals reduces stomach side effects, which are the most common reason people struggle with it.' },
      { q: 'Can I stop metformin when my sugar is normal?', a: 'Not on your own. Normal sugar often means the medicine is working. Any change should be decided with your doctor, alongside diet and lifestyle.' },
    ],
    related: [['diseases/type-2-diabetes', 'Type 2 diabetes'], ['how-to-lower-blood-sugar', 'How to lower blood sugar'], ['blood-tests/hba1c', 'HbA1c test'], ['diseases/pcos', 'PCOS']],
  },
  {
    slug: 'amoxicillin',
    name: 'Amoxicillin',
    lede: 'Amoxicillin is a common penicillin-type antibiotic used for many bacterial infections. Like all antibiotics, it does not work against viruses (such as colds and most sore throats), and the full course should always be completed.',
    uses: ['Chest and ear infections', 'Dental and throat infections', 'Some urinary and skin infections', 'Part of treatment for stomach ulcers (H. pylori)'],
    sideEffects: ['Diarrhoea, nausea or tummy upset', 'Skin rash', 'Thrush (yeast infection)'],
    precautions: ['Tell your doctor about any penicillin allergy', 'Complete the full course even if you feel better', 'Antibiotics do not help viral infections'],
    warnings: ['Severe allergy: swelling of the face/throat, difficulty breathing (emergency)', 'Severe or bloody watery diarrhoea (possible C. difficile)', 'A widespread rash'],
    faqs: [
      { q: 'How quickly does amoxicillin work?', a: 'Many people start feeling better within 2–3 days, but you should still finish the whole course to fully clear the infection and reduce resistance.' },
      { q: 'Can I drink alcohol with amoxicillin?', a: 'A small amount is not usually dangerous with amoxicillin, but alcohol can worsen side effects and slow recovery, so it is best avoided.' },
      { q: 'Why must I finish the course?', a: 'Stopping early can leave surviving bacteria that regrow and become resistant, making future infections harder to treat.' },
    ],
    related: [['medicines/augmentin', 'Augmentin'], ['medicines/azithromycin', 'Azithromycin'], ['diseases/strep-throat', 'Strep throat'], ['diseases/pneumonia', 'Pneumonia']],
  },
  {
    slug: 'azithromycin',
    name: 'Azithromycin (Azithral)',
    lede: 'Azithromycin is a widely used antibiotic, popular because many infections need only a short 3–5 day course. It treats certain chest, throat, sinus and skin infections, and some sexually transmitted infections — but only bacterial ones.',
    uses: ['Chest, throat and sinus infections', 'Some skin and ear infections', 'Certain sexually transmitted infections', 'Sometimes used in typhoid'],
    sideEffects: ['Nausea, diarrhoea or tummy pain', 'Headache', 'Temporary changes in taste'],
    precautions: ['Tell your doctor about heart-rhythm problems', 'Mention liver disease and other medicines you take', 'Complete the prescribed course'],
    warnings: ['Palpitations, fainting or a very irregular heartbeat', 'Yellowing of the eyes (liver)', 'Severe allergic reaction or severe diarrhoea'],
    faqs: [
      { q: 'Why is azithromycin only a 3 or 5 day course?', a: 'It stays active in the body for several days after the last dose, so a short course keeps working — but take it exactly as prescribed and do not repeat it without advice.' },
      { q: 'Is azithromycin good for a cough or cold?', a: 'No — colds and most coughs are viral, and antibiotics do not help. It is only useful for confirmed or suspected bacterial infections.' },
      { q: 'Can I take azithromycin with other medicines?', a: 'Some combinations affect heart rhythm or interact, so always tell your doctor and pharmacist what else you take.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['medicines/augmentin', 'Augmentin'], ['diseases/pharyngitis-sore-throat', 'Sore throat'], ['diseases/pneumonia', 'Pneumonia']],
  },
  {
    slug: 'augmentin',
    name: 'Augmentin (Amoxicillin + Clavulanic Acid)',
    lede: 'Augmentin combines amoxicillin with clavulanic acid, which helps it work against bacteria that would resist amoxicillin alone. It is used for more stubborn or mixed bacterial infections.',
    uses: ['Chest, sinus and ear infections not cleared by simpler antibiotics', 'Dental and skin infections', 'Some urinary infections', 'Animal or human bite infections'],
    sideEffects: ['Diarrhoea (more common than with amoxicillin alone)', 'Nausea', 'Thrush'],
    precautions: ['Tell your doctor about penicillin allergy or liver problems', 'Take with the first bite of a meal to reduce tummy upset', 'Finish the full course'],
    warnings: ['Severe allergy (facial swelling, breathing difficulty)', 'Yellowing of the eyes (rare liver effect)', 'Severe or bloody diarrhoea'],
    faqs: [
      { q: 'What is the difference between Augmentin and amoxicillin?', a: 'Augmentin adds clavulanic acid, which blocks an enzyme some bacteria use to defeat amoxicillin — so it works against a wider range of infections.' },
      { q: 'Should Augmentin be taken with food?', a: 'Yes — taking it at the start of a meal reduces stomach upset and helps absorption.' },
      { q: 'Can I stop when I feel better?', a: 'No — complete the whole course to fully clear the infection and limit antibiotic resistance.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['medicines/azithromycin', 'Azithromycin'], ['diseases/sinusitis', 'Sinusitis'], ['diseases/pneumonia', 'Pneumonia']],
  },
  {
    slug: 'pantoprazole',
    name: 'Pantoprazole (Pan, Pantop)',
    lede: 'Pantoprazole is a proton-pump inhibitor (PPI) that strongly reduces stomach acid. It is used for acidity, reflux and ulcers, and is often given alongside painkillers to protect the stomach.',
    uses: ['Acid reflux and heartburn (GERD)', 'Stomach and duodenal ulcers', 'Protecting the stomach when taking long-term painkillers', 'Part of ulcer (H. pylori) treatment'],
    sideEffects: ['Headache', 'Diarrhoea or constipation', 'Nausea'],
    precautions: ['Best taken about 30–60 minutes before a meal', 'Long-term use should be reviewed (links to low B12, magnesium and bone thinning)', 'Do not ignore ongoing symptoms without a diagnosis'],
    warnings: ['Unintended weight loss, difficulty swallowing or black stools — see a doctor (alarm symptoms)', 'Severe or lasting diarrhoea', 'Muscle cramps or spasms (possible low magnesium)'],
    faqs: [
      { q: 'Should I take pantoprazole before or after food?', a: 'It works best taken on an empty stomach, usually 30–60 minutes before breakfast.' },
      { q: 'Is it safe to take pantoprazole long term?', a: 'Many people use it safely, but long-term use should be reviewed by a doctor because of links to nutrient deficiencies and other effects — use the lowest dose that controls symptoms.' },
      { q: 'Pantoprazole or omeprazole — what is the difference?', a: 'They belong to the same PPI family and work similarly. Differences are mainly in interactions and individual response; your doctor picks what suits you.' },
    ],
    related: [['medicines/omeprazole', 'Omeprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['diseases/gastritis', 'Gastritis'], ['diseases/peptic-ulcer', 'Peptic ulcer']],
  },
  {
    slug: 'omeprazole',
    name: 'Omeprazole',
    lede: 'Omeprazole is a proton-pump inhibitor (PPI) that lowers stomach acid to treat acidity, reflux and ulcers. It is one of the most commonly used stomach medicines worldwide.',
    uses: ['Acid reflux and heartburn (GERD)', 'Stomach and duodenal ulcers', 'Protecting the stomach with long-term painkillers', 'Part of H. pylori ulcer treatment'],
    sideEffects: ['Headache', 'Diarrhoea, constipation or wind', 'Nausea'],
    precautions: ['Take before food, usually before breakfast', 'Review long-term use with a doctor', 'Can interact with some medicines (e.g. clopidogrel)'],
    warnings: ['Alarm symptoms — weight loss, trouble swallowing, black stools — need review', 'Severe diarrhoea', 'Muscle cramps (possible low magnesium)'],
    faqs: [
      { q: 'How long does omeprazole take to work?', a: 'It may ease symptoms within a day or two, but full benefit can take a few days as acid levels settle.' },
      { q: 'Can I take omeprazole every day?', a: 'Short courses are common; longer daily use should be guided by a doctor, using the lowest effective dose.' },
      { q: 'Can I take antacids with omeprazole?', a: 'Usually yes, for quick relief, but space them apart. Ask a pharmacist if unsure.' },
    ],
    related: [['medicines/pantoprazole', 'Pantoprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['diseases/gastritis', 'Gastritis'], ['diseases/peptic-ulcer', 'Peptic ulcer']],
  },
  {
    slug: 'cetirizine',
    name: 'Cetirizine (Cetzine, Alerid)',
    lede: 'Cetirizine is a common antihistamine for allergies. It relieves sneezing, runny nose, itching and hives, and causes less drowsiness than older antihistamines — though some people still feel sleepy.',
    uses: ['Allergic rhinitis (sneezing, runny/itchy nose)', 'Itchy, watery eyes', 'Hives and skin itching', 'Allergy symptoms from dust, pollen or pets'],
    sideEffects: ['Drowsiness in some people', 'Dry mouth', 'Headache or tiredness'],
    precautions: ['Be careful driving if it makes you sleepy', 'Alcohol can increase drowsiness', 'Lower doses may be needed in kidney problems'],
    warnings: ['Severe allergic reaction (rare)', 'Marked drowsiness affecting daily safety'],
    faqs: [
      { q: 'Cetirizine or levocetirizine — which is better?', a: 'Levocetirizine is a refined form of cetirizine and may cause slightly less drowsiness for some people. Both work well for allergies; individual response varies.' },
      { q: 'Can I take cetirizine every day?', a: 'Many people take it daily during allergy seasons, and it is generally safe, but long-term daily use is best discussed with a doctor.' },
      { q: 'Does cetirizine make you sleepy?', a: 'It is less sedating than older antihistamines, but a minority of people do feel drowsy — take it at night if so.' },
    ],
    related: [['medicines/montelukast', 'Montelukast'], ['diseases/allergic-rhinitis', 'Allergic rhinitis'], ['diseases/hives-urticaria', 'Hives (urticaria)'], ['diseases/drug-allergy', 'Drug allergy']],
  },
  {
    slug: 'montelukast',
    name: 'Montelukast (Montair)',
    lede: 'Montelukast is a daily preventer used for asthma and allergic rhinitis. It reduces airway inflammation but is not a reliever inhaler — it does not treat a sudden asthma attack.',
    uses: ['Preventing asthma symptoms (as a controller)', 'Allergic rhinitis (hay fever)', 'Exercise-induced breathing symptoms'],
    sideEffects: ['Headache', 'Tummy upset', 'Vivid dreams or sleep changes'],
    precautions: ['Not for treating a sudden asthma attack — keep your reliever inhaler', 'Often taken in the evening', 'Watch for mood or behaviour changes'],
    warnings: ['Mental-health changes — agitation, low mood, unusual thoughts or behaviour — tell your doctor promptly', 'A severe asthma attack needs your reliever and urgent care, not montelukast'],
    faqs: [
      { q: 'Is montelukast a steroid?', a: 'No. It is a leukotriene receptor antagonist, a different type of anti-inflammatory that is taken as a tablet, not a steroid.' },
      { q: 'Why is montelukast taken at night?', a: 'Evening dosing suits how asthma symptoms often worsen overnight, and it is the timing used in many studies.' },
      { q: 'Does montelukast affect mood?', a: 'Some people notice sleep, mood or behaviour changes. These are recognised, so report anything unusual to your doctor.' },
    ],
    related: [['medicines/cetirizine', 'Cetirizine'], ['diseases/asthma', 'Asthma'], ['diseases/allergic-rhinitis', 'Allergic rhinitis'], ['diseases/childhood-asthma', 'Childhood asthma']],
  },
  {
    slug: 'amlodipine',
    name: 'Amlodipine (Amlong)',
    lede: 'Amlodipine is a common blood-pressure medicine (a calcium-channel blocker). It relaxes and widens blood vessels, lowering blood pressure and easing chest pain (angina). It is usually taken once a day, long term.',
    uses: ['High blood pressure (hypertension)', 'Angina (chest pain from the heart)'],
    sideEffects: ['Ankle or leg swelling', 'Flushing and headache', 'Tiredness or dizziness'],
    precautions: ['Do not stop suddenly without advice', 'Grapefruit can raise its levels', 'Rise slowly from sitting to avoid dizziness'],
    warnings: ['Marked ankle swelling or sudden weight gain', 'Fainting or very low blood pressure', 'Worsening chest pain'],
    faqs: [
      { q: 'What is the best time to take amlodipine?', a: 'It can be taken at any consistent time of day, with or without food. Pick a time you will remember and stick to it.' },
      { q: 'Why does amlodipine cause ankle swelling?', a: 'It widens small blood vessels, which can let fluid pool in the ankles. Tell your doctor if it is troublesome — the dose or medicine may be adjusted.' },
      { q: 'Can I stop amlodipine once my BP is normal?', a: 'Usually not — normal readings often mean it is working. Stopping can let blood pressure rise again. Any change should be made with your doctor.' },
    ],
    related: [['medicines/telmisartan', 'Telmisartan'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['diseases/hypertension', 'Hypertension'], ['diseases/angina', 'Angina']],
  },
  {
    slug: 'telmisartan',
    name: 'Telmisartan',
    lede: 'Telmisartan is a widely used blood-pressure medicine (an ARB). It relaxes blood vessels and protects the heart and kidneys, and is often chosen for people with diabetes or kidney concerns. It is usually taken once daily.',
    uses: ['High blood pressure (hypertension)', 'Protecting the kidneys in diabetes', 'Reducing cardiovascular risk in some people'],
    sideEffects: ['Dizziness, especially at first', 'Tiredness', 'Rarely, a rise in blood potassium'],
    precautions: ['Not to be used in pregnancy', 'Kidney function and potassium may be monitored', 'Rise slowly to avoid dizziness'],
    warnings: ['Fainting or very low blood pressure', 'Swelling of the face, lips or throat (rare, seek urgent care)', 'Muscle weakness or palpitations (possible high potassium)'],
    faqs: [
      { q: 'Is telmisartan better than amlodipine?', a: 'They work differently and are both effective; sometimes they are combined. The best choice depends on your health — for example telmisartan is often preferred with diabetes or kidney disease.' },
      { q: 'When should I take telmisartan?', a: 'Usually once a day at the same time, with or without food. Consistency matters more than the exact hour.' },
      { q: 'Is telmisartan safe in pregnancy?', a: 'No — ARBs like telmisartan should be avoided in pregnancy. Tell your doctor if you are pregnant or planning to be.' },
    ],
    related: [['medicines/amlodipine', 'Amlodipine'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['diseases/hypertension', 'Hypertension'], ['diseases/chronic-kidney-disease', 'Chronic kidney disease']],
  },
  {
    slug: 'atorvastatin',
    name: 'Atorvastatin (Atorva, Lipitor)',
    lede: 'Atorvastatin is a statin that lowers cholesterol, especially LDL (“bad”) cholesterol, to reduce the risk of heart attack and stroke. It is usually taken once a day, long term, alongside a healthy lifestyle.',
    uses: ['Lowering high cholesterol', 'Preventing heart attack and stroke in at-risk people', 'After a heart attack or stroke'],
    sideEffects: ['Muscle aches', 'Digestive upset', 'Rarely, raised liver enzymes'],
    precautions: ['Avoid in pregnancy', 'Limit alcohol; grapefruit can raise its levels', 'Occasional blood tests check the liver'],
    warnings: ['Unexplained muscle pain, tenderness or weakness, especially with dark urine — seek medical advice (rare muscle problem)', 'Yellowing of the eyes or severe tummy pain'],
    faqs: [
      { q: 'Should atorvastatin be taken at night?', a: 'Atorvastatin works well taken at any time of day, though some statins are best at night. Take it consistently as advised.' },
      { q: 'Do I need to take a statin for life?', a: 'Often yes, because cholesterol tends to rise again if the medicine stops. Lifestyle helps, but do not stop without discussing it with your doctor.' },
      { q: 'Are muscle aches from statins dangerous?', a: 'Mild aches are common and usually harmless, but severe or persistent muscle pain with weakness or dark urine is rare and needs prompt medical review.' },
    ],
    related: [['how-to-lower-cholesterol', 'How to lower cholesterol'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], ['diseases/high-cholesterol', 'High cholesterol'], ['diseases/coronary-artery-disease', 'Coronary artery disease']],
  },
  {
    slug: 'levothyroxine',
    name: 'Levothyroxine (Thyronorm, Eltroxin)',
    lede: 'Levothyroxine replaces the thyroid hormone your body is missing in an underactive thyroid (hypothyroidism). Taken correctly it restores normal energy and metabolism, and is usually needed long term.',
    uses: ['Underactive thyroid (hypothyroidism)', 'After thyroid surgery or radioactive iodine', 'Certain thyroid conditions in pregnancy'],
    sideEffects: ['Few if the dose is right', 'Too much: palpitations, weight loss, shakiness, feeling hot', 'Too little: tiredness, weight gain, feeling cold'],
    precautions: ['Take on an empty stomach, usually 30–60 minutes before breakfast', 'Separate it from calcium, iron and antacids by a few hours', 'Try to stay on the same brand for consistent levels'],
    warnings: ['Chest pain, a racing or irregular heartbeat (possible over-replacement)', 'Symptoms returning strongly (possible under-treatment)'],
    faqs: [
      { q: 'Why take levothyroxine on an empty stomach?', a: 'Food, coffee and some minerals reduce how much is absorbed. Taking it 30–60 minutes before breakfast keeps levels steady.' },
      { q: 'Do I need levothyroxine for life?', a: 'Usually yes, because the thyroid cannot make enough hormone on its own. The dose is adjusted using blood tests over time.' },
      { q: 'What if I miss a dose?', a: 'Take it when you remember on the same day, or skip it if it is nearly time for the next — do not double up. Ask your doctor if unsure.' },
    ],
    related: [['diseases/hypothyroidism', 'Hypothyroidism'], ['blood-tests/thyroid-function-test-tft', 'Thyroid function test'], ['blood-tests/tsh', 'TSH test'], ['diseases/thyroid-disorders', 'Thyroid disorders']],
  },
  {
    slug: 'metronidazole',
    name: 'Metronidazole (Flagyl)',
    lede: 'Metronidazole is an antibiotic that also works against certain parasites. It treats specific gut, dental, gynaecological and skin infections. A key rule: do not drink alcohol during the course or shortly after.',
    uses: ['Certain gut infections (amoebiasis, giardia)', 'Dental and gum infections', 'Bacterial vaginosis and some pelvic infections', 'Some skin and wound infections'],
    sideEffects: ['Metallic taste', 'Nausea or loss of appetite', 'Dark-coloured urine (harmless)'],
    precautions: ['Avoid all alcohol during and for a couple of days after the course', 'Complete the full course', 'Tell your doctor about liver disease'],
    warnings: ['A strong reaction with alcohol (flushing, vomiting, fast heartbeat)', 'Numbness or tingling in hands/feet on long courses', 'Severe allergic reaction'],
    faqs: [
      { q: 'Why can’t I drink alcohol with metronidazole?', a: 'The combination can cause an unpleasant reaction — flushing, nausea, vomiting and a rapid heartbeat. Avoid alcohol during the course and for 48 hours after.' },
      { q: 'Why is my urine darker on metronidazole?', a: 'It can harmlessly darken the urine. This is a known, temporary effect and not a cause for concern on its own.' },
      { q: 'How long is a course of metronidazole?', a: 'It varies with the infection, from a single dose to a week or more. Take exactly what your doctor prescribes and finish it.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['diseases/bacterial-vaginosis', 'Bacterial vaginosis'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['diseases/pid', 'Pelvic inflammatory disease']],
  },
  {
    slug: 'ors',
    name: 'ORS (Oral Rehydration Salts)',
    lede: 'ORS is a simple, life-saving mix of salts and glucose dissolved in clean water. It replaces the water and salts lost in diarrhoea, vomiting or heat, and is the first-line treatment for dehydration — especially in children.',
    uses: ['Preventing and treating dehydration from diarrhoea or vomiting', 'Fluid loss from heat or heavy sweating', 'Recovery of fluids and salts in gastroenteritis'],
    sideEffects: ['Very few when prepared correctly', 'Mild nausea if drunk too fast'],
    precautions: ['Mix one sachet with the exact amount of clean water stated on the pack', 'Do not add extra sugar or salt', 'Sip slowly and often, especially for children'],
    warnings: ['Signs of severe dehydration — sunken eyes, very little urine, drowsiness, fast breathing — need medical care', 'Unable to keep any fluids down', 'Blood in stools or a high fever'],
    faqs: [
      { q: 'How do I prepare ORS correctly?', a: 'Dissolve one full sachet in the exact volume of clean (boiled and cooled, if needed) water shown on the pack. Using too little water makes it too concentrated and unsafe.' },
      { q: 'Can adults use ORS too?', a: 'Yes. ORS helps anyone losing fluids from diarrhoea, vomiting or heat, not just children.' },
      { q: 'Is homemade sugar-salt solution as good as ORS?', a: 'A proper ORS sachet has the right balance and is safer. A careful homemade sugar-salt solution can help in an emergency, but get real ORS as soon as possible.' },
    ],
    related: [['how-to-stop-diarrhea', 'How to stop diarrhoea'], ['diseases/dehydration', 'Dehydration'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['diseases/food-poisoning', 'Food poisoning']],
  },
];
