// Patient-facing medicine/drug pages for MedDroid. Educational only.
// IMPORTANT: doses below are TYPICAL ADULT/PAEDIATRIC REFERENCE ranges (like a
// formulary), NOT prescriptions. Real doses vary with age, weight, kidney/liver
// function and the exact product; paediatric doses are usually weight-based and
// must be set by a doctor. Brand lists are common examples, not exhaustive —
// brand names differ by country. rx:true = prescription; rx:false = OTC (varies
// by country). Every page defers the exact dose to a doctor/pharmacist + leaflet.

export const DRUGS = [
  // ============================ Painkillers & fever ============================
  {
    slug: 'paracetamol', name: 'Paracetamol (Acetaminophen)', rx: false,
    brandsIndia: ['Dolo', 'Crocin', 'Calpol', 'Pacimol', 'Paracip'],
    brandsWorld: ['Tylenol', 'Panadol', 'Mapap', 'Perfalgan'],
    adultDose: '500–1000 mg every 4–6 hours; do not exceed 4 g (4000 mg) in 24 hours',
    pedsDose: '10–15 mg/kg per dose every 4–6 h (max 60 mg/kg/day); use syrup and dose by weight',
    lede: 'Paracetamol is one of the most widely used medicines for fever and mild-to-moderate pain. It is very safe at the right dose, but an overdose can seriously harm the liver — so the daily limit matters.',
    uses: ['Bringing down fever', 'Headache and body aches', 'Toothache and period pain', 'Cold and flu aches', 'A first-choice painkiller in pregnancy (confirm with your doctor)'],
    sideEffects: ['Very well tolerated at the correct dose', 'Rare skin rash or allergy', 'Liver damage only with overdose or in liver disease'],
    precautions: ['Do not exceed the daily limit', 'Many cold/flu products already contain paracetamol — do not double up', 'Caution in liver disease and with regular alcohol'],
    warnings: ['An overdose is dangerous even before you feel unwell — get medical help immediately', 'Facial swelling or breathing difficulty (allergy)', 'Yellow eyes, dark urine or severe tummy pain (liver)'],
    faqs: [
      { q: 'How much paracetamol is safe in a day?', a: 'For most adults the limit is 4 g (4000 mg) in 24 hours — for example up to 8 tablets of 500 mg. Never exceed it, and remember combination cold products may also contain paracetamol.' },
      { q: 'Is paracetamol safe in pregnancy?', a: 'It is generally the preferred painkiller in pregnancy at the lowest effective dose for the shortest time — but confirm with your doctor.' },
      { q: 'Paracetamol or ibuprofen?', a: 'Paracetamol is gentler on the stomach and good for fever and pain; ibuprofen also reduces inflammation. Ask a pharmacist which suits you.' },
    ],
    related: [['medicines/dolo-650', 'Dolo 650'], ['medicines/ibuprofen', 'Ibuprofen'], ['medicines/combiflam', 'Combiflam'], ['how-to-reduce-fever-at-home', 'How to reduce fever']],
  },
  {
    slug: 'dolo-650', name: 'Dolo 650 (Paracetamol 650 mg)', rx: false,
    brandsIndia: ['Dolo 650', 'Calpol 650', 'Crocin 650', 'Pacimol 650'],
    brandsWorld: ['(650 mg paracetamol; sold generically abroad)'],
    adultDose: '1 tablet (650 mg) every 6–8 hours; keep total paracetamol under 4 g/day',
    pedsDose: 'Not given as a fixed 650 mg tablet — use weight-based paracetamol syrup (10–15 mg/kg)',
    lede: 'Dolo 650 is India’s most prescribed paracetamol brand. Each tablet has 650 mg of paracetamol and is used for fever and pain — it works exactly like any other paracetamol of the same strength.',
    uses: ['Fever, including viral and post-vaccination fever', 'Headache and body aches', 'Mild-to-moderate pain', 'Cold and flu symptoms'],
    sideEffects: ['Very well tolerated', 'Rare rash or allergy', 'Liver harm only with overdose or liver disease'],
    precautions: ['Do not combine with other paracetamol products', 'Stay within the daily limit', 'Caution with liver disease and alcohol'],
    warnings: ['Overdose is dangerous even before symptoms — seek help at once', 'Yellow eyes, dark urine or severe tummy pain', 'Facial swelling or breathing difficulty'],
    faqs: [
      { q: 'Is Dolo 650 safe to take daily?', a: 'Short courses at the correct dose are generally safe, but daily use over long periods should be guided by a doctor, as excess paracetamol harms the liver.' },
      { q: 'Dolo 650 vs Dolo 500 — what is the difference?', a: 'Only the strength: 650 mg vs 500 mg of paracetamol per tablet. The medicine is the same.' },
      { q: 'Can I take Dolo 650 on an empty stomach?', a: 'Yes, paracetamol can be taken with or without food.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/ibuprofen', 'Ibuprofen'], ['diseases/viral-fever', 'Viral fever'], ['how-to-reduce-fever-at-home', 'How to reduce fever']],
  },
  {
    slug: 'ibuprofen', name: 'Ibuprofen (Brufen)', rx: false,
    brandsIndia: ['Brufen', 'Ibugesic', 'Combiflam (with paracetamol)'],
    brandsWorld: ['Advil', 'Motrin', 'Nurofen'],
    adultDose: '200–400 mg every 4–6 hours with food; OTC max 1200 mg/day (up to 2400 mg/day under a doctor)',
    pedsDose: '5–10 mg/kg per dose every 6–8 h (max 40 mg/kg/day); avoid under 3 months',
    lede: 'Ibuprofen is an anti-inflammatory painkiller (NSAID) for pain, swelling and fever. It works well but is harder on the stomach and kidneys than paracetamol, so it is used more carefully.',
    uses: ['Pain with inflammation (sprains, back pain, arthritis)', 'Period pain', 'Headache and dental pain', 'Fever'],
    sideEffects: ['Stomach upset, heartburn or indigestion', 'Nausea', 'Raised blood pressure with long-term use'],
    precautions: ['Take with or after food', 'Avoid with ulcers, kidney disease or certain heart conditions', 'Caution in asthma, late pregnancy and the elderly'],
    warnings: ['Black/tarry stools or vomiting blood (stomach bleeding)', 'Severe stomach pain', 'Swelling, wheezing or rash (allergy)'],
    faqs: [
      { q: 'Can I take ibuprofen and paracetamol together?', a: 'Yes, they can often be combined or alternated for stronger relief as they work differently. Check with a pharmacist if you have other conditions.' },
      { q: 'Should ibuprofen be taken with food?', a: 'Yes — with or after food to reduce stomach irritation.' },
      { q: 'Who should avoid ibuprofen?', a: 'People with ulcers, kidney disease, some heart problems, or in late pregnancy should avoid it or use it only on medical advice.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/diclofenac', 'Diclofenac'], ['medicines/aspirin', 'Aspirin'], ['diseases/gastritis', 'Gastritis']],
  },
  {
    slug: 'aspirin', name: 'Aspirin', rx: false,
    brandsIndia: ['Ecosprin', 'Disprin', 'Aspicot'],
    brandsWorld: ['Bayer Aspirin', 'Ecotrin', 'Disprin'],
    adultDose: 'Pain/fever: 300–600 mg every 4–6 h. Antiplatelet (heart/stroke): 75–150 mg once daily',
    pedsDose: 'Avoid in children/teens (risk of Reye’s syndrome), except specialist use (e.g. Kawasaki disease)',
    lede: 'Aspirin has two roles: at higher doses it relieves pain and fever, and at low doses it thins the blood to help prevent heart attacks and strokes. It is not for children.',
    uses: ['Low-dose: preventing clots in heart disease and after stroke (on advice)', 'Higher-dose: pain and fever (less common now)', 'Given early in a suspected heart attack in adults'],
    sideEffects: ['Stomach irritation and heartburn', 'Easier bruising or bleeding', 'Ringing in the ears at high doses'],
    precautions: ['Never give to children/teenagers', 'Avoid with bleeding disorders or active ulcers', 'Tell your dentist/surgeon before procedures'],
    warnings: ['Black stools, vomiting blood or unusual bleeding', 'Severe allergy or wheezing', 'Sudden severe stomach pain'],
    faqs: [
      { q: 'Should I take low-dose aspirin daily?', a: 'Only if your doctor advises it — usually for people with heart disease or high risk. Without need it can cause bleeding, so it is not for everyone.' },
      { q: 'Do I stop aspirin before surgery?', a: 'Sometimes, because it thins the blood — but follow your doctor’s specific instructions; do not stop a heart medicine on your own.' },
    ],
    related: [['medicines/clopidogrel', 'Clopidogrel'], ['diseases/heart-attack', 'Heart attack'], ['diseases/stroke', 'Stroke'], ['medicines/ibuprofen', 'Ibuprofen']],
  },
  {
    slug: 'diclofenac', name: 'Diclofenac (Voveran)', rx: true,
    brandsIndia: ['Voveran', 'Diclonac', 'Dynapar', 'Volini (gel)'],
    brandsWorld: ['Voltaren', 'Cataflam', 'Cambia'],
    adultDose: '50 mg 2–3 times daily with food (max ~150 mg/day); topical gel applied 3–4×/day',
    pedsDose: 'Generally avoided in children — specialist use only',
    lede: 'Diclofenac is a strong anti-inflammatory painkiller (NSAID) used for joint, muscle and period pain. It is effective but carries the usual NSAID risks to the stomach, kidneys and heart.',
    uses: ['Arthritis and joint pain', 'Back, muscle and sprain pain', 'Period pain', 'Post-injury or post-surgery pain', 'Topical gel for localised pain'],
    sideEffects: ['Stomach upset and heartburn', 'Nausea', 'Headache or dizziness'],
    precautions: ['Take with food; use the lowest dose for the shortest time', 'Avoid with ulcers, kidney or significant heart disease', 'Topical gel is gentler on the stomach'],
    warnings: ['Black stools or vomiting blood (GI bleeding)', 'Chest pain or breathlessness', 'Swelling, rash or wheezing (allergy)'],
    faqs: [
      { q: 'Is diclofenac stronger than ibuprofen?', a: 'It is a potent NSAID often used for more severe inflammatory pain, but stronger effect can mean higher risk. Your doctor weighs benefit against your heart and stomach risk.' },
      { q: 'Can I use diclofenac gel instead of tablets?', a: 'For localised joint or muscle pain, the gel gives relief with far less effect on the stomach and is often preferred.' },
    ],
    related: [['medicines/ibuprofen', 'Ibuprofen'], ['medicines/aceclofenac', 'Aceclofenac'], ['diseases/osteoarthritis', 'Osteoarthritis'], ['diseases/gastritis', 'Gastritis']],
  },
  {
    slug: 'combiflam', name: 'Combiflam (Ibuprofen + Paracetamol)', rx: false,
    brandsIndia: ['Combiflam', 'Flexon', 'Ibugesic Plus', 'Brufen Plus'],
    brandsWorld: ['(ibuprofen+paracetamol combos, e.g. Nuromol, Maxigesic)'],
    adultDose: '1 tablet (ibuprofen 400 mg + paracetamol 325 mg) every 8 hours with food; max 3 tablets/day',
    pedsDose: 'Do not use the adult tablet; use weight-based paracetamol/ibuprofen syrups instead',
    lede: 'Combiflam pairs ibuprofen with paracetamol in one tablet for stronger relief of pain and fever than either alone. Because it contains an NSAID, the usual stomach and kidney cautions apply.',
    uses: ['Moderate pain (dental, headache, body ache)', 'Fever not settling with paracetamol alone', 'Period and muscle pain'],
    sideEffects: ['Stomach upset or heartburn', 'Nausea', 'Dizziness'],
    precautions: ['Take with food, short-term only', 'Do not add extra paracetamol or ibuprofen products', 'Avoid with ulcers, kidney or heart disease'],
    warnings: ['Black stools or vomiting blood', 'Severe stomach pain', 'Rash, swelling or wheezing (allergy)'],
    faqs: [
      { q: 'Is Combiflam safe for daily use?', a: 'It is meant for short-term relief. Regular daily use raises the risk of stomach, kidney and liver problems, so use it only as needed and check with a doctor for ongoing pain.' },
      { q: 'Can children take Combiflam?', a: 'Not the adult tablet. Children need weight-based paracetamol or ibuprofen syrups — ask a doctor.' },
    ],
    related: [['medicines/ibuprofen', 'Ibuprofen'], ['medicines/paracetamol', 'Paracetamol'], ['medicines/dolo-650', 'Dolo 650'], ['diseases/gastritis', 'Gastritis']],
  },
  {
    slug: 'aceclofenac', name: 'Aceclofenac', rx: true,
    brandsIndia: ['Zerodol', 'Hifenac', 'Aceclo', 'Dolokind'],
    brandsWorld: ['Airtal', 'Preservex'],
    adultDose: '100 mg twice daily with food (often combined with paracetamol)',
    pedsDose: 'Not recommended in children',
    lede: 'Aceclofenac is an anti-inflammatory painkiller (NSAID) popular in India for arthritis and musculoskeletal pain, often sold combined with paracetamol. Standard NSAID precautions apply.',
    uses: ['Osteoarthritis and rheumatoid arthritis pain', 'Back and joint pain', 'Dental and post-injury pain'],
    sideEffects: ['Stomach upset, heartburn', 'Nausea', 'Dizziness'],
    precautions: ['Take with food, lowest effective dose', 'Avoid with ulcers, kidney or heart disease', 'Caution in the elderly'],
    warnings: ['GI bleeding (black stools, vomiting blood)', 'Chest pain or breathlessness', 'Allergic swelling or rash'],
    faqs: [
      { q: 'Is aceclofenac better than diclofenac?', a: 'They are similar NSAIDs; aceclofenac may be slightly easier on the stomach for some people, but both share NSAID risks. Your doctor chooses based on your health.' },
      { q: 'How long can I take aceclofenac?', a: 'Use it for the shortest time needed. Long-term use for chronic conditions should be monitored by a doctor.' },
    ],
    related: [['medicines/diclofenac', 'Diclofenac'], ['medicines/ibuprofen', 'Ibuprofen'], ['diseases/osteoarthritis', 'Osteoarthritis'], ['diseases/rheumatoid-arthritis', 'Rheumatoid arthritis']],
  },
  // ============================ Diabetes ============================
  {
    slug: 'metformin', name: 'Metformin', rx: true,
    brandsIndia: ['Glycomet', 'Gluconorm', 'Glucophage', 'Obimet'],
    brandsWorld: ['Glucophage', 'Fortamet', 'Glumetza'],
    adultDose: 'Start 500 mg once–twice daily with meals; usual range 1000–2000 mg/day (max ~2550 mg)',
    pedsDose: 'Age ≥10 years: 500 mg once–twice daily, up to 2000 mg/day',
    lede: 'Metformin is the first-choice medicine for type 2 diabetes. It lowers blood sugar mainly by reducing sugar released by the liver and does not usually cause low sugar on its own.',
    uses: ['Type 2 diabetes (first-line)', 'Prediabetes in some cases', 'Polycystic ovary syndrome (PCOS)'],
    sideEffects: ['Nausea, diarrhoea or metallic taste (often settle)', 'Reduced appetite', 'Low vitamin B12 with long-term use'],
    precautions: ['Take with food', 'Needs kidney function checks', 'Often paused before contrast scans and around surgery'],
    warnings: ['Lactic acidosis (rare): muscle pain, fast/deep breathing, unusual tiredness, cold feeling — urgent', 'Persistent vomiting or dehydration'],
    faqs: [
      { q: 'Does metformin cause weight loss?', a: 'It is weight-neutral or causes modest weight loss for some, unlike some diabetes drugs that add weight.' },
      { q: 'Can I stop metformin when my sugar is normal?', a: 'Not on your own — normal sugar often means it is working. Change only with your doctor.' },
    ],
    related: [['diseases/type-2-diabetes', 'Type 2 diabetes'], ['medicines/glimepiride', 'Glimepiride'], ['how-to-lower-blood-sugar', 'How to lower blood sugar'], ['blood-tests/hba1c', 'HbA1c test']],
  },
  {
    slug: 'glimepiride', name: 'Glimepiride', rx: true,
    brandsIndia: ['Amaryl', 'Glimestar', 'Zoryl', 'Glimy'],
    brandsWorld: ['Amaryl'],
    adultDose: '1–2 mg once daily with breakfast; usual up to 4 mg (max 8 mg/day)',
    pedsDose: 'Not recommended in children',
    lede: 'Glimepiride is a sulfonylurea for type 2 diabetes. It helps the pancreas release more insulin, which lowers blood sugar — but this means it can cause low sugar (hypoglycaemia).',
    uses: ['Type 2 diabetes, often with metformin', 'When metformin alone is not enough'],
    sideEffects: ['Low blood sugar (hypoglycaemia)', 'Weight gain', 'Nausea'],
    precautions: ['Take with breakfast; do not skip meals', 'Carry a fast sugar source', 'Caution in the elderly and kidney disease'],
    warnings: ['Hypoglycaemia: shakiness, sweating, confusion — take sugar and seek help if severe', 'Signs of allergy or jaundice'],
    faqs: [
      { q: 'Why does glimepiride cause low sugar but metformin usually does not?', a: 'Glimepiride pushes the pancreas to release insulin regardless of your sugar level, so missing a meal can drop it too low. Metformin works differently and rarely does this alone.' },
      { q: 'When should I take glimepiride?', a: 'Usually just before or with breakfast, so its effect matches your first meal.' },
    ],
    related: [['medicines/metformin', 'Metformin'], ['diseases/type-2-diabetes', 'Type 2 diabetes'], ['how-to-lower-blood-sugar', 'How to lower blood sugar'], ['blood-tests/fasting-blood-sugar', 'Fasting blood sugar']],
  },
  {
    slug: 'insulin', name: 'Insulin', rx: true,
    brandsIndia: ['Huminsulin', 'Actrapid', 'Lantus', 'Mixtard', 'Novomix'],
    brandsWorld: ['Lantus', 'Humalog', 'NovoRapid', 'Levemir', 'Tresiba'],
    adultDose: 'Highly individualised units, adjusted to blood sugar; given by injection (never a fixed dose)',
    pedsDose: 'Weight-based units, set and adjusted by a paediatric diabetes team',
    lede: 'Insulin is the hormone that lowers blood sugar. It is essential in type 1 diabetes and used in type 2 when other medicines are not enough. Doses are individual and adjusted over time — never fixed.',
    uses: ['Type 1 diabetes (always needed)', 'Type 2 diabetes when tablets are not enough', 'Diabetes in pregnancy', 'Very high sugar or hospital care'],
    sideEffects: ['Low blood sugar (hypoglycaemia)', 'Weight gain', 'Skin changes at injection sites'],
    precautions: ['Rotate injection sites', 'Store as directed (often refrigerated)', 'Match dose to food and activity; never skip meals after a dose'],
    warnings: ['Severe hypoglycaemia: confusion, fainting or fits — emergency (needs fast sugar/glucagon)', 'Very high sugar with vomiting or drowsiness'],
    faqs: [
      { q: 'Does insulin have a standard dose?', a: 'No — it is always personalised in units and adjusted to your blood-sugar readings, meals and activity by your diabetes team.' },
      { q: 'Does starting insulin mean my diabetes is worse?', a: 'Not necessarily. Insulin is a normal, effective step when the body needs more help — it is a tool, not a failure.' },
    ],
    related: [['medicines/metformin', 'Metformin'], ['diseases/type-1-diabetes', 'Type 1 diabetes'], ['diseases/type-2-diabetes', 'Type 2 diabetes'], ['how-to-lower-blood-sugar', 'How to lower blood sugar']],
  },
  // ============================ Antibiotics ============================
  {
    slug: 'amoxicillin', name: 'Amoxicillin', rx: true,
    brandsIndia: ['Mox', 'Novamox', 'Amoxil'],
    brandsWorld: ['Amoxil', 'Moxatag'],
    adultDose: '250–500 mg every 8 hours, or 500–875 mg every 12 hours',
    pedsDose: '20–40 mg/kg/day divided every 8–12 h (up to 80–90 mg/kg/day for some infections)',
    lede: 'Amoxicillin is a common penicillin-type antibiotic for many bacterial infections. It does not work against viruses (colds, most sore throats), and the full course should always be completed.',
    uses: ['Chest and ear infections', 'Dental and throat infections', 'Some urinary and skin infections', 'Part of stomach-ulcer (H. pylori) treatment'],
    sideEffects: ['Diarrhoea, nausea', 'Skin rash', 'Thrush'],
    precautions: ['Tell your doctor about penicillin allergy', 'Complete the full course', 'Antibiotics do not help viral infections'],
    warnings: ['Severe allergy: face/throat swelling, breathing difficulty (emergency)', 'Severe or bloody diarrhoea', 'Widespread rash'],
    faqs: [
      { q: 'How quickly does amoxicillin work?', a: 'Many feel better in 2–3 days, but finish the whole course to fully clear the infection and limit resistance.' },
      { q: 'Can I drink alcohol with amoxicillin?', a: 'A small amount is not usually dangerous, but it can worsen side effects and slow recovery.' },
    ],
    related: [['medicines/augmentin', 'Augmentin'], ['medicines/azithromycin', 'Azithromycin'], ['medicines/cefixime', 'Cefixime'], ['diseases/strep-throat', 'Strep throat']],
  },
  {
    slug: 'azithromycin', name: 'Azithromycin (Azithral)', rx: true,
    brandsIndia: ['Azithral', 'Azee', 'Zithrox', 'Aziwok'],
    brandsWorld: ['Zithromax', 'Z-Pak', 'Azasite'],
    adultDose: '500 mg once daily for 3 days, or 500 mg on day 1 then 250 mg on days 2–5',
    pedsDose: '10 mg/kg once daily for 3 days (or 10 mg/kg day 1 then 5 mg/kg days 2–5)',
    lede: 'Azithromycin is a widely used antibiotic, popular because many infections need only a short 3–5 day course. It treats certain bacterial chest, throat, sinus and skin infections — not viral ones.',
    uses: ['Chest, throat and sinus infections', 'Some skin and ear infections', 'Certain sexually transmitted infections', 'Sometimes used in typhoid'],
    sideEffects: ['Nausea, diarrhoea or tummy pain', 'Headache', 'Temporary taste changes'],
    precautions: ['Tell your doctor about heart-rhythm problems', 'Mention liver disease and other medicines', 'Complete the course'],
    warnings: ['Palpitations, fainting or irregular heartbeat', 'Yellow eyes (liver)', 'Severe allergy or diarrhoea'],
    faqs: [
      { q: 'Why is azithromycin only a 3 or 5 day course?', a: 'It stays active in the body for days after the last dose, so a short course keeps working. Take it exactly as prescribed.' },
      { q: 'Is azithromycin good for a cough or cold?', a: 'No — those are usually viral, and antibiotics do not help. It is only for bacterial infections.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['medicines/augmentin', 'Augmentin'], ['medicines/doxycycline', 'Doxycycline'], ['diseases/pneumonia', 'Pneumonia']],
  },
  {
    slug: 'augmentin', name: 'Augmentin (Amoxicillin + Clavulanic Acid)', rx: true,
    brandsIndia: ['Augmentin', 'Clavam', 'Moxikind-CV', 'Advent'],
    brandsWorld: ['Augmentin', 'Clavulin'],
    adultDose: '500/125 mg every 8 hours, or 875/125 mg every 12 hours',
    pedsDose: '20–45 mg/kg/day (amoxicillin part) divided every 8–12 h, by weight',
    lede: 'Augmentin combines amoxicillin with clavulanic acid, which helps it beat bacteria that resist amoxicillin alone. It is used for more stubborn or mixed bacterial infections.',
    uses: ['Infections not cleared by simpler antibiotics', 'Sinus, chest and ear infections', 'Dental, skin and some urinary infections', 'Bite-wound infections'],
    sideEffects: ['Diarrhoea (more than amoxicillin alone)', 'Nausea', 'Thrush'],
    precautions: ['Tell your doctor about penicillin allergy or liver problems', 'Take with the first bite of a meal', 'Finish the full course'],
    warnings: ['Severe allergy (swelling, breathing difficulty)', 'Yellow eyes (rare liver effect)', 'Severe or bloody diarrhoea'],
    faqs: [
      { q: 'How is Augmentin different from amoxicillin?', a: 'It adds clavulanic acid, which blocks an enzyme some bacteria use to defeat amoxicillin — widening its range.' },
      { q: 'Should Augmentin be taken with food?', a: 'Yes — with the start of a meal, to reduce stomach upset and help absorption.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['medicines/azithromycin', 'Azithromycin'], ['medicines/cefixime', 'Cefixime'], ['diseases/sinusitis', 'Sinusitis']],
  },
  {
    slug: 'cefixime', name: 'Cefixime', rx: true,
    brandsIndia: ['Taxim-O', 'Zifi', 'Cefolac', 'Mahacef'],
    brandsWorld: ['Suprax'],
    adultDose: '200 mg every 12 hours, or 400 mg once daily',
    pedsDose: '8 mg/kg/day, once daily or split every 12 h, by weight',
    lede: 'Cefixime is a cephalosporin antibiotic widely used in India for throat, ear, urinary and typhoid infections. It is convenient as a once- or twice-daily tablet or syrup.',
    uses: ['Throat, tonsil and ear infections', 'Urinary tract infections', 'Typhoid fever', 'Some chest infections'],
    sideEffects: ['Diarrhoea or loose stools', 'Nausea', 'Tummy pain'],
    precautions: ['Tell your doctor about penicillin/cephalosporin allergy', 'Complete the course', 'Take with food if it upsets the stomach'],
    warnings: ['Severe allergy (swelling, breathing difficulty)', 'Severe or bloody diarrhoea', 'Rash'],
    faqs: [
      { q: 'Is cefixime a strong antibiotic?', a: 'It is a broad-spectrum antibiotic effective against many common bacteria, which is why it is popular — but it should still be used only when a doctor advises.' },
      { q: 'Can I stop cefixime once I feel better?', a: 'No — finish the full course to clear the infection and reduce resistance.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['medicines/augmentin', 'Augmentin'], ['diseases/typhoid', 'Typhoid'], ['diseases/urinary-tract-infection', 'UTI']],
  },
  {
    slug: 'ciprofloxacin', name: 'Ciprofloxacin (Ciplox)', rx: true,
    brandsIndia: ['Ciplox', 'Cifran', 'Ciprobid'],
    brandsWorld: ['Cipro', 'Ciproxin'],
    adultDose: '250–750 mg every 12 hours depending on the infection',
    pedsDose: 'Generally avoided in children (joint/tendon concerns) — specialist use only',
    lede: 'Ciprofloxacin is a fluoroquinolone antibiotic for certain urinary, gut and other infections. It is powerful but reserved for when it is really needed, because of specific side effects.',
    uses: ['Urinary tract infections', 'Some gut infections (e.g. traveller’s diarrhoea)', 'Certain bone, skin and prostate infections'],
    sideEffects: ['Nausea and diarrhoea', 'Dizziness or headache', 'Sensitivity to sunlight'],
    precautions: ['Avoid taking with milk, antacids or iron at the same time', 'Report tendon pain and stop if it occurs', 'Caution with heart-rhythm risk and in the elderly'],
    warnings: ['Tendon pain or swelling (risk of rupture) — stop and seek advice', 'Palpitations or fainting', 'Numbness/tingling, or mood changes'],
    faqs: [
      { q: 'Why is ciprofloxacin not used more freely?', a: 'Fluoroquinolones can rarely cause tendon, nerve and heart-rhythm problems, so guidelines reserve them for infections where they are truly needed.' },
      { q: 'Can I take ciprofloxacin with milk?', a: 'Separate it from milk, dairy, antacids and iron by a couple of hours, as they reduce its absorption.' },
    ],
    related: [['medicines/levofloxacin', 'Levofloxacin'], ['medicines/cefixime', 'Cefixime'], ['diseases/urinary-tract-infection', 'UTI'], ['diseases/gastroenteritis', 'Gastroenteritis']],
  },
  {
    slug: 'levofloxacin', name: 'Levofloxacin', rx: true,
    brandsIndia: ['Levoflox', 'Loxof', 'Tavanic'],
    brandsWorld: ['Levaquin', 'Tavanic'],
    adultDose: '250–750 mg once daily depending on the infection',
    pedsDose: 'Generally avoided in children — specialist use only',
    lede: 'Levofloxacin is a fluoroquinolone antibiotic, often used once daily for respiratory and urinary infections when other antibiotics are unsuitable. It shares the fluoroquinolone cautions.',
    uses: ['Pneumonia and some chest infections', 'Complicated urinary infections', 'Sinus infections in certain cases'],
    sideEffects: ['Nausea and diarrhoea', 'Headache or dizziness', 'Sleep disturbance'],
    precautions: ['Report tendon pain immediately', 'Caution with heart-rhythm risk, diabetes and in the elderly', 'Keep well hydrated'],
    warnings: ['Tendon pain/swelling (rupture risk)', 'Palpitations or fainting', 'Nerve symptoms or mood changes'],
    faqs: [
      { q: 'Levofloxacin vs ciprofloxacin?', a: 'Both are fluoroquinolones; levofloxacin is often once daily and better for chest infections, ciprofloxacin more for urinary/gut. Your doctor picks based on the infection.' },
      { q: 'Is levofloxacin a strong antibiotic?', a: 'Yes, it is broad and potent — which is exactly why it is reserved for when simpler antibiotics will not do.' },
    ],
    related: [['medicines/ciprofloxacin', 'Ciprofloxacin'], ['medicines/azithromycin', 'Azithromycin'], ['diseases/pneumonia', 'Pneumonia'], ['diseases/sinusitis', 'Sinusitis']],
  },
  {
    slug: 'doxycycline', name: 'Doxycycline', rx: true,
    brandsIndia: ['Doxy-1', 'Minicycline', 'Doxt'],
    brandsWorld: ['Vibramycin', 'Doryx', 'Oracea'],
    adultDose: '100 mg every 12–24 hours depending on the infection',
    pedsDose: 'Avoid under 8 years (tooth staining) except for specific serious infections',
    lede: 'Doxycycline is a tetracycline antibiotic used for chest, skin and tick-borne infections, acne, and as malaria prevention. It should be taken sitting upright with water.',
    uses: ['Chest and sinus infections', 'Acne (long courses)', 'Tick-borne infections (e.g. scrub typhus)', 'Malaria prevention for travellers'],
    sideEffects: ['Nausea (take with food and water)', 'Sensitivity to sunlight', 'Throat irritation if not taken with enough water'],
    precautions: ['Take with a full glass of water, sitting upright, not before lying down', 'Use sun protection', 'Separate from milk, antacids and iron'],
    warnings: ['Severe headache with vision changes (rare pressure rise)', 'Painful swallowing or chest pain', 'Severe allergy'],
    faqs: [
      { q: 'Why take doxycycline with lots of water?', a: 'It can irritate or ulcerate the food pipe if it lodges there, so take it upright with a full glass of water and stay sitting for a while.' },
      { q: 'Can children take doxycycline?', a: 'It is usually avoided under 8 years because it can stain developing teeth, except for certain serious infections where the benefit outweighs this.' },
    ],
    related: [['medicines/azithromycin', 'Azithromycin'], ['diseases/scrub-typhus', 'Scrub typhus'], ['diseases/acne', 'Acne'], ['diseases/malaria', 'Malaria']],
  },
  {
    slug: 'metronidazole', name: 'Metronidazole (Flagyl)', rx: true,
    brandsIndia: ['Flagyl', 'Metrogyl', 'Aristogyl'],
    brandsWorld: ['Flagyl', 'Metrogel'],
    adultDose: '400 mg every 8 hours (range 200–800 mg by condition)',
    pedsDose: '7.5 mg/kg per dose every 8 hours, by weight',
    lede: 'Metronidazole is an antibiotic that also works against certain parasites. It treats specific gut, dental, gynaecological and skin infections. Key rule: no alcohol during the course.',
    uses: ['Gut infections (amoebiasis, giardia)', 'Dental and gum infections', 'Bacterial vaginosis and some pelvic infections', 'Some skin and wound infections'],
    sideEffects: ['Metallic taste', 'Nausea or reduced appetite', 'Dark-coloured urine (harmless)'],
    precautions: ['Avoid all alcohol during and 48 hours after the course', 'Complete the course', 'Tell your doctor about liver disease'],
    warnings: ['Strong reaction with alcohol (flushing, vomiting, fast heartbeat)', 'Numbness/tingling on long courses', 'Severe allergy'],
    faqs: [
      { q: 'Why no alcohol with metronidazole?', a: 'The combination can cause flushing, nausea, vomiting and a racing heart. Avoid alcohol during the course and for 48 hours after.' },
      { q: 'Why is my urine darker?', a: 'Metronidazole can harmlessly darken urine — a known, temporary effect.' },
    ],
    related: [['medicines/amoxicillin', 'Amoxicillin'], ['diseases/bacterial-vaginosis', 'Bacterial vaginosis'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['diseases/pid', 'Pelvic inflammatory disease']],
  },
  // ============================ Acidity / gut ============================
  {
    slug: 'pantoprazole', name: 'Pantoprazole (Pan, Pantop)', rx: true,
    brandsIndia: ['Pan', 'Pantop', 'Pantocid', 'Pantodac'],
    brandsWorld: ['Protonix', 'Controloc', 'Somac'],
    adultDose: '40 mg once daily, 30–60 minutes before food',
    pedsDose: 'Age ≥5 years, weight-based (15–40 mg) — specialist advice',
    lede: 'Pantoprazole is a proton-pump inhibitor (PPI) that strongly reduces stomach acid. It treats acidity, reflux and ulcers, and is often given with painkillers to protect the stomach.',
    uses: ['Acid reflux and heartburn (GERD)', 'Stomach and duodenal ulcers', 'Stomach protection with long-term painkillers', 'Part of H. pylori treatment'],
    sideEffects: ['Headache', 'Diarrhoea or constipation', 'Nausea'],
    precautions: ['Take before food', 'Review long-term use (low B12, magnesium, bone thinning)', 'Do not ignore ongoing symptoms without a diagnosis'],
    warnings: ['Weight loss, difficulty swallowing or black stools — see a doctor', 'Severe or lasting diarrhoea', 'Muscle cramps (possible low magnesium)'],
    faqs: [
      { q: 'Before or after food?', a: 'It works best on an empty stomach, usually 30–60 minutes before breakfast.' },
      { q: 'Is long-term pantoprazole safe?', a: 'Many use it safely, but long-term use should be reviewed by a doctor because of nutrient and bone effects — use the lowest effective dose.' },
    ],
    related: [['medicines/omeprazole', 'Omeprazole'], ['medicines/rabeprazole', 'Rabeprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['diseases/gastritis', 'Gastritis']],
  },
  {
    slug: 'omeprazole', name: 'Omeprazole', rx: false,
    brandsIndia: ['Omez', 'Ocid', 'Omecip'],
    brandsWorld: ['Prilosec', 'Losec'],
    adultDose: '20–40 mg once daily before food',
    pedsDose: 'Weight-based, about 0.5–1 mg/kg/day — specialist advice',
    lede: 'Omeprazole is a proton-pump inhibitor (PPI) that lowers stomach acid to treat acidity, reflux and ulcers. It is one of the most used stomach medicines worldwide.',
    uses: ['Acid reflux and heartburn (GERD)', 'Stomach and duodenal ulcers', 'Stomach protection with long-term painkillers', 'Part of H. pylori treatment'],
    sideEffects: ['Headache', 'Diarrhoea, constipation or wind', 'Nausea'],
    precautions: ['Take before food, usually before breakfast', 'Review long-term use', 'Can interact with some medicines (e.g. clopidogrel)'],
    warnings: ['Alarm symptoms (weight loss, trouble swallowing, black stools)', 'Severe diarrhoea', 'Muscle cramps (low magnesium)'],
    faqs: [
      { q: 'How long does omeprazole take to work?', a: 'It may ease symptoms in a day or two, with full benefit over a few days.' },
      { q: 'Can I take omeprazole daily?', a: 'Short courses are common; longer use should be guided by a doctor at the lowest effective dose.' },
    ],
    related: [['medicines/pantoprazole', 'Pantoprazole'], ['medicines/rabeprazole', 'Rabeprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['diseases/peptic-ulcer', 'Peptic ulcer']],
  },
  {
    slug: 'rabeprazole', name: 'Rabeprazole', rx: false,
    brandsIndia: ['Rabekind', 'Veloz', 'Rablet', 'Rabonik'],
    brandsWorld: ['Aciphex', 'Pariet'],
    adultDose: '20 mg once daily before food (10 mg for maintenance in some cases)',
    pedsDose: 'Age ≥12 years; younger children only on specialist advice',
    lede: 'Rabeprazole is a proton-pump inhibitor (PPI) for acidity, reflux and ulcers. It is often sold in India combined with domperidone (as “Rab-D”) for reflux with bloating.',
    uses: ['Acid reflux and heartburn (GERD)', 'Stomach and duodenal ulcers', 'Often combined with domperidone for reflux'],
    sideEffects: ['Headache', 'Diarrhoea or constipation', 'Nausea'],
    precautions: ['Take before food', 'Review long-term use', 'Swallow whole — do not crush enteric-coated tablets'],
    warnings: ['Alarm symptoms (weight loss, black stools, swallowing trouble)', 'Severe diarrhoea', 'Muscle cramps (low magnesium)'],
    faqs: [
      { q: 'Rabeprazole vs pantoprazole?', a: 'Both are PPIs that work similarly; differences are mainly in speed of onset and interactions. Your doctor chooses what suits you.' },
      { q: 'What is Rab-D?', a: 'It is rabeprazole combined with domperidone, used when reflux comes with bloating, nausea or a feeling of fullness.' },
    ],
    related: [['medicines/pantoprazole', 'Pantoprazole'], ['medicines/omeprazole', 'Omeprazole'], ['medicines/domperidone', 'Domperidone'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)']],
  },
  {
    slug: 'domperidone', name: 'Domperidone (Domstal)', rx: true,
    brandsIndia: ['Domstal', 'Motilium', 'Vomistop', 'Domperi'],
    brandsWorld: ['Motilium', '(not marketed in the USA)'],
    adultDose: '10 mg up to 3 times daily before meals, short-term (lowest effective dose)',
    pedsDose: 'Weight-based and cautious (heart-rhythm risk) — doctor only',
    lede: 'Domperidone relieves nausea, vomiting and bloating by helping the stomach empty. Because of a small heart-rhythm risk, it is used at the lowest dose for the shortest time.',
    uses: ['Nausea and vomiting', 'Bloating and fullness (indigestion)', 'Reflux with slow stomach emptying'],
    sideEffects: ['Dry mouth', 'Headache', 'Tummy cramps'],
    precautions: ['Use short-term at the lowest dose', 'Caution with heart conditions and certain medicines', 'Take before meals'],
    warnings: ['Palpitations, fainting or irregular heartbeat', 'Severe allergic reaction'],
    faqs: [
      { q: 'Is domperidone safe?', a: 'For short-term use at low doses it is generally safe, but it carries a small heart-rhythm risk, so it is avoided in people with certain heart problems or drug interactions.' },
      { q: 'When should I take domperidone?', a: 'Usually 15–30 minutes before meals, so it helps the stomach empty as you eat.' },
    ],
    related: [['medicines/ondansetron', 'Ondansetron'], ['medicines/rabeprazole', 'Rabeprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['symptoms/nausea-and-vomiting', 'Nausea & vomiting']],
  },
  {
    slug: 'ondansetron', name: 'Ondansetron (Emeset)', rx: true,
    brandsIndia: ['Emeset', 'Ondem', 'Vomikind', 'Osetron'],
    brandsWorld: ['Zofran', 'Zuplenz'],
    adultDose: '4–8 mg every 8–12 hours as needed',
    pedsDose: 'Weight-based, about 0.15 mg/kg per dose — doctor only',
    lede: 'Ondansetron is a strong anti-sickness medicine that blocks the nausea signal. It is widely used for vomiting from infections, chemotherapy, or after surgery.',
    uses: ['Vomiting from gastroenteritis or infections', 'Nausea from chemotherapy or after surgery', 'Severe vomiting in pregnancy (specialist advice)'],
    sideEffects: ['Constipation', 'Headache', 'Tiredness'],
    precautions: ['Caution with heart-rhythm problems', 'Tell your doctor about other medicines', 'Not a substitute for rehydration in diarrhoea'],
    warnings: ['Palpitations or fainting (heart-rhythm effect)', 'Severe constipation', 'Allergic reaction'],
    faqs: [
      { q: 'Is ondansetron better than domperidone?', a: 'Ondansetron is often more effective for significant vomiting; domperidone also helps bloating. The choice depends on the cause and your heart health.' },
      { q: 'Can I use ondansetron for a stomach bug?', a: 'A doctor may use it to control vomiting so you can keep fluids down, but rehydration with ORS remains the key treatment.' },
    ],
    related: [['medicines/domperidone', 'Domperidone'], ['medicines/ors', 'ORS'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['how-to-stop-diarrhea', 'How to stop diarrhoea']],
  },
  {
    slug: 'ors', name: 'ORS (Oral Rehydration Salts)', rx: false,
    brandsIndia: ['Electral', 'Enerzal', 'WHO-ORS', 'Prolyte'],
    brandsWorld: ['Pedialyte', 'Dioralyte', 'Hydralyte'],
    adultDose: 'Drink after each loose stool/vomit as needed (about 200 ml per stool); sip steadily',
    pedsDose: 'Under 2 yr: 50–100 ml after each stool; older children: 100–200 ml per stool',
    lede: 'ORS is a simple, life-saving mix of salts and glucose in clean water. It replaces water and salts lost in diarrhoea, vomiting or heat, and is the first-line treatment for dehydration.',
    uses: ['Preventing and treating dehydration from diarrhoea or vomiting', 'Fluid loss from heat or heavy sweating', 'Recovery of fluids and salts in gastroenteritis'],
    sideEffects: ['Very few when prepared correctly', 'Mild nausea if drunk too fast'],
    precautions: ['Mix one sachet with the exact water stated on the pack', 'Do not add extra sugar or salt', 'Sip slowly and often'],
    warnings: ['Severe dehydration (sunken eyes, very little urine, drowsiness) needs medical care', 'Unable to keep fluids down', 'Blood in stools or high fever'],
    faqs: [
      { q: 'How do I prepare ORS correctly?', a: 'Dissolve one full sachet in the exact volume of clean water on the pack. Too little water makes it too concentrated and unsafe.' },
      { q: 'Can adults use ORS?', a: 'Yes — anyone losing fluids from diarrhoea, vomiting or heat benefits, not just children.' },
    ],
    related: [['how-to-stop-diarrhea', 'How to stop diarrhoea'], ['diseases/dehydration', 'Dehydration'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['medicines/ondansetron', 'Ondansetron']],
  },
  // ============================ Allergy / respiratory ============================
  {
    slug: 'cetirizine', name: 'Cetirizine (Cetzine, Alerid)', rx: false,
    brandsIndia: ['Cetzine', 'Alerid', 'Okacet', 'Cetriz'],
    brandsWorld: ['Zyrtec', 'Reactine', 'Zirtek'],
    adultDose: '10 mg once daily',
    pedsDose: '6 months–2 yr: 2.5 mg; 2–6 yr: 2.5–5 mg; 6 yr+: 5–10 mg once daily',
    lede: 'Cetirizine is a common antihistamine for allergies — sneezing, runny nose, itching and hives. It causes less drowsiness than older antihistamines, though some people still feel sleepy.',
    uses: ['Allergic rhinitis (sneezing, runny/itchy nose)', 'Itchy, watery eyes', 'Hives and skin itching', 'Dust, pollen or pet allergies'],
    sideEffects: ['Drowsiness in some people', 'Dry mouth', 'Headache'],
    precautions: ['Be careful driving if sleepy', 'Alcohol increases drowsiness', 'Lower dose in kidney problems'],
    warnings: ['Severe allergic reaction (rare)', 'Marked drowsiness affecting safety'],
    faqs: [
      { q: 'Cetirizine or levocetirizine?', a: 'Levocetirizine is a refined form and may be slightly less sedating for some. Both work well; response varies.' },
      { q: 'Can I take cetirizine daily?', a: 'Many take it daily in allergy seasons and it is generally safe, but discuss long-term daily use with a doctor.' },
    ],
    related: [['medicines/levocetirizine', 'Levocetirizine'], ['medicines/montelukast', 'Montelukast'], ['medicines/pheniramine-avil', 'Pheniramine (Avil)'], ['diseases/allergic-rhinitis', 'Allergic rhinitis']],
  },
  {
    slug: 'levocetirizine', name: 'Levocetirizine (Xyzal)', rx: false,
    brandsIndia: ['Levocet', '1-Al', 'Vozet', 'Xyzal', 'Teczine'],
    brandsWorld: ['Xyzal', 'Xusal'],
    adultDose: '5 mg once daily, often in the evening',
    pedsDose: '6 months–5 yr: 1.25 mg; 6–11 yr: 2.5 mg; 12 yr+: 5 mg once daily',
    lede: 'Levocetirizine is a refined antihistamine for allergies, giving relief with generally low drowsiness. It is used for hay fever, hives and itchy allergic symptoms.',
    uses: ['Allergic rhinitis (hay fever)', 'Hives (urticaria) and itching', 'Allergy from dust, pollen or pets'],
    sideEffects: ['Mild drowsiness in some', 'Dry mouth', 'Tiredness or headache'],
    precautions: ['Take in the evening if it makes you sleepy', 'Alcohol adds to drowsiness', 'Lower dose in kidney problems'],
    warnings: ['Severe allergic reaction (rare)', 'Excess drowsiness'],
    faqs: [
      { q: 'Is levocetirizine non-drowsy?', a: 'It is low-sedating for most people, though a minority feel drowsy — taking it at night helps.' },
      { q: 'How is it different from cetirizine?', a: 'It is the active half of cetirizine, so a smaller dose gives similar relief, sometimes with slightly less drowsiness.' },
    ],
    related: [['medicines/cetirizine', 'Cetirizine'], ['medicines/montelukast', 'Montelukast'], ['diseases/allergic-rhinitis', 'Allergic rhinitis'], ['diseases/hives-urticaria', 'Hives (urticaria)']],
  },
  {
    slug: 'pheniramine-avil', name: 'Pheniramine (Avil)', rx: false,
    brandsIndia: ['Avil', 'Anvil'],
    brandsWorld: ['(pheniramine; older antihistamine class similar to Piriton)'],
    adultDose: '22.5–45 mg (e.g. Avil 25 mg) 2–3 times daily; injection used for severe allergy under care',
    pedsDose: 'Small weight/age-based dose — doctor advice (causes drowsiness)',
    lede: 'Pheniramine (Avil) is an older, sedating antihistamine used for allergies, itching and allergic reactions. It works quickly but commonly causes drowsiness.',
    uses: ['Allergic reactions, hives and itching', 'Runny nose and sneezing', 'Allergic reaction support (injection, under medical care)'],
    sideEffects: ['Drowsiness (common)', 'Dry mouth', 'Blurred vision or constipation'],
    precautions: ['Do not drive or operate machinery if drowsy', 'Avoid alcohol', 'Caution in the elderly, glaucoma and prostate problems'],
    warnings: ['Severe allergic reaction (seek emergency care for breathing difficulty/swelling)', 'Marked drowsiness or confusion'],
    faqs: [
      { q: 'Why does Avil make me sleepy?', a: 'It is an older antihistamine that crosses into the brain more than newer ones, which is why drowsiness is common. Non-drowsy options like cetirizine exist.' },
      { q: 'Is Avil used for serious allergic reactions?', a: 'The injection is sometimes given as part of treating allergic reactions under medical care, but a severe reaction (anaphylaxis) is an emergency needing adrenaline.' },
    ],
    related: [['medicines/cetirizine', 'Cetirizine'], ['medicines/levocetirizine', 'Levocetirizine'], ['diseases/anaphylaxis', 'Anaphylaxis'], ['diseases/hives-urticaria', 'Hives (urticaria)']],
  },
  {
    slug: 'montelukast', name: 'Montelukast (Montair)', rx: true,
    brandsIndia: ['Montair', 'Montek', 'Romilast', 'Telekast'],
    brandsWorld: ['Singulair'],
    adultDose: '10 mg once daily in the evening',
    pedsDose: '2–5 yr: 4 mg; 6–14 yr: 5 mg; 15 yr+: 10 mg, once daily evening',
    lede: 'Montelukast is a daily preventer for asthma and allergic rhinitis. It reduces airway inflammation but is not a reliever — it does not treat a sudden asthma attack.',
    uses: ['Preventing asthma symptoms (controller)', 'Allergic rhinitis (hay fever)', 'Exercise-induced breathing symptoms'],
    sideEffects: ['Headache', 'Tummy upset', 'Vivid dreams or sleep changes'],
    precautions: ['Not for a sudden attack — keep your reliever inhaler', 'Often taken in the evening', 'Watch for mood or behaviour changes'],
    warnings: ['Mental-health changes — agitation, low mood, unusual thoughts — tell your doctor promptly', 'A severe asthma attack needs your reliever and urgent care'],
    faqs: [
      { q: 'Is montelukast a steroid?', a: 'No — it is a leukotriene receptor antagonist, a different anti-inflammatory taken as a tablet.' },
      { q: 'Does montelukast affect mood?', a: 'Some people notice sleep, mood or behaviour changes. These are recognised, so report anything unusual.' },
    ],
    related: [['medicines/cetirizine', 'Cetirizine'], ['medicines/salbutamol', 'Salbutamol'], ['diseases/asthma', 'Asthma'], ['diseases/allergic-rhinitis', 'Allergic rhinitis']],
  },
  {
    slug: 'salbutamol', name: 'Salbutamol / Albuterol (Asthalin)', rx: true,
    brandsIndia: ['Asthalin', 'Levolin (levosalbutamol)', 'Aerocort'],
    brandsWorld: ['Ventolin', 'ProAir', 'Proventil (albuterol)'],
    adultDose: 'Inhaler 100 mcg: 1–2 puffs as needed for symptoms (and before exercise)',
    pedsDose: '1–2 puffs as needed via inhaler with a spacer; dose set by doctor',
    lede: 'Salbutamol (called albuterol in the USA) is a reliever inhaler that quickly opens tight airways in asthma. It eases wheeze and breathlessness within minutes but does not treat the underlying inflammation.',
    uses: ['Quick relief of asthma symptoms (wheeze, breathlessness)', 'Before exercise to prevent symptoms', 'COPD flare-ups'],
    sideEffects: ['Shakiness or tremor', 'Fast heartbeat', 'Headache'],
    precautions: ['Use a spacer for better delivery, especially in children', 'Needing it often means asthma is not controlled — see your doctor', 'Carry it at all times if asthmatic'],
    warnings: ['Reliever not working, or needing it very often — urgent asthma review', 'Severe breathlessness, blue lips, unable to speak — emergency'],
    faqs: [
      { q: 'How often can I use my salbutamol inhaler?', a: 'For quick relief as needed, but if you need it more than a couple of times a week your asthma control needs reviewing. Overuse is a warning sign.' },
      { q: 'Is salbutamol a steroid?', a: 'No — it is a fast-acting bronchodilator (reliever). Preventer inhalers, which are often steroids, treat the underlying inflammation.' },
    ],
    related: [['medicines/montelukast', 'Montelukast'], ['diseases/asthma', 'Asthma'], ['diseases/copd', 'COPD'], ['diseases/childhood-asthma', 'Childhood asthma']],
  },
  // ============================ Heart / blood pressure ============================
  {
    slug: 'amlodipine', name: 'Amlodipine (Amlong)', rx: true,
    brandsIndia: ['Amlong', 'Amlopres', 'Stamlo', 'Amlokind'],
    brandsWorld: ['Norvasc', 'Istin'],
    adultDose: '5 mg once daily, increased to 10 mg if needed',
    pedsDose: 'Age ≥6 yr: 2.5–5 mg once daily',
    lede: 'Amlodipine is a common blood-pressure medicine (calcium-channel blocker). It relaxes and widens blood vessels, lowering blood pressure and easing angina. It is usually taken once a day, long term.',
    uses: ['High blood pressure (hypertension)', 'Angina (chest pain from the heart)'],
    sideEffects: ['Ankle or leg swelling', 'Flushing and headache', 'Tiredness or dizziness'],
    precautions: ['Do not stop suddenly', 'Grapefruit can raise its levels', 'Rise slowly to avoid dizziness'],
    warnings: ['Marked ankle swelling or sudden weight gain', 'Fainting or very low blood pressure', 'Worsening chest pain'],
    faqs: [
      { q: 'Best time to take amlodipine?', a: 'Any consistent time of day, with or without food.' },
      { q: 'Why does it cause ankle swelling?', a: 'It widens small vessels, letting fluid pool in the ankles. Tell your doctor if troublesome.' },
    ],
    related: [['medicines/telmisartan', 'Telmisartan'], ['medicines/losartan', 'Losartan'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['diseases/hypertension', 'Hypertension']],
  },
  {
    slug: 'telmisartan', name: 'Telmisartan', rx: true,
    brandsIndia: ['Telma', 'Telsartan', 'Telpres', 'Tazloc'],
    brandsWorld: ['Micardis', 'Pritor'],
    adultDose: '20–80 mg once daily',
    pedsDose: 'Not established in children — avoid',
    lede: 'Telmisartan is a widely used blood-pressure medicine (an ARB). It relaxes blood vessels and protects the heart and kidneys, often chosen for people with diabetes or kidney concerns.',
    uses: ['High blood pressure', 'Kidney protection in diabetes', 'Reducing cardiovascular risk in some people'],
    sideEffects: ['Dizziness, especially at first', 'Tiredness', 'Rarely, raised blood potassium'],
    precautions: ['Not to be used in pregnancy', 'Kidney function and potassium may be monitored', 'Rise slowly to avoid dizziness'],
    warnings: ['Fainting or very low blood pressure', 'Facial/throat swelling (rare — urgent)', 'Muscle weakness or palpitations (high potassium)'],
    faqs: [
      { q: 'Telmisartan or amlodipine?', a: 'Both are effective and sometimes combined; telmisartan is often preferred with diabetes or kidney disease. Your doctor decides.' },
      { q: 'Is telmisartan safe in pregnancy?', a: 'No — ARBs should be avoided in pregnancy. Tell your doctor if pregnant or planning to be.' },
    ],
    related: [['medicines/amlodipine', 'Amlodipine'], ['medicines/losartan', 'Losartan'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['diseases/chronic-kidney-disease', 'Chronic kidney disease']],
  },
  {
    slug: 'losartan', name: 'Losartan', rx: true,
    brandsIndia: ['Losar', 'Repace', 'Covance', 'Losakind'],
    brandsWorld: ['Cozaar'],
    adultDose: '50 mg once daily (range 25–100 mg)',
    pedsDose: 'Age ≥6 yr: about 0.7 mg/kg once daily (max 50 mg) — specialist',
    lede: 'Losartan is a blood-pressure medicine (ARB) that relaxes blood vessels and protects the kidneys, and it also lowers uric acid slightly. It is taken once daily, long term.',
    uses: ['High blood pressure', 'Kidney protection in diabetes', 'Heart protection in some people'],
    sideEffects: ['Dizziness at first', 'Tiredness', 'Rarely, raised potassium'],
    precautions: ['Avoid in pregnancy', 'Monitor kidney function and potassium', 'Rise slowly to avoid dizziness'],
    warnings: ['Fainting or very low blood pressure', 'Facial/throat swelling (rare — urgent)', 'Muscle weakness or palpitations (high potassium)'],
    faqs: [
      { q: 'Losartan or telmisartan?', a: 'Both are ARBs; telmisartan lasts a little longer. The best choice depends on your blood pressure pattern and other conditions.' },
      { q: 'Does losartan help with uric acid?', a: 'It has a mild uric-acid-lowering effect, which can be a bonus for some people with gout and high blood pressure.' },
    ],
    related: [['medicines/telmisartan', 'Telmisartan'], ['medicines/amlodipine', 'Amlodipine'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['diseases/hypertension', 'Hypertension']],
  },
  {
    slug: 'metoprolol', name: 'Metoprolol', rx: true,
    brandsIndia: ['Metolar', 'Betaloc', 'Metpure', 'Starpress'],
    brandsWorld: ['Lopressor', 'Toprol-XL'],
    adultDose: '25–100 mg once or twice daily depending on the formulation and condition',
    pedsDose: 'Specialist use only, weight-based',
    lede: 'Metoprolol is a beta-blocker that slows the heart and lowers blood pressure. It is used for high blood pressure, angina, some abnormal rhythms and after a heart attack.',
    uses: ['High blood pressure', 'Angina', 'Certain fast heart rhythms', 'After a heart attack; heart failure (specific forms)'],
    sideEffects: ['Tiredness', 'Cold hands and feet', 'Slow heartbeat or dizziness'],
    precautions: ['Do not stop suddenly (rebound effects)', 'Caution in asthma and certain heart conditions', 'May mask low-sugar warning signs in diabetes'],
    warnings: ['Very slow pulse, fainting or breathlessness', 'Worsening wheeze in asthma', 'Swelling or rapid weight gain'],
    faqs: [
      { q: 'Can I stop metoprolol suddenly?', a: 'No — stopping abruptly can cause a rebound rise in heart rate and blood pressure. Any change must be gradual and doctor-guided.' },
      { q: 'Why do beta-blockers make me tired?', a: 'By slowing the heart they can reduce energy at first; this often settles. Tell your doctor if it persists.' },
    ],
    related: [['medicines/amlodipine', 'Amlodipine'], ['medicines/telmisartan', 'Telmisartan'], ['diseases/hypertension', 'Hypertension'], ['diseases/atrial-fibrillation', 'Atrial fibrillation']],
  },
  {
    slug: 'atorvastatin', name: 'Atorvastatin (Atorva, Lipitor)', rx: true,
    brandsIndia: ['Atorva', 'Storvas', 'Lipvas', 'Atocor'],
    brandsWorld: ['Lipitor'],
    adultDose: '10–80 mg once daily (any time of day)',
    pedsDose: 'Age ≥10 yr for familial high cholesterol: 10–20 mg — specialist',
    lede: 'Atorvastatin is a statin that lowers cholesterol, especially LDL (“bad”) cholesterol, to reduce the risk of heart attack and stroke. It is usually taken once a day, long term.',
    uses: ['Lowering high cholesterol', 'Preventing heart attack and stroke in at-risk people', 'After a heart attack or stroke'],
    sideEffects: ['Muscle aches', 'Digestive upset', 'Rarely, raised liver enzymes'],
    precautions: ['Avoid in pregnancy', 'Limit alcohol; grapefruit raises its levels', 'Occasional liver blood tests'],
    warnings: ['Unexplained muscle pain/weakness with dark urine — seek advice (rare muscle problem)', 'Yellow eyes or severe tummy pain'],
    faqs: [
      { q: 'Should I take atorvastatin at night?', a: 'It works well at any time of day, unlike some older statins. Take it consistently.' },
      { q: 'Do I need a statin for life?', a: 'Often yes, as cholesterol rises again if it stops. Do not stop without discussing it with your doctor.' },
    ],
    related: [['how-to-lower-cholesterol', 'How to lower cholesterol'], ['blood-tests/lipid-profile-cholesterol', 'Lipid profile'], ['diseases/high-cholesterol', 'High cholesterol'], ['diseases/coronary-artery-disease', 'Coronary artery disease']],
  },
  {
    slug: 'clopidogrel', name: 'Clopidogrel (Plavix)', rx: true,
    brandsIndia: ['Clopilet', 'Deplatt', 'Clopid', 'Plavix'],
    brandsWorld: ['Plavix'],
    adultDose: '75 mg once daily (a 300–600 mg loading dose may be given at the start)',
    pedsDose: 'Specialist use only',
    lede: 'Clopidogrel is a blood thinner (antiplatelet) that stops platelets clumping, reducing the risk of clots, heart attack and stroke. It is often used with aspirin after stents or a heart attack.',
    uses: ['After a heart attack or stent', 'After certain strokes/TIAs', 'Peripheral artery disease'],
    sideEffects: ['Easier bruising or bleeding', 'Indigestion', 'Diarrhoea'],
    precautions: ['Tell dentists/surgeons before procedures', 'Do not stop suddenly without advice (clot risk)', 'Some acid medicines (omeprazole) may reduce its effect'],
    warnings: ['Unusual or prolonged bleeding, black stools or blood in urine', 'Signs of a clot despite treatment (chest pain, stroke symptoms)'],
    faqs: [
      { q: 'Can I stop clopidogrel for surgery?', a: 'Only on your doctor’s/surgeon’s advice — stopping at the wrong time after a stent can cause a dangerous clot.' },
      { q: 'Clopidogrel vs aspirin?', a: 'Both prevent clots differently and are often used together for a period after heart events, then sometimes one alone. Your cardiologist decides.' },
    ],
    related: [['medicines/aspirin', 'Aspirin'], ['diseases/heart-attack', 'Heart attack'], ['diseases/stroke', 'Stroke'], ['diseases/coronary-artery-disease', 'Coronary artery disease']],
  },
  // ============================ Thyroid ============================
  {
    slug: 'levothyroxine', name: 'Levothyroxine (Thyronorm, Eltroxin)', rx: true,
    brandsIndia: ['Thyronorm', 'Eltroxin', 'Thyrox'],
    brandsWorld: ['Synthroid', 'Euthyrox', 'Levoxyl'],
    adultDose: 'About 1.6 mcg/kg once daily on an empty stomach (typically 50–150 mcg); adjusted by blood tests',
    pedsDose: 'Weight-based (higher per kg than adults) — set by a doctor',
    lede: 'Levothyroxine replaces the thyroid hormone missing in an underactive thyroid (hypothyroidism). Taken correctly it restores normal energy and metabolism, and is usually needed long term.',
    uses: ['Underactive thyroid (hypothyroidism)', 'After thyroid surgery or radioactive iodine', 'Certain thyroid conditions in pregnancy'],
    sideEffects: ['Few if the dose is right', 'Too much: palpitations, weight loss, shakiness', 'Too little: tiredness, weight gain, feeling cold'],
    precautions: ['Take on an empty stomach, 30–60 min before breakfast', 'Separate from calcium, iron and antacids by a few hours', 'Stay on the same brand'],
    warnings: ['Chest pain or racing/irregular heartbeat (over-replacement)', 'Symptoms returning strongly (under-treatment)'],
    faqs: [
      { q: 'Why on an empty stomach?', a: 'Food, coffee and some minerals reduce absorption, so take it 30–60 minutes before breakfast for steady levels.' },
      { q: 'Do I need it for life?', a: 'Usually yes — the thyroid cannot make enough on its own; the dose is fine-tuned with blood tests.' },
    ],
    related: [['diseases/hypothyroidism', 'Hypothyroidism'], ['blood-tests/thyroid-function-test-tft', 'Thyroid function test'], ['blood-tests/tsh', 'TSH test'], ['diseases/thyroid-disorders', 'Thyroid disorders']],
  },
  // ============================ Steroids ============================
  {
    slug: 'prednisolone', name: 'Prednisolone', rx: true,
    brandsIndia: ['Wysolone', 'Omnacortil', 'Predmet'],
    brandsWorld: ['Prelone', 'Millipred', '(prednisone: Deltasone)'],
    adultDose: 'Varies widely by condition (e.g. 5–60 mg/day); taken in the morning, tapered — never stopped abruptly',
    pedsDose: 'About 1–2 mg/kg/day, short courses — doctor only',
    lede: 'Prednisolone is a steroid (corticosteroid) that powerfully reduces inflammation and calms an overactive immune system. It treats many conditions but must be tapered, not stopped suddenly.',
    uses: ['Asthma and COPD flare-ups', 'Severe allergies and skin conditions', 'Autoimmune and inflammatory diseases', 'Some cancers and after transplants'],
    sideEffects: ['Increased appetite and weight gain', 'Raised blood sugar and blood pressure', 'Mood changes, sleep problems, stomach upset'],
    precautions: ['Take in the morning with food', 'Never stop suddenly after longer courses (taper)', 'Long-term use affects bones, sugar and infection risk'],
    warnings: ['Signs of infection while on steroids (they can be masked)', 'Severe mood changes', 'Symptoms of adrenal problems if stopped abruptly (weakness, dizziness)'],
    faqs: [
      { q: 'Why can’t I stop steroids suddenly?', a: 'After more than a short course, the body reduces its own steroid production. Stopping suddenly can cause a dangerous drop — the dose is tapered down.' },
      { q: 'Do steroids cause weight gain?', a: 'They can increase appetite and fluid retention, especially with longer use. Shorter courses have less effect.' },
    ],
    related: [['medicines/dexamethasone', 'Dexamethasone'], ['diseases/asthma', 'Asthma'], ['diseases/rheumatoid-arthritis', 'Rheumatoid arthritis'], ['medicines/salbutamol', 'Salbutamol']],
  },
  {
    slug: 'dexamethasone', name: 'Dexamethasone', rx: true,
    brandsIndia: ['Decdan', 'Dexona', 'Wymesone'],
    brandsWorld: ['Decadron', 'Ozurdex (eye)'],
    adultDose: 'Varies widely (e.g. 0.5–8 mg/day, higher in some conditions); as directed',
    pedsDose: 'Weight-based, condition-specific — doctor only',
    lede: 'Dexamethasone is a strong, long-acting steroid used for serious inflammation, allergic reactions, some cancers, brain swelling and certain infections. It is potent, so it is dosed carefully.',
    uses: ['Severe inflammation and allergic reactions', 'Brain swelling and some cancers', 'Certain severe infections (as add-on)', 'Nausea from chemotherapy'],
    sideEffects: ['Raised blood sugar', 'Mood and sleep changes', 'Increased appetite, fluid retention'],
    precautions: ['Do not stop abruptly after longer use', 'Monitor blood sugar, especially in diabetes', 'Watch for infections'],
    warnings: ['Signs of infection (fever, feeling very unwell)', 'Severe mood disturbance', 'Very high blood sugar'],
    faqs: [
      { q: 'Is dexamethasone stronger than prednisolone?', a: 'Yes — it is more potent and longer-acting, so much smaller doses are used. Your doctor chooses based on the condition.' },
      { q: 'Is dexamethasone misused for weight/skin?', a: 'Yes — unsupervised use for weight gain or fairness is dangerous and can cause serious harm. Only use it as prescribed.' },
    ],
    related: [['medicines/prednisolone', 'Prednisolone'], ['diseases/anaphylaxis', 'Anaphylaxis'], ['diseases/brain-tumour', 'Brain tumour'], ['medicines/ondansetron', 'Ondansetron']],
  },
  // ============================ Nervous system / mental health ============================
  {
    slug: 'pregabalin', name: 'Pregabalin (Lyrica)', rx: true,
    brandsIndia: ['Pregeb', 'Pregabid', 'Nervmax', 'Maxgalin'],
    brandsWorld: ['Lyrica'],
    adultDose: '75 mg twice daily, up to 300 mg/day (max 600 mg); tapered when stopping',
    pedsDose: 'Not established in children',
    lede: 'Pregabalin calms overactive nerve signals. It is used for nerve pain, some seizures and anxiety. It can cause dependence, so it is prescribed and stopped carefully.',
    uses: ['Nerve pain (diabetic neuropathy, sciatica, shingles pain)', 'Some seizure types (add-on)', 'Generalised anxiety (in some countries)'],
    sideEffects: ['Drowsiness and dizziness', 'Weight gain', 'Blurred vision or swelling'],
    precautions: ['Do not drive until you know how it affects you', 'Do not stop suddenly (taper)', 'Avoid alcohol; caution with other sedatives'],
    warnings: ['Severe drowsiness or breathing problems (especially with opioids/sedatives)', 'Mood changes or thoughts of self-harm', 'Signs of allergy'],
    faqs: [
      { q: 'Is pregabalin addictive?', a: 'It can cause dependence and is sometimes misused, so it is prescribed carefully, at controlled doses, and tapered rather than stopped suddenly.' },
      { q: 'Why does pregabalin make me sleepy?', a: 'It calms nerve activity, which commonly causes drowsiness and dizziness, especially at first. Avoid driving until you know your response.' },
    ],
    related: [['medicines/gabapentin', 'Gabapentin'], ['diseases/peripheral-neuropathy', 'Peripheral neuropathy'], ['diseases/sciatica', 'Sciatica'], ['diseases/shingles', 'Shingles']],
  },
  {
    slug: 'gabapentin', name: 'Gabapentin', rx: true,
    brandsIndia: ['Gabapin', 'Gabantin', 'Neurontin'],
    brandsWorld: ['Neurontin', 'Gralise'],
    adultDose: 'Started low and increased gradually (e.g. 300 mg/day up to 1800–3600 mg/day in divided doses)',
    pedsDose: 'Specialist use only, weight-based',
    lede: 'Gabapentin calms overactive nerves and is used for nerve pain and some seizures. Like pregabalin, it is started low, increased slowly, and tapered when stopping.',
    uses: ['Nerve pain (neuropathy, shingles pain)', 'Some seizure types (add-on)', 'Restless legs in some cases'],
    sideEffects: ['Drowsiness and dizziness', 'Swelling of the ankles', 'Weight gain'],
    precautions: ['Increase and decrease the dose gradually', 'Caution driving; avoid alcohol', 'Adjust in kidney disease'],
    warnings: ['Severe drowsiness or breathing problems (with opioids/sedatives)', 'Mood changes or thoughts of self-harm', 'Allergic reaction'],
    faqs: [
      { q: 'Gabapentin or pregabalin — what is the difference?', a: 'They are related; pregabalin is absorbed more predictably and dosed twice daily, gabapentin needs slower titration. Your doctor chooses based on response and cost.' },
      { q: 'Can I stop gabapentin suddenly?', a: 'No — stopping abruptly can cause withdrawal or seizures. It should be tapered under medical guidance.' },
    ],
    related: [['medicines/pregabalin', 'Pregabalin'], ['diseases/peripheral-neuropathy', 'Peripheral neuropathy'], ['diseases/epilepsy', 'Epilepsy'], ['diseases/shingles', 'Shingles']],
  },
  {
    slug: 'sertraline', name: 'Sertraline (Zoloft)', rx: true,
    brandsIndia: ['Serta', 'Zosert', 'Daxid', 'Serlift'],
    brandsWorld: ['Zoloft', 'Lustral'],
    adultDose: '50 mg once daily (range 25–200 mg); started low and adjusted',
    pedsDose: 'For OCD in children ≥6 yr under specialist care only',
    lede: 'Sertraline is a common antidepressant (SSRI) used for depression, anxiety, OCD and related conditions. It works gradually over weeks and should be tapered, not stopped suddenly.',
    uses: ['Depression', 'Anxiety and panic disorder', 'OCD and PTSD', 'Some other anxiety-related conditions'],
    sideEffects: ['Nausea, especially early on', 'Sleep changes', 'Sexual side effects; early jitteriness'],
    precautions: ['Full effect takes 4–6 weeks — do not stop early', 'Do not stop suddenly (taper to avoid withdrawal)', 'Tell your doctor about other medicines (interactions)'],
    warnings: ['Worsening mood or thoughts of self-harm, especially in the first weeks — seek help urgently', 'Agitation, high fever or confusion (rare serotonin syndrome)', 'Unusual bleeding'],
    faqs: [
      { q: 'How long does sertraline take to work?', a: 'Some effects appear in 1–2 weeks, but the full benefit usually takes 4–6 weeks. Keep taking it and stay in touch with your doctor.' },
      { q: 'Can I stop sertraline once I feel better?', a: 'Not suddenly. Stopping should be gradual and doctor-guided, and treatment often continues for a while after you feel well to prevent relapse.' },
    ],
    related: [['diseases/depression', 'Depression'], ['diseases/generalised-anxiety-disorder', 'Anxiety disorder'], ['diseases/ocd', 'OCD'], ['diseases/panic-disorder', 'Panic disorder']],
  },
  // ============================ Vitamins & supplements ============================
  {
    slug: 'vitamin-d3', name: 'Vitamin D3 (Cholecalciferol)', rx: false,
    brandsIndia: ['Uprise-D3', 'Calcirol', 'D-Rise', 'Tayo 60K'],
    brandsWorld: ['(cholecalciferol; many brands, e.g. D3)'],
    adultDose: 'Maintenance 400–2000 IU/day; deficiency often 60,000 IU weekly for 6–8 weeks (as advised)',
    pedsDose: 'Infants 400 IU/day; deficiency doses are age/weight-based by a doctor',
    lede: 'Vitamin D3 keeps bones healthy by helping the body absorb calcium. Deficiency is very common in India and can cause tiredness, bone and muscle aches. It is corrected with supplements and sunlight.',
    uses: ['Treating and preventing vitamin D deficiency', 'Bone health (with calcium)', 'Supporting muscle function'],
    sideEffects: ['Usually none at normal doses', 'Very high doses can raise blood calcium (nausea, thirst, kidney issues)'],
    precautions: ['Do not take very high doses without testing/advice', 'Take fatty-food-containing meals for better absorption', 'Combine with calcium as advised'],
    warnings: ['Symptoms of high calcium from overdose: nausea, excessive thirst, confusion', 'Kidney stones with prolonged excess'],
    faqs: [
      { q: 'How much vitamin D should I take?', a: 'Maintenance is often 400–2000 IU/day, but deficiency is treated with higher weekly doses for a few weeks. Ideally, dose is guided by a blood test.' },
      { q: 'Can I get enough vitamin D from sunlight?', a: 'Sensible sun exposure helps, but many people in cities, with darker skin or limited sun still fall short and need supplements.' },
    ],
    related: [['blood-tests/vitamin-d', 'Vitamin D test'], ['medicines/calcium-supplement', 'Calcium supplement'], ['diseases/vitamin-d-deficiency', 'Vitamin D deficiency'], ['diseases/osteoporosis', 'Osteoporosis']],
  },
  {
    slug: 'calcium-supplement', name: 'Calcium Supplement', rx: false,
    brandsIndia: ['Shelcal', 'Calcimax', 'Gemcal', 'Cipcal'],
    brandsWorld: ['Caltrate', 'Citracal', 'Os-Cal'],
    adultDose: '500–1000 mg elemental calcium/day (often with vitamin D), split doses for better absorption',
    pedsDose: 'Prefer dietary calcium; supplements only if a doctor advises, age-based',
    lede: 'Calcium supplements support bone health, usually taken with vitamin D. They are used in deficiency, osteoporosis prevention, pregnancy and for people who don’t get enough calcium from food.',
    uses: ['Bone health and osteoporosis prevention', 'Calcium deficiency', 'Pregnancy and breastfeeding needs', 'With vitamin D for bone protection'],
    sideEffects: ['Constipation or bloating', 'Wind', 'Rarely, kidney stones with excess'],
    precautions: ['Take in split doses (absorption is better ≤500 mg at a time)', 'Separate from iron and thyroid medicine', 'Do not exceed recommended amounts'],
    warnings: ['Symptoms of high calcium: nausea, excessive thirst, confusion', 'Kidney stones with long-term excess'],
    faqs: [
      { q: 'Should I take calcium with or without food?', a: 'Calcium carbonate is best with food; calcium citrate can be taken any time. Split larger amounts across the day for better absorption.' },
      { q: 'Do I need vitamin D with calcium?', a: 'Usually yes — vitamin D helps the body absorb calcium, which is why they are often combined.' },
    ],
    related: [['medicines/vitamin-d3', 'Vitamin D3'], ['blood-tests/calcium', 'Calcium test'], ['diseases/osteoporosis', 'Osteoporosis'], ['diseases/vitamin-d-deficiency', 'Vitamin D deficiency']],
  },
  {
    slug: 'iron-folic-acid', name: 'Iron & Folic Acid', rx: false,
    brandsIndia: ['Livogen', 'Autrin', 'Dexorange', 'Orofer-XT'],
    brandsWorld: ['(ferrous sulfate/fumarate + folic acid; many brands)'],
    adultDose: 'Anaemia: ~100 mg elemental iron/day; folic acid often 5 mg/day (as advised)',
    pedsDose: '3–6 mg/kg/day elemental iron for deficiency — by a doctor',
    lede: 'Iron and folic acid treat and prevent the most common form of anaemia. They are widely used in pregnancy and for iron-deficiency anaemia, especially in women and growing children.',
    uses: ['Iron-deficiency anaemia', 'Pregnancy (iron + folic acid)', 'Preventing anaemia in at-risk groups'],
    sideEffects: ['Constipation or dark stools (harmless)', 'Nausea or stomach upset', 'Metallic taste'],
    precautions: ['Take with vitamin C (citrus) for better absorption', 'Separate from tea, coffee, calcium and antacids', 'Keep away from children (overdose is dangerous)'],
    warnings: ['Accidental iron overdose in children is a medical emergency', 'Severe tummy pain or vomiting', 'No improvement in anaemia despite treatment (needs review)'],
    faqs: [
      { q: 'Why are my stools black on iron?', a: 'Iron harmlessly darkens the stool — a normal effect. Black, tarry, sticky stools with pain could instead mean bleeding, so mention any concern to your doctor.' },
      { q: 'How can I absorb iron better?', a: 'Take it with a source of vitamin C and away from tea, coffee, milk and calcium, which reduce absorption.' },
    ],
    related: [['diseases/iron-deficiency-anaemia', 'Iron-deficiency anaemia'], ['blood-tests/ferritin-iron-studies', 'Ferritin / iron studies'], ['diseases/anaemia', 'Anaemia'], ['diseases/pregnancy-care', 'Pregnancy care']],
  },
];
