// Bulk drug library — batch 3. Same class-based model (no specific dose shown;
// dosing deferred to a doctor). Brand lists are common examples and vary by country.

export const DRUG_CLASSES_3 = [
  {
    class: 'Opioid painkiller (strong)',
    desc: 'Opioids relieve moderate-to-severe pain but can cause dependence and slowed breathing, so they are used carefully and usually short-term.',
    uses: ['Severe pain (injury, surgery, cancer)', 'Pain not controlled by paracetamol/NSAIDs', 'Palliative care'],
    sideEffects: ['Constipation', 'Drowsiness and nausea', 'Dependence with prolonged use'],
    precautions: ['Do not drive if drowsy; avoid alcohol', 'Use the lowest dose for the shortest time', 'Do not stop suddenly after regular use (withdrawal)'],
    warnings: ['Slow or shallow breathing, extreme drowsiness (overdose — emergency, needs naloxone)', 'Confusion', 'Severe constipation'],
    faqs: [
      { q: 'Are opioid painkillers addictive?', a: 'They can cause dependence, especially with longer use, so doctors prescribe the smallest effective dose for the shortest time and monitor closely.' },
      { q: 'Why do opioids cause constipation?', a: 'They slow the bowel, so a laxative is often prescribed alongside. Drink fluids and stay active where possible.' },
    ],
    members: [
      { slug: 'morphine', name: 'Morphine', brandsIndia: ['Morcontin', 'Morphine'], brandsWorld: ['MS Contin', 'Kadian'], blurb: 'Morphine is a strong opioid for severe and cancer pain.' },
      { slug: 'fentanyl', name: 'Fentanyl', brandsIndia: ['Durogesic', 'Fent'], brandsWorld: ['Duragesic', 'Actiq'], blurb: 'Fentanyl is a very strong opioid used as patches or injections for severe pain.' },
      { slug: 'codeine', name: 'Codeine', brandsIndia: ['Codeine (in combos)', 'Corex (syrup)'], brandsWorld: ['(codeine/co-codamol brands)'], blurb: 'Codeine is a mild opioid for pain and cough, often combined with paracetamol.' },
      { slug: 'oxycodone', name: 'Oxycodone', brandsIndia: ['Oxycontin'], brandsWorld: ['OxyContin', 'Percocet'], blurb: 'Oxycodone is a strong opioid for moderate-to-severe pain.' },
      { slug: 'buprenorphine', name: 'Buprenorphine', brandsIndia: ['Tidigesic', 'Norphin', 'Addnok'], brandsWorld: ['Butrans', 'Suboxone'], blurb: 'Buprenorphine treats severe pain and is also used in opioid-dependence treatment.' },
      { slug: 'tapentadol', name: 'Tapentadol', brandsIndia: ['Tapal', 'Aspadol', 'Tydol'], brandsWorld: ['Nucynta'], blurb: 'Tapentadol is an opioid-type painkiller for moderate-to-severe pain.' },
    ],
  },
  {
    class: 'Local anaesthetic',
    desc: 'These numb a part of the body for procedures or to relieve local pain.',
    uses: ['Numbing skin before injections or minor procedures', 'Dental and surgical anaesthesia', 'Local pain and itching (topical)'],
    sideEffects: ['Temporary numbness and tingling', 'Local irritation', 'Rarely, dizziness if too much is absorbed'],
    precautions: ['Given by trained staff for injections', 'Do not exceed recommended topical amounts', 'Tell your doctor about heart-rhythm problems'],
    warnings: ['Palpitations, dizziness or fits (rare, from excess absorption)', 'Severe allergic reaction', 'Numbness that does not wear off'],
    faqs: [
      { q: 'How long does local anaesthetic last?', a: 'It depends on the drug and site — typically from about an hour (lidocaine) to several hours (bupivacaine).' },
      { q: 'Is numbing cream safe for children?', a: 'Yes, in the right amount for their size before procedures, but too much over broken skin can be absorbed — follow instructions.' },
    ],
    members: [
      { slug: 'lidocaine', name: 'Lidocaine (Lignocaine)', brandsIndia: ['Xylocaine', 'Lox', 'Prilox (with prilocaine)'], brandsWorld: ['Xylocaine', 'EMLA (combo)'], blurb: 'Lidocaine is the most common local anaesthetic, as injection, gel or spray.' },
      { slug: 'bupivacaine', name: 'Bupivacaine', brandsIndia: ['Sensorcaine', 'Anawin'], brandsWorld: ['Marcaine', 'Sensorcaine'], blurb: 'Bupivacaine is a long-acting local anaesthetic for surgery and epidurals.' },
      { slug: 'benzocaine', name: 'Benzocaine (topical)', brandsIndia: ['Mucopain', 'Dentogel'], brandsWorld: ['Orajel', 'Anbesol'], blurb: 'Benzocaine is a topical numbing agent for mouth ulcers and teething pain.' },
    ],
  },
  {
    class: 'HIV & hepatitis antiviral',
    desc: 'These control HIV or viral hepatitis. They are taken long-term (or as a full course) under specialist care.',
    uses: ['HIV treatment and prevention (PrEP)', 'Chronic hepatitis B', 'Chronic hepatitis C (curative courses)'],
    sideEffects: ['Nausea, headache or tiredness', 'Kidney or bone effects (some)', 'Vivid dreams (some HIV drugs)'],
    precautions: ['Take every dose to prevent resistance', 'Do not stop without specialist advice', 'Many drug interactions — tell every doctor'],
    warnings: ['Yellow eyes or dark urine (liver)', 'Reduced urine or bone pain (kidney/bone effects)', 'Severe rash or allergy'],
    faqs: [
      { q: 'Can hepatitis C be cured?', a: 'Yes — modern direct-acting antivirals (like sofosbuvir combinations) cure most people with a course of a few months.' },
      { q: 'What is PrEP?', a: 'PrEP is HIV pre-exposure prophylaxis — medicines (like tenofovir/emtricitabine) taken by HIV-negative people to greatly reduce the risk of catching HIV.' },
    ],
    members: [
      { slug: 'tenofovir', name: 'Tenofovir', brandsIndia: ['Tenvir', 'Tavin', 'Ricovir'], brandsWorld: ['Viread', 'Vemlidy'], blurb: 'Tenofovir treats HIV and hepatitis B and is used in HIV prevention (PrEP).' },
      { slug: 'lamivudine', name: 'Lamivudine', brandsIndia: ['Lamivir', '3TC'], brandsWorld: ['Epivir'], blurb: 'Lamivudine is an antiviral for HIV and hepatitis B, usually in combination.' },
      { slug: 'dolutegravir', name: 'Dolutegravir', brandsIndia: ['Tivicay', 'DTG', 'TLD (combo)'], brandsWorld: ['Tivicay'], blurb: 'Dolutegravir is a first-line HIV medicine, often in a single combination tablet.' },
      { slug: 'sofosbuvir', name: 'Sofosbuvir', brandsIndia: ['Hepcinat', 'Myhep', 'Sovaldi'], brandsWorld: ['Sovaldi', 'Epclusa (combo)'], blurb: 'Sofosbuvir is a direct-acting antiviral that helps cure hepatitis C.' },
      { slug: 'entecavir', name: 'Entecavir', brandsIndia: ['Entavir', 'X-Vir'], brandsWorld: ['Baraclude'], blurb: 'Entecavir is a long-term antiviral for chronic hepatitis B.' },
      { slug: 'ritonavir', name: 'Ritonavir', brandsIndia: ['Ritomune', 'Ritovir'], brandsWorld: ['Norvir'], blurb: 'Ritonavir is used in HIV treatment and to boost other antivirals.' },
    ],
  },
  {
    class: 'COVID-19 antiviral',
    desc: 'These reduce the severity of COVID-19, working best when started early in high-risk people.',
    uses: ['Early COVID-19 in high-risk people', 'Reducing hospitalisation risk', 'Severe COVID-19 in hospital (some)'],
    sideEffects: ['Altered taste (Paxlovid)', 'Diarrhoea or nausea', 'Headache'],
    precautions: ['Start within the first few days of symptoms', 'Paxlovid has important drug interactions', 'Given on medical advice'],
    warnings: ['Severe allergic reaction', 'Worsening breathlessness (needs hospital care)', 'Symptom rebound in some cases'],
    faqs: [
      { q: 'Who should take COVID antivirals?', a: 'Mainly people at higher risk of severe illness (older age, weak immunity, certain conditions), started early. Most healthy people recover without them.' },
      { q: 'Why does Paxlovid interact with other medicines?', a: 'It contains ritonavir, which changes how the liver clears many drugs, so your doctor checks all your medicines before prescribing it.' },
    ],
    members: [
      { slug: 'molnupiravir', name: 'Molnupiravir', brandsIndia: ['Molnatris', 'Molxvir', 'Movfor'], brandsWorld: ['Lagevrio'], blurb: 'Molnupiravir is an oral antiviral for early COVID-19 in higher-risk adults.' },
      { slug: 'nirmatrelvir-ritonavir', name: 'Nirmatrelvir-Ritonavir (Paxlovid)', brandsIndia: ['Paxista', 'Primovir'], brandsWorld: ['Paxlovid'], blurb: 'Paxlovid is an oral antiviral for early COVID-19; it has many drug interactions.' },
      { slug: 'remdesivir', name: 'Remdesivir', brandsIndia: ['Cipremi', 'Covifor', 'Remdac'], brandsWorld: ['Veklury'], blurb: 'Remdesivir is an intravenous antiviral used for COVID-19 in hospital.' },
      { slug: 'favipiravir', name: 'Favipiravir', brandsIndia: ['FabiFlu', 'Favipir', 'Coviflu'], brandsWorld: ['Avigan'], blurb: 'Favipiravir was used for mild-to-moderate COVID-19 in some countries.' },
    ],
  },
  {
    class: 'Topical antibiotic',
    desc: 'These treat or prevent infection in minor wounds, burns and skin/eye conditions.',
    uses: ['Minor cuts, grazes and wounds', 'Burns (preventing infection)', 'Skin and some eye/ear infections'],
    sideEffects: ['Local irritation or stinging', 'Allergic skin reaction', 'Rarely, sensitisation with repeated use'],
    precautions: ['Clean the area before applying', 'Avoid prolonged use (resistance/sensitisation)', 'Not for large or deep wounds without advice'],
    warnings: ['Spreading redness, pus or fever (worsening infection)', 'Severe allergic rash', 'No improvement in a few days'],
    faqs: [
      { q: 'Should I put antibiotic cream on every cut?', a: 'Most minor cuts just need cleaning and covering. Antibiotic ointment can help dirty or higher-risk wounds, but overuse can cause allergy and resistance.' },
      { q: 'How is silver sulfadiazine used?', a: 'It is applied to burns to prevent infection, under medical guidance for anything more than a minor burn.' },
    ],
    members: [
      { slug: 'neomycin', name: 'Neomycin', brandsIndia: ['Neosporin (combo)', 'Nebasulf'], brandsWorld: ['Neosporin (combo)'], blurb: 'Neomycin is a topical antibiotic for minor skin infections, often in combination.' },
      { slug: 'framycetin', name: 'Framycetin', brandsIndia: ['Soframycin', 'Framy'], brandsWorld: ['Soframycin'], blurb: 'Framycetin is a topical antibiotic cream/gauze for wounds and minor skin infections.' },
      { slug: 'silver-sulfadiazine', name: 'Silver Sulfadiazine', brandsIndia: ['Silverex', 'Burnheal', 'T-Bact SS'], brandsWorld: ['Silvadene', 'Flamazine'], blurb: 'Silver sulfadiazine cream prevents infection in burns.' },
      { slug: 'bacitracin', name: 'Bacitracin', brandsIndia: ['Nebasulf (combo)', 'Bacitracin'], brandsWorld: ['Neosporin (combo)'], blurb: 'Bacitracin is a topical antibiotic for minor skin wounds.' },
      { slug: 'chloramphenicol', name: 'Chloramphenicol', brandsIndia: ['Chloromycetin', 'Paraxin', 'Chlorocol (eye)'], brandsWorld: ['Chloromycetin'], blurb: 'Chloramphenicol is used as eye drops/ointment for bacterial eye infections.' },
    ],
  },
  {
    class: 'Topical antifungal (extra)',
    desc: 'These creams, lotions and lacquers treat fungal infections of the skin and nails.',
    uses: ['Ringworm and skin fungal infections', 'Athlete’s foot and jock itch', 'Nail fungal infections (lacquers)', 'Vaginal thrush (some)'],
    sideEffects: ['Local irritation or burning', 'Redness or peeling', 'Rarely, allergy'],
    precautions: ['Keep the area clean and dry', 'Continue for the full course, even after it looks better', 'Nail infections take months to clear'],
    warnings: ['Severe burning or spreading rash', 'No improvement after the expected time', 'Signs of a bacterial infection on top'],
    faqs: [
      { q: 'Why does ringworm keep coming back?', a: 'It spreads easily and survives in skin folds, clothes and towels. Treat for the full time, keep skin dry, and wash clothes/bedding hot.' },
      { q: 'Do nail-fungus lacquers work?', a: 'They can help mild cases but work slowly over months; more severe nail infections often need oral antifungals.' },
    ],
    members: [
      { slug: 'miconazole', name: 'Miconazole', brandsIndia: ['Daktarin', 'Zole', 'Gynozole'], brandsWorld: ['Daktarin', 'Monistat'], blurb: 'Miconazole is a topical antifungal for skin and vaginal fungal infections.' },
      { slug: 'sertaconazole', name: 'Sertaconazole', brandsIndia: ['Onabet', 'Sertacid'], brandsWorld: ['Ertaczo'], blurb: 'Sertaconazole cream treats ringworm and athlete’s foot.' },
      { slug: 'amorolfine', name: 'Amorolfine (nail lacquer)', brandsIndia: ['Loceryl', 'Amrol'], brandsWorld: ['Loceryl', 'Curanail'], blurb: 'Amorolfine nail lacquer treats mild fungal nail infections.' },
      { slug: 'ciclopirox', name: 'Ciclopirox', brandsIndia: ['Cico', 'Batrafen'], brandsWorld: ['Penlac', 'Loprox'], blurb: 'Ciclopirox treats skin and nail fungal infections.' },
    ],
  },
  {
    class: 'Antihistamine (extra)',
    desc: 'More antihistamines for allergy symptoms, mostly low-drowsiness.',
    uses: ['Allergic rhinitis and hay fever', 'Hives and itching', 'Allergic eye/nose symptoms'],
    sideEffects: ['Mild drowsiness in some', 'Dry mouth', 'Headache'],
    precautions: ['Be careful driving if drowsy', 'Alcohol adds to drowsiness', 'Follow dosing for children'],
    warnings: ['Severe allergic reaction (rare)', 'Marked drowsiness'],
    faqs: [
      { q: 'Which allergy tablet is least drowsy?', a: 'Newer ones like fexofenadine, bilastine, ebastine and rupatadine tend to be the least sedating.' },
      { q: 'Can I switch between antihistamines?', a: 'Yes — if one does not suit you, another may work better with fewer side effects. Ask a pharmacist.' },
    ],
    members: [
      { slug: 'ebastine', name: 'Ebastine', brandsIndia: ['Ebast', 'Ebetos', 'Est945'], brandsWorld: ['Kestine', 'Ebastel'], blurb: 'Ebastine is a low-drowsiness antihistamine for allergies.' },
      { slug: 'rupatadine', name: 'Rupatadine', brandsIndia: ['Rupanex', 'Rupared', 'Alrup'], brandsWorld: ['Rupafin'], blurb: 'Rupatadine treats allergic rhinitis and chronic hives.' },
      { slug: 'ketotifen', name: 'Ketotifen', brandsIndia: ['Ketasma', 'Ketof'], brandsWorld: ['Zaditor (eye)'], blurb: 'Ketotifen is used for allergy prevention and as anti-allergy eye drops.' },
      { slug: 'azelastine', name: 'Azelastine (nasal/eye)', brandsIndia: ['Azep', 'Arzep'], brandsWorld: ['Astelin', 'Optivar'], blurb: 'Azelastine is an antihistamine nasal spray/eye drop for allergy symptoms.' },
    ],
  },
  {
    class: 'Cough & mucolytic (extra)',
    desc: 'These loosen mucus or calm a cough.',
    uses: ['Chesty cough with thick mucus (mucolytics)', 'Dry, irritating cough (suppressants)', 'Bronchitis symptom relief'],
    sideEffects: ['Nausea or tummy upset', 'Drowsiness (some)', 'Headache'],
    precautions: ['Do not suppress a productive (mucus) cough for long', 'Get a lasting cough checked', 'Follow dosing carefully in children'],
    warnings: ['A cough lasting more than 3 weeks or with blood', 'Breathlessness or wheeze', 'High fever with the cough'],
    faqs: [
      { q: 'What is the difference between a mucolytic and a cough suppressant?', a: 'A mucolytic (like bromhexine) thins mucus so a chesty cough clears; a suppressant (like butamirate) calms a dry, tickly cough.' },
      { q: 'Is acetylcysteine only for cough?', a: 'As a mucolytic it loosens mucus, but it is also used in hospital as the antidote for paracetamol overdose.' },
    ],
    members: [
      { slug: 'bromhexine', name: 'Bromhexine', brandsIndia: ['Bromhexine', 'Solvin (combo)'], brandsWorld: ['Bisolvon'], blurb: 'Bromhexine is a mucolytic that thins and clears chest mucus.' },
      { slug: 'acetylcysteine', name: 'Acetylcysteine (NAC)', brandsIndia: ['Mucomix', 'Effimucil', 'NAC'], brandsWorld: ['Mucomyst', 'Acetadote'], blurb: 'Acetylcysteine loosens mucus and is the antidote for paracetamol overdose.' },
      { slug: 'levodropropizine', name: 'Levodropropizine', brandsIndia: ['Levopraid', 'Cough syrup (LDP)'], brandsWorld: ['Levotuss'], blurb: 'Levodropropizine calms a dry cough with little drowsiness.' },
      { slug: 'butamirate', name: 'Butamirate', brandsIndia: ['Butacough', 'Citran'], brandsWorld: ['Sinecod'], blurb: 'Butamirate is a non-opioid cough suppressant for a dry cough.' },
    ],
  },
  {
    class: 'Bronchodilator & inhaled steroid (extra)',
    desc: 'These open the airways or reduce airway inflammation in asthma and COPD.',
    uses: ['Asthma and COPD control or relief', 'Wheeze and breathlessness', 'Preventing airway inflammation (steroids)'],
    sideEffects: ['Tremor or fast heartbeat (relievers)', 'Hoarseness or thrush (inhaled steroids)', 'Headache'],
    precautions: ['Preventers must be used regularly to work', 'Rinse the mouth after inhaled steroids', 'Keep a fast reliever for sudden symptoms'],
    warnings: ['Severe breathlessness or reliever not working (emergency)', 'Palpitations', 'Worsening symptoms despite treatment'],
    faqs: [
      { q: 'What is levosalbutamol?', a: 'It is a refined form of salbutamol used as a reliever, which may cause slightly less tremor and fast heartbeat for some people.' },
      { q: 'Are inhaled steroids safe long-term?', a: 'Yes — at usual doses they are safe and are the mainstay of asthma control. Rinsing the mouth avoids thrush and hoarseness.' },
    ],
    members: [
      { slug: 'levosalbutamol', name: 'Levosalbutamol (Levolin)', brandsIndia: ['Levolin', 'Levosal'], brandsWorld: ['Xopenex'], blurb: 'Levosalbutamol is a reliever inhaler/nebule that opens the airways quickly.' },
      { slug: 'doxofylline', name: 'Doxofylline', brandsIndia: ['Doxobid', 'Synasma', 'Doxiflo'], brandsWorld: ['(doxofylline brands)'], blurb: 'Doxofylline is an oral airway opener for asthma and COPD, gentler than theophylline.' },
      { slug: 'bambuterol', name: 'Bambuterol', brandsIndia: ['Bambudil', 'Betaday'], brandsWorld: ['Bambec'], blurb: 'Bambuterol is a long-acting oral bronchodilator taken once at night.' },
      { slug: 'beclomethasone', name: 'Beclomethasone (inhaler)', brandsIndia: ['Beclate', 'Aerocort (combo)'], brandsWorld: ['Qvar', 'Clenil'], blurb: 'Beclomethasone is an inhaled steroid preventer for asthma.' },
      { slug: 'ciclesonide', name: 'Ciclesonide (inhaler)', brandsIndia: ['Ciclez', 'Osmohale'], brandsWorld: ['Alvesco'], blurb: 'Ciclesonide is an inhaled steroid for asthma with a low thrush risk.' },
    ],
  },
  {
    class: 'Prokinetic & digestive (extra)',
    desc: 'These help the stomach empty, calm the gut, or restore gut balance.',
    uses: ['Bloating, fullness and slow stomach emptying', 'Nausea (prokinetics)', 'Restoring gut flora after antibiotics (probiotics)', 'Acidity relief (bismuth)'],
    sideEffects: ['Mild tummy upset', 'Drowsiness (levosulpiride)', 'Black stools/tongue (bismuth — harmless)'],
    precautions: ['Prokinetics are used short-term', 'Probiotics are generally safe for most people', 'Do not ignore ongoing symptoms without a diagnosis'],
    warnings: ['Uncontrolled movements or stiffness (levosulpiride, rare)', 'Severe or persistent tummy pain', 'Blood in vomit or stools'],
    faqs: [
      { q: 'Do probiotics help after antibiotics?', a: 'They may reduce antibiotic-associated diarrhoea and help restore gut bacteria for some people, and are generally safe.' },
      { q: 'What is itopride used for?', a: 'It helps the stomach empty and relieves bloating, fullness and nausea in indigestion.' },
    ],
    members: [
      { slug: 'itopride', name: 'Itopride', brandsIndia: ['Ganaton', 'Itotry', 'Itoraze'], brandsWorld: ['Ganaton'], blurb: 'Itopride is a prokinetic for bloating, fullness and indigestion.' },
      { slug: 'levosulpiride', name: 'Levosulpiride', brandsIndia: ['Levogastrol', 'Nexpro-LS (combo)'], brandsWorld: ['(levosulpiride brands)'], blurb: 'Levosulpiride relieves nausea and indigestion by helping the stomach empty.' },
      { slug: 'racecadotril', name: 'Racecadotril', brandsIndia: ['Redotil', 'Zedott', 'Enuff'], brandsWorld: ['Hidrasec'], blurb: 'Racecadotril reduces fluid loss in acute diarrhoea, useful alongside ORS in children.' },
      { slug: 'probiotics', name: 'Probiotics', brandsIndia: ['Vizylac', 'Sporlac', 'Enterogermina'], brandsWorld: ['Culturelle', 'Florastor'], blurb: 'Probiotics provide helpful gut bacteria to support digestion and recovery from diarrhoea.' },
      { slug: 'bismuth-subsalicylate', name: 'Bismuth Subsalicylate', brandsIndia: ['Pepto-Bismol', 'Bismuth'], brandsWorld: ['Pepto-Bismol', 'Kaopectate'], blurb: 'Bismuth subsalicylate soothes indigestion, nausea and mild diarrhoea.' },
    ],
  },
  {
    class: 'Blood-pressure medicine (extra)',
    desc: 'These lower blood pressure by additional mechanisms, often used when first-line drugs are not enough.',
    uses: ['High blood pressure (add-on or specific situations)', 'High blood pressure in pregnancy (methyldopa)', 'Heart failure (sacubitril-valsartan)'],
    sideEffects: ['Dizziness or drowsiness', 'Dry mouth (clonidine)', 'Ankle swelling or flushing (some)'],
    precautions: ['Do not stop clonidine suddenly (rebound BP surge)', 'Rise slowly to avoid fainting', 'Monitoring as advised'],
    warnings: ['Severe rebound high BP if clonidine is stopped abruptly', 'Fainting or very low BP', 'Facial/throat swelling (sacubitril-valsartan)'],
    faqs: [
      { q: 'Which BP medicine is safe in pregnancy?', a: 'Methyldopa, labetalol and nifedipine are commonly used in pregnancy. ACE inhibitors and ARBs are avoided.' },
      { q: 'What is sacubitril-valsartan?', a: 'It is a combination medicine that improves outcomes in heart failure, used under specialist guidance.' },
    ],
    members: [
      { slug: 'methyldopa', name: 'Methyldopa', brandsIndia: ['Alphadopa', 'Emdopa'], brandsWorld: ['Aldomet'], blurb: 'Methyldopa is a blood-pressure medicine widely used in pregnancy.' },
      { slug: 'clonidine', name: 'Clonidine', brandsIndia: ['Arkamin', 'Catapres'], brandsWorld: ['Catapres', 'Kapvay'], blurb: 'Clonidine lowers blood pressure and is also used for some other conditions.' },
      { slug: 'prazosin', name: 'Prazosin', brandsIndia: ['Minipress XL', 'Prazopress'], brandsWorld: ['Minipress'], blurb: 'Prazosin is an alpha-blocker for blood pressure and nightmares in PTSD.' },
      { slug: 'hydralazine', name: 'Hydralazine', brandsIndia: ['Nepresol'], brandsWorld: ['Apresoline'], blurb: 'Hydralazine relaxes blood vessels and is used in pregnancy and heart failure.' },
      { slug: 'sacubitril-valsartan', name: 'Sacubitril-Valsartan', brandsIndia: ['Vymada', 'Azmarda'], brandsWorld: ['Entresto'], blurb: 'Sacubitril-valsartan improves survival in heart failure.' },
      { slug: 'minoxidil-oral', name: 'Minoxidil (oral)', brandsIndia: ['Loniten', 'Mintop (topical is separate)'], brandsWorld: ['Loniten'], blurb: 'Oral minoxidil is a strong blood-pressure medicine, and in low doses is used for hair loss.' },
    ],
  },
  {
    class: 'Cholesterol & antiplatelet (extra)',
    desc: 'These further lower cholesterol or prevent clots in high-risk people.',
    uses: ['Lowering cholesterol when statins are not enough', 'Very high triglycerides', 'Preventing clots after heart events'],
    sideEffects: ['Muscle aches or tummy upset', 'Flushing (niacin)', 'Bleeding tendency (antiplatelets)'],
    precautions: ['Used with lifestyle changes and often a statin', 'Tell doctors/dentists about antiplatelets', 'Some are given by injection'],
    warnings: ['Unexplained muscle pain/weakness', 'Unusual bleeding or black stools', 'Severe flushing or itching (niacin)'],
    faqs: [
      { q: 'What if a statin alone does not lower my cholesterol enough?', a: 'Add-ons like ezetimibe, bempedoic acid or injectable PCSK9 inhibitors (evolocumab) can lower it further — your doctor tailors this to your risk.' },
      { q: 'What is icosapent ethyl?', a: 'It is a purified omega-3 that lowers high triglycerides and can reduce cardiovascular risk in selected people.' },
    ],
    members: [
      { slug: 'prasugrel', name: 'Prasugrel', brandsIndia: ['Prasita', 'Prax'], brandsWorld: ['Effient'], blurb: 'Prasugrel is an antiplatelet used with aspirin after stents/heart attack.' },
      { slug: 'bempedoic-acid', name: 'Bempedoic Acid', brandsIndia: ['Bempedoic'], brandsWorld: ['Nexletol', 'Nilemdo'], blurb: 'Bempedoic acid lowers cholesterol, useful for people who cannot tolerate statins.' },
      { slug: 'niacin', name: 'Niacin (Vitamin B3)', brandsIndia: ['Niacinamide', 'Nicotinamide'], brandsWorld: ['Niaspan'], blurb: 'Niacin can raise HDL and lower cholesterol/triglycerides, but flushing limits its use.' },
      { slug: 'evolocumab', name: 'Evolocumab', brandsIndia: ['Repatha'], brandsWorld: ['Repatha'], blurb: 'Evolocumab is an injectable PCSK9 inhibitor for very high cholesterol or high risk.' },
      { slug: 'icosapent-ethyl', name: 'Icosapent Ethyl', brandsIndia: ['Ipent', 'Vascepa'], brandsWorld: ['Vascepa'], blurb: 'Icosapent ethyl is a purified omega-3 for high triglycerides and cardiovascular risk.' },
    ],
  },
  {
    class: 'Diuretic (extra)',
    desc: 'These specialised diuretics are used for eye pressure, brain swelling or specific salt problems.',
    uses: ['Glaucoma and altitude sickness (acetazolamide)', 'Brain swelling and acute glaucoma (mannitol)', 'Potassium-sparing diuresis (amiloride)'],
    sideEffects: ['Tingling and altered taste (acetazolamide)', 'Passing more urine', 'Salt imbalances'],
    precautions: ['Blood salts are monitored', 'Mannitol is given in hospital by drip', 'Stay hydrated appropriately'],
    warnings: ['Severe dizziness, cramps or palpitations (salt imbalance)', 'Confusion', 'Very high or low potassium'],
    faqs: [
      { q: 'Why is acetazolamide used for altitude sickness?', a: 'It helps the body adjust to low oxygen at altitude, reducing symptoms — taken before and during ascent on medical advice.' },
      { q: 'What is mannitol used for?', a: 'It is an emergency diuretic given by drip to reduce pressure in the brain or eye.' },
    ],
    members: [
      { slug: 'acetazolamide', name: 'Acetazolamide', brandsIndia: ['Diamox', 'Iopar'], brandsWorld: ['Diamox'], blurb: 'Acetazolamide lowers eye and brain pressure and helps altitude sickness.' },
      { slug: 'mannitol', name: 'Mannitol', brandsIndia: ['Mannitol IV'], brandsWorld: ['Osmitrol'], blurb: 'Mannitol is an intravenous osmotic diuretic for raised brain or eye pressure.' },
      { slug: 'amiloride', name: 'Amiloride', brandsIndia: ['Biduret (combo)'], brandsWorld: ['Midamor'], blurb: 'Amiloride is a potassium-sparing diuretic, usually combined with another water tablet.' },
    ],
  },
  {
    class: 'Oral diabetes medicine (extra)',
    desc: 'More tablets that control blood sugar in type 2 diabetes by different routes.',
    uses: ['Type 2 diabetes', 'After-meal sugar spikes (glinides)', 'Combination therapy'],
    sideEffects: ['Low sugar (glinides)', 'Urinary/genital infections (SGLT2)', 'Weight change'],
    precautions: ['Take glinides with meals', 'Kidney function is checked', 'Report frequent infections or low sugar'],
    warnings: ['Low blood sugar symptoms (glinides)', 'Genital/urinary infection or dehydration (SGLT2)', 'Rare serious ketoacidosis with SGLT2 (unusual symptoms — seek care)'],
    faqs: [
      { q: 'What are “gliptins” and “gliflozins”?', a: 'Gliptins (DPP-4 inhibitors, like linagliptin) gently improve insulin response; gliflozins (SGLT2 inhibitors, like canagliflozin) remove sugar via the urine and help the heart/kidneys.' },
      { q: 'Which diabetes tablet suits kidney disease?', a: 'Linagliptin needs no dose change in kidney disease, and some SGLT2 inhibitors protect the kidneys — your doctor chooses based on your kidney function.' },
    ],
    members: [
      { slug: 'repaglinide', name: 'Repaglinide', brandsIndia: ['Eurepa', 'Rapilin'], brandsWorld: ['Prandin', 'NovoNorm'], blurb: 'Repaglinide is a fast, short-acting sugar-lowering tablet taken with meals.' },
      { slug: 'canagliflozin', name: 'Canagliflozin', brandsIndia: ['Invokana', 'Sugaflow'], brandsWorld: ['Invokana'], blurb: 'Canagliflozin is an SGLT2 inhibitor that lowers sugar and protects the kidneys.' },
      { slug: 'linagliptin', name: 'Linagliptin', brandsIndia: ['Trajenta', 'Ondero', 'Lina'], brandsWorld: ['Tradjenta'], blurb: 'Linagliptin is a DPP-4 inhibitor that needs no dose change in kidney disease.' },
      { slug: 'saxagliptin', name: 'Saxagliptin', brandsIndia: ['Onglyza'], brandsWorld: ['Onglyza'], blurb: 'Saxagliptin is a DPP-4 inhibitor for type 2 diabetes.' },
      { slug: 'alogliptin', name: 'Alogliptin', brandsIndia: ['Nesina'], brandsWorld: ['Nesina'], blurb: 'Alogliptin is a DPP-4 inhibitor for type 2 diabetes.' },
    ],
  },
  {
    class: 'Anti-nausea (chemotherapy)',
    desc: 'These prevent the strong nausea and vomiting caused by chemotherapy or surgery.',
    uses: ['Preventing chemotherapy nausea/vomiting', 'Preventing nausea after surgery', 'Radiotherapy-related nausea'],
    sideEffects: ['Constipation', 'Headache', 'Tiredness'],
    precautions: ['Given as part of a planned anti-sickness regimen', 'Tell your doctor about heart-rhythm problems', 'Timing around chemo matters'],
    warnings: ['Palpitations or fainting (heart-rhythm effect)', 'Severe constipation', 'Allergic reaction'],
    faqs: [
      { q: 'Why are several anti-sickness drugs used together for chemo?', a: 'Chemotherapy triggers nausea by different pathways, so combining medicines (e.g. an “setron”, aprepitant and a steroid) controls it far better.' },
      { q: 'How is aprepitant different?', a: 'It blocks a specific vomiting signal (NK-1) and is added to prevent the delayed nausea some chemotherapies cause.' },
    ],
    members: [
      { slug: 'aprepitant', name: 'Aprepitant', brandsIndia: ['Aprecap', 'Emend'], brandsWorld: ['Emend'], blurb: 'Aprepitant prevents delayed chemotherapy nausea and vomiting.' },
      { slug: 'granisetron', name: 'Granisetron', brandsIndia: ['Graniset', 'Emigran'], brandsWorld: ['Kytril', 'Sancuso'], blurb: 'Granisetron prevents nausea/vomiting from chemotherapy and surgery.' },
      { slug: 'palonosetron', name: 'Palonosetron', brandsIndia: ['Palnoz', 'Palosure'], brandsWorld: ['Aloxi'], blurb: 'Palonosetron is a long-acting anti-sickness medicine for chemotherapy.' },
    ],
  },
  {
    class: 'Antidepressant (extra)',
    desc: 'More antidepressants and related mood medicines, each suited to different situations.',
    uses: ['Depression', 'Anxiety and OCD', 'Nerve pain, sleep or smoking cessation (some)'],
    sideEffects: ['Dry mouth, drowsiness or insomnia', 'Nausea early on', 'Weight or appetite changes'],
    precautions: ['Full effect takes weeks — do not stop early', 'Do not stop suddenly (taper)', 'Tell your doctor about all medicines (interactions)'],
    warnings: ['Worsening mood or thoughts of self-harm, especially early — seek help urgently', 'Fast heartbeat or fits (overdose risk with tricyclics)', 'Agitation, fever, confusion (serotonin syndrome)'],
    faqs: [
      { q: 'Why are there so many antidepressants?', a: 'People respond differently, and each has its own side-effect and interaction profile. If one does not suit you, another often does.' },
      { q: 'What is bupropion used for?', a: 'It treats depression and also helps people stop smoking, and is less likely to cause sexual side effects or weight gain.' },
    ],
    members: [
      { slug: 'bupropion', name: 'Bupropion', brandsIndia: ['Bupron SR', 'Smoquit'], brandsWorld: ['Wellbutrin', 'Zyban'], blurb: 'Bupropion treats depression and aids smoking cessation.' },
      { slug: 'clomipramine', name: 'Clomipramine', brandsIndia: ['Clonil', 'Clomfranil'], brandsWorld: ['Anafranil'], blurb: 'Clomipramine is a tricyclic used especially for OCD and depression.' },
      { slug: 'imipramine', name: 'Imipramine', brandsIndia: ['Depsonil', 'Antidep'], brandsWorld: ['Tofranil'], blurb: 'Imipramine is a tricyclic antidepressant also used for bedwetting and nerve pain.' },
      { slug: 'trazodone', name: 'Trazodone', brandsIndia: ['Trazonil', 'Oleptro'], brandsWorld: ['Desyrel', 'Oleptro'], blurb: 'Trazodone treats depression and is often used at low doses for sleep.' },
      { slug: 'vortioxetine', name: 'Vortioxetine', brandsIndia: ['Vortifar', 'Estiva'], brandsWorld: ['Trintellix', 'Brintellix'], blurb: 'Vortioxetine is a newer antidepressant that may also help concentration.' },
      { slug: 'tianeptine', name: 'Tianeptine', brandsIndia: ['Tianeurax', 'Tianept'], brandsWorld: ['Stablon', 'Coaxil'], blurb: 'Tianeptine is an antidepressant used in some countries; misuse can cause dependence.' },
    ],
  },
  {
    class: 'Antipsychotic (extra)',
    desc: 'More medicines for psychosis, severe agitation and treatment-resistant mental illness.',
    uses: ['Schizophrenia and psychosis', 'Severe agitation or mania', 'Treatment-resistant illness (clozapine)'],
    sideEffects: ['Drowsiness', 'Movement stiffness or restlessness', 'Weight/metabolic changes'],
    precautions: ['Regular monitoring (clozapine needs regular blood counts)', 'Do not stop suddenly', 'Caution in the elderly with dementia'],
    warnings: ['High fever with stiffness and confusion (rare, serious — urgent)', 'Fever/sore throat on clozapine (blood-count effect — urgent)', 'Uncontrolled movements'],
    faqs: [
      { q: 'Why does clozapine need regular blood tests?', a: 'It can rarely lower infection-fighting white cells, so blood counts are checked regularly. It is reserved for illness that has not responded to other drugs.' },
      { q: 'Is haloperidol still used?', a: 'Yes — it is an effective older antipsychotic, useful for severe agitation and psychosis, though it can cause movement side effects.' },
    ],
    members: [
      { slug: 'haloperidol', name: 'Haloperidol', brandsIndia: ['Serenace', 'Haloperidol'], brandsWorld: ['Haldol'], blurb: 'Haloperidol is an older antipsychotic for psychosis and severe agitation.' },
      { slug: 'clozapine', name: 'Clozapine', brandsIndia: ['Sizopin', 'Lozapin', 'Clozamed'], brandsWorld: ['Clozaril', 'Versacloz'], blurb: 'Clozapine is used for treatment-resistant schizophrenia, with regular blood monitoring.' },
      { slug: 'amisulpride', name: 'Amisulpride', brandsIndia: ['Amisulide', 'Soltus'], brandsWorld: ['Solian'], blurb: 'Amisulpride treats schizophrenia and is used at low dose for persistent nausea.' },
      { slug: 'lurasidone', name: 'Lurasidone', brandsIndia: ['Lurace', 'Emsidon'], brandsWorld: ['Latuda'], blurb: 'Lurasidone treats schizophrenia and bipolar depression with less weight gain.' },
    ],
  },
  {
    class: 'Anti-epileptic (extra)',
    desc: 'More seizure medicines, some also used for nerve pain, migraine or mood.',
    uses: ['Epilepsy and seizure control', 'Nerve pain or migraine prevention (some)', 'Mood stabilising (some)'],
    sideEffects: ['Drowsiness or dizziness', 'Weight change (topiramate can reduce weight)', 'Tingling or word-finding trouble (topiramate)'],
    precautions: ['Do not stop suddenly (seizure risk)', 'Some interact with contraception and other drugs', 'Stay hydrated (kidney stones with topiramate)'],
    warnings: ['A serious skin rash (stop and seek care urgently)', 'Thoughts of self-harm or marked mood change', 'Confusion or severe drowsiness'],
    faqs: [
      { q: 'Is topiramate only for epilepsy?', a: 'No — it also prevents migraines and is sometimes used for weight, though side effects like tingling and word-finding trouble can limit it.' },
      { q: 'Why is phenobarbital used less now?', a: 'It is effective and cheap but very sedating, so newer, better-tolerated medicines are usually preferred except in some settings.' },
    ],
    members: [
      { slug: 'oxcarbazepine', name: 'Oxcarbazepine', brandsIndia: ['Oxetol', 'Trleptal', 'Oxcarb'], brandsWorld: ['Trileptal', 'Oxtellar'], blurb: 'Oxcarbazepine treats epilepsy and nerve pain, related to carbamazepine.' },
      { slug: 'topiramate', name: 'Topiramate', brandsIndia: ['Topamac', 'Toprnew'], brandsWorld: ['Topamax'], blurb: 'Topiramate treats epilepsy and prevents migraines.' },
      { slug: 'zonisamide', name: 'Zonisamide', brandsIndia: ['Zonisep', 'Zonicare'], brandsWorld: ['Zonegran'], blurb: 'Zonisamide is an add-on epilepsy medicine.' },
      { slug: 'phenobarbital', name: 'Phenobarbital (Phenobarbitone)', brandsIndia: ['Gardenal', 'Phenobarb'], brandsWorld: ['Luminal'], blurb: 'Phenobarbital is an older, effective but sedating epilepsy medicine.' },
    ],
  },
  {
    class: 'ADHD medicine',
    desc: 'These improve attention and reduce hyperactivity/impulsivity in ADHD.',
    uses: ['Attention-deficit hyperactivity disorder (ADHD)', 'Improving focus and impulse control'],
    sideEffects: ['Reduced appetite', 'Trouble sleeping', 'Faster heartbeat or headache'],
    precautions: ['Heart and growth are monitored in children', 'Stimulants are controlled medicines', 'Take earlier in the day to protect sleep'],
    warnings: ['Chest pain, fainting or palpitations', 'Marked mood changes or agitation', 'Very poor appetite or weight loss'],
    faqs: [
      { q: 'Are ADHD medicines safe for children?', a: 'When prescribed and monitored, they are effective and generally safe. Heart, growth, sleep and appetite are checked over time.' },
      { q: 'What is the difference between methylphenidate and atomoxetine?', a: 'Methylphenidate is a stimulant that acts quickly; atomoxetine is a non-stimulant taken daily that builds up over weeks.' },
    ],
    members: [
      { slug: 'methylphenidate', name: 'Methylphenidate', brandsIndia: ['Inspiral', 'Addwize', 'Retalin'], brandsWorld: ['Ritalin', 'Concerta'], blurb: 'Methylphenidate is a stimulant that improves focus in ADHD.' },
      { slug: 'atomoxetine', name: 'Atomoxetine', brandsIndia: ['Attentrol', 'Axepta', 'Tomoxetin'], brandsWorld: ['Strattera'], blurb: 'Atomoxetine is a non-stimulant daily medicine for ADHD.' },
    ],
  },
  {
    class: 'Sexual health (extra)',
    desc: 'These treat erectile dysfunction or premature ejaculation.',
    uses: ['Erectile dysfunction', 'Premature ejaculation (dapoxetine)'],
    sideEffects: ['Headache and flushing', 'Nasal congestion', 'Nausea or dizziness'],
    precautions: ['Never combine ED drugs with nitrate heart medicines', 'Caution with heart disease', 'Alcohol reduces effectiveness'],
    warnings: ['Chest pain during activity', 'An erection lasting over 4 hours (emergency)', 'Sudden vision or hearing changes'],
    faqs: [
      { q: 'Which ED medicine works fastest / longest?', a: 'Avanafil acts fast; tadalafil lasts the longest (up to 36 hours). The best choice depends on your needs and health.' },
      { q: 'What is dapoxetine?', a: 'It is a short-acting SSRI taken before sex to delay ejaculation in premature ejaculation.' },
    ],
    members: [
      { slug: 'vardenafil', name: 'Vardenafil', brandsIndia: ['Vilitra', 'Zhewitra'], brandsWorld: ['Levitra', 'Staxyn'], blurb: 'Vardenafil is a PDE5 inhibitor for erectile dysfunction.' },
      { slug: 'avanafil', name: 'Avanafil', brandsIndia: ['Avana', 'Avanafil'], brandsWorld: ['Stendra', 'Spedra'], blurb: 'Avanafil is a fast-acting erectile-dysfunction medicine.' },
      { slug: 'dapoxetine', name: 'Dapoxetine', brandsIndia: ['Duralast', 'Sustinex', 'Everlast'], brandsWorld: ['Priligy'], blurb: 'Dapoxetine is taken before sex to treat premature ejaculation.' },
    ],
  },
  {
    class: 'Electrolyte & mineral',
    desc: 'These correct salt or mineral imbalances in the body.',
    uses: ['Low potassium, sodium or calcium', 'Acid balance problems (bicarbonate)', 'Preventing cramps and imbalances'],
    sideEffects: ['Tummy upset (oral potassium)', 'Bloating', 'Too much can cause the opposite imbalance'],
    precautions: ['Blood levels are monitored', 'Do not self-dose potassium (dangerous if high)', 'Given carefully in kidney disease'],
    warnings: ['Palpitations, muscle weakness or numbness (severe imbalance)', 'Confusion', 'Very high potassium can affect the heart'],
    faqs: [
      { q: 'Can I take potassium supplements on my own?', a: 'No — too much potassium is dangerous for the heart. It is only taken with a doctor’s advice and monitoring.' },
      { q: 'What is sodium bicarbonate used for?', a: 'It treats acid build-up in the body and some kidney conditions, and neutralises stomach acid short-term.' },
    ],
    members: [
      { slug: 'potassium-chloride', name: 'Potassium Chloride', brandsIndia: ['KCl', 'Potklor', 'Pot-Chlor'], brandsWorld: ['K-Dur', 'Klor-Con'], blurb: 'Potassium chloride corrects low potassium, under monitoring.' },
      { slug: 'sodium-bicarbonate', name: 'Sodium Bicarbonate', brandsIndia: ['Sodamint', 'Nodosis'], brandsWorld: ['(sodium bicarb brands)'], blurb: 'Sodium bicarbonate treats acid build-up and some kidney conditions.' },
      { slug: 'calcium-gluconate', name: 'Calcium Gluconate', brandsIndia: ['Calcium Gluconate IV'], brandsWorld: ['(calcium gluconate brands)'], blurb: 'Calcium gluconate is an injection for dangerously low calcium or high potassium.' },
    ],
  },
  {
    class: 'Antidote & chelation',
    desc: 'These reverse poisoning, correct overloads or restore clotting.',
    uses: ['Reversing certain drug effects or poisons', 'Removing excess iron (chelation)', 'Restoring vitamin K / clotting'],
    sideEffects: ['Vary by drug', 'Injection reactions', 'Tummy upset'],
    precautions: ['Given under medical supervision', 'Timing is critical in poisoning', 'Regular monitoring with chelation'],
    warnings: ['Any poisoning is an emergency — seek urgent care', 'Allergic reactions', 'Bleeding or clotting problems (with vitamin K use)'],
    faqs: [
      { q: 'What is vitamin K used for?', a: 'It helps blood clot and is used to reverse over-thinning from warfarin or to treat vitamin-K deficiency (newborns are given it routinely).' },
      { q: 'What does iron chelation do?', a: 'Medicines like deferasirox remove excess iron that builds up from repeated blood transfusions, protecting the heart and liver.' },
    ],
    members: [
      { slug: 'vitamin-k', name: 'Vitamin K (Phytonadione)', brandsIndia: ['Kapvit', 'Vitamin K1'], brandsWorld: ['Mephyton', 'Konakion'], blurb: 'Vitamin K supports clotting and reverses over-thinning from warfarin.' },
      { slug: 'deferasirox', name: 'Deferasirox', brandsIndia: ['Asunra', 'Desirox', 'Defrijet'], brandsWorld: ['Exjade', 'Jadenu'], blurb: 'Deferasirox removes excess iron from repeated blood transfusions.' },
      { slug: 'pralidoxime', name: 'Pralidoxime (with atropine)', brandsIndia: ['Pam', '2-PAM'], brandsWorld: ['Protopam'], blurb: 'Pralidoxime, with atropine, treats poisoning by organophosphate pesticides.' },
    ],
  },
  {
    class: 'Biologic / immunomodulator',
    desc: 'These targeted injectable medicines treat severe autoimmune and allergic diseases by blocking specific immune signals.',
    uses: ['Severe rheumatoid, psoriatic or other arthritis', 'Severe psoriasis and inflammatory bowel disease', 'Severe asthma or hives (some)', 'Certain cancers (rituximab)'],
    sideEffects: ['Injection/infusion reactions', 'Increased infection risk', 'Headache'],
    precautions: ['Screening for TB/hepatitis before starting', 'Avoid live vaccines; report infections early', 'Given under specialist care'],
    warnings: ['Fever or infection that will not settle', 'Breathlessness or a severe reaction during infusion', 'Reactivation of TB or hepatitis'],
    faqs: [
      { q: 'How are biologics different from tablets?', a: 'They are large, targeted proteins given by injection/infusion that block specific immune signals, used when standard medicines have not worked.' },
      { q: 'Why is TB screening needed first?', a: 'Biologics can reactivate hidden (latent) TB or hepatitis, so these are checked and treated before starting.' },
    ],
    members: [
      { slug: 'adalimumab', name: 'Adalimumab', brandsIndia: ['Exemptia', 'Adfrar', 'Humira'], brandsWorld: ['Humira'], blurb: 'Adalimumab (an anti-TNF) treats rheumatoid arthritis, psoriasis and IBD.' },
      { slug: 'etanercept', name: 'Etanercept', brandsIndia: ['Etacept', 'Intacept'], brandsWorld: ['Enbrel'], blurb: 'Etanercept (an anti-TNF) treats rheumatoid and psoriatic arthritis and psoriasis.' },
      { slug: 'rituximab', name: 'Rituximab', brandsIndia: ['Reditux', 'Mabtas', 'Ristova'], brandsWorld: ['Rituxan', 'MabThera'], blurb: 'Rituximab treats certain lymphomas and severe autoimmune diseases.' },
      { slug: 'omalizumab', name: 'Omalizumab', brandsIndia: ['Xolair'], brandsWorld: ['Xolair'], blurb: 'Omalizumab treats severe allergic asthma and chronic hives.' },
    ],
  },
  {
    class: 'Smoking cessation & weight',
    desc: 'These help people stop smoking or manage weight.',
    uses: ['Quitting smoking (cravings and withdrawal)', 'Weight management with diet and exercise'],
    sideEffects: ['Nausea (varenicline, phentermine)', 'Vivid dreams or mood changes (varenicline)', 'Fast heartbeat or insomnia (phentermine)'],
    precautions: ['Combine with support/counselling for best results', 'Phentermine is short-term only', 'Report mood changes on varenicline'],
    warnings: ['Marked mood change or thoughts of self-harm (varenicline)', 'Palpitations or high blood pressure (phentermine)', 'Chest pain'],
    faqs: [
      { q: 'What is the most effective way to quit smoking?', a: 'Medication (nicotine replacement, varenicline or bupropion) plus behavioural support works far better than willpower alone.' },
      { q: 'Are weight-loss tablets a substitute for lifestyle?', a: 'No — they support, not replace, a healthier diet and activity, and are used under medical guidance.' },
    ],
    members: [
      { slug: 'varenicline', name: 'Varenicline', brandsIndia: ['Champix'], brandsWorld: ['Chantix', 'Champix'], blurb: 'Varenicline reduces cravings and the pleasure of smoking to help you quit.' },
      { slug: 'nicotine-replacement', name: 'Nicotine Replacement (NRT)', brandsIndia: ['Nicotex', 'Kwiknic', '2Baconil'], brandsWorld: ['Nicorette', 'NicoDerm'], blurb: 'Nicotine gum, patches or lozenges ease withdrawal while quitting smoking.' },
      { slug: 'phentermine', name: 'Phentermine', brandsIndia: ['(restricted)'], brandsWorld: ['Adipex-P', 'Lomaira'], blurb: 'Phentermine is a short-term appetite suppressant for weight loss under supervision.' },
    ],
  },
  {
    class: 'Haematinic (injectable)',
    desc: 'These build blood in severe anaemia or kidney disease, given by injection.',
    uses: ['Anaemia of chronic kidney disease (erythropoietin)', 'Severe iron deficiency when tablets are not enough (IV iron)', 'Anaemia in cancer or after surgery'],
    sideEffects: ['Injection reactions', 'Raised blood pressure (erythropoietin)', 'Temporary taste change (IV iron)'],
    precautions: ['Iron stores and blood counts are monitored', 'Blood pressure is checked (erythropoietin)', 'Given under medical supervision'],
    warnings: ['Severe allergic/infusion reaction', 'Very high blood pressure or headache', 'Clotting problems (erythropoietin, if overused)'],
    faqs: [
      { q: 'Why would I need iron by injection?', a: 'When iron tablets are not tolerated or absorbed, or iron is very low and needed quickly, IV iron restores stores faster.' },
      { q: 'What does erythropoietin do?', a: 'It signals the bone marrow to make more red cells, treating the anaemia common in advanced kidney disease.' },
    ],
    members: [
      { slug: 'erythropoietin', name: 'Erythropoietin (EPO)', brandsIndia: ['Eprex', 'Wepox', 'Vintor'], brandsWorld: ['Epogen', 'Procrit'], blurb: 'Erythropoietin treats anaemia in chronic kidney disease and some cancers.' },
      { slug: 'iron-sucrose', name: 'Iron Sucrose (IV iron)', brandsIndia: ['Orofer S', 'Encicarb', 'Ferisome'], brandsWorld: ['Venofer'], blurb: 'Iron sucrose is intravenous iron for severe iron-deficiency anaemia.' },
    ],
  },
  {
    class: 'Anti-anginal (heart, extra)',
    desc: 'These improve blood or energy supply to the heart to reduce angina.',
    uses: ['Angina (chest pain) prevention', 'Add-on when other anti-anginals are not enough'],
    sideEffects: ['Headache', 'Dizziness', 'Flushing (nicorandil)'],
    precautions: ['Not for a sudden attack (use a fast nitrate)', 'Do not stop suddenly', 'Report mouth or gut ulcers (nicorandil)'],
    warnings: ['Worsening or rest chest pain (possible heart attack — emergency)', 'Persistent mouth, anal or skin ulcers (nicorandil)', 'Fainting'],
    faqs: [
      { q: 'How is ranolazine different from other angina drugs?', a: 'It reduces angina without much effect on heart rate or blood pressure, so it is useful as an add-on.' },
      { q: 'What are nicorandil ulcers?', a: 'Nicorandil can rarely cause painful, persistent ulcers of the mouth, gut or skin — report these, as the drug may need stopping.' },
    ],
    members: [
      { slug: 'ranolazine', name: 'Ranolazine', brandsIndia: ['Ranozex', 'Cardilong'], brandsWorld: ['Ranexa'], blurb: 'Ranolazine prevents angina without much effect on heart rate or blood pressure.' },
      { slug: 'nicorandil', name: 'Nicorandil', brandsIndia: ['Nikoran', 'Korandil'], brandsWorld: ['Ikorel'], blurb: 'Nicorandil widens blood vessels to prevent angina.' },
      { slug: 'trimetazidine', name: 'Trimetazidine', brandsIndia: ['Flavedon', 'Metagard'], brandsWorld: ['Vastarel'], blurb: 'Trimetazidine is an add-on that helps the heart use energy more efficiently in angina.' },
    ],
  },
  {
    class: 'Joint & osteoarthritis supplement',
    desc: 'These support joint comfort in osteoarthritis; evidence is modest and they complement, not replace, core care.',
    uses: ['Osteoarthritis joint discomfort', 'Supporting cartilage/joint health', 'Knee osteoarthritis (injections)'],
    sideEffects: ['Mild tummy upset', 'Diarrhoea (diacerein)', 'Local reaction (injections)'],
    precautions: ['Use alongside exercise and weight control', 'Glucosamine may affect some shellfish allergies', 'Manage expectations — effects are modest'],
    warnings: ['Severe or persistent diarrhoea (diacerein)', 'Marked joint swelling, redness or fever (see a doctor)', 'Allergic reaction'],
    faqs: [
      { q: 'Do glucosamine and joint supplements really work?', a: 'Evidence is mixed and any benefit is usually modest. They are safe for most people to try, but exercise, weight control and proper treatment matter more.' },
      { q: 'What are knee gel (hyaluronic acid) injections?', a: 'They add lubricating fluid to an arthritic knee and may ease pain for some months in selected patients.' },
    ],
    members: [
      { slug: 'glucosamine', name: 'Glucosamine (with Chondroitin)', brandsIndia: ['Glucosamine', 'Rejoint', 'Cartigen'], brandsWorld: ['Osteo Bi-Flex', 'Move Free'], blurb: 'Glucosamine, often with chondroitin, is used for osteoarthritis joint comfort.' },
      { slug: 'diacerein', name: 'Diacerein', brandsIndia: ['Dycerin', 'Artidert', 'Diacerein'], brandsWorld: ['(diacerein brands)'], blurb: 'Diacerein is used for osteoarthritis; diarrhoea is a common side effect.' },
      { slug: 'hyaluronic-acid-injection', name: 'Hyaluronic Acid (knee injection)', brandsIndia: ['Synovial', 'Hyalgan', 'OSTENIL'], brandsWorld: ['Synvisc', 'Euflexxa'], blurb: 'Hyaluronic acid injections lubricate an arthritic knee joint.' },
    ],
  },
  {
    class: 'Digestive enzyme',
    desc: 'These replace enzymes to help digest food when the body lacks them.',
    uses: ['Poor fat/food digestion (pancreatic insufficiency)', 'Bloating and indigestion', 'Lactose intolerance (lactase)'],
    sideEffects: ['Tummy upset', 'Constipation or diarrhoea', 'Rarely, mouth irritation'],
    precautions: ['Take enzyme capsules with meals', 'Do not crush enteric-coated pancreatin', 'Match dose to meal size (pancreatin)'],
    warnings: ['Severe abdominal pain', 'Allergic reaction', 'No improvement in digestion despite use'],
    faqs: [
      { q: 'Who needs pancreatic enzymes?', a: 'People whose pancreas does not make enough enzymes (e.g. chronic pancreatitis, cystic fibrosis, after pancreas surgery) take them with meals to digest food.' },
      { q: 'What is lactase for?', a: 'It helps people with lactose intolerance digest dairy, reducing bloating, wind and diarrhoea.' },
    ],
    members: [
      { slug: 'pancreatin', name: 'Pancreatin (Pancreatic Enzymes)', brandsIndia: ['Panlipase', 'Digeplex', 'Creon'], brandsWorld: ['Creon', 'Zenpep'], blurb: 'Pancreatin replaces digestive enzymes when the pancreas makes too few.' },
      { slug: 'lactase', name: 'Lactase', brandsIndia: ['Lactase drops', 'Aptamil (dietary)'], brandsWorld: ['Lactaid'], blurb: 'Lactase helps people with lactose intolerance digest dairy.' },
    ],
  },
  {
    class: 'Peripheral vascular medicine',
    desc: 'These improve blood flow in the legs in peripheral artery disease and related conditions.',
    uses: ['Leg pain on walking from poor circulation (claudication)', 'Improving walking distance', 'Some circulation-related conditions'],
    sideEffects: ['Headache', 'Palpitations (cilostazol)', 'Tummy upset'],
    precautions: ['Cilostazol is avoided in heart failure', 'Combine with stopping smoking and exercise', 'Report palpitations'],
    warnings: ['Chest pain or palpitations', 'Breathlessness or swelling (heart failure)', 'Signs of bleeding'],
    faqs: [
      { q: 'What helps leg pain from poor circulation?', a: 'Stopping smoking, supervised walking exercise, and managing cholesterol/BP are key; medicines like cilostazol can improve walking distance for some.' },
      { q: 'Is cilostazol safe for everyone?', a: 'No — it must be avoided in heart failure and used cautiously with certain heart conditions, so a doctor assesses suitability.' },
    ],
    members: [
      { slug: 'cilostazol', name: 'Cilostazol', brandsIndia: ['Cilodac', 'Cilostar', 'Pletoz'], brandsWorld: ['Pletal'], blurb: 'Cilostazol improves walking distance in peripheral artery disease.' },
      { slug: 'pentoxifylline', name: 'Pentoxifylline', brandsIndia: ['Trental', 'Flexital', 'Ptx'], brandsWorld: ['Trental', 'Pentoxil'], blurb: 'Pentoxifylline improves blood flow in circulation problems of the legs.' },
    ],
  },
];
