// Senior/elderly health Q&A cluster for MedDroid. Practical, respectful,
// caregiver-aware. Full page objects (same shape gen-landing's page() consumes).
// Educational only, not a diagnosis. Elderly-specific safety: falls, delirium,
// medication interactions, dehydration.

export const ELDERLY_QA = [
  {
    slug: 'elderly-health/high-blood-pressure-in-elderly',
    name: 'High Blood Pressure in Elderly',
    title: 'High Blood Pressure in the Elderly: Care Tips | MedDroid',
    desc: 'Managing high blood pressure in older adults — target readings, avoiding dizziness and falls from over-treatment, and lifestyle tips. Not a diagnosis.',
    h1: 'High blood pressure in the elderly',
    lede: 'High blood pressure is very common with age and still worth treating to prevent stroke and heart disease. But in older adults the aim is careful control — avoiding readings so low they cause dizziness and falls.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about BP in elderly',
    featTitle: 'What matters',
    features: [
      'Treatment still lowers stroke and heart-attack risk in older age',
      'Targets may be a little less strict than in younger adults',
      'Rise slowly from sitting/lying to avoid dizziness (postural drop)',
      'Low-salt diet, activity and taking medicines regularly',
      'Home BP monitoring helps track control',
    ],
    warnings: [
      'A reading of 180/120 or higher, or symptoms — urgent',
      'Dizziness, unsteadiness or falls (BP may be dropping too low — review)',
      'Do not stop BP medicine suddenly',
      'Sudden weakness, slurred speech or face droop (stroke — emergency)',
    ],
    noteTitle: 'Control it — but avoid over-treating.',
    note: 'In older adults, over-lowering blood pressure can cause dizziness and falls, so treatment is individualised. Never stop BP medicine on your own. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is a good blood pressure for the elderly?', a: 'Targets are individualised and may be slightly less strict than for younger adults, to avoid dizziness and falls. Your doctor sets the right target for you.' },
      { q: 'Why does my elderly parent feel dizzy on BP medicine?', a: 'Blood pressure may be dropping too low, especially on standing (postural drop), which raises fall risk. Report it — the dose may need adjusting.' },
      { q: 'Should older people still take BP medicine?', a: 'Yes — treating high blood pressure still reduces strokes and heart attacks in older age, but the balance is managed carefully to avoid side effects.' },
    ],
    related: [['diseases/hypertension', 'Hypertension'], ['medicines/amlodipine', 'Amlodipine'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['elderly-health/preventing-falls-in-elderly', 'Preventing falls']],
  },
  {
    slug: 'elderly-health/diabetes-care-in-elderly',
    name: 'Diabetes Care in Elderly',
    title: 'Diabetes Care in the Elderly: Avoiding Lows | MedDroid',
    desc: 'Managing diabetes in older adults — sensible sugar targets, avoiding dangerous low sugars, diet, and foot care. Not a diagnosis.',
    h1: 'Diabetes care in the elderly',
    lede: 'Controlling diabetes matters at every age, but in older adults the priority shifts to avoiding low blood sugar (hypoglycaemia), which is more dangerous and can cause falls and confusion.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about diabetes in elderly',
    featTitle: 'What matters',
    features: [
      'Targets are often a little more relaxed to avoid low sugars',
      'Watch for and prevent hypoglycaemia (especially on sulfonylureas/insulin)',
      'Regular meals; do not skip meals after diabetes medicine',
      'Daily foot checks — small wounds can become serious',
      'Keep hydrated and stay active as able',
    ],
    warnings: [
      'Low-sugar signs: shakiness, sweating, confusion, falls — treat with fast sugar, seek help if severe',
      'Very high sugar with drowsiness or dehydration (emergency)',
      'A non-healing foot wound or ulcer',
      'Confusion (low or high sugar can cause it in the elderly)',
    ],
    noteTitle: 'Avoiding lows is the priority.',
    note: 'In older adults, a low blood sugar can be more harmful than a slightly high one, so targets and medicines are chosen to prevent hypos. Manage changes with a doctor. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What sugar level should an elderly diabetic aim for?', a: 'Targets are individualised and often a little more relaxed than for younger people, to avoid dangerous low sugars. Your doctor sets the right range.' },
      { q: 'Why are low sugars dangerous in the elderly?', a: 'They can cause confusion, falls, and heart problems, and may be less obvious. Preventing them is a key part of elderly diabetes care.' },
      { q: 'Why is foot care important in diabetes?', a: 'Reduced sensation means small wounds go unnoticed and can become serious ulcers or infections — daily foot checks catch problems early.' },
    ],
    related: [['diseases/type-2-diabetes', 'Type 2 diabetes'], ['medicines/metformin', 'Metformin'], ['nutrition/diabetic-diet-chart', 'Diabetic diet'], ['diseases/diabetic-foot-ulcer', 'Diabetic foot ulcer']],
  },
  {
    slug: 'elderly-health/knee-and-joint-pain-in-elderly',
    name: 'Knee & Joint Pain in Elderly',
    title: 'Knee & Joint Pain in the Elderly: Relief | MedDroid',
    desc: 'Knee and joint pain in older adults — managing osteoarthritis with exercise, weight and safe pain relief, and when to consider surgery. Not a diagnosis.',
    h1: 'Knee & joint pain in the elderly',
    lede: 'Osteoarthritis — “wear and tear” of the joints — is the commonest cause of knee and joint pain with age. It cannot be cured, but the right mix of exercise, weight control and safe pain relief keeps people active.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about joint pain',
    featTitle: 'What helps',
    features: [
      'Stay active — gentle exercise and strengthening protect joints',
      'Lose excess weight to reduce load on the knees',
      'Paracetamol first; topical anti-inflammatory gels for local pain',
      'Oral NSAIDs with caution in the elderly (stomach, kidney, heart risks)',
      'Physiotherapy, supports, and joint replacement for severe cases',
    ],
    warnings: [
      'A hot, red, swollen joint with fever (possible infection or gout)',
      'A joint that suddenly gives way, locks, or follows a fall (possible injury)',
      'NSAIDs: caution with kidney disease, ulcers and heart conditions',
    ],
    noteTitle: 'Movement helps more than rest.',
    note: 'Gentle activity and strengthening ease arthritis pain better than rest. Use oral anti-inflammatories cautiously in older adults. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What helps knee pain in old age?', a: 'Staying active with gentle strengthening exercises, losing excess weight, paracetamol and topical anti-inflammatory gels, and physiotherapy. Severe arthritis may need joint replacement.' },
      { q: 'Are painkillers safe for the elderly?', a: 'Paracetamol and topical gels are safest. Oral NSAIDs (like ibuprofen) need caution in older adults due to stomach, kidney and heart risks — use the lowest dose, short-term.' },
      { q: 'Do glucosamine and joint supplements work?', a: 'Any benefit is modest and evidence is mixed. Exercise, weight control and proper pain relief matter more.' },
    ],
    related: [['diseases/osteoarthritis', 'Osteoarthritis'], ['diseases/knee-rehab', 'Knee rehab'], ['medicines/paracetamol', 'Paracetamol'], ['elderly-health/staying-active-exercise-for-seniors', 'Exercise for seniors']],
  },
  {
    slug: 'elderly-health/memory-loss-and-dementia',
    name: 'Memory Loss & Dementia',
    title: 'Memory Loss & Dementia: When to Worry | MedDroid',
    desc: 'Memory loss in older age — normal forgetfulness vs dementia warning signs, treatable causes, and how to get help early. Not a diagnosis.',
    h1: 'Memory loss & dementia',
    lede: 'Some forgetfulness is a normal part of ageing, but memory loss that disrupts daily life can be dementia — or a treatable cause like deficiency, thyroid problems or depression. Getting checked early matters.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about memory loss',
    featTitle: 'Normal vs concerning',
    features: [
      'Normal: occasionally misplacing things, forgetting a name then recalling it',
      'Concerning: getting lost in familiar places, repeating questions, poor judgement',
      'Difficulty with daily tasks, money, or medicines',
      'Treatable causes exist: B12/thyroid deficiency, depression, medicines',
      'Early diagnosis allows treatment, planning and support',
    ],
    warnings: [
      'Sudden confusion (delirium) — often infection, dehydration or medicines — needs urgent care',
      'Memory loss affecting safety (driving, gas, wandering, medicines)',
      'Rapid decline, personality change, or new weakness (see a doctor)',
    ],
    noteTitle: 'Sudden confusion is different — it’s urgent.',
    note: 'Gradual memory loss needs assessment; sudden confusion (delirium) is often due to infection, dehydration or medicines and needs urgent care. Some causes of memory loss are reversible. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the difference between normal forgetfulness and dementia?', a: 'Occasionally forgetting names or where you put keys is normal. Dementia disrupts daily life — getting lost, repeating questions, struggling with money or tasks, and poor judgement.' },
      { q: 'Can memory loss be treated?', a: 'Some causes are reversible (vitamin B12 or thyroid deficiency, depression, medicine side effects). Dementia is not curable but treatments and support can help — early diagnosis matters.' },
      { q: 'My elderly relative suddenly became confused — what should I do?', a: 'Sudden confusion (delirium) is usually caused by infection, dehydration, pain or medicines and needs urgent medical review — it is different from gradual dementia.' },
    ],
    related: [['diseases/dementia', 'Dementia'], ['diseases/alzheimers-dementia', 'Alzheimer’s dementia'], ['diseases/delirium', 'Delirium'], ['medicines/donepezil', 'Donepezil']],
  },
  {
    slug: 'elderly-health/preventing-falls-in-elderly',
    name: 'Preventing Falls in Elderly',
    title: 'Preventing Falls in the Elderly: A Practical Guide | MedDroid',
    desc: 'Preventing falls in older adults — home safety, exercise for balance, medicine review, vision and footwear, and what to do after a fall. Not a diagnosis.',
    h1: 'Preventing falls in the elderly',
    lede: 'Falls are a leading cause of injury in older adults, but many are preventable. A mix of strength and balance exercise, home safety, medicine review and good vision dramatically lowers the risk.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fall prevention',
    featTitle: 'How to prevent falls',
    features: [
      'Strength and balance exercises (like tai chi or physiotherapy)',
      'Home safety: remove loose rugs/wires, add grab bars and good lighting',
      'Review medicines that cause dizziness or drowsiness with a doctor',
      'Check vision and update glasses; treat cataracts',
      'Well-fitting non-slip footwear; a walking aid if needed',
    ],
    warnings: [
      'A fall with a head injury, or on blood thinners — get checked',
      'Being unable to get up, or pain/deformity after a fall (possible fracture)',
      'Recurrent falls or “near-falls” (needs assessment)',
      'Fainting or blackouts (possible heart cause)',
    ],
    noteTitle: 'Most falls are preventable.',
    note: 'A falls assessment can identify and fix risk factors. After any significant fall — especially with a head injury or on blood thinners — get medical review. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can I prevent falls in an elderly person?', a: 'Balance and strength exercises, home safety changes (lighting, grab bars, removing trip hazards), reviewing dizzying medicines, checking vision, and good footwear all reduce falls.' },
      { q: 'What should I do after an elderly person falls?', a: 'Check for injury; do not move them if there is severe pain or a suspected spine injury. Any head injury (especially on blood thinners) or inability to get up needs medical review.' },
      { q: 'Why do older people fall more?', a: 'Weaker muscles, poorer balance and vision, dizziness from medicines or low BP, and home hazards all contribute — most of which can be improved.' },
    ],
    related: [['diseases/falls-in-the-elderly', 'Falls in the elderly'], ['diseases/balance-falls-rehab', 'Balance & falls rehab'], ['elderly-health/dizziness-and-balance', 'Dizziness & balance'], ['diseases/osteoporosis', 'Osteoporosis']],
  },
  {
    slug: 'elderly-health/managing-multiple-medicines',
    name: 'Managing Multiple Medicines',
    title: 'Managing Multiple Medicines (Polypharmacy) | MedDroid',
    desc: 'Managing many medicines in older age — avoiding interactions, using a pill organiser, medicine reviews, and questions to ask your doctor. Not a diagnosis.',
    h1: 'Managing multiple medicines (polypharmacy)',
    lede: 'Older adults often take several medicines, which raises the risk of interactions, side effects and confusion. Regular medicine reviews and simple systems keep it safe — and sometimes fewer medicines are better.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about medicines',
    featTitle: 'How to keep it safe',
    features: [
      'Keep an up-to-date list of all medicines (including supplements)',
      'Use a weekly pill organiser or blister pack',
      'Ask for a medicine review — some drugs may no longer be needed',
      'Take medicines as directed; do not stop or double up on your own',
      'Tell every doctor and pharmacist your full list to avoid interactions',
    ],
    warnings: [
      'New confusion, drowsiness, dizziness or falls (possible medicine side effect)',
      'A new medicine causing side effects — report it, do not just stop',
      'Running out, or taking doubles by mistake',
    ],
    noteTitle: 'More medicines is not always better.',
    note: 'A medicine review can safely reduce unnecessary drugs (deprescribing) and lower side effects. Always change medicines with a doctor, not alone. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can elderly people manage many medicines?', a: 'Keep an up-to-date list, use a weekly pill organiser or blister pack, take doses as scheduled, and have regular medicine reviews to check each one is still needed.' },
      { q: 'Is taking many medicines dangerous?', a: 'It raises the risk of interactions and side effects (polypharmacy). Regular reviews can safely reduce unnecessary medicines and improve wellbeing.' },
      { q: 'What if a medicine causes side effects?', a: 'Report it to your doctor or pharmacist rather than just stopping — some medicines must be reduced gradually, and alternatives may be available.' },
    ],
    related: [['diseases/polypharmacy', 'Polypharmacy'], ['diseases/frailty', 'Frailty'], ['elderly-health/preventing-falls-in-elderly', 'Preventing falls'], ['medicine-for/sleep', 'Medicine for sleep']],
  },
  {
    slug: 'elderly-health/osteoporosis-and-bone-health',
    name: 'Osteoporosis & Bone Health',
    title: 'Osteoporosis & Bone Health in Older Age | MedDroid',
    desc: 'Osteoporosis in older adults — how to keep bones strong, calcium and vitamin D, screening, and treatments to prevent fractures. Not a diagnosis.',
    h1: 'Osteoporosis & bone health',
    lede: 'Bones weaken with age, and osteoporosis makes fractures more likely — often from minor falls. Calcium, vitamin D, exercise and, when needed, medicine keep bones stronger and prevent fractures.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about bone health',
    featTitle: 'How to protect bones',
    features: [
      'Enough calcium (diet first) and vitamin D',
      'Weight-bearing and strength exercise',
      'Stop smoking and limit alcohol',
      'A bone-density (DEXA) scan to assess risk',
      'Bone-strengthening medicines (like bisphosphonates) when advised',
    ],
    warnings: [
      'A fracture from a minor fall (suggests osteoporosis — get assessed)',
      'Loss of height or a stooped back (possible spine fractures)',
      'Sudden severe back pain in an older person',
    ],
    noteTitle: 'Prevent the first fracture.',
    note: 'Osteoporosis is silent until a fracture, so assessing risk and protecting bones early matters. Preventing falls protects fragile bones too. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can I strengthen bones in old age?', a: 'Get enough calcium and vitamin D, do weight-bearing and strength exercise, avoid smoking and excess alcohol, and take bone-strengthening medicine if your doctor advises.' },
      { q: 'How do I know if I have osteoporosis?', a: 'It is usually silent until a fracture. A bone-density (DEXA) scan assesses your risk — recommended for older adults and those with risk factors.' },
      { q: 'Do I need calcium and vitamin D supplements?', a: 'If your diet and sun exposure are not enough — common in older adults — supplements help, especially alongside osteoporosis treatment. Your doctor advises.' },
    ],
    related: [['diseases/osteoporosis', 'Osteoporosis'], ['medicines/alendronate', 'Alendronate'], ['nutrition/calcium-rich-foods', 'Calcium-rich foods'], ['medicines/vitamin-d3', 'Vitamin D3']],
  },
  {
    slug: 'elderly-health/constipation-in-elderly',
    name: 'Constipation in Elderly',
    title: 'Constipation in the Elderly: Causes & Relief | MedDroid',
    desc: 'Constipation in older adults — why it is common, safe relief with fibre, fluids and laxatives, and warning signs to check. Not a diagnosis.',
    h1: 'Constipation in the elderly',
    lede: 'Constipation is very common in older age — from less activity, low fluid and fibre, and many medicines. It is usually easily managed, but a sudden change in bowel habit should always be checked.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about constipation',
    featTitle: 'What helps',
    features: [
      'More fluids and fibre (fruit, vegetables, whole grains)',
      'Stay as active as possible',
      'Review constipating medicines with a doctor',
      'Gentle laxatives (lactulose, PEG) when needed',
      'A regular, unhurried toilet routine',
    ],
    warnings: [
      'A sudden change in bowel habit, especially over 50 (get checked)',
      'Blood in the stool, or unexplained weight loss',
      'Severe pain, vomiting and no passing of stool/gas (possible obstruction)',
      'Constipation with confusion in a frail person (can signal illness)',
    ],
    noteTitle: 'A sudden change needs checking.',
    note: 'Constipation is common and manageable, but a new, persistent change in bowel habit in an older adult should be assessed. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why do elderly people get constipated?', a: 'Less activity, low fluid and fibre intake, weaker bowel muscles, and many common medicines all contribute.' },
      { q: 'What is a safe laxative for the elderly?', a: 'Fibre and osmotic laxatives (like lactulose or PEG) are gentle and suitable for regular use; stimulant laxatives are best short-term. Fluids and fibre come first.' },
      { q: 'When is constipation serious in the elderly?', a: 'A sudden change in bowel habit, blood in stool, weight loss, or severe pain with vomiting and no stool/gas all need prompt medical review.' },
    ],
    related: [['diseases/constipation', 'Constipation'], ['medicines/lactulose', 'Lactulose'], ['medicine-for/constipation', 'Medicine for constipation'], ['nutrition/gut-health-foods', 'Gut health foods']],
  },
  {
    slug: 'elderly-health/sleep-problems-in-elderly',
    name: 'Sleep Problems in Elderly',
    title: 'Sleep Problems in the Elderly: What Helps | MedDroid',
    desc: 'Sleep problems in older adults — why sleep changes with age, safe ways to sleep better, and why sleeping pills carry extra risks in the elderly. Not a diagnosis.',
    h1: 'Sleep problems in the elderly',
    lede: 'Sleep naturally becomes lighter and more broken with age. Good sleep habits help most older adults — and sleeping pills are best avoided, as they raise the risk of falls and confusion.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sleep in elderly',
    featTitle: 'What helps',
    features: [
      'Keep a regular sleep-wake schedule and get daytime light and activity',
      'Limit long daytime naps, caffeine and evening fluids',
      'A calm, dark, comfortable bedroom',
      'Treat causes: pain, frequent urination, anxiety, sleep apnoea',
      'Avoid sleeping pills where possible (fall and confusion risk)',
    ],
    warnings: [
      'Loud snoring with daytime sleepiness (possible sleep apnoea)',
      'Sleep problems with low mood (possible depression)',
      'Sleeping pills causing confusion, unsteadiness or falls',
      'Sudden change in sleep with confusion (possible illness)',
    ],
    noteTitle: 'Habits over pills — especially in the elderly.',
    note: 'Sleeping pills raise the risk of falls, confusion and dependence in older adults, so sleep-hygiene and treating causes come first. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why do older people sleep less?', a: 'Sleep naturally becomes lighter and more fragmented with age, and pain, urination, medicines and anxiety can add to it. Good habits help most.' },
      { q: 'Are sleeping pills safe for the elderly?', a: 'They carry extra risks in older adults — falls, confusion and dependence — so they are avoided where possible in favour of sleep-hygiene and treating causes.' },
      { q: 'How can an elderly person sleep better?', a: 'Regular schedule, daytime activity and light, limited naps and caffeine, a comfortable dark room, and treating pain or frequent urination.' },
    ],
    related: [['diseases/insomnia', 'Insomnia'], ['mental-health/how-to-sleep-better', 'How to sleep better'], ['diseases/obstructive-sleep-apnoea', 'Sleep apnoea'], ['elderly-health/frequent-urination-at-night', 'Frequent urination at night']],
  },
  {
    slug: 'elderly-health/hearing-loss-in-elderly',
    name: 'Hearing Loss in Elderly',
    title: 'Hearing Loss in the Elderly: Help & Hearing Aids | MedDroid',
    desc: 'Age-related hearing loss — the signs, why it matters for the brain and mood, hearing aids, and when to see a doctor. Not a diagnosis.',
    h1: 'Hearing loss in the elderly',
    lede: 'Age-related hearing loss is very common and develops gradually, so it is often missed. Treating it with hearing aids improves not just hearing, but also mood, social life and even memory.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about hearing loss',
    featTitle: 'What to know',
    features: [
      'Signs: asking people to repeat, high TV volume, struggling in noise',
      'Rule out ear wax (a simple, common, reversible cause)',
      'A hearing test guides whether hearing aids will help',
      'Modern hearing aids are effective and discreet',
      'Treating hearing loss helps mood, social life and thinking',
    ],
    warnings: [
      'Sudden hearing loss in one or both ears — see a doctor urgently (may be treatable)',
      'Hearing loss with ear pain, discharge or dizziness',
      'One-sided hearing loss or ringing (needs assessment)',
    ],
    noteTitle: 'Sudden hearing loss is urgent.',
    note: 'Gradual age-related hearing loss should be tested and aided; sudden hearing loss can sometimes be reversed if treated quickly, so seek urgent care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is hearing loss a normal part of ageing?', a: 'Gradual hearing loss is common with age, but it should still be checked and treated — hearing aids improve quality of life, mood and even thinking.' },
      { q: 'Can ear wax cause hearing loss?', a: 'Yes — wax build-up is a common, easily reversible cause. It is worth ruling out before assuming permanent hearing loss.' },
      { q: 'When is hearing loss an emergency?', a: 'Sudden hearing loss (over hours to days), especially in one ear, needs urgent care — early treatment can sometimes restore it.' },
    ],
    related: [['diseases/age-related-hearing-loss', 'Age-related hearing loss'], ['diseases/hearing-loss', 'Hearing loss'], ['diseases/ear-wax-blockage', 'Ear wax blockage'], ['diseases/tinnitus', 'Tinnitus']],
  },
  {
    slug: 'elderly-health/cataract-and-vision-in-elderly',
    name: 'Cataract & Vision in Elderly',
    title: 'Cataract & Vision Problems in the Elderly | MedDroid',
    desc: 'Vision problems in older adults — cataract, glaucoma and macular degeneration, the signs, and why regular eye checks matter. Not a diagnosis.',
    h1: 'Cataract & vision in the elderly',
    lede: 'Failing eyesight is common with age, but much of it is treatable or preventable. Cataract surgery restores vision safely, while conditions like glaucoma need early detection to save sight.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about vision',
    featTitle: 'What to know',
    features: [
      'Cataract: cloudy, dim vision and glare — treated with simple surgery',
      'Glaucoma: silent loss of side vision — needs early detection',
      'Macular degeneration: loss of central vision — needs prompt care',
      'Diabetics: yearly retinal screening is essential',
      'Regular eye checks catch problems early; good vision prevents falls',
    ],
    warnings: [
      'Sudden vision loss, or a curtain/shadow across vision — emergency',
      'Sudden eye pain with redness, halos and nausea (acute glaucoma — urgent)',
      'New flashes and many floaters (possible retinal detachment)',
    ],
    noteTitle: 'Regular eye checks save sight.',
    note: 'Many causes of poor vision in older age are treatable, and some (like glaucoma) are silent until sight is lost — so regular eye checks matter. Sudden vision changes are emergencies. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is cataract surgery safe for the elderly?', a: 'Yes — it is one of the safest, most successful operations, and it restores vision, improves independence and reduces fall risk.' },
      { q: 'How often should older people get eye checks?', a: 'At least every 1–2 years, and yearly for diabetics, to catch treatable conditions like glaucoma and diabetic eye disease early.' },
      { q: 'What causes vision loss in old age?', a: 'Common causes are cataract, glaucoma, macular degeneration and diabetic eye disease — most treatable or manageable if caught early.' },
    ],
    related: [['diseases/cataract', 'Cataract'], ['diseases/glaucoma', 'Glaucoma'], ['diseases/macular-degeneration', 'Macular degeneration'], ['diseases/diabetic-retinopathy', 'Diabetic retinopathy']],
  },
  {
    slug: 'elderly-health/urinary-incontinence-in-elderly',
    name: 'Urinary Incontinence in Elderly',
    title: 'Urinary Incontinence in the Elderly: Help | MedDroid',
    desc: 'Urinary incontinence in older adults — the types, practical management, treatments, and why it is not something to just accept. Not a diagnosis.',
    h1: 'Urinary incontinence in the elderly',
    lede: 'Leaking urine is common with age but is not an inevitable part of ageing — and it is treatable. Many people suffer in silence, when simple measures and treatments could greatly help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about incontinence',
    featTitle: 'What helps',
    features: [
      'Pelvic-floor exercises strengthen bladder control',
      'Bladder training and a regular toilet schedule',
      'Manage fluids and limit caffeine/alcohol',
      'Treat causes: infection, constipation, prostate problems, medicines',
      'Medicines or other treatments for overactive bladder when needed',
    ],
    warnings: [
      'New incontinence with burning urine or fever (possible UTI)',
      'Sudden incontinence with weakness or numbness (urgent — nerve cause)',
      'Blood in the urine',
      'Incontinence causing skin breakdown or distress',
    ],
    noteTitle: 'Treatable — do not just accept it.',
    note: 'Incontinence has effective treatments and is not an unavoidable part of ageing. Sudden incontinence with weakness/numbness is an emergency. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is urinary incontinence a normal part of ageing?', a: 'It is common but not inevitable — and it is treatable. Pelvic-floor exercises, bladder training, treating causes and medicines can greatly help.' },
      { q: 'How can I manage incontinence in an elderly person?', a: 'Pelvic-floor exercises, a toilet schedule, managing fluids, treating infection or constipation, and reviewing medicines — with medical treatment for overactive bladder if needed.' },
      { q: 'When should incontinence be checked?', a: 'Promptly for new incontinence with burning/fever (UTI), blood in urine, or sudden incontinence with weakness or numbness (a nerve emergency).' },
    ],
    related: [['diseases/urinary-incontinence', 'Urinary incontinence'], ['diseases/overactive-bladder', 'Overactive bladder'], ['diseases/benign-prostatic-hyperplasia', 'Enlarged prostate'], ['medicines/mirabegron', 'Mirabegron']],
  },
  {
    slug: 'elderly-health/frequent-urination-at-night',
    name: 'Frequent Urination at Night',
    title: 'Frequent Urination at Night (Nocturia) in Elderly | MedDroid',
    desc: 'Waking to pass urine at night (nocturia) in older adults — the common causes, practical tips, and when to see a doctor. Not a diagnosis.',
    h1: 'Frequent urination at night (nocturia)',
    lede: 'Waking once or more each night to pass urine (nocturia) is common with age and disrupts sleep. It has several treatable causes — from an enlarged prostate to diabetes or heart conditions.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about nocturia',
    featTitle: 'Common causes & tips',
    features: [
      'Enlarged prostate (men) or overactive bladder',
      'Drinking a lot in the evening, or caffeine/alcohol',
      'Diabetes (high sugar), or fluid shifting from swollen legs at night',
      'Tips: limit evening fluids, elevate swollen legs earlier in the day',
      'Treat the cause (prostate, bladder, diabetes, heart)',
    ],
    warnings: [
      'Very frequent urination with excessive thirst and weight loss (check for diabetes)',
      'Burning urine or fever (possible UTI)',
      'Blood in the urine',
      'Nocturia with breathlessness or leg swelling (possible heart cause)',
    ],
    noteTitle: 'Find the cause.',
    note: 'Nocturia is not just “old age” — an enlarged prostate, diabetes, bladder or heart conditions may be treatable causes. It also raises fall risk at night. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why do I wake up so often to urinate at night?', a: 'Common causes include an enlarged prostate, overactive bladder, evening fluids or caffeine, diabetes, and fluid from swollen legs shifting at night. Many are treatable.' },
      { q: 'How can I reduce night-time urination?', a: 'Limit fluids and caffeine/alcohol in the evening, elevate swollen legs earlier in the day, and treat causes like prostate enlargement or diabetes.' },
      { q: 'When should frequent urination be checked?', a: 'With excessive thirst and weight loss (diabetes), burning or fever (UTI), blood in urine, or with breathlessness/leg swelling — see a doctor.' },
    ],
    related: [['diseases/benign-prostatic-hyperplasia', 'Enlarged prostate (BPH)'], ['diseases/overactive-bladder', 'Overactive bladder'], ['diseases/type-2-diabetes', 'Type 2 diabetes'], ['mens-health/enlarged-prostate-bph', 'Enlarged prostate']],
  },
  {
    slug: 'elderly-health/depression-and-loneliness-in-elderly',
    name: 'Depression & Loneliness in Elderly',
    title: 'Depression & Loneliness in the Elderly | MedDroid',
    desc: 'Depression and loneliness in older adults — why it is often missed, the signs, and how to help. It is treatable, not a normal part of ageing. Not a diagnosis.',
    h1: 'Depression & loneliness in the elderly',
    lede: 'Depression is not a normal part of ageing, yet it is common and often missed in older adults — sometimes showing as physical complaints or memory problems. It is treatable, and connection makes a real difference.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about elderly mood',
    featTitle: 'Signs & what helps',
    features: [
      'Signs: low mood, loss of interest, poor sleep/appetite, aches, memory complaints',
      'Stay socially connected — combat isolation and loneliness',
      'Keep active and maintain routines and hobbies',
      'Treat contributing factors: pain, hearing/vision loss, thyroid, medicines',
      'Talking therapy and, if needed, antidepressants both help',
    ],
    warnings: [
      'Any thoughts of self-harm or that life is not worth living — seek help urgently (India: KIRAN 1800-599-0019, Tele-MANAS 14416)',
      'Not eating, drinking or caring for self',
      'Rapid decline, or new confusion (rule out physical illness)',
    ],
    noteTitle: 'Not a normal part of ageing.',
    note: 'Depression in older adults is common, treatable, and not something to just accept. If there are any thoughts of self-harm, seek help now (in India, KIRAN 1800-599-0019 or Tele-MANAS 14416). MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is depression normal in old age?', a: 'No — although common, it is not a normal or inevitable part of ageing. It is treatable, and older adults respond well to therapy and, when needed, medicine.' },
      { q: 'How can I help a lonely elderly parent?', a: 'Regular contact and visits, involving them in activities and community, treating hearing/vision problems that isolate them, and seeking help if you notice signs of depression.' },
      { q: 'How is depression different in the elderly?', a: 'It often shows as physical complaints, aches, poor sleep or memory problems rather than obvious sadness, so it is easily missed.' },
    ],
    related: [['diseases/depression', 'Depression'], ['diseases/loneliness', 'Loneliness'], ['mental-health/depression-signs-and-help', 'Depression: signs & help'], ['medicines/sertraline', 'Sertraline']],
  },
  {
    slug: 'elderly-health/nutrition-for-elderly',
    name: 'Nutrition for the Elderly',
    title: 'Nutrition for the Elderly: Eating Well in Old Age | MedDroid',
    desc: 'Nutrition for older adults — getting enough protein and nutrients with a smaller appetite, staying hydrated, and preventing weight loss and frailty. Not a diagnosis.',
    h1: 'Nutrition for the elderly',
    lede: 'Eating well protects strength, immunity and independence in older age. Appetite often falls, so the focus shifts to nutrient- and protein-rich foods, enough fluids, and preventing unintended weight loss.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about elderly nutrition',
    featTitle: 'What matters',
    features: [
      'Enough protein (dal, curd, paneer, eggs, milk) to preserve muscle',
      'Small, frequent, nutrient-dense meals if appetite is low',
      'Enough fluids — thirst is blunted with age (dehydration risk)',
      'Calcium, vitamin D, B12 and fibre',
      'Soft, easy-to-chew foods if teeth or swallowing are a problem',
    ],
    warnings: [
      'Unintended weight loss (find the cause — see a doctor)',
      'Difficulty or pain swallowing, or coughing when eating/drinking',
      'Signs of dehydration (confusion, little urine)',
      'Poor appetite with low mood (possible depression)',
    ],
    noteTitle: 'Protein and fluids matter most.',
    note: 'Protecting muscle with enough protein and staying hydrated help older adults stay strong and independent. Unintended weight loss should always be investigated. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What should elderly people eat?', a: 'Protein-rich foods (dal, curd, paneer, eggs, milk), plenty of fluids, and calcium, vitamin D, B12 and fibre — in small, frequent, nutrient-dense meals if appetite is low.' },
      { q: 'How can I help an elderly person with poor appetite?', a: 'Offer small frequent meals, nutrient-dense foods and favourites, make mealtimes social, treat mouth/teeth problems, and check for depression or illness behind the loss of appetite.' },
      { q: 'Why is protein important for the elderly?', a: 'It preserves muscle strength, which protects against frailty and falls. Older adults often need more protein than they get.' },
    ],
    related: [['diseases/malnutrition', 'Malnutrition'], ['diseases/frailty', 'Frailty'], ['nutrition/high-protein-vegetarian-foods', 'High-protein veg foods'], ['elderly-health/dehydration-in-elderly', 'Dehydration in elderly']],
  },
  {
    slug: 'elderly-health/dehydration-in-elderly',
    name: 'Dehydration in Elderly',
    title: 'Dehydration in the Elderly: Signs & Prevention | MedDroid',
    desc: 'Dehydration in older adults — why they are at higher risk, the signs (including confusion), and how to prevent it. Not a diagnosis.',
    h1: 'Dehydration in the elderly',
    lede: 'Older adults dehydrate easily because thirst is blunted with age, and dehydration can quickly cause confusion, falls, urine infections and kidney problems. Preventing it is simple but important.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dehydration',
    featTitle: 'Signs & prevention',
    features: [
      'Signs: dry mouth, dark urine, tiredness, dizziness, confusion',
      'Offer fluids regularly through the day (do not wait for thirst)',
      'Watch intake in hot weather, fever, vomiting or diarrhoea',
      'Include water-rich foods (fruit, soups, curd)',
      'Balance with any doctor-advised fluid limits (heart/kidney disease)',
    ],
    warnings: [
      'Confusion, drowsiness, very little urine, or a fast pulse (serious — seek care)',
      'Dehydration with vomiting/diarrhoea, or unable to keep fluids down',
      'Sudden confusion in a frail person (dehydration is a common cause of delirium)',
    ],
    noteTitle: 'Confusion can be a sign of dehydration.',
    note: 'In older adults, dehydration often shows as confusion, falls or a urine infection rather than obvious thirst. Offer fluids regularly. Those with heart/kidney disease should follow their fluid advice. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why do elderly people get dehydrated easily?', a: 'Thirst is blunted with age, the kidneys conserve water less well, and mobility or memory issues can reduce drinking — so dehydration develops easily.' },
      { q: 'What are the signs of dehydration in the elderly?', a: 'Dry mouth, dark urine, tiredness, dizziness and — importantly — confusion. Serious dehydration causes drowsiness, very little urine and a fast pulse.' },
      { q: 'How much should an elderly person drink?', a: 'Usually around 1.5–2 litres a day unless a doctor has advised a fluid limit for heart or kidney disease. Offer fluids regularly rather than waiting for thirst.' },
    ],
    related: [['diseases/dehydration', 'Dehydration'], ['diseases/delirium', 'Delirium'], ['medicines/ors', 'ORS'], ['is-my-child-dehydrated', 'Signs of dehydration'],],
  },
  {
    slug: 'elderly-health/dizziness-and-balance',
    name: 'Dizziness & Balance in Elderly',
    title: 'Dizziness & Balance Problems in the Elderly | MedDroid',
    desc: 'Dizziness and balance problems in older adults — the common causes (BP drop, inner ear, medicines), what helps, and when it is serious. Not a diagnosis.',
    h1: 'Dizziness & balance in the elderly',
    lede: 'Dizziness and unsteadiness are common in older age and raise the risk of falls. There are many causes — from a blood-pressure drop on standing to inner-ear problems or medicines — and most can be helped.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dizziness',
    featTitle: 'Common causes & what helps',
    features: [
      'Blood-pressure drop on standing — rise slowly, stay hydrated',
      'Inner-ear problems (like BPPV) — treatable with specific manoeuvres',
      'Medicines causing dizziness — review with a doctor',
      'Anaemia, low sugar, dehydration, or heart-rhythm problems',
      'Balance exercises and vision correction reduce falls',
    ],
    warnings: [
      'Dizziness with slurred speech, weakness, or face droop (stroke — emergency)',
      'Fainting or blackouts (possible heart cause)',
      'Severe spinning vertigo with vomiting',
      'Dizziness with chest pain or palpitations',
    ],
    noteTitle: 'Find the cause; prevent falls.',
    note: 'Dizziness has many treatable causes; sudden dizziness with stroke signs is an emergency. Addressing it protects against falls. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why does my elderly parent feel dizzy?', a: 'Common causes are a blood-pressure drop on standing, inner-ear problems, medicines, dehydration, anaemia, low sugar or heart-rhythm issues — most of which can be treated.' },
      { q: 'What helps dizziness in the elderly?', a: 'Rising slowly, staying hydrated, reviewing medicines, treating inner-ear causes (like BPPV manoeuvres), and balance exercises. The underlying cause should be found.' },
      { q: 'When is dizziness an emergency?', a: 'With stroke signs (slurred speech, weakness, face droop), fainting, chest pain or palpitations — call emergency services.' },
    ],
    related: [['diseases/vertigo', 'Vertigo'], ['diseases/vertigo-bppv', 'BPPV'], ['first-aid/stroke-first-aid', 'Stroke first aid (FAST)'], ['elderly-health/preventing-falls-in-elderly', 'Preventing falls']],
  },
  {
    slug: 'elderly-health/vaccines-for-elderly',
    name: 'Vaccines for the Elderly',
    title: 'Vaccines for the Elderly: What Is Recommended | MedDroid',
    desc: 'Vaccines recommended for older adults — flu, pneumonia, shingles, tetanus and COVID — why they matter and what to know. Not a diagnosis.',
    h1: 'Vaccines for the elderly',
    lede: 'Vaccines are not just for children. As immunity weakens with age, certain vaccines protect older adults from serious illnesses like flu, pneumonia and shingles — preventing hospitalisation and worse.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about vaccines',
    featTitle: 'Commonly recommended (ask your doctor)',
    features: [
      'Influenza (flu) — yearly',
      'Pneumococcal (pneumonia) vaccine',
      'Shingles (herpes zoster) vaccine',
      'Tetanus/diphtheria booster',
      'COVID-19 vaccination/boosters as advised',
    ],
    warnings: [
      'Postpone routine vaccines if seriously unwell (a mild cold is usually fine)',
      'A severe reaction to a previous dose — tell your doctor',
      'Difficulty breathing or swelling after a vaccine (very rare) — emergency',
    ],
    noteTitle: 'Vaccines prevent serious illness in older age.',
    note: 'Recommended vaccines vary by country and health condition, so confirm with your doctor. They are a safe, effective way to prevent serious infections in older adults. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Which vaccines do elderly people need?', a: 'Commonly the yearly flu vaccine, pneumococcal (pneumonia), shingles, a tetanus booster, and COVID-19 as advised. Your doctor tailors this to your health and country.' },
      { q: 'Is the flu vaccine necessary every year?', a: 'Yes — flu strains change and immunity fades, so a yearly flu vaccine is recommended for older adults, who are at higher risk of complications.' },
      { q: 'What is the shingles vaccine?', a: 'It reduces the risk of shingles (a painful reactivation of the chickenpox virus) and its lasting nerve pain, and is recommended for older adults.' },
    ],
    related: [['diseases/influenza', 'Influenza'], ['diseases/pneumonia', 'Pneumonia'], ['diseases/shingles', 'Shingles'], ['diseases/tetanus', 'Tetanus']],
  },
  {
    slug: 'elderly-health/bedsores-prevention',
    name: 'Preventing Bedsores',
    title: 'Preventing Bedsores (Pressure Sores) | MedDroid',
    desc: 'Preventing bedsores in bedridden or immobile patients — repositioning, skin care, nutrition, and spotting early signs. A caregiver guide. Not a diagnosis.',
    h1: 'Preventing bedsores (pressure sores)',
    lede: 'Bedsores develop when constant pressure cuts off blood flow to the skin, common in bedridden or wheelchair-using people. They are largely preventable with regular repositioning and good skin care — and much harder to treat once formed.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about bedsores',
    featTitle: 'How to prevent them',
    features: [
      'Reposition the person at least every 2 hours',
      'Use pressure-relieving mattresses/cushions',
      'Keep skin clean and dry; manage incontinence promptly',
      'Check pressure points (heels, hips, tailbone, elbows) daily',
      'Good nutrition, hydration and protein help skin stay healthy',
    ],
    warnings: [
      'Early sign: a persistent red (or darker) patch that does not fade — act now',
      'Broken skin, an open sore, or black tissue (needs medical care)',
      'Signs of infection: pus, spreading redness, fever, bad smell',
    ],
    noteTitle: 'Prevention is far easier than cure.',
    note: 'Once a bedsore forms it can be serious and slow to heal, so prevention — repositioning, skin care and nutrition — is key. An established sore needs medical/nursing care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I prevent bedsores?', a: 'Reposition the person at least every 2 hours, use pressure-relieving mattresses/cushions, keep skin clean and dry, check pressure points daily, and ensure good nutrition and hydration.' },
      { q: 'What does an early bedsore look like?', a: 'A persistent red or darker patch of skin over a pressure point (like the tailbone or heels) that does not fade when the pressure is relieved. Act immediately at this stage.' },
      { q: 'When does a bedsore need a doctor?', a: 'When the skin breaks, there is an open or blackened sore, or signs of infection (pus, spreading redness, fever) — these need medical and nursing care.' },
    ],
    related: [['diseases/pressure-sores', 'Pressure sores'], ['diseases/frailty', 'Frailty'], ['elderly-health/nutrition-for-elderly', 'Nutrition for the elderly'], ['diseases/malnutrition', 'Malnutrition']],
  },
  {
    slug: 'elderly-health/staying-active-exercise-for-seniors',
    name: 'Exercise for Seniors',
    title: 'Exercise for Seniors: Staying Active Safely | MedDroid',
    desc: 'Exercise for older adults — safe, effective activity for strength, balance and heart health, how much to aim for, and when to check with a doctor. Not a diagnosis.',
    h1: 'Staying active: exercise for seniors',
    lede: 'Staying active is one of the best things older adults can do — it maintains strength, balance, mood and independence, and reduces falls. It is never too late to start, gently and safely.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about exercise for seniors',
    featTitle: 'What to aim for',
    features: [
      'Aim for regular activity most days — walking counts',
      'Strength exercises twice a week (protect muscle and bone)',
      'Balance exercises (like tai chi) to prevent falls',
      'Gentle stretching for flexibility',
      'Start slow, build up gradually, and stay hydrated',
    ],
    warnings: [
      'Chest pain, severe breathlessness or dizziness during exercise — stop and get checked',
      'Check with a doctor before starting if you have heart, lung or joint conditions',
      'Sharp joint pain (not normal muscle ache)',
    ],
    noteTitle: 'It is never too late to start.',
    note: 'Even gentle regular activity brings big benefits in older age. Those with heart, lung or joint conditions should check with a doctor before starting a new programme. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How much should seniors exercise?', a: 'Aim for regular activity most days (walking counts), plus strength exercises twice a week and balance work. Start gently and build up gradually.' },
      { q: 'Is it safe to start exercising in old age?', a: 'Yes — it is never too late, and the benefits are large. Start slowly, and check with a doctor first if you have heart, lung or significant joint conditions.' },
      { q: 'What exercise prevents falls?', a: 'Strength and balance exercises — like tai chi or physiotherapy-guided programmes — are proven to reduce falls in older adults.' },
    ],
    related: [['diseases/frailty', 'Frailty'], ['elderly-health/preventing-falls-in-elderly', 'Preventing falls'], ['elderly-health/knee-and-joint-pain-in-elderly', 'Knee & joint pain'], ['diseases/osteoporosis', 'Osteoporosis']],
  },
];
