// Eye & ENT Q&A cluster for MedDroid. Practical, India-aware. Full page objects
// (same shape gen-landing's page() consumes). Educational only, not a diagnosis.
// Strong red flags for sight- and hearing-threatening emergencies.

export const EYE_ENT_QA = [
  {
    slug: 'eye-ent/dry-eyes-and-screen-strain',
    name: 'Dry Eyes & Screen Strain',
    title: 'Dry Eyes & Computer Screen Strain: Relief | MedDroid',
    desc: 'Dry, tired eyes from screens — why it happens, the 20-20-20 rule, tear drops, and when to see a doctor. Digital eye strain relief. Not a diagnosis.',
    h1: 'Dry eyes & computer screen strain',
    lede: 'Long hours on screens make us blink less, leaving eyes dry, gritty and tired. This "digital eye strain" is very common and usually eases with simple habits and lubricating tear drops.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dry eyes',
    featTitle: 'What helps',
    features: [
      'The 20-20-20 rule: every 20 minutes, look 20 feet away for 20 seconds',
      'Blink fully and often; use lubricating (artificial tear) drops',
      'Position the screen slightly below eye level; reduce glare',
      'Take breaks, and use a humidifier in dry/AC rooms',
      'Stay hydrated; have an eye check for uncorrected vision',
    ],
    warnings: [
      'Eye pain, marked redness, or vision changes (not just tiredness)',
      'Dry eyes with a dry mouth and joint pains (possible autoimmune cause)',
      'Symptoms not helped by drops and breaks',
    ],
    noteTitle: 'Screens don’t damage eyes — but strain them.',
    note: 'Screen use causes discomfort and dryness, not permanent damage, and improves with habits and tear drops. Persistent pain or vision change needs a check. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I relieve eye strain from computers?', a: 'Use the 20-20-20 rule, blink more, use lubricating tear drops, reduce glare, position the screen well, and take regular breaks. Get an eye check if it persists.' },
      { q: 'Do screens damage your eyes?', a: 'They cause temporary strain and dryness, not permanent damage. Blue-light glasses have little proven benefit; habits and tear drops help more.' },
      { q: 'What eye drops are good for dry eyes?', a: 'Preservative-free lubricating (artificial tear) drops, like carboxymethylcellulose, used as needed. A doctor can advise for persistent dryness.' },
    ],
    related: [['diseases/dry-eye', 'Dry eye'], ['medicines/carboxymethylcellulose-eye', 'Tear drops'], ['eye-ent/eye-twitching', 'Eye twitching'], ['diseases/refractive-errors', 'Refractive errors']],
  },
  {
    slug: 'eye-ent/red-eye-causes',
    name: 'Red Eye: Causes',
    title: 'Red Eye: Common Causes & When It Is Serious | MedDroid',
    desc: 'Red eye — common causes like conjunctivitis and dryness, and the danger signs (pain, vision loss) that need urgent care. Not a diagnosis.',
    h1: 'Red eye: causes & when to worry',
    lede: 'A red eye is usually harmless — from conjunctivitis, dryness or a burst blood vessel. But a red eye with pain, vision changes or light sensitivity can be serious and needs urgent care.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about red eye',
    featTitle: 'Common (usually harmless) causes',
    features: [
      'Conjunctivitis (viral, bacterial or allergic)',
      'Dry eye or eye strain',
      'A burst small blood vessel (subconjunctival haemorrhage) — looks dramatic, harmless',
      'Irritation from dust, smoke or chlorine',
      'Blepharitis (eyelid inflammation)',
    ],
    warnings: [
      'Red eye WITH pain, reduced vision, or light sensitivity — urgent (could be serious)',
      'A red, painful eye in a contact-lens wearer (possible corneal ulcer)',
      'Severe eye pain with halos and nausea (acute glaucoma — emergency)',
      'Red eye after an injury or chemical splash',
    ],
    noteTitle: 'Pain or vision change makes it urgent.',
    note: 'A painless red eye with normal vision is usually minor. Red eye with pain, blurred vision or light sensitivity needs same-day eye care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why is my eye red?', a: 'Most often conjunctivitis, dryness, irritation or a harmless burst blood vessel. But a red eye with pain, blurred vision or light sensitivity can be serious.' },
      { q: 'When is a red eye serious?', a: 'When it comes with pain, reduced vision, light sensitivity, in a contact-lens wearer, or after injury/chemical splash — get urgent eye care.' },
      { q: 'Is a burst blood vessel in the eye dangerous?', a: 'Usually not — a bright red patch on the white of the eye (subconjunctival haemorrhage) looks alarming but is harmless and clears in 1–2 weeks.' },
    ],
    related: [['diseases/conjunctivitis', 'Conjunctivitis'], ['eye-ent/conjunctivitis-pink-eye', 'Pink eye care'], ['diseases/corneal-ulcer', 'Corneal ulcer'], ['diseases/glaucoma', 'Glaucoma']],
  },
  {
    slug: 'eye-ent/conjunctivitis-pink-eye',
    name: 'Conjunctivitis (Pink Eye)',
    title: 'Conjunctivitis (Pink Eye): Care & When It Spreads | MedDroid',
    desc: 'Pink eye (conjunctivitis) — viral, bacterial and allergic types, home care, hygiene to stop it spreading, and when to see a doctor. Not a diagnosis.',
    h1: 'Conjunctivitis (pink eye)',
    lede: 'Conjunctivitis is a common, usually mild eye infection or allergy causing redness, watering and discharge. Most viral cases clear on their own, and good hygiene stops it spreading.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pink eye',
    featTitle: 'Care & hygiene',
    features: [
      'Clean the eyes gently with cooled boiled water; use cold compresses',
      'Wash hands often; do not share towels or pillows',
      'Allergic type: antihistamine or anti-allergy eye drops',
      'Bacterial type (thick pus): may need antibiotic eye drops',
      'Avoid contact lenses and eye make-up until it clears',
    ],
    warnings: [
      'Eye pain, reduced vision, or light sensitivity (not simple conjunctivitis)',
      'A red, painful eye in a contact-lens wearer',
      'A newborn with red, discharging eyes (urgent)',
      'No improvement in a week',
    ],
    noteTitle: 'Very contagious — mind hygiene.',
    note: 'Viral and bacterial conjunctivitis spread easily, so hand hygiene matters. Pain, vision change or a painful contact-lens wearer’s eye needs urgent review. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How long does pink eye last?', a: 'Viral conjunctivitis usually clears in 1–2 weeks; allergic settles when the trigger is removed; bacterial improves within days of antibiotic drops if needed.' },
      { q: 'Is conjunctivitis contagious?', a: 'Viral and bacterial types are very contagious. Wash hands often, avoid touching the eyes, and do not share towels until it clears.' },
      { q: 'Do I need antibiotic drops for pink eye?', a: 'Most cases are viral and clear on their own. Antibiotic drops are only for bacterial conjunctivitis (thick pus) as advised by a doctor.' },
    ],
    related: [['diseases/conjunctivitis', 'Conjunctivitis'], ['diseases/allergic-conjunctivitis', 'Allergic conjunctivitis'], ['medicines/moxifloxacin-eye', 'Moxifloxacin (eye)'], ['medicines/olopatadine-eye', 'Olopatadine (eye)']],
  },
  {
    slug: 'eye-ent/eye-floaters-and-flashes',
    name: 'Eye Floaters & Flashes',
    title: 'Eye Floaters & Flashes: When to Worry | MedDroid',
    desc: 'Eye floaters and flashes of light — when they are harmless and when they signal a retinal detachment emergency. Not a diagnosis.',
    h1: 'Eye floaters & flashes',
    lede: 'Occasional floaters — small specks drifting across your vision — are usually harmless and increase with age. But a sudden shower of new floaters or flashes of light can signal a retinal detachment, a sight-threatening emergency.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about floaters',
    featTitle: 'What to know',
    features: [
      'A few floaters that drift, especially against bright backgrounds, are common',
      'They increase gradually with age and are usually harmless',
      'Flashes of light can occur as the gel inside the eye separates (often benign)',
      'The concern is a SUDDEN change — new floaters, flashes or a shadow',
    ],
    warnings: [
      'A sudden shower of new floaters, or flashes of light — urgent eye assessment',
      'A dark curtain or shadow moving across your vision — emergency (possible retinal detachment)',
      'Sudden loss of vision',
      'Floaters after an eye injury',
    ],
    noteTitle: 'A sudden change is an emergency.',
    note: 'Long-standing stable floaters are usually harmless, but a sudden increase, flashes, or a shadow across vision needs same-day eye care to prevent permanent sight loss. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Are eye floaters dangerous?', a: 'A few stable floaters are usually harmless and common with age. A sudden increase in floaters, flashes of light, or a shadow across vision is an emergency needing same-day eye care.' },
      { q: 'What causes flashes of light in the eye?', a: 'Often the gel inside the eye pulling on the retina, which can be benign — but sudden flashes with new floaters can precede a retinal detachment and need urgent review.' },
      { q: 'When should I worry about floaters?', a: 'Seek urgent eye care for a sudden shower of new floaters, flashes, a curtain/shadow over vision, or sudden vision loss.' },
    ],
    related: [['diseases/eye-floaters', 'Eye floaters'], ['diseases/retinal-detachment', 'Retinal detachment'], ['diseases/diabetic-retinopathy', 'Diabetic retinopathy'], ['eye-ent/blurred-vision-causes', 'Blurred vision']],
  },
  {
    slug: 'eye-ent/blurred-vision-causes',
    name: 'Blurred Vision: Causes',
    title: 'Blurred Vision: Common Causes & Red Flags | MedDroid',
    desc: 'Blurred vision — common causes like refractive errors, dry eye, cataract and diabetes, and the sudden changes that are emergencies. Not a diagnosis.',
    h1: 'Blurred vision: causes & red flags',
    lede: 'Blurred vision has many causes — from needing glasses or dry eyes to cataract or diabetes. Gradual blurring usually needs an eye test, but sudden blurring or vision loss is an emergency.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about blurred vision',
    featTitle: 'Common causes',
    features: [
      'Refractive error (needing glasses) — the commonest cause',
      'Dry eye or eye strain',
      'Cataract (gradual clouding, especially with age)',
      'Diabetes affecting the eyes (get sugars and eyes checked)',
      'Migraine can cause temporary visual disturbance',
    ],
    warnings: [
      'Sudden blurred vision or vision loss — emergency',
      'Blurring with weakness, slurred speech or face droop (stroke — emergency)',
      'Blurring with severe eye pain, redness, halos and nausea (acute glaucoma)',
      'A curtain/shadow, or a sudden shower of floaters/flashes',
    ],
    noteTitle: 'Sudden change = emergency.',
    note: 'Gradual blurring usually needs an eye test; sudden blurring or vision loss, or blurring with stroke signs, is an emergency. Diabetics need regular eye checks. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes blurred vision?', a: 'Most often needing glasses (refractive error), plus dry eye, cataract, diabetes and migraine. An eye test finds the cause of gradual blurring.' },
      { q: 'When is blurred vision an emergency?', a: 'Sudden blurring or vision loss, blurring with stroke signs (weakness, slurred speech), severe eye pain with halos, or a shadow/floaters/flashes — get urgent care.' },
      { q: 'Can diabetes cause blurred vision?', a: 'Yes — high blood sugar and diabetic eye disease both blur vision, so diabetics should get regular eye and sugar checks.' },
    ],
    related: [['diseases/refractive-errors', 'Refractive errors'], ['diseases/cataract', 'Cataract'], ['diseases/diabetic-retinopathy', 'Diabetic retinopathy'], ['eye-ent/eye-floaters-and-flashes', 'Floaters & flashes']],
  },
  {
    slug: 'eye-ent/how-to-improve-eyesight',
    name: 'How to Improve Eyesight',
    title: 'How to Improve Eyesight: What Works & What’s a Myth | MedDroid',
    desc: 'Can you improve eyesight naturally? The honest facts on eye exercises, diet, screens, and what actually protects vision. Not a diagnosis.',
    h1: 'How to improve eyesight',
    lede: 'It is one of the most common searches — and the honest answer is that eye exercises and home remedies cannot reverse refractive errors. But you can genuinely protect your vision and get the best from your eyes.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about eyesight',
    featTitle: 'What genuinely helps vision',
    features: [
      'Wear the correct glasses/contact lenses (they do not "weaken" eyes)',
      'A diet rich in vegetables, fruit and omega-3 supports eye health',
      'Protect eyes from the sun (UV) with sunglasses',
      'Do not smoke; control diabetes and blood pressure',
      'Regular eye checks catch problems early',
    ],
    warnings: [
      'Beware "eyesight improvement" exercises, drops or programmes promising to end glasses',
      'Sudden vision change is an emergency (not something to "exercise" away)',
      'Children: uncorrected vision can affect development — get it checked',
    ],
    noteTitle: 'Exercises don’t cure short/long sight.',
    note: 'No exercise, diet or drop reverses refractive errors — glasses, contacts or surgery correct them. What you can do is protect your eyes and detect disease early. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Can I improve my eyesight naturally?', a: 'Eye exercises and home remedies cannot reverse short- or long-sightedness. You can protect vision with a good diet, sun protection, not smoking, and regular eye checks.' },
      { q: 'Do eye exercises reduce the need for glasses?', a: 'No — despite the claims, they do not correct refractive errors. Glasses, contacts or laser surgery are the ways to correct vision.' },
      { q: 'Does wearing glasses weaken the eyes?', a: 'No — this is a myth. Correct glasses simply help you see clearly and do not make your eyes dependent or weaker.' },
    ],
    related: [['diseases/refractive-errors', 'Refractive errors'], ['diseases/cataract', 'Cataract'], ['diseases/diabetic-retinopathy', 'Diabetic retinopathy'], ['nutrition/immunity-boosting-foods', 'Diet & health']],
  },
  {
    slug: 'eye-ent/watery-eyes',
    name: 'Watery Eyes',
    title: 'Watery Eyes: Causes & What Helps | MedDroid',
    desc: 'Watery eyes — why they water (including from dryness), common causes, and when to see a doctor. Not a diagnosis.',
    h1: 'Watery eyes',
    lede: 'It seems odd, but eyes often water because they are dry or irritated — the eye over-produces reflex tears. Allergies, blocked tear ducts and infections are other causes, most of which are treatable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about watery eyes',
    featTitle: 'Common causes',
    features: [
      'Dry eye (reflex watering) — treated with lubricating drops',
      'Allergies (itchy, watery eyes) — anti-allergy drops',
      'A blocked tear duct (constant watering, especially in babies)',
      'Irritation from dust, wind or smoke',
      'Eyelid problems or infection',
    ],
    warnings: [
      'Watering with eye pain, redness or vision change',
      'A watering, sticky eye in a newborn',
      'Watering with a lump near the inner eye or swelling (possible infection)',
    ],
    noteTitle: 'Dry eyes can water too.',
    note: 'Paradoxically, dryness is a common cause of watery eyes. Most causes are treatable; pain or vision change needs review. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why do my eyes water so much?', a: 'Common causes are dry eye (reflex watering), allergies, a blocked tear duct, or irritation from wind/dust/smoke. Most are treatable.' },
      { q: 'How can dry eyes cause watering?', a: 'When the eye surface is dry or irritated, it triggers a flood of reflex tears that drain away quickly — so the eye waters yet still feels gritty.' },
      { q: 'When should watery eyes be checked?', a: 'With eye pain, redness or vision change, a sticky eye in a newborn, or a lump/swelling near the inner corner of the eye.' },
    ],
    related: [['diseases/watery-eyes', 'Watery eyes'], ['diseases/dry-eye', 'Dry eye'], ['diseases/allergic-conjunctivitis', 'Allergic conjunctivitis'], ['medicines/olopatadine-eye', 'Olopatadine (eye)']],
  },
  {
    slug: 'eye-ent/stye-treatment',
    name: 'Stye Treatment',
    title: 'Stye Treatment: How to Get Rid of an Eye Stye | MedDroid',
    desc: 'How to treat a stye — warm compresses, what not to do, and when a painful eyelid lump needs a doctor. Not a diagnosis.',
    h1: 'Stye treatment',
    lede: 'A stye is a small, painful red lump on the eyelid from a blocked, infected gland. Most clear on their own within a week or two, and warm compresses speed things up.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about a stye',
    featTitle: 'What helps',
    features: [
      'Warm compresses for 5–10 minutes, several times a day',
      'Gentle eyelid cleaning; keep the area clean',
      'Do not squeeze or pop it (spreads infection)',
      'Avoid eye make-up and contact lenses until it clears',
      'Most settle within 1–2 weeks',
    ],
    warnings: [
      'Spreading redness/swelling of the whole eyelid or face, or fever (possible cellulitis — urgent)',
      'Vision affected, or the eye itself becomes painful/red',
      'A stye that does not settle, or a painless firm lump that persists (chalazion)',
    ],
    noteTitle: 'Warm compress; don’t squeeze.',
    note: 'Most styes clear with warm compresses. Spreading facial/eyelid swelling or fever needs urgent care (it can spread). MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I get rid of a stye fast?', a: 'Apply warm compresses for 5–10 minutes several times a day, keep the eyelid clean, and avoid squeezing it or wearing eye make-up/contacts. Most clear in 1–2 weeks.' },
      { q: 'Should I pop a stye?', a: 'No — squeezing or popping can spread the infection. Let it drain on its own with the help of warm compresses.' },
      { q: 'When does a stye need a doctor?', a: 'If the whole eyelid or face swells, there is fever, vision is affected, or a firm lump (chalazion) persists after the pain settles.' },
    ],
    related: [['diseases/stye', 'Stye'], ['diseases/blepharitis', 'Blepharitis'], ['diseases/cellulitis', 'Cellulitis'], ['eye-ent/red-eye-causes', 'Red eye causes']],
  },
  {
    slug: 'eye-ent/contact-lens-safety',
    name: 'Contact Lens Safety',
    title: 'Contact Lens Safety: Avoiding Eye Infections | MedDroid',
    desc: 'Contact lens safety — how to avoid serious eye infections, hygiene rules, and the warning signs to remove lenses and see a doctor. Not a diagnosis.',
    h1: 'Contact lens safety',
    lede: 'Contact lenses are safe when used correctly, but poor hygiene can cause serious, sight-threatening eye infections. A few simple rules keep your eyes safe.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about contact lenses',
    featTitle: 'Golden rules',
    features: [
      'Wash and dry hands before handling lenses',
      'Never sleep in lenses unless they are approved for it',
      'Never use water or saliva — only fresh lens solution',
      'Replace lenses and the case as directed; do not "top up" old solution',
      'Remove lenses and swim/shower without them where possible',
    ],
    warnings: [
      'A red, painful eye with blurred vision or light sensitivity in a lens wearer — remove lenses and get urgent care (possible corneal ulcer)',
      'Persistent discomfort or a feeling something is in the eye',
      'Do not wear lenses over their replacement schedule',
    ],
    noteTitle: 'A painful red eye in a lens wearer is urgent.',
    note: 'Contact-lens-related corneal infections can threaten sight and progress fast — remove the lenses and seek same-day eye care for a painful red eye. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I avoid eye infections from contact lenses?', a: 'Wash hands first, never sleep in lenses (unless approved), never use water/saliva, use fresh solution each time, replace lenses and case on schedule, and avoid water while wearing them.' },
      { q: 'Can I sleep in my contact lenses?', a: 'Only if they are specifically approved for overnight wear. Sleeping in daily lenses greatly raises the risk of serious infection.' },
      { q: 'When should I remove my lenses and see a doctor?', a: 'Immediately for a red, painful eye with blurred vision or light sensitivity — this can be a corneal ulcer, a sight-threatening emergency.' },
    ],
    related: [['diseases/corneal-ulcer', 'Corneal ulcer'], ['diseases/conjunctivitis', 'Conjunctivitis'], ['diseases/dry-eye', 'Dry eye'], ['diseases/refractive-errors', 'Refractive errors']],
  },
  {
    slug: 'eye-ent/eye-twitching',
    name: 'Eye Twitching',
    title: 'Eye Twitching: Causes & When to Worry | MedDroid',
    desc: 'Eye twitching (eyelid myokymia) — the common harmless causes, what helps, and the rare signs that need a doctor. Not a diagnosis.',
    h1: 'Eye twitching: why it happens',
    lede: 'A twitching eyelid is very common, usually harmless, and typically triggered by tiredness, stress, caffeine or eye strain. It almost always settles on its own.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about eye twitching',
    featTitle: 'Common triggers & what helps',
    features: [
      'Tiredness and lack of sleep',
      'Stress and anxiety',
      'Too much caffeine',
      'Eye strain or dry eyes',
      'Helps: rest, less caffeine, manage stress, lubricating drops',
    ],
    warnings: [
      'Twitching spreading to other parts of the face, or the eyelid closing fully',
      'Twitching with drooping, weakness, or vision changes',
      'Twitching lasting many weeks without relief',
    ],
    noteTitle: 'Almost always harmless.',
    note: 'Eyelid twitching is usually benign and settles with rest and less caffeine. Twitching that spreads across the face or forces the eye shut needs a doctor. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why does my eye keep twitching?', a: 'Usually tiredness, stress, caffeine or eye strain. It is harmless and settles with rest, less caffeine and managing stress.' },
      { q: 'How do I stop eye twitching?', a: 'Get more sleep, cut caffeine, reduce stress, and use lubricating drops if your eyes are dry or strained. It usually resolves on its own.' },
      { q: 'When is eye twitching serious?', a: 'Rarely — if it spreads across the face, forces the eyelid fully shut, or comes with drooping, weakness or vision changes, see a doctor.' },
    ],
    related: [['eye-ent/dry-eyes-and-screen-strain', 'Dry eyes & screen strain'], ['mental-health/how-to-reduce-stress', 'Reduce stress'], ['mental-health/how-to-sleep-better', 'Sleep better'], ['diseases/bells-palsy', 'Bell’s palsy']],
  },
  {
    slug: 'eye-ent/ear-pain-causes',
    name: 'Ear Pain: Causes',
    title: 'Ear Pain: Common Causes & What Helps | MedDroid',
    desc: 'Ear pain (earache) in adults and children — common causes like infection and wax, home relief, and when to see a doctor. Not a diagnosis.',
    h1: 'Ear pain: causes & what helps',
    lede: 'Earache is common and often from an infection, wax or referred pain from the throat or teeth. Pain relief helps while it settles, and a few situations need a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about ear pain',
    featTitle: 'Common causes & relief',
    features: [
      'Middle-ear infection (common in children, often after a cold)',
      'Outer-ear infection (swimmer’s ear) — pain worse on tugging the ear',
      'Ear wax build-up or a blocked ear',
      'Referred pain from the throat, tonsils or teeth',
      'Relief: paracetamol/ibuprofen; a warm compress',
    ],
    warnings: [
      'Fluid or pus draining from the ear',
      'Swelling, redness or tenderness behind the ear (possible mastoiditis — urgent)',
      'Severe pain, high fever, or a very unwell child',
      'Sudden hearing loss or dizziness with the pain',
    ],
    noteTitle: 'Do not put objects (or oil) in the ear.',
    note: 'Pain relief helps most earaches; never poke cotton buds or pour oil into the ear canal. Discharge, swelling behind the ear, or a very unwell child needs a doctor. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes ear pain?', a: 'Common causes are middle- or outer-ear infections, wax build-up, and referred pain from the throat or teeth. Pain relief helps while it settles.' },
      { q: 'How do I relieve ear pain at home?', a: 'Paracetamol or ibuprofen (by weight for children) and a warm compress help. Do not insert cotton buds, objects or oil into the ear.' },
      { q: 'When should ear pain be checked?', a: 'With ear discharge, swelling behind the ear, severe pain or high fever, sudden hearing loss/dizziness, or in a very unwell child or young baby.' },
    ],
    related: [['diseases/ear-infection', 'Ear infection'], ['diseases/swimmers-ear', 'Swimmer’s ear'], ['child-health/ear-infection-in-children', 'Ear infection in children'], ['eye-ent/safe-ear-wax-removal', 'Ear wax removal']],
  },
  {
    slug: 'eye-ent/safe-ear-wax-removal',
    name: 'Safe Ear Wax Removal',
    title: 'How to Remove Ear Wax Safely | MedDroid',
    desc: 'How to remove ear wax safely — why cotton buds are harmful, softening drops, and when to see a doctor. Not a diagnosis.',
    h1: 'Safe ear wax removal',
    lede: 'Ear wax is normal and protective, and the ear is self-cleaning — so most people never need to remove it. When wax causes blockage, softening drops or professional removal are safe; cotton buds are not.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about ear wax',
    featTitle: 'The safe way',
    features: [
      'Do NOT use cotton buds — they push wax deeper and can damage the ear',
      'Softening drops (olive oil or over-the-counter ear drops) for a few days',
      'Wax often then comes out on its own',
      'A doctor/nurse can remove stubborn wax (irrigation/microsuction)',
      'Only clean the outer ear with a cloth',
    ],
    warnings: [
      'Ear pain, discharge, or sudden hearing loss (see a doctor)',
      'A history of a perforated eardrum or ear surgery (do not use drops/water without advice)',
      'Wax removal attempts causing pain or bleeding',
    ],
    noteTitle: 'Never use cotton buds inside the ear.',
    note: 'Cotton buds push wax deeper and can injure the eardrum. Softening drops or professional removal are the safe options. Pain, discharge or hearing loss needs a doctor. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I remove ear wax safely?', a: 'Use softening drops (olive oil or ear drops) for a few days to let wax come out naturally, and see a doctor/nurse for stubborn wax. Never use cotton buds.' },
      { q: 'Why are cotton buds bad for ears?', a: 'They push wax deeper, cause blockages, and can scratch the canal or perforate the eardrum. The ear cleans itself — only wipe the outer ear.' },
      { q: 'When should ear wax be checked?', a: 'With ear pain, discharge, sudden hearing loss, or if you have had a perforated eardrum or ear surgery (avoid drops/water without advice).' },
    ],
    related: [['diseases/ear-wax-blockage', 'Ear wax blockage'], ['diseases/hearing-loss', 'Hearing loss'], ['eye-ent/ear-pain-causes', 'Ear pain'], ['elderly-health/hearing-loss-in-elderly', 'Hearing loss in elderly']],
  },
  {
    slug: 'eye-ent/tinnitus-ringing-in-ears',
    name: 'Tinnitus (Ringing in Ears)',
    title: 'Tinnitus (Ringing in the Ears): Causes & Help | MedDroid',
    desc: 'Tinnitus — why you hear ringing or buzzing, common causes, what helps you cope, and when to see a doctor. Not a diagnosis.',
    h1: 'Tinnitus (ringing in the ears)',
    lede: 'Tinnitus is hearing a sound — ringing, buzzing or hissing — with no external source. It is very common, usually not dangerous, and often linked to hearing loss, wax or noise exposure. Several strategies help you cope.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about tinnitus',
    featTitle: 'Common causes & what helps',
    features: [
      'Hearing loss (age or noise-related) — the commonest link',
      'Ear wax, ear infections, or loud-noise exposure',
      'Some medicines, caffeine or stress can worsen it',
      'Helps: treating hearing loss, sound therapy, managing stress',
      'Protect your ears from loud noise',
    ],
    warnings: [
      'Tinnitus in only ONE ear, or pulsating (in time with your heartbeat) — see a doctor',
      'Tinnitus with sudden hearing loss or dizziness (urgent)',
      'Tinnitus severely affecting sleep or mood',
    ],
    noteTitle: 'Usually benign — but one-sided needs checking.',
    note: 'Most tinnitus is harmless and manageable, but tinnitus in one ear only, pulsating tinnitus, or tinnitus with sudden hearing loss needs medical assessment. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes ringing in the ears?', a: 'Most often hearing loss (age or noise), ear wax, infections or loud-noise exposure; stress, caffeine and some medicines can worsen it.' },
      { q: 'Is tinnitus curable?', a: 'There is often no single cure, but treating the cause (like hearing loss or wax), sound therapy and stress management help most people cope well.' },
      { q: 'When is tinnitus serious?', a: 'One-sided tinnitus, pulsating tinnitus (in time with your heartbeat), or tinnitus with sudden hearing loss or dizziness needs medical review.' },
    ],
    related: [['diseases/tinnitus', 'Tinnitus'], ['diseases/hearing-loss', 'Hearing loss'], ['diseases/menieres-disease', 'Ménière’s disease'], ['eye-ent/safe-ear-wax-removal', 'Ear wax removal']],
  },
  {
    slug: 'eye-ent/blocked-nose-and-sinusitis',
    name: 'Blocked Nose & Sinusitis',
    title: 'Blocked Nose & Sinus Infection: What Helps | MedDroid',
    desc: 'Blocked nose and sinusitis — causes, what relieves congestion and sinus pain, why antibiotics are rarely needed, and red flags. Not a diagnosis.',
    h1: 'Blocked nose & sinusitis',
    lede: 'A blocked nose and sinus pressure usually follow a cold or allergy and settle within a couple of weeks. Most sinus infections are viral, so antibiotics are rarely needed — steam, saline and decongestion help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about blocked nose',
    featTitle: 'What helps',
    features: [
      'Steam inhalation and saline nasal rinses/sprays',
      'Short-term decongestant sprays (no more than 5–7 days)',
      'Antihistamines/steroid nasal spray if allergy is the cause',
      'Pain relief for sinus pain; stay hydrated',
      'Most sinusitis is viral and does NOT need antibiotics',
    ],
    warnings: [
      'Severe headache, swelling around the eye, or vision changes (urgent)',
      'High fever, or symptoms worsening after initially improving (possible bacterial sinusitis)',
      'Symptoms lasting more than 10–14 days',
      'Do not overuse decongestant sprays (rebound blockage)',
    ],
    noteTitle: 'Most sinusitis is viral.',
    note: 'Antibiotics rarely help sinusitis, which is usually viral — steam, saline and time work. Swelling around the eye or vision changes are red flags needing urgent care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I unblock my nose?', a: 'Steam inhalation, saline rinses/sprays, and short-term decongestant sprays (max ~5–7 days) help. Treat allergy with antihistamines or a steroid nasal spray.' },
      { q: 'Do I need antibiotics for sinusitis?', a: 'Usually not — most sinusitis is viral and settles on its own. Antibiotics are only for suspected bacterial sinusitis (severe, prolonged or worsening after improvement).' },
      { q: 'Why does my nose get more blocked after using a spray?', a: 'Overusing decongestant sprays beyond about a week causes rebound congestion. Use them only short-term.' },
    ],
    related: [['diseases/sinusitis', 'Sinusitis'], ['diseases/allergic-rhinitis', 'Allergic rhinitis'], ['medicines/xylometazoline', 'Xylometazoline (nasal)'], ['medicine-for/allergy', 'Medicine for allergy']],
  },
  {
    slug: 'eye-ent/hoarse-voice-causes',
    name: 'Hoarse Voice: Causes',
    title: 'Hoarse Voice: Causes & When to Worry | MedDroid',
    desc: 'A hoarse or lost voice — common causes like laryngitis and voice overuse, what helps, and when hoarseness needs urgent checking. Not a diagnosis.',
    h1: 'Hoarse voice: causes & when to worry',
    lede: 'A hoarse voice is usually from a viral infection (laryngitis) or overusing the voice, and settles within days to a couple of weeks. But hoarseness lasting more than three weeks should always be checked.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about hoarse voice',
    featTitle: 'Common causes & what helps',
    features: [
      'Laryngitis (viral) or straining/overusing the voice',
      'Acid reflux irritating the voice box',
      'Smoking and irritants',
      'Helps: rest the voice, fluids, steam, stop smoking',
      'Avoid whispering (it strains the voice more)',
    ],
    warnings: [
      'Hoarseness lasting more than 3 weeks — see a doctor (especially smokers, to rule out cancer)',
      'Difficulty breathing or swallowing',
      'A lump in the neck, coughing up blood, or ear pain with hoarseness',
    ],
    noteTitle: 'Persistent hoarseness needs checking.',
    note: 'Most hoarseness is harmless and short-lived, but a hoarse voice lasting over three weeks — especially in a smoker — must be checked to rule out throat or voice-box cancer. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes a hoarse voice?', a: 'Most often viral laryngitis or overusing the voice, plus acid reflux, smoking and irritants. It usually settles within a couple of weeks.' },
      { q: 'How do I get my voice back?', a: 'Rest your voice (do not whisper), drink fluids, use steam, avoid smoke, and treat reflux if that is the cause. See a doctor if it lasts.' },
      { q: 'When is a hoarse voice serious?', a: 'Hoarseness lasting more than 3 weeks (especially in smokers), or with breathing/swallowing trouble, a neck lump, or coughing blood, needs prompt review.' },
    ],
    related: [['diseases/laryngitis', 'Laryngitis'], ['diseases/vocal-cord-problems', 'Vocal cord problems'], ['diseases/throat-cancer', 'Throat cancer'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)']],
  },
  {
    slug: 'eye-ent/snoring-causes-and-help',
    name: 'Snoring: Causes & Help',
    title: 'Snoring: Causes, Remedies & Sleep Apnoea | MedDroid',
    desc: 'Snoring — why it happens, what reduces it, and how to tell if it is dangerous sleep apnoea. Not a diagnosis.',
    h1: 'Snoring: causes & help',
    lede: 'Snoring is common and often harmless, caused by relaxed throat tissues vibrating during sleep. But loud snoring with pauses in breathing and daytime sleepiness can signal obstructive sleep apnoea, which needs treatment.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about snoring',
    featTitle: 'What reduces snoring',
    features: [
      'Lose excess weight (a major factor)',
      'Sleep on your side, not your back',
      'Avoid alcohol and sedatives before bed',
      'Treat nasal blockage/allergies',
      'Stop smoking',
    ],
    warnings: [
      'Loud snoring with pauses in breathing, gasping, or choking in sleep (possible sleep apnoea)',
      'Excessive daytime sleepiness, morning headaches, poor concentration',
      'Snoring with high blood pressure or heart problems',
    ],
    noteTitle: 'Snoring + breathing pauses = get tested.',
    note: 'Simple snoring is common; loud snoring with breathing pauses and daytime sleepiness suggests obstructive sleep apnoea, which raises heart and BP risks and is treatable. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I stop snoring?', a: 'Lose excess weight, sleep on your side, avoid alcohol and sedatives before bed, treat a blocked nose, and stop smoking. Persistent loud snoring should be assessed.' },
      { q: 'Is snoring dangerous?', a: 'Simple snoring usually is not, but loud snoring with pauses in breathing, gasping and daytime sleepiness can be obstructive sleep apnoea, which needs treatment.' },
      { q: 'What is sleep apnoea?', a: 'Repeated pauses in breathing during sleep that disturb rest and strain the heart. It causes daytime sleepiness and is diagnosed with a sleep study and treated (often with CPAP).' },
    ],
    related: [['diseases/obstructive-sleep-apnoea', 'Obstructive sleep apnoea'], ['diseases/sleep-apnoea', 'Sleep apnoea'], ['diseases/deviated-septum', 'Deviated septum'], ['nutrition/how-to-lose-weight-safely', 'How to lose weight safely']],
  },
  {
    slug: 'eye-ent/bad-breath-causes',
    name: 'Bad Breath: Causes',
    title: 'Bad Breath (Halitosis): Causes & How to Fix It | MedDroid',
    desc: 'Bad breath (halitosis) — the common causes (mostly the mouth), how to fix it, and when it signals something else. Not a diagnosis.',
    h1: 'Bad breath (halitosis)',
    lede: 'Bad breath usually comes from the mouth — bacteria on the tongue, gum disease or food. Good oral hygiene fixes most cases, and persistent bad breath despite this may point to another cause.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about bad breath',
    featTitle: 'Common causes & what helps',
    features: [
      'Bacteria on the tongue and teeth — brush, floss and clean the tongue',
      'Gum disease and tooth decay — see a dentist',
      'Dry mouth (less saliva) — stay hydrated',
      'Foods (onion, garlic), smoking, and skipping meals',
      'Regular dental cleaning and check-ups',
    ],
    warnings: [
      'Bad breath despite good oral care (may point to sinus, throat, stomach or other causes)',
      'Bad breath with bleeding gums, loose teeth or mouth sores',
      'A fruity breath smell in a diabetic (possible high sugar/ketones — urgent)',
    ],
    noteTitle: 'Usually the mouth — start there.',
    note: 'Most bad breath is from the mouth and improves with hygiene and dental care. Persistent bad breath, or a diabetic with fruity breath, needs medical/dental review. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes bad breath?', a: 'Usually bacteria on the tongue and teeth, gum disease, dry mouth, certain foods, or smoking. Good oral hygiene fixes most cases.' },
      { q: 'How do I get rid of bad breath?', a: 'Brush and floss twice daily, clean your tongue, stay hydrated, treat gum disease and cavities, and avoid smoking. See a dentist if it persists.' },
      { q: 'When is bad breath a sign of illness?', a: 'When it persists despite good oral care, or comes with gum bleeding or mouth sores — and a fruity breath smell in a diabetic is a warning sign needing urgent care.' },
    ],
    related: [['diseases/bad-breath', 'Bad breath'], ['diseases/gum-disease', 'Gum disease'], ['diseases/tooth-decay', 'Tooth decay'], ['diseases/dry-mouth', 'Dry mouth']],
  },
  {
    slug: 'eye-ent/ear-blockage-and-popping',
    name: 'Ear Blockage & Popping',
    title: 'Blocked Ear & Popping Sensation: What to Do | MedDroid',
    desc: 'A blocked or popping ear — causes like wax, colds, flights and altitude, how to relieve it, and when to see a doctor. Not a diagnosis.',
    h1: 'Ear blockage & popping',
    lede: 'A blocked, full or popping ear is common — often from wax, a cold blocking the tube that balances ear pressure, or changes in altitude (flights, hills). Most clear on their own or with simple measures.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about ear blockage',
    featTitle: 'Causes & what helps',
    features: [
      'Ear wax build-up — softening drops (not cotton buds)',
      'Colds/allergies blocking the Eustachian tube',
      'Altitude/flights — swallow, yawn, or gently "pop" the ears',
      'Decongestants/antihistamines if a cold or allergy is the cause',
      'Most cases settle within days to a couple of weeks',
    ],
    warnings: [
      'Sudden hearing loss (get urgent care — may be treatable)',
      'Ear pain, discharge or dizziness',
      'Blockage lasting more than 2 weeks',
    ],
    noteTitle: 'Sudden hearing loss is urgent.',
    note: 'A blocked ear is usually harmless, but sudden hearing loss (even if it feels like "blockage") needs urgent care. Never use cotton buds to unblock ears. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I unblock my ear?', a: 'For wax, use softening drops (not cotton buds). For a cold or flight, swallow, yawn or gently pop the ears, and treat congestion. Most cases clear within days.' },
      { q: 'Why does my ear feel blocked after a cold?', a: 'A cold can block the Eustachian tube that balances ear pressure, causing fullness and popping. It usually settles as the cold clears.' },
      { q: 'When should a blocked ear be checked?', a: 'With sudden hearing loss, ear pain, discharge or dizziness, or if it lasts more than 2 weeks.' },
    ],
    related: [['diseases/ear-wax-blockage', 'Ear wax blockage'], ['eye-ent/safe-ear-wax-removal', 'Ear wax removal'], ['diseases/ear-infection', 'Ear infection'], ['diseases/sinusitis', 'Sinusitis']],
  },
  {
    slug: 'eye-ent/should-tonsils-be-removed',
    name: 'Should Tonsils Be Removed?',
    title: 'Should Tonsils Be Removed? Tonsillectomy Facts | MedDroid',
    desc: 'When tonsils should (and should not) be removed — recurrent tonsillitis, sleep apnoea, and modern guidance. Not a diagnosis.',
    h1: 'Should tonsils be removed?',
    lede: 'Tonsils are removed far less often than in the past. Most sore throats and bouts of tonsillitis do not need surgery — it is reserved for frequent, severe recurrences or specific problems like sleep apnoea.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about tonsils',
    featTitle: 'When removal may be considered',
    features: [
      'Very frequent, severe tonsillitis (e.g. several well-documented episodes a year)',
      'Tonsils causing obstructive sleep apnoea or breathing problems',
      'Recurrent tonsil abscesses',
      'Most occasional sore throats and tonsillitis do NOT need surgery',
      'A specialist (ENT) weighs the benefits and risks',
    ],
    warnings: [
      'Difficulty breathing or swallowing, drooling, or a muffled voice (possible abscess — urgent)',
      'One enlarged tonsil, or a tonsil lump with weight loss (needs checking)',
      'After tonsillectomy: bleeding needs urgent care',
    ],
    noteTitle: 'Surgery is reserved for specific cases.',
    note: 'Tonsillectomy is now used mainly for frequent severe tonsillitis or sleep apnoea, decided by an ENT specialist. Occasional tonsillitis is managed without surgery. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'When do tonsils need to be removed?', a: 'Mainly for frequent, severe, well-documented tonsillitis, obstructive sleep apnoea, or recurrent tonsil abscesses — decided by an ENT specialist. Occasional tonsillitis does not need surgery.' },
      { q: 'Is tonsillectomy safe?', a: 'It is a common, generally safe operation, but like any surgery it has risks (notably bleeding), so it is reserved for cases where the benefit is clear.' },
      { q: 'Can adults have their tonsils removed?', a: 'Yes — adults with recurrent severe tonsillitis, abscesses or sleep apnoea from large tonsils can have a tonsillectomy if a specialist advises.' },
    ],
    related: [['diseases/tonsillitis', 'Tonsillitis'], ['diseases/strep-throat', 'Strep throat'], ['diseases/obstructive-sleep-apnoea', 'Sleep apnoea'], ['medicine-for/sore-throat', 'Medicine for sore throat']],
  },
  {
    slug: 'eye-ent/swimmers-ear',
    name: 'Swimmer’s Ear',
    title: 'Swimmer’s Ear (Outer Ear Infection): Care | MedDroid',
    desc: 'Swimmer’s ear (otitis externa) — why it happens, how to treat and prevent it, and when to see a doctor. Not a diagnosis.',
    h1: 'Swimmer’s ear (outer ear infection)',
    lede: 'Swimmer’s ear is an infection of the outer ear canal, common after water gets trapped or from poking the ear. The pain is worse when you tug the ear, and it usually needs medicated ear drops.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about swimmer’s ear',
    featTitle: 'Care & prevention',
    features: [
      'Keep the ear dry; do not swim until it heals',
      'Medicated ear drops (antibiotic/anti-inflammatory) from a doctor',
      'Pain relief with paracetamol or ibuprofen',
      'Do not poke or scratch the ear canal',
      'Prevent it: dry ears after swimming, avoid cotton buds',
    ],
    warnings: [
      'Spreading redness/swelling of the outer ear or face, or fever',
      'Severe pain, or hearing loss',
      'Diabetes or weak immunity with a severe ear infection (can be serious — urgent)',
    ],
    noteTitle: 'Keep it dry; see a doctor for drops.',
    note: 'Swimmer’s ear usually needs medicated ear drops and keeping the ear dry. In people with diabetes or weak immunity it can occasionally become serious, so seek care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I treat swimmer’s ear?', a: 'Keep the ear dry, use medicated ear drops from a doctor, and take pain relief. Do not swim or poke the ear until it heals.' },
      { q: 'How is swimmer’s ear different from a middle-ear infection?', a: 'Swimmer’s ear affects the outer canal — pain is worse when you tug the ear. A middle-ear infection is deeper, often after a cold, common in children.' },
      { q: 'How do I prevent swimmer’s ear?', a: 'Dry your ears after swimming, avoid cotton buds and scratching the canal, and consider ear plugs if you swim often.' },
    ],
    related: [['diseases/swimmers-ear', 'Swimmer’s ear'], ['diseases/ear-infection', 'Ear infection'], ['eye-ent/ear-pain-causes', 'Ear pain causes'], ['eye-ent/safe-ear-wax-removal', 'Ear wax removal']],
  },
];
