// First-aid guides cluster for MedDroid. Step-by-step, emergency-first guidance.
// Full page objects (same shape gen-landing's page() consumes). These follow
// standard first-aid protocols but are NOT a substitute for a first-aid course or
// emergency services — every page leads with calling for help. Educational only.

export const FIRST_AID = [
  {
    slug: 'first-aid/cpr-how-to-perform',
    name: 'How to Perform CPR',
    title: 'How to Perform CPR (Adult): Step-by-Step | MedDroid',
    desc: 'How to do CPR on an adult — check response, call for help, chest compressions and rescue breaths, and hands-only CPR. Learn the steps. Not a substitute for training.',
    h1: 'How to perform CPR (adult)',
    lede: 'CPR keeps blood and oxygen moving when someone’s heart has stopped, buying time until help arrives. If someone is unresponsive and not breathing normally, act fast — starting CPR can double their chance of survival.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about first aid',
    featTitle: 'Step-by-step (adult)',
    features: [
      '1. Check response: tap and shout. If no response, shout for help.',
      '2. Call your emergency number (or ask someone to) and get an AED if available.',
      '3. Check breathing for up to 10 seconds — if absent or gasping, start CPR.',
      '4. Push hard and fast in the centre of the chest: 30 compressions, ~5–6 cm deep, 100–120 per minute.',
      '5. Give 2 rescue breaths (if trained/willing), then continue 30:2.',
      '6. If untrained or unwilling to give breaths, do hands-only (continuous) compressions.',
      '7. Use an AED as soon as it arrives and follow its voice prompts.',
      '8. Do not stop until help takes over or the person recovers.',
    ],
    warnings: [
      'Call emergency services first (or simultaneously) — CPR alone is not enough',
      'Only stop for an AED shock or when professionals take over',
      'Push to the beat of a fast song (~100–120/min) and allow the chest to rise fully between pushes',
    ],
    noteTitle: 'Doing something beats doing nothing.',
    note: 'If you are unsure, hands-only CPR (continuous chest compressions) still saves lives. This guide is not a substitute for a hands-on first-aid course. In an emergency, call your local emergency number immediately.',
    faqs: [
      { q: 'How deep and fast should chest compressions be?', a: 'About 5–6 cm deep at 100–120 compressions per minute in the centre of the chest, letting the chest fully recoil between each push.' },
      { q: 'What if I don’t want to give mouth-to-mouth?', a: 'Hands-only CPR — continuous chest compressions without breaths — is effective for adults and is far better than doing nothing.' },
      { q: 'When do I stop CPR?', a: 'When emergency help takes over, an AED tells you to stand clear, the person starts breathing normally, or you are physically unable to continue.' },
    ],
    related: [['diseases/cardiac-arrest', 'Cardiac arrest'], ['diseases/heart-attack', 'Heart attack'], ['first-aid/choking-first-aid', 'Choking first aid'], ['first-aid/drowning-first-aid', 'Drowning first aid']],
  },
  {
    slug: 'first-aid/choking-first-aid',
    name: 'Choking First Aid',
    title: 'Choking First Aid: Back Blows & Heimlich | MedDroid',
    desc: 'What to do if someone is choking — back blows, abdominal thrusts (Heimlich), and the different steps for a baby. Step-by-step. Not a substitute for training.',
    h1: 'Choking first aid',
    lede: 'If someone can still cough or speak, encourage them to cough. If they cannot breathe, cough or speak, act immediately with back blows and abdominal thrusts — seconds matter.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about first aid',
    featTitle: 'Adult / child over 1 year',
    features: [
      '1. If they can cough, encourage coughing — do not interfere.',
      '2. If choking is severe (cannot breathe/speak), call for help.',
      '3. Give 5 sharp back blows between the shoulder blades with the heel of your hand.',
      '4. If not cleared, give 5 abdominal thrusts (Heimlich): hands above the navel, pull sharply inward and upward.',
      '5. Alternate 5 back blows and 5 abdominal thrusts until it clears.',
      '6. If they become unresponsive, call emergency services and start CPR.',
    ],
    warnings: [
      'For a baby under 1: use 5 back blows then 5 CHEST thrusts — NEVER abdominal thrusts',
      'Never do a blind finger sweep (it can push the object deeper)',
      'Anyone who received abdominal thrusts should be checked by a doctor afterwards',
      'Call emergency services if choking is severe or the person becomes unresponsive',
    ],
    noteTitle: 'Babies are different.',
    note: 'For infants under 1 year, use back blows and chest thrusts, not abdominal thrusts. This guide is not a substitute for a first-aid course. In an emergency, call your local emergency number.',
    faqs: [
      { q: 'What is the Heimlich manoeuvre?', a: 'Abdominal thrusts: stand behind the person, place a fist just above the navel, grasp it with your other hand, and pull sharply inward and upward to expel the blockage.' },
      { q: 'How is choking first aid different for a baby?', a: 'For a baby under 1, give 5 back blows (face down along your forearm) then 5 chest thrusts with two fingers — never abdominal thrusts.' },
      { q: 'What if the person becomes unconscious?', a: 'Lower them safely, call emergency services and begin CPR, checking the mouth for the object before giving breaths.' },
    ],
    related: [['first-aid/cpr-how-to-perform', 'How to perform CPR'], ['diseases/drowning', 'Drowning'], ['first-aid/anaphylaxis-first-aid', 'Anaphylaxis first aid'], ['child-health/starting-solids-for-babies', 'Starting solids (choking safety)']],
  },
  {
    slug: 'first-aid/burns-first-aid',
    name: 'Burns First Aid',
    title: 'Burns First Aid: What to Do (and Not Do) | MedDroid',
    desc: 'Burn first aid — cool the burn under running water for 20 minutes, what to cover it with, and what never to apply. Step-by-step. Not a substitute for medical care.',
    h1: 'Burns first aid',
    lede: 'The single most important step for a burn is to cool it quickly with cool running water — this limits the damage. Never put toothpaste, butter, oil or ice on a burn.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about burns',
    featTitle: 'Step-by-step',
    features: [
      '1. Stop the burning: move away from the heat source.',
      '2. Cool the burn under cool (not ice-cold) running water for at least 20 minutes.',
      '3. Remove jewellery and loose clothing near the burn (not anything stuck to it).',
      '4. Cover with cling film (laid on, not wrapped tight) or a clean, non-fluffy cloth.',
      '5. Keep the person warm and give paracetamol for pain.',
      '6. Seek medical care for anything more than a small, superficial burn.',
    ],
    warnings: [
      'NEVER apply toothpaste, butter, oil, ash or ice to a burn',
      'Do not burst blisters',
      'Get urgent care for burns to the face, hands, feet, genitals or over a joint',
      'Urgent care for large burns, deep/white/charred burns, chemical or electrical burns, or a burn in a child',
    ],
    noteTitle: 'Cool water first — home remedies harm.',
    note: 'Cooling for 20 minutes genuinely reduces burn depth. Traditional remedies like toothpaste or butter trap heat and cause infection. This is not a substitute for medical care. In an emergency, call your local emergency number.',
    faqs: [
      { q: 'How long should I cool a burn?', a: 'At least 20 minutes under cool running water, ideally within the first 3 hours of the burn. This limits the damage and eases pain.' },
      { q: 'Should I put toothpaste or butter on a burn?', a: 'No — never. They trap heat, raise infection risk and must be cleaned off later, causing more pain. Use only cool running water.' },
      { q: 'When does a burn need a doctor?', a: 'For burns larger than a coin, deep or white/charred burns, burns to the face, hands, feet, genitals or joints, chemical/electrical burns, or any burn in a child.' },
    ],
    related: [['diseases/burns', 'Burns'], ['medicines/silver-sulfadiazine', 'Silver sulfadiazine'], ['medicines/paracetamol', 'Paracetamol'], ['first-aid/electric-shock-first-aid', 'Electric shock first aid']],
  },
  {
    slug: 'first-aid/severe-bleeding-first-aid',
    name: 'Severe Bleeding First Aid',
    title: 'How to Stop Severe Bleeding (First Aid) | MedDroid',
    desc: 'First aid for severe bleeding — firm direct pressure, dressings, elevation, and when a tourniquet is used. Step-by-step. Not a substitute for emergency care.',
    h1: 'How to stop severe bleeding',
    lede: 'Heavy bleeding can be life-threatening within minutes. The key is firm, direct, continuous pressure on the wound while emergency help is on the way.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about bleeding',
    featTitle: 'Step-by-step',
    features: [
      '1. Call emergency services for severe bleeding.',
      '2. Apply firm, direct pressure on the wound with a clean cloth or dressing.',
      '3. Keep pressing — do not lift to check; add more dressings on top if it soaks through.',
      '4. If possible, raise the injured part above the level of the heart.',
      '5. Lay the person down and keep them warm (helps prevent shock).',
      '6. For a limb wound that will not stop and is life-threatening, a tourniquet above the wound is a last resort.',
    ],
    warnings: [
      'Signs of shock: pale, cold, clammy skin, fast breathing, confusion — call emergency services',
      'Do not remove an embedded object — press around it instead',
      'Keep pressure on continuously; note the time if a tourniquet is used',
    ],
    noteTitle: 'Direct pressure is the priority.',
    note: 'Firm continuous pressure stops most bleeding. Only use a tourniquet for catastrophic limb bleeding you cannot control. This is not a substitute for emergency care. In an emergency, call your local emergency number.',
    faqs: [
      { q: 'How do I stop heavy bleeding?', a: 'Apply firm, direct, continuous pressure with a clean cloth, add more on top if it soaks through (don’t remove the first), raise the part, and call emergency services.' },
      { q: 'Should I remove an object stuck in a wound?', a: 'No — leave it in place and press firmly around it, as removing it can cause worse bleeding.' },
      { q: 'When is a tourniquet used?', a: 'Only as a last resort for life-threatening limb bleeding that direct pressure cannot control. Apply above the wound, note the time, and get emergency help.' },
    ],
    related: [['diseases/shock', 'Shock'], ['first-aid/fracture-first-aid', 'Fracture first aid'], ['first-aid/nosebleed-first-aid', 'Nosebleed first aid'], ['diseases/severe-trauma', 'Severe trauma']],
  },
  {
    slug: 'first-aid/snakebite-first-aid',
    name: 'Snakebite First Aid',
    title: 'Snakebite First Aid: What to Do & Avoid | MedDroid',
    desc: 'Snakebite first aid in India — keep calm and still, immobilise the limb, get to hospital fast for antivenom, and the dangerous myths to avoid. Not a substitute for care.',
    h1: 'Snakebite first aid',
    lede: 'A snakebite is a medical emergency — the priority is reaching a hospital with antivenom quickly. Stay calm and still, and avoid the traditional remedies that do more harm than good.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about snakebite',
    featTitle: 'Step-by-step (the “do it R.I.G.H.T.” approach)',
    features: [
      '1. Reassure the person and keep them calm and as still as possible.',
      '2. Immobilise the bitten limb with a splint (like a fracture) — do not raise it high.',
      '3. Remove rings, watches and tight clothing near the bite (swelling will follow).',
      '4. Get to a hospital urgently — antivenom is the treatment.',
      '5. Note the time of the bite and the snake’s appearance (a photo from a safe distance helps).',
      '6. Keep the bite at or slightly below heart level and the person lying still.',
    ],
    warnings: [
      'Do NOT cut the wound, suck out venom, or apply a tight tourniquet',
      'Do NOT apply ice, herbs, chemicals or “snake stones”',
      'Do NOT try to catch or kill the snake',
      'Watch for: drooping eyelids, difficulty breathing/swallowing, bleeding, drowsiness — worsening emergency',
    ],
    noteTitle: 'Get to hospital fast — antivenom saves lives.',
    note: 'Old remedies (cutting, sucking, tourniquets, ice, herbal pastes) waste time and cause harm. Rapid transport to a hospital with antivenom is what saves lives. This is not a substitute for emergency care.',
    faqs: [
      { q: 'What should I do first after a snakebite?', a: 'Keep the person calm and still, immobilise the bitten limb with a splint, remove tight items, and get to a hospital urgently for antivenom.' },
      { q: 'Should I use a tourniquet or cut the bite?', a: 'No — cutting, sucking, tight tourniquets and ice are harmful and outdated. Immobilise the limb and get to hospital fast instead.' },
      { q: 'How do I know if a snake is venomous?', a: 'You often cannot tell reliably, so treat every bite as potentially serious and get medical care. Note the snake’s look from a safe distance if possible.' },
    ],
    related: [['first-aid/dog-bite-first-aid', 'Dog bite first aid'], ['diseases/anaphylaxis', 'Anaphylaxis'], ['first-aid/fracture-first-aid', 'Fracture first aid'], ['diseases/shock', 'Shock']],
  },
  {
    slug: 'first-aid/dog-bite-first-aid',
    name: 'Dog Bite First Aid',
    title: 'Dog Bite First Aid & Rabies Prevention | MedDroid',
    desc: 'Dog bite first aid — wash the wound with soap and running water for 15 minutes, and get anti-rabies vaccination urgently. Rabies is preventable but always fatal untreated.',
    h1: 'Dog bite first aid & rabies prevention',
    lede: 'Any bite or scratch from a dog (or cat, monkey or bat) can transmit rabies, which is almost always fatal once symptoms start — but completely preventable with prompt washing and vaccination.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dog bites',
    featTitle: 'Step-by-step',
    features: [
      '1. Wash the wound immediately with soap and running water for at least 15 minutes.',
      '2. Apply an antiseptic (like povidone-iodine or alcohol).',
      '3. Do not close/stitch the wound tightly (unless a doctor decides).',
      '4. Go to a doctor or hospital the same day for anti-rabies vaccination.',
      '5. You may also need rabies immunoglobulin for deep or high-risk bites.',
      '6. Check that your tetanus vaccination is up to date.',
    ],
    warnings: [
      'Rabies is preventable but almost always fatal once symptoms appear — never skip vaccination',
      'Deep bites, bites to the head/neck/hands, or an unknown/wild animal are higher risk',
      'Signs of wound infection: spreading redness, pus, fever',
      'Do not rely on traditional remedies instead of vaccination',
    ],
    noteTitle: 'Wash long, then vaccinate — same day.',
    note: 'Thorough washing plus prompt anti-rabies vaccination prevents rabies. Never wait or use only home remedies. This is not a substitute for medical care.',
    faqs: [
      { q: 'Do I need an injection after a dog bite?', a: 'Yes — wash the wound thoroughly and get anti-rabies vaccination the same day. Deep or high-risk bites may also need rabies immunoglobulin and a tetanus check.' },
      { q: 'What if the dog looks healthy or is vaccinated?', a: 'Still get medical advice and washing done — a healthy-looking animal can carry rabies, and doctors decide on vaccination based on the risk.' },
      { q: 'How long do I have to get vaccinated?', a: 'As soon as possible — ideally the same day. The vaccine works best when started promptly after exposure.' },
    ],
    related: [['diseases/rabies', 'Rabies'], ['diseases/tetanus', 'Tetanus'], ['first-aid/snakebite-first-aid', 'Snakebite first aid'], ['medicines/povidone-iodine', 'Antiseptics']],
  },
  {
    slug: 'first-aid/heat-stroke-first-aid',
    name: 'Heat Stroke First Aid',
    title: 'Heat Stroke First Aid: Cool Fast | MedDroid',
    desc: 'Heat stroke first aid — recognise the signs, move to shade, cool the body aggressively, and call for help. A medical emergency. Not a substitute for care.',
    h1: 'Heat stroke first aid',
    lede: 'Heat stroke is a life-threatening emergency where the body overheats and can no longer cool itself. In India’s summers it is common — rapid cooling while help is on the way saves lives.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about heat stroke',
    featTitle: 'Step-by-step',
    features: [
      '1. Call emergency services — heat stroke is life-threatening.',
      '2. Move the person to a cool, shaded or air-conditioned place.',
      '3. Remove excess clothing.',
      '4. Cool aggressively: wet the skin, fan them, and place cold packs on the neck, armpits and groin.',
      '5. If fully conscious, give small sips of cool water or ORS.',
      '6. Keep cooling until help arrives or the temperature comes down.',
    ],
    warnings: [
      'Warning signs: very hot skin, confusion, no sweating, fainting, seizures, rapid pulse',
      'Do NOT give fluids to someone who is drowsy or unconscious (choking risk)',
      'Heat stroke differs from heat exhaustion — it involves confusion and a very high temperature',
    ],
    noteTitle: 'Cool first, cool fast.',
    note: 'Every minute of delay in cooling increases the danger. Aggressive cooling plus emergency care is the treatment. This is not a substitute for emergency care. Call your local emergency number.',
    faqs: [
      { q: 'What is the difference between heat exhaustion and heat stroke?', a: 'Heat exhaustion causes heavy sweating, weakness and nausea but a clear mind; heat stroke adds confusion, a very high temperature and sometimes no sweating — and is a life-threatening emergency.' },
      { q: 'How do I cool someone with heat stroke?', a: 'Move them to shade, remove clothes, wet the skin and fan them, and put cold packs on the neck, armpits and groin. Call emergency services.' },
      { q: 'Should I give water?', a: 'Only small sips if they are fully awake. Never give fluids to a drowsy or unconscious person because of choking risk.' },
    ],
    related: [['diseases/heat-stroke', 'Heat stroke'], ['diseases/dehydration', 'Dehydration'], ['medicines/ors', 'ORS'], ['first-aid/fainting-first-aid', 'Fainting first aid']],
  },
  {
    slug: 'first-aid/fainting-first-aid',
    name: 'Fainting First Aid',
    title: 'Fainting First Aid: What to Do | MedDroid',
    desc: 'What to do when someone faints — lay them down, raise the legs, and the warning signs that mean it is more serious. Step-by-step. Not a substitute for care.',
    h1: 'Fainting first aid',
    lede: 'Fainting is a brief loss of consciousness from a temporary drop in blood flow to the brain. Most people recover quickly when laid flat with the legs raised — but some faints need a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fainting',
    featTitle: 'Step-by-step',
    features: [
      '1. Lay the person flat on their back.',
      '2. Raise their legs about 30 cm to help blood return to the brain.',
      '3. Loosen tight clothing and ensure fresh air.',
      '4. As they come round, keep them lying down for a few minutes before sitting up slowly.',
      '5. Give sips of water once fully alert.',
      '6. If they do not come round within a minute, call emergency services and check breathing.',
    ],
    warnings: [
      'Not waking within about a minute — call emergency services and be ready to do CPR',
      'Fainting with chest pain, palpitations, breathlessness or during exercise',
      'A fit, injury from the fall, or repeated faints',
      'Fainting in pregnancy or in an older person',
    ],
    noteTitle: 'Most faints are harmless — some are not.',
    note: 'Lying flat with legs raised usually restores consciousness quickly. Fainting with chest pain, during exercise, or that does not resolve needs urgent assessment. This is not a substitute for medical care.',
    faqs: [
      { q: 'What should I do when someone faints?', a: 'Lay them flat, raise their legs, loosen tight clothing and ensure fresh air. They usually come round within a minute — then let them get up slowly.' },
      { q: 'When is fainting serious?', a: 'If it happens during exercise, with chest pain, palpitations or breathlessness, causes a fit, or the person does not wake quickly — seek urgent care.' },
      { q: 'Should I splash water on their face?', a: 'No need — simply laying them down with legs raised and ensuring air is enough. Give water only once they are fully awake.' },
    ],
    related: [['diseases/vertigo', 'Vertigo'], ['diseases/cardiac-arrhythmia', 'Cardiac arrhythmia'], ['first-aid/heat-stroke-first-aid', 'Heat stroke first aid'], ['what-is-a-normal-heart-rate', 'Normal heart rate']],
  },
  {
    slug: 'first-aid/nosebleed-first-aid',
    name: 'Nosebleed First Aid',
    title: 'Nosebleed First Aid: How to Stop It | MedDroid',
    desc: 'How to stop a nosebleed — sit up, lean forward, pinch the soft part of the nose, and when to see a doctor. Step-by-step. Not a substitute for medical care.',
    h1: 'Nosebleed first aid',
    lede: 'Most nosebleeds come from the front of the nose and stop with simple pressure. The key is to lean forward — not back — and pinch the soft part firmly for a full 10–15 minutes.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about nosebleeds',
    featTitle: 'Step-by-step',
    features: [
      '1. Sit up and lean slightly forward (so blood does not run down the throat).',
      '2. Pinch the soft part of the nose (just below the bony bridge) firmly.',
      '3. Hold continuously for 10–15 minutes — do not keep checking.',
      '4. Breathe through the mouth; a cold pack on the bridge can help.',
      '5. After it stops, avoid blowing or picking the nose for several hours.',
    ],
    warnings: [
      'Bleeding that does not stop after 20–30 minutes of pressure — seek care',
      'Very heavy bleeding, or bleeding after a serious head/face injury',
      'Feeling faint, pale or breathless',
      'Frequent nosebleeds, or you take blood thinners',
    ],
    noteTitle: 'Lean forward, not back.',
    note: 'Tilting the head back makes you swallow blood and feel sick, and hides how much is being lost. Pressure and leaning forward stop most nosebleeds. This is not a substitute for medical care.',
    faqs: [
      { q: 'Should I tilt my head back for a nosebleed?', a: 'No — lean forward so blood drains out, not down your throat. Tilting back can make you swallow blood and vomit.' },
      { q: 'How long should I pinch my nose?', a: 'Firmly and continuously for 10–15 minutes without releasing to check. Most front-of-nose bleeds stop in this time.' },
      { q: 'When should a nosebleed be checked?', a: 'If it does not stop after 20–30 minutes, is very heavy, follows an injury, or you feel faint — or if nosebleeds are frequent, especially on blood thinners.' },
    ],
    related: [['diseases/nosebleed', 'Nosebleed (epistaxis)'], ['first-aid/severe-bleeding-first-aid', 'Severe bleeding first aid'], ['medicines/warfarin', 'Warfarin'], ['diseases/hypertension', 'Hypertension']],
  },
  {
    slug: 'first-aid/fracture-first-aid',
    name: 'Fracture & Sprain First Aid',
    title: 'Fracture First Aid: Broken Bone & Sprain | MedDroid',
    desc: 'First aid for a suspected broken bone or sprain — immobilise, support, ice, and when to go to hospital. Step-by-step. Not a substitute for medical care.',
    h1: 'Fracture & sprain first aid',
    lede: 'If you suspect a broken bone, the aim is to keep the injured part still and supported to prevent further damage and ease pain — and to know when it is an emergency.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fractures',
    featTitle: 'Step-by-step',
    features: [
      '1. Keep the person still and support the injured limb in the position found.',
      '2. Do not try to straighten or “set” the bone.',
      '3. Immobilise with a splint or padding, and support above and below the injury.',
      '4. Apply a cold pack (wrapped) to reduce swelling and pain.',
      '5. Raise the limb if possible, and give paracetamol for pain.',
      '6. Go to hospital; call emergency services for severe injuries.',
    ],
    warnings: [
      'Call emergency services for: a spine/neck/head injury, an open fracture (bone through skin), or a deformed limb',
      'Numbness, a cold or blue limb, or no pulse beyond the injury',
      'Do not move someone with a suspected spinal injury unless in danger',
      'Do not give food or drink if surgery may be needed',
    ],
    noteTitle: 'Immobilise — do not realign.',
    note: 'Splinting in the position found and getting an X-ray is safer than trying to straighten a bone. Suspected spinal injuries need special care — keep still and call for help. This is not a substitute for medical care.',
    faqs: [
      { q: 'How do I know if a bone is broken?', a: 'Severe pain, swelling, bruising, deformity, or inability to use or bear weight suggest a fracture. Only an X-ray confirms it — so get it checked.' },
      { q: 'Should I try to straighten a broken limb?', a: 'No — support it in the position found and immobilise it. Trying to realign it can worsen the injury.' },
      { q: 'Is it a sprain or a fracture?', a: 'They can feel similar. Use R.I.C.E. (rest, ice, compression, elevation) for a sprain, but if pain, swelling or inability to use it are severe, get an X-ray.' },
    ],
    related: [['diseases/bone-fracture', 'Bone fracture'], ['diseases/sports-injuries', 'Sports injuries'], ['medicines/paracetamol', 'Paracetamol'], ['first-aid/head-injury-first-aid', 'Head injury first aid']],
  },
  {
    slug: 'first-aid/electric-shock-first-aid',
    name: 'Electric Shock First Aid',
    title: 'Electric Shock First Aid: What to Do | MedDroid',
    desc: 'Electric shock first aid — switch off the power before touching the person, call for help, and check breathing. Step-by-step. Not a substitute for emergency care.',
    h1: 'Electric shock first aid',
    lede: 'With an electric shock, your first job is to make the scene safe — never touch someone who is still in contact with a live current, or you can be electrocuted too.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about electric shock',
    featTitle: 'Step-by-step',
    features: [
      '1. Switch off the power at the mains/plug before touching the person.',
      '2. If you cannot turn it off, do not touch them directly — stand on something dry and use a non-conductive object (like dry wood) to separate them from the source.',
      '3. Call emergency services.',
      '4. Check response and breathing; start CPR if they are not breathing normally.',
      '5. Treat any burns (entry and exit points) with cool water once safe.',
      '6. Keep them still if a fall or spinal injury is possible.',
    ],
    warnings: [
      'Never touch a person still in contact with a live electrical source',
      'High-voltage/overhead lines: stay far back and wait for professionals',
      'Even if they seem fine, electric shocks can cause dangerous heart-rhythm problems — get checked',
      'Watch for burns at entry and exit points',
    ],
    noteTitle: 'Make it safe first.',
    note: 'Cutting the power or safely separating the person from the source comes before first aid. Anyone who has had a significant shock should be assessed for heart-rhythm problems. This is not a substitute for emergency care.',
    faqs: [
      { q: 'What is the first thing to do for an electric shock?', a: 'Turn off the power before touching the person. If you can’t, use a dry non-conductive object to separate them from the source without touching them directly.' },
      { q: 'Do I need a doctor if I feel okay after a shock?', a: 'Yes — significant electric shocks can cause heart-rhythm problems and internal or deep burns that are not obvious, so get checked.' },
      { q: 'What if the person isn’t breathing?', a: 'Once the scene is safe, call emergency services and start CPR immediately.' },
    ],
    related: [['first-aid/cpr-how-to-perform', 'How to perform CPR'], ['first-aid/burns-first-aid', 'Burns first aid'], ['diseases/cardiac-arrest', 'Cardiac arrest'], ['diseases/cardiac-arrhythmia', 'Cardiac arrhythmia']],
  },
  {
    slug: 'first-aid/drowning-first-aid',
    name: 'Drowning First Aid',
    title: 'Drowning First Aid: Rescue & CPR | MedDroid',
    desc: 'Drowning first aid — get the person out safely, call for help, and give rescue breaths and CPR. Step-by-step. Not a substitute for emergency care.',
    h1: 'Drowning first aid',
    lede: 'In drowning, the body is starved of oxygen, so rescue breaths are especially important. But never put yourself at risk — reach or throw, don’t go, unless you are trained.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about drowning',
    featTitle: 'Step-by-step',
    features: [
      '1. Get help and get the person out of the water safely — “reach or throw, don’t go” if untrained.',
      '2. Call emergency services.',
      '3. Check breathing. If absent, give 5 initial rescue breaths, then start CPR (30 compressions : 2 breaths).',
      '4. Do not waste time trying to drain water from the lungs.',
      '5. Remove wet clothes and keep the person warm.',
      '6. Even after recovery, get them checked — water in the lungs can cause problems hours later.',
    ],
    warnings: [
      'Do not enter dangerous water yourself unless trained and safe to do so',
      'Anyone rescued from drowning should be seen by a doctor, even if they seem fine',
      'Watch for breathing difficulty, cough or drowsiness in the hours afterwards',
      'Be careful of a possible neck injury after a dive',
    ],
    noteTitle: 'Rescue breaths matter in drowning.',
    note: 'Unlike a cardiac arrest, drowning is caused by lack of oxygen, so rescue breaths are important. Never risk your own life. Get anyone rescued checked by a doctor. This is not a substitute for emergency care.',
    faqs: [
      { q: 'Should I try to get water out of the lungs?', a: 'No — do not waste time on this. Start rescue breaths and CPR; trying to “drain” water delays the treatment that actually helps.' },
      { q: 'Do I need a doctor after a near-drowning?', a: 'Yes — always. Water in the lungs can cause breathing problems hours later (“secondary drowning”), so get checked even if the person seems recovered.' },
      { q: 'How is drowning CPR different?', a: 'Because drowning is an oxygen problem, give 5 initial rescue breaths before starting the usual 30:2 CPR cycles, if you are willing and able.' },
    ],
    related: [['diseases/drowning', 'Drowning'], ['first-aid/cpr-how-to-perform', 'How to perform CPR'], ['first-aid/choking-first-aid', 'Choking first aid'], ['diseases/pneumonia', 'Pneumonia']],
  },
  {
    slug: 'first-aid/seizure-first-aid',
    name: 'Seizure First Aid',
    title: 'Seizure (Fit) First Aid: What to Do | MedDroid',
    desc: 'What to do during a seizure — protect the person, do not restrain or put anything in their mouth, time it, and when to call emergency. Not a substitute for care.',
    h1: 'Seizure (fit) first aid',
    lede: 'Watching a seizure is frightening, but most stop on their own within a couple of minutes. Your job is to keep the person safe and let it run its course — never restrain them or put anything in their mouth.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about seizures',
    featTitle: 'Step-by-step',
    features: [
      '1. Stay calm and note the time the seizure starts.',
      '2. Move nearby objects away and cushion the head.',
      '3. Do NOT restrain them or put anything in their mouth.',
      '4. Once the jerking stops, gently roll them onto their side (recovery position).',
      '5. Stay with them, reassure them, and let them recover — they may be confused.',
      '6. Call emergency services if it lasts over 5 minutes, repeats, or it is their first-ever seizure.',
    ],
    warnings: [
      'Call emergency services if a seizure lasts more than 5 minutes or one follows another',
      'A first-ever seizure, or a seizure with injury, in water, in pregnancy or with diabetes',
      'Difficulty breathing after the seizure, or not waking up',
      'Never put fingers or objects in the mouth — you cannot “swallow the tongue”',
    ],
    noteTitle: 'Protect, don’t restrain.',
    note: 'You cannot stop a seizure by holding someone down, and nothing should go in the mouth. Keep them safe, time it, and use the recovery position afterwards. This is not a substitute for medical care.',
    faqs: [
      { q: 'Should I put something in the mouth during a seizure?', a: 'No — never. It can break teeth or block the airway. The idea of “swallowing the tongue” is a myth.' },
      { q: 'When should I call an ambulance for a seizure?', a: 'If it lasts more than 5 minutes, one seizure follows another, it is their first ever, there is injury, or they do not recover normally afterwards.' },
      { q: 'What do I do after the seizure stops?', a: 'Roll them onto their side (recovery position), keep the airway clear, stay with them and reassure them as they come round confused.' },
    ],
    related: [['diseases/epilepsy', 'Epilepsy'], ['diseases/status-epilepticus', 'Status epilepticus'], ['diseases/febrile-seizures', 'Febrile seizures'], ['medicines/levetiracetam', 'Levetiracetam']],
  },
  {
    slug: 'first-aid/heart-attack-first-aid',
    name: 'Heart Attack First Aid',
    title: 'Heart Attack First Aid: Recognise & Act | MedDroid',
    desc: 'Heart attack first aid — recognise the signs, call emergency, sit and rest, and chew aspirin. Every minute counts. Not a substitute for emergency care.',
    h1: 'Heart attack first aid',
    lede: 'In a heart attack, part of the heart muscle is starved of blood — and “time is muscle”. Recognising it and calling for help immediately gives the best chance of survival.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about heart attack',
    featTitle: 'Step-by-step',
    features: [
      '1. Call emergency services immediately if you suspect a heart attack.',
      '2. Help the person sit down and rest, calm and still (a half-sitting position is often comfortable).',
      '3. If they are not allergic and it is available, have them chew one adult aspirin (300 mg).',
      '4. Loosen tight clothing.',
      '5. If they become unresponsive and stop breathing normally, start CPR.',
      '6. Note the time symptoms started.',
    ],
    warnings: [
      'Signs: central chest pain/pressure, spreading to the arm, jaw or back, with sweating, nausea or breathlessness',
      'Women, older people and those with diabetes may have subtler signs',
      'Do NOT drive yourself — call an ambulance',
      'Do not give aspirin if they are allergic to it',
    ],
    noteTitle: 'Call first — don’t wait it out.',
    note: 'Do not delay hoping it passes, and do not drive yourself. Chewed aspirin (if not allergic) can help while waiting. This is not a substitute for emergency care. Call your local emergency number.',
    faqs: [
      { q: 'What are the signs of a heart attack?', a: 'Central chest pain or pressure, often spreading to the arm, jaw, neck or back, with sweating, nausea or shortness of breath. Symptoms can be milder in women, the elderly and diabetics.' },
      { q: 'Should I take aspirin during a heart attack?', a: 'If you are not allergic and it is to hand, chewing one adult aspirin (300 mg) can help while you wait for the ambulance. Call emergency services first.' },
      { q: 'Can I drive to hospital myself?', a: 'No — call an ambulance. Paramedics can start treatment and act if the heart stops on the way.' },
    ],
    related: [['diseases/heart-attack', 'Heart attack'], ['medicines/aspirin', 'Aspirin'], ['first-aid/cpr-how-to-perform', 'How to perform CPR'], ['diseases/coronary-artery-disease', 'Coronary artery disease']],
  },
  {
    slug: 'first-aid/stroke-first-aid',
    name: 'Stroke First Aid (FAST)',
    title: 'Stroke First Aid: The FAST Test | MedDroid',
    desc: 'Stroke first aid — spot it FAST (Face, Arms, Speech, Time) and call emergency immediately. Every minute saves brain. Not a substitute for emergency care.',
    h1: 'Stroke first aid: act FAST',
    lede: 'A stroke is a “brain attack” — blood flow to part of the brain is cut off. Fast treatment can save brain tissue and prevent lasting disability, so recognising it and calling for help immediately is vital.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about stroke',
    featTitle: 'The FAST test',
    features: [
      'F — Face: ask them to smile. Does one side droop?',
      'A — Arms: can they raise both arms? Does one drift down?',
      'S — Speech: is it slurred or strange? Can they repeat a simple sentence?',
      'T — Time: if you see any of these signs, call emergency services immediately.',
      'Note the time symptoms started (it guides treatment).',
      'Keep them comfortable; do not give food, drink or medicine.',
    ],
    warnings: [
      'Any FAST sign is an emergency — call immediately, even if it seems to improve',
      'Other signs: sudden numbness/weakness on one side, sudden confusion, vision loss, severe headache, loss of balance',
      'Do not give aspirin (unlike a heart attack — a stroke can be a bleed)',
      'Do not let them “sleep it off”',
    ],
    noteTitle: 'Time lost is brain lost.',
    note: 'Clot-busting and other treatments work only within a few hours, so never wait. Do not give aspirin (a stroke may be a bleed). This is not a substitute for emergency care. Call your local emergency number.',
    faqs: [
      { q: 'What is the FAST test for stroke?', a: 'Face drooping, Arm weakness, Speech difficulty, Time to call emergency services. Any one of these signs means act immediately.' },
      { q: 'Should I give aspirin for a stroke?', a: 'No — unlike a heart attack, a stroke can be caused by bleeding, and aspirin could make it worse. Just call emergency services.' },
      { q: 'What if the symptoms go away?', a: 'Still call for help — it may have been a “mini-stroke” (TIA), which is a serious warning of a possible bigger stroke and needs urgent assessment.' },
    ],
    related: [['diseases/stroke', 'Stroke'], ['diseases/tia', 'TIA (mini-stroke)'], ['diseases/hypertension', 'Hypertension'], ['first-aid/heart-attack-first-aid', 'Heart attack first aid']],
  },
  {
    slug: 'first-aid/poisoning-first-aid',
    name: 'Poisoning First Aid',
    title: 'Poisoning First Aid: What to Do | MedDroid',
    desc: 'Poisoning first aid — call for help, do not induce vomiting, identify the substance, and what to do for swallowed, inhaled or skin poisons. Not a substitute for care.',
    h1: 'Poisoning first aid',
    lede: 'Whether it is medicine, a household chemical, a pesticide or a plant, the safest first step in poisoning is to call for expert help — and never to make the person vomit unless told to.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about poisoning',
    featTitle: 'Step-by-step',
    features: [
      '1. Call emergency services or a poison helpline immediately.',
      '2. Try to identify what, how much and when it was taken — keep the container/label.',
      '3. Do NOT make the person vomit unless a professional tells you to.',
      '4. Swallowed chemical: do not give anything unless advised.',
      '5. On the skin/eyes: remove contaminated clothing and rinse with plenty of water.',
      '6. Inhaled fumes: get them to fresh air safely; if unresponsive and not breathing, start CPR.',
    ],
    warnings: [
      'Never induce vomiting for acids, alkalis, petroleum products or if the person is drowsy',
      'Take the container or a photo of the label to hospital',
      'Watch for drowsiness, fits, vomiting or breathing difficulty',
      'Pesticide (organophosphate) poisoning is a medical emergency (specific antidotes exist)',
    ],
    noteTitle: 'Do not induce vomiting.',
    note: 'Making someone vomit can cause more harm, especially with chemicals. Get expert advice fast and bring the substance’s details. This is not a substitute for emergency care.',
    faqs: [
      { q: 'Should I make someone vomit after poisoning?', a: 'No — not unless a doctor or poison centre tells you to. Vomiting can cause more damage, especially with corrosive chemicals or petroleum products.' },
      { q: 'What information should I give the poison helpline?', a: 'What was taken, roughly how much, when, the person’s age/weight, and their symptoms. Keep the container or label to hand.' },
      { q: 'What about pesticide poisoning?', a: 'It is a medical emergency — get to hospital urgently, as specific antidotes (like atropine and pralidoxime) are needed.' },
    ],
    related: [['diseases/poisoning', 'Poisoning'], ['medicines/activated-charcoal', 'Activated charcoal'], ['medicines/pralidoxime', 'Pralidoxime'], ['medicines/naloxone', 'Naloxone']],
  },
  {
    slug: 'first-aid/anaphylaxis-first-aid',
    name: 'Anaphylaxis First Aid',
    title: 'Anaphylaxis First Aid: Severe Allergic Reaction | MedDroid',
    desc: 'Anaphylaxis first aid — use an adrenaline auto-injector immediately, call emergency, and position the person safely. Life-saving steps. Not a substitute for care.',
    h1: 'Anaphylaxis (severe allergy) first aid',
    lede: 'Anaphylaxis is a severe, rapidly worsening allergic reaction that can be fatal within minutes. Adrenaline is the only first-line treatment — use it without hesitation and call emergency services.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about anaphylaxis',
    featTitle: 'Step-by-step',
    features: [
      '1. Use an adrenaline auto-injector (EpiPen) immediately into the outer thigh.',
      '2. Call emergency services and say “anaphylaxis”.',
      '3. Lie the person flat and raise their legs (sit up only if breathing is very hard; do not stand them up).',
      '4. If no improvement after 5 minutes, give a second auto-injector if available.',
      '5. If they stop breathing, start CPR.',
      '6. Even if they recover, they must go to hospital — symptoms can return.',
    ],
    warnings: [
      'Signs: swelling of the lips/throat, difficulty breathing/wheeze, widespread hives, collapse',
      'Never delay adrenaline — antihistamines alone are NOT enough for anaphylaxis',
      'Do not let the person stand or walk (it can worsen the collapse)',
      'Always go to hospital afterwards, even if they improve',
    ],
    noteTitle: 'Adrenaline first, without delay.',
    note: 'Adrenaline is safe and life-saving in anaphylaxis; hesitation costs lives. Antihistamines and inhalers do not replace it. This is not a substitute for emergency care. Call your local emergency number.',
    faqs: [
      { q: 'How do I use an adrenaline auto-injector?', a: 'Remove the safety cap, press the tip firmly into the middle of the outer thigh (through clothing if needed) until it clicks, and hold for the stated seconds. Then call emergency services.' },
      { q: 'Can I just give antihistamines for a severe reaction?', a: 'No — antihistamines are too slow and weak for anaphylaxis. Adrenaline is the essential first treatment; give it immediately.' },
      { q: 'Do we still go to hospital if they get better?', a: 'Yes — always. Anaphylaxis can return after the adrenaline wears off, so hospital monitoring is needed.' },
    ],
    related: [['diseases/anaphylaxis', 'Anaphylaxis'], ['medicines/adrenaline-epinephrine', 'Adrenaline (EpiPen)'], ['diseases/food-allergy', 'Food allergy'], ['diseases/drug-allergy', 'Drug allergy']],
  },
  {
    slug: 'first-aid/eye-injury-first-aid',
    name: 'Eye Injury First Aid',
    title: 'Eye Injury First Aid: Chemical & Foreign Body | MedDroid',
    desc: 'Eye injury first aid — flush chemicals with water for 15–20 minutes, do not rub or remove embedded objects, and when to seek urgent care. Not a substitute for care.',
    h1: 'Eye injury first aid',
    lede: 'The eye is delicate, and the right first aid protects your sight. For chemical splashes, rinsing immediately and for long enough is the single most important thing you can do.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about eye injuries',
    featTitle: 'What to do',
    features: [
      'Chemical splash: rinse the eye with clean water for 15–20 minutes, holding the lid open, then seek urgent care.',
      'Dust/small particle: blink, or gently rinse with clean water; do not rub.',
      'Embedded/penetrating object: do NOT remove it — cover the eye without pressure and get emergency care.',
      'A blow to the eye: apply a cold pack gently and get it checked if vision is affected.',
      'Remove contact lenses before rinsing a chemical splash (if easy to do).',
    ],
    warnings: [
      'Any chemical splash, penetrating injury, or vision change is an emergency',
      'Do not rub the eye or try to remove an embedded object',
      'Do not apply pressure to an eye with a possible penetrating injury',
      'Pain, light sensitivity or persistent watering after an injury — get checked',
    ],
    noteTitle: 'For chemicals: rinse first, rinse long.',
    note: 'Immediate, prolonged rinsing limits chemical eye damage — do it before anything else, then go to hospital. Never remove an embedded object. This is not a substitute for medical care.',
    faqs: [
      { q: 'What do I do if a chemical splashes in my eye?', a: 'Rinse immediately with clean water (or saline) for 15–20 minutes, holding the eyelids open and removing contact lenses, then get urgent medical care.' },
      { q: 'Should I remove something stuck in the eye?', a: 'Only loose particles by gentle rinsing or blinking. Never try to remove an embedded or penetrating object — cover the eye and get emergency care.' },
      { q: 'Is a blow to the eye serious?', a: 'It can be. Use a gentle cold pack and get it checked if there is vision change, pain, blood in the eye, or the eye looks abnormal.' },
    ],
    related: [['diseases/conjunctivitis', 'Conjunctivitis'], ['diseases/corneal-ulcer', 'Corneal ulcer'], ['first-aid/burns-first-aid', 'Burns first aid'], ['diseases/retinal-detachment', 'Retinal detachment']],
  },
  {
    slug: 'first-aid/head-injury-first-aid',
    name: 'Head Injury First Aid',
    title: 'Head Injury First Aid: Warning Signs | MedDroid',
    desc: 'Head injury first aid — what to do after a bump to the head, the red-flag signs of a serious injury, and when to go to hospital. Not a substitute for care.',
    h1: 'Head injury first aid',
    lede: 'Most minor head bumps are harmless, but a head injury can occasionally cause bleeding or swelling inside the skull that appears hours later — so it is important to know the warning signs.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about head injuries',
    featTitle: 'What to do',
    features: [
      '1. Sit the person down and apply a cold pack to a bump to reduce swelling.',
      '2. For any bleeding, apply gentle pressure with a clean dressing.',
      '3. Let them rest and watch them closely for 24–48 hours.',
      '4. Give paracetamol for headache (avoid sedating painkillers early on).',
      '5. Wake and check a child periodically through the first night if advised.',
      '6. Do not let them play sport/drive until fully recovered.',
    ],
    warnings: [
      'Call emergency services for: loss of consciousness, a fit, repeated vomiting, or clear fluid/blood from the nose or ears',
      'Severe or worsening headache, confusion, drowsiness or being hard to wake',
      'Unequal pupils, weakness, slurred speech, or vision problems',
      'A dangerous mechanism (high fall, road accident) or a person on blood thinners',
    ],
    noteTitle: 'Watch for delayed signs.',
    note: 'Serious bleeding inside the skull can develop hours after the injury, so watch closely and seek help for any red flag. Anyone on blood thinners needs a low threshold for assessment. This is not a substitute for medical care.',
    faqs: [
      { q: 'When is a head injury serious?', a: 'Loss of consciousness, a seizure, repeated vomiting, worsening headache, confusion or drowsiness, unequal pupils, weakness, or fluid from the nose/ears all need emergency care.' },
      { q: 'Should I keep someone awake after a head injury?', a: 'They can sleep, but should be easy to rouse — check on them periodically in the first 24 hours and seek help if they become hard to wake or confused.' },
      { q: 'What is a concussion?', a: 'A temporary disturbance of brain function from a knock to the head — headache, dizziness, confusion. Rest is key, and worsening symptoms need urgent review.' },
    ],
    related: [['diseases/traumatic-brain-injury', 'Traumatic brain injury'], ['first-aid/fracture-first-aid', 'Fracture first aid'], ['medicines/paracetamol', 'Paracetamol'], ['first-aid/seizure-first-aid', 'Seizure first aid']],
  },
  {
    slug: 'first-aid/insect-sting-first-aid',
    name: 'Insect Sting & Bite First Aid',
    title: 'Bee Sting & Insect Bite First Aid | MedDroid',
    desc: 'First aid for bee stings and insect bites — remove the sting, ease pain and swelling, and spot a severe allergic reaction. Step-by-step. Not a substitute for care.',
    h1: 'Insect sting & bite first aid',
    lede: 'Most insect stings and bites cause only local pain, redness and swelling that settle in a day or two. The important thing is to watch for a severe allergic reaction, which is an emergency.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about stings and bites',
    featTitle: 'What to do',
    features: [
      '1. If a bee sting is visible, scrape it out sideways (do not pinch/squeeze it).',
      '2. Wash the area with soap and water.',
      '3. Apply a cold pack to reduce pain and swelling.',
      '4. An antihistamine and a soothing cream (like calamine) ease itching.',
      '5. Paracetamol or ibuprofen for pain.',
      '6. Keep the area clean and avoid scratching.',
    ],
    warnings: [
      'Signs of a severe allergic reaction (anaphylaxis): swelling of lips/throat, difficulty breathing, dizziness, widespread hives — use adrenaline and call emergency services',
      'A sting inside the mouth or throat (swelling can block the airway)',
      'Spreading redness, warmth, pus or fever (infection)',
      'Many stings at once, or a sting in someone with a known severe allergy',
    ],
    noteTitle: 'Watch for allergy.',
    note: 'Most stings are minor, but a severe allergic reaction is life-threatening and needs adrenaline immediately. This is not a substitute for medical care. Call your local emergency number for any breathing difficulty or swelling.',
    faqs: [
      { q: 'How do I remove a bee sting?', a: 'Scrape it out sideways with a fingernail or card rather than pinching it, which can squeeze in more venom. Then wash the area and apply a cold pack.' },
      { q: 'When is an insect sting an emergency?', a: 'If there is swelling of the lips or throat, difficulty breathing, dizziness or widespread hives — this is anaphylaxis. Use an adrenaline auto-injector and call emergency services.' },
      { q: 'What helps the itching and swelling?', a: 'A cold pack, an antihistamine, and a soothing cream like calamine. Avoid scratching to prevent infection.' },
    ],
    related: [['first-aid/anaphylaxis-first-aid', 'Anaphylaxis first aid'], ['diseases/hives-urticaria', 'Hives (urticaria)'], ['medicines/cetirizine', 'Cetirizine'], ['medicines/calamine', 'Calamine lotion']],
  },
];
