// "Medicine for [condition]" cluster for MedDroid. Ties conditions to the drug
// library. Full page objects (same shape gen-landing's page() consumes).
// SAFETY: lists COMMON medicines (OTC vs prescription) by name/class, with NO
// doses and a strong 'do not self-medicate / see a doctor' message. Antibiotics
// and prescription drugs always defer to a doctor. Educational, not a prescription.

const RX_NOTE = 'This lists medicines commonly used for this condition to help you understand your options — it is NOT a prescription. Do not self-medicate: the right choice and dose depend on the cause, your health and other medicines, and prescription drugs (especially antibiotics) need a doctor. Misusing antibiotics drives resistance.';

export const MEDICINE_FOR = [
  {
    slug: 'medicine-for/acidity',
    name: 'Medicine for Acidity',
    title: 'Best Medicine for Acidity & Heartburn | MedDroid',
    desc: 'Medicines commonly used for acidity and heartburn — antacids, H2 blockers and PPIs — how they differ, and when to see a doctor. Not a prescription.',
    h1: 'Medicine for acidity & heartburn',
    lede: 'Acidity and heartburn are usually treated in steps — quick-acting antacids for occasional symptoms, and acid-reducers (H2 blockers or PPIs) for more frequent problems. Diet and habits matter just as much.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about acidity',
    featTitle: 'How the options differ',
    features: [
      'Antacids: neutralise acid for fast, short relief',
      'H2 blockers: reduce acid for a few hours',
      'PPIs: strongly reduce acid for lasting control',
      'Lifestyle and diet changes reduce how much medicine you need',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Antacid gels/tablets (magaldrate, calcium/magnesium salts)', 'H2 blocker: famotidine', 'PPI: omeprazole (OTC in some places)'] },
      { title: 'Prescription / doctor-guided options', items: ['PPIs: pantoprazole, rabeprazole, esomeprazole', 'Prokinetics (with bloating): domperidone', 'Ulcer treatment (H. pylori) if needed'] },
    ],
    warnings: [
      'Difficulty swallowing, weight loss, black stools or vomiting blood — see a doctor',
      'Chest pain (rule out the heart)',
      'Needing acid medicine daily for weeks — get assessed',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for acidity?', a: 'For occasional acidity, an antacid or famotidine helps fast. For frequent symptoms, a PPI like pantoprazole or omeprazole works better — alongside diet changes. See a doctor if it persists.' },
      { q: 'Antacid or PPI — which should I take?', a: 'Antacids give quick, short relief; PPIs give stronger, longer control for frequent acidity. A pharmacist or doctor can guide you.' },
      { q: 'Is it safe to take acidity medicine daily?', a: 'Short courses are fine, but daily long-term use should be reviewed by a doctor to check the cause and avoid side effects.' },
    ],
    related: [['medicines/pantoprazole', 'Pantoprazole'], ['medicines/omeprazole', 'Omeprazole'], ['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['nutrition/diet-for-acidity', 'Diet for acidity']],
  },
  {
    slug: 'medicine-for/gas-and-bloating',
    name: 'Medicine for Gas & Bloating',
    title: 'Medicine for Gas & Bloating | MedDroid',
    desc: 'Medicines commonly used for gas and bloating — simethicone, antacid combinations, prokinetics — plus diet tips, and when to see a doctor. Not a prescription.',
    h1: 'Medicine for gas & bloating',
    lede: 'Trapped wind and bloating are common and usually harmless. Simple anti-gas medicines and diet changes help most people — but persistent bloating with other symptoms deserves a check.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about gas & bloating',
    featTitle: 'What helps',
    features: [
      'Anti-gas agents break up trapped wind',
      'Prokinetics help the stomach empty when there is fullness',
      'Diet: eat slowly, cut fizzy drinks and gas-forming foods',
      'Probiotics/fibre may help some people',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Simethicone (anti-gas)', 'Antacid + simethicone combinations', 'Probiotics'] },
      { title: 'Prescription / doctor-guided options', items: ['Prokinetics: itopride, levosulpiride', 'Antispasmodics for cramps: dicyclomine, drotaverine, mebeverine'] },
    ],
    warnings: [
      'Persistent bloating with weight loss, blood in stool, or a change in bowel habit — see a doctor',
      'Severe or worsening abdominal pain',
      'Bloating with vomiting and no passing of gas/stool',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What medicine helps with gas?', a: 'Simethicone breaks up trapped gas and is available over the counter. Prokinetics and antispasmodics help when there is fullness or cramping — guided by a doctor.' },
      { q: 'Why do I feel bloated so often?', a: 'Common causes are eating quickly, fizzy drinks, gas-forming foods, constipation or IBS. Persistent bloating with other symptoms should be checked.' },
      { q: 'Do probiotics help bloating?', a: 'They help some people, especially with IBS or after antibiotics, alongside diet changes.' },
    ],
    related: [['medicines/simethicone', 'Simethicone'], ['medicines/itopride', 'Itopride'], ['diseases/irritable-bowel-syndrome-ibs', 'IBS'], ['nutrition/gut-health-foods', 'Gut health foods']],
  },
  {
    slug: 'medicine-for/cold-and-cough',
    name: 'Medicine for Cold & Cough',
    title: 'Medicine for Cold & Cough: What Actually Helps | MedDroid',
    desc: 'Medicines for cold and cough — what helps a dry vs chesty cough, why antibiotics do not work for colds, and safe options. Not a prescription.',
    h1: 'Medicine for cold & cough',
    lede: 'Colds are viral, so antibiotics do not help — treatment is about easing symptoms while your body recovers. The right cough medicine depends on whether the cough is dry or chesty.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about cold & cough',
    featTitle: 'What to know',
    features: [
      'Antibiotics do NOT help a normal cold (it is viral)',
      'Dry, tickly cough: a suppressant may help',
      'Chesty cough with mucus: a mucolytic/expectorant helps clear it',
      'Rest, fluids, steam and saline nose drops help a lot',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Paracetamol for fever/aches', 'Antihistamines for runny nose (cetirizine, chlorpheniramine)', 'Dry cough: dextromethorphan or butamirate', 'Chesty cough: bromhexine, ambroxol, guaifenesin', 'Saline nose drops; short-term decongestant sprays'] },
      { title: 'Not usually needed', items: ['Antibiotics (only if a doctor finds a bacterial infection)', 'OTC cough/cold syrups in young children (not advised under ~6 years)'] },
    ],
    warnings: [
      'Breathing difficulty, chest pain, or a high persistent fever',
      'A cough lasting more than 3 weeks, or coughing up blood',
      'Cough & cold medicines are not advised for young children — see a doctor',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for cold and cough?', a: 'For a cold: rest, fluids, paracetamol and an antihistamine for a runny nose. For cough, match the medicine to the type — a suppressant for a dry cough, a mucolytic for a chesty one.' },
      { q: 'Do I need antibiotics for a cold?', a: 'No — colds are viral and antibiotics do not help. They are only useful if a doctor diagnoses a bacterial infection.' },
      { q: 'Can I give cough syrup to my child?', a: 'Over-the-counter cough and cold medicines are not advised for children under about 6. Use fluids, saline drops and honey (over age 1), and see a doctor.' },
    ],
    related: [['diseases/common-cold-flu', 'Common cold & flu'], ['medicines/cetirizine', 'Cetirizine'], ['medicines/dextromethorphan', 'Dextromethorphan'], ['child-health/cough-and-cold-in-children', 'Cough & cold in children']],
  },
  {
    slug: 'medicine-for/fever',
    name: 'Medicine for Fever',
    title: 'Medicine for Fever: What to Take | MedDroid',
    desc: 'Medicines for fever — paracetamol and ibuprofen, how to use them safely, and when a fever needs a doctor. Not a prescription.',
    h1: 'Medicine for fever',
    lede: 'Fever is a natural response to infection and does not always need treating — the aim is comfort. Paracetamol is the usual first choice; ibuprofen is an alternative. What matters most is watching for warning signs.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fever',
    featTitle: 'What to know',
    features: [
      'Paracetamol is the usual first choice for fever',
      'Ibuprofen is an alternative (take with food; avoid if dehydrated)',
      'Do not combine products that both contain paracetamol',
      'Fluids and rest matter as much as medicine',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Paracetamol', 'Ibuprofen (with food)'] },
      { title: 'What to avoid', items: ['Aspirin in children/teens (Reye’s syndrome)', 'Exceeding the daily paracetamol limit', 'Antibiotics unless a doctor finds a bacterial cause'] },
    ],
    warnings: [
      'Any fever in a baby under 3 months — urgent',
      'Fever with a stiff neck, non-fading rash, breathing difficulty or confusion',
      'Fever above 40°C, or lasting more than 3 days',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for fever?', a: 'Paracetamol is usually first choice for comfort, with ibuprofen as an alternative (with food). Fluids and rest help too. Treat the person, not just the number.' },
      { q: 'Paracetamol or ibuprofen for fever?', a: 'Either works; paracetamol is gentler on the stomach and safer if dehydrated, while ibuprofen also reduces inflammation. A pharmacist can advise.' },
      { q: 'When does a fever need a doctor?', a: 'Any fever under 3 months of age, or with a stiff neck, non-fading rash, breathing trouble, confusion, or lasting more than 3 days.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/ibuprofen', 'Ibuprofen'], ['how-to-reduce-fever-at-home', 'How to reduce fever'], ['is-my-fever-serious', 'Is my fever serious?']],
  },
  {
    slug: 'medicine-for/body-pain',
    name: 'Medicine for Body Pain',
    title: 'Medicine for Body Pain & Aches | MedDroid',
    desc: 'Medicines for body pain and aches — paracetamol, anti-inflammatories, and muscle relaxants — how to choose and use safely. Not a prescription.',
    h1: 'Medicine for body pain & aches',
    lede: 'For everyday aches, paracetamol is a safe first step, and anti-inflammatory painkillers (NSAIDs) help when there is inflammation. The right choice depends on the cause and your health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about body pain',
    featTitle: 'What to know',
    features: [
      'Paracetamol: safe first choice for general aches',
      'NSAIDs (ibuprofen, diclofenac, naproxen): good for inflammatory pain, take with food',
      'Topical gels are gentler on the stomach for local pain',
      'Persistent pain needs its cause found, not just masked',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Paracetamol', 'Ibuprofen / diclofenac gel (topical)', 'Combination (ibuprofen + paracetamol)'] },
      { title: 'Prescription / doctor-guided options', items: ['Stronger NSAIDs (etoricoxib, aceclofenac)', 'Muscle relaxants for spasm (short-term)', 'Nerve-pain medicines for nerve pain (pregabalin, gabapentin)'] },
    ],
    warnings: [
      'Pain with fever and a very unwell feeling',
      'Chest, severe abdominal, or one-sided limb pain (get checked)',
      'NSAIDs: avoid with ulcers, kidney or significant heart disease',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for body pain?', a: 'Paracetamol is a safe first choice; anti-inflammatories like ibuprofen help inflammatory pain (with food). Topical gels suit local pain. The best choice depends on the cause.' },
      { q: 'Which is safer, paracetamol or ibuprofen?', a: 'Paracetamol is generally gentler on the stomach and kidneys; ibuprofen (an NSAID) also reduces inflammation but needs caution with ulcers, kidney or heart disease.' },
      { q: 'When should body pain be checked?', a: 'If it is severe, persistent, comes with fever or feeling very unwell, or is chest/abdominal/one-sided limb pain — see a doctor.' },
    ],
    related: [['medicines/paracetamol', 'Paracetamol'], ['medicines/ibuprofen', 'Ibuprofen'], ['medicines/diclofenac', 'Diclofenac'], ['diseases/viral-fever', 'Viral fever']],
  },
  {
    slug: 'medicine-for/headache',
    name: 'Medicine for Headache',
    title: 'Medicine for Headache: What to Take | MedDroid',
    desc: 'Medicines for headache — simple painkillers, when it is a migraine, and the danger signs that need urgent care. Not a prescription.',
    h1: 'Medicine for headache',
    lede: 'Most headaches are tension-type and ease with simple painkillers, rest and hydration. Migraines need a different approach, and a few "red-flag" headaches need urgent care.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about headache',
    featTitle: 'What to know',
    features: [
      'Tension headache: paracetamol or an NSAID, rest, water',
      'Migraine: NSAIDs or specific migraine tablets (triptans)',
      'Do not overuse painkillers (can cause rebound headaches)',
      'Treat causes: dehydration, eye strain, stress, poor sleep',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Paracetamol', 'Ibuprofen / other NSAIDs', 'Caffeine-containing combinations (limited use)'] },
      { title: 'Prescription / doctor-guided options', items: ['Triptans for migraine (sumatriptan, rizatriptan)', 'Migraine preventers (propranolol, flunarizine, amitriptyline, topiramate)'] },
    ],
    warnings: [
      'A sudden "worst-ever" or thunderclap headache — emergency',
      'Headache with fever and a stiff neck, or a rash',
      'Headache with weakness, confusion, vision loss or after a head injury',
      'A new headache in someone over 50, or one that keeps worsening',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for a headache?', a: 'For a tension headache, paracetamol or ibuprofen with rest and water usually helps. Migraines may need NSAIDs or triptans. Avoid overusing painkillers.' },
      { q: 'When is a headache dangerous?', a: 'A sudden "worst-ever" headache, or one with fever and stiff neck, weakness, confusion, vision loss, or after a head injury, needs urgent care.' },
      { q: 'Why do I get headaches from painkillers?', a: 'Using painkillers too often (medication-overuse headache) can cause more headaches. Limit acute treatment days and consider prevention for frequent headaches.' },
    ],
    related: [['symptoms/headache', 'Headache'], ['medicines/paracetamol', 'Paracetamol'], ['medicine-for/migraine', 'Medicine for migraine'], ['diseases/tension-headache', 'Tension headache']],
  },
  {
    slug: 'medicine-for/migraine',
    name: 'Medicine for Migraine',
    title: 'Medicine for Migraine: Relief & Prevention | MedDroid',
    desc: 'Medicines for migraine — what stops an attack (triptans, NSAIDs) and what prevents frequent migraines, plus when to see a doctor. Not a prescription.',
    h1: 'Medicine for migraine',
    lede: 'Migraine medicines fall into two groups: those that stop an attack once it starts, and those taken daily to prevent frequent attacks. The best plan depends on how often and how severe your migraines are.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about migraine',
    featTitle: 'What to know',
    features: [
      'Acute (to stop an attack): take early for best effect',
      'Preventive (daily): considered when attacks are frequent',
      'Anti-sickness medicine can help nausea during attacks',
      'Avoid overusing acute painkillers/triptans (rebound headache)',
    ],
    lists: [
      { title: 'To stop an attack', items: ['NSAIDs (ibuprofen, naproxen) or paracetamol', 'Triptans (sumatriptan, rizatriptan, zolmitriptan)', 'Anti-sickness medicine for nausea'] },
      { title: 'To prevent frequent migraines (doctor-guided)', items: ['Propranolol, flunarizine', 'Amitriptyline, topiramate', 'Newer preventives in some cases'] },
    ],
    warnings: [
      'A sudden "worst-ever" headache, or one very different from your usual migraine — emergency',
      'Migraine with new weakness, speech or vision loss that does not fully recover',
      'Triptans are avoided in uncontrolled heart disease',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine to stop a migraine?', a: 'Taken early, an NSAID (or paracetamol) helps milder attacks; triptans like sumatriptan are specific migraine medicines for moderate-severe attacks. Anti-sickness medicine helps nausea.' },
      { q: 'How do I prevent frequent migraines?', a: 'Daily preventers (like propranolol, flunarizine, amitriptyline or topiramate) are considered when attacks are frequent — a doctor tailors these.' },
      { q: 'Can migraine tablets cause more headaches?', a: 'Yes — overusing acute painkillers or triptans can cause medication-overuse headache. Limit acute treatment days and consider prevention.' },
    ],
    related: [['diseases/migraine', 'Migraine'], ['medicines/sumatriptan', 'Sumatriptan'], ['medicines/flunarizine', 'Flunarizine'], ['medicine-for/headache', 'Medicine for headache']],
  },
  {
    slug: 'medicine-for/allergy',
    name: 'Medicine for Allergy',
    title: 'Medicine for Allergy (Sneezing & Runny Nose) | MedDroid',
    desc: 'Medicines for allergy — non-drowsy antihistamines, nasal sprays, and what helps hay fever and allergic rhinitis. Not a prescription.',
    h1: 'Medicine for allergy',
    lede: 'Allergies like hay fever and dust allergy respond well to antihistamines and steroid nasal sprays. Newer antihistamines cause little drowsiness, and avoiding triggers helps too.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about allergy',
    featTitle: 'What to know',
    features: [
      'Antihistamines relieve sneezing, itching and a runny nose',
      'Newer ones (fexofenadine, loratadine, bilastine) are non-drowsy',
      'Steroid nasal sprays are best for a blocked, congested nose',
      'Avoiding triggers (dust, pollen, pets) reduces symptoms',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Non-drowsy antihistamines: cetirizine, levocetirizine, fexofenadine, loratadine', 'Steroid nasal sprays (in some places): fluticasone, mometasone', 'Antihistamine eye drops for itchy eyes'] },
      { title: 'Add-on / doctor-guided', items: ['Montelukast for allergic rhinitis with asthma', 'Short courses for severe flare-ups'] },
    ],
    warnings: [
      'Swelling of the lips/throat or breathing difficulty (severe allergy) — emergency',
      'Wheezing or breathlessness (possible asthma)',
      'Do not overuse decongestant nasal sprays (rebound congestion)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best allergy medicine?', a: 'Non-drowsy antihistamines like fexofenadine, cetirizine or loratadine work well for sneezing and itching; a steroid nasal spray is best for a blocked nose.' },
      { q: 'Which antihistamine is non-drowsy?', a: 'Fexofenadine, loratadine and bilastine are the least sedating; cetirizine and levocetirizine are usually low-drowsiness.' },
      { q: 'When is an allergy an emergency?', a: 'Swelling of the lips or throat, difficulty breathing or collapse is anaphylaxis — use adrenaline and call emergency services.' },
    ],
    related: [['diseases/allergic-rhinitis', 'Allergic rhinitis'], ['medicines/cetirizine', 'Cetirizine'], ['medicines/fexofenadine', 'Fexofenadine'], ['first-aid/anaphylaxis-first-aid', 'Anaphylaxis first aid']],
  },
  {
    slug: 'medicine-for/skin-allergy-and-itching',
    name: 'Medicine for Skin Allergy & Itching',
    title: 'Medicine for Skin Allergy, Hives & Itching | MedDroid',
    desc: 'Medicines for skin allergy, hives and itching — antihistamines, soothing creams, and when itching needs a doctor. Not a prescription.',
    h1: 'Medicine for skin allergy & itching',
    lede: 'Itchy skin, hives and allergic rashes usually settle with antihistamines and soothing creams. Identifying and avoiding the trigger is key, and some rashes need a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about skin allergy',
    featTitle: 'What to know',
    features: [
      'Antihistamines reduce itching and hives',
      'Calamine and moisturisers soothe irritated skin',
      'Short courses of steroid cream for inflamed patches (doctor-guided)',
      'Avoid the trigger and do not scratch (it worsens it)',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Antihistamines: cetirizine, levocetirizine, fexofenadine', 'Calamine lotion; moisturisers', 'Mild steroid cream (in some places)'] },
      { title: 'Prescription / doctor-guided options', items: ['Stronger steroid creams (betamethasone, clobetasol) — short-term', 'Tacrolimus cream for eczema', 'Treatment for the cause (infection, scabies, drug allergy)'] },
    ],
    warnings: [
      'Swelling of the lips/throat or breathing difficulty — emergency (anaphylaxis)',
      'Widespread blistering, peeling skin or a rash with fever',
      'A rash that does not fade under pressure with fever (meningitis red flag)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What medicine stops itching?', a: 'Antihistamines (like cetirizine or fexofenadine) reduce allergic itching and hives, and calamine or moisturisers soothe the skin. Inflamed patches may need a short course of steroid cream.' },
      { q: 'What is the best cream for skin allergy?', a: 'Calamine and moisturisers soothe mild cases; steroid creams help inflamed patches but should be used briefly and, for stronger ones, on a doctor’s advice.' },
      { q: 'When should itching be checked?', a: 'If it is widespread, with blistering or fever, does not settle, or comes with swelling or breathing difficulty (an emergency).' },
    ],
    related: [['diseases/hives-urticaria', 'Hives (urticaria)'], ['medicines/cetirizine', 'Cetirizine'], ['medicines/calamine', 'Calamine lotion'], ['diseases/eczema', 'Eczema']],
  },
  {
    slug: 'medicine-for/loose-motion',
    name: 'Medicine for Loose Motion',
    title: 'Medicine for Loose Motion (Diarrhoea) | MedDroid',
    desc: 'Medicines for loose motion — ORS and zinc first, when anti-diarrhoeals are safe, and when antibiotics are needed. Not a prescription.',
    h1: 'Medicine for loose motion (diarrhoea)',
    lede: 'The most important "medicine" for loose motion is ORS to prevent dehydration. Most cases are viral and settle on their own — anti-diarrhoeals and antibiotics are only for specific situations.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about loose motion',
    featTitle: 'What to know',
    features: [
      'ORS is the mainstay — replaces lost fluids and salts',
      'Zinc helps children recover faster',
      'Continue eating bland food; keep breastfeeding',
      'Most cases do NOT need antibiotics',
    ],
    lists: [
      { title: 'Commonly used', items: ['ORS (oral rehydration salts)', 'Zinc (for children)', 'Probiotics', 'Racecadotril (reduces fluid loss)'] },
      { title: 'Only when appropriate (doctor-guided)', items: ['Loperamide for adults (NOT with blood/high fever, and not for young children)', 'Antibiotics only for specific bacterial/parasitic infections'] },
    ],
    warnings: [
      'Signs of dehydration: little urine, sunken eyes, drowsiness',
      'Blood or mucus in the stool, or high fever',
      'Diarrhoea lasting more than a few days, or in a baby/elderly person',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for loose motion?', a: 'ORS to prevent dehydration is the key treatment, plus zinc for children. Most cases are viral and need no antibiotics; loperamide may help adults but not with blood or high fever.' },
      { q: 'Should I take antibiotics for loose motion?', a: 'Usually not — most diarrhoea is viral. Antibiotics are only for specific bacterial or parasitic infections diagnosed by a doctor.' },
      { q: 'Is loperamide safe?', a: 'For simple adult diarrhoea it can help, but avoid it if there is blood or high fever, and do not give it to young children.' },
    ],
    related: [['medicines/ors', 'ORS'], ['medicines/zinc', 'Zinc'], ['diseases/gastroenteritis', 'Gastroenteritis'], ['how-to-stop-diarrhea', 'How to stop diarrhoea']],
  },
  {
    slug: 'medicine-for/vomiting',
    name: 'Medicine for Vomiting',
    title: 'Medicine for Vomiting & Nausea | MedDroid',
    desc: 'Medicines for vomiting and nausea — anti-sickness options, rehydration, and when vomiting needs a doctor. Not a prescription.',
    h1: 'Medicine for vomiting & nausea',
    lede: 'For most vomiting, sips of fluid or ORS and rest are enough. Anti-sickness medicines help in some situations, but the cause matters — and persistent vomiting needs a doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about vomiting',
    featTitle: 'What to know',
    features: [
      'Small, frequent sips of fluid or ORS prevent dehydration',
      'Anti-sickness medicines can help but need care in children',
      'Ginger and rest help mild nausea',
      'Treat the cause (infection, motion sickness, pregnancy)',
    ],
    lists: [
      { title: 'Commonly used (doctor-guided)', items: ['Ondansetron (strong anti-sickness)', 'Domperidone (nausea with bloating)', 'Doxylamine + B6 for pregnancy nausea', 'Antihistamines for motion sickness (dimenhydrinate, meclizine)'] },
      { title: 'First, always', items: ['ORS / rehydration', 'Rest and small sips'] },
    ],
    warnings: [
      'Green (bile) or blood-stained vomit',
      'Signs of dehydration, or unable to keep any fluids down',
      'Vomiting with severe tummy pain, stiff neck, or after a head injury',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What medicine stops vomiting?', a: 'Ondansetron and domperidone are commonly used anti-sickness medicines, but the cause matters and children need caution. Rehydration with ORS comes first.' },
      { q: 'What can I take for vomiting in pregnancy?', a: 'Doxylamine with vitamin B6 is considered safe for pregnancy nausea; severe vomiting needs a doctor. Ginger and small frequent meals also help.' },
      { q: 'When is vomiting serious?', a: 'Green or bloody vomit, dehydration, inability to keep fluids down, severe pain, stiff neck, or vomiting after a head injury all need urgent care.' },
    ],
    related: [['medicines/ondansetron', 'Ondansetron'], ['medicines/domperidone', 'Domperidone'], ['medicines/ors', 'ORS'], ['child-health/baby-vomiting-when-to-worry', 'Baby vomiting']],
  },
  {
    slug: 'medicine-for/constipation',
    name: 'Medicine for Constipation',
    title: 'Medicine for Constipation: Laxatives Explained | MedDroid',
    desc: 'Medicines for constipation — fibre, osmotic and stimulant laxatives, how they differ, and when to see a doctor. Not a prescription.',
    h1: 'Medicine for constipation',
    lede: 'Constipation usually improves with more fluids, fibre and activity. When a laxative is needed, gentler types (fibre and osmotic) are preferred for regular use, with stimulant laxatives kept short-term.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about constipation',
    featTitle: 'What to know',
    features: [
      'First: more water, fibre, fruit and activity',
      'Fibre (bulk) laxatives: gentle, for regular use with water',
      'Osmotic laxatives (lactulose, PEG): draw water into the bowel',
      'Stimulant laxatives (senna, bisacodyl): short-term only',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Ispaghula/psyllium (fibre)', 'Lactulose, polyethylene glycol (PEG) — osmotic', 'Senna, bisacodyl — stimulant (short-term)', 'Glycerine suppositories'] },
      { title: 'Doctor-guided', items: ['Treatment of an underlying cause', 'Newer prescription options for chronic constipation'] },
    ],
    warnings: [
      'Constipation with severe pain, vomiting and a swollen belly (possible obstruction)',
      'Blood in the stool, or unexplained weight loss',
      'A sudden change in bowel habit, especially over 50',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best laxative for constipation?', a: 'Fibre and osmotic laxatives (like ispaghula, lactulose or PEG) are gentle and suit regular use; stimulant laxatives (senna, bisacodyl) work faster but are for short-term use.' },
      { q: 'Are laxatives safe for daily use?', a: 'Gentle fibre and osmotic laxatives can be used longer term under guidance; stimulant laxatives are best short-term. Diet and fluids should come first.' },
      { q: 'When should constipation be checked?', a: 'With severe pain and vomiting, blood in the stool, weight loss, or a new change in bowel habit — especially over 50.' },
    ],
    related: [['diseases/constipation', 'Constipation'], ['medicines/lactulose', 'Lactulose'], ['medicines/polyethylene-glycol', 'PEG (laxative)'], ['nutrition/gut-health-foods', 'Gut health foods']],
  },
  {
    slug: 'medicine-for/sore-throat',
    name: 'Medicine for Sore Throat',
    title: 'Medicine for Sore Throat: What Helps | MedDroid',
    desc: 'Medicines for a sore throat — pain relief, lozenges and gargles, and why most sore throats do not need antibiotics. Not a prescription.',
    h1: 'Medicine for sore throat',
    lede: 'Most sore throats are viral and settle within a week — treatment is about easing the pain. Antibiotics are only needed for a confirmed bacterial (strep) throat.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sore throat',
    featTitle: 'What to know',
    features: [
      'Pain relief: paracetamol or ibuprofen',
      'Warm salt-water gargles and soothing lozenges',
      'Warm fluids, honey (over age 1) and rest',
      'Antibiotics only for confirmed strep throat',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Paracetamol / ibuprofen', 'Medicated lozenges and throat sprays', 'Salt-water gargles'] },
      { title: 'Only if needed (doctor-guided)', items: ['Antibiotics (amoxicillin, etc.) for confirmed strep throat'] },
    ],
    warnings: [
      'Difficulty breathing or swallowing, or drooling',
      'A sore throat with a high fever and no cough (possible strep — get tested)',
      'A sore throat lasting more than a week, or a lump in the neck',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for a sore throat?', a: 'Pain relief with paracetamol or ibuprofen, plus soothing lozenges and salt-water gargles. Most sore throats are viral and do not need antibiotics.' },
      { q: 'Do I need antibiotics for a sore throat?', a: 'Only if it is a confirmed bacterial (strep) throat — a sudden severe sore throat with fever and no cough. A throat swab confirms it.' },
      { q: 'When is a sore throat serious?', a: 'Difficulty breathing or swallowing, drooling, a very high fever, or a sore throat lasting more than a week need medical review.' },
    ],
    related: [['diseases/pharyngitis-sore-throat', 'Pharyngitis (sore throat)'], ['diseases/strep-throat', 'Strep throat'], ['medicines/paracetamol', 'Paracetamol'], ['diseases/tonsillitis', 'Tonsillitis']],
  },
  {
    slug: 'medicine-for/toothache',
    name: 'Medicine for Toothache',
    title: 'Medicine for Toothache: Pain Relief | MedDroid',
    desc: 'Medicines for toothache — pain relief that works, why you still need a dentist, and when swelling is an emergency. Not a prescription.',
    h1: 'Medicine for toothache',
    lede: 'Painkillers can control toothache, but they treat the pain, not the cause — you still need a dentist. Anti-inflammatories often work well for dental pain, and facial swelling needs urgent care.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about toothache',
    featTitle: 'What to know',
    features: [
      'NSAIDs (ibuprofen) often work well for dental pain (with food)',
      'Paracetamol as an alternative or in combination',
      'Salt-water rinses and a clove/benzocaine gel can soothe',
      'See a dentist — painkillers do not fix the cause',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Ibuprofen / other NSAIDs', 'Paracetamol', 'Numbing dental gel (benzocaine)'] },
      { title: 'Only if a dentist/doctor advises', items: ['Antibiotics for a dental abscess/spreading infection (with dental treatment, not instead of it)'] },
    ],
    warnings: [
      'Facial or jaw swelling, fever, or difficulty swallowing/breathing (spreading infection — urgent)',
      'Severe, persistent pain',
      'A knocked-out or broken tooth (see a dentist urgently)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best painkiller for toothache?', a: 'Anti-inflammatories like ibuprofen (with food) often work well for dental pain, alone or with paracetamol. A numbing gel can help temporarily — but see a dentist.' },
      { q: 'Do I need antibiotics for toothache?', a: 'Not usually — painkillers and dental treatment address most toothaches. Antibiotics are only for a spreading infection or abscess, alongside dental care.' },
      { q: 'When is toothache an emergency?', a: 'Facial or jaw swelling, fever, or difficulty swallowing or breathing means a spreading infection — seek urgent care.' },
    ],
    related: [['diseases/toothache', 'Toothache'], ['diseases/tooth-abscess', 'Tooth abscess'], ['medicines/ibuprofen', 'Ibuprofen'], ['medicines/benzocaine', 'Benzocaine (topical)']],
  },
  {
    slug: 'medicine-for/period-pain',
    name: 'Medicine for Period Pain',
    title: 'Medicine for Period Pain (Cramps) | MedDroid',
    desc: 'Medicines for period pain — the anti-inflammatories that work best, other options, and when cramps need a doctor. Not a prescription.',
    h1: 'Medicine for period pain',
    lede: 'Anti-inflammatory painkillers work particularly well for period cramps because they target the chemicals that cause them. Taken as cramps start, with heat and rest, they give good relief for most women.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about period pain',
    featTitle: 'What to know',
    features: [
      'NSAIDs (ibuprofen, mefenamic acid, naproxen) work best — take with food as cramps start',
      'Paracetamol is an alternative if NSAIDs do not suit you',
      'Heat, gentle activity and hydration help',
      'The contraceptive pill can reduce cramps for some (doctor-guided)',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Ibuprofen', 'Mefenamic acid', 'Naproxen', 'Paracetamol'] },
      { title: 'Doctor-guided options', items: ['Hormonal options (the pill, hormonal IUD)', 'Antispasmodics (drotaverine)'] },
    ],
    warnings: [
      'Very severe pain, or pain getting worse over months (possible endometriosis)',
      'Pain outside periods, or very heavy bleeding',
      'Pain with a chance of pregnancy and a missed period (possible ectopic — urgent)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for period pain?', a: 'Anti-inflammatories like ibuprofen or mefenamic acid, taken with food as cramps start, work best. Paracetamol is an alternative, and heat and rest help too.' },
      { q: 'Why do NSAIDs work better for cramps?', a: 'They block prostaglandins, the chemicals that make the womb contract painfully — so they target the cause of cramps, not just the pain.' },
      { q: 'When should period pain be checked?', a: 'If it is severe, worsening, present outside periods, or comes with very heavy bleeding — to check for conditions like endometriosis or fibroids.' },
    ],
    related: [['diseases/painful-periods', 'Painful periods'], ['medicines/mefenamic-acid', 'Mefenamic acid'], ['womens-health/how-to-reduce-period-pain', 'How to reduce period pain'], ['diseases/endometriosis', 'Endometriosis']],
  },
  {
    slug: 'medicine-for/fungal-infection',
    name: 'Medicine for Fungal Infection',
    title: 'Medicine for Fungal Infection (Ringworm) | MedDroid',
    desc: 'Medicines for fungal skin infections and ringworm — antifungal creams and tablets, why it keeps coming back, and hygiene tips. Not a prescription.',
    h1: 'Medicine for fungal infection (ringworm)',
    lede: 'Fungal skin infections like ringworm are very common in India’s humid climate and are treated with antifungal creams or, for widespread cases, tablets. Completing the full course and keeping skin dry prevent recurrence.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fungal infection',
    featTitle: 'What to know',
    features: [
      'Small patches: antifungal cream, continued for the full course',
      'Widespread, scalp or nail infections: often need tablets',
      'Keep the skin clean and dry; wash and hot-iron clothes',
      'Avoid steroid-antifungal combination creams for long periods (they worsen ringworm)',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Antifungal creams: clotrimazole, terbinafine, miconazole, luliconazole', 'Antifungal powders/shampoo (ketoconazole)'] },
      { title: 'Prescription / doctor-guided options', items: ['Oral antifungals: terbinafine, itraconazole, fluconazole, griseofulvin (for scalp)', 'Nail lacquers (amorolfine, ciclopirox)'] },
    ],
    warnings: [
      'Widespread, fast-spreading, or recurring infection — see a doctor',
      'Scalp or nail infection (usually needs tablets)',
      'Avoid unlabelled combination "skin creams" with strong steroids (they spread ringworm)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for ringworm?', a: 'Antifungal creams like terbinafine or clotrimazole for small patches, applied for the full course. Widespread, scalp or nail infections usually need antifungal tablets.' },
      { q: 'Why does my ringworm keep coming back?', a: 'Common reasons are stopping treatment too early, humid conditions, reinfection from clothes/bedding, and overusing steroid-containing creams. Complete the course and keep skin dry.' },
      { q: 'Are steroid-antifungal combination creams good for ringworm?', a: 'No — long use of these can worsen and spread ringworm. Use a proper antifungal and see a doctor if it is not clearing.' },
    ],
    related: [['diseases/ringworm', 'Ringworm'], ['medicines/terbinafine', 'Terbinafine'], ['medicines/clotrimazole', 'Clotrimazole'], ['medicines/fluconazole', 'Fluconazole']],
  },
  {
    slug: 'medicine-for/worms',
    name: 'Medicine for Worms (Deworming)',
    title: 'Medicine for Worms: Deworming Tablets | MedDroid',
    desc: 'Deworming medicines for intestinal worms — which tablets are used, how deworming works, prevention, and when to see a doctor. Not a prescription.',
    h1: 'Medicine for worms (deworming)',
    lede: 'Intestinal worms are common, especially in children, and are easily treated with deworming tablets. Good hygiene and treating the household prevent them coming back.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about deworming',
    featTitle: 'What to know',
    features: [
      'Deworming tablets clear most common intestinal worms',
      'For threadworm, treat the whole household and repeat after 2 weeks',
      'Routine deworming is often advised every 6 months in childhood',
      'Hygiene (handwashing, short nails, clean bedding) prevents reinfection',
    ],
    lists: [
      { title: 'Commonly used', items: ['Albendazole', 'Mebendazole', 'Ivermectin (certain infections)', 'Praziquantel (tapeworm)', 'Diethylcarbamazine (filariasis)'] },
    ],
    warnings: [
      'Weight loss, blood in stool, or a swollen tummy',
      'Passing a large worm, or worms not clearing after treatment',
      'Pallor and tiredness (possible anaemia from heavy infestation)',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'Which tablet is best for worms?', a: 'Albendazole or mebendazole clear most common intestinal worms. For threadworm, treat the whole family and repeat the dose after 2 weeks, with good hygiene.' },
      { q: 'How often should I deworm my child?', a: 'Many programmes advise deworming every 6 months in childhood. Follow your doctor or local health guidance.' },
      { q: 'Do I need to treat the whole family?', a: 'For threadworms, yes — treating everyone together plus good hygiene prevents reinfection.' },
    ],
    related: [['diseases/worm-infestation', 'Worm infestation'], ['medicines/albendazole', 'Albendazole'], ['medicines/mebendazole', 'Mebendazole'], ['child-health/worms-in-children', 'Worms in children']],
  },
  {
    slug: 'medicine-for/high-blood-pressure',
    name: 'Medicine for High Blood Pressure',
    title: 'Medicine for High Blood Pressure (BP Tablets) | MedDroid',
    desc: 'Medicines for high blood pressure — the main classes of BP tablets, how they work, and why they are long-term. Doctor-prescribed only. Not a prescription.',
    h1: 'Medicine for high blood pressure',
    lede: 'Blood-pressure medicines are prescribed by a doctor and usually taken long term. Several classes work in different ways, and many people need a combination — alongside a low-salt diet and lifestyle changes.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about BP medicines',
    featTitle: 'What to know',
    features: [
      'BP tablets are prescription-only and chosen for your health profile',
      'Many people need two or more together for good control',
      'Do not stop them when your BP is normal — that means they are working',
      'Diet (low salt), exercise and weight loss reduce the dose needed',
    ],
    lists: [
      { title: 'Main classes (doctor decides)', items: ['ACE inhibitors: ramipril, enalapril, lisinopril', 'ARBs: telmisartan, losartan, olmesartan', 'Calcium-channel blockers: amlodipine, cilnidipine', 'Diuretics: hydrochlorothiazide, chlorthalidone', 'Beta-blockers: metoprolol, atenolol (specific situations)'] },
    ],
    warnings: [
      'A reading of 180/120 or higher, or symptoms — urgent',
      'Do not stop BP medicine suddenly',
      'ACE inhibitors and ARBs are avoided in pregnancy',
    ],
    noteTitle: 'Prescription-only — see a doctor.',
    note: RX_NOTE,
    faqs: [
      { q: 'What are the common blood-pressure tablets?', a: 'Main classes are ACE inhibitors (ramipril), ARBs (telmisartan, losartan), calcium-channel blockers (amlodipine), diuretics and, in some cases, beta-blockers. A doctor chooses based on your health.' },
      { q: 'Do I have to take BP medicine for life?', a: 'Often yes — normal readings usually mean the medicine is working. Lifestyle changes can reduce the dose, but stop only with your doctor.' },
      { q: 'Which BP medicine is best?', a: 'There is no single best — it depends on your age, other conditions (like diabetes or kidney disease) and how you respond. Many people need a combination.' },
    ],
    related: [['diseases/hypertension', 'Hypertension'], ['medicines/amlodipine', 'Amlodipine'], ['medicines/telmisartan', 'Telmisartan'], ['how-to-lower-blood-pressure', 'How to lower blood pressure']],
  },
  {
    slug: 'medicine-for/diabetes',
    name: 'Medicine for Diabetes',
    title: 'Medicine for Diabetes (Sugar Tablets & Insulin) | MedDroid',
    desc: 'Medicines for diabetes — metformin and other tablet classes, insulin, and how they are chosen. Doctor-prescribed only. Not a prescription.',
    h1: 'Medicine for diabetes',
    lede: 'Diabetes medicines are prescribed by a doctor and chosen to fit your sugar levels, weight, kidneys and heart. Metformin is usually first, with other tablets or insulin added as needed — alongside diet and activity.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about diabetes medicines',
    featTitle: 'What to know',
    features: [
      'Metformin is usually the first-line tablet',
      'Other tablet classes are added to reach target sugar (HbA1c)',
      'Some newer medicines also protect the heart and kidneys',
      'Insulin is used in type 1, and in type 2 when needed',
    ],
    lists: [
      { title: 'Main tablet classes (doctor decides)', items: ['Metformin (first-line)', 'Sulfonylureas: glimepiride, gliclazide', 'DPP-4 inhibitors: sitagliptin, teneligliptin, linagliptin', 'SGLT2 inhibitors: dapagliflozin, empagliflozin', 'Others: pioglitazone, voglibose'] },
      { title: 'Injectable', items: ['Insulin (various types)', 'GLP-1 medicines: semaglutide, liraglutide, dulaglutide'] },
    ],
    warnings: [
      'Very high sugar with vomiting or drowsiness (emergency)',
      'Low-sugar episodes (shakiness, sweating, confusion) — adjust with your doctor',
      'Do not stop diabetes medicine on your own',
    ],
    noteTitle: 'Prescription-only — see a doctor.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the first medicine for type 2 diabetes?', a: 'Metformin is usually first-line, alongside diet and activity. Other tablets or insulin are added to reach and maintain your target sugar (HbA1c).' },
      { q: 'Which diabetes medicine is best?', a: 'It depends on your sugar levels, weight, kidney and heart health. Some newer medicines (SGLT2, GLP-1) also protect the heart and kidneys. Your doctor tailors this.' },
      { q: 'Can I stop diabetes medicine if my sugar is normal?', a: 'Not on your own — normal sugar usually means the medicine is working. Type 2 can sometimes improve with major weight loss, but change medicines only with your doctor.' },
    ],
    related: [['diseases/type-2-diabetes', 'Type 2 diabetes'], ['medicines/metformin', 'Metformin'], ['how-to-lower-blood-sugar', 'How to lower blood sugar'], ['nutrition/diabetic-diet-chart', 'Diabetic diet']],
  },
  {
    slug: 'medicine-for/high-cholesterol',
    name: 'Medicine for High Cholesterol',
    title: 'Medicine for High Cholesterol (Statins & More) | MedDroid',
    desc: 'Medicines for high cholesterol — statins and add-on options, who needs them, and why they are usually long-term. Doctor-prescribed. Not a prescription.',
    h1: 'Medicine for high cholesterol',
    lede: 'Statins are the main medicine for high cholesterol, lowering the risk of heart attack and stroke. They are prescribed based on your overall risk, alongside diet and lifestyle — and usually taken long term.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about cholesterol medicines',
    featTitle: 'What to know',
    features: [
      'Statins are first-line and lower "bad" LDL cholesterol',
      'Add-ons are used if statins alone are not enough',
      'Fibrates mainly lower high triglycerides',
      'Diet and exercise reduce the dose needed',
    ],
    lists: [
      { title: 'Main options (doctor decides)', items: ['Statins: atorvastatin, rosuvastatin, simvastatin', 'Ezetimibe (add-on)', 'Fibrates: fenofibrate (for triglycerides)', 'Newer: bempedoic acid, PCSK9 injections (evolocumab)'] },
    ],
    warnings: [
      'Unexplained muscle pain/weakness with dark urine (rare statin effect) — see a doctor',
      'Statins are avoided in pregnancy',
      'Do not stop statins without advice',
    ],
    noteTitle: 'Prescription-only — see a doctor.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for high cholesterol?', a: 'Statins (atorvastatin, rosuvastatin) are first-line and most effective for lowering LDL and heart-disease risk. Add-ons like ezetimibe are used if needed.' },
      { q: 'Do I need a statin for high cholesterol?', a: 'It depends on your cholesterol level and overall risk of heart disease. Some manage with lifestyle; others benefit greatly from a statin. Your doctor decides with you.' },
      { q: 'Do I have to take cholesterol medicine for life?', a: 'Often yes, because cholesterol rises again if it stops. Lifestyle helps, but stop only on your doctor’s advice.' },
    ],
    related: [['diseases/high-cholesterol', 'High cholesterol'], ['medicines/atorvastatin', 'Atorvastatin'], ['how-to-lower-cholesterol', 'How to lower cholesterol'], ['nutrition/diet-for-high-cholesterol', 'Diet for high cholesterol']],
  },
  {
    slug: 'medicine-for/uti',
    name: 'Medicine for UTI',
    title: 'Medicine for UTI (Urinary Infection) | MedDroid',
    desc: 'Medicines for a urinary tract infection — the antibiotics commonly used, why you should not self-treat, and when it is urgent. Not a prescription.',
    h1: 'Medicine for UTI',
    lede: 'Most urinary tract infections need a short course of antibiotics prescribed by a doctor. Drinking plenty of water and pain relief help, but self-buying antibiotics drives resistance and can miss a kidney infection.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about UTIs',
    featTitle: 'What to know',
    features: [
      'Most UTIs need a short antibiotic course from a doctor',
      'Drink plenty of water; paracetamol for discomfort',
      'A urine test guides the right antibiotic',
      'Do not self-buy antibiotics — it drives resistance and can mask a kidney infection',
    ],
    lists: [
      { title: 'Commonly prescribed (doctor decides)', items: ['Nitrofurantoin', 'Fosfomycin (single dose)', 'Cotrimoxazole', 'Cefixime or others depending on the urine test'] },
    ],
    warnings: [
      'Fever, back/flank pain, chills or vomiting (possible kidney infection — urgent)',
      'Blood in the urine',
      'A UTI in pregnancy (needs prompt treatment)',
      'Recurring UTIs (get assessed)',
    ],
    noteTitle: 'Antibiotics need a doctor.',
    note: RX_NOTE,
    faqs: [
      { q: 'What antibiotic is used for a UTI?', a: 'Common choices include nitrofurantoin, fosfomycin and cotrimoxazole, chosen by a doctor and guided by a urine test. Do not self-medicate with antibiotics.' },
      { q: 'Can a UTI be treated without antibiotics?', a: 'Mild cases can sometimes settle with fluids, but most bacterial UTIs need antibiotics. Fever or back pain suggests a kidney infection needing urgent treatment.' },
      { q: 'Why should I not self-buy UTI antibiotics?', a: 'Wrong or unnecessary antibiotics drive resistance, may not match the bacteria, and can mask a more serious kidney infection. A doctor should guide treatment.' },
    ],
    related: [['diseases/urinary-tract-infection', 'Urinary tract infection'], ['medicines/nitrofurantoin', 'Nitrofurantoin'], ['womens-health/uti-in-women', 'UTI in women'], ['medicines/fosfomycin', 'Fosfomycin']],
  },
  {
    slug: 'medicine-for/asthma',
    name: 'Medicine for Asthma',
    title: 'Medicine for Asthma (Inhalers Explained) | MedDroid',
    desc: 'Medicines for asthma — reliever vs preventer inhalers, how they work, and why preventers matter. Doctor-prescribed. Not a prescription.',
    h1: 'Medicine for asthma',
    lede: 'Asthma is controlled with inhalers, prescribed by a doctor. A "reliever" opens the airways quickly during symptoms, while a "preventer" (usually a steroid) is taken daily to reduce inflammation and prevent attacks.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about asthma medicines',
    featTitle: 'What to know',
    features: [
      'Reliever inhaler: fast relief of symptoms (keep it always)',
      'Preventer inhaler: daily, reduces inflammation and attacks',
      'Needing the reliever often means poor control — review with a doctor',
      'Use correct technique and a spacer; rinse mouth after steroid inhalers',
    ],
    lists: [
      { title: 'Main options (doctor decides)', items: ['Reliever: salbutamol / levosalbutamol', 'Preventer (inhaled steroid): budesonide, fluticasone, beclomethasone', 'Long-acting + steroid combinations (formoterol/salmeterol)', 'Add-on tablet: montelukast'] },
    ],
    warnings: [
      'Severe breathlessness, blue lips, or a reliever not working — emergency',
      'Needing your reliever more than a couple of times a week',
      'Waking at night with asthma symptoms',
    ],
    noteTitle: 'Prescription-only — see a doctor.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the difference between reliever and preventer inhalers?', a: 'A reliever (salbutamol) opens the airways quickly during symptoms; a preventer (an inhaled steroid) is taken daily to reduce inflammation and prevent attacks.' },
      { q: 'Are steroid inhalers safe?', a: 'Yes — at usual doses inhaled steroids are safe and are the mainstay of asthma control. Rinse your mouth after using them to avoid thrush.' },
      { q: 'Why do I still get attacks if I use my inhaler?', a: 'Often because the preventer is not used regularly, technique is poor, or control needs stepping up. Needing your reliever often is a sign to see your doctor.' },
    ],
    related: [['diseases/asthma', 'Asthma'], ['medicines/salbutamol', 'Salbutamol'], ['medicines/budesonide', 'Budesonide'], ['medicines/montelukast', 'Montelukast']],
  },
  {
    slug: 'medicine-for/sleep',
    name: 'Medicine for Sleep',
    title: 'Medicine for Sleep (Insomnia): What to Know | MedDroid',
    desc: 'Medicines and options for sleep — why sleeping pills are a last resort, safer options like melatonin, and better long-term fixes. Not a prescription.',
    h1: 'Medicine for sleep (insomnia)',
    lede: 'Sleeping pills are a last resort, not a first step. Most insomnia improves with better sleep habits and, if needed, short-term or non-habit-forming options — with prescription sleeping tablets used briefly and carefully.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sleep',
    featTitle: 'What to know',
    features: [
      'Sleep-hygiene changes and CBT for insomnia work best long term',
      'Melatonin is non-habit-forming and useful for some (and jet lag)',
      'Prescription sleeping pills are for short-term use only (dependence risk)',
      'Treat causes: stress, anxiety, pain, sleep apnoea',
    ],
    lists: [
      { title: 'Options', items: ['Melatonin (non-habit-forming)', 'Sedating antihistamines (doxylamine) for occasional use', 'Prescription sleeping tablets (zolpidem, short-term) — doctor-guided', 'Treating underlying anxiety or depression'] },
    ],
    warnings: [
      'Loud snoring with daytime sleepiness (possible sleep apnoea)',
      'Insomnia with low mood or anxiety',
      'Do not combine sleeping pills with alcohol',
      'Avoid long-term reliance on sleeping pills',
    ],
    noteTitle: 'Habits first, pills last.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for sleep?', a: 'For most people, better sleep habits and CBT for insomnia work best. Melatonin helps some without dependence; prescription sleeping pills are for short-term use only.' },
      { q: 'Is melatonin safe?', a: 'Yes — it is generally well tolerated for short-term sleep problems and jet lag and is not habit-forming, though good sleep habits matter most.' },
      { q: 'Are sleeping pills addictive?', a: 'Some prescription ones can cause dependence with regular use, so they are meant for short courses while sleep habits are improved.' },
    ],
    related: [['diseases/insomnia', 'Insomnia'], ['medicines/melatonin', 'Melatonin'], ['mental-health/how-to-sleep-better', 'How to sleep better'], ['diseases/obstructive-sleep-apnoea', 'Sleep apnoea']],
  },
  {
    slug: 'medicine-for/mouth-ulcers',
    name: 'Medicine for Mouth Ulcers',
    title: 'Medicine for Mouth Ulcers: What Helps | MedDroid',
    desc: 'Medicines for mouth ulcers — soothing gels, rinses, pain relief, and when a mouth ulcer needs a doctor. Not a prescription.',
    h1: 'Medicine for mouth ulcers',
    lede: 'Most mouth ulcers are harmless and heal within 1–2 weeks. Soothing gels and rinses ease the pain while they heal — but an ulcer that lasts more than 3 weeks needs to be checked.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about mouth ulcers',
    featTitle: 'What to know',
    features: [
      'Numbing/soothing gels ease the pain',
      'Antiseptic or salt-water/steroid mouth rinses help healing',
      'Avoid spicy, acidic and rough foods while it heals',
      'Treat causes: deficiency (iron, B12), stress, injury',
    ],
    lists: [
      { title: 'Common over-the-counter options', items: ['Numbing gels (benzocaine/choline salicylate)', 'Antiseptic mouthwash (chlorhexidine)', 'Salt-water rinses', 'Vitamin correction if deficient (iron, B12, folate)'] },
      { title: 'Doctor/dentist-guided', items: ['Steroid mouth gels/rinses for severe or recurrent ulcers', 'Investigating recurrent ulcers'] },
    ],
    warnings: [
      'An ulcer lasting more than 3 weeks (needs to be checked, especially in tobacco users)',
      'Frequent, severe or widespread ulcers',
      'Ulcers with weight loss, or a neck lump',
    ],
    noteTitle: 'Not a prescription.',
    note: RX_NOTE,
    faqs: [
      { q: 'What is the best medicine for mouth ulcers?', a: 'Numbing gels and antiseptic or salt-water rinses ease pain and aid healing. Recurrent or severe ulcers may need a steroid gel, and deficiencies should be corrected.' },
      { q: 'Why do I keep getting mouth ulcers?', a: 'Common causes are minor injury, stress, certain foods, and deficiencies of iron, B12 or folate. Recurrent ulcers are worth investigating.' },
      { q: 'When is a mouth ulcer serious?', a: 'An ulcer that does not heal within 3 weeks — especially in tobacco or alcohol users, or with a neck lump or weight loss — must be checked to rule out oral cancer.' },
    ],
    related: [['diseases/mouth-ulcers', 'Mouth ulcers'], ['diseases/vitamin-b12-deficiency', 'Vitamin B12 deficiency'], ['diseases/oral-cancer', 'Oral cancer'], ['nutrition/vitamin-b12-foods', 'Vitamin B12 foods']],
  },
];
