// Men's-health Q&A cluster for MedDroid. Respectful, myth-busting, practical.
// Full page objects (same shape gen-landing's page() consumes). Educational only,
// not a diagnosis. Handles sensitive topics factually and reassuringly, and flags
// the real red flags (testicular torsion, lumps, blood in urine, ED as a heart sign).

export const MENS_QA = [
  {
    slug: 'mens-health/erectile-dysfunction-help',
    name: 'Erectile Dysfunction: Help',
    title: 'Erectile Dysfunction: Causes & Treatment | MedDroid',
    desc: 'Erectile dysfunction (ED) — common physical and psychological causes, why it can be a heart warning sign, treatments that work, and when to see a doctor. Not a diagnosis.',
    h1: 'Erectile dysfunction: causes and help',
    lede: 'Erectile dysfunction is common and very treatable, and it is nothing to be ashamed of. Importantly, it can be an early warning sign of heart or blood-vessel problems — so it is worth understanding, not just ignoring.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about ED',
    featTitle: 'Common causes & what helps',
    features: [
      'Physical: diabetes, high blood pressure, high cholesterol, smoking, obesity',
      'Psychological: stress, anxiety, depression, relationship worries',
      'Lifestyle: exercise, weight loss, stopping smoking and limiting alcohol help a lot',
      'Medicines like sildenafil (Viagra) or tadalafil (Cialis) are effective and safe for most men',
      'Treating the underlying cause (e.g. diabetes, low testosterone) often improves it',
    ],
    warnings: [
      'Never combine ED tablets with nitrate heart medicines (dangerous drop in blood pressure)',
      'New ED can be an early sign of heart/blood-vessel disease — get a health check',
      'An erection lasting over 4 hours (priapism) is an emergency',
      'Sudden ED with numbness or difficulty passing urine — see a doctor',
    ],
    noteTitle: 'It is common, treatable — and a health signal.',
    note: 'ED shares causes with heart disease, so it is worth a check of blood pressure, sugar and cholesterol. Do not buy unregulated “sex tablets”. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes erectile dysfunction?', a: 'Often a mix of physical (diabetes, blood-pressure, cholesterol, smoking) and psychological (stress, anxiety) causes. Because it involves blood flow, it can also flag early heart disease.' },
      { q: 'Do ED tablets like Viagra work?', a: 'Yes — sildenafil and tadalafil work for most men and are safe when prescribed. They must never be combined with nitrate heart medicines. Avoid unregulated online “sex pills”.' },
      { q: 'Can ED be cured naturally?', a: 'Lifestyle changes — exercise, weight loss, stopping smoking, less alcohol, and treating diabetes/BP — genuinely improve erections, sometimes enough on their own.' },
    ],
    related: [['diseases/erectile-dysfunction', 'Erectile dysfunction'], ['medicines/sildenafil', 'Sildenafil'], ['medicines/tadalafil', 'Tadalafil'], ['mens-health/low-testosterone-symptoms', 'Low testosterone']],
  },
  {
    slug: 'mens-health/premature-ejaculation-help',
    name: 'Premature Ejaculation: Help',
    title: 'Premature Ejaculation: Causes & How to Last Longer | MedDroid',
    desc: 'Premature ejaculation — why it happens, techniques and medicines that help, and when to see a doctor. Common and treatable. Educational, not a diagnosis.',
    h1: 'Premature ejaculation: how to get help',
    lede: 'Premature ejaculation is one of the most common male sexual concerns — and one of the most treatable. It is rarely a sign of anything serious, and simple techniques and medicines help most men.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about PE',
    featTitle: 'What helps',
    features: [
      'Techniques: the “stop-start” and “squeeze” methods',
      'Pelvic-floor exercises',
      'Thicker condoms or numbing sprays/creams to reduce sensitivity',
      'Medicines: dapoxetine (taken before sex) or certain daily antidepressants (off-label)',
      'Reducing performance anxiety — counselling can help',
    ],
    warnings: [
      'New PE with erectile difficulty, or after starting a medicine — see a doctor',
      'Significant relationship or emotional distress',
      'Painful ejaculation or blood in semen (needs assessment)',
    ],
    noteTitle: 'Very common and very treatable.',
    note: 'PE is usually not caused by any disease and responds well to techniques and, if needed, medicine. Avoid unregulated products. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes premature ejaculation?', a: 'Often psychological factors like anxiety and over-excitement, sometimes with a biological tendency. It is rarely a sign of serious illness.' },
      { q: 'How can I last longer in bed?', a: 'Behavioural techniques (stop-start, squeeze), pelvic-floor exercises, thicker condoms or numbing sprays, and — if needed — medicine like dapoxetine all help.' },
      { q: 'Is there a tablet for premature ejaculation?', a: 'Yes — dapoxetine is taken before sex, and some daily antidepressants are used off-label. A doctor can advise what suits you.' },
    ],
    related: [['diseases/premature-ejaculation', 'Premature ejaculation'], ['medicines/dapoxetine', 'Dapoxetine'], ['mens-health/erectile-dysfunction-help', 'Erectile dysfunction'], ['diseases/low-libido', 'Low libido']],
  },
  {
    slug: 'mens-health/low-testosterone-symptoms',
    name: 'Low Testosterone Symptoms',
    title: 'Low Testosterone: Symptoms & What to Do | MedDroid',
    desc: 'Low testosterone (low T) — the real symptoms, common causes, how it is tested and treated, and the risks of unnecessary testosterone. Educational, not a diagnosis.',
    h1: 'Low testosterone: symptoms and what to do',
    lede: 'Testosterone naturally declines with age, but genuinely low levels can cause tiredness, low sex drive and mood changes. It is worth testing properly rather than self-treating — because unnecessary testosterone carries real risks.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about low testosterone',
    featTitle: 'Possible symptoms',
    features: [
      'Low sex drive and erectile problems',
      'Persistent tiredness and low mood',
      'Loss of muscle and increased body fat',
      'Reduced body/facial hair; sometimes breast tenderness',
      'Poor concentration or reduced motivation',
    ],
    warnings: [
      'Do not take testosterone without confirmed low levels — it can shrink the testicles and reduce fertility',
      'Testosterone can worsen some prostate conditions and thicken the blood',
      'Very low levels or symptoms in a young man need investigation',
      'Beware unregulated “testosterone boosters” and steroids',
    ],
    noteTitle: 'Test before you treat.',
    note: 'Low-T symptoms overlap with many conditions, so a morning blood test (repeated) confirms it before treatment. Testosterone is not a general tonic and has real risks. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the symptoms of low testosterone?', a: 'Low sex drive, erectile problems, tiredness, low mood, loss of muscle and increased fat. These overlap with other conditions, so a blood test is needed to confirm it.' },
      { q: 'Should I take testosterone supplements?', a: 'Only if a doctor confirms genuinely low levels. Taking it unnecessarily can shrink the testicles, reduce fertility, thicken the blood and affect the prostate.' },
      { q: 'How is low testosterone tested?', a: 'With a blood test taken in the morning, usually repeated, along with checking for causes. Your doctor interprets it with your symptoms.' },
    ],
    related: [['diseases/low-testosterone', 'Low testosterone'], ['diseases/hypogonadism', 'Hypogonadism'], ['blood-tests/testosterone', 'Testosterone test'], ['mens-health/how-to-increase-testosterone-naturally', 'Increase testosterone naturally']],
  },
  {
    slug: 'mens-health/how-to-increase-testosterone-naturally',
    name: 'Increase Testosterone Naturally',
    title: 'How to Increase Testosterone Naturally | MedDroid',
    desc: 'Natural ways to support healthy testosterone — sleep, exercise, weight, diet and stress — and why most “testosterone boosters” do not work. Educational, not a diagnosis.',
    h1: 'How to increase testosterone naturally',
    lede: 'Lifestyle has a genuine effect on testosterone. Losing excess weight, sleeping well, exercising and managing stress support healthy levels — while most marketed “boosters” do little.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about testosterone',
    featTitle: 'What genuinely helps',
    features: [
      'Lose excess belly fat (obesity lowers testosterone)',
      'Strength training and regular exercise',
      'Good sleep (7–9 hours) — poor sleep lowers testosterone',
      'A balanced diet with enough protein, healthy fats, zinc and vitamin D',
      'Manage stress and limit alcohol',
    ],
    warnings: [
      'Most over-the-counter “testosterone boosters” are unproven — be sceptical',
      'Never use anabolic steroids to boost testosterone (serious harms, infertility)',
      'Persistent low-T symptoms deserve a proper blood test, not just supplements',
    ],
    noteTitle: 'Lifestyle first; boosters rarely help.',
    note: 'Weight, sleep, exercise and diet have real effects; commercial boosters usually do not, and steroids are dangerous. If symptoms persist, get tested. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Can I raise testosterone without medication?', a: 'Yes — losing excess weight, strength training, good sleep, a balanced diet and less alcohol all support healthy testosterone levels.' },
      { q: 'Do testosterone booster supplements work?', a: 'Most do not have good evidence. Correcting deficiencies (like vitamin D or zinc) and lifestyle changes help more than marketed “boosters”.' },
      { q: 'Does exercise increase testosterone?', a: 'Regular exercise, especially strength training, supports healthy levels — and helps by reducing body fat, which otherwise lowers testosterone.' },
    ],
    related: [['mens-health/low-testosterone-symptoms', 'Low testosterone symptoms'], ['blood-tests/testosterone', 'Testosterone test'], ['mens-health/how-to-build-muscle-safely', 'How to build muscle'], ['diseases/obesity', 'Obesity']],
  },
  {
    slug: 'mens-health/male-hair-loss-treatment',
    name: 'Male Hair Loss: Treatment',
    title: 'Male Pattern Hair Loss: Treatments That Work | MedDroid',
    desc: 'Male pattern baldness — why it happens, the treatments with real evidence (minoxidil, finasteride, transplant), and what does not work. Educational, not a diagnosis.',
    h1: 'Male hair loss: what actually works',
    lede: 'Male pattern baldness is mostly genetic and hormonal, and it is very common. A few treatments have solid evidence — and starting early gives the best results, because they slow loss more than they regrow.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about hair loss',
    featTitle: 'Treatments with evidence',
    features: [
      'Minoxidil (topical solution/foam) — slows loss and regrows some hair',
      'Finasteride (tablet) — reduces the hormone driving baldness',
      'Starting early works best (it protects existing hair)',
      'Hair transplant for established baldness',
      'Treating any other cause (iron/thyroid deficiency, stress, scalp disease)',
    ],
    warnings: [
      'Sudden, patchy or scarring hair loss, or hair loss with a rash — see a doctor (different cause)',
      'Finasteride can rarely affect libido/mood and is not for use around pregnancy',
      'Beware unproven “hair oils” and miracle cures',
      'Hair loss with tiredness/other symptoms — check for thyroid or iron deficiency',
    ],
    noteTitle: 'Start early; be realistic.',
    note: 'Evidence-based options slow loss and regrow some hair, but none is a full cure. Rule out other causes if the pattern is unusual. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the best treatment for male pattern baldness?', a: 'Minoxidil (applied to the scalp) and finasteride (a tablet) have the best evidence, and work best started early. A hair transplant helps established baldness.' },
      { q: 'Does finasteride have side effects?', a: 'Most men tolerate it well, but a small number notice reduced libido or mood changes. It must be handled carefully around pregnancy. Discuss it with a doctor.' },
      { q: 'Do hair oils regrow hair?', a: 'There is little evidence that oils regrow hair in male pattern baldness. Proven treatments are minoxidil, finasteride and transplantation.' },
    ],
    related: [['diseases/hair-loss-alopecia', 'Hair loss (alopecia)'], ['medicines/minoxidil-topical', 'Minoxidil (topical)'], ['medicines/finasteride', 'Finasteride'], ['diseases/hair-transplant', 'Hair transplant']],
  },
  {
    slug: 'mens-health/enlarged-prostate-bph',
    name: 'Enlarged Prostate (BPH)',
    title: 'Enlarged Prostate (BPH): Symptoms & Treatment | MedDroid',
    desc: 'Enlarged prostate (BPH) — urinary symptoms in older men, how it differs from prostate cancer, and treatments from tablets to surgery. Educational, not a diagnosis.',
    h1: 'Enlarged prostate (BPH)',
    lede: 'The prostate naturally enlarges with age, which can squeeze the urine tube and cause bothersome urinary symptoms. It is common, usually not cancer, and very treatable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about the prostate',
    featTitle: 'Symptoms & treatment',
    features: [
      'Symptoms: weak flow, hesitancy, dribbling, going often, and at night',
      'Lifestyle: limit evening fluids and caffeine/alcohol',
      'Medicines: alpha-blockers (tamsulosin) relax the flow; finasteride/dutasteride shrink the prostate',
      'Surgery (like TURP) for severe or drug-resistant cases',
      'A check often includes a urine test, examination and PSA',
    ],
    warnings: [
      'Sudden inability to pass urine (retention) — urgent',
      'Blood in the urine',
      'Fever with urinary symptoms (possible infection)',
      'Weight loss, bone pain, or a hard/irregular prostate — needs cancer assessment',
    ],
    noteTitle: 'BPH is not prostate cancer.',
    note: 'An enlarged prostate is usually benign, but similar symptoms can occur with prostate cancer, so a proper check (including PSA where appropriate) matters. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is an enlarged prostate cancer?', a: 'Usually not — BPH is a benign, age-related enlargement. But because symptoms can overlap with prostate cancer, a doctor’s assessment (and sometimes PSA) is important.' },
      { q: 'What are the symptoms of an enlarged prostate?', a: 'A weak or hesitant urine stream, dribbling, needing to go frequently and urgently, and getting up at night to pass urine.' },
      { q: 'How is BPH treated?', a: 'Lifestyle measures, alpha-blockers like tamsulosin to ease flow, and finasteride/dutasteride to shrink the prostate. Surgery is used for severe cases.' },
    ],
    related: [['diseases/benign-prostatic-hyperplasia', 'Benign prostatic hyperplasia'], ['medicines/tamsulosin', 'Tamsulosin'], ['medicines/dutasteride', 'Dutasteride'], ['mens-health/prostate-cancer-and-psa-screening', 'Prostate cancer & PSA']],
  },
  {
    slug: 'mens-health/prostate-cancer-and-psa-screening',
    name: 'Prostate Cancer & PSA Screening',
    title: 'Prostate Cancer & PSA Test: Should You Screen? | MedDroid',
    desc: 'Prostate cancer and the PSA test — risk factors, symptoms, what a PSA result means, and the pros and cons of screening. Educational, not a diagnosis.',
    h1: 'Prostate cancer & PSA screening',
    lede: 'Prostate cancer is common in older men and often slow-growing. The PSA blood test can help detect it early, but it is not perfect — so it is worth understanding the benefits and limits before deciding to test.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about prostate cancer',
    featTitle: 'What to know',
    features: [
      'Risk rises with age, family history and ethnicity',
      'Early prostate cancer often has NO symptoms',
      'PSA is a blood test that can be raised in cancer — but also in BPH or infection',
      'A high PSA may lead to an MRI and sometimes a biopsy',
      'Many prostate cancers are slow-growing and may just be monitored',
    ],
    warnings: [
      'Blood in urine or semen, bone pain, or unexplained weight loss',
      'New urinary symptoms with a family history of prostate cancer',
      'A hard or irregular prostate on examination',
    ],
    noteTitle: 'PSA has benefits and limits.',
    note: 'PSA screening can find cancer early but also causes false alarms and can detect harmless cancers. Discuss the pros and cons with your doctor to decide if it is right for you. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What does a high PSA mean?', a: 'It can indicate prostate cancer, but it also rises with an enlarged prostate (BPH), infection, or after certain activities. A high result usually leads to further tests, not an immediate diagnosis.' },
      { q: 'Should I get a PSA test?', a: 'It is a personal decision, usually from around age 50 (earlier with a family history). Discuss the benefits and downsides with your doctor.' },
      { q: 'What are the symptoms of prostate cancer?', a: 'Early cancer often has none. Later signs can include urinary changes, blood in urine or semen, and bone pain — so screening discussions matter for at-risk men.' },
    ],
    related: [['diseases/prostate-cancer', 'Prostate cancer'], ['blood-tests/psa', 'PSA test'], ['mens-health/enlarged-prostate-bph', 'Enlarged prostate (BPH)'], ['diseases/benign-prostatic-hyperplasia', 'BPH']],
  },
  {
    slug: 'mens-health/nightfall-is-it-normal',
    name: 'Nightfall: Is It Normal?',
    title: 'Nightfall (Nocturnal Emission): Is It Normal? | MedDroid',
    desc: 'Nightfall (nocturnal emission) — why it happens, why it is completely normal and harmless, and the myths to ignore. Reassuring facts. Educational, not a diagnosis.',
    h1: 'Nightfall: is it normal?',
    lede: 'Nightfall, or nocturnal emission, is when semen is released during sleep. It is completely normal and harmless — especially in teenagers and young men — and does not cause weakness or any disease, despite common myths.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about nightfall',
    featTitle: 'The facts',
    features: [
      'It is a normal, natural release of semen during sleep',
      'It is most common in teenagers and young adults',
      'It does NOT cause weakness, weight loss, hair loss or infertility',
      'It does not need any treatment',
      'Frequency varies from person to person — there is no “normal” number',
    ],
    warnings: [
      'It is not a disease and needs no “tonic” or special medicine',
      'Beware advertisements and quacks that create fear and sell useless cures',
      'Only see a doctor if it causes you real distress or with other genuine symptoms',
    ],
    noteTitle: 'Normal and harmless — ignore the myths.',
    note: 'Many products and myths wrongly claim nightfall causes weakness or disease. It does not. There is no need for treatment. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is nightfall harmful?', a: 'No — nightfall (nocturnal emission) is completely normal and harmless. It does not cause weakness, hair loss, weight loss or infertility.' },
      { q: 'How can I stop nightfall?', a: 'It does not need stopping or treating — it is a normal body process. If it bothers you, be reassured; there is no medical problem to fix.' },
      { q: 'Does losing semen cause weakness?', a: 'No. This is a myth. Semen loss through nightfall, sex or masturbation does not cause weakness or drain the body.' },
    ],
    related: [['mens-health/is-masturbation-harmful', 'Is masturbation harmful?'], ['diseases/low-libido', 'Low libido'], ['mens-health/low-sperm-count-and-fertility', 'Low sperm count & fertility'], ['mens-health/erectile-dysfunction-help', 'Erectile dysfunction']],
  },
  {
    slug: 'mens-health/is-masturbation-harmful',
    name: 'Is Masturbation Harmful?',
    title: 'Is Masturbation Harmful? The Facts | MedDroid',
    desc: 'Is masturbation harmful? The medical facts — it is normal and safe, does not cause weakness or disease, and the myths to ignore. Educational, not a diagnosis.',
    h1: 'Is masturbation harmful?',
    lede: 'Masturbation is a normal, common and safe activity for people of all genders. Despite widespread myths, it does not cause weakness, blindness, infertility, hair loss or any disease.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about this',
    featTitle: 'The facts',
    features: [
      'It is medically normal and safe at any frequency that is not distressing',
      'It does NOT cause weakness, blindness, acne, hair loss or infertility',
      'It does not reduce testosterone or “drain” the body',
      'It can be a normal part of sexual health and stress relief',
      'It only becomes a concern if it feels compulsive or interferes with daily life',
    ],
    warnings: [
      'Beware quacks and products that create guilt and sell “cures”',
      'Only seek help if it feels out of control, causes distress, or affects relationships/work',
      'Pain, bleeding or injury during masturbation should be checked',
    ],
    noteTitle: 'Normal and safe — the myths are false.',
    note: 'The cultural myths around masturbation causing weakness or disease are not true. There is no need for treatment or “tonics”. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Does masturbation cause weakness or health problems?', a: 'No — this is a myth. Masturbation is normal and safe and does not cause weakness, infertility, hair loss or any disease.' },
      { q: 'How much masturbation is “too much”?', a: 'There is no medical limit. It is only a concern if it becomes compulsive, causes distress, or interferes with your daily life or relationships.' },
      { q: 'Does it lower testosterone or affect fertility?', a: 'No — it has no lasting effect on testosterone or fertility. These are common myths.' },
    ],
    related: [['mens-health/nightfall-is-it-normal', 'Nightfall: is it normal?'], ['diseases/low-libido', 'Low libido'], ['mens-health/erectile-dysfunction-help', 'Erectile dysfunction'], ['diseases/substance-addiction', 'Compulsive behaviour']],
  },
  {
    slug: 'mens-health/low-sperm-count-and-fertility',
    name: 'Low Sperm Count & Fertility',
    title: 'Low Sperm Count & Male Fertility: What Helps | MedDroid',
    desc: 'Low sperm count and male fertility — common causes, lifestyle changes that help, when to get a semen analysis, and treatment options. Educational, not a diagnosis.',
    h1: 'Low sperm count & male fertility',
    lede: 'Male factors are involved in about half of fertility problems, so it is not only about the woman. Many causes of low sperm count are treatable, and lifestyle changes can genuinely improve sperm health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fertility',
    featTitle: 'What helps sperm health',
    features: [
      'Stop smoking, limit alcohol, and avoid recreational drugs and anabolic steroids',
      'Maintain a healthy weight and exercise moderately',
      'Avoid excess heat to the testicles (very hot baths, laptops on the lap)',
      'Treat causes like varicocele, infections or hormone problems',
      'A semen analysis is the key first test for the man',
    ],
    warnings: [
      'No pregnancy after 12 months of trying (or 6 months if the partner is over 35) — get checked',
      'A testicular lump, pain or swelling (see a doctor)',
      'Anabolic steroid or excess testosterone use badly harms sperm production',
      'Previous mumps, undescended testis, or groin/testicular surgery',
    ],
    noteTitle: 'Both partners should be checked.',
    note: 'Fertility involves both partners, and a simple semen analysis checks the man. Many causes are treatable, and steroid/testosterone misuse is a common, reversible cause of low counts. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can I increase my sperm count?', a: 'Stop smoking, limit alcohol, keep a healthy weight, avoid excess heat and steroids, and treat causes like varicocele. A semen analysis guides what will help most.' },
      { q: 'What is a semen analysis?', a: 'A lab test of a semen sample that checks sperm count, movement and shape. It is the main first test of male fertility.' },
      { q: 'Does testosterone help fertility?', a: 'No — taking testosterone or steroids actually suppresses sperm production and can cause infertility. Fertility problems need proper assessment, not testosterone.' },
    ],
    related: [['diseases/male-infertility', 'Male infertility'], ['mens-health/semen-analysis-explained', 'Semen analysis explained'], ['diseases/varicocele', 'Varicocele'], ['mens-health/low-testosterone-symptoms', 'Low testosterone']],
  },
  {
    slug: 'mens-health/semen-analysis-explained',
    name: 'Semen Analysis Explained',
    title: 'Semen Analysis: Normal Values Explained | MedDroid',
    desc: 'Semen analysis explained — what count, motility and morphology mean, roughly normal values, how to prepare, and next steps. Educational, not a diagnosis.',
    h1: 'Semen analysis: understanding your report',
    lede: 'A semen analysis is the main test of male fertility. It looks at how many sperm there are, how well they move, and their shape. One result is only a snapshot — it is often repeated before drawing conclusions.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about semen analysis',
    featTitle: 'What it measures (rough guide)',
    features: [
      'Volume: about 1.4 ml or more',
      'Sperm concentration: about 16 million per ml or more',
      'Total motility (movement): about 42% or more',
      'Normal shape (morphology): about 4% or more',
      'Prepare with 2–5 days of abstinence before the test',
    ],
    warnings: [
      'A single abnormal result should be confirmed with a repeat test',
      'Very low or absent sperm needs specialist (andrology) assessment',
      'Recent illness, fever or heat can temporarily lower results',
    ],
    noteTitle: 'Ranges vary; repeat before concluding.',
    note: 'Reference values differ slightly between labs, and results vary over time, so tests are often repeated. A specialist interprets an abnormal result. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is a normal sperm count?', a: 'Roughly 16 million sperm per ml or more is considered within the reference range, but movement and shape matter too — and one result is only a snapshot.' },
      { q: 'How do I prepare for a semen analysis?', a: 'Usually 2–5 days without ejaculation beforehand, avoid alcohol and illness where possible, and follow the lab’s collection instructions.' },
      { q: 'My report is abnormal — what next?', a: 'It is usually repeated after a few weeks, and if still abnormal, a specialist (andrologist) looks for treatable causes like varicocele, infection or hormone problems.' },
    ],
    related: [['mens-health/low-sperm-count-and-fertility', 'Low sperm count & fertility'], ['diseases/male-infertility', 'Male infertility'], ['diseases/varicocele', 'Varicocele'], ['blood-tests/testosterone', 'Testosterone test']],
  },
  {
    slug: 'mens-health/testicular-lump-when-to-worry',
    name: 'Testicular Lump: When to Worry',
    title: 'Testicular Lump: When to Worry & Self-Check | MedDroid',
    desc: 'Testicular lumps — most are harmless, how to self-examine, the signs of testicular cancer, and why any new lump should be checked. Educational, not a diagnosis.',
    h1: 'Testicular lump: when to worry',
    lede: 'Most testicular lumps are harmless (like cysts), but a painless lump can be the first sign of testicular cancer — which is highly curable when caught early. So any new lump should be checked promptly.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about a testicular lump',
    featTitle: 'How to check & what to look for',
    features: [
      'Check monthly, ideally after a warm shower when the skin is relaxed',
      'Roll each testicle gently between fingers and thumb, feeling for lumps',
      'Know what is normal for you (the epididymis at the back is a normal soft tube)',
      'Look for a hard, painless lump, swelling, or a change in size/weight',
      'Any new lump or change → see a doctor',
    ],
    warnings: [
      'A hard, painless lump or swelling in a testicle',
      'A feeling of heaviness or a dull ache in the scrotum or lower belly',
      'Sudden severe testicular pain (possible torsion — emergency, see next)',
      'Any change in size, shape or firmness',
    ],
    noteTitle: 'Most are harmless — but always check.',
    note: 'Testicular cancer is very treatable when found early, and a painless lump is the classic sign, so never ignore one. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Are most testicular lumps cancer?', a: 'No — many are harmless cysts or swellings. But because a painless lump can be testicular cancer, which is very curable when caught early, every new lump should be checked.' },
      { q: 'How do I check my testicles?', a: 'Monthly after a warm shower, gently roll each testicle between fingers and thumb, feeling for hard lumps or changes, and get to know what is normal for you.' },
      { q: 'Is testicular cancer curable?', a: 'Yes — it is one of the most treatable cancers, especially when found early, which is why self-checks and prompt review of any lump matter.' },
    ],
    related: [['diseases/testicular-cancer', 'Testicular cancer'], ['mens-health/testicular-pain-causes', 'Testicular pain causes'], ['diseases/hydrocele', 'Hydrocele'], ['diseases/varicocele', 'Varicocele']],
  },
  {
    slug: 'mens-health/testicular-pain-causes',
    name: 'Testicular Pain: Causes',
    title: 'Testicular Pain: Causes & Emergencies | MedDroid',
    desc: 'Testicular pain — common causes, the emergency (testicular torsion) that needs surgery within hours, and when to seek urgent care. Educational, not a diagnosis.',
    h1: 'Testicular pain: causes and emergencies',
    lede: 'Testicular pain has many causes, from infection to minor injury — but sudden, severe pain can be testicular torsion, an emergency where the testicle can be lost within hours if not treated.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about testicular pain',
    featTitle: 'Common causes',
    features: [
      'Epididymitis (infection/inflammation) — pain, swelling, sometimes fever',
      'Minor injury or strain',
      'A urinary or sexually transmitted infection',
      'A varicocele or hydrocele (usually ache/heaviness, not severe pain)',
      'Referred pain from a kidney stone or hernia',
    ],
    warnings: [
      'Sudden, severe testicular pain, often with nausea/vomiting — possible TORSION, an emergency (surgery within hours)',
      'A swollen, red, hot scrotum with fever',
      'Pain after an injury that does not settle',
      'Pain with burning urination or discharge (possible infection/STI)',
    ],
    noteTitle: 'Sudden severe pain = emergency.',
    note: 'Testicular torsion is a surgical emergency — do not wait to “see if it settles”. Go to hospital immediately for sudden severe testicular pain. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes testicular pain?', a: 'Common causes include infection (epididymitis), injury, urinary or sexually transmitted infections, and varicocele. Sudden severe pain, though, can be torsion — an emergency.' },
      { q: 'What is testicular torsion?', a: 'The testicle twists and cuts off its own blood supply, causing sudden severe pain. It needs surgery within hours to save the testicle — so seek emergency care immediately.' },
      { q: 'When should I go to hospital for testicular pain?', a: 'Immediately for sudden severe pain (especially with nausea), a red/hot swollen scrotum with fever, or pain after injury that does not settle.' },
    ],
    related: [['diseases/epididymitis', 'Epididymitis'], ['mens-health/testicular-lump-when-to-worry', 'Testicular lump'], ['diseases/varicocele', 'Varicocele'], ['diseases/inguinal-hernia', 'Inguinal hernia']],
  },
  {
    slug: 'mens-health/varicocele',
    name: 'Varicocele',
    title: 'Varicocele: Symptoms, Effect on Fertility & Treatment | MedDroid',
    desc: 'Varicocele — enlarged veins in the scrotum, how it can affect fertility, symptoms, and when treatment (surgery/embolisation) helps. Educational, not a diagnosis.',
    h1: 'Varicocele: what it is and when it matters',
    lede: 'A varicocele is a “bag of worms” of enlarged veins in the scrotum, a bit like varicose veins. Many cause no problems, but some cause a dull ache or affect fertility — in which case treatment can help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about varicocele',
    featTitle: 'What to know',
    features: [
      'Often symptomless, found on examination or during a fertility check',
      'Can cause a dull ache or heaviness, worse when standing',
      'More common on the left side',
      'May reduce sperm count/quality in some men',
      'Treatment (surgery or embolisation) is considered mainly for pain or fertility',
    ],
    warnings: [
      'A varicocele that appears suddenly, or only on the right side, needs a doctor’s review',
      'Significant testicular pain or a separate hard lump',
      'A shrinking testicle on the affected side',
    ],
    noteTitle: 'Treat it for a reason.',
    note: 'Not every varicocele needs treatment — it is usually treated for troublesome pain or a fertility problem. A sudden or right-sided one should be checked further. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Does a varicocele affect fertility?', a: 'It can reduce sperm count or quality in some men, which is why it is often found during fertility checks. Treating it may improve semen results in selected cases.' },
      { q: 'Do all varicoceles need surgery?', a: 'No — many cause no problems and need no treatment. Surgery or embolisation is mainly for troublesome pain or a fertility problem.' },
      { q: 'What are the symptoms of a varicocele?', a: 'Often none. Some men notice a dull ache or heaviness (worse when standing) or feel a “bag of worms” above the testicle.' },
    ],
    related: [['diseases/varicocele', 'Varicocele'], ['mens-health/low-sperm-count-and-fertility', 'Low sperm count & fertility'], ['mens-health/testicular-pain-causes', 'Testicular pain'], ['diseases/male-infertility', 'Male infertility']],
  },
  {
    slug: 'mens-health/gynecomastia-male-breasts',
    name: 'Gynecomastia (Male Breasts)',
    title: 'Gynecomastia (Male Breast Enlargement): Causes & Options | MedDroid',
    desc: 'Gynecomastia — why men develop breast tissue, common causes (hormones, medicines, puberty), and treatment options. Educational, not a diagnosis.',
    h1: 'Gynecomastia (male breast enlargement)',
    lede: 'Gynecomastia is the growth of real breast tissue in men, caused by a hormone imbalance. It is common — especially in puberty and older age — and is usually harmless, though it can be distressing.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about gynecomastia',
    featTitle: 'Common causes',
    features: [
      'Puberty (very common; usually settles in 1–2 years)',
      'Ageing and rising body fat',
      'Certain medicines and anabolic steroids',
      'Hormone imbalances, liver, kidney or thyroid conditions',
      'It is true breast tissue, unlike fat-only “chest fat”',
    ],
    warnings: [
      'A hard, fixed lump, one-sided growth, skin changes or nipple discharge — see a doctor (rule out breast cancer)',
      'Rapid growth or breast tenderness',
      'Gynecomastia with testicular changes',
      'Use of steroids or hormone products',
    ],
    noteTitle: 'Usually benign — check unusual features.',
    note: 'Most gynecomastia is harmless and hormone-related, but a hard one-sided lump or nipple discharge needs assessment (men can rarely get breast cancer). MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes man boobs?', a: 'True gynecomastia is breast tissue from a hormone imbalance — common in puberty and older age, and sometimes from medicines or steroids. Simple “chest fat” is different and improves with weight loss.' },
      { q: 'Does gynecomastia go away?', a: 'Pubertal gynecomastia usually settles within 1–2 years. Persistent or distressing cases can be treated with medicine (early) or surgery.' },
      { q: 'When should I worry about male breast growth?', a: 'See a doctor for a hard, fixed or one-sided lump, nipple discharge, skin changes, or rapid growth, to rule out rarer causes.' },
    ],
    related: [['diseases/gynaecomastia', 'Gynaecomastia'], ['diseases/gynaecomastia-surgery', 'Gynaecomastia surgery'], ['mens-health/low-testosterone-symptoms', 'Low testosterone'], ['diseases/obesity', 'Obesity']],
  },
  {
    slug: 'mens-health/is-penis-size-normal',
    name: 'Is My Penis Size Normal?',
    title: 'Is My Penis Size Normal? The Facts | MedDroid',
    desc: 'Penis size — what is medically average, why most worries are unfounded, and the facts about “enlargement” products. Reassuring and honest. Educational, not a diagnosis.',
    h1: 'Is my penis size normal?',
    lede: 'Worry about penis size is extremely common and almost always unnecessary. Most men who worry are well within the normal range, and size has little to do with sexual satisfaction.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about this',
    featTitle: 'The facts',
    features: [
      'Average erect length is roughly 12–16 cm — a wide normal range',
      'Flaccid size varies a lot and predicts little about erect size',
      'Size has little bearing on a partner’s satisfaction',
      'No cream, pill, oil or device reliably increases penis size',
      'Most “small penis” worries are within the normal range',
    ],
    warnings: [
      'Beware enlargement pills, oils, pumps and surgery claims — they can cause harm and waste money',
      'A curved, painful erection (possible Peyronie’s disease) — see a doctor',
      'A genuinely very small penis present since birth is rare and should be assessed',
    ],
    noteTitle: 'Almost always normal — ignore the ads.',
    note: 'Enlargement products do not work and can be harmful. If size anxiety is affecting you, talking to a doctor or counsellor helps more than any product. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the average penis size?', a: 'Average erect length is roughly 12–16 cm, with a wide normal range. Most men who worry are well within it.' },
      { q: 'Do penis enlargement products work?', a: 'No — pills, creams, oils, pumps and most devices do not reliably increase size, and some cause injury. Be very sceptical of such claims.' },
      { q: 'Does size affect sexual satisfaction?', a: 'Research shows size has little bearing on a partner’s satisfaction, which depends far more on intimacy, communication and technique.' },
    ],
    related: [['mens-health/erectile-dysfunction-help', 'Erectile dysfunction'], ['diseases/peyronies-disease', 'Peyronie’s disease'], ['mens-health/premature-ejaculation-help', 'Premature ejaculation'], ['diseases/low-libido', 'Low libido']],
  },
  {
    slug: 'mens-health/stis-in-men',
    name: 'STIs in Men',
    title: 'STIs in Men: Symptoms & When to Test | MedDroid',
    desc: 'Sexually transmitted infections in men — common symptoms (discharge, sores, burning), why some have none, testing and protection. Educational, not a diagnosis.',
    h1: 'STIs in men: symptoms & testing',
    lede: 'Sexually transmitted infections are common and treatable, but many cause no symptoms at all — so testing matters even when you feel fine. Knowing the signs helps you get treated and avoid passing them on.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about STIs',
    featTitle: 'Possible symptoms',
    features: [
      'Discharge from the penis',
      'Burning or pain when passing urine',
      'Sores, ulcers, blisters or warts around the genitals',
      'Testicular pain or swelling',
      'Many STIs (including HIV and chlamydia) often have NO symptoms',
    ],
    warnings: [
      'Get tested after unprotected sex or a new partner, even without symptoms',
      'A painless genital ulcer can be syphilis — get it checked',
      'Inform and encourage partners to get tested and treated',
      'Use condoms to reduce risk; consider HIV testing',
    ],
    noteTitle: 'No symptoms does not mean no infection.',
    note: 'Because many STIs are silent, regular testing after new or unprotected sex is important. Most are curable or treatable, and early treatment protects you and your partners. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the signs of an STI in men?', a: 'Penile discharge, burning on urination, genital sores or warts, and testicular pain — but many STIs, like chlamydia and HIV, often cause no symptoms.' },
      { q: 'Should I get tested if I have no symptoms?', a: 'Yes — after unprotected sex or with a new partner, because many STIs are silent yet still treatable and transmissible.' },
      { q: 'Are STIs curable?', a: 'Many bacterial STIs (like chlamydia, gonorrhoea, syphilis) are curable with antibiotics; viral ones (like HIV, herpes) are treatable and manageable. Early care is best.' },
    ],
    related: [['diseases/chlamydia', 'Chlamydia'], ['diseases/gonorrhoea', 'Gonorrhoea'], ['diseases/syphilis', 'Syphilis'], ['diseases/hiv-aids', 'HIV/AIDS']],
  },
  {
    slug: 'mens-health/burning-urination-in-men',
    name: 'Burning Urination in Men',
    title: 'Burning Urination in Men: Causes & What to Do | MedDroid',
    desc: 'Burning or painful urination in men — common causes (infection, STI, prostate, stones), what helps, and when to see a doctor. Educational, not a diagnosis.',
    h1: 'Burning urination in men',
    lede: 'Burning or pain when passing urine (dysuria) in men can come from a urinary infection, an STI, a prostate problem or a stone. It is usually treatable — the cause guides the treatment.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about burning urination',
    featTitle: 'Common causes',
    features: [
      'Urinary tract infection (less common in men, so always worth checking)',
      'A sexually transmitted infection (e.g. chlamydia, gonorrhoea)',
      'Prostate inflammation (prostatitis)',
      'A kidney or bladder stone',
      'Irritation from products or a narrowing of the urine tube (stricture)',
    ],
    warnings: [
      'Fever, back/flank pain or chills (possible kidney infection — urgent)',
      'Blood in the urine',
      'Penile discharge or genital sores (possible STI)',
      'Inability to pass urine, or severe pain',
    ],
    noteTitle: 'In men, always find the cause.',
    note: 'UTIs are less common in men, so burning urination should be assessed rather than self-treated — it may be an STI or prostate problem. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What causes burning urination in men?', a: 'A urinary infection, an STI, prostate inflammation, or a stone are common causes. Because UTIs are less common in men, the cause should be checked.' },
      { q: 'Is burning urination always an STI?', a: 'No, but it can be — especially with discharge or after a new partner. A doctor can test to find the cause and treat it correctly.' },
      { q: 'When should I see a doctor?', a: 'Promptly for fever, back pain, blood in the urine, discharge, or inability to pass urine — and generally, since the cause should be identified.' },
    ],
    related: [['diseases/urinary-tract-infection', 'Urinary tract infection'], ['diseases/prostatitis', 'Prostatitis'], ['mens-health/stis-in-men', 'STIs in men'], ['diseases/urethral-stricture', 'Urethral stricture']],
  },
  {
    slug: 'mens-health/how-to-build-muscle-safely',
    name: 'How to Build Muscle Safely',
    title: 'How to Build Muscle Safely (No Steroids) | MedDroid',
    desc: 'How to build muscle safely — training, protein and diet, recovery, realistic timelines, and why to avoid steroids. Educational, not a diagnosis.',
    h1: 'How to build muscle safely',
    lede: 'Building muscle comes down to consistent resistance training, enough protein and calories, and recovery — not shortcuts. Steroids and many “mass gainer” shortcuts carry real health risks.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fitness',
    featTitle: 'What actually builds muscle',
    features: [
      'Progressive resistance (weight) training 3–5 times a week',
      'Enough protein (roughly 1.6–2.2 g per kg body weight per day)',
      'A slight calorie surplus with balanced nutrition',
      'Sleep and rest days — muscle grows during recovery',
      'Patience: real gains take months, not weeks',
    ],
    warnings: [
      'Avoid anabolic steroids — they harm the heart, liver, hormones, fertility and mood',
      'Beware unregulated supplements and very high-protein diets in kidney disease',
      'Chest pain, palpitations or severe muscle pain during exercise — stop and get checked',
      'Sudden dark urine with muscle pain after intense exercise (rare rhabdomyolysis)',
    ],
    noteTitle: 'No steroids, no shortcuts.',
    note: 'Steroids and quick-fix products are dangerous. Sustainable muscle comes from training, nutrition and recovery. Those with health conditions should get advice before intense programmes. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How much protein do I need to build muscle?', a: 'Roughly 1.6–2.2 g of protein per kg of body weight per day, from food or supplements, alongside resistance training and enough overall calories.' },
      { q: 'Are steroids worth it for muscle?', a: 'No — anabolic steroids cause serious harm to the heart, liver, hormones, fertility and mental health. The risks far outweigh the gains.' },
      { q: 'How long does it take to build muscle?', a: 'Noticeable gains usually take a few months of consistent training and nutrition. Beware anything promising dramatic results in weeks.' },
    ],
    related: [['mens-health/are-protein-supplements-safe', 'Are protein supplements safe?'], ['mens-health/how-to-increase-testosterone-naturally', 'Increase testosterone naturally'], ['diseases/obesity', 'Obesity'], ['diseases/metabolic-syndrome', 'Metabolic syndrome']],
  },
  {
    slug: 'mens-health/are-protein-supplements-safe',
    name: 'Are Protein Supplements Safe?',
    title: 'Are Protein Supplements Safe? Whey & Creatine | MedDroid',
    desc: 'Are protein powders and creatine safe? What the evidence says, who should be cautious, and how to use them sensibly. Educational, not a diagnosis.',
    h1: 'Are protein supplements safe?',
    lede: 'For healthy people, quality protein powders and creatine are generally safe and can help meet protein and training goals. The key is using genuine products sensibly and getting most nutrition from food.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about supplements',
    featTitle: 'Sensible use',
    features: [
      'Whey/plant protein is just a convenient food — safe for most healthy adults',
      'Creatine is one of the best-studied, safe performance supplements',
      'Get most of your protein from food; use powder to fill gaps',
      'Choose reputable, tested brands (contamination and fakes are common)',
      'Stay hydrated, especially with creatine',
    ],
    warnings: [
      'Kidney disease: check with a doctor before high-protein diets or supplements',
      'Beware supplements spiked with steroids or stimulants (buy tested brands)',
      '“Mass gainers” are often just sugar and calories',
      'Digestive upset with whey may mean lactose intolerance — try a plant/isolate option',
    ],
    noteTitle: 'Safe for most — food first.',
    note: 'Protein powder and creatine are safe for most healthy people, but those with kidney disease should seek advice, and product quality matters. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is whey protein bad for the kidneys or liver?', a: 'For healthy people, no — high protein does not harm normal kidneys or liver. Those with existing kidney disease should get medical advice first.' },
      { q: 'Is creatine safe?', a: 'Yes — creatine is one of the most researched, safe and effective supplements for strength and muscle. Stay well hydrated while using it.' },
      { q: 'Do I even need protein powder?', a: 'Not necessarily — it is just convenient. If you get enough protein from food (dal, eggs, dairy, meat), you may not need it at all.' },
    ],
    related: [['mens-health/how-to-build-muscle-safely', 'How to build muscle safely'], ['medicines/vitamin-d3', 'Vitamin D3'], ['diseases/chronic-kidney-disease', 'Chronic kidney disease'], ['diseases/lactose-intolerance', 'Lactose intolerance']],
  },
];
