// Mental-health Q&A cluster for MedDroid. Supportive, non-judgmental, practical.
// Full page objects (same shape gen-landing's page() consumes). Educational only,
// not a diagnosis or therapy. Every relevant page escalates self-harm risk and
// points to real help. India crisis lines: KIRAN 1800-599-0019, Tele-MANAS 14416.

const CRISIS = 'If you are thinking about harming yourself, please reach out now — in India call KIRAN 1800-599-0019 or Tele-MANAS 14416 (both free, 24/7), contact a trusted person, or go to your nearest hospital. In an emergency, call your local emergency number.';

export const MENTAL_QA = [
  {
    slug: 'mental-health/anxiety-symptoms-and-help',
    name: 'Anxiety: Symptoms & Help',
    title: 'Anxiety: Symptoms & How to Manage It | MedDroid',
    desc: 'Anxiety — the physical and mental symptoms, simple techniques that help, and when to seek treatment. You are not alone and it is treatable. Educational, not a diagnosis.',
    h1: 'Anxiety: symptoms and how to manage it',
    lede: 'Some anxiety is normal, but when worry becomes constant or overwhelming it can affect your body, sleep and daily life. The good news: anxiety is very treatable, and simple skills can help a lot.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about anxiety',
    featTitle: 'What helps anxiety',
    features: [
      'Slow breathing (breathe out longer than you breathe in)',
      'Regular exercise, good sleep and limiting caffeine and alcohol',
      'Grounding techniques (5-4-3-2-1 senses) when worry spikes',
      'Talking therapy (CBT) — very effective for anxiety',
      'Medicine (like SSRIs) for moderate-to-severe anxiety, if a doctor advises',
    ],
    warnings: [
      'Anxiety that stops you working, studying or living normally',
      'Panic attacks, or avoiding places/people out of fear',
      'Physical symptoms you are worried about (get them checked to be sure)',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Anxiety is common and treatable.',
    note: `Talking therapy and, where needed, medicine work well — you do not have to cope alone. ${CRISIS}`,
    faqs: [
      { q: 'What are the symptoms of anxiety?', a: 'Constant worry, restlessness and difficulty concentrating, plus physical signs like a racing heart, tight chest, sweating, stomach upset and poor sleep.' },
      { q: 'How can I calm anxiety quickly?', a: 'Slow your breathing (longer out-breaths), try a grounding exercise (name things you can see, hear, feel), and remind yourself the feeling will pass. Regular exercise and sleep help long term.' },
      { q: 'When should I get help for anxiety?', a: 'When it is frequent, distressing, or affecting your daily life — a doctor or therapist can help, and treatment (therapy and/or medicine) works well.' },
    ],
    related: [['diseases/generalised-anxiety-disorder', 'Generalised anxiety disorder'], ['mental-health/how-to-manage-panic-attacks', 'Panic attacks'], ['medicines/escitalopram', 'Escitalopram'], ['mental-health/how-to-sleep-better', 'Sleep better']],
  },
  {
    slug: 'mental-health/how-to-manage-panic-attacks',
    name: 'How to Manage Panic Attacks',
    title: 'Panic Attacks: How to Stop & Manage Them | MedDroid',
    desc: 'Panic attacks — what they feel like, how to ride one out, why they are not dangerous, and how to reduce them. Educational, not a diagnosis.',
    h1: 'How to manage panic attacks',
    lede: 'A panic attack is a sudden wave of intense fear with strong physical symptoms — a pounding heart, breathlessness, dizziness. It feels frightening but is not dangerous, and it always passes.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about panic attacks',
    featTitle: 'How to ride out a panic attack',
    features: [
      'Remind yourself: this is a panic attack, it will pass, and it cannot harm me',
      'Breathe slowly — in for 4, out for 6 — to settle the body',
      'Ground yourself: name 5 things you can see, 4 you can hear, and so on',
      'Do not fight it or run away; let the wave rise and fall',
      'Longer term: therapy (CBT) greatly reduces panic attacks',
    ],
    warnings: [
      'First-ever episode, especially with chest pain in an older person — get it checked to rule out the heart',
      'Panic attacks that are frequent or make you avoid places',
      'Using alcohol or drugs to cope',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Frightening, but not dangerous.',
    note: `Panic attacks peak within minutes and pass. If chest pain is new or severe, get checked to be safe. Therapy is very effective for recurrent panic. ${CRISIS}`,
    faqs: [
      { q: 'How do I stop a panic attack?', a: 'Slow your breathing (out-breath longer than in), ground yourself in your senses, and remind yourself it will pass and cannot harm you. Do not fight it — let it rise and fall.' },
      { q: 'Are panic attacks dangerous?', a: 'No — although they feel terrifying, they are not physically dangerous and peak within minutes. A first episode with chest pain, though, should be checked to rule out the heart.' },
      { q: 'How can I prevent panic attacks?', a: 'Regular exercise, good sleep, limiting caffeine, breathing practice and CBT all reduce them. A doctor can help if they are frequent.' },
    ],
    related: [['diseases/panic-disorder', 'Panic disorder'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['diseases/phobias', 'Phobias'], ['what-is-a-normal-heart-rate', 'Normal heart rate']],
  },
  {
    slug: 'mental-health/depression-signs-and-help',
    name: 'Depression: Signs & Help',
    title: 'Depression: Signs & How to Get Help | MedDroid',
    desc: 'Depression — the signs beyond just sadness, what helps, treatments that work, and how to support recovery. You are not alone. Educational, not a diagnosis.',
    h1: 'Depression: signs and how to get help',
    lede: 'Depression is more than feeling sad — it is a persistent low mood and loss of interest that affects sleep, energy, appetite and thinking. It is common and treatable, and reaching out is a sign of strength.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about depression',
    featTitle: 'Signs of depression',
    features: [
      'Persistent low mood or emptiness for 2+ weeks',
      'Loss of interest or pleasure in things you used to enjoy',
      'Changes in sleep, appetite or energy',
      'Difficulty concentrating, guilt or feelings of worthlessness',
      'Feeling hopeless, or thoughts that life is not worth living',
    ],
    warnings: [
      'Any thoughts of self-harm or suicide — get help immediately',
      'Being unable to function at work, study or home',
      'Not eating/drinking, or neglecting self-care',
      'Symptoms lasting more than two weeks or getting worse',
    ],
    noteTitle: 'Depression is treatable — help works.',
    note: `Talking therapy, lifestyle support and, where needed, antidepressants all help, and most people recover. ${CRISIS}`,
    faqs: [
      { q: 'What are the signs of depression?', a: 'Persistent low mood, loss of interest, and changes in sleep, appetite, energy and concentration for two weeks or more, sometimes with guilt or hopelessness.' },
      { q: 'How is depression treated?', a: 'With talking therapy (like CBT), lifestyle support, and antidepressants when needed. Most people improve — often a combination works best.' },
      { q: 'Is depression a weakness?', a: 'No — it is a common medical condition, not a personal failing. Reaching out for help is a strong and important step.' },
    ],
    related: [['diseases/depression', 'Depression'], ['medicines/sertraline', 'Sertraline'], ['mental-health/suicidal-thoughts-getting-help', 'Suicidal thoughts: getting help'], ['mental-health/how-to-help-someone-with-depression', 'Helping someone with depression']],
  },
  {
    slug: 'mental-health/suicidal-thoughts-getting-help',
    name: 'Suicidal Thoughts: Getting Help',
    title: 'Suicidal Thoughts: You Are Not Alone — Get Help | MedDroid',
    desc: 'If you are having thoughts of suicide or self-harm, help is available right now. India helplines (KIRAN 1800-599-0019, Tele-MANAS 14416) and steps to stay safe.',
    h1: 'Suicidal thoughts: you are not alone',
    lede: 'If you are thinking about ending your life or harming yourself, please know that you are not alone and these feelings can change with support. Reaching out now is the bravest and most important step you can take.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid',
    featTitle: 'What to do right now',
    features: [
      'Tell someone you trust how you are feeling — you do not have to carry this alone',
      'Call a helpline: in India, KIRAN 1800-599-0019 or Tele-MANAS 14416 (free, 24/7)',
      'Remove or move away from anything you could use to harm yourself',
      'Stay with someone, or ask someone to stay with you',
      'Go to your nearest hospital, or call your local emergency number, if you feel unsafe',
    ],
    warnings: [
      'If you feel you may act on these thoughts, treat it as an emergency — call for help now',
      'Do not use alcohol or drugs to cope — they make things worse',
      'These feelings are a sign you need support, not a sign of weakness',
    ],
    noteTitle: 'Help is available, and things can get better.',
    note: `You matter, and support is available right now. In India call KIRAN 1800-599-0019 or Tele-MANAS 14416 (free, 24/7), reach out to someone you trust, or go to the nearest hospital. In an emergency, call your local emergency number. MedDroid is not a crisis service and cannot provide emergency help.`,
    faqs: [
      { q: 'I am having suicidal thoughts — what should I do right now?', a: 'Reach out immediately: tell someone you trust, call a helpline (in India, KIRAN 1800-599-0019 or Tele-MANAS 14416), and if you feel unsafe, go to a hospital or call your local emergency number. You do not have to face this alone.' },
      { q: 'Will these feelings go away?', a: 'Suicidal feelings are often linked to pain that feels unbearable in the moment, but with support and treatment they can and do ease. Please give yourself the chance by reaching out.' },
      { q: 'How can I help someone who is suicidal?', a: 'Take them seriously, listen without judgement, ask directly if they are thinking of suicide, stay with them, remove means of harm, and help them contact a helpline or doctor urgently.' },
    ],
    related: [['diseases/depression', 'Depression'], ['mental-health/depression-signs-and-help', 'Depression: signs & help'], ['mental-health/how-to-help-someone-with-depression', 'Helping someone with depression'], ['diseases/bipolar-disorder', 'Bipolar disorder']],
  },
  {
    slug: 'mental-health/how-to-help-someone-with-depression',
    name: 'Helping Someone With Depression',
    title: 'How to Help Someone With Depression | MedDroid',
    desc: 'How to support someone with depression — what to say and avoid, how to encourage help, and how to look after yourself too. Educational, not a diagnosis.',
    h1: 'How to help someone with depression',
    lede: 'Supporting someone with depression can feel hard, but your presence matters more than perfect words. Listening, patience and gently encouraging help make a real difference.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid',
    featTitle: 'How to help',
    features: [
      'Listen without judging or rushing to “fix” it',
      'Take their feelings seriously; avoid “just cheer up” or “others have it worse”',
      'Gently encourage professional help and offer to go with them',
      'Help with small practical tasks; keep in regular contact',
      'Look after your own wellbeing too — support is a marathon',
    ],
    warnings: [
      'If they mention suicide or self-harm, take it seriously and act — ask directly and get help',
      'Do not promise to keep suicidal plans a secret',
      'Watch for them withdrawing, giving things away, or saying goodbye',
      'Encourage urgent help if they are at risk',
    ],
    noteTitle: 'Your support matters.',
    note: `Encourage professional help and stay connected. If they may be at risk of suicide, act now. ${CRISIS}`,
    faqs: [
      { q: 'What should I say to someone who is depressed?', a: 'Listen and validate: “I’m here for you”, “That sounds really hard”, “You’re not alone”. Avoid minimising it or telling them to snap out of it.' },
      { q: 'How do I encourage someone to get help?', a: 'Gently suggest talking to a doctor or therapist, offer to help book or attend the appointment, and frame it as strength, not weakness.' },
      { q: 'What if they talk about suicide?', a: 'Take it seriously. Ask directly, stay with them, remove means of harm, and help them contact a helpline or emergency services immediately.' },
    ],
    related: [['mental-health/depression-signs-and-help', 'Depression: signs & help'], ['mental-health/suicidal-thoughts-getting-help', 'Suicidal thoughts: getting help'], ['diseases/depression', 'Depression'], ['diseases/grief', 'Grief']],
  },
  {
    slug: 'mental-health/how-to-reduce-stress',
    name: 'How to Reduce Stress',
    title: 'How to Reduce Stress: Practical Ways That Work | MedDroid',
    desc: 'How to reduce stress — practical, evidence-based techniques for daily life, and when stress needs more help. Educational, not a diagnosis.',
    h1: 'How to reduce stress',
    lede: 'Stress is the body’s response to pressure, and some is normal — even helpful. But ongoing stress harms sleep, mood and health, so simple daily habits to manage it are worth building.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about stress',
    featTitle: 'What genuinely reduces stress',
    features: [
      'Regular physical activity — one of the most effective stress-relievers',
      'Slow breathing, meditation or prayer, and time in nature',
      'Protect sleep and limit caffeine, alcohol and late-night screens',
      'Break big tasks into small steps; say no to overcommitment',
      'Stay connected to people you trust',
    ],
    warnings: [
      'Stress causing chest pain, panic, or persistent low mood',
      'Relying on alcohol, smoking or drugs to cope',
      'Stress that affects sleep, appetite or work for weeks',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Manage stress before it manages you.',
    note: `Small daily habits add up. If stress is persistent or overwhelming, a doctor or counsellor can help. ${CRISIS}`,
    faqs: [
      { q: 'What is the fastest way to reduce stress?', a: 'Slow breathing and a short walk or movement help within minutes. Over time, exercise, sleep, connection and limiting stimulants make the biggest difference.' },
      { q: 'Is some stress good?', a: 'Yes — short-term stress can sharpen focus and motivation. It is constant, unrelieved stress that harms health.' },
      { q: 'When should I get help for stress?', a: 'If it is persistent, affects sleep, mood, appetite or work, or you are coping with alcohol or drugs — talk to a doctor or counsellor.' },
    ],
    related: [['diseases/stress-burnout', 'Stress & burnout'], ['mental-health/dealing-with-burnout', 'Dealing with burnout'], ['mental-health/how-to-sleep-better', 'Sleep better'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety']],
  },
  {
    slug: 'mental-health/how-to-sleep-better',
    name: 'How to Sleep Better (Insomnia)',
    title: 'How to Sleep Better: Beating Insomnia | MedDroid',
    desc: 'How to sleep better — proven sleep-hygiene habits, what to avoid, and when insomnia needs a doctor. Educational, not a diagnosis.',
    h1: 'How to sleep better (insomnia)',
    lede: 'Poor sleep affects mood, focus and health, and it is very common. Most sleep problems improve with better sleep habits — sleeping pills are a last resort, not a first step.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sleep',
    featTitle: 'Sleep habits that work',
    features: [
      'Keep a regular sleep and wake time, even on weekends',
      'Avoid screens, caffeine and heavy meals late in the evening',
      'Keep the bedroom dark, quiet, cool and for sleep only',
      'If you can’t sleep after ~20 minutes, get up and do something calm',
      'Wind-down routine; get daylight and exercise during the day',
    ],
    warnings: [
      'Insomnia lasting more than a few weeks, or badly affecting your day',
      'Loud snoring with daytime sleepiness (possible sleep apnoea)',
      'Sleep problems with low mood or anxiety',
      'Relying on alcohol or sleeping pills to sleep',
    ],
    noteTitle: 'Habits first, pills last.',
    note: `Sleep-hygiene changes and CBT for insomnia work better long-term than sleeping pills, which are for short-term use only. ${CRISIS}`,
    faqs: [
      { q: 'How can I fall asleep faster?', a: 'Keep a regular schedule, avoid screens and caffeine in the evening, keep the room cool and dark, and get up if you can’t sleep rather than lying frustrated. Daytime exercise and daylight help.' },
      { q: 'Are sleeping pills safe?', a: 'They are for short-term use only and can cause dependence. Sleep-hygiene changes and CBT for insomnia are safer and more effective long term.' },
      { q: 'When should I see a doctor about sleep?', a: 'If insomnia lasts weeks, affects your day, comes with mood problems, or you snore loudly with daytime sleepiness (possible sleep apnoea).' },
    ],
    related: [['diseases/insomnia', 'Insomnia'], ['diseases/obstructive-sleep-apnoea', 'Sleep apnoea'], ['medicines/melatonin', 'Melatonin'], ['mental-health/how-to-reduce-stress', 'How to reduce stress']],
  },
  {
    slug: 'mental-health/dealing-with-burnout',
    name: 'Dealing With Burnout',
    title: 'Burnout: Signs & How to Recover | MedDroid',
    desc: 'Work burnout — the signs, how it differs from ordinary stress, and how to recover and prevent it. Educational, not a diagnosis.',
    h1: 'Dealing with burnout',
    lede: 'Burnout is exhaustion from prolonged stress, often from work — leaving you drained, cynical and less effective. Recognising it early and making changes helps you recover before it harms your health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about burnout',
    featTitle: 'Signs & recovery',
    features: [
      'Signs: constant exhaustion, cynicism/detachment, feeling ineffective',
      'Set boundaries around work hours and “always-on” messaging',
      'Take real breaks and protect sleep and downtime',
      'Reconnect with people and activities outside work',
      'Talk to your manager, a doctor or a counsellor about changes',
    ],
    warnings: [
      'Burnout tipping into depression (persistent low mood, hopelessness)',
      'Physical symptoms, or coping with alcohol/drugs',
      'Being unable to function at work or home',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Recovery needs real change, not just rest.',
    note: `Burnout improves with genuine changes to workload, boundaries and recovery — and sometimes professional help. ${CRISIS}`,
    faqs: [
      { q: 'What is the difference between stress and burnout?', a: 'Stress is feeling overloaded but still engaged; burnout is the exhaustion, detachment and reduced effectiveness that follow prolonged, unrelieved stress.' },
      { q: 'How do I recover from burnout?', a: 'Rest is a start, but lasting recovery needs real changes — boundaries, reduced load, reconnecting with life outside work, and sometimes counselling or medical help.' },
      { q: 'Can burnout lead to depression?', a: 'Yes — untreated burnout can develop into depression, so persistent low mood or hopelessness should prompt professional help.' },
    ],
    related: [['diseases/stress-burnout', 'Stress & burnout'], ['diseases/work-life-balance', 'Work-life balance'], ['mental-health/how-to-reduce-stress', 'How to reduce stress'], ['mental-health/depression-signs-and-help', 'Depression']],
  },
  {
    slug: 'mental-health/exam-stress-management',
    name: 'Exam Stress Management',
    title: 'Exam Stress: How Students Can Cope | MedDroid',
    desc: 'Managing exam stress — study and wellbeing tips for students, handling pressure and panic, and when to seek help. Educational, not a diagnosis.',
    h1: 'Exam stress: how to cope',
    lede: 'Exam pressure is intense, especially in India’s competitive system. Some nerves are normal and even helpful, but too much stress hurts both wellbeing and performance — so managing it is part of doing well.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about exam stress',
    featTitle: 'What helps students',
    features: [
      'A realistic timetable with short, focused study blocks and breaks',
      'Sleep, meals and some exercise — they improve memory and focus',
      'Slow breathing before and during exams to calm nerves',
      'Focus on effort and process, not only on marks',
      'Talk to family, friends, a teacher or counsellor if overwhelmed',
    ],
    warnings: [
      'Panic that blocks studying, or physical symptoms (not eating/sleeping)',
      'Hopelessness, or feeling that life depends only on results',
      'Any thoughts of self-harm — seek help immediately',
      'Persistent low mood or withdrawal',
    ],
    noteTitle: 'Your worth is not your marks.',
    note: `Results do not define you, and help is available if pressure feels unbearable. ${CRISIS}`,
    faqs: [
      { q: 'How can I manage exam stress?', a: 'Plan realistic study blocks with breaks, protect sleep and meals, use slow breathing to calm nerves, and keep perspective — your worth is not your marks. Talk to someone if it is too much.' },
      { q: 'How do I stop panicking in an exam?', a: 'Pause and breathe slowly, start with an easier question to build momentum, and remind yourself the feeling will pass. Preparation and sleep beforehand reduce panic.' },
      { q: 'What if the pressure feels unbearable?', a: 'Please talk to a trusted adult, teacher or counsellor. If you have any thoughts of self-harm, reach out to a helpline (in India, KIRAN 1800-599-0019 / Tele-MANAS 14416) right away.' },
    ],
    related: [['diseases/exam-work-stress', 'Exam & work stress'], ['mental-health/how-to-reduce-stress', 'How to reduce stress'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['mental-health/how-to-sleep-better', 'Sleep better']],
  },
  {
    slug: 'mental-health/social-anxiety-help',
    name: 'Social Anxiety: Help',
    title: 'Social Anxiety: Signs & How to Overcome It | MedDroid',
    desc: 'Social anxiety — more than shyness, the signs, and how therapy and gradual steps help you feel more confident. Educational, not a diagnosis.',
    h1: 'Social anxiety: how to overcome it',
    lede: 'Social anxiety is an intense fear of being judged in social situations, going beyond ordinary shyness. It is common and very treatable, and small, gradual steps build real confidence.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about social anxiety',
    featTitle: 'What helps',
    features: [
      'Gradual exposure: face feared situations in small, manageable steps',
      'Challenge the thought that everyone is judging you',
      'Slow breathing and grounding before social situations',
      'CBT is highly effective for social anxiety',
      'Medicine (SSRIs) for more severe cases, if a doctor advises',
    ],
    warnings: [
      'Avoiding work, study, or relationships because of fear',
      'Using alcohol to cope with social situations',
      'Panic attacks in social settings',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'It is treatable — small steps work.',
    note: `Avoidance feeds social anxiety, while gradual exposure and therapy shrink it. ${CRISIS}`,
    faqs: [
      { q: 'Is social anxiety just shyness?', a: 'No — it is a stronger, persistent fear of being judged that can stop you doing everyday things. Unlike ordinary shyness, it often needs and responds well to treatment.' },
      { q: 'How do I overcome social anxiety?', a: 'Face feared situations gradually rather than avoiding them, challenge anxious thoughts, practise calming techniques, and consider CBT — which is very effective.' },
      { q: 'Does medication help social anxiety?', a: 'For moderate-to-severe social anxiety, SSRIs can help alongside therapy. A doctor can advise whether it is right for you.' },
    ],
    related: [['diseases/social-anxiety-disorder', 'Social anxiety disorder'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['diseases/phobias', 'Phobias'], ['medicines/escitalopram', 'Escitalopram']],
  },
  {
    slug: 'mental-health/ocd-signs-and-help',
    name: 'OCD: Signs & Help',
    title: 'OCD: Signs & How It Is Treated | MedDroid',
    desc: 'Obsessive-compulsive disorder (OCD) — what obsessions and compulsions are, how it differs from being “neat”, and effective treatment. Educational, not a diagnosis.',
    h1: 'OCD: signs and how it is treated',
    lede: 'OCD involves unwanted, distressing thoughts (obsessions) and repetitive actions done to relieve them (compulsions). It is not about being tidy — it can be exhausting, and it is very treatable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about OCD',
    featTitle: 'Signs & treatment',
    features: [
      'Obsessions: intrusive fears (contamination, harm, doubt) that cause distress',
      'Compulsions: repeated checking, washing, counting or reassurance-seeking',
      'The main treatment is a therapy called ERP (exposure and response prevention)',
      'SSRIs (often at higher doses) also help',
      'It responds well to treatment — you can get your time and freedom back',
    ],
    warnings: [
      'Rituals taking up hours a day or dominating your life',
      'Intrusive thoughts about harm that frighten you (these are common in OCD and do not mean you will act)',
      'Severe distress or avoidance',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Not just “being neat”.',
    note: `OCD is a treatable condition, not a personality quirk. ERP therapy and SSRIs work well. ${CRISIS}`,
    faqs: [
      { q: 'What is OCD really?', a: 'A condition of distressing intrusive thoughts (obsessions) and repetitive behaviours (compulsions) done to reduce the anxiety — not simply liking things tidy.' },
      { q: 'How is OCD treated?', a: 'The most effective treatment is ERP, a form of CBT, often combined with an SSRI. Most people improve significantly.' },
      { q: 'Do intrusive thoughts mean I will act on them?', a: 'No — distressing intrusive thoughts are a common feature of OCD, and the distress they cause is actually a sign they go against your values. Treatment helps.' },
    ],
    related: [['diseases/ocd', 'OCD'], ['medicines/fluoxetine', 'Fluoxetine'], ['medicines/clomipramine', 'Clomipramine'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety']],
  },
  {
    slug: 'mental-health/ptsd-signs',
    name: 'PTSD: Signs',
    title: 'PTSD: Signs & How It Is Treated | MedDroid',
    desc: 'Post-traumatic stress disorder (PTSD) — the signs after a traumatic event, when normal reactions become PTSD, and effective treatments. Educational, not a diagnosis.',
    h1: 'PTSD: signs and treatment',
    lede: 'After a frightening or traumatic event, it is normal to feel shaken for a while. When symptoms persist and interfere with life, it may be PTSD — which is treatable, so you do not have to live with it.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about PTSD',
    featTitle: 'Common signs',
    features: [
      'Reliving the event: flashbacks, nightmares, intrusive memories',
      'Avoiding reminders of the trauma',
      'Feeling constantly on edge, jumpy or unable to sleep',
      'Negative changes in mood, guilt or numbness',
      'Symptoms lasting more than a month and affecting daily life',
    ],
    warnings: [
      'Symptoms that persist beyond a month or worsen',
      'Using alcohol or drugs to cope',
      'Being unable to function or feeling detached from life',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'PTSD is treatable.',
    note: `Trauma-focused therapies (like trauma-focused CBT and EMDR) and medication help. ${CRISIS}`,
    faqs: [
      { q: 'What are the signs of PTSD?', a: 'Reliving the trauma (flashbacks, nightmares), avoiding reminders, feeling constantly on edge, and negative mood changes — lasting more than a month and affecting daily life.' },
      { q: 'How is PTSD treated?', a: 'Trauma-focused therapies such as trauma-focused CBT and EMDR are very effective, sometimes with medication. Recovery is possible.' },
      { q: 'Is it normal to feel shaken after trauma?', a: 'Yes — distress in the first weeks is a normal reaction. It becomes PTSD when it persists and interferes with life, at which point treatment helps.' },
    ],
    related: [['diseases/ptsd', 'PTSD'], ['diseases/adjustment-disorder', 'Adjustment disorder'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['diseases/depression', 'Depression']],
  },
  {
    slug: 'mental-health/anger-management',
    name: 'Anger Management',
    title: 'Anger Management: How to Control Anger | MedDroid',
    desc: 'Anger management — why we get angry, techniques to stay in control, and when anger needs professional help. Educational, not a diagnosis.',
    h1: 'Anger management',
    lede: 'Anger is a normal, healthy emotion — the problem is how it is expressed. Learning to notice and channel anger protects your relationships, work and health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about anger',
    featTitle: 'Techniques that help',
    features: [
      'Notice early warning signs and take a timeout before reacting',
      'Slow breathing and counting down to cool the body',
      'Physical activity to release tension',
      'Express needs calmly using “I feel…” rather than blame',
      'Address underlying stress, sleep and, sometimes, depression',
    ],
    warnings: [
      'Anger leading to violence, or hurting people or property',
      'Anger damaging your relationships, job or health',
      'Anger with low mood, alcohol or drug use',
      'Any thoughts of harming yourself or others — get help immediately',
    ],
    noteTitle: 'It’s the expression, not the emotion.',
    note: `Anger that causes harm can be managed with skills and, if needed, counselling. If you fear you may hurt someone, seek help urgently. ${CRISIS}`,
    faqs: [
      { q: 'How can I control my anger?', a: 'Spot early signs, take a timeout, slow your breathing, and release tension through activity — then express your needs calmly. Addressing stress and sleep helps too.' },
      { q: 'When does anger need professional help?', a: 'If it leads to violence, damages relationships or work, or comes with low mood or substance use — counselling and anger-management programmes help.' },
      { q: 'Is anger a mental illness?', a: 'Anger itself is a normal emotion, but frequent, intense or harmful anger can be linked to conditions like depression or trauma, which are treatable.' },
    ],
    related: [['diseases/anger-management', 'Anger management'], ['mental-health/how-to-reduce-stress', 'How to reduce stress'], ['diseases/depression', 'Depression'], ['diseases/relationship-problems', 'Relationship problems']],
  },
  {
    slug: 'mental-health/coping-with-grief',
    name: 'Coping With Grief',
    title: 'Coping With Grief & Loss | MedDroid',
    desc: 'Coping with grief after losing someone — what grief feels like, that there is no “right” way, and when grief needs extra support. Educational, not a diagnosis.',
    h1: 'Coping with grief and loss',
    lede: 'Grief is the natural response to losing someone or something important. It comes in waves and has no fixed timeline — and there is no single “right” way to grieve.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about grief',
    featTitle: 'What can help',
    features: [
      'Allow yourself to feel — there is no timeline or “correct” way',
      'Lean on people you trust; talk about your loss if it helps',
      'Keep basic routines, sleep and eating where you can',
      'Remember and honour the person in ways that feel right',
      'Be patient and gentle with yourself',
    ],
    warnings: [
      'Grief that leaves you unable to function after a long time',
      'Persistent hopelessness, or feeling life is not worth living',
      'Turning to alcohol or drugs to cope',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Grief has no timetable.',
    note: `Most people gradually adjust with time and support. If grief becomes overwhelming or you feel unsafe, please reach out. ${CRISIS}`,
    faqs: [
      { q: 'How long does grief last?', a: 'There is no set timeline — it comes in waves and eases gradually for most people. Some days are harder than others, and that is normal.' },
      { q: 'Is there a right way to grieve?', a: 'No — people grieve differently, and all feelings (sadness, anger, numbness, even relief) can be part of it. Be gentle with yourself.' },
      { q: 'When does grief need extra help?', a: 'If it leaves you unable to function long-term, brings persistent hopelessness, or you turn to alcohol/drugs or have thoughts of self-harm — seek support.' },
    ],
    related: [['diseases/grief', 'Grief'], ['diseases/depression', 'Depression'], ['mental-health/depression-signs-and-help', 'Depression: signs & help'], ['diseases/loneliness', 'Loneliness']],
  },
  {
    slug: 'mental-health/how-to-stop-overthinking',
    name: 'How to Stop Overthinking',
    title: 'How to Stop Overthinking & Racing Thoughts | MedDroid',
    desc: 'How to stop overthinking — why the mind races, practical techniques to quiet it, and when it is a sign of anxiety. Educational, not a diagnosis.',
    h1: 'How to stop overthinking',
    lede: 'Overthinking — replaying the past or worrying about the future on a loop — is exhausting and rarely solves anything. A few practical skills can help you step out of the spiral.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about overthinking',
    featTitle: 'What helps quiet the mind',
    features: [
      'Notice the loop and name it: “I’m overthinking”',
      'Set a short “worry time”, then park worries until then',
      'Write thoughts down to get them out of your head',
      'Shift into action or the present moment (a walk, a task, your senses)',
      'Challenge worst-case thinking with realistic questions',
    ],
    warnings: [
      'Overthinking that stops you sleeping or functioning',
      'Constant worry across many areas of life (possible anxiety disorder)',
      'Low mood or panic alongside it',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'You can step out of the spiral.',
    note: `If overthinking is constant and affecting your life, it may be anxiety — which is very treatable. ${CRISIS}`,
    faqs: [
      { q: 'How do I stop overthinking at night?', a: 'Keep a notepad to “download” thoughts, use a set worry time earlier in the day, avoid screens before bed, and use slow breathing or grounding to shift out of the loop.' },
      { q: 'Why can’t I stop overthinking?', a: 'The mind loops when it feels a problem is unresolved. Naming it, writing it down, and shifting into action or the present break the cycle. Persistent overthinking can be part of anxiety.' },
      { q: 'Is overthinking a sign of anxiety?', a: 'It can be — constant, hard-to-control worry across many areas is a feature of anxiety disorders, which respond well to therapy and, if needed, medicine.' },
    ],
    related: [['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['diseases/generalised-anxiety-disorder', 'Generalised anxiety disorder'], ['mental-health/how-to-sleep-better', 'Sleep better'], ['mental-health/how-to-reduce-stress', 'How to reduce stress']],
  },
  {
    slug: 'mental-health/smartphone-and-social-media-addiction',
    name: 'Smartphone & Social Media Addiction',
    title: 'Smartphone & Social Media Addiction: How to Cut Back | MedDroid',
    desc: 'Smartphone and social-media overuse — the signs, effects on mood and sleep, and practical steps to build a healthier balance. Educational, not a diagnosis.',
    h1: 'Smartphone & social media addiction',
    lede: 'Phones and social media are designed to be hard to put down. When use starts harming sleep, focus, mood or relationships, small deliberate changes can restore a healthier balance.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about screen habits',
    featTitle: 'How to cut back',
    features: [
      'Track your screen time to see the real picture',
      'Turn off non-essential notifications',
      'Keep phones out of the bedroom and away from meals',
      'Set app time-limits and phone-free periods',
      'Replace scrolling with activities and people you value',
    ],
    warnings: [
      'Use that harms sleep, studies, work or relationships',
      'Feeling anxious or low when unable to check the phone',
      'Comparison and social media worsening low mood or self-esteem',
      'In children/teens: withdrawal, sleep loss, or exposure to harmful content',
    ],
    noteTitle: 'Design your use on purpose.',
    note: `Small structural changes work better than willpower alone. If low mood or anxiety underlie the overuse, support helps. ${CRISIS}`,
    faqs: [
      { q: 'How do I reduce my screen time?', a: 'Track it, turn off notifications, keep the phone out of the bedroom, set app limits and phone-free times, and fill the gaps with activities and people you enjoy.' },
      { q: 'Is social media bad for mental health?', a: 'It can worsen mood, sleep and self-esteem, especially with heavy use and comparison — but mindful, limited use is fine for most people.' },
      { q: 'How do I help my child with phone overuse?', a: 'Set clear, consistent limits, keep devices out of bedrooms, model healthy use yourself, and stay involved in what they see online.' },
    ],
    related: [['diseases/substance-addiction', 'Addiction'], ['mental-health/how-to-sleep-better', 'Sleep better'], ['mental-health/anxiety-symptoms-and-help', 'Anxiety'], ['diseases/low-self-esteem', 'Low self-esteem']],
  },
  {
    slug: 'mental-health/alcohol-dependence-help',
    name: 'Alcohol Dependence: Help',
    title: 'Alcohol Dependence: Signs & How to Get Help | MedDroid',
    desc: 'Alcohol dependence — the signs, why quitting suddenly can be dangerous, and how to get help safely. Non-judgmental support. Educational, not a diagnosis.',
    h1: 'Alcohol dependence: getting help',
    lede: 'Alcohol dependence means the body and mind have come to rely on alcohol. It is a health condition, not a moral failing — and help works. Importantly, heavy drinkers should not stop suddenly without advice.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about alcohol',
    featTitle: 'Signs & getting help',
    features: [
      'Needing more to get the same effect, or drinking to feel “normal”',
      'Struggling to cut down, or drinking despite harm',
      'Withdrawal (shakes, sweating, anxiety) when not drinking',
      'Help exists: doctors, counselling, and support groups',
      'Medical support can make cutting down or stopping safer',
    ],
    warnings: [
      'Do NOT stop heavy drinking abruptly without medical advice — withdrawal can cause seizures and be dangerous',
      'Confusion, fits, hallucinations or severe shaking (medical emergency)',
      'Vomiting blood or yellow skin (liver damage)',
      'Any thoughts of self-harm — seek help immediately',
    ],
    noteTitle: 'Get medical advice before stopping heavy drinking.',
    note: `Sudden withdrawal from heavy drinking can be life-threatening, so seek medical help to do it safely. Treatment and support work. ${CRISIS}`,
    faqs: [
      { q: 'How do I know if I’m dependent on alcohol?', a: 'Signs include needing more for the same effect, being unable to cut down, drinking despite harm, and withdrawal symptoms (shakes, sweating, anxiety) when you stop.' },
      { q: 'Is it dangerous to stop drinking suddenly?', a: 'For heavy, dependent drinkers, yes — abrupt withdrawal can cause seizures and be life-threatening. Get medical advice to reduce or stop safely.' },
      { q: 'Where can I get help for drinking?', a: 'A doctor can guide safe reduction and treatment, and counselling and support groups help. Reaching out is a strong first step, not a failure.' },
    ],
    related: [['diseases/alcohol-use-disorder', 'Alcohol use disorder'], ['diseases/alcoholic-liver-disease', 'Alcoholic liver disease'], ['diseases/substance-addiction', 'Substance addiction'], ['mental-health/depression-signs-and-help', 'Depression']],
  },
  {
    slug: 'mental-health/when-to-see-a-psychiatrist',
    name: 'When to See a Psychiatrist',
    title: 'Therapist or Psychiatrist? When to Get Help | MedDroid',
    desc: 'When to see a psychiatrist vs a psychologist/therapist, what to expect, and how to take the first step. Educational, not a diagnosis.',
    h1: 'When to see a psychiatrist or therapist',
    lede: 'Knowing who to turn to for mental-health support can be confusing. Here is a simple guide to the difference between a therapist and a psychiatrist, and when to seek help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about getting help',
    featTitle: 'Who does what & when to go',
    features: [
      'Psychologist/counsellor/therapist: talking therapies (like CBT); no medicines',
      'Psychiatrist: a medical doctor who can diagnose and prescribe medicine',
      'Your GP/family doctor is a good first step and can refer you',
      'Go when problems are persistent, distressing, or affecting daily life',
      'You can seek help early — you do not need to be “in crisis”',
    ],
    warnings: [
      'Any thoughts of self-harm or suicide — seek help urgently',
      'Being unable to function, or symptoms rapidly worsening',
      'Hearing/seeing things others do not, or losing touch with reality',
      'Severe mood swings or risky behaviour',
    ],
    noteTitle: 'Asking for help is a strength.',
    note: `You do not need to wait until things are severe. A doctor can guide you to the right support. ${CRISIS}`,
    faqs: [
      { q: 'What is the difference between a psychologist and a psychiatrist?', a: 'A psychologist/therapist provides talking therapies; a psychiatrist is a medical doctor who can diagnose and prescribe medicine. Many people benefit from both.' },
      { q: 'When should I see a mental-health professional?', a: 'When problems are persistent, distressing, or affecting your work, studies, relationships or daily life — you do not need to wait for a crisis.' },
      { q: 'Do I need medicine or therapy?', a: 'It depends on the problem and its severity. Mild issues often respond to therapy and lifestyle; moderate-to-severe conditions may benefit from medicine too. A doctor helps decide.' },
    ],
    related: [['diseases/depression', 'Depression'], ['diseases/generalised-anxiety-disorder', 'Anxiety disorder'], ['mental-health/are-antidepressants-addictive', 'Are antidepressants addictive?'], ['diseases/bipolar-disorder', 'Bipolar disorder']],
  },
  {
    slug: 'mental-health/are-antidepressants-addictive',
    name: 'Are Antidepressants Addictive?',
    title: 'Are Antidepressants Addictive? The Facts | MedDroid',
    desc: 'Are antidepressants addictive? The facts — dependence vs discontinuation, why you should not stop suddenly, and common myths. Educational, not a diagnosis.',
    h1: 'Are antidepressants addictive?',
    lede: 'A common worry that stops people getting help is the fear that antidepressants are addictive. They are not addictive in the way drugs or alcohol are — but they should be stopped gradually, not suddenly.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about antidepressants',
    featTitle: 'The facts',
    features: [
      'Antidepressants (SSRIs) are not addictive — you do not crave them or need ever-higher doses',
      'Stopping suddenly can cause temporary “discontinuation” symptoms, so they are tapered',
      'They usually take 4–6 weeks to work fully',
      'They do not change your personality or make you “high”',
      'Treatment often continues for months after you feel well, to prevent relapse',
    ],
    warnings: [
      'Do not stop antidepressants suddenly — reduce gradually with your doctor',
      'Worsening mood or thoughts of self-harm, especially early in treatment — seek help urgently',
      'Tell your doctor about side effects rather than just stopping',
    ],
    noteTitle: 'Not addictive — but taper, don’t stop suddenly.',
    note: `Fear of addiction should not stop you getting effective treatment. Stop only gradually, guided by a doctor. ${CRISIS}`,
    faqs: [
      { q: 'Are antidepressants addictive?', a: 'No — they do not cause cravings or need ever-increasing doses like addictive drugs. However, stopping suddenly can cause temporary withdrawal-like symptoms, so they are reduced gradually.' },
      { q: 'Will antidepressants change my personality?', a: 'No — they aim to lift the depression or anxiety so you feel more like yourself, not to make you “high” or someone different.' },
      { q: 'How long will I need to take them?', a: 'Often for several months after you feel well, to prevent relapse. Your doctor will guide when and how to reduce them safely.' },
    ],
    related: [['medicines/sertraline', 'Sertraline'], ['medicines/escitalopram', 'Escitalopram'], ['mental-health/depression-signs-and-help', 'Depression'], ['mental-health/when-to-see-a-psychiatrist', 'When to see a psychiatrist']],
  },
];
