// Diet & nutrition Q&A cluster for MedDroid. Practical, India-aware, honest
// (no fad/detox claims). Full page objects (same shape gen-landing's page()
// consumes). Educational only, not a diagnosis or a personalised diet plan.

export const NUTRITION_QA = [
  {
    slug: 'nutrition/how-to-lose-weight-safely',
    name: 'How to Lose Weight Safely',
    title: 'How to Lose Weight Safely & Keep It Off | MedDroid',
    desc: 'How to lose weight safely — realistic calorie and food changes, activity, and why crash diets fail. Sustainable, evidence-based tips. Educational, not a diagnosis.',
    h1: 'How to lose weight safely',
    lede: 'Safe, lasting weight loss comes from a modest, steady calorie deficit and habits you can keep — not crash diets. Losing about half a kilo a week protects muscle and is far easier to maintain.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about weight loss',
    featTitle: 'What actually works',
    features: [
      'Eat more vegetables, dal/pulses, fruit and protein; fewer fried foods and sweets',
      'Cut sugary drinks and refined carbs (white rice, maida, sugar)',
      'Watch portion sizes; use a smaller plate',
      'Be active most days — walking counts; add strength training to keep muscle',
      'Aim for gradual loss (~0.5 kg/week); protect sleep and manage stress',
    ],
    warnings: [
      'Very-low-calorie or crash diets usually fail and can be unsafe',
      'Rapid unintended weight loss (not from dieting) — see a doctor',
      'Weight issues with a thyroid or hormone condition may need treatment',
      'Beware slimming pills, teas and “fat-cutter” products',
    ],
    noteTitle: 'Slow and steady wins.',
    note: 'Sustainable habits beat quick fixes. If weight is linked to a medical condition (thyroid, PCOS, medicines), your doctor can help. MedDroid gives general information, not a personalised diet plan.',
    faqs: [
      { q: 'What is the fastest safe way to lose weight?', a: 'A steady deficit of about 500 calories a day gives ~0.5 kg loss per week — safe and sustainable. Faster crash diets usually rebound and can lose muscle.' },
      { q: 'Which foods help weight loss?', a: 'High-fibre, high-protein foods (vegetables, dal, pulses, eggs, curd) keep you full, while cutting sugary drinks, fried food and refined carbs makes the biggest difference.' },
      { q: 'Do slimming pills and teas work?', a: 'Most are ineffective or unsafe. Real, lasting weight loss comes from food, activity and habits — occasionally with doctor-prescribed medicine for obesity.' },
    ],
    related: [['diseases/obesity', 'Obesity'], ['nutrition/how-to-reduce-belly-fat', 'How to reduce belly fat'], ['diseases/metabolic-syndrome', 'Metabolic syndrome'], ['mens-health/how-to-build-muscle-safely', 'Build muscle safely']],
  },
  {
    slug: 'nutrition/how-to-reduce-belly-fat',
    name: 'How to Reduce Belly Fat',
    title: 'How to Reduce Belly Fat (Honestly) | MedDroid',
    desc: 'How to reduce belly fat — why spot reduction is a myth, what really works, and why belly fat matters for health. Honest, evidence-based. Educational, not a diagnosis.',
    h1: 'How to reduce belly fat',
    lede: 'You cannot “spot reduce” belly fat with crunches — fat is lost from the whole body. But belly fat responds well to the same steady habits that reduce overall weight, and losing it genuinely improves health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about belly fat',
    featTitle: 'What genuinely helps',
    features: [
      'Overall calorie deficit (there is no spot-reduction shortcut)',
      'Cut sugary drinks, sweets and refined carbs',
      'More protein and fibre; watch portion sizes',
      'Regular activity plus strength training',
      'Good sleep and less stress (both affect belly fat)',
    ],
    warnings: [
      'A large waist raises the risk of diabetes and heart disease',
      'Sudden abdominal swelling (not fat) needs a doctor',
      'Beware “belly fat burner” pills, belts and creams — they do not work',
    ],
    noteTitle: 'Spot reduction is a myth.',
    note: 'Endless crunches will not melt belly fat — whole-body fat loss does. Belly fat matters for health, so it is worth reducing. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'How do I lose belly fat specifically?', a: 'You cannot target it — belly fat falls as overall body fat drops. A calorie deficit, less sugar and refined carbs, more protein and fibre, activity and good sleep all help.' },
      { q: 'Do belly-fat belts, creams or pills work?', a: 'No — these do not remove fat. Whole-body habits (diet, activity, sleep) are what reduce belly fat.' },
      { q: 'Why is belly fat unhealthy?', a: 'Fat around the organs raises the risk of type 2 diabetes, high blood pressure and heart disease, so reducing it improves your health markers.' },
    ],
    related: [['nutrition/how-to-lose-weight-safely', 'How to lose weight safely'], ['diseases/obesity', 'Obesity'], ['diseases/metabolic-syndrome', 'Metabolic syndrome'], ['diseases/fatty-liver', 'Fatty liver']],
  },
  {
    slug: 'nutrition/how-to-gain-weight-healthily',
    name: 'How to Gain Weight Healthily',
    title: 'How to Gain Weight Healthily | MedDroid',
    desc: 'How to gain weight in a healthy way — nutrient-dense foods, a calorie surplus, strength training, and when to check for a cause. Educational, not a diagnosis.',
    h1: 'How to gain weight healthily',
    lede: 'Gaining weight healthily means adding muscle and nutrient-dense calories — not junk food. A modest calorie surplus with protein and strength training builds weight you actually want.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about gaining weight',
    featTitle: 'How to do it well',
    features: [
      'Eat a little more than you burn — frequent, calorie-dense meals',
      'Nutrient-dense choices: nuts, dairy, eggs, dal, paneer, ghee, whole grains',
      'Enough protein plus strength training to gain muscle, not just fat',
      'Healthy add-ons: milkshakes, dry fruits, nut butters',
      'Be patient — steady gain is healthier than rapid gain',
    ],
    warnings: [
      'Unexplained weight loss (not from low intake) — see a doctor',
      'Weight loss with fever, night sweats, or tummy problems',
      'Being underweight with tiredness (check thyroid, diabetes, anaemia, coeliac)',
      'Avoid junk-food “bulking” — it harms heart and metabolic health',
    ],
    noteTitle: 'Rule out a cause if you can’t gain.',
    note: 'Difficulty gaining weight can have medical causes (thyroid, diabetes, coeliac, infections), so get checked if eating more does not help. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'How can I gain weight fast?', a: 'Eat frequent, calorie-dense, nutritious meals in a modest surplus, add protein and strength training to build muscle, and be consistent. Avoid junk food, which adds unhealthy fat.' },
      { q: 'Why am I not gaining weight even though I eat a lot?', a: 'A fast metabolism, not eating as much as you think, or a medical cause (thyroid, diabetes, coeliac disease, infection) can be responsible — worth a check if it persists.' },
      { q: 'What foods help healthy weight gain?', a: 'Nuts, dairy, eggs, dal, paneer, ghee, whole grains, dry fruits and nut butters give nutrient-dense calories.' },
    ],
    related: [['diseases/malnutrition', 'Malnutrition'], ['diseases/hyperthyroidism', 'Hyperthyroidism'], ['diseases/coeliac-disease', 'Coeliac disease'], ['nutrition/high-protein-vegetarian-foods', 'High-protein veg foods']],
  },
  {
    slug: 'nutrition/diabetic-diet-chart',
    name: 'Diabetic Diet: What to Eat',
    title: 'Diabetic Diet: What to Eat & Avoid | MedDroid',
    desc: 'Diabetes diet — foods to eat and avoid, how to plan meals to steady blood sugar, and the Indian-diet swaps that help. Educational, not a personalised plan.',
    h1: 'Diabetic diet: what to eat and avoid',
    lede: 'Diet is central to controlling diabetes. The aim is steady blood sugar — favouring high-fibre, lower-glycaemic foods, controlling portions of carbs, and cutting sugar — without giving up balanced, enjoyable meals.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about a diabetic diet',
    featTitle: 'Eat more / eat less',
    features: [
      'Eat: vegetables, dal/pulses, whole grains (ragi, oats, whole wheat), protein, curd',
      'Choose whole fruit over juice; nuts as snacks',
      'Limit: sugar, sweets, sugary drinks, white rice and maida, fried foods',
      'Control carb portions and space meals evenly',
      'Pair carbs with protein/fibre to slow the sugar rise',
    ],
    warnings: [
      'Very high sugar with vomiting or drowsiness (emergency)',
      'Frequent low-sugar episodes on medicine (adjust with your doctor)',
      'Do not stop diabetes medicine when starting a diet — adjust with your doctor',
      'A non-healing foot wound in diabetes',
    ],
    noteTitle: 'Diet works with medicine, not instead of it.',
    note: 'A good diet can reduce medicine needs, but change medicines only with your doctor. HbA1c and sugar tests track your control. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods should a diabetic avoid?', a: 'Sugar, sweets, sugary drinks and juices, white rice and maida, and fried foods raise sugar quickly — limit them and choose high-fibre whole grains and vegetables instead.' },
      { q: 'Can I eat rice with diabetes?', a: 'In controlled portions, yes — but smaller servings, ideally with dal, vegetables and protein to slow the sugar rise. Whole grains (brown rice, millets) are better choices.' },
      { q: 'Can diet reverse diabetes?', a: 'Type 2 diabetes can sometimes go into remission with significant weight loss and diet change, especially early on — but always manage this with your doctor.' },
    ],
    related: [['diseases/diabetes-diet', 'Diabetes diet'], ['diseases/type-2-diabetes', 'Type 2 diabetes'], ['how-to-lower-blood-sugar', 'How to lower blood sugar'], ['blood-tests/hba1c', 'HbA1c test']],
  },
  {
    slug: 'nutrition/diet-for-high-cholesterol',
    name: 'Diet for High Cholesterol',
    title: 'Diet for High Cholesterol: Foods to Eat & Avoid | MedDroid',
    desc: 'High-cholesterol diet — the foods that lower cholesterol, what to cut, and heart-healthy Indian swaps. Educational, not a personalised plan.',
    h1: 'Diet for high cholesterol',
    lede: 'What you eat has a real effect on cholesterol. Cutting saturated and trans fats while adding fibre and healthy fats lowers “bad” LDL cholesterol and protects your heart.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about cholesterol diet',
    featTitle: 'Eat more / eat less',
    features: [
      'Eat: oats, beans, dal, fruit, vegetables (soluble fibre lowers cholesterol)',
      'Healthy fats: nuts, seeds, and oils like mustard, olive or rice-bran',
      'Oily fish, or plant omega-3 sources',
      'Limit: fried foods, ghee/butter/vanaspati, fatty meat, full-fat dairy',
      'Avoid trans fats (bakery items, vanaspati) and cut sugar',
    ],
    warnings: [
      'Very high cholesterol or a family history may need medicine (statins)',
      'Chest pain, breathlessness or a heart-disease history — see a doctor',
      'Do not stop prescribed statins when improving your diet without advice',
    ],
    noteTitle: 'Diet plus medicine when needed.',
    note: 'Diet lowers cholesterol, but higher-risk people also benefit from statins. A lipid profile tracks progress. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods lower cholesterol?', a: 'Soluble fibre (oats, beans, dal, fruit), nuts, healthy oils and oily fish lower cholesterol, especially when they replace fried and fatty foods.' },
      { q: 'What should I avoid with high cholesterol?', a: 'Fried foods, vanaspati/trans fats, fatty meat, full-fat dairy and excess ghee/butter, plus sugary foods that worsen triglycerides.' },
      { q: 'Is ghee bad for cholesterol?', a: 'Ghee is high in saturated fat, so use it in small amounts. It is not poison, but large quantities can raise cholesterol — moderation is key.' },
    ],
    related: [['diseases/high-cholesterol-diet', 'High-cholesterol diet'], ['diseases/high-cholesterol', 'High cholesterol'], ['how-to-lower-cholesterol', 'How to lower cholesterol'], ['medicines/atorvastatin', 'Atorvastatin']],
  },
  {
    slug: 'nutrition/diet-for-high-blood-pressure',
    name: 'Diet for High Blood Pressure',
    title: 'Diet for High Blood Pressure (Low-Salt/DASH) | MedDroid',
    desc: 'High blood pressure diet — cutting salt, the DASH approach, potassium-rich foods, and Indian-diet tips to lower BP. Educational, not a personalised plan.',
    h1: 'Diet for high blood pressure',
    lede: 'Cutting salt and eating more fruit, vegetables and wholegrains genuinely lowers blood pressure. The DASH eating pattern is proven to help — and it fits well with a balanced Indian diet.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about BP diet',
    featTitle: 'Eat more / eat less',
    features: [
      'Cut salt: aim well under one teaspoon a day; avoid pickles, papad, processed and packaged foods',
      'Eat more fruit, vegetables, dal and wholegrains',
      'Potassium-rich foods (banana, coconut water, vegetables) help — unless you have kidney disease',
      'Low-fat dairy and nuts (unsalted)',
      'Limit alcohol; cut sugary and fried foods',
    ],
    warnings: [
      'A reading of 180/120 or higher, or symptoms — urgent',
      'People with kidney disease should not increase potassium without advice',
      'Do not stop BP medicine when improving diet — adjust with your doctor',
    ],
    noteTitle: 'Salt is the big lever.',
    note: 'Most Indians eat far more salt than needed, largely hidden in processed foods. Diet works alongside any prescribed BP medicine. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods lower blood pressure?', a: 'Fruit, vegetables, dal, wholegrains, low-fat dairy and potassium-rich foods, combined with a low-salt diet (the DASH pattern), lower blood pressure.' },
      { q: 'How much salt is safe?', a: 'Aim for less than about 5 g (one teaspoon) of salt a day. Much of it is hidden in pickles, papad, namkeen and packaged foods.' },
      { q: 'Does eating less salt really help?', a: 'Yes — reducing salt lowers blood pressure for most people, and the effect is greater in those who are salt-sensitive.' },
    ],
    related: [['diseases/hypertension', 'Hypertension'], ['how-to-lower-blood-pressure', 'How to lower blood pressure'], ['normal-blood-pressure-by-age', 'Normal BP by age'], ['diseases/chronic-kidney-disease', 'Chronic kidney disease']],
  },
  {
    slug: 'nutrition/diet-for-high-uric-acid',
    name: 'Diet for High Uric Acid (Gout)',
    title: 'Diet for High Uric Acid & Gout: Foods to Avoid | MedDroid',
    desc: 'High uric acid / gout diet — the high-purine foods to limit, what to eat more of, and the drinks that matter. Educational, not a personalised plan.',
    h1: 'Diet for high uric acid (gout)',
    lede: 'Diet can help control uric acid and reduce gout attacks. The idea is to cut high-purine foods and sugary drinks, stay hydrated, and keep a healthy weight — alongside any medicine your doctor prescribes.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about uric acid diet',
    featTitle: 'Limit / favour',
    features: [
      'Limit: red meat, organ meats, and seafood/shellfish (high purine)',
      'Cut sugary drinks and fructose (they raise uric acid)',
      'Limit alcohol, especially beer',
      'Favour: low-fat dairy, vegetables, whole grains, fruit (like cherries)',
      'Drink plenty of water and keep a healthy weight',
    ],
    warnings: [
      'A hot, red, very painful joint (acute gout) — treat and see a doctor',
      'Diet alone may not be enough — many need urate-lowering medicine',
      'Do not start/stop gout medicine during an attack without advice',
    ],
    noteTitle: 'Diet helps, but is often not enough alone.',
    note: 'For recurring gout, urate-lowering medicine is usually needed alongside diet. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods should I avoid with high uric acid?', a: 'Red meat, organ meats, shellfish, sugary drinks and excess alcohol (especially beer) raise uric acid — limit them.' },
      { q: 'What foods lower uric acid?', a: 'Low-fat dairy, vegetables, whole grains, plenty of water, and fruit like cherries help. Weight loss also lowers uric acid.' },
      { q: 'Can diet cure gout?', a: 'Diet reduces attacks, but many people with recurrent gout also need urate-lowering medicine (like allopurinol or febuxostat) for good control.' },
    ],
    related: [['diseases/gout', 'Gout'], ['medicines/allopurinol', 'Allopurinol'], ['medicines/febuxostat', 'Febuxostat'], ['blood-tests/uric-acid', 'Uric acid test']],
  },
  {
    slug: 'nutrition/thyroid-diet',
    name: 'Thyroid Diet',
    title: 'Thyroid Diet: Foods to Eat & Avoid | MedDroid',
    desc: 'Thyroid diet — foods that support thyroid health, the truth about goitrogens and iodine, and what actually matters. Honest and evidence-based. Not a personalised plan.',
    h1: 'Thyroid diet: what really matters',
    lede: 'Diet supports thyroid health but does not replace thyroid medicine. A few nutrients (iodine, selenium) matter, and there is a lot of myth around “thyroid superfoods” — here is the honest picture.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about thyroid diet',
    featTitle: 'What to know',
    features: [
      'Use iodised salt (iodine is essential for the thyroid)',
      'A balanced diet with enough selenium (nuts), zinc and iron',
      'Cooked cruciferous vegetables (cabbage, cauliflower) are fine in normal amounts',
      'Take levothyroxine on an empty stomach, apart from calcium/iron and soy',
      'No single food cures thyroid disease',
    ],
    warnings: [
      'Diet does not replace thyroid medicine — do not stop it',
      'Very high-dose iodine or kelp supplements can harm the thyroid',
      'Unexplained tiredness, weight or mood changes — get thyroid tests',
    ],
    noteTitle: 'Food supports, medicine treats.',
    note: 'An underactive thyroid needs levothyroxine, not just diet. Beware exaggerated “thyroid diet” claims. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods are good for the thyroid?', a: 'A balanced diet with iodised salt, selenium (nuts), zinc and iron supports thyroid health. No single food fixes a thyroid problem.' },
      { q: 'Should I avoid cabbage and cauliflower with thyroid problems?', a: 'Normal amounts, especially cooked, are fine. Only very large raw quantities could affect the thyroid, mainly if iodine is deficient.' },
      { q: 'Can diet cure hypothyroidism?', a: 'No — an underactive thyroid needs levothyroxine. Diet supports overall health but does not replace the medicine.' },
    ],
    related: [['diseases/hypothyroidism', 'Hypothyroidism'], ['diseases/thyroid-disorders', 'Thyroid disorders'], ['medicines/levothyroxine', 'Levothyroxine'], ['blood-tests/thyroid-function-test-tft', 'Thyroid function test']],
  },
  {
    slug: 'nutrition/pcos-diet',
    name: 'PCOS Diet',
    title: 'PCOS Diet: What to Eat to Manage PCOS | MedDroid',
    desc: 'PCOS diet — how eating for insulin resistance helps periods, weight and skin, plus practical Indian-diet tips. Educational, not a personalised plan.',
    h1: 'PCOS diet: eating to manage PCOS',
    lede: 'Because PCOS is closely linked to insulin resistance, a diet that steadies blood sugar helps hormones, periods, weight and skin. Even modest weight loss can restore regular cycles.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about PCOS diet',
    featTitle: 'What helps',
    features: [
      'Lower refined carbs and sugar (white rice, maida, sweets, sugary drinks)',
      'Favour whole grains, dal/pulses, vegetables and protein',
      'Include fibre and healthy fats (nuts, seeds)',
      'Regular meals; pair carbs with protein to steady sugar',
      'Combine with activity — even modest weight loss helps a lot',
    ],
    warnings: [
      'Very irregular or absent periods (needs medical review)',
      'Signs of high blood sugar (excess thirst, passing lots of urine)',
      'Difficulty conceiving after a year of trying',
    ],
    noteTitle: 'Diet is powerful in PCOS.',
    note: 'A low-glycaemic diet plus activity improves insulin resistance, which is at the heart of PCOS. Combine with any treatment your doctor advises. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What is the best diet for PCOS?', a: 'A balanced, lower-glycaemic diet — reduced refined carbs and sugar, with whole grains, pulses, vegetables, protein and healthy fats — helps insulin resistance and hormones.' },
      { q: 'Can diet help me lose weight with PCOS?', a: 'Yes — and even modest weight loss can restore periods, improve fertility and reduce symptoms. It can be harder with PCOS, so be patient and consistent.' },
      { q: 'Should I cut carbs completely for PCOS?', a: 'No need to cut them completely — choose better carbs (whole grains, pulses) in controlled portions rather than refined ones, and pair them with protein.' },
    ],
    related: [['diseases/pcos', 'PCOS'], ['womens-health/pcos-management', 'Managing PCOS'], ['nutrition/how-to-lose-weight-safely', 'How to lose weight safely'], ['medicines/metformin', 'Metformin']],
  },
  {
    slug: 'nutrition/foods-to-increase-hemoglobin',
    name: 'Foods to Increase Hemoglobin',
    title: 'Foods to Increase Hemoglobin (Iron-Rich Foods) | MedDroid',
    desc: 'Iron-rich foods to raise hemoglobin — the best vegetarian and non-veg sources, how to absorb iron better, and when supplements are needed. Not a personalised plan.',
    h1: 'Foods to increase hemoglobin',
    lede: 'Low hemoglobin (anaemia) is very common, especially in women and children. Iron-rich foods help — and pairing them with vitamin C, while avoiding tea/coffee at meals, boosts how much iron you absorb.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about iron-rich foods',
    featTitle: 'Iron-rich foods & absorption',
    features: [
      'Vegetarian: dal, rajma, chana, spinach and greens, jaggery, dates, dry fruits',
      'Non-veg: liver, red meat, chicken, fish, eggs (well absorbed)',
      'Add vitamin C (lemon, amla, citrus) to boost iron absorption',
      'Avoid tea/coffee with meals (they block iron)',
      'Iron + folic acid supplements when a doctor advises',
    ],
    warnings: [
      'Very low hemoglobin with breathlessness, dizziness or a fast heartbeat — see a doctor',
      'Anaemia with heavy periods, or blood in stool (find the cause)',
      'Diet alone may not correct significant anaemia — supplements are often needed',
    ],
    noteTitle: 'Find the cause of low hemoglobin.',
    note: 'Food helps, but real anaemia usually needs iron supplements and finding the cause (like blood loss or poor absorption). A blood test guides treatment. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'Which foods increase hemoglobin fastest?', a: 'Iron-rich foods (dal, greens, red meat, liver, eggs) with vitamin C for absorption help, but significant anaemia usually needs iron supplements to rise quickly.' },
      { q: 'Does spinach really boost iron?', a: 'Spinach and greens contain iron, but plant (non-haem) iron is less well absorbed — pair them with vitamin C and avoid tea/coffee at meals to get more from them.' },
      { q: 'When do I need iron tablets instead of food?', a: 'When hemoglobin is genuinely low, diet alone is usually too slow — iron (often with folic acid) tablets are needed, plus finding the cause of the anaemia.' },
    ],
    related: [['diseases/iron-deficiency-anaemia', 'Iron-deficiency anaemia'], ['diseases/anaemia', 'Anaemia'], ['medicines/iron-folic-acid', 'Iron & folic acid'], ['blood-tests/hemoglobin', 'Hemoglobin test']],
  },
  {
    slug: 'nutrition/high-protein-vegetarian-foods',
    name: 'High-Protein Vegetarian Foods',
    title: 'High-Protein Vegetarian Foods (Indian) | MedDroid',
    desc: 'High-protein vegetarian foods — the best Indian veg sources, how much protein you need, and how to combine them. Educational, not a personalised plan.',
    h1: 'High-protein vegetarian foods',
    lede: 'You can easily meet your protein needs on a vegetarian diet with the right foods. Combining pulses, dairy, soya and grains gives good-quality protein for muscle, recovery and overall health.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about protein',
    featTitle: 'Top vegetarian protein sources',
    features: [
      'Pulses: dal, rajma, chana, moong, soya (soya is especially high)',
      'Dairy: milk, curd, paneer',
      'Nuts and seeds: peanuts, almonds, pumpkin seeds',
      'Whole grains and combinations (dal + rice/roti make complete protein)',
      'Eggs (for eggetarians) and tofu/soya products',
    ],
    warnings: [
      'Kidney disease: check protein needs with a doctor',
      'Relying only on grains can leave protein low — include pulses/dairy/soya',
      'Growing children, pregnancy and the elderly have higher protein needs',
    ],
    noteTitle: 'Combine sources for complete protein.',
    note: 'Most adults need roughly 0.8–1 g of protein per kg body weight daily (more if very active). Combining pulses with grains and dairy covers all amino acids. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What are the best vegetarian protein sources in India?', a: 'Dal and pulses, soya, paneer, milk, curd, nuts and seeds — and eggs if you eat them. Combining dal with rice or roti gives complete protein.' },
      { q: 'How much protein do I need daily?', a: 'Roughly 0.8–1 g per kg of body weight for most adults, and more (around 1.6–2.2 g/kg) if you are building muscle or very active.' },
      { q: 'Can vegetarians get enough protein?', a: 'Yes — with a mix of pulses, dairy, soya, nuts and grains, vegetarians can easily meet their protein needs.' },
    ],
    related: [['mens-health/how-to-build-muscle-safely', 'Build muscle safely'], ['mens-health/are-protein-supplements-safe', 'Are protein supplements safe?'], ['nutrition/how-to-gain-weight-healthily', 'Gain weight healthily'], ['diseases/malnutrition', 'Malnutrition']],
  },
  {
    slug: 'nutrition/vitamin-b12-foods',
    name: 'Vitamin B12 Foods',
    title: 'Vitamin B12 Foods (& Vegetarian Sources) | MedDroid',
    desc: 'Vitamin B12 foods — the best sources, why vegetarians often fall short, signs of deficiency, and when to supplement. Educational, not a personalised plan.',
    h1: 'Vitamin B12 foods',
    lede: 'Vitamin B12 is vital for blood and nerves, and deficiency is very common in India — especially among vegetarians, because B12 comes mainly from animal foods. Knowing the sources (and when to supplement) matters.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about vitamin B12',
    featTitle: 'Sources & who is at risk',
    features: [
      'Best sources: eggs, dairy (milk, curd, paneer), fish, meat',
      'Vegetarians rely on dairy/eggs and fortified foods — often not enough',
      'Pure vegetarians/vegans usually need a B12 supplement',
      'Signs of deficiency: tiredness, tingling/numbness, poor memory, anaemia',
      'A blood test confirms deficiency',
    ],
    warnings: [
      'Numbness, tingling or balance problems (nerve effects) — get checked',
      'Deficiency with anaemia or memory problems',
      'Long-term metformin or acid-reducer use can lower B12',
    ],
    noteTitle: 'Vegetarians: watch your B12.',
    note: 'Because B12 is mainly in animal foods, many Indian vegetarians are deficient and benefit from supplements. Nerve symptoms need prompt treatment. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'Which foods are high in vitamin B12?', a: 'Eggs, dairy, fish and meat. Plant foods do not reliably contain B12, so vegetarians rely on dairy/eggs and fortified foods, and vegans need a supplement.' },
      { q: 'How do vegetarians get enough B12?', a: 'Through dairy and eggs plus fortified foods — but many still fall short and need a B12 supplement, ideally guided by a blood test.' },
      { q: 'What are the signs of B12 deficiency?', a: 'Tiredness, tingling or numbness, poor memory or concentration, a sore tongue, and anaemia. Nerve symptoms need prompt treatment.' },
    ],
    related: [['diseases/vitamin-b12-deficiency', 'Vitamin B12 deficiency'], ['medicines/methylcobalamin-b12', 'Vitamin B12'], ['blood-tests/vitamin-b12', 'Vitamin B12 test'], ['diseases/anaemia', 'Anaemia']],
  },
  {
    slug: 'nutrition/calcium-rich-foods',
    name: 'Calcium-Rich Foods',
    title: 'Calcium-Rich Foods for Strong Bones | MedDroid',
    desc: 'Calcium-rich foods — the best dairy and vegetarian sources, how much you need, and why vitamin D matters for absorption. Educational, not a personalised plan.',
    h1: 'Calcium-rich foods',
    lede: 'Calcium keeps bones and teeth strong, and needs are higher in growing children, pregnancy and older age. Vitamin D is essential to absorb it, so the two go together.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about calcium',
    featTitle: 'Best sources',
    features: [
      'Dairy: milk, curd, paneer, cheese',
      'Vegetarian: ragi (finger millet), sesame (til), almonds, tofu',
      'Green leafy vegetables and beans',
      'Fish with edible bones (for non-vegetarians)',
      'Get enough vitamin D (sun + food) to absorb calcium',
    ],
    warnings: [
      'Bone pain, easy fractures or loss of height (possible osteoporosis)',
      'Numbness, tingling or muscle cramps (possible low calcium)',
      'Very high-dose calcium supplements without advice (kidney-stone risk)',
    ],
    noteTitle: 'Calcium needs vitamin D.',
    note: 'Calcium and vitamin D work together for bone health. Supplements help when diet and sun are not enough, especially in menopause and older age. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'Which foods are high in calcium?', a: 'Milk, curd, paneer and cheese are richest; vegetarian options include ragi, sesame seeds, almonds, tofu and green leafy vegetables.' },
      { q: 'How much calcium do I need?', a: 'Roughly 1000 mg a day for most adults, more in older age and pregnancy. Get it from food first, with supplements if needed.' },
      { q: 'Why do I need vitamin D with calcium?', a: 'Vitamin D helps the body absorb calcium — without enough, even a calcium-rich diet does not protect bones well.' },
    ],
    related: [['medicines/calcium-supplement', 'Calcium supplement'], ['medicines/vitamin-d3', 'Vitamin D3'], ['diseases/osteoporosis', 'Osteoporosis'], ['diseases/vitamin-d-deficiency', 'Vitamin D deficiency']],
  },
  {
    slug: 'nutrition/fatty-liver-diet',
    name: 'Fatty Liver Diet',
    title: 'Fatty Liver Diet: What to Eat & Avoid | MedDroid',
    desc: 'Fatty liver diet — the foods that help reverse fatty liver, what to cut, and why weight loss is the key. Educational, not a personalised plan.',
    h1: 'Fatty liver diet',
    lede: 'Non-alcoholic fatty liver is increasingly common and is closely tied to weight, sugar and refined carbs. The good news: it often improves — even reverses — with diet, weight loss and activity.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about fatty liver diet',
    featTitle: 'Eat more / cut',
    features: [
      'Cut sugar, sugary drinks, sweets and refined carbs (the biggest drivers)',
      'Avoid fried foods, and limit or stop alcohol',
      'Eat vegetables, whole grains, dal/pulses, fruit and healthy fats',
      'Prefer coffee (unsweetened) and lean protein',
      'Lose about 7–10% of body weight — the single most effective step',
    ],
    warnings: [
      'Fatty liver with diabetes, obesity or high cholesterol needs those managed too',
      'Yellow eyes, swelling of the belly, or confusion (advanced liver disease) — urgent',
      'Alcohol makes fatty liver worse',
    ],
    noteTitle: 'Weight loss is the key treatment.',
    note: 'Losing around 7–10% of body weight can reverse fatty liver. There is no specific pill — diet, activity and managing diabetes/cholesterol are the treatment. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'Can fatty liver be reversed with diet?', a: 'Yes — especially early on, losing 7–10% of body weight through diet and activity can significantly improve or reverse non-alcoholic fatty liver.' },
      { q: 'What foods should I avoid with fatty liver?', a: 'Sugar, sugary drinks, sweets, refined carbs, fried foods and alcohol are the main things to cut.' },
      { q: 'Is there a medicine for fatty liver?', a: 'There is no single approved pill — the treatment is weight loss, diet, exercise and controlling related conditions like diabetes and cholesterol.' },
    ],
    related: [['diseases/fatty-liver', 'Fatty liver'], ['diseases/fatty-liver-disease', 'Fatty liver disease'], ['nutrition/how-to-lose-weight-safely', 'How to lose weight safely'], ['diseases/metabolic-syndrome', 'Metabolic syndrome']],
  },
  {
    slug: 'nutrition/diet-for-acidity',
    name: 'Diet for Acidity',
    title: 'Diet for Acidity & Acid Reflux: Foods to Avoid | MedDroid',
    desc: 'Acidity diet — the foods and habits that trigger acid reflux, what soothes it, and lifestyle changes that help. Educational, not a personalised plan.',
    h1: 'Diet for acidity & reflux',
    lede: 'Acidity and reflux are often driven by food choices and habits. Identifying your triggers and adjusting how and when you eat can reduce symptoms — often more than medicine alone.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about acidity diet',
    featTitle: 'Avoid / helps',
    features: [
      'Common triggers: spicy, fried and fatty foods, citrus, tomato, coffee, chocolate, mint',
      'Avoid large meals; eat smaller, more frequent ones',
      'Do not lie down for 2–3 hours after eating',
      'Helps: bananas, oats, non-citrus fruit, cold milk/curd for some',
      'Lose excess weight, and avoid smoking and alcohol',
    ],
    warnings: [
      'Difficulty swallowing, weight loss, black stools or vomiting blood — see a doctor (alarm symptoms)',
      'Chest pain (rule out the heart)',
      'Frequent acidity needing daily medicine — get assessed',
    ],
    noteTitle: 'Habits matter as much as food.',
    note: 'When and how you eat (portion size, late meals, lying down) affects reflux as much as what you eat. Alarm symptoms need a doctor. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods cause acidity?', a: 'Spicy, fried and fatty foods, citrus, tomato, coffee, chocolate, mint and large or late meals commonly trigger acidity and reflux.' },
      { q: 'What foods reduce acidity?', a: 'Bananas, oats, non-citrus fruit, vegetables and, for some people, cold milk or curd. Smaller, earlier meals help too.' },
      { q: 'When should acidity be checked?', a: 'See a doctor for difficulty swallowing, weight loss, black stools, vomiting blood, or acidity needing daily medicine — these need assessment.' },
    ],
    related: [['diseases/acid-reflux-gerd', 'Acid reflux (GERD)'], ['diseases/gastritis', 'Gastritis'], ['medicines/pantoprazole', 'Pantoprazole'], ['medicines/omeprazole', 'Omeprazole']],
  },
  {
    slug: 'nutrition/gut-health-foods',
    name: 'Gut Health Foods',
    title: 'Gut Health Foods: Fibre & Probiotics | MedDroid',
    desc: 'Gut health foods — fibre, fermented and probiotic foods that support digestion, and honest facts about “gut-cleanse” claims. Educational, not a personalised plan.',
    h1: 'Gut health foods',
    lede: 'A healthy gut supports digestion, immunity and even mood. The best way to look after it is simple: plenty of fibre and variety, some fermented foods, and skipping the expensive “detox” gimmicks.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about gut health',
    featTitle: 'What supports gut health',
    features: [
      'Fibre: vegetables, fruit, whole grains, dal and pulses',
      'Fermented foods: curd, buttermilk, idli/dosa batter, pickles (in moderation)',
      'Variety of plants feeds a diverse gut microbiome',
      'Stay hydrated and stay active',
      'Limit ultra-processed foods, excess sugar and unnecessary antibiotics',
    ],
    warnings: [
      'Persistent change in bowel habits, blood in stool, or weight loss — see a doctor',
      '“Detox” and “gut cleanse” products are unnecessary and can be harmful',
      'Severe bloating or pain with diarrhoea/constipation (possible IBS or other condition)',
    ],
    noteTitle: 'Fibre and variety beat “detox”.',
    note: 'Your liver and kidneys already detoxify the body — no cleanse is needed. Fibre, fermented foods and variety are what genuinely help. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What foods are good for gut health?', a: 'High-fibre foods (vegetables, fruit, whole grains, dal) and fermented foods (curd, buttermilk) support a healthy, diverse gut microbiome.' },
      { q: 'Do I need gut cleanse or detox products?', a: 'No — the body detoxifies itself. “Cleanse” products are unnecessary and sometimes harmful. Fibre, variety and hydration are what help.' },
      { q: 'Are probiotics worth taking?', a: 'Fermented foods are a good everyday source. Probiotic supplements can help in specific situations (like after antibiotics), but variety in the diet matters most.' },
    ],
    related: [['medicines/probiotics', 'Probiotics'], ['diseases/irritable-bowel-syndrome-ibs', 'IBS'], ['diseases/constipation', 'Constipation'], ['nutrition/diet-for-acidity', 'Diet for acidity']],
  },
  {
    slug: 'nutrition/how-to-cut-sugar',
    name: 'How to Cut Sugar',
    title: 'How to Cut Sugar From Your Diet | MedDroid',
    desc: 'How to cut down on sugar — where hidden sugar lurks, practical swaps, and the real health benefits. Honest, no fads. Educational, not a personalised plan.',
    h1: 'How to cut sugar from your diet',
    lede: 'Cutting added sugar is one of the highest-impact diet changes for weight, diabetes risk, teeth and fatty liver. The trick is spotting hidden sugar and making gradual, sustainable swaps.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about cutting sugar',
    featTitle: 'How to do it',
    features: [
      'Cut sugary drinks first (soft drinks, packaged juices, sweetened tea/coffee)',
      'Watch hidden sugar in biscuits, sauces, cereals and “health” drinks',
      'Swap sweets for fruit; reduce sugar in tea/coffee gradually',
      'Read labels — sugar has many names (syrup, dextrose, maltose)',
      'Whole fruit is fine; it is added and free sugars to limit',
    ],
    warnings: [
      'Cutting sugar helps weight, diabetes risk, teeth and fatty liver',
      'People on diabetes medicine should adjust with their doctor to avoid lows',
      'Beware “sugar-free” products loaded with refined carbs or unhealthy fats',
    ],
    noteTitle: 'Hidden sugar is everywhere.',
    note: 'Most added sugar is hidden in drinks and packaged foods, not the sugar bowl. Whole fruit is healthy; it is free/added sugars to cut. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What is the easiest way to cut sugar?', a: 'Start with sugary drinks — they are the biggest source of added sugar. Then reduce sugar in tea/coffee gradually and watch hidden sugar in packaged foods.' },
      { q: 'Is fruit sugar bad?', a: 'No — whole fruit comes with fibre, vitamins and water, and is healthy. It is added and “free” sugars (in drinks, sweets and juices) to limit.' },
      { q: 'Are sugar-free products healthy?', a: 'Not always — some are high in refined carbs or unhealthy fats. Check the whole label, not just the “sugar-free” claim.' },
    ],
    related: [['diseases/type-2-diabetes', 'Type 2 diabetes'], ['diseases/prediabetes', 'Prediabetes'], ['diseases/tooth-decay', 'Tooth decay'], ['nutrition/how-to-lose-weight-safely', 'How to lose weight safely']],
  },
  {
    slug: 'nutrition/healthy-cooking-oils-and-ghee',
    name: 'Healthy Cooking Oils & Ghee',
    title: 'Healthiest Cooking Oils & Is Ghee Healthy? | MedDroid',
    desc: 'Which cooking oil is healthiest, whether ghee is good or bad, smoke points, and how much fat to use — the honest, balanced answer. Educational, not a personalised plan.',
    h1: 'Healthy cooking oils & ghee',
    lede: 'There is no single “best” oil — the healthiest approach is variety, moderation, and the right oil for the cooking method. Ghee is fine in small amounts, and total quantity matters more than endless debate over which oil.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about cooking oils',
    featTitle: 'Practical guidance',
    features: [
      'Good everyday oils: mustard, rice-bran, groundnut, sunflower, olive (rotate them)',
      'For high-heat frying, choose oils with a high smoke point',
      'Ghee is fine in small amounts (it is high in saturated fat)',
      'Avoid trans fats: vanaspata/dalda and repeatedly reused frying oil',
      'Total fat quantity matters most — use oil sparingly',
    ],
    warnings: [
      'People with high cholesterol/heart disease should limit saturated fat (ghee, butter, coconut oil)',
      'Never reuse frying oil many times (forms harmful compounds)',
      'Avoid vanaspati/partially hydrogenated (trans) fats',
    ],
    noteTitle: 'Variety and moderation beat any “miracle oil”.',
    note: 'No oil is magic; using less oil overall, avoiding trans fats and not reusing frying oil matter more than the exact type. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'Which cooking oil is the healthiest?', a: 'There is no single best — rotating oils like mustard, rice-bran, groundnut, sunflower and olive works well. Using less oil overall matters more than the type.' },
      { q: 'Is ghee healthy or bad?', a: 'Ghee is fine in small amounts but is high in saturated fat, so large quantities can raise cholesterol. Moderation is the key, especially with heart disease.' },
      { q: 'Is it okay to reuse frying oil?', a: 'Avoid repeatedly reusing oil — it forms harmful compounds and trans fats. Use fresh oil and fry less often.' },
    ],
    related: [['nutrition/diet-for-high-cholesterol', 'Diet for high cholesterol'], ['diseases/high-cholesterol', 'High cholesterol'], ['diseases/coronary-artery-disease', 'Coronary artery disease'], ['nutrition/best-diet-for-heart-health', 'Diet for heart health']],
  },
  {
    slug: 'nutrition/best-diet-for-heart-health',
    name: 'Best Diet for Heart Health',
    title: 'Best Diet for a Healthy Heart | MedDroid',
    desc: 'The best diet for heart health — the eating pattern that lowers heart-disease risk, foods to favour and limit, and simple Indian swaps. Educational, not a personalised plan.',
    h1: 'Best diet for heart health',
    lede: 'No single food protects the heart — it is the overall pattern that counts. A diet rich in vegetables, fruit, whole grains and healthy fats, low in salt, sugar and fried food, is proven to lower heart-disease risk.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about heart-healthy diet',
    featTitle: 'Eat more / limit',
    features: [
      'Eat: vegetables, fruit, whole grains, dal/pulses, nuts, and oily fish',
      'Use healthy oils in moderation; include fibre at every meal',
      'Limit salt (for blood pressure) and added sugar',
      'Cut fried foods, trans fats (vanaspati), and processed/red meat',
      'A largely plant-based, home-cooked pattern is ideal',
    ],
    warnings: [
      'Chest pain, breathlessness or a heart-disease history — see a doctor',
      'Diet complements, not replaces, prescribed heart medicines',
      'High blood pressure, cholesterol or diabetes need managing together',
    ],
    noteTitle: 'The pattern matters more than any one food.',
    note: 'Heart health comes from an overall balanced pattern, not superfoods. Combine it with not smoking, activity and managing BP/cholesterol/sugar. MedDroid gives general information, not a personalised plan.',
    faqs: [
      { q: 'What is the best diet for the heart?', a: 'A pattern rich in vegetables, fruit, whole grains, pulses, nuts and healthy fats, low in salt, sugar, fried and processed foods — similar to the Mediterranean/DASH patterns, adaptable to Indian food.' },
      { q: 'Which foods are bad for the heart?', a: 'Fried foods, trans fats (vanaspati), excess salt and sugar, and processed/red meat raise heart-disease risk.' },
      { q: 'Do superfoods protect the heart?', a: 'No single “superfood” does — it is the overall balanced eating pattern, combined with activity and not smoking, that protects your heart.' },
    ],
    related: [['diseases/coronary-artery-disease', 'Coronary artery disease'], ['nutrition/diet-for-high-cholesterol', 'Diet for high cholesterol'], ['nutrition/diet-for-high-blood-pressure', 'Diet for high blood pressure'], ['how-to-lower-cholesterol', 'How to lower cholesterol']],
  },
  {
    slug: 'nutrition/immunity-boosting-foods',
    name: 'Immunity-Boosting Foods',
    title: 'Immunity-Boosting Foods: What Really Helps | MedDroid',
    desc: 'Immunity and diet — the honest facts on “immunity-boosting” foods, what genuinely supports your immune system, and the myths to ignore. Educational, not a diagnosis.',
    h1: 'Immunity-boosting foods: the honest facts',
    lede: 'No food or supplement “boosts” immunity overnight — that is marketing. But a balanced diet with enough key nutrients genuinely supports a well-functioning immune system, alongside sleep, exercise and not smoking.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about immunity',
    featTitle: 'What genuinely supports immunity',
    features: [
      'A varied diet with plenty of vegetables and fruit',
      'Enough protein, and key nutrients: vitamin C, vitamin D, zinc, iron',
      'Correcting deficiencies (like vitamin D or iron) helps most',
      'Good sleep, regular activity and stress management',
      'Not smoking and limiting alcohol',
    ],
    warnings: [
      'No food, kadha or supplement prevents or cures infections on its own',
      'Very high-dose “immunity” supplements can be harmful',
      'Frequent or severe infections — see a doctor to look for a cause',
    ],
    noteTitle: 'Support, don’t “boost”.',
    note: 'A healthy immune system is supported by overall good nutrition and lifestyle, not a single food or megadose supplement. Vaccines remain the strongest protection against specific infections. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What foods boost immunity?', a: 'No food “boosts” immunity, but a varied diet with enough protein, vitamin C, vitamin D, zinc and iron supports it. Correcting deficiencies helps most.' },
      { q: 'Do immunity supplements and kadhas work?', a: 'They do not prevent or cure infections on their own, and high doses can harm. A balanced diet, sleep, exercise and vaccines matter far more.' },
      { q: 'How can I strengthen my immune system?', a: 'Eat well, sleep enough, stay active, manage stress, do not smoke, and keep vaccinations up to date — there is no shortcut supplement.' },
    ],
    related: [['diseases/vitamin-d-deficiency', 'Vitamin D deficiency'], ['medicines/vitamin-c', 'Vitamin C'], ['medicines/zinc', 'Zinc'], ['diseases/primary-immunodeficiency', 'Immunodeficiency']],
  },
];
