// Skin & hair Q&A cluster for MedDroid. Practical, India-aware, honest (no
// fairness/whitening or miracle claims). Full page objects (same shape
// gen-landing's page() consumes). Educational only, not a diagnosis.

export const SKIN_HAIR_QA = [
  {
    slug: 'skin-hair/how-to-treat-acne',
    name: 'How to Treat Acne',
    title: 'How to Treat Acne (Pimples): What Works | MedDroid',
    desc: 'How to treat acne — the products and routines that actually clear pimples, what to avoid, and when to see a dermatologist. Evidence-based. Not a diagnosis.',
    h1: 'How to treat acne (pimples)',
    lede: 'Acne is caused by oil, clogged pores and bacteria — not by being “dirty”. It is very treatable with the right products used consistently, and starting early helps prevent scars.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about acne',
    featTitle: 'What actually works',
    features: [
      'A gentle cleanser twice daily — do not over-wash or scrub',
      'Benzoyl peroxide and/or a retinoid (adapalene) are proven treatments',
      'Salicylic acid helps unclog pores',
      'Be patient — it takes 6–12 weeks to see results',
      'A non-comedogenic (non-clogging) moisturiser and sunscreen',
    ],
    warnings: [
      'Severe, painful, cystic or scarring acne — see a dermatologist',
      'Do not pick or squeeze (causes scars and marks)',
      'Sudden severe acne with irregular periods/hair growth (possible PCOS)',
      'Beware harsh “fairness” or bleaching products (they worsen skin)',
    ],
    noteTitle: 'Consistency beats harshness.',
    note: 'Over-washing and scrubbing make acne worse. Gentle, consistent, evidence-based care works — and a dermatologist can prescribe stronger treatment for severe acne. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the best treatment for acne?', a: 'Benzoyl peroxide and topical retinoids (like adapalene), with a gentle cleanser and non-clogging moisturiser, are the proven basics. Give them 6–12 weeks. Severe acne needs a dermatologist.' },
      { q: 'Why do I keep getting pimples?', a: 'Acne comes from oil, clogged pores, bacteria and hormones — not poor hygiene. Hormonal changes, some products and picking can worsen it.' },
      { q: 'Does toothpaste or lemon help pimples?', a: 'No — these irritate the skin and can worsen acne or cause marks. Use proven treatments instead.' },
    ],
    related: [['diseases/acne', 'Acne'], ['medicines/benzoyl-peroxide', 'Benzoyl peroxide'], ['medicines/adapalene', 'Adapalene'], ['skin-hair/how-to-remove-acne-scars', 'Acne scars']],
  },
  {
    slug: 'skin-hair/how-to-remove-acne-scars',
    name: 'How to Remove Acne Scars',
    title: 'How to Remove Acne Scars & Marks | MedDroid',
    desc: 'Acne scars and dark marks — the difference between them, what fades marks, and the treatments for true scars. Honest expectations. Not a diagnosis.',
    h1: 'How to remove acne scars & marks',
    lede: 'It helps to know the difference: dark marks (post-acne pigmentation) fade over months with the right care, while true pitted scars need dermatological procedures. Preventing new acne is the most important step.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about acne scars',
    featTitle: 'What helps',
    features: [
      'Dark marks: sunscreen, retinoids, vitamin C, azelaic acid — fade over months',
      'True pitted scars: need procedures (a dermatologist)',
      'Sunscreen daily — sun makes marks darker and last longer',
      'Treat active acne first, to stop new scars forming',
      'Be patient — improvement is gradual',
    ],
    warnings: [
      'Deep, pitted or raised (keloid) scars need a dermatologist',
      'Avoid harsh home “bleaching” — it can worsen pigmentation',
      'Ongoing active acne will keep causing new marks — treat it',
    ],
    noteTitle: 'Marks fade; true scars need procedures.',
    note: 'Dark marks respond to skincare over months; genuine pitted scars need professional treatments like microneedling, peels or lasers. Sunscreen is essential. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I remove acne scars at home?', a: 'Home care fades dark marks (with sunscreen, retinoids, vitamin C, azelaic acid) over months, but true pitted scars need dermatological procedures — they cannot be removed by creams alone.' },
      { q: 'What is the difference between acne marks and scars?', a: 'Marks are flat dark or red spots that fade over time; scars are permanent changes in skin texture (pits or raised areas) that need procedures.' },
      { q: 'Does sunscreen help acne scars?', a: 'Yes — sun exposure darkens marks and makes them last longer, so daily sunscreen is one of the most important steps.' },
    ],
    related: [['diseases/acne', 'Acne'], ['skin-hair/pigmentation-and-melasma', 'Pigmentation & melasma'], ['diseases/keloid', 'Keloid'], ['medicines/azelaic-acid', 'Azelaic acid']],
  },
  {
    slug: 'skin-hair/dandruff-treatment',
    name: 'Dandruff Treatment',
    title: 'Dandruff Treatment: How to Get Rid of It | MedDroid',
    desc: 'How to treat dandruff — the medicated shampoos that work, how to use them, and when a flaky scalp needs a doctor. Not a diagnosis.',
    h1: 'Dandruff treatment',
    lede: 'Dandruff is a common, harmless scalp condition linked to a yeast and oily skin — not to poor hygiene. Medicated anti-dandruff shampoos, used correctly, control it well.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dandruff',
    featTitle: 'What works',
    features: [
      'Anti-dandruff shampoos: ketoconazole, zinc pyrithione, selenium sulfide, salicylic acid',
      'Leave the shampoo on for a few minutes before rinsing',
      'Use regularly (2–3 times/week), then less often to maintain',
      'Alternate shampoos if one stops working',
      'It is not caused by poor hygiene or oiling',
    ],
    warnings: [
      'A very red, itchy, scaly scalp spreading to the face (seborrhoeic dermatitis or psoriasis)',
      'Hair loss with scalp scaling',
      'No improvement with anti-dandruff shampoos — see a doctor',
    ],
    noteTitle: 'Control, not cure.',
    note: 'Dandruff tends to come and go, so ongoing occasional use of a medicated shampoo keeps it in check. Persistent or severe scalp problems need a doctor. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I get rid of dandruff?', a: 'Use a medicated anti-dandruff shampoo (ketoconazole, zinc pyrithione, selenium sulfide or salicylic acid), leaving it on a few minutes before rinsing, 2–3 times a week.' },
      { q: 'What causes dandruff?', a: 'A common yeast on oily scalp skin, plus individual sensitivity — not poor hygiene. Stress and weather can worsen it.' },
      { q: 'Does oiling cure dandruff?', a: 'No — heavy oiling can actually feed the yeast and worsen it. Medicated shampoos are the effective treatment.' },
    ],
    related: [['diseases/dandruff', 'Dandruff'], ['diseases/seborrheic-dermatitis', 'Seborrhoeic dermatitis'], ['medicines/ketoconazole-cream', 'Ketoconazole (shampoo)'], ['skin-hair/hair-fall-causes-and-treatment', 'Hair fall']],
  },
  {
    slug: 'skin-hair/hair-fall-causes-and-treatment',
    name: 'Hair Fall: Causes & Treatment',
    title: 'Hair Fall: Causes & Treatment That Works | MedDroid',
    desc: 'Hair fall — how much is normal, the common causes (deficiency, stress, thyroid, pattern baldness), and treatments that work. Honest. Not a diagnosis.',
    h1: 'Hair fall: causes and treatment',
    lede: 'Losing 50–100 hairs a day is normal. Increased hair fall often has a treatable cause — like iron or vitamin deficiency, thyroid problems, stress or illness — while pattern baldness needs specific treatment.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about hair fall',
    featTitle: 'Common causes & what helps',
    features: [
      'Deficiencies (iron, vitamin D, B12), thyroid problems — check and correct',
      'Stress, illness, fever or childbirth (temporary shedding that recovers)',
      'Pattern baldness: minoxidil, and finasteride for men (doctor-guided)',
      'Gentle hair care; a balanced, protein-rich diet',
      'Treat scalp conditions (dandruff, fungal infection)',
    ],
    warnings: [
      'Patchy hair loss, or bald patches with scaling/redness (see a doctor)',
      'Sudden heavy hair loss, or loss with other symptoms (thyroid, anaemia)',
      'Scarring hair loss (permanent if untreated) — needs prompt care',
    ],
    noteTitle: 'Find the cause first.',
    note: 'Many causes of hair fall are temporary and treatable once identified with simple tests. Beware “miracle” hair oils and products. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How much hair fall is normal?', a: 'Losing about 50–100 hairs a day is normal. Noticeably more, thinning, or bald patches suggests a cause worth checking.' },
      { q: 'What causes sudden hair fall?', a: 'Stress, illness, fever, childbirth, crash diets, and deficiencies (iron, vitamin D, B12) or thyroid problems commonly cause temporary heavy shedding that usually recovers.' },
      { q: 'How can I stop hair fall?', a: 'Treat the cause — correct deficiencies and thyroid problems, manage stress, and eat well. For pattern baldness, minoxidil (and finasteride for men) are proven. Miracle oils are not.' },
    ],
    related: [['diseases/hair-loss-alopecia', 'Hair loss (alopecia)'], ['medicines/minoxidil-topical', 'Minoxidil (topical)'], ['nutrition/foods-to-increase-hemoglobin', 'Iron-rich foods'], ['mens-health/male-hair-loss-treatment', 'Male hair loss']],
  },
  {
    slug: 'skin-hair/premature-greying-of-hair',
    name: 'Premature Greying of Hair',
    title: 'Premature Greying of Hair: Causes & Facts | MedDroid',
    desc: 'Premature grey hair — why it happens, the role of genetics and deficiency, what can and cannot reverse it, and honest facts. Not a diagnosis.',
    h1: 'Premature greying of hair',
    lede: 'Hair greys when pigment cells slow down, and when it happens early it is mostly genetic. A few deficiencies play a role, but most greying cannot be reversed — despite many false claims.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about grey hair',
    featTitle: 'The honest picture',
    features: [
      'Mostly genetic (if parents greyed early, you may too)',
      'Deficiencies (B12, iron, copper) and thyroid issues can contribute — worth checking',
      'Smoking and severe stress may speed it up',
      'Correcting a deficiency may help; genetic greying usually will not reverse',
      'Colouring is the practical option for appearance',
    ],
    warnings: [
      'Greying with tiredness or other symptoms (check B12, thyroid)',
      'Patchy hair or skin colour loss (possible vitiligo — see a doctor)',
      'Beware products claiming to “reverse” grey hair',
    ],
    noteTitle: 'Mostly genetic — no magic cure.',
    note: 'No oil or supplement reliably reverses genetic greying. It is worth checking for a deficiency, but manage expectations. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Why is my hair greying early?', a: 'Mostly genetics. Deficiencies (B12, iron, copper), thyroid problems, smoking and stress can contribute, so a check is worthwhile — but much early greying is inherited.' },
      { q: 'Can grey hair turn black again?', a: 'Greying from a treatable deficiency may partly improve, but genetic greying usually cannot be reversed. Products claiming to “reverse” grey hair do not work.' },
      { q: 'Do stress and diet cause grey hair?', a: 'Severe stress and poor nutrition can contribute, but genetics is the main factor in early greying.' },
    ],
    related: [['diseases/vitamin-b12-deficiency', 'Vitamin B12 deficiency'], ['diseases/vitiligo', 'Vitiligo'], ['diseases/thyroid-disorders', 'Thyroid disorders'], ['skin-hair/hair-fall-causes-and-treatment', 'Hair fall']],
  },
  {
    slug: 'skin-hair/dark-circles-under-eyes',
    name: 'Dark Circles Under Eyes',
    title: 'Dark Circles Under Eyes: Causes & What Helps | MedDroid',
    desc: 'Dark circles — the real causes (genetics, sleep, pigmentation, hollowing), what actually helps, and honest limits. Not a diagnosis.',
    h1: 'Dark circles under the eyes',
    lede: 'Dark circles have several causes — genetics, pigmentation, thin skin, hollowing, or simply tiredness. Understanding the type helps you treat it realistically; no single cream fixes all of them.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dark circles',
    featTitle: 'Causes & what helps',
    features: [
      'Sleep well and manage stress; treat allergies (rubbing worsens them)',
      'Sun protection and vitamin C / retinoid creams for pigmentation type',
      'Cold compress and reducing salt for puffiness',
      'Correct iron/vitamin deficiencies if present',
      'Hollowing (shadows) may only improve with procedures (fillers)',
    ],
    warnings: [
      'Dark circles with tiredness/pallor (check for anaemia)',
      'Sudden swelling around the eyes (allergy or other cause)',
      'Beware bleaching creams near the eyes',
    ],
    noteTitle: 'Type matters; no miracle cream.',
    note: 'Some dark circles improve a lot with sleep, sun protection and treating pigmentation, while shadow/hollowing types need procedures. Manage expectations. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I remove dark circles?', a: 'It depends on the cause — sleep, sun protection, treating allergies and pigmentation creams help many, but genetic/hollow types may only improve with procedures.' },
      { q: 'Do dark circles mean I’m unhealthy?', a: 'Often they are just genetic or from tiredness. But dark circles with pallor and fatigue can suggest anaemia, which is worth checking.' },
      { q: 'Do eye creams work for dark circles?', a: 'Those with vitamin C, retinoids or caffeine can help pigmentation and puffiness modestly, but they will not fix genetic hollowing.' },
    ],
    related: [['diseases/dark-circles', 'Dark circles'], ['diseases/iron-deficiency-anaemia', 'Iron-deficiency anaemia'], ['mental-health/how-to-sleep-better', 'Sleep better'], ['skin-hair/pigmentation-and-melasma', 'Pigmentation']],
  },
  {
    slug: 'skin-hair/dry-skin-care',
    name: 'Dry Skin Care',
    title: 'Dry Skin: Causes & How to Care for It | MedDroid',
    desc: 'Dry skin care — why skin gets dry, the right moisturising routine, and when dryness needs a doctor. Simple and practical. Not a diagnosis.',
    h1: 'Dry skin care',
    lede: 'Dry, flaky or itchy skin is common, especially in winter and with age. The key is gentle cleansing and regular moisturising — harsh soaps and hot water make it worse.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about dry skin',
    featTitle: 'What helps',
    features: [
      'Moisturise right after bathing, on damp skin',
      'Use a gentle, soap-free cleanser and lukewarm (not hot) water',
      'Thicker creams/ointments work better than light lotions for very dry skin',
      'Humidifier in dry weather; avoid over-washing',
      'Look for ingredients like glycerin, ceramides, urea',
    ],
    warnings: [
      'Very itchy, red, cracked or weeping skin (possible eczema/infection)',
      'Dry skin with excessive thirst/urination (check for diabetes) or tiredness (thyroid)',
      'Widespread persistent dryness not helped by moisturiser',
    ],
    noteTitle: 'Moisturise more, wash gently.',
    note: 'Consistent moisturising and gentle cleansing solve most dry skin. Persistent, itchy or cracked skin may be eczema or linked to a medical condition. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I fix very dry skin?', a: 'Moisturise generously right after bathing on damp skin, use a gentle soap-free cleanser and lukewarm water, and choose thicker creams with glycerin, ceramides or urea.' },
      { q: 'Why is my skin so dry?', a: 'Cold or dry weather, hot showers, harsh soaps, age, and over-washing are common causes. Conditions like eczema, thyroid problems or diabetes can also dry the skin.' },
      { q: 'When should dry skin be checked?', a: 'If it is very itchy, red, cracked or weeping, or comes with other symptoms like fatigue or excessive thirst — see a doctor.' },
    ],
    related: [['diseases/atopic-dermatitis-eczema', 'Eczema'], ['skin-hair/eczema-care', 'Eczema care'], ['diseases/hypothyroidism', 'Hypothyroidism'], ['diseases/diabetes-diet', 'Diabetes'],],
  },
  {
    slug: 'skin-hair/oily-skin-and-open-pores',
    name: 'Oily Skin & Open Pores',
    title: 'Oily Skin & Open Pores: How to Manage | MedDroid',
    desc: 'Oily skin and large pores — how to control shine, the right products, myths to avoid, and realistic expectations. Not a diagnosis.',
    h1: 'Oily skin & open pores',
    lede: 'Oily skin is largely genetic and hormone-driven. You cannot “close” pores permanently, but the right routine controls shine, reduces breakouts and makes pores look smaller.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about oily skin',
    featTitle: 'What helps',
    features: [
      'Gentle cleanser twice daily — do not over-wash (it rebounds with more oil)',
      'Lightweight, oil-free (non-comedogenic) moisturiser and sunscreen',
      'Salicylic acid or niacinamide to manage oil and pores',
      'Retinoids can improve pore appearance over time',
      'Blotting papers for shine during the day',
    ],
    warnings: [
      'Oily skin with lots of acne (treat the acne)',
      'Sudden oiliness with irregular periods/hair growth (possible PCOS)',
      'Avoid harsh scrubbing and alcohol-heavy toners (they worsen oil)',
    ],
    noteTitle: 'You can’t shrink pores permanently.',
    note: 'Pore size is mostly genetic; products make pores look smaller and control oil but do not permanently close them. Over-washing backfires. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I control oily skin?', a: 'Cleanse gently twice a day (not more), use an oil-free moisturiser and sunscreen, and add salicylic acid or niacinamide. Over-washing makes skin oilier.' },
      { q: 'Can I permanently close my pores?', a: 'No — pore size is largely genetic. Salicylic acid, niacinamide and retinoids make pores look smaller and reduce oil, but cannot permanently shrink them.' },
      { q: 'Does oily skin need moisturiser?', a: 'Yes — a lightweight oil-free moisturiser. Skipping it can trigger more oil production.' },
    ],
    related: [['diseases/acne', 'Acne'], ['skin-hair/how-to-treat-acne', 'How to treat acne'], ['diseases/pcos', 'PCOS'], ['medicines/salicylic-acid', 'Salicylic acid']],
  },
  {
    slug: 'skin-hair/pigmentation-and-melasma',
    name: 'Pigmentation & Melasma',
    title: 'Pigmentation & Melasma: How to Treat Dark Patches | MedDroid',
    desc: 'Skin pigmentation and melasma — why dark patches appear, treatments that fade them, and why sun protection is essential. Not a diagnosis.',
    h1: 'Pigmentation & melasma',
    lede: 'Melasma and other pigmentation cause brown or grey patches, often on the face, and are worsened by sun and hormones. They fade slowly with the right treatment — and daily sunscreen is non-negotiable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pigmentation',
    featTitle: 'What helps',
    features: [
      'Strict daily sunscreen (the single most important step)',
      'Ingredients: vitamin C, niacinamide, azelaic acid, kojic acid',
      'Short, supervised courses of hydroquinone for stubborn melasma',
      'Retinoids and gentle exfoliation over time',
      'Be patient — fading takes months and needs consistency',
    ],
    warnings: [
      'Avoid unregulated “fairness” creams (often contain harmful steroids/mercury)',
      'A new, changing or irregular dark spot (see a doctor to rule out other causes)',
      'Pigmentation that worsens despite sun protection — see a dermatologist',
    ],
    noteTitle: 'Sunscreen first; be patient.',
    note: 'Without daily sun protection, no pigmentation treatment works well. Avoid unregulated fairness/bleaching creams, which can damage skin. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I remove pigmentation from my face?', a: 'Daily sunscreen plus ingredients like vitamin C, niacinamide, azelaic acid and (for stubborn melasma) supervised hydroquinone fade patches over months. Consistency is key.' },
      { q: 'What causes melasma?', a: 'Sun exposure, hormones (pregnancy, the pill) and genetics. It is common on the cheeks, forehead and upper lip, and sun makes it worse.' },
      { q: 'Are fairness creams safe for pigmentation?', a: 'Many unregulated fairness creams contain harmful steroids or mercury and can damage skin. Use dermatologist-guided treatments instead.' },
    ],
    related: [['diseases/melasma', 'Melasma'], ['skin-hair/skin-whitening-truth', 'The truth about skin whitening'], ['medicines/hydroquinone', 'Hydroquinone'], ['skin-hair/sunscreen-guide', 'Sunscreen guide']],
  },
  {
    slug: 'skin-hair/how-to-remove-tan',
    name: 'How to Remove Tan',
    title: 'How to Remove Sun Tan Safely | MedDroid',
    desc: 'How to remove a sun tan — what genuinely helps it fade, gentle home care, and why prevention (sunscreen) matters most. Honest. Not a diagnosis.',
    h1: 'How to remove sun tan',
    lede: 'A tan is the skin’s response to sun and fades on its own over weeks. Gentle care and sun protection speed it up — harsh scrubbing and bleaching only damage the skin.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about tanning',
    featTitle: 'What helps a tan fade',
    features: [
      'Daily sunscreen to stop further tanning (prevention matters most)',
      'Gentle exfoliation and moisturising',
      'Mild brightening ingredients (vitamin C, niacinamide) over time',
      'Cover up and avoid peak-sun hours',
      'Patience — tans fade naturally over a few weeks',
    ],
    warnings: [
      'A new or changing mole/spot after sun exposure (see a doctor)',
      'Painful, blistering sunburn (treat like a burn)',
      'Avoid harsh bleaching or “instant fairness” products',
    ],
    noteTitle: 'Prevent more than “remove”.',
    note: 'There is no instant tan-removal miracle — a tan fades with time and gentle care, and sunscreen prevents more. Avoid harsh bleaching. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can I remove tan fast?', a: 'There is no instant fix — gentle exfoliation, moisturising and brightening ingredients help it fade over weeks, while daily sunscreen prevents more tanning.' },
      { q: 'Do home remedies remove tan?', a: 'Gentle options like curd or aloe soothe skin, but harsh remedies (lemon, strong scrubs) can irritate and darken it. Sunscreen and time work best.' },
      { q: 'Is a tan harmful?', a: 'Tanning is sun damage, and repeated sunburn raises skin-cancer risk. Protecting skin from the sun matters more than removing a tan.' },
    ],
    related: [['skin-hair/sunscreen-guide', 'Sunscreen guide'], ['skin-hair/pigmentation-and-melasma', 'Pigmentation & melasma'], ['diseases/skin-cancer-melanoma', 'Skin cancer'], ['first-aid/burns-first-aid', 'Burns (sunburn) first aid']],
  },
  {
    slug: 'skin-hair/skin-whitening-truth',
    name: 'The Truth About Skin Whitening',
    title: 'Skin Whitening/Fairness Creams: The Honest Truth | MedDroid',
    desc: 'The truth about skin-whitening and fairness creams — why many are harmful, what they cannot do, and safe ways to care for skin. Honest. Not a diagnosis.',
    h1: 'The truth about skin whitening',
    lede: 'Fairness and skin-whitening creams are heavily marketed but often harmful, and they cannot change your natural skin colour. Healthy skin — not lighter skin — is the goal worth pursuing.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about skin whitening',
    featTitle: 'The honest facts',
    features: [
      'Your base skin colour is genetic and cannot be safely “whitened”',
      'Many fairness creams contain harmful steroids, mercury or hydroquinone misused',
      'These can cause thinning, rashes, permanent marks and even kidney/nerve harm',
      'Treating pigmentation (dark patches) is different and can be done safely',
      'Sun protection and good skincare give healthy, even-toned skin',
    ],
    warnings: [
      'Steroid-containing fairness creams damage skin (redness, thinning, acne, rebound)',
      'Mercury-containing creams can cause serious poisoning',
      'A specific dark patch or spot should be assessed, not bleached',
    ],
    noteTitle: 'Aim for healthy skin, not “fair” skin.',
    note: 'Skin-whitening creams cannot safely change your natural colour and many cause real harm. Pigmentation problems can be treated safely under a dermatologist. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Do skin-whitening creams work?', a: 'They cannot safely change your natural skin colour. Many contain harmful ingredients (steroids, mercury) that damage skin. Only specific pigmentation can be treated, and safely.' },
      { q: 'Are fairness creams safe?', a: 'Many unregulated ones are not — steroid- and mercury-containing creams can cause thinning, rashes, permanent marks and serious poisoning.' },
      { q: 'How can I get even-toned skin safely?', a: 'Daily sunscreen, gentle skincare, and dermatologist-guided treatment of pigmentation (not whitening) give healthy, even-toned skin.' },
    ],
    related: [['skin-hair/pigmentation-and-melasma', 'Pigmentation & melasma'], ['skin-hair/sunscreen-guide', 'Sunscreen guide'], ['medicines/hydroquinone', 'Hydroquinone'], ['diseases/melasma', 'Melasma']],
  },
  {
    slug: 'skin-hair/sunscreen-guide',
    name: 'Sunscreen Guide',
    title: 'Sunscreen Guide: How to Choose & Use It | MedDroid',
    desc: 'Sunscreen guide — what SPF and PA mean, how much to apply, and why sunscreen matters for everyone. Simple and practical. Not a diagnosis.',
    h1: 'Sunscreen guide',
    lede: 'Sunscreen is the most effective anti-ageing and skin-protecting product you can use. It prevents tanning, pigmentation, wrinkles and skin cancer — and it is for everyone, all year round.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sunscreen',
    featTitle: 'How to use it',
    features: [
      'Choose SPF 30+ (ideally 50) with good UVA protection (PA+++)',
      'Apply generously — most people use too little',
      'Reapply every 2–3 hours outdoors, more if sweating/swimming',
      'Use it daily, even indoors near windows and on cloudy days',
      'All skin tones benefit — darker skin also gets pigmentation and damage',
    ],
    warnings: [
      'A new, changing or irregular mole/spot (see a doctor)',
      'Painful blistering sunburn (treat like a burn)',
      'Very sensitive skin: choose a mineral (zinc/titanium) sunscreen',
    ],
    noteTitle: 'The best anti-ageing product there is.',
    note: 'Daily, generous sunscreen prevents tanning, pigmentation, wrinkles and skin cancer. It benefits every skin tone. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What SPF sunscreen should I use?', a: 'SPF 30 or higher (ideally 50) with strong UVA protection (PA+++). What matters most is applying enough and reapplying every 2–3 hours outdoors.' },
      { q: 'Do I need sunscreen if I have dark skin or stay indoors?', a: 'Yes — darker skin still gets pigmentation, tanning and damage, and UVA passes through windows. Daily use benefits everyone.' },
      { q: 'How much sunscreen should I apply?', a: 'Generously — about two finger-lengths for the face and neck. Most people apply too little to get the labelled protection.' },
    ],
    related: [['skin-hair/pigmentation-and-melasma', 'Pigmentation & melasma'], ['skin-hair/anti-ageing-and-wrinkles', 'Anti-ageing & wrinkles'], ['diseases/skin-cancer-melanoma', 'Skin cancer'], ['skin-hair/how-to-remove-tan', 'How to remove tan']],
  },
  {
    slug: 'skin-hair/how-to-get-glowing-skin',
    name: 'How to Get Glowing Skin',
    title: 'How to Get Glowing, Healthy Skin | MedDroid',
    desc: 'How to get healthy, glowing skin — a simple evidence-based routine, diet and habits, and the myths to skip. Honest. Not a diagnosis.',
    h1: 'How to get glowing skin',
    lede: '“Glowing skin” really means healthy, well-cared-for skin — and it comes from a simple, consistent routine plus good habits, not expensive miracle products or fairness creams.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about skincare',
    featTitle: 'A simple routine that works',
    features: [
      'Cleanse gently, moisturise, and use sunscreen every morning',
      'Add a treatment (vitamin C in the morning, a retinoid at night) if you wish',
      'Stay hydrated, sleep well, and eat plenty of fruit and vegetables',
      'Do not over-exfoliate or pile on too many products',
      'Be consistent — results take weeks, not days',
    ],
    warnings: [
      'Skin problems (acne, rashes, pigmentation) need targeted treatment',
      'Avoid unregulated fairness/bleaching products',
      'Reactions to new products — patch test and simplify',
    ],
    noteTitle: 'Healthy beats “fair”.',
    note: 'A simple routine, sun protection and good habits give healthy, glowing skin. Skip fairness creams and “detox” gimmicks. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How can I get glowing skin naturally?', a: 'Cleanse gently, moisturise, use sunscreen daily, stay hydrated, sleep well and eat plenty of fruit and vegetables. Consistency matters more than expensive products.' },
      { q: 'What is the best skincare routine?', a: 'A simple one: cleanser, moisturiser and sunscreen by day; cleanser, moisturiser and (optionally) a retinoid at night. Add vitamin C if you like. Do not overdo products.' },
      { q: 'Do diet and water affect skin?', a: 'Yes — a balanced diet, enough water and good sleep support healthy skin, though no single food gives an instant “glow”.' },
    ],
    related: [['skin-hair/sunscreen-guide', 'Sunscreen guide'], ['skin-hair/dry-skin-care', 'Dry skin care'], ['skin-hair/anti-ageing-and-wrinkles', 'Anti-ageing & wrinkles'], ['nutrition/immunity-boosting-foods', 'Diet & health']],
  },
  {
    slug: 'skin-hair/anti-ageing-and-wrinkles',
    name: 'Anti-Ageing & Wrinkles',
    title: 'Anti-Ageing Skincare & Wrinkles: What Works | MedDroid',
    desc: 'Anti-ageing skincare — the ingredients and habits with real evidence for wrinkles and skin ageing, and what to skip. Honest. Not a diagnosis.',
    h1: 'Anti-ageing & wrinkles',
    lede: 'Most skin ageing comes from the sun, so protecting your skin is the most powerful anti-ageing step. A few proven ingredients genuinely help, while most expensive “miracle” creams do not.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about anti-ageing',
    featTitle: 'What genuinely helps',
    features: [
      'Daily sunscreen — the number-one anti-ageing measure',
      'Retinoids (retinol/tretinoin) — the best-proven anti-wrinkle ingredient',
      'Vitamin C and moisturiser support skin health',
      'Do not smoke; sleep well and eat a balanced diet',
      'Procedures (by a dermatologist) for deeper lines',
    ],
    warnings: [
      'Retinoids can irritate at first — start slow and use sunscreen',
      'Avoid unregulated injectables/fillers from untrained providers',
      'A new or changing skin lesion should be checked',
    ],
    noteTitle: 'Sunscreen + retinoids beat “miracle” creams.',
    note: 'Sun protection and retinoids have the best evidence for skin ageing; most costly creams over-promise. Procedures should be done by qualified professionals. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the best anti-ageing product?', a: 'Daily sunscreen is the most effective, followed by retinoids (retinol/tretinoin), which have the strongest evidence for reducing wrinkles.' },
      { q: 'Do expensive anti-ageing creams work?', a: 'Price does not equal results. A few ingredients (retinoids, vitamin C, sunscreen) have evidence; many pricey creams over-promise.' },
      { q: 'How can I prevent wrinkles?', a: 'Protect skin from the sun, do not smoke, use a retinoid, moisturise, and keep a healthy lifestyle.' },
    ],
    related: [['skin-hair/sunscreen-guide', 'Sunscreen guide'], ['medicines/tretinoin', 'Tretinoin'], ['skin-hair/how-to-get-glowing-skin', 'Glowing skin'], ['skin-hair/pigmentation-and-melasma', 'Pigmentation']],
  },
  {
    slug: 'skin-hair/eczema-care',
    name: 'Eczema Care',
    title: 'Eczema Care: How to Manage Itchy Skin | MedDroid',
    desc: 'Eczema care — how to control the itch-scratch cycle with moisturisers and treatment, avoid triggers, and when to see a doctor. Not a diagnosis.',
    h1: 'Eczema care',
    lede: 'Eczema is dry, itchy, inflamed skin that flares and settles. It cannot be cured, but it is very controllable — the foundation is heavy, regular moisturising, plus treating flares and avoiding triggers.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about eczema',
    featTitle: 'How to manage it',
    features: [
      'Moisturise generously and often (the foundation of control)',
      'Use steroid creams on flares as directed (short courses)',
      'Gentle, soap-free cleansing; lukewarm water',
      'Identify and avoid triggers (soaps, heat, sweat, allergens)',
      'Keep nails short; try not to scratch',
    ],
    warnings: [
      'Weeping, crusted or pus-filled skin, or fever (possible infection)',
      'Severe or widespread eczema not controlled by usual care',
      'Eczema badly affecting sleep or daily life',
    ],
    noteTitle: 'Moisturise even when it’s clear.',
    note: 'Regular moisturising between flares keeps eczema under control. Steroid creams are safe used correctly for flares. Infected eczema needs prompt care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I control eczema?', a: 'Moisturise heavily and often, use steroid creams on flares as directed, cleanse gently, and avoid your triggers. Keeping skin hydrated between flares is key.' },
      { q: 'Are steroid creams safe for eczema?', a: 'Yes — used correctly for flares they are safe and effective. Long-term overuse of strong ones should be avoided, and a doctor can guide you.' },
      { q: 'What triggers eczema?', a: 'Common triggers include soaps and detergents, heat and sweat, dry weather, certain fabrics, stress and allergens. Identifying yours helps prevent flares.' },
    ],
    related: [['diseases/atopic-dermatitis-eczema', 'Atopic dermatitis (eczema)'], ['diseases/eczema', 'Eczema'], ['medicines/tacrolimus-topical', 'Tacrolimus (topical)'], ['skin-hair/dry-skin-care', 'Dry skin care']],
  },
  {
    slug: 'skin-hair/psoriasis-care',
    name: 'Psoriasis Care',
    title: 'Psoriasis Care: Managing Flare-Ups | MedDroid',
    desc: 'Psoriasis care — what it is, how to manage the scaly patches, treatment options, and when to see a dermatologist. Not a diagnosis.',
    h1: 'Psoriasis care',
    lede: 'Psoriasis is a long-term condition where skin cells build up into thick, scaly patches. It is not contagious and cannot be cured, but many treatments control it well — and it flares and settles over time.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about psoriasis',
    featTitle: 'How it is managed',
    features: [
      'Moisturise heavily to reduce scaling and itching',
      'Topical treatments: steroids, vitamin-D creams (calcipotriol), coal tar',
      'Light therapy for more extensive disease',
      'Tablets or biologics for severe psoriasis (specialist-led)',
      'Manage triggers: stress, infections, smoking, alcohol',
    ],
    warnings: [
      'Widespread, rapidly spreading, or pustular psoriasis (urgent)',
      'Joint pain and swelling (possible psoriatic arthritis)',
      'Signs of skin infection, or severe impact on wellbeing',
    ],
    noteTitle: 'Controllable, not curable.',
    note: 'Psoriasis is not contagious and is managed long-term with treatments matched to its severity. Joint symptoms need review for psoriatic arthritis. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is psoriasis curable?', a: 'No, but it is very controllable. Treatments range from moisturisers and creams to light therapy and, for severe cases, tablets or biologics. It flares and settles over time.' },
      { q: 'Is psoriasis contagious?', a: 'No — it is an immune-related skin condition and cannot be caught from or passed to others.' },
      { q: 'What triggers psoriasis flares?', a: 'Stress, infections, skin injury, cold weather, smoking and alcohol can trigger flares. Managing these helps control it.' },
    ],
    related: [['diseases/psoriasis', 'Psoriasis'], ['diseases/psoriatic-arthritis', 'Psoriatic arthritis'], ['medicines/calcipotriol', 'Calcipotriol'], ['medicines/methotrexate', 'Methotrexate']],
  },
  {
    slug: 'skin-hair/prickly-heat-and-sweat-rash',
    name: 'Prickly Heat & Sweat Rash',
    title: 'Prickly Heat (Sweat Rash): Relief & Prevention | MedDroid',
    desc: 'Prickly heat and sweat rash — why it happens in hot weather, how to soothe and prevent it, and when to see a doctor. India-relevant. Not a diagnosis.',
    h1: 'Prickly heat & sweat rash',
    lede: 'Prickly heat (heat rash) is a common, itchy, prickly rash in hot, humid weather when sweat gets trapped. It is harmless and settles by keeping cool and dry.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about prickly heat',
    featTitle: 'Relief & prevention',
    features: [
      'Keep cool: fans, AC, cool showers, shade',
      'Wear loose, light cotton clothing',
      'Calamine lotion and prickly-heat powder soothe',
      'Keep the skin dry; avoid heavy creams that block pores',
      'Stay hydrated',
    ],
    warnings: [
      'Signs of heat exhaustion/heat stroke (dizziness, confusion) — urgent',
      'The rash becoming infected (pus, spreading redness, fever)',
      'A rash that does not settle when cool, or is very widespread',
    ],
    noteTitle: 'Keep cool and dry.',
    note: 'Prickly heat clears when the skin stays cool and dry. In extreme heat, watch for heat exhaustion or heat stroke, which are emergencies. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I get rid of prickly heat?', a: 'Keep cool and dry — use fans/AC, cool showers, loose cotton clothes, and calamine or prickly-heat powder. It settles once the skin is no longer overheating and sweating.' },
      { q: 'What causes prickly heat?', a: 'Blocked sweat glands in hot, humid weather trap sweat under the skin, causing the itchy, prickly rash. It is common in India’s summers.' },
      { q: 'When should I worry about a heat rash?', a: 'If it becomes infected (pus, spreading redness, fever), does not settle when cool, or you develop dizziness/confusion (possible heat illness).' },
    ],
    related: [['diseases/heat-stroke', 'Heat stroke'], ['first-aid/heat-stroke-first-aid', 'Heat stroke first aid'], ['medicines/calamine', 'Calamine lotion'], ['diseases/fungal-skin-infection', 'Fungal skin infection']],
  },
  {
    slug: 'skin-hair/warts-and-skin-tags',
    name: 'Warts & Skin Tags',
    title: 'Warts & Skin Tags: Causes & Removal | MedDroid',
    desc: 'Warts and skin tags — the difference, why they appear, safe removal options, and when to see a doctor. Not a diagnosis.',
    h1: 'Warts & skin tags',
    lede: 'Warts (caused by a virus) and skin tags (small soft skin growths) are both common and harmless. Many need no treatment, but several safe removal options exist — and DIY removal of the wrong thing can be risky.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about warts & skin tags',
    featTitle: 'What to know',
    features: [
      'Warts are viral and can spread; skin tags are harmless skin growths',
      'Many warts clear on their own over months',
      'Options: salicylic-acid wart treatments, freezing (cryotherapy), removal by a doctor',
      'Skin tags can be removed by a doctor if bothersome',
      'Do not cut or burn them off yourself',
    ],
    warnings: [
      'A growing, bleeding, colour-changing or irregular “wart/tag” (could be something else — see a doctor)',
      'Warts on the genitals or face (see a doctor)',
      'Do not attempt DIY removal of anything you are unsure about',
    ],
    noteTitle: 'Get unusual growths checked.',
    note: 'Most warts and skin tags are harmless, but a growth that changes, bleeds or looks irregular should be checked to rule out skin cancer. Avoid risky DIY removal. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I remove a wart?', a: 'Options include over-the-counter salicylic-acid treatments, freezing (cryotherapy), or removal by a doctor. Many warts also clear on their own over months.' },
      { q: 'Are skin tags dangerous?', a: 'No — they are harmless. They can be removed by a doctor if they catch or bother you. Do not cut them off yourself.' },
      { q: 'When should a wart or growth be checked?', a: 'If it grows, bleeds, changes colour, looks irregular, or is on the face or genitals — see a doctor to be sure of what it is.' },
    ],
    related: [['diseases/warts', 'Warts'], ['diseases/moles', 'Moles'], ['diseases/skin-cancer-melanoma', 'Skin cancer'], ['medicines/salicylic-acid', 'Salicylic acid']],
  },
  {
    slug: 'skin-hair/stretch-marks',
    name: 'Stretch Marks',
    title: 'Stretch Marks: Causes & What Helps | MedDroid',
    desc: 'Stretch marks — why they form, what genuinely helps them fade, and honest limits on “removal”. Not a diagnosis.',
    h1: 'Stretch marks',
    lede: 'Stretch marks form when skin stretches quickly — in growth spurts, pregnancy or weight change. They are harmless and very common, and while they fade over time, they cannot be fully “erased”.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about stretch marks',
    featTitle: 'What helps',
    features: [
      'They fade from red/purple to pale over time on their own',
      'Moisturising and staying hydrated support skin',
      'Retinoids may help early (red) marks — not in pregnancy',
      'Procedures (lasers, microneedling) can improve them modestly',
      'Gradual weight change reduces new marks',
    ],
    warnings: [
      'Sudden widespread stretch marks with other symptoms (rarely, a hormone problem)',
      'Beware creams promising to “remove” stretch marks completely',
      'Retinoid creams should be avoided in pregnancy',
    ],
    noteTitle: 'They fade, but don’t fully vanish.',
    note: 'No cream completely removes stretch marks; they fade over time and treatments improve them modestly. Manage expectations. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I get rid of stretch marks?', a: 'They fade over time on their own. Moisturising, early retinoid use (not in pregnancy) and procedures like lasers or microneedling improve them, but none fully erases them.' },
      { q: 'What causes stretch marks?', a: 'Rapid stretching of the skin — during growth spurts, pregnancy, weight gain or muscle gain — plus a genetic tendency.' },
      { q: 'Do stretch mark creams work?', a: 'Most give modest results at best. Early (red) marks respond a little better; no cream removes them completely.' },
    ],
    related: [['nutrition/how-to-lose-weight-safely', 'Healthy weight change'], ['womens-health/what-to-eat-in-pregnancy', 'Pregnancy care'], ['medicines/tretinoin', 'Tretinoin'], ['skin-hair/dry-skin-care', 'Dry skin care']],
  },
  {
    slug: 'skin-hair/body-odour-and-sweating',
    name: 'Body Odour & Excessive Sweating',
    title: 'Body Odour & Excessive Sweating: What Helps | MedDroid',
    desc: 'Body odour and excessive sweating — practical control, the difference between deodorant and antiperspirant, and treatments for heavy sweating. Not a diagnosis.',
    h1: 'Body odour & excessive sweating',
    lede: 'Sweat itself is odourless — body odour comes from bacteria acting on sweat. Good hygiene and antiperspirants control most cases, and heavy sweating (hyperhidrosis) has effective treatments.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about sweating',
    featTitle: 'What helps',
    features: [
      'Wash daily with soap; dry well (especially skin folds)',
      'Antiperspirant reduces sweat; deodorant tackles smell',
      'Wear breathable cotton; change clothes when sweaty',
      'For heavy sweating: strong antiperspirants, and medical options exist',
      'Manage triggers (spicy food, caffeine, stress)',
    ],
    warnings: [
      'Sudden heavy sweating with weight loss, fever, or night sweats (see a doctor)',
      'Sweating with palpitations, tremor or heat intolerance (possible thyroid)',
      'A new, strong or unusual body odour that persists',
    ],
    noteTitle: 'Antiperspirant for sweat, deodorant for smell.',
    note: 'Most body odour is controlled with hygiene and antiperspirants. Excessive sweating (hyperhidrosis) has effective treatments. New sweating with other symptoms should be checked. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the difference between deodorant and antiperspirant?', a: 'A deodorant masks or reduces odour; an antiperspirant reduces the amount of sweat. Many products combine both.' },
      { q: 'How do I stop excessive sweating?', a: 'Strong (aluminium-based) antiperspirants help; for hyperhidrosis, doctors can offer prescription treatments, iontophoresis, botox or other options.' },
      { q: 'When is sweating a sign of a problem?', a: 'Heavy sweating with weight loss, fever, night sweats, palpitations or heat intolerance can signal thyroid or other conditions — get checked.' },
    ],
    related: [['diseases/hyperthyroidism', 'Hyperthyroidism'], ['skin-hair/prickly-heat-and-sweat-rash', 'Prickly heat'], ['diseases/fungal-skin-infection', 'Fungal skin infection'], ['mental-health/how-to-reduce-stress', 'Reduce stress']],
  },
];
