// Women's-health Q&A cluster for MedDroid. High-search, respectful, practical.
// Full page objects (same shape gen-landing's page() consumes). Educational only,
// not a diagnosis. Strong warning cards where safety matters (pregnancy, breast
// lump, ectopic, heavy bleeding).

export const WOMEN_QA = [
  {
    slug: 'womens-health/irregular-periods-causes',
    name: 'Irregular Periods: Causes',
    title: 'Irregular Periods: Common Causes & What to Do | MedDroid',
    desc: 'Irregular periods — common causes (PCOS, thyroid, stress, weight, perimenopause), what is normal, and when to see a doctor. Educational, not a diagnosis.',
    h1: 'Irregular periods: why it happens',
    lede: 'An occasional late or early period is normal, but a pattern of irregular cycles can point to something treatable — from PCOS or thyroid problems to stress, weight change or approaching menopause.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about your periods',
    featTitle: 'Common causes of irregular periods',
    features: [
      'PCOS (polycystic ovary syndrome) — a very common cause',
      'Thyroid problems (under- or over-active)',
      'Significant stress, weight loss or weight gain',
      'Intense exercise or an eating disorder',
      'Perimenopause (in the 40s–50s)',
      'Some contraceptives and other medicines',
    ],
    warnings: [
      'Bleeding between periods or after sex',
      'Very heavy bleeding, or periods lasting more than 7 days',
      'No periods for 3+ months when not pregnant',
      'Periods restarting after menopause',
      'Severe pelvic pain',
    ],
    noteTitle: 'A pattern is worth checking.',
    note: 'Simple tests (like thyroid, hormones and an ultrasound) often find a treatable cause. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is considered an irregular period?', a: 'Cycles that are consistently shorter than about 21 days or longer than 35 days, or that vary a lot month to month. An occasional off month is usually normal.' },
      { q: 'Can stress delay my period?', a: 'Yes — stress, big changes in weight or exercise, illness and travel can all delay or skip a period by affecting the hormones that control your cycle.' },
      { q: 'When should I see a doctor about irregular periods?', a: 'If they are persistently irregular, very heavy, come with bleeding between periods or after sex, or you have no period for 3+ months without being pregnant.' },
    ],
    related: [['diseases/pcos', 'PCOS'], ['diseases/thyroid-disorders', 'Thyroid disorders'], ['diseases/irregular-periods', 'Irregular periods'], ['womens-health/pcos-management', 'Managing PCOS']],
  },
  {
    slug: 'womens-health/how-to-reduce-period-pain',
    name: 'How to Reduce Period Pain',
    title: 'How to Reduce Period Pain (Cramps) Naturally & With Medicine | MedDroid',
    desc: 'Period pain relief — proven home measures, which painkillers help, and when cramps mean something more (like endometriosis). Educational, not a diagnosis.',
    h1: 'How to reduce period pain',
    lede: 'Period cramps are caused by the womb contracting, and for most women simple measures and the right painkiller give good relief. Pain that is severe or getting worse deserves a check.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about period pain',
    featTitle: 'What helps period cramps',
    features: [
      'A heat pad or hot water bottle on the lower tummy',
      'Anti-inflammatory painkillers like ibuprofen or mefenamic acid (with food)',
      'Gentle exercise, stretching or yoga',
      'Staying hydrated and rest',
      'The contraceptive pill can reduce cramps for some women (ask your doctor)',
    ],
    warnings: [
      'Pain so severe it stops you doing normal activities',
      'Pain that is getting worse over months, or pain outside periods',
      'Very heavy bleeding, or pain with fever or unusual discharge',
      'Pain with a chance of pregnancy and a missed period (possible ectopic — urgent)',
    ],
    noteTitle: 'Severe or worsening pain is not “just periods”.',
    note: 'Conditions like endometriosis or fibroids can cause severe period pain and are treatable. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the best painkiller for period cramps?', a: 'Anti-inflammatories like ibuprofen or mefenamic acid, taken with food as cramps start, usually work best. Paracetamol is an alternative if NSAIDs do not suit you.' },
      { q: 'Do home remedies really help cramps?', a: 'Yes — heat, gentle activity, hydration and rest genuinely ease cramps for many women, alongside or instead of painkillers.' },
      { q: 'When is period pain a sign of a problem?', a: 'If it is severe, worsening, present outside periods, or comes with heavy bleeding, fever or unusual discharge, see a doctor to check for conditions like endometriosis.' },
    ],
    related: [['diseases/painful-periods', 'Painful periods'], ['diseases/endometriosis', 'Endometriosis'], ['medicines/mefenamic-acid', 'Mefenamic acid'], ['medicines/ibuprofen', 'Ibuprofen']],
  },
  {
    slug: 'womens-health/how-to-stop-heavy-periods',
    name: 'How to Stop Heavy Periods',
    title: 'Heavy Periods: Causes & How to Reduce Them | MedDroid',
    desc: 'Heavy menstrual bleeding — what counts as heavy, common causes (fibroids, hormones), treatments like tranexamic acid, and warning signs. Educational, not a diagnosis.',
    h1: 'How to stop heavy periods',
    lede: 'Heavy periods (menorrhagia) can affect daily life and cause anaemia. There are effective non-surgical treatments — so you do not have to just put up with it.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about heavy periods',
    featTitle: 'What can help',
    features: [
      'Tranexamic acid, taken during the period, reduces bleeding',
      'Anti-inflammatories (mefenamic acid) reduce bleeding and pain',
      'Hormonal options: the pill or a hormonal IUD (Mirena)',
      'Treating iron deficiency with iron supplements',
      'Investigating and treating causes like fibroids',
    ],
    warnings: [
      'Flooding, passing large clots, or changing pads/tampons every 1–2 hours',
      'Feeling very tired, breathless or dizzy (possible anaemia)',
      'Bleeding between periods or after sex',
      'Bleeding after menopause',
    ],
    noteTitle: 'Heavy bleeding is treatable — and can cause anaemia.',
    note: 'Effective treatments exist, and a blood test can check for iron-deficiency anaemia. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What counts as a heavy period?', a: 'Soaking through pads/tampons every 1–2 hours, passing large clots, bleeding over 7 days, or bleeding that limits daily life all count as heavy.' },
      { q: 'How can I reduce heavy periods without hormones?', a: 'Tranexamic acid and mefenamic acid, taken during your period, both reduce bleeding non-hormonally. A doctor can advise which suits you.' },
      { q: 'Can heavy periods make me anaemic?', a: 'Yes — regular heavy bleeding is a common cause of iron-deficiency anaemia, so iron levels are often checked and treated.' },
    ],
    related: [['diseases/heavy-periods', 'Heavy periods'], ['diseases/uterine-fibroids', 'Uterine fibroids'], ['medicines/tranexamic-acid', 'Tranexamic acid'], ['diseases/iron-deficiency-anaemia', 'Iron-deficiency anaemia']],
  },
  {
    slug: 'womens-health/late-period-not-pregnant',
    name: 'Late Period (Not Pregnant)',
    title: 'Reasons for a Late Period When Not Pregnant | MedDroid',
    desc: 'Why your period might be late when you are not pregnant — stress, weight, thyroid, PCOS, perimenopause and more — and when to check. Educational, not a diagnosis.',
    h1: 'Reasons for a late period (when not pregnant)',
    lede: 'Pregnancy is the first thing many people think of with a late period, but there are many other reasons — and a delayed period now and then is completely normal.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about a late period',
    featTitle: 'Common reasons (other than pregnancy)',
    features: [
      'Stress, poor sleep or a big routine change',
      'Sudden weight loss or gain, or intense exercise',
      'PCOS or thyroid problems',
      'Coming off or changing contraception',
      'Illness, travel or perimenopause',
    ],
    warnings: [
      'A positive pregnancy test with pain or bleeding (see a doctor)',
      'No periods for 3+ months when not pregnant',
      'Severe pelvic pain or unusual discharge',
      'Signs of thyroid problems (weight, mood, hair, heat/cold changes)',
    ],
    noteTitle: 'Rule out pregnancy first.',
    note: 'If there is any chance of pregnancy, take a test. If periods are repeatedly late without pregnancy, a doctor can check hormones and thyroid. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How late can a period be before I worry?', a: 'A few days late is very common and usually nothing. If it is more than a week late and pregnancy is possible, take a test; if periods are repeatedly irregular, see a doctor.' },
      { q: 'Can stress stop my period?', a: 'Yes — significant stress can delay or even skip a period by disrupting the hormones that trigger ovulation.' },
      { q: 'I have no period but tests are negative — why?', a: 'Common reasons include stress, weight change, PCOS, thyroid problems or perimenopause. If it continues for 3+ months, get checked.' },
    ],
    related: [['womens-health/early-pregnancy-symptoms', 'Early pregnancy symptoms'], ['diseases/pcos', 'PCOS'], ['diseases/thyroid-disorders', 'Thyroid disorders'], ['womens-health/irregular-periods-causes', 'Irregular periods']],
  },
  {
    slug: 'womens-health/pcos-management',
    name: 'Managing PCOS',
    title: 'PCOS: Symptoms & How to Manage It | MedDroid',
    desc: 'PCOS (polycystic ovary syndrome) — the signs, how it affects periods, weight, skin and fertility, and how lifestyle and medicines help. Educational, not a diagnosis.',
    h1: 'PCOS: symptoms and how to manage it',
    lede: 'PCOS is one of the most common hormone conditions in women, affecting periods, skin, weight and fertility. It cannot be “cured”, but it is very manageable — and lifestyle changes make a real difference.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about PCOS',
    featTitle: 'How PCOS is managed',
    features: [
      'Weight management and regular activity (even modest loss helps hormones)',
      'A balanced, lower-refined-carb diet',
      'The contraceptive pill to regulate periods and help skin/hair',
      'Metformin for insulin resistance in some women',
      'Fertility treatment (like letrozole/clomiphene) when trying to conceive',
    ],
    warnings: [
      'Very irregular or absent periods for long stretches (needs review)',
      'Rapid weight gain, excessive hair growth or severe acne',
      'Signs of high blood sugar (very thirsty, passing lots of urine)',
      'Difficulty conceiving after a year of trying',
    ],
    noteTitle: 'Lifestyle is the foundation.',
    note: 'PCOS raises the long-term risk of diabetes, so healthy habits and regular checks matter. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Can PCOS be cured?', a: 'There is no cure, but it is very manageable. Lifestyle changes, and medicines where needed, control the symptoms and lower long-term risks like diabetes.' },
      { q: 'Can I get pregnant with PCOS?', a: 'Yes — many women with PCOS conceive, sometimes with help. Weight management and medicines like letrozole or clomiphene improve ovulation.' },
      { q: 'What diet is best for PCOS?', a: 'A balanced diet lower in refined carbs and sugar, with regular activity, helps insulin levels and hormones. Even modest weight loss can restore periods.' },
    ],
    related: [['diseases/pcos', 'PCOS'], ['diseases/pcod', 'PCOD'], ['medicines/metformin', 'Metformin'], ['medicines/clomiphene', 'Clomiphene']],
  },
  {
    slug: 'womens-health/early-pregnancy-symptoms',
    name: 'Early Pregnancy Symptoms',
    title: 'Early Pregnancy Symptoms: Signs & When to Test | MedDroid',
    desc: 'Early pregnancy symptoms — the common first signs, how soon they appear, when to take a test, and what to do next. Educational, not a diagnosis.',
    h1: 'Early pregnancy symptoms',
    lede: 'Early pregnancy signs vary a lot between women, and some feel nothing at first. A missed period is the classic clue — a home urine test is the simplest way to confirm.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pregnancy signs',
    featTitle: 'Common early signs',
    features: [
      'A missed period',
      'Nausea or “morning” sickness (any time of day)',
      'Tender, swollen breasts',
      'Tiredness',
      'Passing urine more often',
      'Food aversions or a heightened sense of smell',
    ],
    warnings: [
      'A positive test with severe one-sided pain or bleeding (possible ectopic — urgent)',
      'Heavy bleeding or fainting',
      'Severe vomiting with inability to keep fluids down',
      'A positive test — start folic acid and see a doctor',
    ],
    noteTitle: 'Start folic acid early.',
    note: 'If pregnant, begin folic acid and arrange antenatal care. Severe pain or bleeding needs urgent review. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the first signs of pregnancy?', a: 'A missed period, nausea, tender breasts, tiredness and needing to pass urine more often are common early signs — though they vary and some women notice little at first.' },
      { q: 'When should I take a pregnancy test?', a: 'A home urine test is most reliable from the day your period is due, or about 3 weeks after unprotected sex. Testing too early can give a false negative.' },
      { q: 'What should I do if the test is positive?', a: 'Start a folic acid supplement, avoid alcohol and smoking, and book antenatal care with a doctor. Seek urgent help for severe pain or bleeding.' },
    ],
    related: [['diseases/pregnancy-care', 'Pregnancy care'], ['womens-health/when-to-take-pregnancy-test', 'When to take a pregnancy test'], ['medicines/folic-acid', 'Folic acid'], ['diseases/ectopic-pregnancy', 'Ectopic pregnancy']],
  },
  {
    slug: 'womens-health/when-to-take-pregnancy-test',
    name: 'When to Take a Pregnancy Test',
    title: 'When to Take a Pregnancy Test (for Accuracy) | MedDroid',
    desc: 'When to take a home pregnancy test for the most accurate result, how they work, false results, and next steps. Educational, not a diagnosis.',
    h1: 'When to take a pregnancy test',
    lede: 'Home pregnancy tests detect the hormone hCG in urine. Testing at the right time — and correctly — gives the most reliable answer and avoids confusing false results.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pregnancy testing',
    featTitle: 'For the most accurate result',
    features: [
      'Test from the first day of a missed period (or ~3 weeks after unprotected sex)',
      'Use the first urine of the morning (most concentrated)',
      'Follow the timing on the instructions exactly',
      'A faint line usually still means positive',
      'Repeat in a few days if negative but your period has not come',
    ],
    warnings: [
      'A positive test with severe pain or bleeding (possible ectopic — urgent)',
      'Repeated negative tests but no period (see a doctor)',
      'Confusing or unclear results',
    ],
    noteTitle: 'Too early can read falsely negative.',
    note: 'Testing before your period is due can miss an early pregnancy. A blood test at a clinic can confirm earlier and more precisely. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How soon can I take a pregnancy test?', a: 'Most home tests are reliable from the day your period is due. Some “early” tests claim a few days sooner, but testing too early can give a false negative.' },
      { q: 'Does a faint line mean pregnant?', a: 'Usually yes — even a faint line generally means hCG is present. Repeat in a couple of days to see it darken, or do a blood test to confirm.' },
      { q: 'Can a test be wrong?', a: 'False negatives happen if you test too early or with dilute urine. False positives are rarer but can follow certain medicines or a recent pregnancy loss.' },
    ],
    related: [['womens-health/early-pregnancy-symptoms', 'Early pregnancy symptoms'], ['diseases/pregnancy-care', 'Pregnancy care'], ['blood-tests/beta-hcg-pregnancy', 'Beta hCG test'], ['womens-health/late-period-not-pregnant', 'Late period (not pregnant)']],
  },
  {
    slug: 'womens-health/morning-sickness-remedies',
    name: 'Morning Sickness Remedies',
    title: 'Morning Sickness: Remedies & When to Worry | MedDroid',
    desc: 'Morning sickness in pregnancy — what helps nausea and vomiting, safe options, and the severe form (hyperemesis) that needs a doctor. Educational, not a diagnosis.',
    h1: 'Morning sickness: what helps',
    lede: 'Nausea and vomiting are very common in early pregnancy and, despite the name, can happen any time of day. It usually eases by the second trimester — and several safe measures help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about morning sickness',
    featTitle: 'What helps',
    features: [
      'Eat small, frequent meals; do not let your stomach get empty',
      'Plain, dry foods (toast, crackers) — especially before getting up',
      'Ginger (tea, biscuits) and cold, clear fluids in small sips',
      'Rest and avoid smells that trigger nausea',
      'Vitamin B6, and doctor-approved anti-sickness medicine if needed',
    ],
    warnings: [
      'Unable to keep any food or fluid down (risk of dehydration)',
      'Passing very little, dark urine, or feeling faint',
      'Vomiting blood, or severe constant vomiting (possible hyperemesis)',
      'Weight loss in pregnancy',
    ],
    noteTitle: 'Severe vomiting (hyperemesis) needs treatment.',
    note: 'If you cannot keep fluids down, you may be dehydrated and need medical care — safe anti-sickness medicines are available in pregnancy. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What helps morning sickness naturally?', a: 'Small frequent meals, dry plain foods, ginger, cold sips of fluid, rest and avoiding trigger smells help most women. Vitamin B6 can also reduce nausea.' },
      { q: 'When does morning sickness stop?', a: 'It usually eases by around 12–16 weeks, though a minority have it longer. Severe, persistent vomiting is different and needs medical care.' },
      { q: 'Is it safe to take anti-sickness medicine in pregnancy?', a: 'Yes — there are anti-sickness medicines considered safe in pregnancy (like doxylamine-B6). See your doctor if simple measures are not enough.' },
    ],
    related: [['diseases/pregnancy-care', 'Pregnancy care'], ['medicines/doxylamine', 'Doxylamine (with B6)'], ['medicines/ondansetron', 'Ondansetron'], ['womens-health/pregnancy-warning-signs', 'Pregnancy warning signs']],
  },
  {
    slug: 'womens-health/pregnancy-warning-signs',
    name: 'Pregnancy Warning Signs',
    title: 'Danger Signs in Pregnancy: When to Seek Help | MedDroid',
    desc: 'Pregnancy danger signs — the symptoms that need urgent medical care at any stage, from bleeding to severe headache and reduced baby movements. Educational, not a diagnosis.',
    h1: 'Warning signs in pregnancy',
    lede: 'Most pregnancies are healthy, but knowing the danger signs can save your life and your baby’s. If you notice any of these, contact your doctor or go to hospital without delay.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pregnancy warning signs',
    featTitle: 'Seek help urgently for',
    features: [
      'Vaginal bleeding at any stage',
      'Severe or one-sided tummy pain (early pregnancy — possible ectopic)',
      'A severe headache, blurred vision or sudden swelling of face/hands (possible pre-eclampsia)',
      'Reduced or absent baby movements (later pregnancy)',
      'Fluid leaking, or strong regular contractions before term',
      'High fever, painful urination, or persistent vomiting',
    ],
    warnings: [
      'Heavy bleeding, fainting or severe pain — call emergency services',
      'Severe headache with vision changes and swelling — urgent (pre-eclampsia)',
      'Baby moving much less than usual — get checked the same day',
      'Fluid gush or regular contractions before 37 weeks',
    ],
    noteTitle: 'When in doubt, get checked.',
    note: 'It is always better to be checked and reassured. Do not wait with any of these signs. MedDroid gives general information, not a diagnosis; in an emergency contact your local emergency number.',
    faqs: [
      { q: 'What are the danger signs in pregnancy?', a: 'Bleeding, severe tummy pain, a severe headache with vision changes or swelling, reduced baby movements, fluid leaking, high fever, or persistent vomiting all need urgent medical attention.' },
      { q: 'What is pre-eclampsia?', a: 'A serious pregnancy condition with high blood pressure, often with headache, vision changes and swelling. It needs urgent care, so attend all antenatal blood-pressure checks.' },
      { q: 'What should I do if my baby moves less?', a: 'In later pregnancy, reduced movements can be important — contact your maternity unit the same day to be checked; do not wait.' },
    ],
    related: [['diseases/pregnancy-care', 'Pregnancy care'], ['diseases/ectopic-pregnancy', 'Ectopic pregnancy'], ['diseases/gestational-diabetes', 'Gestational diabetes'], ['womens-health/morning-sickness-remedies', 'Morning sickness']],
  },
  {
    slug: 'womens-health/what-to-eat-in-pregnancy',
    name: 'What to Eat in Pregnancy',
    title: 'What to Eat in Pregnancy: Foods & Supplements | MedDroid',
    desc: 'Pregnancy diet — foods to eat, foods and drinks to avoid, key supplements (folic acid, iron), and safe weight gain. Educational, not a diagnosis.',
    h1: 'What to eat in pregnancy',
    lede: 'A balanced diet plus the right supplements gives your baby the best start. You do not need to “eat for two” — quality matters more than quantity.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about pregnancy diet',
    featTitle: 'Eat well & supplement',
    features: [
      'Folic acid (ideally before and in the first 12 weeks) and iron as advised',
      'Plenty of fruit, vegetables, wholegrains and pulses',
      'Protein: dal, eggs, dairy, lean meat/fish (well cooked)',
      'Calcium and vitamin D for bones',
      'Stay hydrated; small frequent meals help nausea',
    ],
    warnings: [
      'Avoid alcohol and smoking completely',
      'Avoid raw/undercooked eggs and meat, unpasteurised dairy, and high-mercury fish',
      'Limit caffeine; wash fruits and vegetables well',
      'Very restricted eating or big unintended weight loss — see a doctor',
    ],
    noteTitle: 'Folic acid is essential.',
    note: 'Folic acid before and in early pregnancy greatly lowers the risk of neural-tube defects. Follow your doctor’s advice on supplements. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What supplements should I take in pregnancy?', a: 'Folic acid (especially the first 12 weeks) and usually iron, plus calcium and vitamin D as advised. Your doctor tailors this to you.' },
      { q: 'What foods should I avoid in pregnancy?', a: 'Alcohol, raw/undercooked eggs and meat, unpasteurised dairy, high-mercury fish, and too much caffeine. Wash produce well and cook food thoroughly.' },
      { q: 'Do I need to eat for two?', a: 'No — your calorie needs rise only modestly, mostly later in pregnancy. Focus on nutritious, balanced meals rather than eating much more.' },
    ],
    related: [['diseases/pregnancy-care', 'Pregnancy care'], ['medicines/folic-acid', 'Folic acid'], ['medicines/iron-folic-acid', 'Iron & folic acid'], ['diseases/gestational-diabetes', 'Gestational diabetes']],
  },
  {
    slug: 'womens-health/trying-to-conceive-tips',
    name: 'Trying to Conceive: Tips',
    title: 'Trying to Conceive: How to Boost Your Chances | MedDroid',
    desc: 'Trying to get pregnant — timing intercourse to ovulation, healthy habits that help, and when to seek fertility help. Educational, not a diagnosis.',
    h1: 'Trying to conceive: tips that help',
    lede: 'Most couples conceive within a year of trying. Understanding your fertile window and looking after your health improves the odds — and it is worth knowing when to seek help.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about conceiving',
    featTitle: 'What improves your chances',
    features: [
      'Have sex regularly, especially in your fertile window (around ovulation)',
      'Track your cycle; ovulation is roughly mid-cycle',
      'Both partners: healthy weight, no smoking, limit alcohol',
      'Start folic acid before conceiving',
      'Manage conditions like PCOS, thyroid or diabetes',
    ],
    warnings: [
      'No pregnancy after 12 months of trying (or 6 months if over 35) — seek help',
      'Very irregular or absent periods',
      'Severe period pain or pain during sex (possible endometriosis)',
      'Known fertility risk factors — see a doctor sooner',
    ],
    noteTitle: 'Both partners matter.',
    note: 'Fertility involves both partners, and many causes are treatable. Start folic acid early and seek help at the right time. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'When am I most fertile?', a: 'Around ovulation, roughly the middle of your cycle. The few days before and the day of ovulation are the most fertile — regular sex across this window helps.' },
      { q: 'How long should we try before seeing a doctor?', a: 'See a doctor after about a year of regular unprotected sex without pregnancy — or after 6 months if you are over 35, or sooner if periods are very irregular.' },
      { q: 'What can improve fertility naturally?', a: 'A healthy weight, not smoking, limiting alcohol, managing stress and treating conditions like PCOS or thyroid problems all help both partners.' },
    ],
    related: [['diseases/female-infertility', 'Female infertility'], ['diseases/pcos', 'PCOS'], ['medicines/folic-acid', 'Folic acid'], ['medicines/clomiphene', 'Clomiphene']],
  },
  {
    slug: 'womens-health/white-discharge-causes',
    name: 'Vaginal Discharge: Normal or Not',
    title: 'Vaginal Discharge: Normal vs When to Worry | MedDroid',
    desc: 'Vaginal (white) discharge — what is normal, signs of infection like thrush or bacterial vaginosis, and when to see a doctor. Educational, not a diagnosis.',
    h1: 'Vaginal discharge: normal or not?',
    lede: 'Some clear or white discharge is normal and healthy, and it changes across your cycle. Certain changes — in colour, smell, itching or amount — can signal an infection that is easily treated.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about discharge',
    featTitle: 'What is usually normal',
    features: [
      'Clear or milky-white discharge that changes with your cycle',
      'More discharge around ovulation, in pregnancy, or with the pill',
      'No strong smell, itching or irritation',
      'A mild scent is normal',
    ],
    warnings: [
      'Thick white, itchy, “cottage-cheese” discharge (possible thrush)',
      'Greyish discharge with a fishy smell (possible bacterial vaginosis)',
      'Green/yellow, frothy or foul-smelling discharge (possible infection/STI)',
      'Discharge with pelvic pain, fever, or bleeding between periods',
    ],
    noteTitle: 'Most causes are easily treated.',
    note: 'Thrush, bacterial vaginosis and some STIs cause abnormal discharge and are simple to treat once identified. Avoid douching, which upsets the natural balance. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is white discharge normal?', a: 'Yes — clear or white discharge without itching or a strong smell is normal and changes across your cycle. It is the body’s way of keeping the vagina clean and healthy.' },
      { q: 'How do I know if discharge is an infection?', a: 'Itching, a strong or fishy smell, a change to thick white, grey, green or yellow, or discharge with pain or bleeding suggests an infection — see a doctor.' },
      { q: 'Should I use intimate washes or douching?', a: 'No — douching and harsh washes disturb the natural balance and can cause infections. Plain water for the outside is enough.' },
    ],
    related: [['diseases/vaginal-infections', 'Vaginal infections'], ['diseases/bacterial-vaginosis', 'Bacterial vaginosis'], ['medicines/clotrimazole', 'Clotrimazole'], ['medicines/fluconazole', 'Fluconazole']],
  },
  {
    slug: 'womens-health/uti-in-women',
    name: 'UTI in Women',
    title: 'UTI in Women: Symptoms, Relief & Prevention | MedDroid',
    desc: 'Urinary tract infection in women — burning urination and urgency, home relief, when antibiotics are needed, and how to prevent recurrences. Not a diagnosis.',
    h1: 'UTI in women',
    lede: 'Urinary tract infections are very common in women, causing burning, urgency and frequent urination. Most are easily treated, and simple habits help prevent them coming back.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about UTIs',
    featTitle: 'Symptoms & relief',
    features: [
      'Burning or stinging when passing urine',
      'Needing to go often and urgently, passing little',
      'Cloudy, strong-smelling urine or lower tummy discomfort',
      'Drink plenty of water; paracetamol for discomfort',
      'Antibiotics if a doctor confirms a bacterial UTI',
    ],
    warnings: [
      'Fever, back/flank pain, chills or vomiting (possible kidney infection — urgent)',
      'Blood in the urine',
      'Symptoms in pregnancy (needs prompt treatment)',
      'Frequent, recurring UTIs',
    ],
    noteTitle: 'Kidney infection needs prompt care.',
    note: 'A UTI that spreads to the kidney (fever, back pain, vomiting) needs urgent treatment. UTIs in pregnancy are always treated promptly. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I get rid of a UTI?', a: 'Drink plenty of fluids and use paracetamol for comfort; most bacterial UTIs need a short course of antibiotics from a doctor. Do not ignore fever or back pain.' },
      { q: 'How can I prevent UTIs?', a: 'Drink enough water, pass urine after sex, wipe front to back, and avoid holding urine for long. Some women benefit from other measures your doctor can advise.' },
      { q: 'When is a UTI serious?', a: 'Fever, back or side pain, chills or vomiting suggest the infection has reached the kidney and needs urgent treatment. UTIs in pregnancy also need prompt care.' },
    ],
    related: [['diseases/uti-in-women', 'UTI in women'], ['diseases/urinary-tract-infection', 'Urinary tract infection'], ['medicines/nitrofurantoin', 'Nitrofurantoin'], ['medicines/fosfomycin', 'Fosfomycin']],
  },
  {
    slug: 'womens-health/breast-lump-when-to-worry',
    name: 'Breast Lump: When to Worry',
    title: 'Breast Lump: When to Worry & What to Do | MedDroid',
    desc: 'Breast lumps — most are not cancer, the changes that need a doctor, how to check your breasts, and what happens next. Educational, not a diagnosis.',
    h1: 'Breast lump: when to worry',
    lede: 'Most breast lumps are not cancer — many are cysts or normal changes. But any new lump or change should be checked, because when breast cancer is found early it is very treatable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about a breast lump',
    featTitle: 'Get any of these checked',
    features: [
      'A new lump or thickening in the breast or armpit',
      'A change in size, shape or skin (dimpling, puckering)',
      'Nipple changes: turning inward, a rash, or discharge (especially bloody)',
      'Ongoing breast pain in one spot',
      'Know how your breasts normally look and feel',
    ],
    warnings: [
      'A hard, fixed, painless lump',
      'Skin dimpling, an “orange-peel” texture, or nipple pulling inward',
      'Bloody nipple discharge',
      'A lump in the armpit',
    ],
    noteTitle: 'Most lumps are benign — but always check.',
    note: 'Do not panic, but do not delay: a doctor can examine you and arrange a scan (ultrasound/mammogram) if needed. Early detection saves lives. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Are most breast lumps cancer?', a: 'No — most are benign, such as cysts or fibroadenomas, especially in younger women. But every new lump should be checked to be sure.' },
      { q: 'How should I check my breasts?', a: 'Get to know their normal look and feel, and check regularly for new lumps or changes in shape, skin or the nipple. Report anything new to a doctor.' },
      { q: 'What happens after I report a lump?', a: 'A doctor examines you and may arrange an ultrasound or mammogram, and sometimes a needle test, to find out what it is — most turn out to be harmless.' },
    ],
    related: [['diseases/breast-lump', 'Breast lump'], ['diseases/breast-cancer', 'Breast cancer'], ['blood-tests/mammography', 'Mammography'], ['medicines/tamoxifen', 'Tamoxifen']],
  },
  {
    slug: 'womens-health/menopause-symptoms-and-relief',
    name: 'Menopause Symptoms & Relief',
    title: 'Menopause: Symptoms & How to Get Relief | MedDroid',
    desc: 'Menopause — the common symptoms (hot flushes, sleep, mood, dryness), what helps including HRT, and long-term health. Educational, not a diagnosis.',
    h1: 'Menopause: symptoms and relief',
    lede: 'Menopause is a natural stage, usually around the late 40s to early 50s, when periods stop. Symptoms vary widely — and there are effective ways to feel better, from lifestyle to hormone therapy.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about menopause',
    featTitle: 'What helps',
    features: [
      'Layered clothing and a cool environment for hot flushes',
      'Regular exercise, good sleep habits and stress management',
      'Vaginal moisturisers/lubricants for dryness',
      'Hormone replacement therapy (HRT) for many women, if suitable',
      'Calcium, vitamin D and weight-bearing exercise for bones',
    ],
    warnings: [
      'Any bleeding after menopause (needs urgent review)',
      'Very heavy or irregular bleeding in perimenopause',
      'Low mood or anxiety that affects daily life',
      'New breast lumps or changes',
    ],
    noteTitle: 'Bleeding after menopause always needs checking.',
    note: 'Postmenopausal bleeding must be reviewed by a doctor. HRT helps many women and its benefits/risks depend on your age and health. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What are the main symptoms of menopause?', a: 'Hot flushes and night sweats, irregular then stopping periods, sleep and mood changes, vaginal dryness, and reduced libido are common. They vary a lot between women.' },
      { q: 'Is HRT safe?', a: 'For many women, especially near the start of menopause, the benefits outweigh the risks. It is individual, so your doctor helps weigh it up.' },
      { q: 'Is bleeding after menopause normal?', a: 'No — any bleeding after periods have stopped for a year needs to be checked promptly by a doctor.' },
    ],
    related: [['diseases/menopause', 'Menopause'], ['medicines/estradiol-hrt', 'Estradiol (HRT)'], ['diseases/osteoporosis', 'Osteoporosis'], ['medicines/calcium-supplement', 'Calcium supplement']],
  },
  {
    slug: 'womens-health/contraception-options',
    name: 'Contraception Options',
    title: 'Contraception Options: Which Birth Control Is Right? | MedDroid',
    desc: 'Birth control options compared — pills, IUDs, implants, injections, condoms and more — how well each works and how to choose. Educational, not a diagnosis.',
    h1: 'Contraception options: choosing what suits you',
    lede: 'There are many reliable contraception methods, and the “best” one depends on your health, plans and preferences. Here is a simple overview to help you talk to your doctor.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about contraception',
    featTitle: 'Main methods',
    features: [
      'Long-acting (most effective): IUD (copper or hormonal), implant',
      'Hormonal: the combined pill, mini-pill, injection',
      'Barrier: condoms (also protect against STIs)',
      'Permanent: sterilisation (for those who have completed their family)',
      'Emergency contraception for after unprotected sex',
    ],
    warnings: [
      'Combined (oestrogen) methods are avoided with certain clot, migraine or smoking risks',
      'Only condoms protect against sexually transmitted infections',
      'Leg pain/swelling, breathlessness or severe headache on hormonal methods — seek care',
      'Missed pills can reduce protection — know the rules',
    ],
    noteTitle: 'Match the method to you.',
    note: 'Effectiveness, side effects and suitability differ by method and by person. A doctor helps you choose safely. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the most effective contraception?', a: 'Long-acting methods — the IUD and the implant — are the most effective because they do not rely on remembering a daily pill.' },
      { q: 'Does the pill protect against STIs?', a: 'No — only condoms protect against sexually transmitted infections. Many people use condoms alongside another method.' },
      { q: 'Which contraception is best for me?', a: 'It depends on your health, whether you want children later, and your preferences. A doctor can match a method to your situation safely.' },
    ],
    related: [['diseases/contraception-overview', 'Contraception overview'], ['medicines/combined-oral-contraceptive', 'Combined pill'], ['medicines/desogestrel', 'Mini-pill'], ['womens-health/emergency-contraception-guide', 'Emergency contraception']],
  },
  {
    slug: 'womens-health/emergency-contraception-guide',
    name: 'Emergency Contraception',
    title: 'Emergency Contraception: How the Morning-After Pill Works | MedDroid',
    desc: 'Emergency contraception — how the morning-after pill and copper IUD work, how soon to use them, and what to expect. Educational, not a diagnosis.',
    h1: 'Emergency contraception: what to know',
    lede: 'Emergency contraception can prevent pregnancy after unprotected sex or a contraceptive slip. It works best the sooner it is used — so do not wait.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about emergency contraception',
    featTitle: 'Your options',
    features: [
      'Levonorgestrel pill: works best within 72 hours (sooner is better)',
      'Ulipristal pill: effective up to 120 hours (5 days)',
      'Copper IUD: the most effective option, within 5 days (and ongoing contraception)',
      'Take the pill as soon as possible after unprotected sex',
      'It does not cause an abortion and does not affect future fertility',
    ],
    warnings: [
      'Severe lower tummy pain or a very late/abnormal next period (rule out pregnancy/ectopic)',
      'Vomiting within 2–3 hours of the pill (it may need repeating)',
      'It does not protect against STIs',
      'Repeated need for it means a regular method would be safer',
    ],
    noteTitle: 'Sooner is more effective.',
    note: 'Emergency contraception is not a regular method and is less effective than ongoing contraception. It does not end an existing pregnancy. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How soon should I take the morning-after pill?', a: 'As soon as possible — levonorgestrel works best within 72 hours, and ulipristal up to 120 hours. The copper IUD is the most effective and works up to 5 days.' },
      { q: 'Does emergency contraception cause abortion?', a: 'No — it mainly works by delaying ovulation and prevents pregnancy from starting. It does not end an established pregnancy.' },
      { q: 'Will it affect my future fertility?', a: 'No — it has no lasting effect on fertility. Your next period may come a little early or late.' },
    ],
    related: [['diseases/emergency-contraception', 'Emergency contraception'], ['medicines/levonorgestrel-ecp', 'Levonorgestrel (ECP)'], ['womens-health/contraception-options', 'Contraception options'], ['womens-health/when-to-take-pregnancy-test', 'When to take a pregnancy test']],
  },
  {
    slug: 'womens-health/breastfeeding-tips',
    name: 'Breastfeeding Tips & Problems',
    title: 'Breastfeeding: Tips, Latch & Common Problems | MedDroid',
    desc: 'Breastfeeding help — getting a good latch, boosting supply, easing sore nipples and blocked ducts, and when to see a doctor. Educational, not a diagnosis.',
    h1: 'Breastfeeding: tips and common problems',
    lede: 'Breastfeeding is natural but not always easy at first. A good latch solves most early problems, and support makes a big difference — so ask for help early rather than struggling alone.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about breastfeeding',
    featTitle: 'Tips that help',
    features: [
      'Aim for a deep latch (baby takes a big mouthful, not just the nipple)',
      'Feed on demand, day and night, in the early weeks',
      'Frequent feeding and skin-to-skin build supply',
      'Vary positions to empty the breast and prevent blockages',
      'Look after yourself: fluids, food and rest',
    ],
    warnings: [
      'A red, hot, painful area of breast with fever/flu-like feeling (possible mastitis)',
      'Cracked, bleeding nipples not improving with a better latch',
      'Baby not gaining weight, few wet nappies, or very sleepy to feed',
      'Signs of jaundice or dehydration in the baby',
    ],
    noteTitle: 'Ask for help early.',
    note: 'A lactation counsellor or doctor can fix most latch and supply problems. Mastitis and a poorly feeding baby need prompt care. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'How do I know my baby is getting enough milk?', a: 'Regular wet and dirty nappies, steady weight gain, and a settled baby after feeds are good signs. Your doctor tracks weight on a growth chart.' },
      { q: 'How can I increase my milk supply?', a: 'Feed frequently and on demand, ensure a good latch, empty the breast, and rest and eat well. Supply usually responds to more feeding/expressing.' },
      { q: 'What is mastitis?', a: 'A red, hot, painful area of breast with fever and feeling unwell. Keep feeding, use warmth and see a doctor promptly — it may need antibiotics.' },
    ],
    related: [['child-health/starting-solids-for-babies', 'Starting solids'], ['child-health/normal-baby-weight-by-age', 'Baby weight by age'], ['diseases/postpartum-depression', 'Postpartum depression'], ['child-health/newborn-jaundice-when-to-worry', 'Newborn jaundice']],
  },
  {
    slug: 'womens-health/postpartum-depression-signs',
    name: 'Postpartum Depression Signs',
    title: 'Postpartum Depression: Signs & Getting Help | MedDroid',
    desc: 'Postpartum depression — how it differs from “baby blues”, the signs to watch for, and how to get help. You are not alone. Educational, not a diagnosis.',
    h1: 'Postpartum depression: signs and help',
    lede: 'Feeling low, tearful or overwhelmed after having a baby is common, and short-lived “baby blues” pass in a couple of weeks. When low mood lasts longer or is severe, it may be postpartum depression — which is common and treatable.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about postpartum mood',
    featTitle: 'Signs to watch for',
    features: [
      'Persistent low mood, tearfulness or emptiness beyond 2 weeks',
      'Loss of interest or pleasure, and constant tiredness',
      'Feeling unable to cope or bond with the baby',
      'Sleep and appetite changes beyond normal newborn disruption',
      'Anxiety, guilt or feelings of worthlessness',
    ],
    warnings: [
      'Thoughts of harming yourself or the baby — seek help immediately',
      'Being unable to care for yourself or your baby',
      'Frightening thoughts, confusion or seeing/hearing things (urgent)',
      'Symptoms that are severe or getting worse',
    ],
    noteTitle: 'It is common, and help works.',
    note: 'Postpartum depression is not a weakness or your fault, and it responds well to support, talking therapy and, if needed, medicine. If you have thoughts of self-harm, seek help now. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'What is the difference between baby blues and postpartum depression?', a: 'Baby blues are mild and pass within about two weeks. Postpartum depression lasts longer, is more intense, and affects your ability to function — and needs support.' },
      { q: 'How is postpartum depression treated?', a: 'With support, talking therapy (counselling), and antidepressants if needed — many of which are compatible with breastfeeding. Recovery is the norm with help.' },
      { q: 'When should I get urgent help?', a: 'If you have any thoughts of harming yourself or your baby, or frightening thoughts or confusion, seek help immediately — contact a doctor or emergency services.' },
    ],
    related: [['diseases/postpartum-depression', 'Postpartum depression'], ['diseases/depression', 'Depression'], ['medicines/sertraline', 'Sertraline'], ['womens-health/breastfeeding-tips', 'Breastfeeding tips']],
  },
  {
    slug: 'womens-health/pcod-vs-pcos',
    name: 'PCOD vs PCOS',
    title: 'PCOD vs PCOS: What’s the Difference? | MedDroid',
    desc: 'PCOD vs PCOS — how the two terms differ, symptoms they share, effects on periods and fertility, and how each is managed. Educational, not a diagnosis.',
    h1: 'PCOD vs PCOS: what’s the difference?',
    lede: 'The terms PCOD and PCOS are often used interchangeably in India, but they are not quite the same. Both involve the ovaries and hormones, and both are very manageable with the right approach.',
    ctaShort: 'Ask MedDroid', ctaLong: 'Ask MedDroid about PCOD and PCOS',
    featTitle: 'The key differences',
    features: [
      'PCOD: ovaries release many immature eggs; often milder, very common',
      'PCOS: a hormonal/metabolic disorder; usually more significant',
      'Both can cause irregular periods, acne, extra hair and weight gain',
      'PCOS more often affects fertility and insulin/blood sugar',
      'Both improve with weight management and healthy lifestyle',
    ],
    warnings: [
      'Very irregular or absent periods for long stretches',
      'Difficulty conceiving',
      'Signs of high blood sugar (excess thirst, passing lots of urine)',
      'Rapid weight gain or severe acne/hair growth',
    ],
    noteTitle: 'Both are manageable.',
    note: 'Whatever the label, the approach is similar: lifestyle first, plus medicines for periods, skin or fertility as needed. MedDroid gives general information, not a diagnosis.',
    faqs: [
      { q: 'Is PCOD more serious than PCOS?', a: 'Generally PCOS is considered the more significant hormonal/metabolic condition, while PCOD is often milder. But both need attention and both are manageable.' },
      { q: 'Can PCOD/PCOS be cured?', a: 'Neither is “cured”, but both are well controlled with lifestyle changes and, where needed, medicines — restoring periods and improving symptoms and fertility.' },
      { q: 'Do both affect pregnancy?', a: 'Both can affect ovulation, but many women with either conceive, sometimes with help such as weight management and ovulation-inducing medicines.' },
    ],
    related: [['diseases/pcod', 'PCOD'], ['diseases/pcos', 'PCOS'], ['womens-health/pcos-management', 'Managing PCOS'], ['womens-health/irregular-periods-causes', 'Irregular periods']],
  },
];
